### ISSUE TITLE
Setting ENVIRONMENT configuration via Environment Variable

### ISSUE THREAD

**Issue by roberto-butti** [bcit-ci/CodeIgniter#1112]
Setting ENVIRONMENT configuration via Environment Variable CI_ENV (in .htacess with SetEnv)

In your .htaccess:
SetEnv CI_ENV development

In your index.php
    $env = getenv("CI_ENV");
    $env_default = "development";
    if ($env === false) { $env = $env_default; }
    define('ENVIRONMENT', $env);

**Comment by apps25** [comment]
Hi All,
I am new to PHP I am facing an issue. I have a constant file where I have kept my constant file.
