### ISSUE TITLE
Fatal error: Call to a member function view() on a non-object

### ISSUE THREAD

**Issue by ken-master** [bcit-ci/CodeIgniter#1248]
I am receiving error when declaring my view which is: $this->load->view( 'index/index' );

but when i declare the parent::__construct(); on the current controller constructor the error is gone.

the code:
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Index extends CI_Controller {

```
function __construct(){

           //if i remove this parent::__construct(); the error is gone
    parent::__construct();
}

public function index(){

    $this->load->view( 'index/index' );
}
```

}

i don't know if this is a really a bug, i came from a 1.7 version and i know that i haven't encounter this FATAL error with or without declaring the parent constructor. this is my first time using 2.x version.

Thanks and more power to CI.

**Comment by lalithsagar03** [comment]
Severity: Notice

Message: Undefined property: REST_Controller::$load

i have the following error can anyone help me to resolve that one?
