### ISSUE TITLE
Email Subject Unicode Support with B encoding instead of Q

### ISSUE THREAD

**Issue by wiiiimm** [bcit-ci/CodeIgniter#1253]
Right now, the default Email library uses Q encode (_prep_q_encoding) to encode email subjects.
I find that while working in most email client, Apple's Mail and iOS mail client have problem rendering some characters like => (預繳提前30日通知) (Traditional Chinese, UTF8).
for "預繳提前30日通知" the email client in OS X shows the subject as "=e9=a0=90=e7=b9=b3=e6=8f=90=e5=89=8d30=e6=97=a5=e9=80=9a=e7=9f=a5" and in RAW "Subject: =?utf-8?Q?=e9=a0=90=e7=b9=b3=e6=8f=90=e5=89=8d30=e6=97=a5=e9=80=9a=e7=9f?="
Changing to B encoding seems to solve this problem.

**Comment by petrovaliev95** [comment]
This works for me. Thank you!
