### ISSUE TITLE
global_xss_filtering bug

### ISSUE THREAD

**Issue by akbortoli** [bcit-ci/CodeIgniter#1261]
Line 285 - system/core/Security.php - $str = $this->_validate_entities($str);

Append a ";" to the end of the string, given string "$98dubrucHa7a&EC" becomes "$98dubrucHa7a&EC;", was checking the password it was not matching. The cause most be the &EC as it's not a valid entity but should be able to have invalid entities in a string.

**Comment by bigprof** [comment]
Could this be a fix?
`$str = preg_replace('#(&\#[0-9a-z]{2,})([\x00-\x20])*;?#i', "\\1;\\2", $str);`
