### ISSUE TITLE
db->data_cache not (correctly) updated on drop_table / create_table

### ISSUE THREAD

**Issue by matthias-001** [bcit-ci/CodeIgniter#1264]
table_exists fails due to data_cache not being correctly updated on drop_table / create_table
issue first occured when testing a model (CI internal test class)

e.g. creating multiple tables, dropping them again und re-creating them which resulted in table_exists giving incorrect results

see also:
http://codeigniter.com/forums/viewthread/179460/#996089

kind regards,
matthias

**Comment by danielrhodeswarp** [comment]
create_table() in 3.1.2 seems to have dropped this fix??!?
