### ISSUE TITLE
num_rows() returns -1 when using ODBC

### ISSUE THREAD

**Issue by bitbucket-import** [bcit-ci/CodeIgniter#129]
When querying a MS Access database using the odbc driver, the num_rows() method always returns -1 even when there are rows returned.  Discussed on the forum: http://codeigniter.com/forums/viewthread/186292/

-William

**Comment by theblack00** [comment]
Hello, Narfbg
Use your library and saved me.
I shot an error
Message: Declaration of CI_DB_odbc_result :: _ fetch_object () Should be Compatible with CI_DB_result :: _ fetch_object ($ class_name = 'stdClass')

Make a change in the line 191
_fetch_object protected function ($ class_name = 'stdClass')

and all ok

Thank you very much.
Sorry but the wording is translation google,

**Comment by mckaygerhard** [comment]
there's no ODBC rule that offers num rows niether rows affected so many odbc drivers will fails, with CI2 and with CI3 some odbc drivers have problems

best its to count all results (dangerous in big resultsets) in SQL database fits and later offerts to..
