### ISSUE TITLE
Application vs. System Testing 

### ISSUE THREAD

**Issue by jamierumbelow** [bcit-ci/CodeIgniter#1315]
This isn't so much of an issue but more of an open question as to where unit testing support is heading for CI3.0.

It's awesome that unit tests are now a part of CI core, and it's great that the branch has been merged in and everything's starting to look good and official. I'm excited.

As you'll all know, currently the tests are in `/tests`. While this is fine, that folder seems to only facilitate system tests. What about application tests? It would make sense to move the `/tests` directory into `/system/tests` and have an `/application/tests` directory with a sample test inside it.

Is there a framework in place for application tests? There'll need to be mocks setup, methods to override core bits of CI functionality etc.

Is there anything in there that I'm missing to allow for this yet? If not, want me to look into it?

**Comment by greenwizard88** [comment]
Anything that promotes more unit testing is good in my book.

I'm a fan of Application/tests and System/tests, if anyone cares.

**Comment by bgeesaman** [comment]
I have just been charged with refactoring a good chunk of a CI 2.2 codebase with ~47K loc `find . -name '*.php' | grep -v "third_party" | xargs wc -l` and zero tests.  I came across this thread in looking for the best method for integrating a unit testing framework so I can write tests to cover certain areas before I start refactoring safely. The built-in CI unit testing library is insufficient, and despite their best efforts, community implementations are rife with self-admitted "hacks" to get things working.

I find it extremely suspicious that the "core" is unit tested with PHPUnit, but extending that structure to the "application" space is considered undesirable and would go against the core tenets of CI to not "force" you into any methodology.  Picking a primary testing framework and making it usable for the application side in NO WAY means I have to actually write test files or even run them.  It doesn't force you into TDD or test-after-the-fact.  But what it *does* do is make sure that there is a common and supportable way to hook into the framework to run tests that other testing frameworks can leverage if one liked those instead.  As it is now, that interface doesn't exist.  Any testing framework I shoe-horn in can't be guaranteed any sort of compatibility going forward.  That is why I believe the decision to refrain from making the built-in CI test framework full featured (fixtures, mocks, environment handling, web drivers, etc) or even providing a somewhat legitimate integration path for external testing frameworks is so short-sighted.

This example is one of the main reasons frameworks with the tenets of "make it easier to create and refactor code" are thriving and frameworks that haven't adopted critical features into their core approach are on life support.  I'm spending days/weeks trying to bolt something as fundamental as testing on to the codebase after the fact, but all I can think of is "What would it take to rewrite this all in ____ framework?  It's probably less effort and a better long-term decision."

**Comment by kenjis** [comment]
I wrote a bridge tool called *ci-phpunit-test* for CodeIgniter 3.0 application testing.
http://kenjis.github.io/ci-phpunit-test/

And I sum up request list for CI 3.x, just for your information.
https://github.com/kenjis/ci-phpunit-test/blob/master/docs/RequestsToCodeIgniter.md

+1 for `system/tests` and `application/tests`

**Comment by jagandecapri** [comment]
@kenjis I am using the bridge tool that you wrote. Pretty neat. It will be nice if it is included in CI core and further improved. :+1:

**Comment by kenjis** [comment]
@jagandecapri Thanks!

**Comment by kfern-github** [comment]
@kenjis +1. Works fine, well documented and add a good tool for developers

**Comment by feryardiant** [comment]
+1 for @kenjis, actually I'm not using your bridge but I do aggreed that Codeigniter should be testable.

> Writing tests for CodeIgniter 3.0 application has troublesome. Because CodeIgniter has some code which is untestable or difficult to test.

I'm using [this one](https://github.com/fmalk/codeigniter-phpunit) and had same problem.

**Comment by kenjis** [comment]
@kfern-github Thanks!

@feryardiant all the problems stated in the request list have been solved (or there is workaround) in my *ci-phpunit-test*.

**Comment by feryardiant** [comment]
@kenjis great!
