### ISSUE TITLE
$query->result() memory exhausted

### ISSUE THREAD

**Issue by juanitomint** [bcit-ci/CodeIgniter#1351]
While geting large results (4k rows) i get  from xdebug:

( ! ) Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 38 bytes) in /home/ci2/public_html/system/database/drivers/mysql/mysql_result.php on line 167
Call Stack
# Time    Memory  Function    Location

1   0.0005  347340  {main}( )   ../index.php:0
2   0.0016  410180  require_once( '/home/ci2/public_html/system/core/CodeIgniter.php' ) ../index.php:202
3   0.0349  2320000 call_user_func_array ( )    ../CodeIgniter.php:359
4   0.0349  2320072 Testdb->run_test( ) ../CodeIgniter.php:359
5   0.3494  2418348 CI_DB_result->result( ) ../testdb.php:18
6   0.3494  2418424 CI_DB_result->result_object( )  ../DB_result.php:51
7   10.8952 134194960   CI_DB_mysql_result->_fetch_object( )    ../DB_result.php:119
8   10.8952 134195004   mysql_fetch_object ( )  ../mysql_result.php:167

The problem is that DB_result.php is trying to add all rows to the object it returns, exhausting memory

I provide a controller to test this out:

<?php
//----file name: /controllers/testdb.php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Testdb extends CI_Controller {

```
public function index() {
    echo "<h1>DB Memmore Exhaustion TEST (128Mb)</h1>";
    echo "<ol>";
    echo "<li><a href='/testdb/create_db'>Create a table with 4k records</a></li>";
    echo "<li><a href='/testdb/run_test'>Run test</a></li>";
    echo "</ol>";
}
public function run_test() {
    $query=$this->db->get('ci_mem_test');

    foreach($query->result() as $row){//<---- This line will exhaust 128Mb

    }
    echo "yes!";
}
public function create_db() {
    //---load dbforge
    set_time_limit(3600);
    $this->load->dbforge();

    $this->dbforge->drop_table('ci_mem_test');
    $this->dbforge->add_field('id');
    $this->dbforge->create_table('ci_mem_test');
    $object=new stdClass();
    $object->id=0;
    for($i=1;$i<=400000;$i++){
        $this->db->insert('ci_mem_test',$object);
    }
    //$this->output->enable_profiler(TRUE);
}
```

}

/\* End of file testdb.php _/
/_ Location: ./application/controllers/testdb.php */

**Comment by Mr-Faizan** [comment]
Thank you so much @narfbg your solution perfectly works for me. I am facing memory exhaust issue and i am searching from one week. Finally this works for me. 
$this->db->save_queries = FALSE;
Although you gave this solution in 2012 but still this is helpful :)

**Comment by laratutoteam** [comment]
code get this **get this easy error solving** https://laratuto.com/solved-out-of-memory-error-in-query-sybase_connect/
