### ISSUE TITLE
EU "cookie law" compliance

### ISSUE THREAD

**Issue by alexbilbie** [bcit-ci/CodeIgniter#1375]
I've added a new branch called `feature/eu-cookie-law` (https://github.com/EllisLab/CodeIgniter/tree/feature/eu-cookie-law).

This branch makes the CI session library compliant with the EU "cookie law" which states that cookies should not be set on a user's computer unless they have given the [EU based] site permission to do so.

There is a new config variable called `$config['cookie_consent_required']`. When this is set to `TRUE` no cookies will be set when the session library is first loaded (if a session cookie doesn't exist already), and any existing session cookies will be destroyed.

Cookies now won't be set until the user has given explicit consent. This can be controlled using two new functions in the cookie helper - `cookie_consent_granted()` and `cookie_consent_withdrawn()`.

What do people think?

>_Note this commit only changes the automated behaviour of the session library, cookies can still be set manually using the cookie helper_

**Comment by narfbg** [comment]
Fixed by #3073.
