### ISSUE TITLE
Email subject line starts with “?utf-8?Q?”

### ISSUE THREAD

**Issue by mga242** [bcit-ci/CodeIgniter#1409]
Sending email using CI the subject line starts with “?utf-8?Q?”. The subject line is not over 75 characters
The following post suggestions don't solve the problem:

http://codeigniter.com/forums/viewthread/154493/

http://stackoverflow.com/questions/8350865/malformed-email-subject-header-when-subject-75-chars-using-codeigniter-email-l

I  copied the email class into my application/libraries and then made the edits suggested here:

http://codeigniter.com/forums/viewthread/119946/

Works correctly now…

**Comment by jitendraF5buddy** [comment]
This code are working properly  you need to change "system/libraries/Email.php"

public function subject($subject)
	{
		/*$subject = $this->_prep_q_encoding($subject);
		$this->_set_header('Subject', $subject);
		return $this;*/
		$subject = '=?UTF-8?B?'.base64_encode($subject).'?=';
	       $this->_set_header('Subject', $subject);
	        return $this;
	}

**Comment by somsgod** [comment]
Was facing same issue , the solution suggested here solved the problem.
https://forum.codeigniter.com/archive/index.php?thread-54634.html
