### ISSUE TITLE
cannot upload with php5.2 

### ISSUE THREAD

**Issue by ve3** [bcit-ci/CodeIgniter#1494]
This file 'system/libraries/Upload.php' in this method "_file_mime_type" 

if web server using php 5.2, the mime_content_type will be used.
it return wrong value for mime type in  .zip, .others

if i comment mime_content_type out, the code works fine.

please do not use mime_content_type because it cannot detect other file except image and text files.

... and more error.
## 

Severity: Warning
Message: finfo_open() [function.finfo-open]: Failed to load magic database at '/usr/share/misc/magic'.
Filename: libraries/Upload.php
Line Number: 1035
## 

Severity: Warning
Message: escapeshellarg() has been disabled for security reasons
Filename: libraries/Upload.php
Line Number: 1066

---

server info.
Codeigniter 2.1.1
php 5.2.17
Linux server

**Comment by abhishekkumar7aug** [comment]
Thank you .......!
