### ISSUE TITLE
Rapid requests during session updates trigger unexpected session destruction

### ISSUE THREAD

**Issue by bitbucket-import** [bcit-ci/CodeIgniter#154]
=== Issue ===
When using the sessions library and the following conditions exist:
- $config['sess_use_database'] = true;
- The period specified in $config['sess_time_to_update'] has expired

It is possible to inadvertently trigger destruction of the session by performing two requests at the same time.  An example of a scenario that easily triggers this error is a page which initiates two or more AJAX requests at the same time.

=== Expected Behavior ===
The CodeIgniter sessions library should not inadvertantly destroy sessions.

=== Cause of Issue ===
This is what I believe to be occurring.

Two requests are made at the same time, causing them to submit the same cookie data.

When the server receives the request, the session library looks for the session matching the ID submitted on the cookie. (Session.php:192)

The first request finds the session record and updates it since sess_time_to_update has expired. (Session.php:377)

The second request still has the old session id, and fails to find the newly updated database record.  This then triggers a sess_destroy. (Session.php:212)

=== To Replicate ===

In config.php:
{{{
// Reduce the amount of time we have to wait to see the bug to 5 seconds.
$config['sess_time_to_update']  = 5;
}}}

Create controller session_error_demo.php:
{{{
<?php
class Session_error_demo extends Controller {
    function initialize () {
        $this->session->set_userdata('session_alive', 'Hi world!');
        echo 'Session initialized.';
    }

```
function test() {
    if ($this->session->userdata('session_alive')) {
        echo 'Session is alive.';
    } else {
        echo 'Session is dead.';
    }
}

function reset() {
    $this->session->sess_destroy();
    echo 'Session reset.';
}
```

}
?>
}}}

Perform the following tasks:
# Call reset() to ensure we start on a clean slate.
# Call initialize() to seed a session value.
# Wait 5 seconds so that the session will be forced to update on next request.
# Call test() twice in rapid succession, so that both requests will be sent before either is fully processed.  I used jQuery & Firebug to submit these requests using $.get().
# View the responses.  The first will report that the session is alive, but the second and all subsequent requests will report that it is dead.

=== Versions Affected ===
This issue exists back in my version on 1.7.2.  I haven't verified that this still exists in 2.0.2, but it appears that the buggy code remains intact.

**Comment by StefanLex** [comment]
Try to use MyISAM over InnoDB for session table.

**Comment by CodeBrauer** [comment]
@StefanLex , thanks for that tip. I set the table now in MyISAM - maybe that will do the trick.

**Comment by ahmed-mahdi-pt** [comment]
I'm using CI (2.1.3) which has this issue, and using database sessions.
I've solved the issue.
In the function sess_update(), instead of updating the session_id with new one, I insert the new session as new record, and the old one will expire and be deleted by garbage collection function _sess_gc().
So you need to do the following:
1. Comment out the below lines or remove them (lines 378-384):

```
    $cookie_data = array();
    foreach (array('session_id','ip_address','user_agent','last_activity') as $val)
    {
        $cookie_data[$val] = $this->userdata[$val];
    }
    
    $this->CI->db->query($this->CI->db->update_string($this->sess_table_name, array('last_activity' => $this->now, 'session_id' => $new_sessid), array('session_id' => $old_sessid)));
```

2. Replace them with the following:

```
    $custom_data = $this->userdata;
    $cookie_data = array();
    foreach (array('session_id','ip_address','user_agent','last_activity') as $val)
    {
            unset($custom_data[$val]);
            $cookie_data[$val] = $this->userdata[$val];
    }

    if (count($custom_data) === 0)
    {
            $custom_data = '';
    }
    else
    {
            $custom_data = $this->_serialize($custom_data);
    }

    $this->CI->db->query($this->CI->db->insert_string($this->sess_table_name, array('last_activity' => $this->now, 'session_id' => $new_sessid, 'ip_address' => $this->CI->input->ip_address(), 'user_agent' => substr($this->CI->input->user_agent(), 0, 120), 'user_data' => $custom_data)));
```

**Comment by uchida-nunet** [comment]
@ahmed-mahdi-pt 

Thanks. It is useful information for me.  You are my hero.
