### ISSUE TITLE
Warning in postgre_driver.php

### ISSUE THREAD

**Issue by rwillert** [bcit-ci/CodeIgniter#1583]
I get following message with Postgre insert_id

A PHP Error was encountered
Severity: Warning
Message: Illegal string offset 'server'
Filename: postgre/postgre_driver.php
Line Number: 331

$v = $this->_version();
$v = $v['server'];

function _version()
{
    return "SELECT version() AS ver";
}

**Comment by rajitha-bandara** [comment]
I'm still getting the warning
 Illegal string offset 'server'
in XAMPP 1.8.1, PostgreSQL 9.0

**Comment by KonstantinasA** [comment]
Thanks a lot, works for me :)
