### ISSUE TITLE
use of namespace

### ISSUE THREAD

**Issue by iamfarhad** [bcit-ci/CodeIgniter#1600]
i think codeigniter use of namespace can help to be powerfull

**Comment by ganl** [comment]
model or libraries？

**Comment by jim-parry** [comment]
@gani This is a six-year old closed thread, and commenting here makes no sense.

If you are looking for namespace support, the current version of CI, 3.1.9, does ... https://github.com/bcit-ci/CodeIgniter#server-requirements
Or you might want to check out the upcoming https://github.com/bcit-ci/CodeIgniter4

Either way, asking on the forum is the proper way to ask support questions!
