### ISSUE TITLE
Warning mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given

### ISSUE THREAD

**Issue by vjranjithp7** [bcit-ci/CodeIgniter#1614]
HI im getting a Warning  --> mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given /server/web/system/database/drivers/mysqli/mysqli_result.php 37 when ever i calling to database the warning message is showing. I am using mysqli driver for codeigniter. The mostly warning message show while calling selection SP

This is what written on line 37 of 
function num_rows() {
        return @mysqli_num_rows ( $this->result_id );
    }

Thanks in advance.

**Comment by narfbg** [comment]
Sorry for anyone who receives a notification from this ...

Just referencing this as a duplicate of #495.
