### ISSUE TITLE
add text/plain in the csv array in the mimes.php file

### ISSUE THREAD

**Issue by kanhaic** [bcit-ci/CodeIgniter#1644]
when trying to upload a csv file using CI file uploader class we get an error that the file type you are trying to upload is not allowed. 

``` php
$config['upload_path'] = "./uploads/";
$config['allowed_types'] = 'csv|txt';
$config['overwrite'] = TRUE;
$this->load->library('upload', $config);
$this->upload->do_upload('file');
```

http://codeigniter.com/forums/viewthread/204725/P15/#1019166

---

I did some debugging and found that in the is_allowed_filetype function in line 624 for a csv file the $this->file_type returns text/plain where as when I check in the $_FILES[“file”][“type”] it returns text/csv

I added the text/plain in the csv array in the application/config/mime.php file and it started working,

There are two possible solutions 
1. Find out why there is this difference in these two and fix it (this feels the correct way to solve this)
2. just add text/plain in the csv array in mimes.php file (this seems the easy way, not sure if this is correct).

I could file a bug and suggest that we should add the text/plain in the csv array anyway in the next build.

Kanhai Chhgani

**Comment by cyberformed** [comment]
No `text/plain` doesn't fix the issue.
