### ISSUE TITLE
Cart - Is not possible to add item with 0 price

### ISSUE THREAD

**Issue by djpilgrim** [bcit-ci/CodeIgniter#1645]
It's important to add item with 0 price. Some products may be as a free product like a present with any other product. But zero price product must be in a order list.

I've tested in CodeIgniter 2.1.2

**Comment by naskam** [comment]
you can add this sign (-) as below
![screen shot 2015-03-28 at 11 44 20 am](https://cloud.githubusercontent.com/assets/2658530/6880384/eb6bab3e-d53f-11e4-8d02-e6889c6503dd.png)
