### ISSUE TITLE
xss_clean adds semicolon to anything with an &

### ISSUE THREAD

**Issue by Raffy6250** [bcit-ci/CodeIgniter#1674]
I’ve noticed that the xss_clean function seems to add a semi-colon to any string that contains an ampersand. 
For example, if someone writes “me&you” in a textarea and I run it through the xss_clean function, it will return “me&you;”.

Regards.

**Comment by bigprof** [comment]
Could this be a fix?
$str = preg_replace('#(&\#[0-9a-z]{2,})([\x00-\x20])*;?#i', "\\1;\\2", $str);

**Comment by narfbg** [comment]
@bigprof This was 3 years ago ... If you tried the latest CI versions you'd see that it is already fixed.

**Comment by bigprof** [comment]
@narfbg  I was using this component as a stand-alone in a project rather than the entire CodeIgniter framework. Sorry for the misunderstanding.
