### ISSUE TITLE
Depricated warning when autoinit off in mysql driver

### ISSUE THREAD

**Issue by skione** [bcit-ci/CodeIgniter#1681]
A PHP Error was encountered

Severity: 8192
Message: mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() instead.
Filename: mysql/mysql_driver.php
Line Number: 319

I am manually connecting

**Comment by erikasf** [comment]
i'm using CI 3.0 and I regret to inform you that it hasn't changed anything . I still get this $this-Severity: 8192

Message: mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() instead.

Filename: mysql/mysql_driver.php

Line Number: 319

**Comment by skione** [comment]
Change to the mysqli driver
