### ISSUE TITLE
oci_fetch_assoc(): ORA-01002: fetch out of sequence

### ISSUE THREAD

**Issue by ylynfatt** [bcit-ci/CodeIgniter#1701]
I am getting a PHP Warning for a query I am using for an Oracle Database. It works fine when I run the SQL query in SQL Developer, however it gives the error when viewing the page in the browser (through PHP and CodeIgniter).

```
A PHP Error was encountered
Severity: Warning
Message: oci_fetch_assoc(): ORA-01002: fetch out of sequence
Filename: oci8/oci8_result.php
Line Number: 155
```

I checked the following thread on the Forums (http://codeigniter.com/forums/viewthread/208846/) and it seems one solution is to put the `@` character in front of `oci_fetch_assoc($id)` on **line 155** of the `oci8_result.php` file.

So the function would now be

``` php
/**
 * Result - associative array
 *
 * Returns the result set as an array
 *
 * @access  protected
 * @return  array
 */
protected function _fetch_assoc()
{
    $id = ($this->curs_id) ? $this->curs_id : $this->stmt_id;
    return @oci_fetch_assoc($id);
}
```

Not sure why this warning is being caused or what other solution there is.

As some added information. I am running my application on **Ubuntu 10.04.3 LTS** with **PHP 5.3.2-1ubuntu4.17** and the Oracle database is version **10g**.

**Comment by SrVinicius** [comment]
This solved my problem, jst tks
