### ISSUE TITLE
email class bug

### ISSUE THREAD

**Issue by pchmlrs** [bcit-ci/CodeIgniter#1735]
If use 263's Enterprise Mail System in CI Email Class(SMTP)
Don't send mail.

If user other Enterprise Mail System in CI Email Class(SMTP) 
or 
user other email class 
send mail is ok

Test Account
username:no-reply@eerong.com
password:no-reply
smtp service:smtpcom.263xmail.com

**Comment by cyberformed** [comment]
Changed, But does't help
