### ISSUE TITLE
$this->dbforge->add_key for Foreign Key

### ISSUE THREAD

**Issue by andreustimm** [bcit-ci/CodeIgniter#1762]
Still do not have this method? Why? I can create?

**Comment by rejoan** [comment]
Hi, 
I have created a method add_foreign_key() for adding foreign key in existing table in dbforge library. Its working nicely, tested. Would CI authority review it? Will I submit my code here?

Thanks

**Comment by EpicKris** [comment]
Will this be available in upcoming releases of CodeIgniter 3?

**Comment by rejoan** [comment]
should be. donno CI authority will considering it or not

**Comment by dillix** [comment]
Why AndrewPodner commits not accepted by CI Team?

**Comment by THEMBOCHARLES** [comment]
To add a foreign key to the schema do the following;
Add these methods in system/database/DB_forge.php

Declare on top after primary key 
public $foreign_keys = array();//for the foreign key

`/*** FOREIGN KEY****/

	public function add_foreign_key($key, $reference_table, $reference_column, $on_update = 'NO ACTION', $on_delete = 'NO ACTION')
	{
		if (empty($on_update))
		{
			$on_update = 'NO ACTION';
		}

		if (empty($on_delete))
		{
			$on_delete = 'NO ACTION';
		}

		$foreign_key = array(
			'key'              => $key,
			'reference_table'  => $reference_table,
			'reference_column' => $reference_column,
			'on_update'        => $on_update,
			'on_delete'        => $on_delete
		);

		$this->foreign_keys[] = $foreign_key;

		return $this;
	}

  public function add_foreign_key_to_table($table, $key, $reference_table, $reference_column, $on_update = 'CASCADE', $on_delete = 'CASCADE')
	{
		$this->add_foreign_key($key, $reference_table, $reference_column, $on_update, $on_delete);

		$sql = 'ALTER TABLE ' . $this->db->escape_identifiers($table) . ' ADD ' . $this->_process_foreign_keys($table,
				TRUE);

		$this->_reset_foreign();

		if ($this->db->query($sql) === FALSE)
		{
			return FALSE;
		}

		return TRUE;
	}



	protected function _process_foreign_keys($table, $first = FALSE)
	{
		$sql = '';

		foreach ($this->foreign_keys as $foreign_key)
		{
			if ( ! $first)
			{
				$sql .= ',';
			}

			$sql .= PHP_EOL . "\t" . 'CONSTRAINT '
			        . $this->db->escape_identifiers('fk__' . $table . '__' . $foreign_key['reference_table'])
			        . ' FOREIGN KEY (' . $this->db->escape_identifiers($foreign_key['key']) . ') REFERENCES '
			        . $this->db->escape_identifiers($foreign_key['reference_table'])
			        . ' (' . $this->db->escape_identifiers($foreign_key['reference_column']) . ')'
			        . ' ON UPDATE ' . $foreign_key['on_update']
			        . ' ON DELETE ' . $foreign_key['on_delete'];
		}

		return $sql;
	}

	protected function _reset_foreign()//altred by by thembo charles
 	{	 
		$this->fields = $this->keys = $this->primary_keys = $this->foreign_keys = array();
 	}`

//End here


In your model class use it like this

`<?php
  /**
  * 
  */
  class Person extends CI_Model
  { 
  	public function person_table()
  	{  	 
  		$this->load->dbforge();	 
  		$person_table_feilds=array(
  		 	'person_name'=>array(
  		 		'type'=>'varchar',
  		 		'constraint'=>255,
  		 		),
  		 	'phone_number'=>array(
  		 		'type'=>'varchar',
  		 		'constraint'=>30,
  		 		),
  		 	'person_id'=>array(
  		 		'type'=>'INT',
  		 		'unsigned'=>TRUE,
  		 		'constraint'=>10,
  		 		'auto_increament'=>TRUE
  		 		), 
        'address_id'=>array(
          'type'=>'INT',
          'constraint'=>10,
          'unsigned'=>TRUE,          
          ),
  		 	);
  		$this->dbforge->add_key('person_id',TRUE);
  		$this->dbforge->add_field($person_table_feilds);
      $this->dbforge->create_table('charles',TRUE);
  		return $this->dbforge->add_foreign_key_to_table('charles','address_id','address','id');

  	}

    public function person_address()
    {
        $this->load->dbforge(); 
        $address_table=array(
          'name'=>array(
            'type'=>'text',
            'constraint'=>20,
            ),
          'id'=>array(
            'type'=>'int',
            'constraint'=>10,
            'unsigned'=>TRUE,
            'auto_increament'=>TRUE
            ),      

          );
        $this->dbforge->add_key('id',TRUE);
        $this->dbforge->add_field($address_table);
        return $this->dbforge->create_table('address',TRUE);

    }
  }
?>`

![capture](https://cloud.githubusercontent.com/assets/23166142/19850846/cce2722c-9f6b-11e6-9d9b-269719f02fc7.PNG)

**Comment by ariandi22** [comment]
@dillix  i think they are not giving anything shit about this featured already, you can see on documentation page are **suck**
