### ISSUE TITLE
loading config file from library

### ISSUE THREAD

**Issue by mirzadelic** [bcit-ci/CodeIgniter#1772]
Hi,
i made new file in `/config/` folder `render.php` and have this content:

```
<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');


$config['test1']    = 'some text';
```

And i have library `Render.php` in `/libraries/` folder with this content:

```
<?php
class Render {

    protected $CI;

    public function __construct() {

        $this->CI =& get_instance();
        $this->CI->load->config('render');
    }

    function link() {

        return $this->config->item('test1');
    }

}
```

Now i get error:

> Message: Undefined property: Render::$config

that library is autoloaded, but config is not, becouse i will load it manualy from this library, why am i getting this error ?

**Comment by Abdulmanan0315** [comment]
make sure to use this in your class

    /**
     * Enables the use of CI super-global without having to define an extra variable.
     *
     * @param $var
     *
     * @return mixed
     */
    public function __get($var){
        return get_instance()->$var;
    }
