### ISSUE TITLE
Support for using regex in the $field parameter of Form_validation::set_rules().

### ISSUE THREAD

**Issue by andrewryno** [bcit-ci/CodeIgniter#1812]
For many projects, I've needed to validate forms which have a multi-dimensional array with a dynamic number of array rows.

For example:

```
Array
(
    [field1] => value1
    [field2] => Array
        (
            [1] => Array
                (
                    [subfield1] => subvalue1
                    [subfield2] => subvalue2
                )

            [2] => Array
                (
                    [subfield1] => subvalue1
                    [subfield2] => subvalue2
                )

        )

)
```

Where each array under `field2` is created dynamically through the use of JavaScript. Right now, my solution is to check if `$_POST['field2']` is set, and if so, count the elements and use a `for` loop to create a rule for each sub-field for that index.

```
if (isset($_POST['field2']))
{
    for ($i = 1; $i <= count($_POST['field2']); $i++)
    {
        $this->form_validation->set_rules('field2['.$i.'][subfield1]', 'Subfield 1', 'trim|required|xss_clean');
        $this->form_validation->set_rules('field2['.$i.'][subfield2]', 'Subfield 2', 'trim|required|xss_clean');
    }
}
```

What would be easier is to do something such as:

```
$this->form_validation->set_rules('field2[(\d+)][subfield1]', 'Subfield 1', 'trim|required');
$this->form_validation->set_rules('field2[(\d+)][subfield2]', 'Subfield 2', 'trim|required');
```

Or potentially just use `field2[][subfield1]` and it knows to check all arrays under the `field2` key without the need of regex.

Thoughts? This is a rather common occurrence in many of the apps we build that require an unlimited amount of rows of data (budget tables, custom meta fields, etc.).

**Comment by jspreddy** [comment]
bump, I could use this too...

**Comment by abude** [comment]
@andrewryno Do you have a live sample of code to test against ? Thanks!

**Comment by narfbg** [comment]
56c233fc4a455d33d2e679b59132b8a7a1cf1832 (#193) covers this in a very customizable way - after setting `is_array` as a rule for `field2`, you can apply a callback that validates the entire array.
