### ISSUE TITLE
Keyboard shortcuts in user guide

### ISSUE THREAD

**Issue by MetalMatze** [bcit-ci/CodeIgniter#1825]
Hey, I would really appreciate some keyboard shortcuts in the user guide.
For example 't' for the table of content and '?' for a overview of all shortcuts.

I don't want to always have to click on 'Table of contents'.
If someone is able to implement this with prototype, I'm not, I would really like it.

**Comment by narfbg** [comment]
I've kept this as a "call for contributions" kind of issue, but after 3 years it's obvious that nobody is interested in submitting a patch, so closing.
