### ISSUE TITLE
Native PHP function's boolean responses are ignored in Form_validation

### ISSUE THREAD

**Issue by bitbucket-import** [bcit-ci/CodeIgniter#183]
When using a one-parameter native PHP function as a validation rule, the boolean response of that function is ignored.

I use a global PHP function (not native, but accessible globally) for certain validations.  When it returns FALSE, this response is ignored.

I have modified Form_validation so that, if a PHP function validation rule returns FALSE and there is a corresponding CI error message, it will act like a normal callback.  Otherwise, it acts as it does now.

**Comment by r00ps** [comment]
erm looks like this problem is still present in version 2.2.0....the offending code in Form_validation.php, lines 613 - 647

    if ( ! method_exists($this, $rule))
    {
        // If our own wrapper function doesn't exist we see if a native PHP function does.
        // Users can use any native PHP function call that has one param.
        if (function_exists($rule))
        {
            $result = $rule($postdata);

            if ($_in_array == TRUE)
            {
                $this->_field_data[$row['field']]['postdata'][$cycles] = (is_bool($result)) ? $postdata : $result;
            }
            else
            {
                $this->_field_data[$row['field']]['postdata'] = (is_bool($result)) ? $postdata : $result;
            }
        }
        else
        {
            log_message('debug', "Unable to find validation rule: ".$rule);
        }

        continue;
    }

    $result = $this->$rule($postdata, $param);

    if ($_in_array == TRUE)
    {
        $this->_field_data[$row['field']]['postdata'][$cycles] = (is_bool($result)) ? $postdata : $result;
    }
    else
    {
        $this->_field_data[$row['field']]['postdata'] = (is_bool($result)) ? $postdata : $result;
    }
