### ISSUE TITLE
ActiveRecord - ORDER BY FIELD values protection wrong

### ISSUE THREAD

**Issue by ghost** [bcit-ci/CodeIgniter#1846]
I have Hotels and Products models, when consturct this query :

``` php
 $this -> db -> like('title', $search);
 $this -> db -> or_like('description', $search);
 $this->db->join('products', 'products.id = hotels.id', 'left');
 $this -> db -> order_by('FIELD ( products.country_id, 2, 0, 1 )');
 return $this -> db -> get($this -> 'hotels');
```

The generated SQL is not interpeted by MySQL server :

``` sql
SELECT * FROM (`hotels`)
LEFT JOIN `products` ON `products`.`id` = `hotels`.`id`
WHERE `title` LIKE '%hotel%' OR `description` LIKE '%hotel%'
ORDER BY FIELD ( products.country_id, `2`, `0`, `1` )
```

MySQL server parses integers as column names and the query does not succeed : 

``` log
#1054 - Unknown column '2' in 'order clause'
```

Look at line 851 in DB_active_rec.php file, the _protect_identifiers is responsible for this behaviour.

**Comment by tony1223** [comment]
It helps a lot on old projects. :+1:

**Comment by searchpcc** [comment]
this may help you .
$this->db->_protect_identifiers = FALSE;
$this -> db -> order_by('FIELD(id, 3,1,2)');
$this->db->_protect_identifiers = TRUE;
