### ISSUE TITLE
Call to a member function result() on a non-object error

### ISSUE THREAD

**Issue by it-can** [bcit-ci/CodeIgniter#1856]
Hi,

I am seeing in my logs the following error on some of my custom queries:

**Call to a member function result() on a non-object**

```
class Test_Model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }

    public function get_all($id)
    {
        $query = $this->db->query("SELECT * FROM tbl WHERE id=?", array($id));

        return $query->result();   // Error is on this line
    }
}
```

It seems to throw the error when the result set is empty.... Is this normal behavior?

Using the latest develop btw...

**Comment by JonAlco** [comment]
@it-can Pudiste resolver el error?
Tengo el mismo problema.
Imprimi la declaración SQL y la ejecute en MYSQL y si funciona.
