### ISSUE TITLE
Grouping LIKE clause (putting parenthesis around)

### ISSUE THREAD

**Issue by daljit3** [bcit-ci/CodeIgniter#1881]
``` PHP
        $this->db->select('id, name, description')
                ->from('myfiles')
                ->where('is_public', 0)
                ->limit($limit, $offset);

        if (isset($query_array['q']) && strlen($query_array['q'])) {
            $this->db->like('name', $query_array['q']);
            $this->db->or_like('description', $query_array['q']);
            $this->db->or_like('others', $query_array['q']);
        }
```

The above code produces this query ... 

``` PHP
SELECT `id` , `name` , `description`
FROM `myfiles`
WHERE `is_public` =0
AND
`name` LIKE '%m%'
OR `description` LIKE '%m%'
OR `others` LIKE '%m%'
```

But I need it to be like this - Please note the parenthesis around LIKE clauses

``` php
SELECT `id` , `name` , `description`
FROM `myfiles`
WHERE `is_public` =0
AND 
(
`name` LIKE '%m%'
OR `description` LIKE '%m%'
OR `others` LIKE '%m%'
)
```

Is there any way to tell CI to put thos parenthesis? I know there is `$this->db->query()` but would wait to see if this is possible with above code.

**Comment by diwahyu** [comment]
Try this
$test = ci()->db
    ->select('COUNT(id) AS n')
    ->from('products')
    ->where('out_of_stock', 0)
    ->where("( name LIKE '%".$search."%' OR description LIKE '%".$search."%' AND id != ),'0',true )
    ->get_compiled_select();

I use "AND id != 0" just to complete the rule of the active query WHERE. It can be replaced freely as long as not interfere with the results of the query. Sorry, my English is bad.
