### ISSUE TITLE
Encoding of form fields

### ISSUE THREAD

**Issue by it-can** [bcit-ci/CodeIgniter#1953]
Hi,

since I updated to the latest develop it seems that when I post/save to the database `&` it seems to get encoded to `&amp;`
In the database it is saved correctly...

I think it is related to this: https://github.com/EllisLab/CodeIgniter/commit/3ccc386be4e0e1e4b3d47f1785e11d4b8613ef72#diff-25

**Comment by narfbg** [comment]
Well ... yet another revert on this.

It is `set_value()` that shouldn't be used together with other form helpers and that has caused the issue that you described here. Added a note about it the docs this time.

**Comment by it-can** [comment]
ok... but what can I use instead of ```set_value()```?

**Comment by narfbg** [comment]
If you're using it like shown in that example it's completely fine - it doesn't pass `set_value()` to i.e. `form_input()`, so no double encoding.

**Comment by it-can** [comment]
@narfbg I am using it like this: ```echo form_input(array('name'=>'abc'), set_value('abc', $abc));```

**Comment by narfbg** [comment]
Well ... don't.

`isset($var) ? $var : $default` should do it.

**Comment by it-can** [comment]
I use ```set_value()``` the form_validation class.

**Comment by narfbg** [comment]
`set_value() != $this->form_validation->set_value()`

**Comment by it-can** [comment]
Okay then I just have to pass the value given back by the form_validation class?

**Comment by narfbg** [comment]
I guess so.

**Comment by ivantcholakov** [comment]
What about an additional form helper function that returns raw, unescaped values? Then in some cases we will be able to decide how to apply escaping manually. Here is a code drafting:

```php

if ( ! function_exists('form_value'))
{
	/**
	 * Form Value (Raw)
	 *
	 * Grabs a value from the POST array for the specified field so you can
	 * re-populate fields in some special or cutting-edge cases. If Form Validation
	 * is active it retrieves the info from the validation class.
	 *
	 * Important: The result is not HTML-escaped or HTML-attribute-escaped,
	 * you should do it additionalyy according to the context of usage.
	 *
	 * @param	string	$field		Field name
	 * @param	string	$default	Default value
	 * @return	string
	 */
	function form_value($field, $default = '')
	{
		$CI =& get_instance();

		$value = (isset($CI->form_validation) && is_object($CI->form_validation) && $CI->form_validation->has_rule($field))
			? $CI->form_validation->set_value($field, $default)
			: $CI->input->post($field, FALSE);

		return $value === NULL ? $default : $value;
	}
}
```

**Comment by it-can** [comment]
I implemented something similiar in my projects...
