### ISSUE TITLE
form validation matches problem

### ISSUE THREAD

**Issue by hakimihamdan88** [bcit-ci/CodeIgniter#1957]
form validation matches bug

**Comment by erponline** [comment]
Hi,

if you use the crypto SHA1 attention to the confirmation line, place the code | sha1 before the function matches [xxx] if the code does not work ???

`		//if this is a new account require a password, or if they have entered either a password or a password confirmation
		if ($this->input->post('password') != '' || $this->input->post('confirm') != '' || !$id)
		{
			$this->form_validation->set_rules('password', 'lang:password', 'required|min_length[6]|sha1');
			$this->form_validation->set_rules('confirm', 'lang:confirm_password', 'required|sha1|matches[password]');
		}`
		//if this is a new account require a password, or if they have entered either a password or a password confirmation
		if ($this->input->post('password') != '' || $this->input->post('confirm') != '' || !$id)
		{
			$this->form_validation->set_rules('password', 'lang:password', 'required|min_length[6]|sha1');
			$this->form_validation->set_rules('confirm', 'lang:confirm_password', 'required|sha1|matches[password]');

Gabriel BYOOS

**Comment by flexsingit** [comment]
All the validation rules having parameters in them are giving internal server error ,

$this->form_validation->set_rules('password', 'Password', 'required|min_length[6]|max_length[12]');
$this->form_validation->set_rules('confirm_password', 'Password Confirmation', 'required|min_length[6]|max_length[12]|matches[password]');
