### ISSUE TITLE
form_validation lang 'valid_url', but no method

### ISSUE THREAD

**Issue by GDmac** [bcit-ci/CodeIgniter#1966]
While trying to test issue #1850 i saw that the reporter uses 
a valid_url rule in the form validation set_rules

There is no method or function named `valid_url()` anywhere, so the rule will actually never validate to TRUE. 
However, there is a language line for valid_url here:
https://github.com/EllisLab/CodeIgniter/blob/develop/system/language/english/form_validation_lang.php#L33

shouldn't either that line be removed to prevent confusion, or a method be added to actually test for valid_url() ?

**Comment by ProfNandaa** [comment]
Hey valid_url rule seems not work on my CI 3.0, e.g. a url like "test" passes the test. Advise.

**Comment by ZombieProtectionAgency** [comment]
@ProfNandaa I think that is intentional, have a look at Narfs comment on #3478
