### ISSUE TITLE
404 Page Not Found - The page you requested was not found.

### ISSUE THREAD

**Issue by it-can** [bcit-ci/CodeIgniter#1967]
I am getting a "404 Page Not Found The page you requested was not found." error when I go to my site: www.test.com

I have a the following routes.php

``` php
$route['default_controller'] = 'index';
$route['404_override'] = '';

/* CMS ROUTES */
$route['page/(:any)'] = 'index/page/$1';
```

I use also MY_Controller that extends CI_Controller, a quick view in the code I suspect that the problem is somewhere in this?

Urls with www.test.com/page/test-page  seems to work. But the default page (just www.test.com) shows a 404. This worked before...

**Comment by kavindaps** [comment]
Thanks narfbg..
I had a issue with this 404 error. your answer helped :+1:
