### ISSUE TITLE
problem query builder, spaces in field name

### ISSUE THREAD

**Issue by it-can** [bcit-ci/CodeIgniter#2080]
Hi,

There seems to be a problem with the query builder. I do this:

``` php
Array
(
    [date] => 2012-01-03
    [Test] => 1.232452342809917355
    [Test XL] => 1.3423525
)

$this->db->insert('testing', $data);

will produce:

INSERT INTO `testing` (`date`, `Test`, `Test` `XL`) VALUES ('2012-01-03', 1.232452342809917355, 1.3423525)
```

It seems to be escaping spaces?

**Comment by galdiolo** [comment]
Hi @narfbg, in case of "insert" maybe the query builder should not escape the spaces within a field name? I'm not sure if some RDBMS support aliased field in INSERT statements or if there are other downsides.
