### ISSUE TITLE
Redesign of Image Manipulation library

### ISSUE THREAD

**Issue by Debeet** [bcit-ci/CodeIgniter#2082]
I'll start with an example.

```php
$config['source_image'] = '/path/to/image/mypic.jpg';
$config['quality'] = 80;
$config['width'] = 500;
$config['height'] = 400;
$config['x_axis'] = '100';
$config['y_axis'] = '60';
$config['wm_text'] = 'Copyright 2006 - John Doe';
$config['wm_type'] = 'text';
$config['wm_font_path'] = './system/fonts/texb.ttf';
$config['wm_font_size'] = '16';
$config['wm_font_color'] = 'ffffff';
$config['wm_vrt_alignment'] = 'bottom';
$config['wm_hor_alignment'] = 'center';
$config['wm_padding'] = '20';

$this->load->library('image_lib', $config);
$this->image_lib->resize();
$this->image_lib->crop();
$this->image_lib->watermark();
```

At first glance it all seems alright. In practice we lost much more quality than we initially expected. Why? JPEG is a lossy format - it means that after every save we loose quality. In this example we loaded and saved the same file 3 times. We were loosing quality every single time.

The problem with this library is that we don't have load() and save() functions. It should not save the file after a certain action (resize, crop, etc.) is performed because of the reason above. Developers should do this manually in their code.

**Comment by narfbg** [comment]
We've already agreed in other discussions that at least some refactoring of the library is necessary. However, creating issues about it instead of submitting a pull request is not productive and it would probably be re-written in CI4 anyway, so ... closing.
