### ISSUE TITLE
Making DB Cache use the Cache driver not file cache

### ISSUE THREAD

**Issue by ragboyjr** [bcit-ci/CodeIgniter#2159]
The db caching system currently uses a file cache. For folks who deploy their ci application across multiple servers (like the company I work with does), a file cache does **not** work. We use memcached for all of our caching needs and CI's Cache driver has been great for us in that area. Now we'd love to use CI's db caching method because of how elegant/simple it is, but we need to alter it to work with memcached.
We have to choices to make.
We alter the CI db cache class to work with CI Cache driver
OR
We create our own library specific to our needs.

Bighead (the company I work for/with) loves CI, and we'd love to give back. We can spend the extra time to alter the CI db class to work with the cache driver which will make it work for everyone, but we only want to go that route if CI is going to want/use this feature.
Else we'll just make that library.

Thanks,
RJ

**Comment by narfbg** [comment]
Closing due to ~5 years of inactivity.
