### ISSUE TITLE
Upload.php getting wrong MIME Type for .CSV file. 

### ISSUE THREAD

**Issue by zechdc** [bcit-ci/CodeIgniter#2169]
My computers setup:
Mac OS 10.8.2
Chrome 24.0.1312.52
MAMP 2.1.1
PHP 5.4.4

The MIME Type that the upload class is returning when I try to upload a csv file created by Mac Excel is `text/plain`

I had a friend upload the same file from his Windows 7 machine and he didn't have any problems. 

Here is a link to the file I am trying to upload:
https://www.dropbox.com/s/xq2wgh90vmgjj9h/play_codes.csv

I don't know much about mime types but after reading this article it looks like the issue I am having is based on my local computer configuration (Browser, OS, etc)

http://blog.futtta.be/2009/08/24/http-upload-mime-type-hell/

**Comment by kushal555** [comment]
![7z](https://cloud.githubusercontent.com/assets/8221746/8371366/20c40290-1bf4-11e5-9f56-dd4ae7c7f02f.png)
