### ISSUE TITLE
CI_Driver_Library not found when upgrading from 2.1.3 to 3-dev

### ISSUE THREAD

**Issue by tkaw220** [bcit-ci/CodeIgniter#2191]
When upgrading from CI2.1.3 to CI3.0.0 Dev, I got this error: Fatal error: `Class 'CI_Driver_Library' not found in C:\Server\www\pelican\system\libraries\Session\Session.php on line 53.`

I has replaced the `system` folder and tweaked config files as per instructions from the upgrade guide. What could possibly goes wrong here?

**Comment by rohmanmuhamad** [comment]
Just set session as driver like this $autoload['drivers'] = array('session');
