### ISSUE TITLE
odbc num_rows() return is not empty value, but result() and result_array() is both return empty array

### ISSUE THREAD

**Issue by whyb** [bcit-ci/CodeIgniter#2214]
version: CodeIgniter 2.1.3 release
OS:winxp
DB:sql server 2008
php version : 5.3.21 
in model
num_rows() return is 60+ , 
but $query->result() and $query->result_array() is both return empty array .... 
now the project is not work, please help me ~~~

controllers/country.php:
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class country extends CI_Controller {

```
public function index()
{
    $this->load->model('country_model');
    $result = $this->country_model->getAll();
    $this->output->set_content_type('application/json');
            $this->output->set_output(json_encode($result));
}
```

}

models/country_model.php:
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class country_model extends CI_Model {

```
public function getAll()
{
    $query = $this->db->get("Country");
            echo $query->num_rows()."<br>".$query->num_fields();     //185\15
            //return $query->result();     //not work
    return $query->result_array();       //not work
}
```

}

output :   185<br>15[]

**Comment by mckaygerhard** [comment]
hi @narfbg i hve this issue, and noted others issue in CI# but unfortunatelly i cannot upgrade right now a production proyect, please can you provided related commits with this problem? so i can adapt for CI2 (i do not use active record), i have this exact problem

**Comment by mckaygerhard** [comment]
hi @narfbg i hve this issue, and noted others issue in CI# but unfortunatelly i cannot upgrade right now a production proyect, please can you provided related commits with this problem? so i can adapt for CI2 (i do not use active record), i have this exact problem

CI3 have some minor issues that can be improved but right now i not have time to do so.. i need some related info about thist problem

**Comment by narfbg** [comment]
Dude, I merely told you that you didn't comment in the right place and now you go comment on every ancient issue that mentions ODBC. Stop!

I can't provide you with the stuff that you're asking for and there's countless reasons for that. My only answer is "upgade". This is a bug tracker, not a support ticketing system.

**Comment by mckaygerhard** [comment]
it's a hard response for a comunity proyect, well normal response when a proyect are so famous. . thanks in any case i past all the night searchivng and waste a lot of time, so i post here for those like me that are in troubles i'll contribute:

commits: 

1. https://github.com/bcit-ci/CodeIgniter/issues/1125#issuecomment-4317954
2. cc5af53346397846f2035dc2bf6a2c2f9b0cd4ab
3. 9c68c3173c84041b1ee77929e540a4a4382edeee
4. only for stupid windoze access https://github.com/bcit-ci/CodeIgniter/issues/1125#issuecomment-111336917

sorry for that @narfbg dont worry i'll post also the fised for those very professional but no so easy to access odbc drivers working with CI3, but later, right now i'm very busy.. thanks in any way for...

**Comment by narfbg** [comment]
No, please don't post anymore. If you do, I'll delete your comments - you've been warned.

It's hard to even understand what you're saying, and I don't know how you think you're helping, but you're really not.
