### ISSUE TITLE
xlsx - The filetype you are attempting to upload is not allowed.

### ISSUE THREAD

**Issue by hakimihamdan88** [bcit-ci/CodeIgniter#2231]
When using upload library
- PHP 5.2.17 Centos
- Codeigniter develop branch

``` php
$config = array(
'allowed_types' => 'xlsx',
);
```

will throw "The filetype you are attempting to upload is not allowed."

---
- PHP 5.3 Windows
- Codeigniter develop branch

``` php
$config = array(
'allowed_types' => 'xlsx',
);
```

no problem at all

**Comment by cyberformed** [comment]
No still doesn't work on live server for the code.
`'xlsx' => array('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/zip', 'application/vnd.ms-excel', 'application/msword', 'application/x-zip'),`

**Comment by narfbg** [comment]
@cyberformed When I [told you to post on our forums](https://github.com/bcit-ci/CodeIgniter/issues/4589#issuecomment-211883983), I didn't mean to comment on other threads here.
