### ISSUE TITLE
Function _protect_identifiers from CI_DB_driver class breaks when active_record is set to FALSE

### ISSUE THREAD

**Issue by sergio-bobillier** [bcit-ci/CodeIgniter#2284]
When active_record is set to false in config.php file and you try to use the update_string function specifying a complete route for the table name (database.table) the _protect_identifiers function causes the following errors:

```
Message:  Undefined property: CI_DB_mysql_driver::$ar_aliased_tables
Filename: database/DB_driver.php
Line Number: 1299

Message:  in_array() expects parameter 2 to be array, null given
Filename: database/DB_driver.php
Line Number: 1299
```

The UPDATE string is produced without problem but the errors are reported, causing trouble for example in functions that produce XML output.

How to reproduce:
- Create a new CodeIgniter application and a new database with a single table.
- Alter the database.php file in the application/config folder, configure the database connection and **set active record to false**

``` php
$active_record = FALSE;
```
- In the Welcome controller write a sample block of code similar to the next one. The important thing here is to use update_string function and specify a complete route for the table name (database.table)

``` php
$this->load->database();
$where = "id = 1";
$data = array("name" => 'Apple');
$sql = $this->db->update_string("test_ci.Test_Table", $data, $where);
echo $sql;
```

This will cause two PHP errors (the ones mentioned above) however the last line will print the SQL UPDATE statement.

A suggested fix wold be to check if ar_aliased_tables attribute was initialized and if not then initialize it, or initialize it as an empty array when the function starts or the class is constructed.

**Comment by narfbg** [comment]
Disabling the Query Builder is no longer possible.
