### ISSUE TITLE
Misleading/Confusing SSL/TLS parameter with SMTP connection

### ISSUE THREAD

**Issue by yuanzhou** [bcit-ci/CodeIgniter#2320]
The following config works without problem.

```
$config = array(
    protocol' => 'smtp',
    'smtp_host' => 'ssl://smtp.example.com',
    'smtp_port' => 465,
    'smtp_user' => 'username',
    'smtp_pass' => 'password',
);
```

When I checked the email class source code, I noticed that we can specify the value of "smtp_crypto", if you remove "ssl://" prefix from the "smtp_host" value and assign it to "smtp_crypto" as shown below:

```
$config = array(
    protocol' => 'smtp',
    'smtp_host' => 'smtp.example.com',
    'smtp_port' => 465,
    'smtp_user' => 'username',
    'smtp_pass' => 'password',
    'smtp_crypto' => 'ssl',
);
```

BUT this won't work. Because "smtp_crypto" was set as NULL in the property definition and it can't be initialized in initialize($config = array()) when evaluated by isset() 

```
/**
 * SMTP Encryption
 * 
 * @var string NULL, 'tls' or 'ssl'
 */
public $smtp_crypto = NULL;
```

So it should be assigned with an empty string in property definition:

```
/**
 * SMTP Encryption
 * 
 * @var string 'tls' or 'ssl'
 */
public $smtp_crypto = '';
```

And in _smtp_connect(), we should change the NULL into empty string: 

```
$ssl = ($this->smtp_crypto === 'ssl') ? 'ssl://' : NULL;
```

to 

```
$ssl = ($this->smtp_crypto === 'ssl') ? 'ssl://' : '';
```

Besides, I think the available values of "smtp_crypto" can be confusing to some people when it comes to use TLS. As this article (https://www.fastmail.fm/help/technology_ssl_vs_tls_starttls.html) points out, and I'm not quite sure about if we should use "SSL/TSL" and "STARTTLS" instead of "SSL" and "TSL". Let's see what's gonna happen after we fix the above NULL to empty string '': 

```
$config = array(
    protocol' => 'smtp',
    'smtp_host' => 'smtp.example.com',
    'smtp_port' => 465,
    'smtp_user' => 'username',
    'smtp_pass' => 'password',
    'smtp_crypto' => 'ssl',
);
```

Now, this works as expected because 'ssl://' is added as the prefix to smtp connection. What if we choose 'tls' like below? 

```
$config = array(
    protocol' => 'smtp',
    'smtp_host' => 'smtp.example.com',
    'smtp_port' => 587,
    'smtp_user' => 'username',
    'smtp_pass' => 'password',
    'smtp_crypto' => 'tls',
);
```

This works too. But this time, no 'ssl://' is prefixed to the smtp connection, because $ssl will be empty in this case.

```
$ssl = ($this->smtp_crypto === 'ssl') ? 'ssl://' : '';
```

If you check the source code, you will find the following code block in _smtp_connection()

```
if ($this->smtp_crypto === 'tls')
        {
            $this->_send_command('hello');
            $this->_send_command('starttls');

            $crypto = stream_socket_enable_crypto($this->_smtp_connect, TRUE, STREAM_CRYPTO_METHOD_TLS_CLIENT);

            if ($crypto !== TRUE)
            {
                $this->_set_error_message('lang:email_smtp_error', $this->_get_smtp_data());
                return FALSE;
            }
        }
```

If I understand correctly, the existing insecure connection will be upgraded to a secure connection using SSL/TLS, which is called "STARTTLS".

**Comment by ns23** [comment]
adding 'smtp_crypto' => 'tls' to config solved my issue
