### ISSUE TITLE
CSRF protection and page caching doesn't work

### ISSUE THREAD

**Issue by royduin** [bcit-ci/CodeIgniter#2325]
It's a little bit lazy but I've posted the issue already on stackoverflow, so hereby just the link: http://stackoverflow.com/questions/15120735/codeigniter-csrf-protection-and-page-caching

I'm running CI 2.1.3

I've figured it out in my last comment at the answer. I hope you guys will implement it in the next version of CodeIgniter.

**Comment by seigba** [comment]
@Royduin - I borrowed Your solution and described [on my blog](http://stwarog.com/en/tips-and-tricks/75/codeigniter-3-csrf-token-and-cache). Big TY
