### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by nbaztec** [bcit-ci/CodeIgniter#2357]
Does CodeIgniter have any plans to support MongoDB as of now? I know this is tricky since the architecture does not fall in place with others (MySQLi, PostGre, PDO, etc.) since this is a NoSQL database, effectively rendering the query builder next to useless.

What are the current opinions on this?

**Comment by vigneshenfin** [comment]
Is codeigniter 3 currently support  MongoDB? If so, please share the library details.
