### ISSUE TITLE
Unstable CI Session

### ISSUE THREAD

**Issue by taranti555** [bcit-ci/CodeIgniter#2384]
Sometimes CI cannot read its own cookie file, and keeps on changing session ID. This error is practically impossible to reproduce, but about 2% people, especially IE users complain about it. Me, personally have seen it only ones.
 I have tried everything I could think of:
• Using DB for CI session; 
• Made sure that 4k space is not exceed;
• Clearing browsers cookies manually; 
• Playing around with the settings in every possible pattern;
This is the worst error in CI, which lead me to consider other frameworks. Please correct for v3.

**Comment by KalanaPerera** [comment]
still this issue is there, version 2.2.1

**Comment by narfbg** [comment]
2.x is no longer supported.

**Comment by errd** [comment]
And what is conclusion to this long thread? How to eliminate this error? 
Updated to 3.1.5 this weekend and this is still issue for me.
