### ISSUE TITLE
$_POST and $this->input->post() are empty

### ISSUE THREAD

**Issue by inigosola** [bcit-ci/CodeIgniter#242]
When I send data in some forms $_POST is empty in the controller.
The method is POST and de location is right. In the controller I can't get the post values. $this->input->post() is empty as well.
I tried several versions of apache (1.3... and 2.2...).
I tried several versions of php (5.2... and 5.3...).
I tried with the lastest version of codeigniter.
I tried with Mac OS X SnowLeopard and Mac OS X Lion.
I tried with Gentoo (lastest version).
I tried with Windows XP.
I tried with MAMP and WAMP.
The error is the same.

**Comment by craigsailor** [comment]
Hi, hoping to save others some time with what I learned.
On an IIS server, if you don't have a trailing slash on your URL the server will send a 301 redirect which will interfere with POST data. 
I banged my head against the wall for quite a while before stumbling across that tidbit of knowledge.

**Comment by dfstorm** [comment]
Same here. Solved with "sudo a2enmod rewrite" :)

**Comment by NilsRenaud** [comment]
same problem... same solution :)

**Comment by rohanjha1992** [comment]
Use the following two command in your terminal
1. sudo a2enmod rewrite
2. service apache2 restart
This is Rewriting issue but i am almost sure it will work for you. :)
