### ISSUE TITLE
form_prep() strips backslashes (\) and keeps htmlentities unescaped.

### ISSUE THREAD

**Issue by Dumk0** [bcit-ci/CodeIgniter#2477]
1. I would like to edit in form field the exact text "foo&nbsp;bar", but when I pass this text to form_input(), then there is field with text "foo bar" on page.

2. As long as Input class handles all POST, GET, etc superglobals and strips slashes on CodeIgniter load then it is unnecessary to stripslashes on form_prep() again or what was the purpose of that action?

I have made two test cases for form_prep() helper function which fail for me.
```php
		$this->assertEquals(
			'Here is a string containing slashes / and \.',
			form_prep('Here is a string containing slashes / and \.')
		);

		$this->assertEquals(
			'Here is a string containing ampersand &amp;.',
			form_prep('Here is a string containing ampersand &.')
		);
```

I guess the right way to process the form_prep() values is to convert all chars to entities and escape double quotes. Maybe You have also comments and/or solutions on this.

**Comment by ivantcholakov** [comment]
A case:

You have a CKEditor attached to a textarea element created with form_textarea(). By using the editor you enter a HTML fragment, on saving this HTML is sanitized (allowed tags) and stored within a database field.

Now let us edit the stored HTML fragment the same way with CKEditor. We take this fragment from the database field and put it as an argument of form_textarea(). As a result, an escaped HTML fragment will be inserted inside the textarea tag. And the editor will show garbage.

Please, reconsider this change, form_prep() with the optional parameter $is_textarea was fine in this case.

**Comment by narfbg** [comment]
CKEditor is made to work with raw HTML fields, it doesn't care about `form_textarea()`.

And more importantly, we can't support every edge case, let alone third-party tools.
