### ISSUE TITLE
Fatal Error: Call to undefined method MY_Upload::clean_file_name()

### ISSUE THREAD

**Issue by daljit3** [bcit-ci/CodeIgniter#2494]
I just download the latest copy (dev version) and replaced with older dev version. I have started getting this error  Call to undefined method MY_Upload::clean_file_name() in /My_Upload.php now.

I can't find any newer version of this method in the CodeIgniter/libraries/Upload.php .... Is this method no longer required?

**Comment by Ashishkhiunju** [comment]
i Didnot understand yet
