### ISSUE TITLE
Add comment to table fields #New Feature

### ISSUE THREAD

**Issue by fzhan** [bcit-ci/CodeIgniter#2519]
It would be good if field comment can be added using dbforge->add_field().

$table = array(
'email' => array( 'type' => 'VARCHAR', 'constraint' => '64' ), 'securehash' => array( 'type' => 'VARCHAR', 'constraint' => '64', 'comment' => 'store temprary email address'),
);

**Comment by luckydonald** [comment]
Herby I'll complain because of the lack of such feature.
Would adding that feature via pull request still be accepted?

**Comment by luckydonald** [comment]
In fact it was added (mysql only) back in e4b10bf0ad59049ed78ed9cfc5f708188f3cd442.
Couldn't find that documented anywhere, but now I know.
Thanks @zachflower for implementing it.
