### ISSUE TITLE
Usage of standard timezones to get real times (daylight savings)

### ISSUE THREAD

**Issue by xcript** [bcit-ci/CodeIgniter#2578]
I'm working with CI-Bonfire, which ist based on CI. As I need the timezones for getting the real and current time of a user, I found a great bug of CI: the timezone handling. CI is working with timezones like "UM4" or "UP1". But WHY? Why does CI not uses standard timeszone like "Europe/Berlin", which handles daylight saving times without any problem?

Here (https://github.com/ci-bonfire/Bonfire/issues/851) I posted a solution for the timezone-menu for CI-Bonfire, which based on CI's timezone-menu, but uses standard timezones. Bonfire saves the timezone of an user in it's user table. If it is an user of Germany, than you currently get the wrong time, because CI sets "UP1" for the user, but his current time ist UTC+2 - not UTC+1!

Please explain, why CI uses non standard timezones. I suggest to switch CI competely to the standard timezones.

**Comment by DavidOtis** [comment]
Is this still an issue that should be dealt with? Other than the timezone menu, the date_helper doesn't seem to offer anything that PHP doesn't. Is the timezone menu worth rewriting the date_helper for?

**Comment by pmbaldha** [comment]
timezone_identifiers_list() function should be used to get timezone array. http://php.net/manual/en/function.timezone-identifiers-list.php
What is other developer's opinion?

**Comment by adomasalcore3** [comment]
I think that you are right @pmbaldha
