### ISSUE TITLE
iconv() detect illegal char in input

### ISSUE THREAD

**Issue by CrazyLionHeart** [bcit-ci/CodeIgniter#261]
In PHP 5.3 Debian 6.0.1 (and older) iconv generate notice:  iconv(): Detected an illegal character in input string /var/www/www/system/core/Utf8.php 89

**Comment by hardeverick** [comment]
I know that this is a closed issue, but this thread didn't really resolve my issue. I did find a solution in a comment at (http://php.net/manual/en/function.iconv.php#108643). Basically you change line 89 of Utf8.php with these 2 lines;

ini_set('mbstring.substitute_character', "none"); 
$text= mb_convert_encoding($text, 'UTF-8', 'UTF-8');

Hope that can help out anyone else trying to get rid of this error in their log.
P.S. - @tgriesser mentioned this function above as well

**Comment by keshav1990** [comment]
Thanks for your support , :+1:

**Comment by narfbg** [comment]
This isn't a support thread.
