### ISSUE TITLE
session problem in localhost

### ISSUE THREAD

**Issue by sankbhatt** [bcit-ci/CodeIgniter#2624]
i have download a fresh copy of CI 2.1.4 on my local machine using xampp
i have made two changes in all 
1. in config.php 
$config['encryption_key'] = 'asddsad';
2. in autoload.php
$autoload['libraries'] = array('database', 'session');
when i open the page in browser (localhost/ci)
the default page of project following error shows up
In order to use the Session class you are required to set an encryption key in your 
config file
i googled a lot and tried many codes and changes, also testing in other browsers and in other new copy of CI too. error remains the same for me
i am using windows8 and xampp to do this
can someone suggest a way out of this..

**Comment by a4ankii** [comment]
hello there ,
have u solved this issue 
"An Error Was Encountered

In order to use the Session class you are required to set an encryption key in your config file." 
i am getting this error even after setting up the things  using ci 2.1.3.
please help me out Asap.
