### ISSUE TITLE
Security.php "e" modifier depracated php >= 5.5

### ISSUE THREAD

**Issue by ckris** [bcit-ci/CodeIgniter#2681]
In Security.php eval modifier depracated, for fix can be use preg_replace_callback.

For 5.5 or later version of parser, open Security.php go to line 557 and 558 then replace with:

``` php
            if(version_compare(PHP_VERSION,5.5,'>=')){
                $str = preg_replace_callback('~&#x(0*[0-9a-f]{2,5})~i', function(){return chr(hexdec('\\1'));}, $str, -1, $matches);
                $str = preg_replace_callback('~&#([0-9]{2,4})~', function(){return chr('\\1');}, $str, -1, $matches1);
            }else{
                $str = preg_replace('~&#x(0*[0-9a-f]{2,5})~ei', 'chr(hexdec("\\1"))', $str, -1, $matches);
                $str = preg_replace('~&#([0-9]{2,4})~e', 'chr(\\1)', $str, -1, $matches1);
            }
```

**Comment by Fohlen** [comment]
This code also affects CI 2.x series and should be fixed within a minor bug release (as soon as possible!). The code instructions are not as precise, I have accomplished it this way https://github.com/inexor-game/community-site/commit/dcc7c541bebe183516d08899bff8c654ff4acb01

**Comment by narfbg** [comment]
You should look into the 2.2.1 code, as soon as possible. ;)

**Comment by Fohlen** [comment]
Haven't seen the new release yet, ty! :+1: 
Can be closed, I guess.
