### ISSUE TITLE
Naming convention in sessions

### ISSUE THREAD

**Issue by aanbar** [bcit-ci/CodeIgniter#2702]
so I spent 2 hours debugging an issue on why a script I am working on doesn't process the logins, Only to find out that there's a field named 'last_activity' in the session that's being overridden in my table.

I thought all session related variables have the "sess_" prefix, leaving this field without a prefix isn't a good idea (for now I had to change my field name to skip messing with the library).

**Comment by narfbg** [comment]
Fixed by #3073.
