### ISSUE TITLE
Extend DB Drivers...?

### ISSUE THREAD

**Issue by a-h-abid** [bcit-ci/CodeIgniter#2717]
Today I tried to extend a DB driver in hope that it will work on CI 3.0 but seems like it has not been implemented yet. Placed in `application/database/drivers/mysqli/MY_mysqli_driver.php`. Needed for adding "insert duplicate update" feature. We currently extend via this approach:

https://github.com/EllisLab/CodeIgniter/wiki/Extending-Database-Drivers

But to me this seems like extra work for extending a DB driver. Plus in case the database() method is updated in main Loader.php and forgot to update in extended class, then we'll be missing any fixes/changes that are done.

So would be great if made easier to extend any db driver just like extending core, helpers or libraries.

**Comment by Nudasoft** [comment]
Just wondering if this feature is gonna implement in the near future?

**Comment by narfbg** [comment]
No. I've slowly convinced myself out of it and with CI4 out I now have even less reason to think of big new features for CI3.
