### ISSUE TITLE
Unable to locate the specified class: Session.php

### ISSUE THREAD

**Issue by veizz** [bcit-ci/CodeIgniter#2793]
I tried to upgrade 2.1.4 to 3.0-dev, when I enabled hooks, autoload session driver, it just give me this error: 

Unable to locate the specified class: Session.php

**Comment by moazzamabbas** [comment]
Sir how to load controller in another controller in codeigniter 3x version

**Comment by narfbg** [comment]
You don't.

And this is a bug tracker; if you want to ask a question, please do it on our [forums](http://forum.codeigniter.com/).
