### ISSUE TITLE
Default controller subdirectory (worked in 2.1.4 but not in the latest 3.0.0/release)

### ISSUE THREAD

**Issue by zentaos** [bcit-ci/CodeIgniter#2849]
Hello,

I just updated to the latest 3.0.0/release build but the default controller doesn't working anymore if the controller is in a subdirectory.

$route['default_controller'] = 'page/news';
$route['404_override'] = 'error_404';
$route['translate_uri_dashes'] = FALSE;

I hope you can fix this.

Thank you.

**Comment by seputrodimas** [comment]
so on the CI3 you "can't" change default_controller on sub-directory? 
is this feature really disabled? :(
dude... really? :(

**Comment by narfbg** [comment]
Yes, really.

Please ask your questions on the [forum boards](http://forum.codeigniter.com/), not here.
