### ISSUE TITLE
Common.php returned by reference error

### ISSUE THREAD

**Issue by kutothe** [bcit-ci/CodeIgniter#2901]
After commit c26b9ebb00e29be2e972fece3bcf73d33249a64b, I'm getting the following:

`Severity: Notice
Message: Only variable references should be returned by reference
Filename: core/Common.php
Line Number: 188`

I'm sorry I don't have any more information, but let me know if you need more than this.

**Comment by muzaffar1** [comment]
on line number 257. (common.php) file change return $_config[0] =& $config; into 
 $_config[0] =& $config;
 return $_config[0];

hope this will work..

**Comment by remya90** [comment]
thank yu so much...it wrks...

**Comment by tiveor** [comment]
@muzaffar1 thanks, it works.

**Comment by hsali** [comment]
on line number 257. I replace that line with this below snippet. 
$_config[0] =& $config;
		return $_config[0];
