### ISSUE TITLE
Session : array to string conversion error on multi-deimentional array

### ISSUE THREAD

**Issue by alzalabany** [bcit-ci/CodeIgniter#2923]
calling `$CI->session->set_userdata('alertify', ['error','empty',['error,'empty data'] ]);` will trigger error

A PHP Error was encountered
Severity: Notice
Message: Array to string conversion
Filename: drivers/Session_cookie.php
Line Number: 728

`
$config['sess_driver']			= 'cookie';
$config['sess_valid_drivers']	= array();
$config['sess_cookie_name']		= 'ci_session';
$config['sess_expiration']		= 7200;
$config['sess_expire_on_close']	= TRUE;
$config['sess_encrypt_cookie']	= TRUE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']		= 'ci_sessions';
$config['sess_match_ip']		= TRUE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;
`
not sure if this is supposed to happen or not, but thought i should mention it !.

1. this error disappear when using native driver.
2. this error was not existing in v 2.*

**Comment by narfbg** [comment]
Fixed by #3073.
