### ISSUE TITLE
database migration version numbers in file names taken too literally

### ISSUE THREAD

**Issue by bgarrison25** [bcit-ci/CodeIgniter#2970]
In the current documentation it teaches you to make your migration files with examples like this: 001_add_sessions.php and then to set the migration version number in the config to 1. 

In attempting to do this with 3.0-dev I was getting a version not found error. When find_migrations() is called the regex is pulling in all three numbers in the file name and returning 001. When isset looks for the key of 1 it doesn't find it because the key is 001. I'm not sure if this is due to a new regex or if php handles 001 differently now or what. This may be valid and we have to make sure to set our versions to exactly the version specified in our migration file. I only mention it because it is different / undocumented.

For now I will be using specific version numbers in my config file. 

Thanks!

**Comment by hero78** [comment]
By default migration type is eqaul to timestamp and if you are going to use sequence/ numbering you need to change it FROM  $config['migration_type'] = 'timestamp'; TO $config['migration_type'] = 'sequential';
