### ISSUE TITLE
New Session library

### ISSUE THREAD

**Issue by narfbg** [bcit-ci/CodeIgniter#3073]
It can be found in the **feature/session** branch and is the last thing I want finished before the 3.0 release. To everybody reading this: please test it and give some (useful) feedback. :) Tests with non-mysql DBs in particular would be really useful.

Implemented features:

 - Locking (this is mandatory, no drivers without locking will be implemented; locking for non-MySQL/Postgre DBs though is done through sysvsem, which means there's no locking on Windows)
 - Lazy writes (only write data to storage if it was changed)
 - 'files' & 'database' drivers

Planned/todo features & other stuff that *might* get implemented:

 - Redis & Memcache(d) drivers
 - Not sure if extending the library works at this time, but this certainly needs more work
 - Optional session data encryption
 - Other drivers?
 - Tests? (we've had issues with PHPUnit burping with "headers already sent" messages when we send cookies)
 - PHP should validate incoming session IDs (they need to be all alphanumeric chars), but still - double check that to avoid SQL injections
 - Automatic regeneration of IDs
 - session.use_strict_mode functionality

BC breaks:

 - Flash/temp/user-data can collide & are all actual `$_SESSION` vars
 - Changed table structure for database storage
 - No cookie storage (no, it will **not** happen, you must use server-side storage)
 - No user-agent matching - it's user input and therefore ineffective and pointless
 - Database storage can't be used with a persistent connection (to avoid deadlock and to allow concurrency)

Issues/PRs that this resolves/supersedes:

 - #1344 
 - #1375 
 - #1780 
 - #1940
 - #2476 
 - #2702 
 - #2923

**Comment by MrGate** [comment]
So is the docs for the new session library the only thing holding back the 3.0 release?

**Comment by jim-parry** [comment]
That, plus then merging the feature branch, and then of course the release prep process.
Andrey is working on these :)
________________________________

**Comment by JeremybellEU** [comment]
Wouldn't the state design pattern be a good improvement for the field $_platform?

This way you wouldn't do the if's for each platform, but simply call an abstract method to a implementation of a DbPlatform subclass.

**Comment by narfbg** [comment]
Unnecessary complexity.

**Comment by orionstar** [comment]
I started to use the latest version of this repo, and the database driver stopped working...
(Files driver working fine.)

There are records in the ci_sessions table, but I can't access the data with $this->session->userdata. The cisession cookie is created at client side. The $_SESSION array is empty. The profiler shows there are no session variables and on the queries tab I see a strange query on every page load: 
```sql
SELECT GET_LOCK('a195031d4a996ea9ddddff4e3755ad5a06fc93dd', 10) AS ci_session_lock 
```
I am using the latest develop branch, with a modified version of wiredezign's HMVC extension, database pconnect is FALSE.

Encryption key:
```php
$config['encryption_key'] = 'b542cq1j80m2x77U2V07Fl23373M62Q6i33582b7401m6e73wN3C1653yQN4686nrt81O2572x180965P8b427U48iaecH38365Y';
```

SESSION config settings:
```php
$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'cisession';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
```

Environment: Win8.1, Apache 2.4.4, PHP 5.4.19, MySQL 5.5.32.

**Comment by narfbg** [comment]
I might re-add the 'userdata' property (or a `__get()` with logic to access it) for BC purposes, but other than that, any problem is likely caused by your own code or the HMVC "extension" ... CI doesn't support HMVC and I don't know what's in it, so if you're using it - debug it on your own.

Also, if all of it tries to access `$this->session->userdata` and it doesn't exist ... it's natural that there's no data in the database.

There's nothing strange about that query, and 'encryption_key' is unused. If you're getting any error messages logged - that would be useful.

**Comment by orionstar** [comment]
I debugged it, the third parties and my codes are working fine!

The problem is in your code: CI_Session_database_driver::read(), line 150
You wrote:
```php
$result = ($this->_platform === 'postgre')
				? base64_decode(rtrim($result->data))
				: $result->data;
```
Instead of:
```php
$result = ($this->_platform === 'postgre')
				? base64_decode(rtrim($result->data))
				: base64_decode($result->data);
```

Because of this little bug, the session data never decoded back, except in case of using Postgres....

**Comment by ivantcholakov** [comment]
It is likely the fragment starting at the line 196 to be fixed.

**Comment by narfbg** [comment]
... or a bit above it.

**Comment by ivantcholakov** [comment]
Ah, yes.

**Comment by ivantcholakov** [comment]
A typo within the line 203:

```
A PHP Error was encountered
Severity: Notice
Message: Undefined variable: time
Filename: drivers/Session_database_driver.php
Line Number: 203
```

**Comment by narfbg** [comment]
The 'feature/session' branch is now merged into 'develop'.

**Comment by hengsoheak** [comment]
I've update to CI3 I got a problem when I used Session (auto load). My Problem is session can't ignoring session regenerated when ajax requested although I found below code in Session library 

if ((empty($_SERVER['HTTP_X_REQUESTED_WITH']) OR strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) !== 'xmlhttprequest')
			&& ($regenerate_time = config_item('sess_time_to_update')) > 0)
		{
			if ( ! isset($_SESSION['__ci_last_regenerate']))
			{
				$_SESSION['__ci_last_regenerate'] = time();
			}
			elseif ($_SESSION['__ci_last_regenerate'] < (time() - $regenerate_time))
			{
				$this->sess_regenerate((bool) config_item('sess_regenerate_destroy'));
			}
		}

**Comment by narfbg** [comment]
@hengsoheak Please post that on the [forums](http://forum.codeigniter.com/) and I'm sure somebody there will be able to help you. We don't provide support via github.
