### ISSUE TITLE
session cookie issuing different values per page refresh

### ISSUE THREAD

**Issue by foxlance** [bcit-ci/CodeIgniter#3084]
To recreate the bug, do the following on a fresh download of 2.2.0

On autoload.php

``` php
$autoload['libraries'] = array('session');
```

On config.php

``` php
$config['encryption_key'] = 'qwertyuiopasdfghjklzxcvbnmqwerty'; // something random
$config['sess_encrypt_cookie'] = TRUE;
```

Open up your devtool and confirm that every page request will assign a new value for ci_session.

Checking out the code changes on system\libraries\Session.php, I can confirm that lines 157 - 175 is directly responsible for this issue. 

I'm using xampp version 1.8.3 running PHP 5.5.6 (mcrypt enabled)

**Comment by loopstation1024** [comment]
Hi

I had the same issue with CI 3.0.6. and php 7.3.4
After trying for many hours the solutions was changing the Session.php file i had in the core/libraries/session folder for the CI 3.1.10 version.
Now it works!
