### ISSUE TITLE
CodeIgniter 2.2.0 HMAC mismatch error

### ISSUE THREAD

**Issue by mga242** [bcit-ci/CodeIgniter#3094]
Session: HMAC mismatch. The session cookie data did not match what was expected.

The Mcrypt extension is enabled. If I set $config['sess_encrypt_cookie'] = FALSE; (not an option for production) there is no error. Initially downloaded on release 5/6/2014. Downloaded new copy as per suggested at https://github.com/EllisLab/CodeIgniter/issues/3086 at but still seeing same bug.

http://stackoverflow.com/questions/24121705/codeigniter-2-2-0-hmac-mismatch-error

**Comment by jejjcop** [comment]
Hi guys, 
I seem to be having the same problem even after making the updates which were made to /system/core/Input.php in CI 2.2.1. 

My log file says: "Session: HMAC mismatch. The session cookie data did not match what was expected.".... and it then seems to start a new session. 

Please note: this is only happening in Google Chrome! The problem does not seem to occur in Firefox or IE (11). 

FYI: I am using DB for storing sessions and using session encryption. 

Regards
Per

**Comment by Kosonome** [comment]
I have CI 2.2.1 and having problems of "Session: HMAC mismatch.", it happens in Opera Browser and Internet Explorer too.

I stopped using flashdata with a redirect(), and all works now. Maybe this is a hint?

**Comment by edersonlrf** [comment]
Explanation about this error:

http://www.hiretheworld.com/blog/tech-blog/codeigniter-session-race-conditions
