### ISSUE TITLE
trans_status() === TRUE even if transactions fails

### ISSUE THREAD

**Issue by yekver** [bcit-ci/CodeIgniter#3098]
If `$trans_strict` is set to false and transaction fails then we expecting to get `false` in `$this->db->trans_status()`, instead of this we will always receive `true` independently of real transaction status.

``` php
$this->db->trans_strict(FALSE);

$this->db->trans_start();
$this->db->query('AN SQL QUERY...');
$this->db->query('QUERY THAT WILL GENERATE AN SQL ERROR...');
$this->db->trans_complete();

if ($this->db->trans_status() === FALSE)
{
    // error woun't be generated...
}
```

**Comment by zenepay** [comment]
I wonder that if query return zero match based on where cause, will the $this->trans_status return false?
