### ISSUE TITLE
Regenerate session_id every time page reloads.

### ISSUE THREAD

**Issue by nardev** [bcit-ci/CodeIgniter#3108]
Unfortunately i spend so many time not seeing this issue

If you name a cookie with dots in name (the website domain name for ex.), you gonna get this stupid issue.

$config['sess_cookie_name'] = 'some.domain.com.ba';

And, there you are. It fails. It regenerate session id every time you reload the page.

p.s. codeigniter 2.2.0

**Comment by nathanpitman** [comment]
Just to note that the same is true of using underscores from what I can ascertain. It would be useful if the config var was commented to make this clear. :)

**Comment by WillieStevenson** [comment]
I can confirm brenjt's post. It is indeed an issue with dots in the cookie domain config. Spent a few hours watching new session ids be generated on every page refresh (and therefore not keeping set userdata).

**Comment by salim9030** [comment]
<script>alert('Hi');</script>

**Comment by nathanpitman** [comment]
Could this be resolved by simply stripping non alphanumeric chars from the cookie name in CI and then appending a note to the config file such?

**Comment by narfbg** [comment]
@WillieStevenson The cookie **domain** is not the same thing as the cookie **name**.

People constantly confusing the two has resulted in that myth about underscores in cookie names - no such problem exists. And it's the same with the dot character - it's a perfectly valid one both in cookie names and the domains they're coupled with.

The valid cookie name characters are defined by IETF's [RFC6265, section 4.1.1](https://tools.ietf.org/html/rfc6265#section-4.1.1) as:

> cookie-name = token
> ...
> token = \<token, defined in [RFC2616, Section 2.2](https://tools.ietf.org/html/rfc2616#section-2.2)>

And [RFC2616, section 2.2](https://tools.ietf.org/html/rfc2616#section-2.2) defines the following:

>       CHAR           = <any US-ASCII character (octets 0 - 127)>
>       ...
>       CTL            = <any US-ASCII control character
>                        (octets 0 - 31) and DEL (127)>
>       ...
>       SP             = <US-ASCII SP, space (32)>
>       HT             = <US-ASCII HT, horizontal-tab (9)>
>       ...
>       token          = 1*<any CHAR except CTLs or separators>
>       separators     = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT

Meaning that the following are *all valid cookie name characters*:

<pre>
!#$%&'*+-.0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ^_`abcdefghijklmnopqrstuvwxyz|~
</pre>

I am very skeptical of the usage of any of these causing any kind of problems, but I guess we can't rule out browsers bugs at 100%. However, as far as CodeIgniter is concerned, this is all that needs to be said here.
