### ISSUE TITLE
Form validation is_unique fails on update

### ISSUE THREAD

**Issue by raduhek** [bcit-ci/CodeIgniter#3109]
When updating an entry, having `is_unique` rule for a field that was not changed will make the validation fail.

**Comment by Safeervs7** [comment]
$this->form_validation->set_rules('user_name', 'Username', 'required|is_unique[tablename.id!='.$id.' AND '.'user_name=]');

simplest method to validate the form for uniqueness on creating and updating record

**Comment by Ahmad-Almosallam** [comment]
you can simply do this 
is_unique[tablename.username , id , {id}] 
'username' => 'required|min_length[2]|max_length[10]|is_unique[users.username ,id,{id}]'

**Comment by spreaderman** [comment]
> you can simply do this
> is_unique[tablename.username , id , {id}]
> 'username' => 'required|min_length[2]|max_length[10]|is_unique[users.username ,id,{id}]'

That's what the documentation says I can't see it working on implemented anywhere.
