### ISSUE TITLE
Email validation should not use regex

### ISSUE THREAD

**Issue by igasparetto** [bcit-ci/CodeIgniter#3116]
Emails with apostrophes don't pass the validation. For example, jon.o'shea@email.com

system/libraries/Form_validation.php
        return ( ! preg_match("/^([a-z0-9+_-]+)(.[a-z0-9+_-]+)*@([a-z0-9-]+.)+[a-z]{2,6}$/ix", $str)) ? FALSE : TRUE;

I suggest:
        return filter_var($str, FILTER_VALIDATE_EMAIL);

Same problem at system/helpers/email_helper.php
and system/libraries/Email.php

**Comment by salmanAhmad143** [comment]
Hi @igasparetto , please check this. Here is the solution of your problem ..
http://phpsollutions.blogspot.com/2016/02/allowing-apostrophes-in-valid-email.html
