### ISSUE TITLE
Conflicts using __get() method to automatically load models

### ISSUE THREAD

**Issue by OldChapStudio** [bcit-ci/CodeIgniter#3137]
Hi,

I was trying to add the __get() method to my main controller, so that I don't need anymore to call the $this->load->model() each time I call for a model, here's the code :

```
public function __get($property) 
    {
        if(strpos($property,'_model') !== FALSE) 
        {
            $this->load->model($property);
            return $this->$property;
        }
        return NULL;
    }
```

It works fine but generates some conflicts with Code Igniter internals :
1. Generates a notice error : 

```
Message: Indirect modification of overloaded property Game_controller::$benchmark has no effect
```
1. Generates a fatal error : 

```
Cannot assign by reference to overloaded object in path\system\core\Controller.php on line 64
```

It seems the __get method don't really like the pass-by reference syntax...
By correcting this two lines in core/Controller.php

```
$this->$var =& load_class($class);
$this->$var = load_class($class);

$this->load =& load_class('Loader', 'core');
$this->load = load_class('Loader', 'core');
```

Everything works fine. So my question is : 
Do CodeIgniter needs anymore the pass-by reference syntax for objects assignements ? Knowing it is obsolete now with php 5.

Do this part of code could be proposed as a pull request ?

Thanks

**Comment by terrylinooo** [comment]
Same problem here. I do the same thing as OP did. 

Do you solve this issue?

**Comment by Everterstraat** [comment]
Easy, no changes at loader class needed but click on link below and don't forget to favorite..

Second snippet is a solution t not need to declare $this-ci in each library

https://gist.github.com/Everterstraat

**Comment by terrylinooo** [comment]
Not solve my problem but give me some idea to solve it. Thanks.

**Comment by narfbg** [comment]
This is a bug tracker, not a forum board.
