### ISSUE TITLE
Undifine mysqli_init() line 103

### ISSUE THREAD

**Issue by mediasaranainformatika** [bcit-ci/CodeIgniter#3159]
Hello,
I am from Indonesia and I have one question regarding Codeigniter mysqli_driver
I have uploaded my apps into web server but there was an error that saying : 
Call to undefined function mysqli_init()...in sys/database/drivers/mysqli/mysqli_driver.php on line 103..
I dont know how to fixit. FYI: my host running PHP 5.4.30, Apache 2.2.27, MySQL version 5.5.37-cll. 

If i use my offline server (using php 5.5.11), there is no such issue come up.
If there are allready closed issues on this, please guide me to it.
Thanks in advance.

Regards,

**Comment by Qnatz** [comment]
Hey narfbg;
mysqli_init() is in system\database\drivers\mysqli\mysqli_driver.php on line 125
and this is supposed to initialize mysqli.... amhaving sam problem n failed to solve

**Comment by mwhitneysdsu** [comment]
If mysqli_init() is not defined, you need to install/load the MySQL Improved (mysqli) extension. Check with your host or read the relevant section of the PHP manual: http://php.net/manual/en/book.mysqli.php This is not an issue with CodeIgniter.

**Comment by kakysha** [comment]
@Qnatz you must be very studios to fail resolving this issue lol
