### ISSUE TITLE
Query builder: IS NOT NULL support

### ISSUE THREAD

**Issue by ostrolucky** [bcit-ci/CodeIgniter#3194]
It seems CodeIgniter's Query Builder is able to construct query with IS NULL statement

``` php
$this->db->where('column', NULL);
```

But is not able to do the opposite.  Neither works, it doesn't add NULL into query string and takes comparator literally:

``` php
$this->db->where('column !=', NULL);
$this->db->where('column IS NOT', NULL);
```

Generates  (notice missing NULL on end): 

```
WHERE `column` !=
WHERE `column` IS NOT
```

One have to use this:

``` php
$this->db->where('column IS NOT NULL');
```

Now think what one needs to do  this if NULL may and may not be stored in variable. Then I need to do something like this I guess:

``` php
if (is_null($var))
    $this->db->where('column  IS NOT NULL');
else
   $this->db->where('column !=', $var);
```

Now I need to do query builder's  job.

**Comment by 5432112** [comment]
how can set optional filed in codeIgniter    
view form and controller

**Comment by 5432112** [comment]
file(any document) uploading is propperly but i want this is optional   but now i am facing database notnull error

**Comment by chiranjit04** [comment]
Just do this it is used code,working properly.
$this -> db -> where('basic_sal !=','');

**Comment by narfbg** [comment]
@chiranjit04 

1. An empty string, or a single space is not the same thing as NULL.
2. This is a bug tracker; not a place for random suggestions. Please don't ressurect closed issues.

If you want to help people out, you can do that on our [forums](https://forum.codeigniter.com/).
