### ISSUE TITLE
Common.php: The function html_escape() needs additional parameter $double_encode = TRUE

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#3201]
html_escape() wraps in a specific way htmlspecialchars() http://php.net//manual/en/function.htmlspecialchars.php

As of PHP 5.2.3 htmlspecialchars has the fourth optional parameter $double_encode = true.

$double_encode = FALSE prevents escaping the input string twice.

Here is a case when this feature is useful - translated from human language html-attribures (title, alt, value, placeholder, data-*). It is not sure whether a translator provides a manually escaped string or not, especially for legacy applications. Using the option $double_encode = FALSE solves this.

**Comment by csksm** [comment]
The fix changed the original behavior when applied to an associative array.

Test case:
```
$array = array( "zero" => 0, "one" => 1 );
print_r(html_escape($array));
```

Expected:
```
Array(
    [zero] => 0
    [one] => 1
)
```

Actual:
```
Array(
    [0] => 0
    [1] => 1
)
````

**Comment by ivantcholakov** [comment]
I confirm that there is a change of the original behavior, it is hidden within the function array_map(). Maybe for some preserving keys is valuable.

@narfbg Is there need for a correction? I think about usage of array_walk_recursive() function.

**Comment by ivantcholakov** [comment]
Or just array_walk(), I'll see which one is suitable.

**Comment by ivantcholakov** [comment]
@narfbg I would like to make a PR for this, but I wonder on which branch is to be done and for which release the changelog note is to be added. This is the prepared code:

```php
if ( ! function_exists('html_escape'))
{
	/**
	 * Returns HTML escaped variable.
	 *
	 * @param	mixed	$var		The input string or array of strings to be escaped.
	 * @param	bool	$double_encode	$double_encode set to FALSE prevents escaping twice.
	 * @return	mixed			The escaped string or array of strings as a result.
	 */
	function html_escape($var, $double_encode = TRUE)
	{
		if (empty($var))
		{
			return $var;
		}

		$charset = config_item('charset');

		if (is_array($var))
		{
			array_walk_recursive($var, '_html_escape_callback', array($charset, $double_encode));
			return $var;
		}

		return htmlspecialchars($var, ENT_QUOTES, $charset, $double_encode);
	}

	function _html_escape_callback(& $value, $key, $options)
	{
		$value = htmlspecialchars($value, ENT_QUOTES, $options[0], $options[1]);
	}
}
```

**Comment by csksm** [comment]
FYR, this is my proposed change, which probably simpler?
```php
    function html_escape($var, $double_encode = TRUE)
	{
		if (empty($var))
		{
			return $var;
		}

		if (is_array($var))
		{
            array_walk($var, function(&$value, $key, $double_encode)
            {
                $value = html_escape($value, $double_encode);
            });

            return $var;
		}

		return htmlspecialchars($var, ENT_QUOTES, config_item('charset'), $double_encode);
	}
```

**Comment by ivantcholakov** [comment]
@csksm It will not work for PHP 5.2.4, which as far as I know is still silently supported.
