### ISSUE TITLE
Severity: 4096

### ISSUE THREAD

**Issue by joaocosta-azores** [bcit-ci/CodeIgniter#3217]
I used to output my view inside my main view like this:

```
public function index()
{
    $this->template->load('tpl/bp-tpl', 'content\container');
}
```

Then inside my "bp-tpl.php" view, simply would output my 'content/container' like this:

```
<?php echo $contents; ?>
```

But yesterday when starting a new project using this template library as always would keep getting this error:

```
Severity: 4096

Message: Object of class CI_Loader could not be converted to string

Filename: tpl/bp-tpl.php
```

After a waste afternoon trying to find the problem, this morning i start looking better and noticed that now i can't output my view inside my main view like this:

```
<?php echo $this->load->view('content/container'); ?>
```

To avoid get the error i can't output the view with "echo". I simply just load the view inside the main view and no error at all. Also all the content is loaded without problems.

```
<?php $this->load->view('content/container'); ?>
```

I'm sure i would always "echo" my views inside my main view. Now i can't echo or i get this error.
Any idea why echo a view is no longer necessary?
Hope i made myself clear.

**Comment by yahyaerturan** [comment]
How should we do "you tell CI_Loader::view() to return the loaded content". I proudly installed CI3 but having issues now..

**Comment by yahyaerturan** [comment]
Ok, errors comes from ```<?=$this->load->view();?>```. When not echo-ing, it works just fine. ```<?php $this->load->view();?>```

**Comment by EpicKris** [comment]
I'm having the same issue as @yahyaerturan even when telling `$this->load->view()` to return, I would have thought by returning I would have to echo, but this does not seem to be the case.

**Comment by sid3214** [comment]
> `echo`-ing was _never_ necessary. Furthermore, that is only possible if you tell `CI_Loader::view()` to return the loaded content, it doesn't do that by default.

thank you for this
