### ISSUE TITLE
 flashdata erased when using a hook "pre_controller"

### ISSUE THREAD

**Issue by luger95** [bcit-ci/CodeIgniter#3234]
Hello,
I just put up a hook "pre_controller"

I noticed that flashdata are used in this hook, but after they are no longer.
I am using CI 2.1.3

THX

**Comment by gphg** [comment]
It isn't erased. It isn't initiated yet. The `get_instance()` returns null. The `$CI` (or `get_instance()`) inside the hook returns null.

You may change the `pre_controller` onto `post_controller_constructor`.

Might related to my issue: https://github.com/bcit-ci/CodeIgniter/issues/6068
