### ISSUE TITLE
Moving logic from create_links() in pagination

### ISSUE THREAD

**Issue by aanbar** [bcit-ci/CodeIgniter#3250]
I am thinking that create_links() method shouldn't do all the work, it should just create links in html form.

What if we add a protected method that runs at the end of initialize which generates the data like 'next_url', 'prev_url', 'page_numbers' ...etc;

then these data are available to access via getters which create_links() will use, this would make it easier to provide json response of pagination for APIs

**Comment by sv3tli0** [comment]
Perhaps a refactorisation of this lib will be a good point in future 3.1 version ? 
I am volunteer to do it when there is an accepted idea for its next version :)

**Comment by narfbg** [comment]
I don't imagine anyone still actively looking at this, or anything related to the shitty Pagination library for that matter, but ... pull requests are good and issues just sitting open like this one are useless.
