### ISSUE TITLE
Problems with drivers (autoloading and extending)

### ISSUE THREAD

**Issue by ruthlessfish** [bcit-ci/CodeIgniter#327]
Currently you cannot extend or autoload drivers out of the box. Is this intended or just functionality that hasn't been written yet?

It would be nice if drivers were extendable like libraries so that we can create custom child drivers in applications. This isn't currently possible because the CI_Loader does not support loading extended libraries from subdirectories (i.e. libraries/Driver_name/MY_Driver_name.php) so there's no way to add the new driver to the $valid_drivers array in the parent driver class. Another issue with extending is that CI_Driver_Library completely ignores the subclass prefix when loading its children so even if the parent was able to be loaded the children still wouldn't be.

Right now the only system driver is cache but soon parser will be a driver and it's possible that other libraries may follow (email, image_lib would be good candidates) so I imagine this will become a bigger issue over time if not dealt with.

I have code that does this if this but I think it's on my other computer. I will post it when I find it.

**Comment by cauboy** [comment]
Hey. Just wondering if someone can help me…

I'm using Codeigniter 2.1.3 and I am wondering how one would actually use that feature.

I've added the file
```
application/libraries/Cache/drivers/MY_Cache_memcached.php
```
with the following content
```
class MY_Cache_memcached extends CI_Cache_memcached {
	public function __construct()
	{
		parent::__construct();

		die('Testing…');
	}
}
````
but nothing happens. What's wrong?

**Comment by thominj** [comment]
@cauboy - I think that this is only available in the develop branch, the changes made in that pull request are not showing up in 2.1, 2.2, or master branches.

**Comment by cauboy** [comment]
@thominj -  That's a pitty. But thanks for the info.
