### ISSUE TITLE
potential host header XSS

### ISSUE THREAD

**Issue by Dutchy-** [bcit-ci/CodeIgniter#3292]
There exists a potential XSS in form_open under these conditions:

1) The server uses a default virtual host
2) No site name configured in the codeigniter configuration
3) form_open is called without a full URL
4) An attacker is able to change the Host header in the request

The following call will result in XSS:

```
curl -v -H 'Host: " onmouseover=alert(1) "' http://mysite.com/page
```

Result:

```
<form action="http://" onmouseover=alert(1) "/page" method="post" accept-charset="utf-8">
```

The offending line is most likely https://github.com/bcit-ci/CodeIgniter/blob/develop/system/helpers/form_helper.php#L80

A workaround solution is simple enough by removing conditions 1 or 2 on any vulnerable site.
This was tested using version 2.1.4 and it seems likely that it still exists in current versions.

**Comment by Jamalc0m** [comment]
c
