### ISSUE TITLE
Double single quotes on "DBForge"

### ISSUE THREAD

**Issue by Theremsoe** [bcit-ci/CodeIgniter#3301]
I found this problem when create a field "ENUM" with dbforge class.

``` php
'type' => [ "type" => "ENUM", "constraint" => [ "foo", "bar" ]
```

And Output is this:

``` sql
`type` ENUM(''foo'',''bar'') NOT NULL
```

The dbforge class generate an extra single quote and trigger this SQL (MySQL) error:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'foo'',''bar'') NOT NULL
```

My temporal solution:

``` php
/* Location: ./system/database/DB_forge.php */
/* Method: _process_fields
/* Line: 817 */

case 'SET':
                        $attributes['CONSTRAINT'] = $this->db->escape($attributes['CONSTRAINT']);

                        // Bug => remove extra single quote generated by "escape" function
                        $attributes['CONSTRAINT'] = array_map(function( $input ){ return str_replace( "'", "", $input ); }, $attributes['CONSTRAINT'] );

                        $field['length'] = is_array($attributes['CONSTRAINT'])
                            ? "('".implode("','", $attributes['CONSTRAINT'])."')"
                            : '('.$attributes['CONSTRAINT'].')';
                        break;
```

**Comment by orionstar** [comment]
It's still an issue in CI 3.0.3.

I am using Apache 2.4, PHP 5.6.3

https://gist.github.com/orionstar/356e32833a09f4cbc9b0

ERROR - 2015-11-23 17:45:39 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'text'',''textarea'',''password'',''select'',''select-multiple'',''radio'',''chec' at line 6 - Invalid query: CREATE TABLE `settings` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`slug` VARCHAR(255) NOT NULL UNIQUE,
	`title` VARCHAR(255) NOT NULL,
	`description` TEXT NOT NULL,
	`type` ENUM(''text'',''textarea'',''password'',''select'',''select-multiple'',''radio'',''checkbox'') NOT NULL,
	`default` TEXT NOT NULL,
	`value` TEXT NOT NULL,
	`options` TEXT NOT NULL,
	`module` VARCHAR(255) NOT NULL,
	`order` INT(10) NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`updated_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	CONSTRAINT `pk_settings` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci

**Comment by afbora** [comment]
https://github.com/bcit-ci/CodeIgniter/issues/4245 issue fixed https://github.com/bcit-ci/CodeIgniter/commit/9e2c7b9dd7e87a94c5a3696bc326cbbec5da7bb8 on 3.0.4 milestone. But guess not merged with develop brach yet. You should change manual.

**Comment by orionstar** [comment]
@afbora Thx for the suggestion, didn't saw the new issue. :S
