### ISSUE TITLE
PDO Driver loses results

### ISSUE THREAD

**Issue by parkars** [bcit-ci/CodeIgniter#3333]
CodeIgniter 2.2.0
When using the pdo driver, the row count returns a value greater than 0. However the result_array() returns an empty array. I switched to mysqli, row count and result_array returned correct values from DB. I var_dump the PDO object and it doesn't contain results. Any chance the results are being lost after the query.

**Comment by mxcoder** [comment]
I might be wrong, but I think its dues this code:
File: ./system/database/drivers/pdo/pdo_driver.php
Line: 196
```
if (is_numeric(stripos($sql, 'SELECT')))
{
    $this->affect_rows = count($result_id->fetchAll());
}
else
{
    $this->affect_rows = $result_id->rowCount();
}
```

fetchAll will move the cursor to the last position.
This code should be just:
```
$this->affect_rows = $result_id->rowCount();
```

**Comment by narfbg** [comment]
I had left this open simply because it was reported probably for the 10th time, but it is not fixable in the 2.x version tree ... with 3.0rc released and the final version following soon, hopefully there won't be any more people trying to use PDO with CI2.
