### ISSUE TITLE
$this->db->disctinct() appears to not be doing a distinct

### ISSUE THREAD

**Issue by danetch** [bcit-ci/CodeIgniter#3430]
Hi,
looks like Active record $this->db->disctinct() doesn't do a distinct, merely a select().
I'm using >select('DISTINCT my_column_name',FALSE); in the meantime and it works well, but thought i would tell you.
i'm using CI 2.2.
Thanks,
m

**Comment by crimson-labs** [comment]
$this->db->disctinct() should be $this->db->distinct() ?

**Comment by narfbg** [comment]
Can't reproduce.
