### ISSUE TITLE
Password Generation Component

### ISSUE THREAD

**Issue by sarciszewski** [bcit-ci/CodeIgniter#3432]
In lieu of rolling our own, let's decide on a third party to incorporate.

I'm envisioning something similar to `ircmaxell/password_compat` being included in `system/core/compat`, thought we may want to plan third-party components to be in a more obvious location.

**Comment by narfbg** [comment]
I'm against *shipping* a third-party component together with CI.

The goal of using a third-party component is to avoid duplicating code and maintenance efforts. Including a copy of a third-party library in the framework's codebase means that the library is maintained *as a part* of the framework and then you fail to meet that goal.

I'd rather recommend a popular library in the documentation instead.

**Comment by safecat** [comment]
Why not use composer to manage third party package?

**Comment by sunkang2008** [comment]
composer not work in china. CI is good for phper who in china. thank you for you effort

**Comment by sarciszewski** [comment]
https://github.com/bcit-ci/CodeIgniter/blob/21898a45f323bb74ef6e5ee8cf21c3397467665b/system/helpers/string_helper.php#L195-L240

Also, we really ought to deprecate this and wrap the password library instead.

https://github.com/ircmaxell/RandomLib is a very solid choice. @ircmaxell

**Comment by stefkes** [comment]
random_string can (and probably should only) be used for non-password scenarios. It's a string helper and not a password helper. I use it for example to generate order ids.

**Comment by mehdibo** [comment]
what if we add password option to random_string ?
