### ISSUE TITLE
PSR-0 Compliance

### ISSUE THREAD

**Issue by ColonelMoutarde** [bcit-ci/CodeIgniter#3438]
Hello,
For version 4.0, I propose the support PSR-0 for the management of autoloading classes and namespaces.
This development will make full use of advanced PHP5.3.

**Comment by Quix0r** [comment]
What @narfbg means is that you @ColonelMoutarde may look at the forums: https://forum.codeigniter.com/thread-62615.html?highlight=PSR

**Comment by narfbg** [comment]
The thread you've linked didn't exist at the time, and that is not what I meant.
Please don't resurrect more years-old issues to speak on my behalf.

**Comment by Quix0r** [comment]
Sure thing.
