### ISSUE TITLE
CI_DB_driver::field_data fails to provide valid values for fields of type ENUM

### ISSUE THREAD

**Issue by sneakyimp** [bcit-ci/CodeIgniter#3443]
I know that MySQLI will tell you for an enum field what the valid values are. Seems to me this is pretty important information when you are trying to examine the properties of a db table.
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_driver.php

**Comment by narfbg** [comment]
There's a ton of ways to output this information, yet none of them is appropriate IMO. Also, any DB-related feature in CI must be supported by *most* databases, not just MySQL.
