### ISSUE TITLE
MySQL  driver produces suppressed PHP Fatal errors

### ISSUE THREAD

**Issue by chrissound** [bcit-ci/CodeIgniter#3445]
If I set my application/config/database.php to use the 'mysql' driver and it fails it seems to fail silently.

Code Ignitor - v2.2 release.
PHP - v5.6.4

**Comment by narfbg** [comment]
On another thought ... screw that. If you're on PHP 5.5, just switch the driver to 'mysqli' or suppress your `$this->load->database()` calls on your own.

1dc43aaefb341daaae10841e5ca2504ba9b03d7c
