### ISSUE TITLE
Controller issue

### ISSUE THREAD

**Issue by Shyim** [bcit-ci/CodeIgniter#3451]
If the controller "Index" means he will be called twice.

Code:
class Index extends CI_Controller {
	public function index() {
		echo "Test";
	} // END public function index()
} // END class Index extends CI_Controller

Output:
TestTest

**Comment by narfbg** [comment]
It's not overriding, like @ivantcholakov said - it's a PHP4 style constructor - method name matching a class name will be executed as a constructor, unless under a namespace (and probably if you don't have a `__construct()` method, not sure). It's just how PHP works, can't do nothing about it.

**Comment by Llbe** [comment]
The old style constructor won't be called if a __construct exists. This will also prevent a deprecation warning in PHP 7.

**So to fix this issue**, simply add an empty construct: public function __construct () {}
