### ISSUE TITLE
Can't load language file containing hyphen in idiom

### ISSUE THREAD

**Issue by includebeer** [bcit-ci/CodeIgniter#3453]
I found a problem with the language names containing a hyphen (portuguese-brazilian, simplified-chinese, traditionnal-chinese). When I try to switch language and load the language files with $this->lang->load($lang_file, $idiom) it loads the default language file because the idiom contains non alphabetic characters, '-' is rejected by ctype_alpha().

**Comment by ZombieProtectionAgency** [comment]
The ctype_alpha check was added by @narfbg to fix issue #1268. I think `! ctype_alpha($idiom)` can be changed to `preg_match('/[^A-Za-z\-]/', $idiom)` without hurting anything. (I was going to use this as an opportunity for my first commit/PR but the Github editor added a new line and I can't figure out how to remove it...)

**Comment by jim-parry** [comment]
Would it be better to use underscores in the idiom names? Underscores are supposed to be legal in locale names, and it would make sense that they be so in idiom names as well.
This would be a correction to the translations repository, and not this one.

**Comment by includebeer** [comment]
@jim-parry Underscores will also be rejected by ctype_alpha. In my opinion the regex is a better solution.

**Comment by ivantcholakov** [comment]
```php
if (empty($idiom) OR preg_match('/[^A-Za-z\-_]/', $idiom))
```
