### ISSUE TITLE
Return by reference in Core Model

### ISSUE THREAD

**Issue by aanbar** [bcit-ci/CodeIgniter#3454]
Can we change core/Model.php ```__get```  to ```&__get``` so it returns by reference? 

This would allow modifying public variables defined within controller from a Model.

Currently it throws this error.
```Indirect modification of overloaded property xxx has no effect```

**Comment by narfbg** [comment]
Getters are not executed in write context, so how would that allow you to modify anything?

**Comment by aanbar** [comment]
I have tested it locally & when returned by reference I am able to modify properties.

Steps to reproduce:
- created a public $data array in Controller.
- Added an item to it through a Model.

When modifying __get it works, but this might create a problem with double reference that's why I am asking here instead of submitting a PR as I am not 100% sure it's a clean solution.

**Comment by ivantcholakov** [comment]
@aanbar

Even if it works, the idea is not clean. Isolation of contexts is widely recommended as a good practice and it is more intuitive it to be expected here too.

You can pass an array by reference from the controller to the related model methods. Or, if you want this array (within the controller) to be accessible everywhere within the model, you may add to the model a special setter method that passes the array by reference and assigns it to a protected model's property. 

The point is, if you make this pass explicitly, code would be easy for debugging.

**Comment by narfbg** [comment]
I agree with @ivantcholakov, if you need to modify a controller's property from within a model, you better be explicit about it or that operation doesn't belong in the model in the first place.

Not much value in this feature.
