### ISSUE TITLE
Import page code

### ISSUE THREAD

**Issue by WibbenZ** [bcit-ci/CodeIgniter#3456]
Hey got a problem, I use a {$main} function with Smarty to load the view code, but with CodeIgniter it loads it above the head code, how can I make CodeIgniter not load the view and let me use the {$main} in my layout.tpl file insted?
Im doing this to not be forced to use 3 layout files and insted just use the one layout.tpl.
Regards

**Comment by jim-parry** [comment]
This is a forum "issue", not a problem that needs fixing in the codebase.
I don't know about Smarty, but with the built-in parser, the parsing method has a third parameter  which if set to true lets you capture the template output, and which if not set sends the output to the browser stream, which could be what you are describing (hint: pastebin your code when you make a post in the forum).

**Comment by WibbenZ** [comment]
@jim-parry ive been trying to register but the captcha system seems to be bugged as hell, could you tell me where the code loads the page code?
Smarty does not handle that, I use ob functions making it into a variable so I can use the variable in the "text" part of the layout.

**Comment by jim-parry** [comment]
email me (jim_parry@bcit.ca) ... this discussion does NOT belong on github
