### ISSUE TITLE
when global XSS is enabled, input sanitization runs unconditionally

### ISSUE THREAD

**Issue by joeauty** [bcit-ci/CodeIgniter#346]
when global XSS is enabled, it seems impossible to include any sort of login form where passwords may include characters such as &. Shouldn't $this->input->post('var', FALSE) not only disable XSS cleaning, but also sanitization, or there otherwise be some option to not sanitize these sorts of fields?

**Comment by nmfzone** [comment]
Hey guys, anyone in here?
May i know, when i was set global_xss_filtering TRUE, must i add xss_clean in form_validation rules?
And what is the effort if i was add and was not add xss_clean in form_validation when global_xss_filtering TRUE?
