### ISSUE TITLE
$this->db->list_fields($table) missing parameter

### ISSUE THREAD

**Issue by paulbunyannet** [bcit-ci/CodeIgniter#3460]
A PHP Error was encountered

    Severity: Notice

    Message: Undefined variable: table

    Filename: database/DB_driver.php

    Line Number: 1236

Looks like the [$table variable is missing](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_driver.php#L1233) and because of this the query runs a `SHOW COLUMNS FROM` query., missing the table name. Just did a `composer update` call this morning and this issue popped up.

**Comment by narfbg** [comment]
Sorry, my bad. Apparently I've removed the whole parameter when I only wanted to remove the default value. :)

**Comment by paulbunyannet** [comment]
Thanks!
