### ISSUE TITLE
PHP Compatibility

### ISSUE THREAD

**Issue by inadarei** [bcit-ci/CodeIgniter#3469]
There's at least one issue: https://github.com/bcit-ci/CodeIgniter/issues/2251 where critical upgrade was refused due to need for "PHP 5.2.4 compatibility".

Here's the thing: even 5.2 was end-of-life-ed 4 (!!!) years ago and even 5.3 was end-of-life-ed four months ago. Using these versions is simply insecure and reckless. Nobody should be using PHP version prior to 5.3 in production.

CodeIgniter 3.x is not even released yet and its fate is tied to PHP version that was discontinued 4 years ago? No major framework or CMS supports 5.3 anymore.

Feels like a very candid discussion is overdue here.

**Comment by mohammadhzp** [comment]
Did you see #3450 ? I think you'll get what's going on

**Comment by inadarei** [comment]
Thanks
