### ISSUE TITLE
CI 3.0.0 has HMVC support?

### ISSUE THREAD

**Issue by bartmika** [bcit-ci/CodeIgniter#3472]
In CodeIgniterI 2.2.0 I was able to load a Controller within a Controller with no problems using sessions, but when I try doing the same thing with CI 3.0.0 I get the following error:

Unable to locate the specified class: Session.php

Our web-app uses a tremendous amount of AJAX calls so it's necessary we need to use HMVAC. On the forum I've read that 'HMVC is no longer supported': https://ellislab.com/forums/viewthread/242406/

Can I get some help on this issue? I followed the link: https://www.chuongduong.net/ci3/installation/upgrade_300.html

Our config.php looks like this:
![screen shot 2015-01-12 at 5 57 52 pm](https://cloud.githubusercontent.com/assets/5767602/5712944/a14b0d6a-9a84-11e4-97c9-01c886fe7796.png)

And our autoload.php looks like this:
![screen shot 2015-01-12 at 5 57 32 pm](https://cloud.githubusercontent.com/assets/5767602/5712952/af7bdb4e-9a84-11e4-84ce-9d54b996eedb.png)

Thanks,
-Bart

**Comment by jim-parry** [comment]
This is a support issue, and not a bug.
As such, it should be raised on the forum (forum.codeigniter.com) and not here on github.
I don't use HMVC, but there are a bunch of folks on the forum that do.
