### ISSUE TITLE
The new Session library: 'A non well formed numeric value encountered'

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#3473]
I have an error that is hard to be explained. This is what I can say for sure, now:

PHP 5.6.4 on Ubuntu 14.10

system/libraries/Session/Session_driver.php, line 126.

https://github.com/bcit-ci/CodeIgniter/blob/feature/session/system/libraries/Session/Session_driver.php#L126

```php
		if (($this->_lock = sem_get($session_id.($this->_config['match_ip'] ? '_'.$_SERVER['REMOTE_ADDR'] : ''), 1, 0644)) === FALSE)
```

I see:

```
Severity: Notice

Message: A non well formed numeric value encountered

Filename: Session/Session_driver.php

Line Number: 126
```

The first parameter of sem_get() is documented as integer, but a string (non-numeric) is passed in our case.
http://php.net/manual/en/function.sem-get.php

Edit: The other error I've mentioned was my stupid mistake, it just gave me a chance to see this notice.

**Comment by dbernar1** [comment]
The string I see there is the concatenation of the IP address onto the session ID. Do you have match_ip set in your config?

If you do, maybe try to see whether you get the error without the match_ip setting.

**Comment by ivantcholakov** [comment]
```php
$config['sess_match_ip']        = FALSE;
```
But this does not matter. The session id is something like this "ddc0135cc813f0a4cca92f86c205530376795a9b".

I don't know how sem_get() works internally, I don't know whether the mismatching type would be a problem alone or an indication of something more.

**Comment by dbernar1** [comment]
Did you try to var_dump() the value that is returned and inspect it?

**Comment by ivantcholakov** [comment]
Yes, this is how I copy/pasted the value string(40) "ddc0135cc813f0a4cca92f86c205530376795a9b"
```php
var_dump($session_id.($this->_config['match_ip'] ? '_'.$_SERVER['REMOTE_ADDR'] : '')); exit;
```

**Comment by narfbg** [comment]
Oh boy ... you two will turn this into a chatroom if I don't interfere.

It's a bug, let me deal with it.

**Comment by narfbg** [comment]
So, basically ... semaphores were a stupid idea for this. You better don't use a database other than PostgreSQL and MySQL for storing session data, as it won't have locks.
