### ISSUE TITLE
form validation CI v3.0 dev with xss_clean: error

### ISSUE THREAD

**Issue by casa10** [bcit-ci/CodeIgniter#3482]
hye,
i'm testing CI v3.0 dev (download on www.codeigniter.com) and when i put "xss_clean" on form validation i had this error : "Could not find the language line "form_validation_xss_clean"
- My config : $config['global_xss_filtering'] = TRUE;
- i loaded form helper on autoload.php: $autoload['helper'] = array('form', 'url','html') ;
- This is my code validation in my controller: 
$this->load->library('form_validation');
$this->form_validation->set_rules('login','Login','trim|strtolower|strip_tags|xss_clean|required');
$this->form_validation->set_rules('mdp','Mot de passe','trim|xss_clean|required');
if ($this->form_validation->run() == TRUE)
{  
    $this->load->view('success_page');
}
else
{
    $this->load->view('mypage');
 }
- When i valid, form_validation->run is FALSE because "mypage" is reloaded whereas i try with simple values. Exemple: login = "dva" and mdp = "salut" and in the log files i'have this messages : 
"Could not find the language line "form_validation_xss_clean"
"Could not find the language line "form_validation_error_message_not_set"
- if i do: $config['global_xss_filtering'] = FALSE ; and i try my code, i have the same result.
- In the documentation, i don't see this problem. Can you help me? or is i an error in form_validation?
Thanks.

**Comment by narfbg** [comment]
You haven't updated all of your files, nor read the upgrade instructions.

Also, please post on the [forums](http://forum.codeigniter.com/) if you're looking for somebody to help you. We only accept bug reports here.

**Comment by goFrendiAsgard** [comment]
Sorry @narfbg , just ignore this.
@casa10 : Somewhere in your controller, you have set xss_clean. Remove the rule and everything should be okay: http://www.codeigniter.com/userguide3/installation/upgrade_300.html#step-13-check-for-usage-of-the-xss-clean-form-validation-rule
