### ISSUE TITLE
Bug in Upload library

### ISSUE THREAD

**Issue by josewilsoncc** [bcit-ci/CodeIgniter#3489]
Sorry for insisting

I tried with CodeIgniter-develop 3.0 and fail, it throws the message: Undefined property: Upload::$upload.

This works in the previous versions (CodeIgniter 2.x)
_________________
Upload library throw:
Severity: Notice --> Undefined property: Upload::$upload
Even after being included.

**Comment by Razican** [comment]
Do not open another issue, please. This is a duplicate of #3487.

**Comment by ivantcholakov** [comment]
What line?

**Comment by josewilsoncc** [comment]
The error occurs when call the function "$ this-> upload-> do_upload ()", this happens even when the library 'upload' is loaded "$this->load->library('upload', $config)", this did not happen before, is something recent. (I sorry for my english, I just want to contribute)

**Comment by josewilsoncc** [comment]
The error occurs when call the function "$ this->upload->do_upload ()", this happens even when the library 'upload' is loaded "$this->load->library('upload', $config)", this did not happen before, is something recent. (I sorry for my english, I just want to contribute)

**Comment by narfbg** [comment]
Post it on the forums, not here.
