### ISSUE TITLE
ar_orderby is broken?

### ISSUE THREAD

**Issue by rohan-peters** [bcit-ci/CodeIgniter#3492]
In some research i am using a tuts plus CI build a CMS tutorial for some ideas etc. i came across this little bit of code

if (!count($this->db->ar_orderby)) {
            $this->db->order_by($this->_order_by);
}

it results in Message: Undefined property: CI_DB_mysqli_driver::$ar_orderby.

now if this has been removed from CI 3 then all good, i will work something out, but if not, might be worth looking into.

**Comment by ashiina** [comment]
As far as I know, `ar_orderby` is an internal property, and is not publicly supported = is not meant to be used externally. Therefore I don't think supporting it in CI 3 is required.

**Comment by narfbg** [comment]
What @ashiina said - it was never part of the public API.

**Comment by pradeep-rajapaksha** [comment]
Using this it can be resolve! ;)
`if(!count($this->db->order_by($this->_order_by))) 
        {
            $this->db->order_by($this->_order_by);
        }`
