### ISSUE TITLE
Remove license headers at top of files

### ISSUE THREAD

**Issue by vlakoff** [bcit-ci/CodeIgniter#3498]
Follow-up to #3476.
Separate issue as we are now specifically talking about the (huge) license headers.

<br>I think that as long as we have these info in each file we are fine:
* What license? MIT
* To who? BCIT

The relevant licensing info, straightforward. Two lines.

The rest is unnecessary redundancy. These belong to the root directory (you know, the usual *README*, *LICENSE*, *AUTHORS*...):
* Full license text (thankfully it is short)
* Authors listing (EllisLab, BCIT)
* Project description (website, etc.)

In fact, doing this way would be better for the lawyers, because the "metadata" included in each file is the only relevant one about licensing, so that it focuses on it.

<br>A few additional comments:
* @narfbg Remember that `/application` was previously inside `/system` ;-)
* @webvitaly We already have a license file in the root directory.

**Comment by Razican** [comment]
As I said in the other issue, my opinion is that having the reference to the license and the authors is enough, and that we do not need to copy the license in each file. If it was GPL, would you copy the whole license in each file? that would double the project size.

**Comment by narfbg** [comment]
@vlakoff 

I don't understand why you insist on removing or shortening the comment blocks under system/ ... It has never bothered me and nobody spends nearly as much time as myself looking at those files.

Are you scrolling until you find what you want or ...? Really, I don't get it.

@Razican 

Thankfully, it's not GPL. If it was completely up to me, it would've been the ISC license, which is even shorter (but with literally the same meaning). Still, MIT is short enough not to care about that.

**Comment by ivantcholakov** [comment]
I think, full license headers protect owner's rights better. The files may be used outside CodeIgniter framework, people may bundle specific libraries and drivers within different projects. Assuming this possibility it would be better these full headers to stay.

**Comment by vlakoff** [comment]
@narfbg In fact I agree with you:

* Those in `/system` shouldn't annoy users, and so can be kept.
* Those in `/application` are annoying, and should be trimmed as I posted above, or removed (there isn't much, if anything, to "protect"). I'm for the latter.

**Comment by narfbg** [comment]
@vlakoff 

I guess I misunderstood your reasoning to open another issue then ... it was just a matter of @jim-parry giving another +1 in the previous thread.

**Comment by vlakoff** [comment]
Long story short: #3499. Feel free to suggest any improvement.

**Comment by jim-parry** [comment]
The existing comment blocks in sorce code files under system/ and in index.php are appropriate.
Quoting OSI:
[quote]To apply the MIT license to your project, you must add the file license.txt into the root directory of your project. 
Another step is to include a notice in all of the source files of your project. It should be at the top of each source file in a multi-line comment. [/quote]

**Comment by jim-parry** [comment]
As for the comment blocks in source code inside the applicaiton/ folder, they can be shortened, but not eliminated, as we are not trying to assert collective copyright over example code.

My suggestion:

/**
* CodeIgniter(tm): An open source application development framework for PHP
*
* @package	CodeIgniter
* @author	CodeIgniter Dev Team
* @copyright	Copyright (c) 2008 - 2014, EllisLab, Inc. (http://ellislab.com/)
* @copyright	Copyright (c) 2014 - 2015, British Columbia Institute of Technology (http://bcit.ca/)
* @license	http://opensource.org/licenses/MIT MIT License
* @link	http://codeigniter.com
* @since	Version 1.0.0
* @filesource
*/

**Comment by jim-parry** [comment]
Comments have been made about Laravel & WordPress, and their lack of comment blocks.
It appears to me that they do not comply with the OSI suggestions for applying an open source license ... even though they include a license.txt in the root of their project, they do not reference that in a comment block at the top of source code elements.

**Comment by vlakoff** [comment]
The "[(tm)](https://en.wikipedia.org/wiki/Unregistered_trademark)" you added is just useless ;-)

Your proposal would already be shorter/better than the current blocks. I suggest this:

    /**
     * CodeIgniter - An open source application development framework for PHP
     *
     * @package	CodeIgniter
     * @author	CodeIgniter Dev Team
     * @copyright	Copyright (c) 2008 - 2014, EllisLab, Inc. (http://ellislab.com/)
     * @copyright	Copyright (c) 2014 - 2015, British Columbia Institute of Technology (http://bcit.ca/)
     * @license	http://opensource.org/licenses/MIT	MIT License
     * @link	http://codeigniter.com
     * @since	Version 1.0.0
     * @filesource
     */

**Comment by jim-parry** [comment]
Some of the stuff I have seen shows the "(tm)", some doesn't. I don't know if it helps/hinders.

I am fine with the header you suggest, for application/*

**Comment by narfbg** [comment]
@jim-parry 

> As for the comment blocks in source code inside the applicaiton/ folder, they can be shortened, but not eliminated, as we are not trying to assert collective copyright over example code.

That seems like a contradiction to me.

**Comment by jim-parry** [comment]
The example code is provided as an example or as a starter, not as something that would fall under the conventional interpretation of "intellectual property", no?

The possible exception I see would be index.php, where missing or mis-interpreted settings might affect the correct/intended operation of the framework.

**Comment by jim-parry** [comment]
If i recall correctly, application/ was treated differently than system/ from the beginning. EllisLab planned to release the framework under OSL3, but application/ under AFL3. I don't think there has been any claim that application/ is *part of* the framework, hence my apparently contradictory suggestions earlier.

**Comment by narfbg** [comment]
That is correct, yes.

What I don't understand is why the block can't be removed from application/ files, given that we don't want to claim any copyrights over them? (which I don't think is possible anyway)

**Comment by jim-parry** [comment]
Good point :-/ The purpose of having a license is to make it explicit that others can reuse a distributed piece of software, and many hold that such rights are questionable without any license at all. Is that implied by distributing the starter as part of the framework download, or would the absolute minimum be a comment at the top of the application/ files, along the lines of

/* Example released under the MIT license */

**Comment by vlakoff** [comment]
`config/*` and `controllers/Welcome.php` aren't really subject to copyright, however `views/errors/*` could be considered as part of the framework…

All of that have become overthought. https://github.com/vlakoff/CodeIgniter/commit/dcbf6049ffff9ce6e27b79d10cc35890d00b646b would be fine for the time being.

**Comment by narfbg** [comment]
Technically, yes - no license means that a user would need to ask for permissions instead of assuming them.

But as we've already said numerous times - examples and config files aren't subject to copyright. And the license.txt file is enough anyway - we put license notices for the framework's code to avoid ambiguity, but for stuff like Welcome.php that's too much IMO.

**Comment by jim-parry** [comment]
ok - uncle. You can remove the license comment block at the beginning of the files under application/

**Comment by narfbg** [comment]
b56de6537e9d9a6156dbeaa325f52d3b6e3792a4
