### ISSUE TITLE
Form validation: set_select() re-population with arrays as field names

### ISSUE THREAD

**Issue by bitbucket-import** [bcit-ci/CodeIgniter#35]
I can't get re-population working for my select boxes while using arrays as field names, which I believe is due to a bug. Check the following post for details about what I am trying to do: http://codeigniter.com/forums/viewthread/178442/

The set_value() was buggy as well but recently got fixed: https://bitbucket.org/ellislab/codeigniter-reactor/changeset/19fc3732e593

The current set_select() function checks, when it's an array, if the selected value is in the POST array for the current field name. When you select different options from the select boxes there will be a few different values in the POST array. This will result in select boxes where multiple options will have the 'selected="selected"' added to it. I hope you understand what I mean. 

For example: I have 3 select boxes with example[] as name and 'example-1', 'example-2' and 'example-3' as options. Select 'example-1' for the first, 'example-2' for the second and  'example-3' for the third select box, hit the submit button and make sure the form validation fails. Now set_select() should do the re-population for the 3 example[] select boxes. But all options from all the select boxes will get the 'selected="selected"' added to it :(

**Comment by nandalal** [comment]
I want to display the data in select-drop down not only hard-code value, but also the value from master table what can i do....?? i got a solution from google the code is like this below i mentioned


		<select class="form-control" id="sel2" name="branch">
		<option value="">---Select Choice---</option>
		<?php
		foreach ($branch as $each) {
		?>
		<option value="<?=$each['bid']?>"<?php echo set_select('branch', '$each["branch_name"]'); ?> ><?=$each['branch_name']?></option>
		<?php
		}
		?>
		</select>


But after that i submit the form but this drop-down value is missing please help
