### ISSUE TITLE
Compatibility between 2.2 and 3.0

### ISSUE THREAD

**Issue by XMadMax** [bcit-ci/CodeIgniter#3500]
Helo,

I am usssing a project with 3.0 dev branch, also I had 2.2 with HMVC.
Now, I can use both frameworks without any difference.

Changes needed:

1) Router.php, function _set_default_controller, reverting code to CI 2.2 (due to be ussing HMVC, the  "if ( ! file_exists(APPPATH" ... line breaks compatibility with HMVC.

2) config/mimes.... change return array ...... per  $mimes = array ..... return $mimes

3) Add new features to config.php, and change Session from library to driver. in autoload.php

Othe changes has been made to HMVC, but no to the CI core.
Nothing else needed, hope this helps to be compatible with previous versions.

**Comment by narfbg** [comment]
This is not a place to post random advice - please don't do that. We only accept bug reports here.
