### ISSUE TITLE
Unreachable pages in documentation

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#3505]
There are no navigation links to these pages:

https://github.com/bcit-ci/CodeIgniter/blob/develop/user_guide_src/source/general/requirements.rst

https://github.com/bcit-ci/CodeIgniter/blob/develop/user_guide_src/source/changelog.rst

License Agreement

https://github.com/bcit-ci/CodeIgniter/blob/develop/user_guide_src/source/general/credits.rst

The pages were under the section "Basic Info" within CI2.x documentation.

Forum thread: http://forum.codeigniter.com/thread-869-post-4114.html

**Comment by narfbg** [comment]
There are links to these pages at the top of the index page, they are not unreachable.

**Comment by ivantcholakov** [comment]
Yes, I saw them.
