### ISSUE TITLE
3.0 Release Candidate extra files?

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/CodeIgniter#3513]
Should the 3.0RC include the tests folder and the phpdoc.dist.cml file?
These feel out of place.

**Comment by narfbg** [comment]
tests - unsure; I think user-space testing was possible with it, but it would be quite ugly. Will probably remove it in final.

phpdoc - no, I've missed that one

**Comment by ksbipin** [comment]
Waiting for the final version to be released..!

**Comment by jim-parry** [comment]
Let's remove the tests from the "release build".
