### ISSUE TITLE
When you do a search in the CI3 user manual the python doc gen still reflects some python

### ISSUE THREAD

**Issue by dmyers2004** [bcit-ci/CodeIgniter#3515]
That should probably say PHP not Python

Searched for "cookie"

Search Results

Search finished, found 10 page(s) matching the search query.

CI_Input.cookie (Python method, in Input Class)
Cookie Helper
Input Class
CI_Input.set_cookie (Python method, in Input Class)
delete_cookie (Python function, in Cookie Helper)
get_cookie (Python function, in Cookie Helper)

**Comment by narfbg** [comment]
I'm aware of this.
