### ISSUE TITLE
[Proposal] Extending the Form Validation

### ISSUE THREAD

**Issue by foxlance** [bcit-ci/CodeIgniter#3520]
I extended the validation class to support more functionality such as date validity, in and not in, etc. 

Would you look at 

https://github.com/foxlance/CodeIgniter/compare/bcit-ci:develop...develop 

and see if its worth creating a pull request?

Thanks!

**Comment by narfbg** [comment]
At first glance - 'in' might be useful.

The rest can either be done though already existing rules or are prone to bugs and reports about them will surely follow.

I will have to ask you to go straight with a pull request in the future though. If you've already commited code in a fork, it's probably easier to submit it as a PR than to write a description about it in an issue.
