### ISSUE TITLE
if cange '$config['language']', display error using form-validation/pagination of library

### ISSUE THREAD

**Issue by rdlabo** [bcit-ci/CodeIgniter#3522]
1. change application/config/config.php
$config['language']	= 'japanese';

2.use form-validation/pagination of library

3.display error
Unable to load the requested language file: language/japanese/form_validation_lang.php
Unable to load the requested language file: language/japanese/pagination_lang.php

now, if other language i use, can't use form-validation/pagination of library.

**Comment by narfbg** [comment]
Sorry, I don't understand what you're saying here ...

Did you mean that you have the translation files under *application/language/japanese/* and CI can't load them or are you complaining that we don't have Japanese translations? Or is it something else?

**Comment by dontforget** [comment]
@rdlabo you should copy language files from /system/language/english/ to application/language/japanese/

@narfbg I think if there is no form_validation_lang.php inside japanese (or any other language) the default one (from system folder) should be used. It's just my idea.

**Comment by jim-parry** [comment]
@dontforget @rdlabo  https://github.com/bcit-ci/codeigniter3-translations provides a translation of the language folder for Japanese. Its "japanese" folder would get copied to application/language.

@dontforget  Your other suggestion might be worthy. This could be done by having something like $this->load($value, 'english', $return,TRUE,''); as the first executable line inside the load method.

@narfbg Does this make sense?

**Comment by narfbg** [comment]
It has been suggested before and it doesn't make any sense to me - it's a no-brainer to add the necessary lang files during the development process. I don't see a reason why defaulting to another language is appropriate.

**Comment by jim-parry** [comment]
This doesn't make much more sense now than it did when raise. It sounds more like a support issue than a bug!
