### ISSUE TITLE
Code Ignitor Layout Issue

### ISSUE THREAD

**Issue by liangzhengai** [bcit-ci/CodeIgniter#3523]
Your CodeIgniter is great PHP framework which reduces the development cycle, and provide loose coupling, has a good modularity.
Either it is easy to learn and use.
But I found a problem in page layout.
CodeIgniter has only sequential merging of views and has not layout templating so it needs more time to complete page view than Zend and others.
I wish CodeIgniter has a layout function like Apache Tiles so developers can concentrate the view which every function generates except whole layout.

Of course, high skill developers can customize the hooks to do those but I want CodeIgniter has a completed layout function.

I like CodeIgniter very much.
Thank you.

**Comment by jim-parry** [comment]
This is by design.
Your "issue" is a discussion topic for the forum, and not a bug to be repoted here.
