### ISSUE TITLE
Session database driver issue

### ISSUE THREAD

**Issue by cristiangile** [bcit-ci/CodeIgniter#3529]
Hi,

the line 86 of the Session_database_driver.php file 

https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Session/drivers/Session_database_driver.php#L86

seems to create strange session behaviour. I get errors like the following in my apps and I can't store or get session information:

Fatal error: Call to a member function where() on a non-object in /var/www/ci/system/libraries/Session/drivers/Session_database_driver.php on line 225

Fatal error: Call to a member function query() on a non-object in /var/www/ci/system/libraries/Session/drivers/Session_database_driver.php on line 363

If I remove the reference and chage the line to:

$this->_db = $CI->db;

everything works fine.

Thanks
Cristian

**Comment by narfbg** [comment]
What PHP version are you on?

**Comment by cristiangile** [comment]
5.5.9

**Comment by narfbg** [comment]
And you're not getting *any other* error messages?

**Comment by cristiangile** [comment]
Only these error messages. No error in the log files.

**Comment by narfbg** [comment]
Huh ... what happens if you do this instead?

    $this->_db = '';
    $this->_db =& $CI->db;

**Comment by cristiangile** [comment]
Error is still there.

**Comment by narfbg** [comment]
Well, that's officially the most bizzare bug I've ever seen ... thanks for reporting it.

**Comment by cristiangile** [comment]
Thanks to you.

**Comment by vlakoff** [comment]
I could not reproduce it, @cristiangile have you tweaked anything concerning database, sessions?

**Comment by narfbg** [comment]
I don't think anybody would be able to reproduce it, but we're talking about assigning a property by reference to a property of another reference, which in turn is also a reference ... It's not hard to imagine a rare PHP bug in that case.

**Comment by kakysha** [comment]
@narfbg is it your assumptions or you've digged some other proofs for this? It is not so unusual to assign references to references, I suppose.

**Comment by narfbg** [comment]
Does it matter? We still have a reference and even if we didn't, it would still work flawlessly.

**Comment by vlakoff** [comment]
My guess, cristiangile is overwriting `$superobject->db` somewhere in its code, and it was affecting `$this->_db` too, because of the reference.

**Comment by cristiangile** [comment]
I will check it again later.
