### ISSUE TITLE
select join and in join has subquery select with condition where in codeigniter.

### ISSUE THREAD

**Issue by thearyoun** [bcit-ci/CodeIgniter#3534]
Example I have query in sql like:

SELECT SUM(CASE tblPaymentType.StatSale
        WHEN 1 THEN tblSalePaymentType.Amount
        ELSE 0
    END) AS TotalSaleAmount,
    `tblSalePaymentType`.`DateStamp`,
    `AbbreviationShop` AS Shop,
    `QtyTotal`,
    `Traffic`,
    `RRPSale`,
FROM tblSalePaymentType
JOIN
    `tblShopLocation` ON `tblSalePaymentType`.`ShopLocationID` = `tblShopLocation`.`ShopLocationID`
 LEFT JOIN
    (SELECT 
        SUM(sd.Qty) AS QtyTotal, s.DateStamp, SUM(sd.RRP) AS RRPSale,s.ShopLocationID
    FROM
        tblSaleDetail sd
    JOIN tblSale s ON s.SaleID = sd.SaleID
        AND s.ShopLocationID = sd.ShopLocationID
    WHERE
        s.Printed != 0 AND sd.Enable = 1
      --  and s.ShopLocationID=4
    GROUP BY s.DateStamp) AS tblSaleandSaleDetail ON `tblSaleandSaleDetail`.`DateStamp` = `tblSalePaymentType`.`DateStamp`
        LEFT JOIN
    (SELECT 
        tf.DateStamp, SUM(tfd.Qty) AS Traffic
    FROM
        tblDailyTrafficDetail tfd
    JOIN tblDailyTraffic tf ON tf.DailyTrafficID = tfd.DailyTrafficID
    GROUP BY tf.DateStamp) AS tblTraffic ON `tblTraffic`.`DateStamp` = `tblSalePaymentType`.`DateStamp`
WHERE
    `tblSalePaymentType`.`ShopLocationID` = '4'
       AND `tblSalePaymentType`.`CountryID` = '7'
GROUP BY `tblSalePaymentType`.`DateStamp`

So, how can I convert this code to PHP Framework Codeigniter.

**Comment by jim-parry** [comment]
Raise this issue on our forum, please.
Github is for bugs, not support.
