### ISSUE TITLE
routing

### ISSUE THREAD

**Issue by Azakur4** [bcit-ci/CodeIgniter#3535]
In CI 3.0 seens like routing a controller inside a folder doesn't work.

**Comment by narfbg** [comment]
It "seens"? Please post on the forums and open an issue here after you've *verified* that it is a bug.

**Comment by Azakur4** [comment]
actually i don't know if u remove this functionality and i read the doc of route and doesn't talk about this is cuz that i wrote that here cuz in code igniter 2 this work normally

**Comment by Azakur4** [comment]
im trying to figure out what happen in code igniter 3 and seems like the default controller doesn't support a route: directory/controller/method

if i create another router this is working

**Comment by narfbg** [comment]
Read through issue #2849 and in the future please use the search box first.

Also, please don't double post on the forums and here (I told you to post on the forums, but after that I saw you've already done that). Post here *only* after you've verified that something is a bug. We do not provide general support here, nor is it the place to figure something out. We'd like to keep it clean.

**Comment by Azakur4** [comment]
Ok sorry for that i try to search about that here but only found one in closed issues.

Well thanks.

**Comment by narfbg** [comment]
Just because something is in closed issues, that doesn't mean it's not relevant.

**Comment by Azakur4** [comment]
no one say that sorry for my english man take it easy.
