### ISSUE TITLE
3.0 RC Image Manipulation Class bug - Watermark text not showing when no shadow is set

### ISSUE THREAD

**Issue by omma2289** [bcit-ci/CodeIgniter#3536]
I encountered a bug while developing my application under the release candidate for CI 3.0. The watermark function in the image manipulation class fails to add the text set with `wm_text` when no `wm_shadow_color` option is set.

After inspecting the class source, I found that the code that outputs the text is inside a condition `if ($this->wm_use_drop_shadow)` which means that if no shadow is set, the text won't be added to the image.

**Comment by MrGate** [comment]
Could you pastebin the code and ill take a look and see what i can do!

**Comment by MrGate** [comment]
omma2289 i think i fixed the library so you can do watermark without shadow, im just waiting on someone to review it and accept the pull request!

**Comment by omma2289** [comment]
@MrGate Thanks for looking into this. I think I found a cleaner solution though, instead of adding an `else` statement I put together all the shadow related code inside the condition, let's just see what the dev team has to say about this.
