### ISSUE TITLE
https://github.com/bcit-ci/CodeIgniter/wiki/Smarty-plugin---URL-Helper

### ISSUE THREAD

**Issue by vanchuong201** [bcit-ci/CodeIgniter#3537]
I copy file to third_party/Smarty/plugin
but it do not working !
You can help. email: vanchuong201@gmail.com
thanks a lot

**Comment by avenirer** [comment]
forum...

**Comment by jim-parry** [comment]
This is a support issue and not a CodeIgniter bug ... raise it on our forum, not here.

**Comment by vanchuong201** [comment]
sorry, i'm a newbie. forum ?, where is it ?

**Comment by Razican** [comment]
codeigniter.com

**Comment by jim-parry** [comment]
forum.codeigniter.com :)

**Comment by vanchuong201** [comment]
My english is very bad, I hope I will solve your problems, but i don't where to start. 
So,Tks everybody
