### ISSUE TITLE
Validate GET values

### ISSUE THREAD

**Issue by maxime1992** [bcit-ci/CodeIgniter#3541]
Before the 3.0 version, i used to do the following when i wanted to form_validate GET values :
```
public function foo($my_value) {
   $_POST['my_value'] = $my_value; 
   $this->form_validation->set_rules('my_value', 'My value', 'whatever...');
   if ($this->form_validation->run()) {
      // do whatever ...
   }
}
```

Here's the deal : 
I noticed that CI 3.0 is now checking if the input method is a POST. So i have to delete it in system ... And i really don't like to modify anything in it !

Don't you think it would be better to delete in system/librairies/Form_validation.php that part (??) : 
```
// No reason to set rules if we have no POST data
// or a validation array has not been specified
if ($this->CI->input->method() !== 'post' && empty($this->validation_data))
{
	return $this;
}
```

Cheers and thanks to CI team for the amazing work !

**Comment by narfbg** [comment]
No, the form validation library was meant to work with POST request forms and this change is a bug fix.

If you want to validate GET data, do this:

    $this->form_validation->set_data($_GET);
