### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by levipadre** [bcit-ci/CodeIgniter#3543]
Hi,

How can I set up the default language with this structure?
I have two predefined language:
domainname.com/en/pagename
domainname.com/de/pagename

Both are working perfectly, but when I type domainname.com/pagename , the page is jumping to the main page (domainname.com).

I want make the english default, but without any redirection. So when I type domainname.com/pagename, that should be the english version as well (domainname.com/en/pagename).

Does anybody know how can I do?

Thanks,
L

**Comment by narfbg** [comment]
Please post such questions on the [forums](http://forum.codeigniter.com/). Here we only accept bug reports.
