### ISSUE TITLE
_remap() is Not Work

### ISSUE THREAD

**Issue by yllumi** [bcit-ci/CodeIgniter#3544]
I upgraded my application from 2.2.0 to 3.0rc. I set in config/routes.php

```
$route["default_controller"]	= "Cms";
$route["404_override"] 		= "Cms";
```

to remap all first segment to check if it is a page or not, using _remap() function in CMS controller. But it seems _remap() is not being called. I also check that with simple echo inside _remap() and it was not shown. 

Is that a bug?

**Comment by narfbg** [comment]
Can you be more specific? Under what conditions does that happen?

**Comment by yllumi** [comment]
By default first URI segment is reserved for controller name. But in this case I want to remap the first segment as the page slug for my CMS (or in other case like that). That can be done by set the $route["404_override"] with controller name that containing _remap(). That is work in v2.x. But in v3 the _remap() is not being called. It is just called when we call the controller the basic way..

**Comment by narfbg** [comment]
... so you want to call `_remap()` in case of a 404 error? Why?

**Comment by yllumi** [comment]
Ah I see. In my previous code which is using v2.2, I use _remap() to check if the first segment is a page or post slug from database. If it is not found in database then I call show_404(). But after I try again, I can do that without _remap(). It can be done by using just index() function.

**Comment by narfbg** [comment]
Yep ... that's how 404_override works.
