### ISSUE TITLE
File Driver Session Library: rewind() expects parameter 1 to be resource 

### ISSUE THREAD

**Issue by adrianorsouza** [bcit-ci/CodeIgniter#3545]
When using File Driver Session I get the following error if I setup the `/path/application/sessions` as said in [Session Library Docs](http://www.codeigniter.com/userguide3/libraries/sessions.html#files-driver).

```
Severity: Warning --> rewind() expects parameter 1 to be resource, boolean given /var/www/domain.com/system/libraries/Session/drivers/Session_files_driver.php 182
Severity: Warning --> filesize(): stat failed for /var/www/domain.com/application/sessions/ci_session46fd5efca47570eb3aff783881d3f1a27c42d983 /var/www/domain.com/system/libraries/Session/drivers/Session_files_driver.php 186
Severity: Warning --> fopen(/var/www/domain.com/application/sessions/ci_session3fc5c0400677300708efb7dfb8805ab28dec2e11): failed to open stream: Permission denied /var/www/domain.com/system/libraries/Session/drivers/Session_files_driver.php 150
Session: File '/var/www/domain.com/application/sessions/ci_session3fc5c0400677300708efb7dfb8805ab28dec2e11' doesn't exist and cannot be created.
```

I'm running PHP 5.5.9 on Ubuntu 14.04 with a fresh CI3.0RC

The way to fix is:

```bash
chmod 0700 /<path to your application directory>/sessions/
``` 
then Session File Driver works.

**Comment by narfbg** [comment]
Are you posting a bug report or a "how to fix this"  thread? File permissions are explained in the manual.

**Comment by adrianorsouza** [comment]
I mean bug report, but also I mention a workaround that works for me.

**Comment by narfbg** [comment]
How is it a bug report if the "work-around" is a *requirement* that is explained in the documentation (on the very link you posted)?

**Comment by adrianorsouza** [comment]
I think the docs should say you can achieve this permissions using `0700` instead of `0600` if it's not a bug on how Session Driver handle sessions files.

**Comment by narfbg** [comment]
So you're saying that it works with 0700 but not 0600?

**Comment by adrianorsouza** [comment]
@narfbg exactly 0700 works fine, 0600 throws that error I mentioned earlier.

**Comment by narfbg** [comment]
OK, sorry then - my bad.

**Comment by adrianorsouza** [comment]
No worries, Thanks.

**Comment by george-dragnea** [comment]
The sessions folder have 0700, but I still get those errors.
What could be the problem ?

**Comment by adrianorsouza** [comment]
@george-dragnea check if your web user have the correct permission to write to that folder.
