### ISSUE TITLE
Modules :: run(module/class/method) not working

### ISSUE THREAD

**Issue by bthulung** [bcit-ci/CodeIgniter#3546]
i have module class Job extends MY_Controller {} and i have method jobcategory {} i run module like this echo Modules::run('job/job/jobcategory '); but when i load job/jobcategory on url it works, again when i load job/shoe(categoryname) it give following error

A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: controllers/job.php

Line Number: 132

so kindly anyone let me know what the problem is

**Comment by narfbg** [comment]
CI doesn't have module classes.

And this is for the forums anyway, we only accept bug reports here.
