### ISSUE TITLE
ini_set(): Use of iconv.internal_encoding is deprecated

### ISSUE THREAD

**Issue by ozziest** [bcit-ci/CodeIgniter#3549]
system/core/CodeIgniter.php [LINE: 266] 
ini_set(): Use of iconv.internal_encoding is deprecated.

[http://php.net/manual/en/iconv.configuration.php](http://php.net/manual/en/iconv.configuration.php)

It's about 3.1 RC

**Comment by narfbg** [comment]
Lines 264,265:

                // iconv.internal_encoding is deprecated starting with PHP 5.6
                // and it's usage triggers E_DEPRECATED messages.

**Comment by dknell** [comment]
@narfbg In PHP 7, I think this might be a bigger deal. I was getting a 500 Internal Server Error in our app with no other message or errors in the log and I tracked it back to this. When I commented out `@ini_set('iconv.internal_encoding', $charset);`, I get a 200 response and everything loads fine. If I remove the silencer (`ini_set('iconv.internal_encoding', $charset);`), I get this:
```
A PHP Error was encountered
Severity: 8192
Message: ini_set(): Use of iconv.internal_encoding is deprecated
Filename: core/CodeIgniter.php
Line Number: 269
```
We're running the latest PHP7 (7.0.15) in Ubuntu 16.04. By default iconv is enabled and if I disable it then other things start breaking, like composer.

According to the [iconv configuration page](http://php.net/manual/en/iconv.configuration.php), the recommended way to set the charset (as of PHP 5.6 or higher) is `ini_set('default_charset', 'UTF-8')`, which is already done [here](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/CodeIgniter.php#L194).

What do you think about doing something like this:
```
	// There's an ICONV_IMPL constant, but the PHP manual says that using
	// iconv's predefined constants is "strongly discouraged".
	if (extension_loaded('iconv'))
	{
		define('ICONV_ENABLED', TRUE);
		// iconv.internal_encoding is deprecated starting with PHP 5.6
		// and it's usage triggers E_DEPRECATED messages.
                if (! is_php('5.6')) {
    		    @ini_set('iconv.internal_encoding', $charset);
                }
	}
	else
	{
		define('ICONV_ENABLED', FALSE);
	}
```
I'd be happy to submit a PR if you think this is OK.

**Comment by narfbg** [comment]
@dknell That makes no sense ... An E_DEPRECATED error is *only* a message telling you that something's deprecated and has no side effects. If something works, but shows an E_DEPRECATED message, there's no reason why it wouldn't work when the message is silenced.

But the bigger problem is that `iconv.internal_encoding`, even though deprecated, *still* has a higher precedence than `default_charset`. If your php.ini sets `iconv.internal_encoding`, it doesn't matter what else we do unless we override it.

**Comment by dknell** [comment]
I looked at the `_error_handler ` function and I see what you mean about how the E_DEPRECATED messages should not send a 500 status to the client. After investigating further, I found that we have a `_error_handler` override that was simply sending 500 to the client. After removing that, CI acted exactly as you described. 

Thanks for your reply and for helping me track down the root cause!
