### ISSUE TITLE
Can't combine query string with URI string ($_GET not work)

### ISSUE THREAD

**Issue by yllumi** [bcit-ci/CodeIgniter#3554]
My previous application use $_GET in many feature, but the link detected as it has disallowed characters. My example link like this:

`http://localhost/myapp/panel/pages/edit?page=lipsum/subpage`

and it shows error "The URI you submitted has disallowed characters."

**Comment by jim-parry** [comment]
This is a support issue, not a bug. It should be raised on the forum, not here.

See http://www.codeigniter.com/userguide3/general/urls.html#enabling-query-strings
You might be able to use http://www.codeigniter.com/userguide3/libraries/uri.html#CI_URI::uri_string
Or you might have to use the appropriate PHP superglobal.

Your previous usage may have worked, but it is not supported.

Your specific error message comes from http://www.codeigniter.com/userguide3/libraries/security.html?highlight=disallowed
You could have searched the user guide too :-/

**Comment by yllumi** [comment]
So then in v3 we cannot use query string and uri string together anymore?

**Comment by jim-parry** [comment]
You might be able to, but you will need to deal with the security, perhaps turning it off. Ask on the forum for suggestions - I could be misinterpreting things :-/

**Comment by narfbg** [comment]
> So then in v3 we cannot use query string and uri string together anymore?

The valid characters are configurable.
