### ISSUE TITLE
dead parameter in form_upload

### ISSUE THREAD

**Issue by gadelat** [bcit-ci/CodeIgniter#3558]
There is parameter $value in form_upload which is not used and does not make sense for file input tag. This parameter should be removed. Hovewer, this may cause breakage in user applications, so I think this should be changed in 3.1

**Comment by narfbg** [comment]
Agreed, it's a stalemate right now.

**Comment by narfbg** [comment]
There's nothing that can be done about this without breaking BC and that shouldn't happen in minor versions such as 3.1, so it stays as is.

**Comment by narfbg** [comment]
On another note however, SemVer won't be benefitial as we move forward to CI4 ... it's going to be a rewrite anyway, so holding deprecated functionalities and such until then is pointless.
