### ISSUE TITLE
index.php rewrite not working on user directory

### ISSUE THREAD

**Issue by carloscarcamo** [bcit-ci/CodeIgniter#3569]
Hello all, I have a [little problem](http://stackoverflow.com/questions/28258126/codeigniter-htaccess-index-php-rewrite-not-working-on-user-directory) with .htaccess in codeigniter 2.x.
 I have a .htaccess for rewrite the index.php it works great if I put my projects on /var/www or if I make a virtual host for it.

But I want to use my user directory such as http://localhost/~userdir/myproject. If I use my user directory when I'm trying to do request to a controller like: http://localhost/~userdir/myproject/signup I get this error:

    Not Found

    The requested URL /index.php was not found on this server.

This is my current configuration:

* htaccess
```apache
RewriteEngine on
RewriteCond $1 !^(index\.php|(.*)\.swf|forums|images|css|downloads|jquery|js|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php?/$1 [L,QSA]
```

* application/config/config.php
```php
$config['base_url'] = '';
$config['index_page'] = '';
$config['uri_protocol'] = 'AUTO';
$config['encryption_key'] = 'myencryption_key';
//all remaining is the default config
```
This config works great on http://localhost/ and also on production enviroments with a domain like http://example.com/ but not on my user directory http://localhost/~userdir/project/

 Any thoughts? Thanks in advance.

**Comment by jim-parry** [comment]
This is a support issue, not a bug. It should be raised on forum.codeigniter.com

**Comment by carloscarcamo** [comment]
Ooh sorry and thanks, I will post this on forum :)
