### ISSUE TITLE
Corruption of cookies/premature destruction of sessions by XSS filter malfunction

### ISSUE THREAD

**Issue by doogie99** [bcit-ci/CodeIgniter#3570]
I've been chasing this one for a while.

Our users were occasionally experiencing being kicked out of the web app I've created for them. 

I traced this to cookie corruption which led to a HMAC mismatch error which caused the destruction of the session.

The cookie corruption is actually being caused by sanitize_globals in this part:

		// Clean $_COOKIE Data
		if (is_array($_COOKIE) AND count($_COOKIE) > 0)
		{
			// Also get rid of specially treated cookies that might be set by a server
			// or silly application, that are of no use to a CI application anyway
			// but that when present will trip our 'Disallowed Key Characters' alarm
			// http://www.ietf.org/rfc/rfc2109.txt
			// note that the key names below are single quoted strings, and are not PHP variables
			unset($_COOKIE['$Version']);
			unset($_COOKIE['$Path']);
			unset($_COOKIE['$Domain']);

			foreach ($_COOKIE as $key => $val)
			{
				$cleanKey = $this->_clean_input_keys($key);
				log_message('info', '$_COOKIE before cleaning. Key = ' . $cleanKey . ' Value = ' . $_COOKIE[$cleanKey]);
				$_COOKIE[$cleanKey] = $this->_clean_input_data($val);
				log_message('info', '$_COOKIE after cleaning. Key = ' . $cleanKey . ' Value = ' . $_COOKIE[$cleanKey]);
			}
		}

the "cleaning" part that actually corrupts the cookie is in Security.php in remove_evil_attributes and more specifically here:

		// All javascript event handlers (e.g. onload, onclick, onmouseover), style, and xmlns
		$evil_attributes = array('on\w*', 'style', 'xmlns', 'formaction');

			// find occurrences of illegal attribute strings without quotes
			preg_match_all('/('.implode('|', $evil_attributes).')\s*=\s*([^\s>]*)/is', $str, $matches, PREG_SET_ORDER);

			foreach ($matches as $attr)
			{
				$attribs[] = preg_quote($attr[0], '/');
			}

			// replace illegal attribute strings that are inside an html tag
			if (count($attribs) > 0)
			{
-------->				$str = preg_replace('/(<?)(\/?[^><]+?)([^A-Za-z<>\-])(.*?)('.implode('|', $attribs).')(.*?)([\s><]?)([><]*)/i', '$1$2 $4$6$7$8', $str, -1, $count);
			}

The problem occurs for me when an encrypted cookie contains "on" somewhere in it.

Here is a cookie that fails:

+35Fh9PDDPCGB04jkDSSToycLbknM1odORXLJhsd7tDImYAxnPw+NxlqfXWFbt3TQULpOTiC74k4+NkLIGWtnIDzTq1ueKtGvE913xEqTU0m6PRWyW+lgqqa+HrfhTtNeLb0uckqEu7d7gVRzWSer4ZV3wFw02AcDIeni7DW7VFGDfgOqjCldTsYKKkuFWwojDD5q+yv7IHIvYyGr9LUj1jgFPCz/T0V6LjCLkciLOvtXOS1xlc8JV1ya0sJmhtJwMwNATvUNrHpIyEczOTOJRLhiKNvHGVy9fjr8+9GRx6csu7CAqz6lzuJDehl3Evx6nD6KytE8mK2JRESN+k5V9fiz+1X61rvH2G4kb0LzzecAJmZ2rrJMVWwNZfvu4RawVFEVYKSRNon0wPe3EXpeIgNfKU9v4RmtKGntRr396Q=b943770faa5d84c664eaa24a1ae456425d4651ea

After passing through the previous piece of code this gets altered to:

+ 5Fh9PDDPCGB04jkDSSToycLbknM1odORXLJhsd7tDImYAxnPw+NxlqfXWFbt3TQULpOTiC74k4+NkLIGWtnIDzTq1ueKtGvE913xEqTU0m6PRWyW+lgqqa+HrfhTtNeLb0uckqEu7d7gVRzWSer4ZV3wFw02AcDIeni7DW7VFGDfgOqjCldTsYKKkuFWwojDD5q+yv7IHIvYyGr9LUj1jgFPCz/T0V6LjCLkciLOvtXOS1xlc8JV1ya0sJmhtJwMwNATvUNrHpIyEczOTOJRLhiKNvHGVy9fjr8+9GRx6csu7CAqz6lzuJDehl3Evx6nD6KytE8mK2JRESN+k5V9fiz+1X61rvH2G4kb0LzzecAJmZ2rrJMVWwNZfvu4RawVFEVYKSRN

totally hacking off the HMAC and some other data and altering the first part of the string. When sess_read goes to work with the altered cookie it fails and kills the session, kicking the user out to the login screen.

I'm not sure what a good permanent fix is to this issue so I'll leave it to you Codeigniter experts.

**Comment by rfulcher** [comment]
doogie99,

I have had some issues with that but it has been very sparatic and I was not able to reproduce it to troubleshoot.  Basically our users would get totally kicked out like they were never logged in.  Is that what was happening to your user?  Usually this would be on a form submissions for us.

Thanks

**Comment by doogie99** [comment]
rfulcher,

Yep. Very similar. Very sporadic because it is caused by "on" followed by a word character (regexlib.com/CheatSheet.aspx) showing up in the encrypted cookie used for session tracking. The fairly simple match term is not so uncommon when you get an encrypted cookie + HMAC that can be upwards of 400 chars. Although I haven't explored the likelihood (I'm not a stats major) I'm sure there are likely other false matches that could occur resulting in cookie corruption. A possible solution for the code igniter library is to perhaps check the session tracking cookie for validity first before cleaning it. If the HMAC is invalid or the encrypted portion doesn't decrypt then do the cleaning(?). Experts?

**Comment by rfulcher** [comment]
Thanks for the information, very nice find...

On Thu, Feb 5, 2015 at 2:23 PM, doogie99 <notifications@github.com> wrote:

> rfulcher,
>
> Yep. Very similar. Very sporadic because it is caused by "on" followed by
> a word character (regexlib.com/CheatSheet.aspx) showing up in the
> encrypted cookie used for session tracking. The fairly simple match term is
> not so uncommon when you get an encrypted cookie + HMAC that can be upwards
> of 400 chars. Although I haven't explored the likelihood (I'm not a stats
> major) I'm sure there are likely other false matches that could occur
> resulting in cookie corruption. A possible solution for the code igniter
> library is to perhaps check the session tracking cookie for validity first
> before cleaning it. If the HMAC is invalid or the encrypted portion doesn't
> decrypt then do the cleaning(?). Experts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcit-ci/CodeIgniter/issues/3570#issuecomment-73108930>
> .
>



-- 
Robert Fulcher
iWAT LLC
Phone: 717-884-9281
Cell: 717-658-5100
rob@iwatllc.com
www.iwatllc.com

___/Confidentiality Notice\_____________________________
This email message, including any attachments, is for the sole use of
intended recipient(s) and may contain confidential and privileged
information. Any unauthorized review, use, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply email and destroy all copies of the original message.

**Comment by narfbg** [comment]
This is already fixed in the 2.2.1 release - encrypted session cookies are explicitly excluded from that procedure and they don't go through `_clean_input_data()`. Just update to the latest CI version.

**Comment by rfulcher** [comment]
Thanks narfbg..Awesome..did not know that.

**Comment by doogie99** [comment]
narfbg,

Thanks - I cloned your repo and checked the develop branch before I posted. I guess I didn't look closely enough or in the right place; I thought the problem was still there.

**Comment by narfbg** [comment]
The develop branch is the soon to come 3.0 release ... of course, it also doesn't have that issue, but it's completely different. I'd encourage you to upgrade straight to 3.0 (rc2 is available in the downloads section), but you should know that it's not 2.2.1.

Please post on the [forums](http://forum.codeigniter.com/) if you have any more questions as we only deal with bug reports here.
