### ISSUE TITLE
CI 2.2.1 mysqli_real_escape_string fails

### ISSUE THREAD

**Issue by zknightfsw** [bcit-ci/CodeIgniter#3571]
In the new CI 2.2.1, it uses  mysqli_real_escape_string($this->conn_id,$str) on line 316 of the mysqli_driver.php. Well if you have "autoinit" set to false, that makes all our SQL crash and burn if you haven't connected yet.

I had to add
```
if($this->autoinit == false) {
			$this->initialize();
		}
```
before line 316 in the function and that fixes the issue.

If I don't do that, I get a nice big fat error for the first query connecting to the DB,
```
Message: mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given

Filename: mysqli/mysqli_driver.php
```

**Comment by narfbg** [comment]
There's nothing unusual about this.
