### ISSUE TITLE
Follow up on PR #3562

### ISSUE THREAD

**Issue by aanbar** [bcit-ci/CodeIgniter#3578]
I think the default behavior should be un-escaped html & those who are not using the form_helper to generate their forms should be sending the third argument not the other way around.

This would guarantee seamless upgrade (not having to edit all views to include the FALSE in each set_value call)

**Comment by avenirer** [comment]
Is safer to have it escaped by default.

**Comment by narfbg** [comment]
... and it would be a BC break to change it.

**Comment by aanbar** [comment]
It's not made to make things safer, it's just there so having HTML in a form field won't break the field itself.

As for the BC break, the default behaviour in the previous version didn't generate a double escaped fields when using form_helper functions along side set_value.

**Comment by narfbg** [comment]
It's made to work with raw HTML and you don't excuse a BC break with another BC break. There's no point in arguing ... we're in RC stage - any new feature or change in behavior must be completely optional.

**Comment by aanbar** [comment]
Last comment for me on this (I don't want to push it)

Can we default it to NULL & have a global flag somewhere like in config.php to set the default behaviour of this.

So a simple change in config changes the default for this.

**Comment by narfbg** [comment]
A config setting for a single form helper function ... no.

**Comment by tareq-halaby** [comment]
Hello @narfbg, 

this should be as @aanbar said, you're forcing us to modify a huge number of files on each project we have to upgrade.

Please reconsider your decision

**Comment by narfbg** [comment]
As I said - it's supposed to be used with raw HTML and that's what the examples in the manual display. You're only forced to modify code because you've not used as described in the documentation in the first place.
