### ISSUE TITLE
user guide link application/views/welcome_message.php has to be edited to user_guide_src

### ISSUE THREAD

**Issue by fandressouza** [bcit-ci/CodeIgniter#3581]
the current link doesn't work

**Comment by narfbg** [comment]
I'm sorry, what link?

**Comment by fandressouza** [comment]
it's not a big deal but in application=>views => welcome_message.php there is just one link that should direct to the user guide page but it's broken, in order for it to work we have to point it to user_guide_src, as I said it's not a big deal but it might confuse someone new to the framework like myself.

**Comment by narfbg** [comment]
It's not broken, official releases have a user_guide/ dir, not user_guide_src/.
