### ISSUE TITLE
Unit testing with Codeigniter

### ISSUE THREAD

**Issue by destructivecreator** [bcit-ci/CodeIgniter#3586]
Hi there, few years back I wrote a unit testing extension (lib) that runs as part of the application and provides a web interface for running tests (console also available). If you guys think there is value in this peace of work few free to adopt it and ship it with the framework. I don't have much time to play with CI, thus haven't improved CIUnit recently. Project can be found [here](https://github.com/destructivecreator/ciunit-framework) .

**Comment by taiar** [comment]
It would be better if you post it here: http://forum.codeigniter.com/ :thumbsup:

**Comment by DevotionGeo** [comment]
It would be awesome !

**Comment by danieleteti** [comment]
+1

Even a small integration with phpunit in CLI mode would be OK.

DT
Il 09/mag/2015 05:25 PM, "DevotionGeo" <notifications@github.com> ha
scritto:

**Comment by jtneal** [comment]
I'd love to see unit testing features added to core. Is there any reason something like this hasn't happened yet?

**Comment by kenjis** [comment]
See https://github.com/bcit-ci/CodeIgniter/issues/1315#event-191833370
Unit testing for applications is a Large, New Feature and Fixing Down the Road.
And you can see a issue like this: https://github.com/bcit-ci/CodeIgniter/issues/4189

**Comment by narfbg** [comment]
This isn't realistically going into core. Having a package out there is good enough for me.
