### ISSUE TITLE
Nitrous - Codeigniter with Ion_auth, "No server"

### ISSUE THREAD

**Issue by michaelstokes** [bcit-ci/CodeIgniter#3587]
Hi guys,

would really appreciate your help please.

I'm currently developing a website in php using codeigniter with ion_auth. 

When logging sometimes (not everytime) and when submitting other forms, the website becomes inaccessible and nitrous says that "there is no server running on this port" even though I can still access phpmyadmin still. The website becomes inaccessible for a while and then accessible again eventually only for the same thing to occur again.

I've looked at CSRF etc but I still continue to get the same error.

Thank you :)

Michael

**Comment by narfbg** [comment]
Post this on the [forums](http://forum.codeigniter.com), not here.
