### ISSUE TITLE
every ci_library_paths contains "libraries"?

### ISSUE THREAD

**Issue by minuux** [bcit-ci/CodeIgniter#3591]
application/config/autoload.php

```
$autoload['packages'] = array('E:/Libs/php/');

```
I can't load my libraries

when I see system/core/Loader.php  row:1002
```
$filepath = $path.'libraries/'.$subdir.$class.'.php';

```
so every library_paths add  "libraries"

php search my libraries from

"E:/Libs/php/**libraries**/auth/1.0.0/Auth.php"
"E:\Projects\Php\test\application\libraries/auth/1.0.0/Auth.php"

**Comment by narfbg** [comment]
Yes.
