### ISSUE TITLE
QueryBuilder ->where_in doesn't disable escaping

### ISSUE THREAD

**Issue by aanbar** [bcit-ci/CodeIgniter#3592]
I am unable to disable escaping for ->where_in method in QueryBuilder, I tried sending the third argument as FALSE, and it keeps adding quotes inside the braces.

@narfbg Could you please take a look at this?

**Comment by narfbg** [comment]
It disables escaping of the field name, not its values. Or do I not understand what you mean?

**Comment by aanbar** [comment]
Yes, the value is always escaped, currently I am using ->where("fieldname IN(xxxx)", NULL, FALSE) instead which is working fine.
I am building a Query & saving it to a variable using ->get_compiled_select then passing it to ->where_in

**Comment by narfbg** [comment]
Eh ... all of this work just to shove something into where_in(), you better just run the raw query. :)

As I said, the parameter exists disable field name escaping, not value escaping.

**Comment by aanbar** [comment]
No, That's not the case.
The normal ->where does not behave this way, You can see it has 
```
if ($escape === TRUE)
{
  $v = ' '.$this->escape($v);
}
```

I think the ->where_in should have the same behavior.

**Comment by narfbg** [comment]
The normal `where()` accepts strings and deals with all kinds of conditions.

`where_in()` doesn't - its sole purpose is to process lists of values, and if you pass it a string, it will turn into an array and treat that string as a single value. That's how it is meant to work, how it has always worked and how it is documented.

**Comment by aanbar** [comment]
Turning it into array isn't going to affect how it would work if you sent it a single string as there's an implode after escaping the values, And it will result in a single string being passed after the implode.

As for the documentation part it says "Whether to escape values and identifiers" which means it should be disabling escape for the values too.

This limitation doesn't make sense, I have given a valid use case I guess.

**Comment by narfbg** [comment]
It's not a valid use case, it's a hack ... If you really need to do that, just use `where()`:

    $this->db->where('fieldname', 'IN('.$your_values_string.')', FALSE);

Fixed the docs: c749bfbca99291fe64ca98d45a20d0735cb4e461
