### ISSUE TITLE
set_time_limit

### ISSUE THREAD

**Issue by wirasto** [bcit-ci/CodeIgniter#3602]
Why set_time_limit() no longer in Codeigniter.php?

**Comment by avenirer** [comment]
is that an issue? :))

**Comment by narfbg** [comment]
Because you can put it in yourself if you really need it.

Please don't open such issues here and unless you have a verified bug to report, post all of your questions on the [forums](http://forum.codeigniter.com/).

**Comment by wirasto** [comment]
I just wonder why set_time_limit is not there when function for disable magic_quotes_runtime still there. I think there is a problem.

Sorry for wrong post,,, and bad english :D
