### ISSUE TITLE
Unable to load session library

### ISSUE THREAD

**Issue by arisdario** [bcit-ci/CodeIgniter#3606]
hey, nice to see that codeigniter is alive !, i would like to upgrade only the Session Library, i fallowed closely the instructions for upgrade from 2 to 3, and i have removed first the Session.php from libraries and copied only the Session Library folder to libraries system folder, but on load the library it says: "Unable to load the requested class: session"

**Comment by narfbg** [comment]
You can't do that. It's either full upgrade or no upgrade.

Also, please don't post support requests or questions here - we only accept bug reports on GitHub. Anything else should be posted on the [forums](http://forum.codeigniter.com/).

**Comment by arisdario** [comment]
Dude, since you rewrite the entire code, and changed the mode how we was coding with codeigniter, you invented and change the methods, so, since the Session library from 2.2 is not very good, and in this version was perfectioned i say Ok, lets change the Session, because it is in CANDIDATE RELEASE, not a stable version, why you people just not keep the same structure and keep the same way of coding ? all the time you redirect to o a forum that doesn't exist anymore in google, and it goes to a ridiculous page where say "Codeigniter has a new home" !

**Comment by narfbg** [comment]
If you even clicked on the link, you'd know it's a new forum and it sure as hell exists. I wouldn't send you there if it didn't.
