### ISSUE TITLE
[PDO] Call to a member function quote

### ISSUE THREAD

**Issue by andreas22** [bcit-ci/CodeIgniter#3607]
I tried to use pdo as database driver but I am getting the following fatal error, which means that when that line of code is called the database has not been initialized yet.

Fatal error: Call to a member function quote() on a non-object in  /database/drivers/pdo/pdo_driver.php on line 333

My Code:

in my model constructor, I am loading the corresponding db:

$this->load->database('db_name');

and when the below line is called the  above fatal error is thrown, the below line is in my function called create which is in model

$this->db->set('name', 'value');

FYI, the following error occurs when I use mysqli as dbdriver.

Thanks

**Comment by narfbg** [comment]
So why did you not configure it to autoconnect if that's what you want?

**Comment by andreas22** [comment]
I already tried that as well but the error remains the same.

$autoload['libraries'] = array('database');

**Comment by narfbg** [comment]
That's auto-loading of the database library, not configuring it to auto-connect. Setting 'autoinit' to TRUE in config/database.php does that.

**Comment by andreas22** [comment]
Thank u for the prompt response, is working fine now.

**Comment by narfbg** [comment]
Please use the [forums](http://forum.codeigniter.com/) in the future to ask questions. I wasn't sure if this is a valid bug report at first, which is why I responded instead of just closing it ... we don't provide support here.
