### ISSUE TITLE
default controller with subfolder not working

### ISSUE THREAD

**Issue by riwakawebsitedesigns** [bcit-ci/CodeIgniter#3611]
When I add a subfolder to $route['default_controller'] it does not pick up. I just downloaded a new copy for latest updates.

// Not Work
$route['default_controller'] = 'subfolder/welcome';

// Works
$route['default_controller'] = 'welcome';

Not sure if this is something wrong in codeigniter 2 I could.

**Comment by narfbg** [comment]
#2849 #3535 + surely at least one more duplicate issue of this.

The same was already asked on the forums, where you've already opened tens of threads requesting help with basic issues ... Please at least keep such questions in there and don't open issues on github unless you've already confirmed it to be a bug.

**Comment by narfbg** [comment]
Now I see that you've already [asked the same question on the forums](http://forum.codeigniter.com/thread-1238.html).

So, for the [second time](https://github.com/bcit-ci/CodeIgniter/issues/3043): DO NOT DOUBLE POST!
