### ISSUE TITLE
Email : Random weird chars 

### ISSUE THREAD

**Issue by kevincaradant** [bcit-ci/CodeIgniter#3615]
Hi everybody ,

For two days , i have been working on email and i have always the same bug with random chars appearing in email. Exemple :" $9 , !$"  and many others. I noticed that sometimes the dom was broken. I tried to encode the mail in base 64 , using wordwrap with the separation at 76 chars etc , but nothing worked.

So, i have decided to look at on github some librairies and i suggest to look at this : https://github.com/PHPMailer/PHPMailer . This librairy works well.
I don't know if that would be possible / if you want to use this as default mail librairy in Codeigniter but this would solve many problems with the mail class.

I hope that will be usefull for people and also the next version of CodeIgniter :)

**Comment by narfbg** [comment]
No, we don't replace our libraries with third-party ones. There's nothing stopping you to use it if that's what you wish.
