### ISSUE TITLE
Composer Autoloader

### ISSUE THREAD

**Issue by Lilibuth12** [bcit-ci/CodeIgniter#3622]
Hey,
Regarding the latest release of v3.0 ( rc2 ) I can autoload the composer files from the config fine, however the addition I always add to my config file:

/*
|--------------------------------------------------------------------------
| Autoload Custom Controllers
|--------------------------------------------------------------------------
|
*/
function __autoload($class) {
    if (substr($class,0,3) !== 'CI_') {
        if (file_exists($file = APPPATH . 'core/' . $class . EXT)) {
            include $file;
        }
    }
}

Which I believe is pretty common, seems to be overridden somehow(?) and I cannot access the classes I have in application/core.  I had previously downloaded a dev version of 3.0 and it works completely fine. I have tried looking through the code to pinpoint what is different that may affect it but I cant see anything that would do it.

**Comment by narfbg** [comment]
Post this on the [forums](http://forum.codeigniter.com/), we only accept bug reports here.
