### ISSUE TITLE
Make "mysqli" the default for 2.2, or remove the "@" from mysql_connect

### ISSUE THREAD

**Issue by dzuelke** [bcit-ci/CodeIgniter#3625]
The legacy `mysql` extension has been deprecated since PHP 5.5 and isn't even enabled anymore by default on certain hosting environments (e.g. on Heroku).

As CI's MySQL driver against all common sense uses `@` to suppress errors (without actually handling the potential error cases), it also swallows the "undefined function `mysql_connect`..." fatal error that PHP throws if the extension isn't loaded. The result is a blank error page and absolutely zero output in the PHP error logs, because CI also registered its own error handler that doesn't let messages bubble up to the system error log.

Possible solutions:

- remove the "@"
- change the driver in the default db config to "mysqli"
- check if `mysql_connect` is available before using it
- Call `error_log()` in addition to the internal exception handler thing when a "native" PHP error is encountered.

**Comment by narfbg** [comment]
All of this is already fixed in the develop branch.

**Comment by dzuelke** [comment]
Yeah, I saw, but I figured that 3.0 was going to be backwards incompatible in many areas? And even if it's not, many users won't upgrade for a while because the "3.0" scares them away :(

**Comment by narfbg** [comment]
Any new deployment should happen with 3.0, we've kept BC breaks to a (practical) minimum ... it's nothing to be scared of.
