### ISSUE TITLE
Underscore '_' Character Containing Database Table Field Names And Escaping

### ISSUE THREAD

**Issue by mertdogan** [bcit-ci/CodeIgniter#3635]
$field=$CI->db->escape_like_str('TARIH_TR_GUNLU');

returns 'TARIH!_TR!_GUNLU

Hope you fix this bug?

**Comment by narfbg** [comment]
It's not a bug.

**Comment by mertdogan** [comment]
Why it's not a bug? I want to get field names from jqgrid and before use in sql query i want to escape it. In where clause i want to use it but it generates error message.

May you explain why it's not and what may i do?

**Comment by narfbg** [comment]
The underscore is a wildcard character just like the percent sign, only it matches only a single character. Please ask your other questions on the forum.

**Comment by JrrMaster** [comment]
Yeah, you can't call this a bug but how if I want to produce query like:

select * from foo_tbl where bar_column like '%match%something%'

with query builder: $this->db->like('bar_column', 'match%something', 'both')->get('foo_tbl');
without escaping % with !% ?

**Comment by narfbg** [comment]
Don't use the query builder? You don't *have* to use it if it doesn't help you.

**Comment by narfbg** [comment]
@JrrMaster This may be helful for you: d738b6ba89d7b719114cbfaa5a62964f943ba926

**Comment by mertdogan** [comment]
@JrrMaster dont try to explain your problem; he neler understands. Just solve your problems yourself. I made like this

**Comment by narfbg** [comment]
Oh, the guy who's never wrong again ...
