### ISSUE TITLE
sess_destroy not working in codeigniter

### ISSUE THREAD

**Issue by paraz013** [bcit-ci/CodeIgniter#3641]
function logout()
	{
		$this->session->sess_destroy();
		redirect(base_url().'home');
	}
after Log out after redirecting when i press back button in browser it goes to logged in page only, as session is not destroyed.

Please help.. thank in advance..

**Comment by avenirer** [comment]
How do you call a function from a view? Use forums for help: http://forum.codeigniter.com/

**Comment by jim-parry** [comment]
Ask this question on the forum, as avenirer says. Github is for bugs, not support.

**Comment by vov1** [comment]
I think when you press back button your browser loads page from cache, try to do some action that needs login it will rejected.

**Comment by paraz013** [comment]
in view page:
if($this->session->userdata('user_id')){ ?>
    &lt;a href="<?=base_url()?>index.php/users/logout"&gt;Log out&lt;/a&gt;
        /////////////the body////
<?php } else { ?>
	&lt;a href="<?=base_url()?>index.php/users/login"&gt;Login&lt;/a&gt;
<?php } ?>

**Comment by narfbg** [comment]
Please, use the forums like you were already asked to. We *don't provide support* here.
