### ISSUE TITLE
Can't load config file with same name in Package after add_package_path()

### ISSUE THREAD

**Issue by wai** [bcit-ci/CodeIgniter#3642]
class CI_Config {
function load($file = '', $use_sections = FALSE, $fail_gracefully = FALSE){
$file = ($file === '') ? 'config' : str_replace('.php', '', $file);
...
}
}

For example:
i have a config.php file in - PHP\application\third_party\my_app\config\config.php

So i add this package, and try to load the file
$this->load->add_package_path(APPPATH . 'third_party/my_app');
$this->config->load('config');

But in this case, CI will always return TRUE on line 131 in CI_Config and skip to load package/config
Because, PHP\application\config\config.php is loaded at the beginning.

I don't know this is a bug or not. I fix it by create a function pass the package config path to load the config file.

**Comment by narfbg** [comment]
Already fixed in the develop branch.

**Comment by wai** [comment]
I'm sorry for my unclear report. 
I am testing on CI 3.0rc2, also i looked on develop branch.

My test case
PHP\application\config\config.php
PHP\application\third_party\my_app\config\config.php

When i want to load the config.php in \third_party\my_app\,
in class CI_Config function load
it will try to check the _config_paths
PHP\application\config/config.php
PHP\application\config/development/config.php
but never go to 
PHP\application\third_party\my_app\config\config.php

MY TEST 1 config->load('config')
120 :loaded=>Array ( [0] => PHP\application\config/some_config.php ) 
123 :config paths=>Array ( [0] => PHP\application\ [1] => PHP\application\third_party/my_app/ ) 
125 :start=>PHP\application\
129 :auto gen path=>PHP\application\config/config.php
140 :include =>PHP\application\config/config.php
159 :config merge =>PHP\application\config/config.php
166 :config file loaded =>PHP\application\config/config.php
129 :auto gen path=>PHP\application\config/development/config.php
136 :file not exists (PHP\application\config/development/config.php)
170 :loaded =>PHP\application\
MY TEST 2 config->load('config')
120 :loaded=>Array ( [0] => PHP\application\config/some_config.php [1] => PHP\application\config/config.php ) 
123 :config paths=>Array ( [0] => PHP\application\ [1] => PHP\application\third_party/my_app/ ) 
125 :start=>PHP\application\
129 :auto gen path=>PHP\application\config/config.php
131 :already include=>PHP\application\config/config.php
FINISH

TEST1 show that when we load the main config file, it will not add into CI_Config::is_loaded.
TEST2 show once we use the same name, it will stop end quit the function when the file use a same file name in main folder (\application\config), so i can't load config.php file in \application\third_party\my_app\config

Thanks.

**Comment by narfbg** [comment]
Yea, I thought you were saying that it doesn't check package paths at all ... sorry about that. See the referenced commit.
