### ISSUE TITLE
Could not find the language line using "unit_test"

### ISSUE THREAD

**Issue by gegere** [bcit-ci/CodeIgniter#3645]
Hello, I have spent a good amount of time researching this issue and have not found a proper solution. I don't want to simply reduce debugging locally.

[Screenshot](http://cl.ly/image/2Y0Y3l38171i)

Is this an issue or something that requires a simple tweak?

**Comment by narfbg** [comment]
See #188 and #1832.

**Comment by gegere** [comment]
[This](http://stackoverflow.com/questions/19724577/remove-codeigniter-label-wrapping-lang) worked well, created MY_lang.php file.
