### ISSUE TITLE
Encryption library and OpenSSL return binary string

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter#3647]
I'm not sure if this is intended, since my system doesn't seem to have mcrypt installed and PHP's help doesn't seem to tell me that either function used in the `create_key` method is supposed to be binary or a hexadecimal value. 

However, I'm on a Mac running OS X Yosemite and PHP 5.5.18, and it's returning a binary value from the `create_key(16)` method. 

Should this be a string? According the CI's docs, you can use that method to create an encryption key for the config file. A binary value doesn't work well for that since it just gets turned to gibberish. 

It seems like return a `bin2hex` of the value generated by `openssl_random_pseudo_bytes` should work as it creates a 32-character string, which is the correct length, right?

**Comment by narfbg** [comment]
Binary string is a string. :)

Yes, this is the intended behavior ... all random byte functions return binary, including `mcrypt_create_iv()`. It may look like gibberish, but it's completely valid. However, I guess we should give some tips for how to handle them keys easier with `bin2hex()` and `hex2bin()` ... I can't argue that putting a binary string in a config file is even easy (a copy-paste may screw it up, for example).

And yes, a 32-character *hexadecimal* representation string is the correct length as it represents 16 bytes by 2 characters per byte. However, the key itself MUST be binary ... hex format is just easier to look at.

I'll leave this one open as a reminder to update the docs with tips about handling binary strings.

**Comment by lonnieezell** [comment]
Just to verify then, the one that must be in the config file is the binary string and NOT the hex version? 
Seems like it might reduce more user error if we allowed a hex representation and converted back in the library itself? 

Is this new to CI 3 or did I just never notice it on CI 2? I didn't use the Encryption stuff much, to be honest, so I might have just missed it. I usually generated a random string off of a md5 generator and used that. :)

**Comment by lonnieezell** [comment]
Wait - I'm confusing things - the value in the config file doesn't necessarily need to be generated with that method does it? As long as it's 32 characters long it's fine, right?

**Comment by lonnieezell** [comment]
Jumping the gun - just re-read CI3's docs. It MUST be from the create_key method. 

In that case a couple of usability thoughts - 

- I think using a hex representation and converting in the encryption library would be much easier for users. 
- Since different ciphers could be in use, would it be best to have it determine the cipher that it's set to user currently and automatically determine the length of the string to generate?

**Comment by narfbg** [comment]
> Just to verify then, the one that must be in the config file is the binary string and NOT the hex version?

Correct.

> Seems like it might reduce more user error if we allowed a hex representation and converted back in the library itself? 

Sounds like a good idea, and I've thought about it ... but it will backfire - users will just continue to md5-hash something and use that as a key. And that is **very, very bad**. I'd rather have it explode in their faces and make them read the docs to find out the right way.

> Is this new to CI 3 or did I just never notice it on CI 2? I didn't use the Encryption stuff much, to be honest, so I might have just missed it. I usually generated a random string off of a md5 generator and used that. :)

It's not new, but the CI2 Encrypt lib was horrible too ... you better forget anything you did with it. :)

> Wait - I'm confusing things - the value in the config file doesn't necessarily need to be generated with that method does it? As long as it's 32 characters long it's fine, right? 

No, you need 16 bytes of binary data. At 32 chars you either have 16 unused bytes or it errors ... it should do the latter, but I'm not sure if it really does - I'll check it later.

> Jumping the gun - just re-read CI3's docs. It MUST be from the create_key method.
>
> In that case a couple of usability thoughts -
>
> - I think using a hex representation and converting in the encryption library would be much easier for users.
> - Since different ciphers could be in use, would it be best to have it determine the cipher that it's set to user currently and automatically determine the length of the string to generate?

I don't think the docs say you *MUST* use `create_key()`, but they do strongly encourage it, simply because there's no better method for creating keys. pbkdf2 (with raw output set to true) is the only alternative, if you're basing the key on a password ... it's not technically random, but it is strong. The word "strong" in cryptography really means "unpredictable".

Read up for the bullet points. :)

**Comment by lonnieezell** [comment]
Gotcha. I've updated my installer script to go back to using the binary string then. 

And I understand what's going on here, so that's good. :) 

I do think the framework has a couple of items in it (like this and date-based migrations) that could really benefit with some form of CLI tool. I understand that CI doesn't traditionally like CLI so I'm just going to say that it's maybe something we should look at for v4.

**Comment by narfbg** [comment]
You can create the key as `bin2hex($this->encryption->create_key(16))` and then store it in the config file as `hex2bin('<the hex-encoded string here>')` ... that's basically what I intend to suggest in the docs. :)
