### ISSUE TITLE
Mistake on userguide

### ISSUE THREAD

**Issue by marcossffilho** [bcit-ci/CodeIgniter#3648]
In the **user_guide_src/source/libraries/sessions.rst**, in the section about Tempdatas

> Or if you want to be sure that you're reading "flashdata" (and not any other kind), you can also use the tempdata() method:

Must be

Or if you want to be sure that you're reading "**tempdata**" (and not any other kind), you can also use the tempdata() method:

**Comment by jim-parry** [comment]
Fixed in #3650
