### ISSUE TITLE
where_in() method only accept array with quoted elements

### ISSUE THREAD

**Issue by tiny-rejoan** [bcit-ci/CodeIgniter#3652]
Hi, 
where_in() method accept array like
```
array('1','2','3');//when 1,2... should be string
```

but not work (i.e not quote automatically) when array looks like
```
array(1,2,3);
```

Is there any way to warp array elements to quote??

**Comment by narfbg** [comment]
It *does* accept non-quoted elements, it just doesn't quote them and that's completely fine.

If you're looking for help on how to quote them, please ask your question on the [forums](http://forum.codeigniter.com/) as we only accept bug reports here.
