### ISSUE TITLE
Issue with RC2 and Email Configs

### ISSUE THREAD

**Issue by cpierce** [bcit-ci/CodeIgniter#3654]
according to the documentation when I do 

```
    /**
     * Constructor
     */
    public function __construct()
    {
        parent::__construct();

        $this->config->load('email');
    }
```

I should have the email conf loaded in.  This doesn't load in when I call $this->email->send(); so to fix I had to do the following:

```
                    // this is at best a hack
                    // reporting this a bug in code igniter because this is ridiculous
                    $config = [
                        'protocol' => $this->config->item('protocol'),
                        'smtp_host' => $this->config->item('smtp_host'),
                        'smtp_port' => $this->config->item('smtp_port'),
                        'mailtype' => $this->config->item('mailtype'),
                    ];
        
                    $this->load->library('email');
        
                    $this->email->initialize($config);
```

This fixes the issue but isn't as the documentation states.

**Comment by narfbg** [comment]
Is that CI2 or CI3?

**Comment by cpierce** [comment]
CI 3 RC 2

**Comment by narfbg** [comment]
Can't reproduce it with the latest code from the develop branch ... And you really don't need to load the config manually as `$this->load->library('email')` will automatically load *application/config/email.php*.

**Comment by cpierce** [comment]
@narfbg - could it be that I have application/config/testing/email.php and other environments .... only thing I didn't mention.

**Comment by narfbg** [comment]
Depends on what you mean by that ... it may have been related, see this commit: 137aa20e0b0fd71ff8f672c57c07c4972c91c6a4

If that was the issue, you should try with 3.0rc3, which was tagged yesterday.
