### ISSUE TITLE
Where is Session_cookie_driver.php?

### ISSUE THREAD

**Issue by trungdq88** [bcit-ci/CodeIgniter#3656]
I have just upgraded my codeigniter base to 3.0rc2 and my login function refused to work. I found this in PHP error log:

    ERROR - 2015-03-10 09:09:32 --> Session: Configured driver 'cookie' was not found. Aborting.

I checked the directory `system/libraries/Session/drivers` and didn't see the `Session_cookie_driver.php` which is causing the problem I guess.

You guys have any suggestion for me? Thanks a lot.

**Comment by jim-parry** [comment]
This is a support issue and should be raised on the forum, please.
When you upgraded, did you read the upgrade guide?
http://www.codeigniter.com/userguide3/installation/upgrade_300.html
See Step 6!

**Comment by trungdq88** [comment]
Hi @jim-parry, I upgraded from Codeigniter 3 to 3.0rc2 (not from 2.0). I did read the upgrade guide but seems like it have changed recently.
Anyway, thanks for your information.

**Comment by jim-parry** [comment]
@trungdq88 My point was that the cookie driver is no longer being used. That was one of the big changes going to the release candidate, when the session changes were merged :-/

**Comment by trungdq88** [comment]
@jim-parry can you tell my why did they remove cookie as a storage driver? Is there a discussion or document explain about this? Thanks.

**Comment by jim-parry** [comment]
Short story: Basically, not secure!
Long story: https://github.com/bcit-ci/CodeIgniter/issues/3073

**Comment by trungdq88** [comment]
Thanks a lot.

**Comment by kakysha** [comment]
@trungdq88 I've reimpleneted it on top of CI3 : https://github.com/kakysha/ci/tree/session-cookie
