### ISSUE TITLE
Session problem

### ISSUE THREAD

**Issue by rickdgraaff** [bcit-ci/CodeIgniter#3658]
Putting this in de code works.
$this->session->set_userdata('dlkfhjgfm', 'iorthijr');

retrieving the data in the same method works too.

$this->session->all_userdata();

BUT! When i load another page with the same code to load all userdata the arar is empty :(
I have set in the config file "cookie" and turned off all the http(s) settings + set the domain to localhost.

The resources tab in the debugbar of Chrome doesn't show any cookies what so ever

**Comment by einca** [comment]
I have the same problem and i notice in the debug logs i have

"Configured driver 'native' was not found. Aborting".

I tried "cookie" also and the problem still remains.

I personnaly use a mysql database to store sessions and it is not working at all either wich seems pretty normal at this point

**Comment by narfbg** [comment]
There no longer are 'cookie' and 'native' drivers (but if you have 'sess_use_database' enabled the driver will be automatically set to 'database').

This should make it more obvious: 34b92c6c058a27fda4572f16af41340e0b46f4df

**Comment by rickdgraaff** [comment]
If there are no cookie sessions anymore, why are the cookies stuff still in the config??
So how we supposed to use a session or login because cookies aren't enabled anymore now.

Thanks in advance
PS: Guide says normal things and nothing bout cookies aren't supported anymore

**Comment by narfbg** [comment]
I didn't say there aren't cookies, I said there isn't a 'cookie' driver. And the user guide also says the same thing ... read the upgrade instructions.
