### ISSUE TITLE
file session driver have a problem about path.

### ISSUE THREAD

**Issue by yupmin** [bcit-ci/CodeIgniter#3664]
sessions folder is [web_root]/sessions
error message is below..

Message: touch(): Unable to create file sessions/ci_session4dc0e26a2bb79fc8a06893ce8fbd19b9e1974a0b because No such file or directory
Filename: drivers/Session_files_driver.php
Line Number: 234

		elseif ($this->_fingerprint === md5($session_data))
		{
			return ($this->_file_new)
				? TRUE
				: touch($this->_file_path.$session_id); <== line 234
		}

at line 234, 'pwd' path is '/'. in 'write function' save path is maybe missing.

**Comment by narfbg** [comment]
Might be related to a PHP bug where `SessionHandler::read()` never returns FALSE and therefore a certain error condition is never treated as such ...

But either way, it means CI simply doesn't have permissions to write to that directory. Try asking on the [forums](http://forum.codeigniter.com/) if you need help with that ... it's not a bug.

**Comment by yupmin** [comment]
this is not permission problem of directory. i want you to rethink this.

my env is php-fpm + nginx

**Comment by narfbg** [comment]
Well, then I want you to rethink your demanding language and *prove* that it is a bug ... the fact that you think the FPM SAPI or nginx have anything to do with this only tells me that you don't know how the sessions works at all.

**Comment by yupmin** [comment]
First, i do not speak English well.

i tested by below order.

wget https://github.com/bcit-ci/CodeIgniter/archive/3.0rc3.zip
unzip 3.0rc3.zip
mkdir CodeIgniter-3.0rc3/sessions
chmod 777 CodeIgniter-3.0rc3/sessions

after web server setting.

edit application/config/config.php

$config['sess_save_path'] = 'sessions'; <-- edit this.

edit application/controllers/Welcome.php


        public function index()
        {
                $this->load->library('session');  <-- add this.
                $this->load->view('welcome_message');
        }

and reload twice!! 

-------------
A PHP Error was encountered

Severity: Warning

Message: touch(): Unable to create file sessions/ci_session80b446fbb643d2353f19c9679de9b3d1138c4bb3 because No such file or directory

Filename: drivers/Session_files_driver.php

Line Number: 234


------------------------


and add debug code liek below.

var_dump('read -->',\__FILE\__." ".\__LINE\__." line", array('$this->_file_path' => $this->_file_path, 'pwd()' => getcwd()));

and result is..

at function open

/home/ec2-user/workspace/codeigniter/system/libraries/Session/drivers/Session_files_driver.php 131 line

array(2) { ["$this->_file_path"]=> string(19) "sessions/ci_session" ["pwd()"]=> string(36) "/home/ec2-user/workspace/codeigniter" }

at function read

/home/ec2-user/workspace/codeigniter/system/libraries/Session/drivers/Session_files_driver.php 201 line

array(2) { ["$this->_file_path"]=> string(19) "sessions/ci_session" ["pwd()"]=> string(36) "/home/ec2-user/workspace/codeigniter" }

at function write

/home/ec2-user/workspace/codeigniter/system/libraries/Session/drivers/Session_files_driver.php 218 line

array(2) { ["$this->_file_path"]=> string(19) "sessions/ci_session" ["pwd()"]=> string(1) "/" }



and ... I prepared this one for you. testing site... ^^

http://session.simpletools.kr/



$this->_config['save_path'] must be absolute path. if first char is not '/'. must add FCPATH.

**Comment by narfbg** [comment]
Yeah ... only absolute paths are supported, this is explained in the manual.

**Comment by yupmin** [comment]
hummm... but. logs, cache folder is relative path. 
i see this point. and fix it.

$config['sess_save_path'] = FCPATH.'sessions';

thank you.

**Comment by narfbg** [comment]
dd8c0ed8d595425cd935c2f4638c398d2a2d23e2

**Comment by Deepak0110** [comment]
Thank you yupmin thank you so much error solved you rocks..!

**Comment by iamchathu** [comment]
How to set Codeigniter 3 Session File Driver Path correctly : 

http://chathu.me/2015/09/30/codeIgniter-3-session-file-driver/
