### ISSUE TITLE
Image_lib:image_process_gd() just copies file if width/height match original, but what about quality?

### ISSUE THREAD

**Issue by louisl** [bcit-ci/CodeIgniter#3666]
Image_lib:image_process_gd()

```
// If the target width/height match the source, AND if the new file name is not equal to the old file name
// we'll simply make a copy of the original with the new name... assuming dynamic rendering is off.
if ($this->dynamic_output === FALSE && $this->orig_width === $this->width && $this->orig_height === $this->height)
{
    if ($this->source_image !== $this->new_image && @copy($this->full_src_path, $this->full_dst_path))
    {
        chmod($this->full_dst_path, $this->file_permissions);
    }
    return TRUE;
}
```

I think you also ought to be checking '$this->quality' here otherwise the quality setting will have no effect as you're copying the original image. If I set quality I expect the file to have that quality regardless of the dimensions.

I guess, it's a bit of a dilemma for backwards compatibility with the 90 default quality so you probably need a check in place to see if quality was actually set in the config or if it was left as default.

Regards

Louis

**Comment by rashidshafique** [comment]
Can you determine the quality of an existing image?

**Comment by narfbg** [comment]
I don't really know what this is about and was never interested in it. Feel free to submit a pull request if you do.
