### ISSUE TITLE
CI 2.2.1 - Security error on special content

### ISSUE THREAD

**Issue by pijulius** [bcit-ci/CodeIgniter#3667]
Hi Guys,

Just upgraded to the latest stable CodeIgniter and having xss turned on by default there is a php error in the entity_decode() method:

Notice: Undefined offset: 1 
core/Security.php # 543

It seems the check doesn't check if the index in the $matches array exists so it throws an undefined offset, I fixed this by adding an isset() before the array_search like this:

/system/core/Security.php #Line 543
if (isset($matches[$i]) && ($char = array_search($matches[$i].';', $_entities, TRUE)) !== FALSE)

Please check it out and see if there is a better option for this fix or something else going on wrongly, I know you are working hard on the new CI3 but please don't forget about CI2 too as in my opinion CI3 is going into the wrong direction, a lot of changes make it impossible for one to move over from CI2 and most of them are useless changes so if one has hundreds of websites with CI2 one won't be able to update to CI3 so please don't give up support on CI2!

Thanks in advance!
Julius

**Comment by narfbg** [comment]
This is already fixed: f99a4de6ac97a10570f1391998b8087bce8371e1

**Comment by pijulius** [comment]
Hi Narfbg,

Thanks a lot for the quick fix, and sorry for my bad, I didn't check out the commits before writing but will not happen anymore :)

Also can confirm that the fix works just fine.

Regards,
Julius
