### ISSUE TITLE
count_all_results() with $this->reset_select()

### ISSUE THREAD

**Issue by yaoshanliang** [bcit-ci/CodeIgniter#3668]
On line 1358 of file ['system/database/DB_query_builder.php'](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_query_builder.php)，function `count_all_results()` will call `reset_select()`, and this will reset the condition of select query.
However, in some case, we need to get the results as well as count. For example, in pagination, we need to count all the results, but only results of 0-20 using limit.
If we code as
    
    $count = $this->db->count_all_results();//get total numbers
    $this->db->limit(0, 20);//get first 20
    $data = $this->db->get()->result();//this will not work

So, I suggest to add a parameter with boolean value to judge whether to call  `reset_select()`.

**Comment by narfbg** [comment]
Please don't open issues for feature requests if you're also submitting a pull request for the same feature.
