### ISSUE TITLE
Just add 'session' to autoload.php, meet this error

### ISSUE THREAD

**Issue by wphp** [bcit-ci/CodeIgniter#3670]
A PHP Error was encountered

Severity: Warning

Message: mkdir() [function.mkdir]: Invalid argument

Filename: drivers/Session_files_driver.php

Line Number: 117

Backtrace:

File: E:\Dropbox\Backup\Wamp\WWW\cms.com\index.php
Line: 292
Function: require_once

An uncaught Exception was encountered

Type: Exception

Message: Session: Configured save path '' is not a directory, doesn't exist or cannot be created.

Filename: E:\Dropbox\Backup\Wamp\WWW\cms.com\system\libraries\Session\drivers\Session_files_driver.php

Line Number: 119

Backtrace:

File: E:\Dropbox\Backup\Wamp\WWW\cms.com\index.php
Line: 292
Function: require_once

**Comment by wphp** [comment]
If I want to use the full native Session, how to do it?

**Comment by narfbg** [comment]
Of course you'll get an error, you didn't configure it ...

Ask your questions on the [forums](http://forum.codeigniter.com/) if you need help.
