### ISSUE TITLE
CI_Config class - feature request

### ISSUE THREAD

**Issue by SystemDisc** [bcit-ci/CodeIgniter#3672]
Can we add the following code to the CI_Config class?

It would allow us to do things like `$this->config->property_key` instead of `$this->config->item('property_key')` and `$this->config->property_key = 'stuff'` instead of `$this->config->set_item('property_key', 'stuff')`
``` PHP
class CI_Config {

	...

	public function __get($item)
	{
		return $this->item($item);
	}

	public function __set($item, $value)
	{
		return $this->set_item($item, $value);
	}

	public function __isset($item)
	{
		return !is_null($this->item($item));
	}

	public function __unset($item)
	{
		$this->set_item($item, NULL);
	}
}
```

(I would create a pull request, but it's just something I though of and I'm lazy. I can create a pull request if that's easier)

**Comment by narfbg** [comment]
No.

And now you'll probably ask why ... I just don't see any benefit in this.

**Comment by SystemDisc** [comment]
No prob, I'll just add them with MY_Config. Thanks
