### ISSUE TITLE
Facing Problem to fetch record from database date wise in codeigniter.

### ISSUE THREAD

**Issue by jogee31** [bcit-ci/CodeIgniter#3685]
Hi,

I am facing problem to fetch record from database for a year.
Actually I m having one DB Table, in that i have to columns, first is Date From and second is Date to. So i want to fetch all the record for current Year, date from would be equal to or greater than first date of current year and date to would be less than or equal to last date of current year.

Please help me.

**Comment by narfbg** [comment]
Post your questions on the [forums](http://forum.codeigniter.com/) please, we only accept bug reports here.

**Comment by jogee31** [comment]
Okay Thanks.
