### ISSUE TITLE
About get_instance() result, an obsolete note within the documentation?

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#3686]
I read this forum comment http://forum.codeigniter.com/thread-1535-post-6938.html#pid6938

And this mentioned page from the documentation attracted my attention: http://www.codeigniter.com/userguide3/general/ancillary_classes.html

This is what the page says within a note:
"
You’ll notice that the above get_instance() function is being passed by reference:
$CI =& get_instance();
This is very important. Assigning by reference allows you to use the original CodeIgniter object rather than creating a copy of it.
"

This comment I found within PHP documentation: http://php.net/manual/en/language.references.return.php#78123
At the moment I did not see more formal text about how an object is returned by a function/method in PHP5.

I did the following quick test:

```php
$ci1 = get_instance();
$ci2 = get_instance();

$ci1->test1 = 'Test 1';

var_dump($ci1->test1);
echo '<br />';
var_dump($ci2->test1);
```
and this is the result:
```
string(6) "Test 1" 
string(6) "Test 1"
```
What my eyes see is that the "=" operator here passes the returned object by a reference. No "=&" is needed I think.

I think, that the recommended syntax $CI =& get_instance(); is applicable for PHP4, now the note is obsolete.

PHP documentation is not helping much on this, I hope that I am not missing anything.

**Comment by ivantcholakov** [comment]
I see within the Framework's code sentences like this one:

```php
return get_instance()->config->site_url($uri, $protocol);
```

This makes me more confident that the note is obsolete.

**Comment by narfbg** [comment]
It is obsolete, yes - it will work with or without assign-by-reference.

However, there's still a difference between assigning objects by reference or not - you'll have a lower memory footprint with references. Please don't submit a PR that removes every mention of `=&` :D

**Comment by kakysha** [comment]
@ivantcholakov, fyi: "Just remember: pointers to objects, not objects themselves, are passed by copy. These pointers are COPIES of the original unless you use "&" in your parameter or return list to actually pass the originals."

**Comment by ivantcholakov** [comment]
@kakysha
The text is from http://php.net/manual/en/language.oop5.references.php
It is just a comment, but I assume it is correct.

I read the official part of the page, and as I understood, if I use "=" I am making a copy of an object identifier structure with a pointer to the same object, not a copy of the object itself. Some loss of memory happens indeed, not too much my taste.

I realized that in CodeIgniter's note the phrase "Assigning by reference allows you to use the original CodeIgniter object rather than creating a copy of it." is not correct anymore (for PHP5).

**Comment by vlakoff** [comment]
These references because of alleged memory footprint are just pointless. It's time to admit it.

**Comment by narfbg** [comment]
There are no concerns about it. It's just the fact that there is a difference and I'm always annoyed when once an year somebody comes saying "objects are always returned by reference" (which is not true) and wants to remove all reference usage.

Is it OK not to use references? Sure, it's completely fine.
Does that mean we *have* to remove them? No.
