### ISSUE TITLE
Bug with database configuration

### ISSUE THREAD

**Issue by ColonelMoutarde** [bcit-ci/CodeIgniter#3687]
Hello,
If i use the argument withos codeigniter 3.0 rc3 : 
```
$db['default']['pconnect'] = TRUE; 
```
in database.php

i have this error: 
An uncaught Exception was encountered

Type: Exception

Message: Configured database connection is persistent. Aborting.

Filename: S:\wamp\www\run2\system\libraries\Session\drivers\Session_database_driver.php

Line Number: 94

No error if $db['default']['pconnect'] = FALSE;

**Comment by jeffstoner** [comment]
The manual clearly says to not use persistent db connections for the Session library.
http://www.codeigniter.com/userguide3/libraries/sessions.html#database-driver

**Comment by ColonelMoutarde** [comment]
Ok,
But i'ts an uncaught Exception, the exception can be catched.

This parameters work in ci2.2.x

**Comment by jeffstoner** [comment]
It's not an uncaught exception. The Session library's database driver is the one throwing the exception.

**Comment by narfbg** [comment]
If it wasn't uncaught, you wouldn't see an error message, which is the whole point.

**Comment by gbarosio** [comment]
FALSE is not valid, you need to unset pconnect in order to make this work. That is a bug, IMHO

**Comment by gbarosio** [comment]
Correction 'FALSE' is not valid. People using FALSE in pconnect, without the quotes (apparently supported in other parts of the array, will receive the error because the database driver will consider 'FALSE' as true.

**Comment by gbarosio** [comment]
* Persistent connection flag
	 *
	 * @var	bool
	 */
	public $pconnect		= FALSE;
