### ISSUE TITLE
notice on setting config mismatch

### ISSUE THREAD

**Issue by KickassCoxa** [bcit-ci/CodeIgniter#3688]
Would be useful if codeigniter would give notice's when trying set CI Libraries config variables on mismatch.

Example:

$config['upload_paht'] = './uploads/';
$config['allowde_types'] = 'gif|jpg|png';
$config['max_sze']	= '100';
$config['max_width'] = '1024';
$config['max_height'] = '768';

$this->load->library('upload', $config);

Would give notices:
* Unknown Setting "upload_paht" in upload_library
* Unknown Setting "allowde_types" in upload_library
* Unknown Setting "max_sze" in upload_library

**Comment by narfbg** [comment]
Useful to you, but prevents others from having their own user-defined settings.

**Comment by jim-parry** [comment]
@KickassCoxa There is a translation tester that can be used for that purpose ... http://forum.codeigniter.com/thread-1242.html

**Comment by KickassCoxa** [comment]
@narfbg it does not prevent anything, in my opinion. Because it could give only a notice when there is development enviroment set. it does not have to be hard coded to stop script execution or force file upload to be not completed.

**Comment by narfbg** [comment]
Undesired notices aren't any less annoying just because they only occur during development. What you want is a unit test's job, not one of the framework ... the framework doesn't care if you set an extra value or not.
