### ISSUE TITLE
Redis cache engine save issue

### ISSUE THREAD

**Issue by mafooo** [bcit-ci/CodeIgniter#3691]
You can set key in the cache and read it fine until it's TTL has expired. Then it will miss and not save anything to that key anymore.

You have to go into redis and manually delete the '_ci_redis_serialized' key for it to work again.

The save() function was trying to use sAdd as a check if the key was created, but that will return false if it is already present in the set, so I have added a check to see if it is already a member of the set, and created a pull request for the fix: [https://github.com/bcit-ci/CodeIgniter/pull/3690](https://github.com/bcit-ci/CodeIgniter/pull/3690)

**Comment by narfbg** [comment]
Please don't open PRs and issues separately. Writing this description in the PR itself would've been completely fine and would've made it easier to review.

**Comment by mafooo** [comment]
By bad
