### ISSUE TITLE
form_validation language error

### ISSUE THREAD

**Issue by nfaiz** [bcit-ci/CodeIgniter#3693]
I'm using CI 3.0 

In controller I'm using this code

```
$this->lang->load('form_validation', $lang);
```

to load my native language. But when I run this code 

```
$this->form_validation->run() == TRUE
```

the default language loaded instead. I found out that this code 

```
$this->CI->lang->load('form_validation'); 
```
located at _system/libraries/Form_validation.php_

replaced my original code. I'm not sure whether I'm doing it right and please help me.

**Comment by narfbg** [comment]
Please post your questions on the [forums](http://forum.codeigniter.com/), we only accept bug reports here.
