### ISSUE TITLE
Cannot override Core Libraries with packages?

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter#3694]
Overriding core libraries doesn't seem to work any longer. There's a check in `Loader::_ci_load_library()` that checks if the library exists in `BASEPATH/libraries` and, if so, runs `_ci_load_stock_library()`. This method never checks across package folders for classes overriding these core libraries. 

@narfbg Is this intentional? Did I just miss it in the docs? Seems like packages should have the ability to override this, yes? 

This came up as a comment on my Profiler bar replacement and I found it when digging through why it wasn't working. Because the profiler bar, being a small package, was placed in the third_party folder and wasn't loading like it used to.

**Comment by jeffstoner** [comment]
From the docs: To use one of your own system classes instead of a default one simply place your version inside your local application/core/ directory

http://www.codeigniter.com/userguide3/general/core_classes.html#replacing-core-classes

**Comment by jeffstoner** [comment]
The goes for overriding/extending libraries...put your replacement in application/libraries

http://www.codeigniter.com/userguide3/general/creating_libraries.html#replacing-native-libraries-with-your-versions

**Comment by lonnieezell** [comment]
I am very aware of those parts of the docs,  but packages also allow you to include libraries and in the past they have overriden system libraries just fine. That's why I posted this: to check if this was an intentional BC break or not.

And I do apologize if the use of "core" was confusing. I did mean files in system/libraries.

**Comment by narfbg** [comment]
Did it work in 2.x?

#3692

**Comment by lonnieezell** [comment]
Just verified and, yes, it works in 2.1.4. 

I realize it was never advertised feature but is very useful for distributing changes, or packaging up stuff we use on our own projects a lot.

**Comment by lonnieezell** [comment]
Sorry - didn't see that since it was closed. I did look through open issues, though. :) 

Should I move this to the forums, then?

**Comment by narfbg** [comment]
That's not usually my stance about undocumented features, but if this one in particular has previously worked it would screw up a lot of things ...

**Comment by lonnieezell** [comment]
Excellent. Thanks. I didn't mean for you to have to do the update, I would have been willing to, but I appreciate it.
