### ISSUE TITLE
insert_batch and update_batch with multiple where keys

### ISSUE THREAD

**Issue by Zayon** [bcit-ci/CodeIgniter#3695]
Something like :

```php
$data = array(
   array(
      'title' => 'My title' ,
      'name' => 'My Name 2' ,
      'date' => 'My date 2'
   ),
   array(
      'title' => 'Another title' ,
      'name' => 'Another Name 2' ,
      'date' => 'Another date 2'
   )
);

$this->db->update_batch('mytable', $data, 'title, date');
```
// Produces:
// UPDATE `mytable` SET `name` = CASE
// WHEN `title` = 'My title' AND `date` = 'My date 2' THEN 'My Name 2'
// WHEN `title` = 'Another title' AND `date` = 'Another date 2' THEN 'Another Name 2'
// ELSE `name` END,
// WHERE `title` IN ('My title','Another title')
// AND 'date' IN ('My date 2', 'Another date 2')

**Comment by narfbg** [comment]
If you can come up with a sensible way to implement it, please submit a pull request. No guarantee that it would be accepted, but it surely won't happen any other way.

**Comment by parthviroja** [comment]
Hi... friends i have an solution of this issue... 
i solved it .. 
refer this link : 

https://github.com/parthviroja/codeigniter/

**Comment by vikaskumarmca** [comment]
Thanks Friend please share more codeigntier problem.

Please send request for google chat :+1: 
vikaskumarmca1985@gmail.com
