### ISSUE TITLE
Session_files_driver's garbage collector memory issue

### ISSUE THREAD

**Issue by dtmax** [bcit-ci/CodeIgniter#3701]
I have a lot of error messages like this:
```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32 bytes) in /var/www/...../system/libraries/Session/drivers/Session_files_driver.php on line 321
```
It's because of **scandir()** function, it reads all session file names into an array, in this block of code:
```
if ( ! is_dir($this->_config['save_path']) OR ($files = scandir($this->_config['save_path'])) === FALSE)
{
	log_message('debug', "Session: Garbage collector couldn't list files under directory '".$this->_config['save_path']."'.");
	return FALSE;
}
```
I think there should be another mechanism of session files storing/listing. May be to store them in three-like folder structure. In this case GC could use scandir() only for some of those subfolders.

**Comment by narfbg** [comment]
How many sessions do you have for that to happen? Millions?

**Comment by dtmax** [comment]
Less than 100k, I think. Already moved to Redis driver.
