### ISSUE TITLE
Form validation with model callback does not count error.

### ISSUE THREAD

**Issue by JeremybellEU** [bcit-ci/CodeIgniter#3702]
Using the form_validation system library, I encountered a bug with a callable model function in the _execute function.

Whenever you submit a callable function consisting of an array e.g.
```php
$this->form_validation->set_rules(
			'netid',
			'NetID',
			array('required', array($this->user, 'exists_by_netid'))
		);
```

with the function in the user model

```php
public function exists_by_netid($netid)
  {
    $value = $this->db->query('
      SELECT 1
      FROM users
      WHERE netid = ' . $this->db->escape($netid) . '
    ')->first_row();

    return isset($value);
  }
```

this correctly returns false/true if the value exists in the database. Then in form_validation.php:749 the result of the callback is found by

```php
$result = is_array($rule)
						? $rule[0]->{$rule[1]}($postdata)
						: $rule($postdata);
```

Then the result is checked on form_validation.php:815. Whenever the callback returned false, it will go into this branch. However, the very first check is
```php
if ( ! is_string($rule))
				{
					return;
				}
```
The problem now is that the actual error is not delegated to the run() method at form_validation.php:418 where at form_validation.php:487 the errors are counted.

Since this error was not inputted in $this->_error_array it does not determine an error was encountered.

# How to fix this? #
The most easy fix was adding the following line before line form_validation.php:418

```php
$this->_error_array[$row['field']] = $row['errors'];
```

However a simple incrementer for $this->_error_array could work too.

I was not able to create a pull request for this, but hopefully someone else can code review this (and maybe verify the issue) and then apply the fix.

UPDATE: Since the $row contains the error, we can simply enforce that callable rules must have an errors in order to be tracked.

**Comment by JeremybellEU** [comment]
As a reply to myself: the 'ERROR' is not a good fix, as this will also be displayed using validation_errors();

Therefore an incrementer would be more user friendly. However keeping track of the actual error will be a bit harder to do.

**Comment by narfbg** [comment]
This is not a bug, you're required to set the error message yourself.

http://www.codeigniter.com/userguide3/libraries/form_validation.html#callable-use-anything-as-a-rule
