### ISSUE TITLE
Form_validation function to clean error messages

### ISSUE THREAD

**Issue by KickassCoxa** [bcit-ci/CodeIgniter#3705]
I develop new application. And i use form validation to validate inputs.
Recently i came to a problem.

In my form i have tabs with same main form input names, but each input name has prefix depending on what tab it is, like:

formdata[page_title][lithuanian]
formdata[page_title][english]
formdata[page_title][etc]

When posted, all languages are validated in foreach loop depending on language. Problem is that each time i validate inputs on each language, validation_errors() makes more and more errors. 

And it's not possible to assign errors for each form-language-tab.

My idea, is that there could be function reset_validation_errors() / reset_validation_messages()

**Comment by narfbg** [comment]
There is, reset_validation().
