### ISSUE TITLE
hooks loading twice

### ISSUE THREAD

**Issue by KickassCoxa** [bcit-ci/CodeIgniter#3707]
I am trying to implement hooks, to be able read example.com/language/seo-id segments and re-set controller that has to be loaded, depending on seo-id module that is defined in database.

Anyway. 

        $hook['post_controller_constructor'][] = array(
            'class'    => 'BaseHook',
            'function' => 'initiate',
            'filename' => 'BaseHook.php',
            'filepath' => 'hooks',
            'params'   => array( )
        );

        class BaseHook {

            public function initiate(){
                if ( !defined('basehook_initiate') ){
                    $ci = &get_instance();
                    $ci->config->set_item('enable_hooks', false);

                    $ci->db->query('INSERT INTO table ( `id` ) VALUES ( 1 )');
                }
                define('basehook_initiate', '123');
            }
        }

... results in two inserted rows in the table on every http request. dont know why it's not even possible to secure code with constant?

**Comment by narfbg** [comment]
Whatever it it that's causing 2 insertions, it's not all of the code that you're showing here.

Anyway, we only accept bug reports on github and this is the 4th issue opened by you, none of the four being a valid bug report ... Please post your questions on the [forums](http://forum.codeigniter.com/).
