### ISSUE TITLE
where_in - preg_match(): Compilation failed: regular expression is too large

### ISSUE THREAD

**Issue by suvozit** [bcit-ci/CodeIgniter#3708]
```
A PHP ERROR WAS ENCOUNTERED!

Severity: 2
Message: preg_match(): Compilation failed: regular expression is too large at offset 63858
Filename: /srv/www/log_pixel/releases/20150326203504/system/database/DB_query_builder.php
Line: 2331
```

**Comment by narfbg** [comment]
Line 2331 in DB_query_builder.php is the closing parenthesis for a `preg_split()` call (not a `preg_match()` one) and its regular expression is 19 characters long. This means is that you either have a quite outdated version of the file, or you've manually modified it.

The message itself however indicates that you've passed an unusually large string to some of the query build methods, and it is not made to work with such - you're better off with using raw queries.

Also, please provide more details next time and unless you are sure you've got a valid bug report, post your questions on the [forums](http://forum.codeigniter.com/).

**Comment by suvozit** [comment]
Thanks @narfbg for the reply.

I am currently using **CI 3.0rc3** which is different than the current head.
https://github.com/bcit-ci/CodeIgniter/blob/4ccc2f80c501d839245915d058f77dea7f1bd3f3/system/database/DB_query_builder.php#L2331
```php
if (($op = $this->_get_operator($conditions[$ci])) === FALSE
    OR ! preg_match('/^(\(?)(.*)('.preg_quote($op, '/').')\s*(.*(?<!\)))?(\)?)$/i', $conditions[$ci], $matches))
{
    continue;
}
```

I solved it using `array_chunk` to split the query. Shall I update the system/DB_query_builder.php to the current head?
