### ISSUE TITLE
Email library batch_bcc_send() will never know if all batches actually sent _spool_email()

### ISSUE THREAD

**Issue by conzone** [bcit-ci/CodeIgniter#3711]
Email Library send()

When sending a batch email where the _bcc_array of email addresses to send to is greater than the bcc_batch_size limit and thus the function batch_bcc_send() is called.

The function batch_bcc_send() does not accurately return a response whether or not the email was truly sent. After calling _spool_email() there is no logic to return a boolean false if the sending actually failed.

There is no way to know that all the batches successfully sent.

For my specific case it would make sure to track all of the _spool_email() calls and if any of them fail to return a response that there was a send failure. However, if all of the calls to _spool_email() were a success then I'd expect a boolean true to bubble back up to response from the original send() call.

![screen shot 2015-03-27 at 12 27 35 pm](https://cloud.githubusercontent.com/assets/105103/6875533/af85e8b4-d47c-11e4-913b-19526b37dc41.png)

**Comment by narfbg** [comment]
If anything, I'd change it to return void instead of boolean ...
