### ISSUE TITLE
Illegal offset type in unset (on Session.php line 727)

### ISSUE THREAD

**Issue by luizzz** [bcit-ci/CodeIgniter#3726]
Got a lot of warnings in my log with:

```php
Severity: Warning --> Illegal offset type in unset C:\var\data\localweb\gv\system\libraries\Session\Session.php 727
```
What is it?

p.s.: sorry if this is not appropriated to post here :P

**Comment by narfbg** [comment]
It's not appropriate here indeed. Post your questions on the [forums](http://forum.codeigniter.com/) and only report bugs here.
