### ISSUE TITLE
Email library bug ?

### ISSUE THREAD

**Issue by ghost** [bcit-ci/CodeIgniter#3738]
2 days ago i used email library to send email from CI based web app. As i read on CI 3 docs, nothing different in methodology from CI 2.x to use email class. But the email never sent to recipient address, and the page keep loading. Even i used configuration & sample code from documentation it keep fail to sent email. I though my email server configuration was wrong, i try different config, but still no luck. 

So i test install PHPMailer to CI, and email just sent right away without any problem. Is anyone see this as a bug or something? On CI 2.x i have meet no problem using email library from CI.

Thanks in advance.

**Comment by narfbg** [comment]
It may turn out to be a bug, but "it's not working" tells us nothing ... please give us detailed information that can be used for debugging.

**Comment by it9xpro** [comment]
I also had a similar error. I really do not understand . help me fix CI 3X

**Comment by LouisMilotte** [comment]
Please supply what the error report tells you when this error is triggered.

**Comment by arisdario** [comment]
There is no Error, it is just not sending emails and no result from echo $this->email->print_debugger(); so we dont have an error to provide !

**Comment by narfbg** [comment]
Well you have to give us *something*. E-Mail is a complex protocol, we can't just guess what went wrong ... Dig for some error logs, experiment, etc.

**Comment by Nucleo1985** [comment]
Sorry for very late reply. Currently working on something urgent. Im gonna try again next week, and i hope i can provide useful info or if i can some suggestion. Thanks for the attention.

**Comment by it9xpro** [comment]
I have chosen to https://github.com/ivantcholakov/codeigniter-phpmailer

**Comment by bvrignaud** [comment]
I have the same problem.

my config/email.php :
```php
$config['protocol'] = 'smtp';
$config['smtp_host'] = 'mail.xxxxx.fr';
$config['smtp_user'] = 'xxxx@xxxxxx.re';
$config['smtp_pass'] = 'xxxxxxxxxxxx';
```
If I use the CI 2.2 email library, it's ok, but it isn't with the CI 3 one.
Notes : You can test it just with switch Email.php 2.2 between 3

**Comment by bvrignaud** [comment]
The problem come from the _send_with_smtp and if you replace 
```php
if ( ! $this->_smtp_connect() OR ! $this->_smtp_authenticate())
{
	return FALSE;
}
```
by the old one (CI 2.2) :
```php
$this->_smtp_connect();
$this->_smtp_authenticate();
```
It's OK

**Comment by narfbg** [comment]
So one of these two calls is returning FALSE. Would you care to check which one and why?

**Comment by mwhitneysdsu** [comment]
This is what I'm seeing if I use this code in place of the code listed by @bvrignaud above:

```php
        $tempVal = $this->_smtp_connect();
        if (! $tempVal) {
            log_message('error', '_smtp_connect: ' . $this->print_debugger(array()));
        }
        $tempVal = $this->_smtp_authenticate();
        if (! $tempVal) {
            log_message('error', '_smtp_authenticate: ' . $this->print_debugger(array()));
        }
```

```
_smtp_authenticate: 220 For xxxx Use Only
<br /><pre>hello: 250-xxxx.xxxx.xxx Hello xxxxx.xxxx.xxx [###.###.###.###], pleased to meet you
250-SIZE 500000000
250-STARTTLS
250-PIPELINING
250-8BITMIME
250 HELP
</pre>Failed to authenticate password. Error: 504 Unrecognized authentication type
<br />
```

This is after initializing the library with:

```php
$this->ci->email->initialize(
    array(
        'mailpath' => '/usr/sbin/sendmail',
        'mailtype' => 'text',
        'protocol' => 'smtp',
        'sender_email' => 'sender@xxxx.xxxx.xxx',
        'smtp_host' => 'xxxx.xxxx.xxx',
        'smtp_pass' => 'smtp_password_here',
        'smtp_port' => 25,
        'smtp_timeout' => 30,
        'smtp_user' => 'sender@xxxx.xxxx.xxx',
    )
);
```

**Comment by LouisMilotte** [comment]
Research regarding SMTP error 504 suggests a relation to the SSL/TLS settings of the exchange server and if the application using SMTP is matching those settings.

Suggestions:

1. Make sure hostname and port match the exchange server's settings for sending mail from an application. i.e. SMTP Port, SMTPSSL Port, or TLS Port.

2. Set the ini array to include the key `smtp_crypto` and set its value to the encryption method that the exchange server requires. As per http://www.codeigniter.com/userguide3/libraries/email.html your options are: tls, or ssl.

**Comment by narfbg** [comment]
OK, this is a configuration issue then ... not checking the return values doesn't fix anything, it's just sendmail that ignores authentication errors.

**Comment by mwhitneysdsu** [comment]
I would say that, at the least, there is some room to improve the error reporting in the existing code for the email library. With the 3.x code, I get no error messages and mail is not sent. With the 2.x code, I still get no error messages, but mail is sent. 

It was only by changing the code to force it to log the errors when the returns failed that I was able to determine what error was occurring on my site. So, the original issue here still stands, with certain configurations the library will refuse to send email but will not give any indication as to why that is occurring.

**Comment by narfbg** [comment]
What do you mean you don't get error messages? Your feedback above shows `print_debugger()` output ...

**Comment by mwhitneysdsu** [comment]
You're right, I'll have to double check my code. I thought I was logging the debug messages when I received a false return, but it looks like I may have disabled that in production (exactly where I should have enabled it, apparently).
