### ISSUE TITLE
url helper function undefine in error page default CI

### ISSUE THREAD

**Issue by zawaruddin** [bcit-ci/CodeIgniter#3743]
i've same problem with this one
http://forum.codeigniter.com/thread-1694.html?highlight=base_url

in CI 2.x.x it's no problem to customize the default error page from CI using base_url etc. But in CI 3 there's problem that say the function in url helper (base_url) isn't defined.

**Comment by narfbg** [comment]
This is not a bug and we don't provide support via github. Involve youself in that forum thread instead.
