### ISSUE TITLE
Mobile bot not detected

### ISSUE THREAD

**Issue by pijulius** [bcit-ci/CodeIgniter#3750]
Hi Guys,

Today we just had a request from a client why google isn't detecting our mobile websites and we tracked down the problem to the User_agent.php library.

It seems CI isn't able to detect a mobile client if it's a bot as first it checks for bot and if bot found it will simply exit and not continue checking and so it will never recognize it as mobile if it is a mobile bot.

This bug affects both CI Stable and Dev version and can be easily fixed by checking for mobile user agent too even if bot is recognized:

CI 2.2.1
system/libraries/User_agent.php - _compile_data() # 148
if ($this->$function() === TRUE)
{
	break;
}

CHANGING to will fix the problem:
$this->$function();

You can check the functionality of this bug/fix here:
https://www.google.com/webmasters/tools/mobile-friendly

Regards,
Julius

**Comment by narfbg** [comment]
I consider this lack of a feature, not a bug - a robot is not a mobile device.

Anyway, this feature was added in CI3.0. You'll have to upgrade if you want to use it.

**Comment by pijulius** [comment]
Hi Narfbg,

Can you please point me to the fix in CI3 that you are talking about? also if I may ask, how isn't this a bug? isn't we (CI) doing something wrong for not detecting the mobile bot on google? I don't think you can say that google is the one to blame on this.

Regards,
Julius

**Comment by narfbg** [comment]
I'm not pointing you to a "fix" so you can copy-paste it - that would be to encourage a user to manually modifying the system/ files and I don't want to do that, especially given that there already is a newer version of the framework that you can simply update to.

And no, skipping the mobile check for a robot is not something wrong, I already explained why in my previous comment. And I'm not blaming Google either, as I said - it's a feature that simply doesn't exist in CI2, not a bug.

**Comment by pijulius** [comment]
I'm not requesting for the fix on CI3 to copy/paste (have better things to do than modifying system files that's why I report you guys the problems so I don't have to touch core files) the reason I ask for you to point me to a fix is that I can see how you fixed it and what you did.

**Comment by pijulius** [comment]
Ok, I see what you did, you added 
$this->_set_mobile();

to the _set_robot() method too if it founds out it is a robot which is great, tested in CI3 and can confirm that it works there but may I know why you aren't willing to fix this in CI2? did you give up on CI? as if you remember my other case it isn't as easy as you say to upgrade to CI3 and if you did give up on CI2 we will need to fork CI3 and start to work on that ourselves.

Regards,
Julius

**Comment by LouisMilotte** [comment]
What's with the accusations? narfbg and the volunteers to this did not "give up" on CI2. As any worthwhile versioning system goes; enough changes were made to CI that CI2 is and or will be no longer supported.

Do you and your clients a favor and update to the new CI version.

**Comment by pijulius** [comment]
Hi LouisMilotte,

Ok, got it, that's what I wanted to know that you indeed gave up support on CI2. I don't mind at all as it's your choice so you can do it freely without any problem I just needed to know this as we have around 500 sites running on CI2 and I can't upgrade them to CI3 just by replacing system files as for e.g. you dropped controller recognition for lowercase files in CI3 so that means we will need to rename all those files for each website not to mention some other changes in CI3 that you dropped so it won't be backward compatible.

But again, I'm not accusing you guys of anything, it's your project so you can take whatever road you wish I just needed to know that CI2 won't be supported anymore.

Thanks,
Julius

**Comment by narfbg** [comment]
Fixing is for things that are broken, and for the 3rd time - it's not a bug, it's not broken, it's just a feature that you wish it had.

And if you're asking if we've given up on including new features into CI2 - yes, we've given up on that years ago and not a single new feature has been included into the 2.x version tree since 3.0 development started. New features go into newer versions, not the old ones - it's as simple as that.

**Comment by pijulius** [comment]
Hi Guys,

Got it and thanks for the update, exactly what I wanted to know!

Regards,
Julius
