### ISSUE TITLE
Router not setting directory, class or method on time.

### ISSUE THREAD

**Issue by xeno** [bcit-ci/CodeIgniter#3752]
When using a routing directory in index.php, the routing directory is not being set before _set_routing() is called [in the Router.php constructor method]. The result is a 404 on the default controller and full routes required (including the directory name) in routes.php.

**Comment by LouisMilotte** [comment]
I have received this error if I forget to follow the naming standards. Assuming this is for CI version 3; is your default controller named like so: Controller_name.php? If not, what is the setting for your default controller and what is the name of your default controller?
