### ISSUE TITLE
Load library with one parameter for the constructor

### ISSUE THREAD

**Issue by JCSama** [bcit-ci/CodeIgniter#3760]
Hi guys,
I can't load a library that needs only one parameter for the constructor, like following :
```php
$this->load->library('SomeLibrary', 'filename');
```
So I did take a look at the `system/core/Loader.php` for C.I version 3.0, and I saw this at the line 214 :
```php
if ($params !== NULL && ! is_array($params)){
     $params = NULL;
}
```
And I don't understand why this condition exists ?

**Comment by narfbg** [comment]
Ask your questions on the forums, we only accept bug reports here.
