### ISSUE TITLE
Feature Request: Select fields as associative array

### ISSUE THREAD

**Issue by marcossffilho** [bcit-ci/CodeIgniter#3764]
If instead of using this:

```php
$this->db->select(array(
  'field1 AS foo',
  'field2 AS bar',
  'field3 AS baz'
));
```

We can use:

```php
$this->db->select(array(
  'field1' => 'foo',
  'field2' => 'bar',
  'field3' => 'baz'
));
```

And get the same result?

**Comment by ZombieProtectionAgency** [comment]
I don't think you are supposed to make feature requests on GitHub. This would be better posted to the [Development forums](http://forum.codeigniter.com/forum-6.html) in either the [CI 3.x](http://forum.codeigniter.com/forum-17.html) or the [CI 4](http://forum.codeigniter.com/forum-27.html) subforums.

I don't know if there is even a reasonable/consistent way to determine if an array is associative or not which would make it a little hard to do both (i think?)

**Comment by marcossffilho** [comment]
@ZombieProtectionAgency Sorry, I don't even know that already exists a forum to CI 4 :stuck_out_tongue_winking_eye:.

> I don't know if there is even a reasonable/consistent way to determine if an array is associative or not which would make it a little hard to do both (i think?)

About this, If it's gonna to implement the way I put in the example (the key is the field/column), just check if the key isn't numeric. If somehow the field/column is numeric, the developer will need to use the current way (example: "0 as field")

**Comment by darkwhispering** [comment]
According to the documentation select() expect a string, not an array of any form. http://www.codeigniter.com/userguide3/database/query_builder.html#CI_DB_query_builder::select

**Comment by narfbg** [comment]
What @darkwhispering said.

And what @ZombieProtectionAgency said too ... post on the forums. If we have everybody opening issues here because they thought of something, we'd have thousands of issues.
