### ISSUE TITLE
Config option to force upload file regarding application/cdfv2-corrupt

### ISSUE THREAD

**Issue by kabeza** [bcit-ci/CodeIgniter#3765]
Hi
I've started a forum thread regarding uploading files problem
You can read it here:

http://forum.codeigniter.com/thread-61406.html

When I upload an excel file (generated from other app) in my CI app, I get the "The filetype you are attempting to upload is not allowed.", even If I have the detect_mime set to false and allowing all kind of files

```php
$config['allowed_types'] = '';
$config['detect_mime'] = false;
```

When I upload a new excel file created from office/libreoffice, all works fine. Now that I'm aware of the cause (maybe bad file header from excel spreadsheet) I'd like to have an option to set in $config array so the upload library uploads file anyway, without throwing the wrong error "filetype not allowed".

```php
$config["force_upload"] = 1;
```

**Comment by narfbg** [comment]
allowed_types must be set to '*', not an empty string ...

**Comment by kabeza** [comment]
@narfbg That is not the problem. I can set allowed_types = '*' (which would not be a good choice)

The problem I was trying to reference is that I get "The filetype you are attempting to upload is not allowed." when I upload an excel file and get the [file_type] => application/cdfv2-corrupt in the $this->upload->data() array
I'd need to do something so CI uploads it anyway and to be able to restrict allowed_types too

Thanks

**Comment by narfbg** [comment]
So you want to ignore the type mismatch error and allow the upload anyway ... That is EXACTLY the same as allowing all types.

Please post on the forums if you need help with this.

**Comment by kabeza** [comment]
**Is it a type mismatch?** Because the file IS an excel spreadsheet. Excel/Libreoffice open the file correctly, but the CI->upload returns [file_type] => application/cdfv2-corrupt and throws (incorrectly) "The filetype you are attempting to upload is not allowed", **just because it could not match some mime?**

I've solved the problem temporarily by opening each file and saving as xlsx again, but I thought I'd be able to force the upload anyway, without setting '*' to allowed_types

PS: posted in forum

Thanks again
