### ISSUE TITLE
[Insight] Code should not be duplicated - in system/database/…/mssql/mssql_driver.php, line 313

### ISSUE THREAD

**Issue by Tjoosten** [bcit-ci/CodeIgniter#3766]
**[in system/database/drivers/mssql/mssql_driver.php, line 313](https://github.com/bcit-ci/CodeIgniter/blob/c0b2ae29b8a4c48c6adde72bc3f66ad3780246ec/system/database/drivers/mssql/mssql_driver.php#L313)**

> The next 57 lines appear both in `system/database/drivers/mssql/mssql_driver.php:313` and `system/database/drivers/pdo/subdrivers/pdo_dblib_driver.php:161`.

```php
	{
		$sql = 'SELECT '.$this->escape_identifiers('name')
			.' FROM '.$this->escape_identifiers('sysobjects')
			.' WHERE '.$this->escape_identifiers('type')." = 'U'";

		if ($prefix_limit !== FALSE && $this->dbprefix !== '')
		{
			$sql .= ' AND '.$this->escape_identifiers('name')." LIKE '".$this->escape_like_str($this->dbprefix)."%' "
				.sprintf($this->_like_escape_str, $this->_like_escape_chr);
		}

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/c2937cd8-0858-40ed-b4ac-4b48d7aa867b/analyses/1)_

**Comment by ZombieProtectionAgency** [comment]
It looks like a lot more than 57 lines are duplicated between the two. [Online Diff](https://www.diffchecker.com/e8w74uvj)

**Comment by Tjoosten** [comment]
Hmm it should be romoved and fixed in my opinion!

**Comment by narfbg** [comment]
Sorry to burst your bubble, but SensioLabs Insight isn't something we measure by. Please raise your opinions on the [forums](http://forum.codeigniter.com/) ... if you continue to do it here, we'll just close most of them and it will become annoying for everybody.

**Comment by Tjoosten** [comment]
Srry @narfbg
