### ISSUE TITLE
Array helper element() with non-array

### ISSUE THREAD

**Issue by Dentxinho** [bcit-ci/CodeIgniter#3767]
On 2.x I used to call `element('item', $thing)` without bothering if `$thing` was an array, because `element` did its magic. This way I could do 
```php
element('item3', element('item2', element('item1', $thing)));
```

Now on 3.x, this behaviour changed to simply call `array_key_exists` and it was a BC break for me.
I suggest doing this instead (array_helper.php#L67):
```php
return (is_array($array) && array_key_exists($item, $array)) ? $array[$item] : $default;
```
I can open a PR if you agree.

If you answer 'no, you should ensure you passed an array', then I suggest the method signature being `element($item, array $array, $default = NULL)` and BC break like a boss :)

**Comment by ZombieProtectionAgency** [comment]
It isn't completely related to this issue but it looks like there was some discussion about this function in one of the commits that changed it (https://github.com/bcit-ci/CodeIgniter/commit/4d1a214836fc16bbecd5afd11060a56bc2859b7d).

If you are going to update it now you could also add an isset check to speed it up a little, based on [a suggestion on php.net](http://php.net/manual/en/function.array-key-exists.php#107786).

 something like...
`return (is_array($array) && (isset($array[$item]) || array_key_exists($item, $array))) ? $array[$item] : $default;`

**Comment by Dentxinho** [comment]
You are right! I totally forgot about that php.net comment.

**Comment by Dentxinho** [comment]
BC Breaking like a boss \o

**Comment by narfbg** [comment]
... because people apparently *do try* to do everything the wrong way.

Honestly, this helper shouldn't have existed in the first place and you shouldn't be using it.
