### ISSUE TITLE
Form Validation Field Name Translation in 3.0

### ISSUE THREAD

**Issue by splodgeco** [bcit-ci/CodeIgniter#3771]
In version 3, the language library and form_validation class were changed to prefix validation errors with "form_validation_".  The _translate_fieldname function of the form_validation class tries to check for user entered custom language fields for the field name and use that instead of the fieldname.  However this function adds the "form_validation_" and checks for that in the language line.  This seems like a bug to me as this language line is a user entered human readable field name and not the error message.

Does this function need to add the additional "form_validation_" for language line?

**Comment by narfbg** [comment]
I don't understand what you mean and I don't see anything wrong with the logic in `_translate_fieldname()` ... Please give an example of a case that shows what you think is wrong.

**Comment by splodgeco** [comment]
Please see the [documentation](http://www.codeigniter.com/userguide3/libraries/form_validation.html#translating-field-names) for form validation regarding the translation of field name.  This indicates that a human readable (referenced in a language file) name may be given for field names.

When you use this functionality and the rule you are testing with fails, the **_translate_fieldname** function checks for the use of a custom language line.  It does 2 checks, 1 with **form_validation_** prefixed to the line and 1 where it is not (deprecated part).  If the line from the language file was returned then that value will be used as the field name.  If the **form_validation_** prefix was not found in the language line then this is added to the error log.

It seems like a bug to me because I am supplying the language line to use from my own language file for the **field name**, not the error message.  As such does the prefix **form_validation_** need to be added?  This would indicate that anybody trying to use their own language files for **field names** would need to prefix them with **form_validation_** and to me this seems a little odd.

Example:
Language file test_lang.php
```php
$lang['head_field_a'] = 'Your full name';
```
Controller with some form validation:
```php
$this->lang->load('test');
$this->load->library('form_validation');

// Field a is some post data that is required
$this->form_validation->set_rules('field_a', 'lang:head_field_a', 'trim|required');

if ($this->form_validation->run() === TRUE)
{
    // Process the form data etc..
}
```

In the above example I am using my own language file for a field name so the end user has a better understanding of what filed the error is in relation to.  If the post data received did not have any data for the **field_a** field then the required validation rule would fail.  As a custom language line was used for the field name, the **_translate_fieldname** function would prefix my custom language line with **form_validation_** and try to find that (form_validation_head_field_a).  This would produce an error being logged as this line was not found.  My custom line would still be used as it's picked up by the deprecated part of the check (the one without the prefix added).

I'm saying that the **form_validation_** prefix in the **_translate_fieldname** function does not make any sense.  I understand the need for the prefix to be added for error messages so they do not conflict with our own language files etc.  However the field name is not the error message and as such does not need the prefix added.  I might be using this same language line throughout my project and the prefix of **form_validation_** just doesn't make sense if I want to use this language line in one or more of my views.

**Comment by narfbg** [comment]
Agreed, although it still took me some time to understand what you mean ... it could've been a lot simpler. :)

**Comment by splodgeco** [comment]
Your right, it could have been and thanks for fixing.
