### ISSUE TITLE
Session overwrite native sessions?

### ISSUE THREAD

**Issue by ikarius6** [bcit-ci/CodeIgniter#3776]
Hi there, I've working on the new CI 3.0.0 and I noticed than my controller than check the upload progress stop working, I use a view like the next:

```php
<form action="<?=site_url("picture/upload")?>" method="post" enctype="multipart/form-data">
	<?=form_hidden($this->security->get_csrf_token_name(), $this->security->get_csrf_hash())?>
	<input class="id_progress" type="hidden" name="<?php echo ini_get("session.upload_progress.name"); ?>" value="<?=(mt_rand()*100+1);?>">
	<input type="file" name="src">
	<input type="submit" value="Enviar"/>
</form>
```

And in my controller there is a common upload controller, but after send the form I start an interval with ajax to my method:
```php
function progress( $id_progress = 0 ){
	@session_start();
	$id_progress+=0;
	$key = ini_get("session.upload_progress.prefix") . $id_progress;
	if (!empty($_SESSION[$key])) {
		$current = $_SESSION[$key]["bytes_processed"];
		$total = $_SESSION[$key]["content_length"];
		echo $current < $total ? ceil($current / $total * 100) : 100;
	}
	else {
		echo 0;
	}
}
```

In CI 2.2 it worked great, I get the value of the upload progress like the examples (http://php.net/manual/en/session.upload-progress.php), but since I updated to CI 3.0 it stop working, I think that the new session library is overwritten the session.upload_progress of PHP.

Suggestions?

**Comment by avenirer** [comment]
Yes. Use forums.
