### ISSUE TITLE
ci2.2.2 pdo error

### ISSUE THREAD

**Issue by smalleyes** [bcit-ci/CodeIgniter#3780]
in models, function look like that,
function get_last_ten()
    {
    	$query = $this->db->query("SELECT * FROM `test` limit 30");
    	var_dump($query);
//     	echo $this->db->last_query();
    	var_dump($query->result_array());
    }

can't return true result!

var_dump() result:
object(CI_DB_pdo_result)#18 (8) { ["num_rows"]=> int(2) ["conn_id"]=> object(PDO)#14 (0) { } ["result_id"]=> object(PDOStatement)#17 (1) { ["queryString"]=> string(29) "SELECT * FROM `test` limit 30" } ["result_array"]=> array(0) { } ["result_object"]=> array(0) { } ["custom_result_object"]=> array(0) { } ["current_row"]=> int(0) ["row_data"]=> NULL }

Array ( )

**Comment by narfbg** [comment]
Please post your questions on the [forums](http://forum.codeigniter.com/), not here - here we only accept bug reports.

Also, PDO in CI2 is broken, don't use it.
