### ISSUE TITLE
Add SSL Support to MySQLi Driver

### ISSUE THREAD

**Issue by timnolte** [bcit-ci/CodeIgniter#3781]
There has been a hack out there for years to enable this. Really should be put into core. Given the security issues that have risen over the past couple of years there really is no excuse for not using encrypted communications between systems internally. I will fork and submit a proper pull request for this feature once I get it working and tested. You can find a snippet of that core hack on this pastbin (http://pastebin.com/ekVJMdRG). I'm working on something a bit more complete.

**Comment by timnolte** [comment]
So I don't see any comments on this subject. So it would seem no one cares about it? I guess I do have an additional question and that's concern CI 2.2 and if this feature would even be back-ported to 2.2 or not. I've got all the changes working in our 2.2 environment but now that I'm looking through things the current `develop` branch is pretty much 3.x. There are a lot of changes in the DB drivers in 3.x that will require me to change how I've implemented the SSL changes which I'm currently unable to test at the moment, as I don't have a 3.x install anywhere. I guess I'd like to at the very least get some comments and perhaps this being tagged as a feature/enhancement and targeted for a specific milestone.

**Comment by mwhitneysdsu** [comment]
Generally, with this repo you can usually be assured that if no one cared about it, your issue would have been closed.

CI 2.x end of life was [announced for this coming October](http://forum.codeigniter.com/thread-61357.html), so only security fixes will be added. I have a feeling they would consider SSL support to be a feature addition rather than a fix. That said, if they didn't think it was worth having for CI3 or 4, they probably would have closed this in April.

**Comment by timnolte** [comment]
@mwhitneysdsu good to know. Thanks for chiming in. I'm fixing my 2.x code to follow the 3.x convention and changes, just to make it easier to port to the 3.x code base. I'll work on getting a 3.x install up and running for development testing. I know I'll also need to get up to speed on the current setup for unit testing as well. We've been using an older, yet still loosely maintained, version of CIUnit for our application unit testing but I haven't tracked the CI core unit testing work.
