### ISSUE TITLE
CI 2.2 - form_validation required bugs 

### ISSUE THREAD

**Issue by aubinlorieux** [bcit-ci/CodeIgniter#3782]
There is a bug in the `form_validation`library in CI 2.2.

When you validate a data wich is an integer with the value 0 the `required`method fails.

Line 337 

```php
if (isset($_POST[$field]) AND $_POST[$field] != "") // return false with 0 true with "0"
```

We should have to test the type too
```php
if (isset($_POST[$field]) AND $_POST[$field] !== "") // return true with 0 return true with "0"
```

**Comment by narfbg** [comment]
The 2.x version tree now only gets security fixes, so this one is a "won't fix", sorry.
