### ISSUE TITLE
Deprecated method safe_mode in CodeIgniter 2.2.2

### ISSUE THREAD

**Issue by Egorby** [bcit-ci/CodeIgniter#3789]
Path: `system/core/CodeIgniter.php`
Line: 106-109

if (function_exists("set_time_limit") == TRUE AND @ini_get("safe_mode") == 0)
	{
		@set_time_limit(300);
	}

Method safe_mode already deleted from PHP -> `always return 0`
CLI not working (max_execution_time always `300`!!!)

**Comment by narfbg** [comment]
Sorry, only security fixes go into CI 2.x now.

**Comment by Egorby** [comment]
Ok.
