### ISSUE TITLE
3 vs 2

### ISSUE THREAD

**Issue by WilliamHua** [bcit-ci/CodeIgniter#3795]
Is there a page where we can see differences in features between CI 3 and CI 2? Will migrating from CI 2 to CI 3 break things?

**Comment by kakysha** [comment]
http://www.codeigniter.com/userguide3/installation/upgrading.html

**Comment by narfbg** [comment]
We have a forum board for you to ask questions at, don't do it here.

http://forum.codeigniter.com/
