### ISSUE TITLE
xls file is not uploading on the server

### ISSUE THREAD

**Issue by shubham0503** [bcit-ci/CodeIgniter#3798]
i am using ci 2.0.0....there is a problem is occurring that is the file is not entering in the server soo plz help me..... i m trying it from 5 hours...

**Comment by avenirer** [comment]
use forums... Also, 2.0??? Use forums.

**Comment by nuclearpengy** [comment]
Try taking a look at: https://ellislab.com/codeigniter/user-guide/libraries/file_uploading.html

**Comment by narfbg** [comment]
Ask your question on the [forums](http://forum.codeigniter.com). We only accept bug reports here.
