### ISSUE TITLE
Error during execution of Query (Compilation Failed)

### ISSUE THREAD

**Issue by arisdario** [bcit-ci/CodeIgniter#3805]
I have executed a query that seem to bee to large.
The issue is that i have created an array of 5k rows, and it is returning me only the id of that row:
Example:
From a foreach loop im asking the database if the product_id exists and it is returning the id or false.
```
if($exist_real->num_rows() > 0 ){
	return $exist_real->row()->id;
}else{
	return false;
}
```

so inside of that loop im crating the array that is passed to the next task that get data from database with a condition `where_in`:

```
$this->db->select('*')->from('products')->where_in('product_id', $ids)->get();
```
and from here the next error: i would like to know what is the large expression will support the query builder or what method can i use to get it properly working.

```
A PHP Error was encountered
Severity: Warning
Message: preg_match(): Compilation failed: regular expression is too large at offset 44123
Filename: database/DB_query_builder.php
Line Number: 2336
Backtrace:
File: /path/to/codeigniter/application/controllers/Products.php
Line: 435
Function: get
```

**Comment by narfbg** [comment]
Please post your questions on the [forums](http://forum.codeigniter.com).

We only accept bug reports here and this is deffinately not a bug ...

**Comment by arisdario** [comment]
Ok, no problem, i already posted on stackoverflow to see if there is another way to get properly working the function 'where_in' without adding PCRE library backtracking limit options to php.ini ;

Thanks
