### ISSUE TITLE
session expiration set to 0 is not working for redis as expect

### ISSUE THREAD

**Issue by netweaver** [bcit-ci/CodeIgniter#3811]
session driver: redis
expiration set to 0 means session never expire until cookie is gone
but it the expiration  equals to  gc_maxlifetime(php.ini) when it is set to 0 in config.php 
it caused by 
 code below in file "system/library/session/session.php "
if (empty($expiration))
{
			$params['expiration'] = (int) ini_get('session.gc_maxlifetime');
}

plz check

**Comment by narfbg** [comment]
It works exactly as expected.

**Comment by netweaver** [comment]
plz explain this behavior.
i set sess_expiration to 0 (use redis) , because i wan't to let session expired only when cookie is gone (browser close or cookie expired,whatever)
but it affected by gc_maxlifetime (default 1440 secs)
i thought that when i set sess_expiration to 0 ,session never expired in redis (also noticed that redis does't need external gc )  , but now i have to set gc_maxlifetime  big enough to avoid session keys of redis expired.

it think it should be 
if (empty($expiration))
{
      if(   driver is not redis || $expiration!==0)
     {
           $params['expiration'] = (int) ini_get('session.gc_maxlifetime');
     }
}
else
....

**Comment by netweaver** [comment]
the point is  redis does not need external session gc.  it's expiration should not be affected by gc_lifttime

**Comment by narfbg** [comment]
It doesn't need a separate GC mechanism because you can directly set the expiry time, but that doesn't mean that it should hold a session forever - it *must* expire at some point, and that point is gc_maxlifetime.

**Comment by netweaver** [comment]
mmm...i think i got your point.  thank you!
