### ISSUE TITLE
DB num_rows now always returning null

### ISSUE THREAD

**Issue by dannyreil** [bcit-ci/CodeIgniter#3812]
When querying the database (using mysqli) nuw_rows now always returns null, even when there are results found using result_array()

**Comment by narfbg** [comment]
When is "now"?
And what is "num_rows"? A property or a method?

**Comment by dannyreil** [comment]
Previous when running queries on the database in codeigniter 2.2 using for example $this->db->get('table'); This would return an object with the method num_rows() which would contain an int value of the number of rows returned from the DB query, as of codeigniter 3 the value of this is now always null, even when the DB query is successful

**Comment by narfbg** [comment]
There's a `num_rows()` method that you should use.

The property with that name has never been a part of the official API and the fact that it has worked for you in some case is rather a coincidence.

**Comment by Lvkz** [comment]
I have the same issue... According to the documentation of CI 3.0: 

<b>"If you run queries that might not produce a result, you are encouraged to test the result first:"</b>
<code>if ($query->num_rows() > 0) { </code>
<code>//Run query->result  or query->row() according to your needs.</code>
<code>}</code>

But if it always return null, how are we gonna check if the query returned values or not? :/

**Comment by mwhitneysdsu** [comment]
@Lvkz: Note what @narfbg said as well as the code that you quoted: use the `num_rows()` method, not the `num_rows` property.

**Comment by Lvkz** [comment]
Argh!!! Got it now!!! Method, not property! Thank you very much!! :D
