### ISSUE TITLE
blank set_value() return default value

### ISSUE THREAD

**Issue by rierei** [bcit-ci/CodeIgniter#3816]
On set empty a input with set_value(), the input value is set to $default.

**Comment by rierei** [comment]
Codeigniter Forum discussion: http://forum.codeigniter.com/thread-1689-post-316473.html

**Comment by sparky672** [comment]
I manually applied this change to my source and it made absolutely no difference.  The problem continues.

**Comment by narfbg** [comment]
Then you don't have the same problem.

**Comment by sparky672** [comment]
I have the exact same problem.  When the form repopulates, the default value is used, but only if I blank out the field.  Described in greater detail, and referred here...

http://forum.codeigniter.com/thread-61600-post-317554.html#pid317554

**Comment by sparky672** [comment]
Have not heard anything... should I open this as new issue?

**Comment by narfbg** [comment]
No, it's not designed to work like you want it to.

**Comment by rierei** [comment]
The documentation says "The Form Validation class supports the use of arrays of field names."

I tested the examples in accordance with the documentation and they have the same problem.

http://www.codeigniter.com/user_guide/libraries/form_validation.html

In version 2.2.2 it did not happen, what is the reason for this be happening?

**Comment by sparky672** [comment]
> No, it's not designed to work like you want it to.

Then it's been changed from version 2.  Just uploaded my test page to a CI v 2 installation and it's working perfectly fine.

I simply want it to work the same whether the input is named `foo` or `foo[1]`, which is the same as it did in CI 2.

**Comment by narfbg** [comment]
@rierei That doesn't necessarily mean that it supports @sparky672's case.

@sparky672 Would it really make sense to you if 'foo' and 'foo[1]' were the same thing? They aren't ... In fact, it was a bug that they were the same thing to CI2.

'foo[bar]' and 'foo[]' should work fine, but 'foo[1]' is ... Let's just say that there's no way to make it work properly without breaking something else.

**Comment by ivantcholakov** [comment]
Just FYI: I copied the method
protected function _reduce_array($array, $keys, $i = 0)
from CodeIgniter 2.2 into CI3, and the "foo[1]" case is back again.

**Comment by ivantcholakov** [comment]
Without thinking too much (there is no time) I copy/pasted the method form CI2.2
protected function _reduce_array($array, $keys, $i = 0)
in the same place in CI3 and "foo[1]" case started working for me.

**Comment by sparky672** [comment]
>  Would it really make sense to you if 'foo' and 'foo[1]' were the same thing?

Of course not, and I never said these two different names were the same thing.
