### ISSUE TITLE
Mountain timezone offset in documentation is incorrect in Date Helper documentation

### ISSUE THREAD

**Issue by rogerjaffe** [bcit-ci/CodeIgniter#3818]
In the Timezone reference in the Date Helper documentation (http://www.codeigniter.com/user_guide/helpers/date_helper.html) the Mountain Timezone is listed as (UTC - 11:00) and it should be (UTC - 9:00).  

EDIT: Yes, mwhitneysdsu is correct MST is UTC - 7 -- I got my numbers confused.

**Comment by narfbg** [comment]
Strange enough, it is listed against UM7, for which the helper returns -7, not -9 or -11 ... so we have at least two problems here.

**Comment by mwhitneysdsu** [comment]
Mountain Standard Time is UTC - 7, MDT is UTC - 6.
UTC - 9 is Alaska Standard Time

http://aa.usno.navy.mil/faq/docs/us_tzones.php
