### ISSUE TITLE
_get_lock wrongly handles number of retries in Redis and Memcached session drivers

### ISSUE THREAD

**Issue by kraszdan** [bcit-ci/CodeIgniter#3823]
Both Redis and Memcached session drivers have bug in handling number of retries to obtain lock.

E.g. [Session_redis_driver.php at line 341](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Session/drivers/Session_redis_driver.php#L341)

```php
		}
		while ($attempt++ < 30);
		if ($attempt === 30)
		{
			log_message('error', 'Session: Unable to obtain lock for '.$this->_key_prefix.$session_id.' after 30 attempts, aborting.');
			return FALSE;
		}
```

Two error cases:
- Do-While loop ends after 29 attemps but post-incrementation increases the value to 30 - lock obatined, function returns FALSE
- Do-While loop ends after 30 attemps but post-incrementation increases the value to 31 - lock not obatined, function returns TRUE

**Comment by narfbg** [comment]
Your first case is handled by a `break` inside the loop and the second one is simply impossible, for reasons evident even in the isolated snippet that you've shown.

**Comment by kraszdan** [comment]
Sorry for incorrect description, but in my opinion problem still remains.

Let say, we're analysing situation when $attempt === 30 and this is last loop execution (possible, because of post-incrementation in while condition).

If we obtained the lock, we're breaking the loop, just like you said. $attempt is still 30 and this fultills next if statement, which is wrong.

Also in situation when lock cannot be obtained, $attempt is increased to value 31 after checking while condidtion. Loop ends, but next if statement is not fulfilled (31 !== 30).

**Comment by narfbg** [comment]
Still an "incorrect" description (as you're explaining the wrong problem), but my bad as well ... you are indeed right.

The key here is "post-incrementation", by which assumed you meant `do ... while` - I didn't realize you were using it as a specific term. Will commit the fix right away, thanks.
