### ISSUE TITLE
Can the Cart library / class not be improved instead of being deprecated ?

### ISSUE THREAD

**Issue by DevotionGeo** [bcit-ci/CodeIgniter#3827]
@narfbg , @rickellis, @derekjones  It will need too much work, but I think it will be great if the Cart Class is improved instead of ditching it. The framework should not start ditching great FEATURES because they are hard to maintain / improve.
For example if its being deprecated what alternative is being given ?

**Comment by narfbg** [comment]
Please post such topics on the [forums](http://forum.codeigniter.com/), not here.

Also, Rick Ellis and Derek Jones are no longer associated with the project.
