### ISSUE TITLE
Documentation could do with updating for version 2

### ISSUE THREAD

**Issue by exussum12** [bcit-ci/CodeIgniter#3843]
http://www.codeigniter.com/userguide2/libraries/form_validation.html

has the following (in the prepping data section)

$this->form_validation->set_rules('password', 'Password', 'trim|required|matches[passconf]|md5');
$this->form_validation->set_rules('passconf', 'Password Confirmation', 'trim|required');

This should be similar to the new docs 
http://www.codeigniter.com/userguide3/libraries/form_validation.html

$this->form_validation->set_rules('password', 'Password', 'trim|required|md5');
$this->form_validation->set_rules('passconf', 'Password Confirmation', 'trim|required|matches[password]');

in order to correctly work when trimming. The first compares the trimmed password to a non trimmed passwordconf

example

"password " matches "password"

but

"password " does not match "password "

I can see there is a doc section for CI3 but that doesnt seem to exist for CI2 so can not send a pull request

**Comment by narfbg** [comment]
edcc80714f87a3a793f79cc82e1148f75a2478bb
