### ISSUE TITLE
Create a JSON-RPC library

### ISSUE THREAD

**Issue by luizzz** [bcit-ci/CodeIgniter#3845]
... or a option to convert all xmlrpc data to json, like this:
```php
$this->xmlrpc->send_error_message('404','Not Found','json'); /* with 'json' explicited, outputs json data */
//or...
$this->xmlrpc->send_response($message,'json'); /* with 'json' explicited, outputs json data */
// ;) 
```

**Comment by narfbg** [comment]
No ...

And please at least wait for some feedback on your [forum posts](http://forum.codeigniter.com/thread-61708.html?highlight=json-rpc) before coming here with the same request.

**Comment by luizzz** [comment]
sorry, i was confused. thanks!
