### ISSUE TITLE
mysqli custom_result_object is ignored overloading function 

### ISSUE THREAD

**Issue by gahea** [bcit-ci/CodeIgniter#3848]
system/database/driver/mysqli_result.php
```php

	/**
	 * Result - object
	 *
	 * Returns the result set as an object
	 *
	 * @param	string	$class_name
	 * @return	object
	 */
	protected function _fetch_object($class_name = 'stdClass')
	{
		return $this->result_id->fetch_object($class_name);
	}

```

mysqli_result::fetch_object is ignoring __set function. 
http://php.net/manual/en/language.oop5.overloading.php

i think it is not people's expectations.

**Comment by narfbg** [comment]
And somebody else may think otherwise ... We can't make changes based on that.

**Comment by tibonilab** [comment]
__set() overloading works only if property is not declared. Otherwise there is property name collisions, i guess.

**Comment by narfbg** [comment]
... or if they're declared as private/protected, but `fetch_object()` probably ignores it in these cases as well. It sets values before calling the constructor is called, which possibly means that it can't call `__set()` at all because the object is not yet initialized.

**Comment by tibonilab** [comment]
private/protected declared in the class are still visible in the scope unless the class is an extension of another class with those properties private.
In all other cases __set() won't be called, as specified here http://php.net/manual/en/language.oop5.overloading.php#language.oop5.overloading

**Comment by narfbg** [comment]
Which means that unless the object you're assigning to is a child of `mysqli_result`, those properties won't be visible to `fetch_object()`.

But either way that doesn't matter.
