### ISSUE TITLE
CSRF problem while using cookie_secure and coockie_httponly

### ISSUE THREAD

**Issue by jellepals** [bcit-ci/CodeIgniter#3855]
When i using this options in the config file:

$config['cookie_secure']	= TRUE;
$config['cookie_httponly'] = TRUE;

The CSRF does not work anymore when using https. It gives the message: "The action you have requested is not allowed". When turning it back to false the CSRF does work again. Without CSRF the function works well for the coockies. 

Is there an solution for this (using Codeigniter 2)? Thanks!

**Comment by mwhitneysdsu** [comment]
'cookie_httponly' is not used by CodeIgniter 2 (unless you've modified/overridden the Security->csrf_set_cookie() method).

With 'cookie_secure' set, the most obvious possibility is that the method isn't detecting that HTTPS is enabled properly.

Either way, until an issue is actually found, this discussion is probably better suited to the forums: http://forum.codeigniter.com/

**Comment by narfbg** [comment]
Indeed, we only accept bug reports here and you should direct all your other questions to the [forums](http://forum.codeigniter.com/).

Also, CI2 now only receives security fixes, so even if this was a bug, it's not a vulnerability and therefore wouldn't get fixed.
