### ISSUE TITLE
redirect() stops phpunit testing

### ISSUE THREAD

**Issue by kenjis** [bcit-ci/CodeIgniter#3857]
This is common problem when you run application (probably controller) tests.

`redirect()` has `exit` and it ends php process.
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/helpers/url_helper.php#L567

I hope CodeIgniter cares for it. Is there any plan to solve this problem?

**Comment by narfbg** [comment]
How do you propose to solve this "problem"?

**Comment by kenjis** [comment]
How about this?

1. remove all `exit` and add throwing new Exception, eg, `ExitException`
2. catch the Exception at the end of `index.php`

**Comment by aanbar** [comment]
I think Controllers should be tested using WebGuy since it's more about user experience, this would still allow you to check the database or the output including redirects.

 If you still insist on using Unit Test for this, You can override the function for 'testing' environment by creating MY_url_helper file & make the new function available if the environment is set to 'testing'

**Comment by kenjis** [comment]
Do you think CodeIgniter should oppose unit testing for controllers?

> If you still insist on using Unit Test for this, You can override the function for 'testing' environment by creating MY_url_helper file & make the new function available if the environment is set to 'testing' 

I use MY_url_helper now: https://github.com/kenjis/ci-phpunit-test/blob/master/application/helpers/MY_url_helper.php#L89

**Comment by narfbg** [comment]
I guess that could work, but I don't really like it ... Tests should be built around the framework code, not the other way around.

**Comment by kenjis** [comment]
@narfbg Are you saying about `ExitException`?
If so, do you mean you don't like to remove `exit`?

**Comment by narfbg** [comment]
Yes.

**Comment by kenjis** [comment]
If we don't remove `exit`, I think the only solution is to provide URL helper for testing.
Are there any other solutions?

Or CodeIgniter will not provide how to test controllers?

**Comment by narfbg** [comment]
Well, given that we still catching-up on testing the framework's own code, user-space testing hasn't really been given a serious thought. That being said, if you can come up with an appropriate mock - sure, we'll merge it.

**Comment by skunkbad** [comment]
Instead of redirecting, I like the idea of re-routing. I built that into my own framework. Sure, there are some cases when you need to do an actual redirect, but re-routing a request is nice too.

**Comment by kenjis** [comment]
At the moment, here is the our best practice for testing:
https://github.com/kenjis/ci-phpunit-test/blob/master/application/helpers/MY_url_helper.php

If you use this helper, you can catch `redirect()`.

**Comment by narfbg** [comment]
Keeping this open serves no purpose, so I'm closing it.

Again, if somebody could provide a useful mock - that's welcome. Although, every helper function declaration is wrapped inside a `function_exists()` check, so IMO that makes them easy enough to override locally in any testcase - just declare the function before CI does.
