### ISSUE TITLE
captcha_helper warning mt_rand() issue

### ISSUE THREAD

**Issue by renishar** [bcit-ci/CodeIgniter#3860]
I'm using new Codeigniter 3. Some times when loading a captcha_image using captcha_helper, the following warning occurred !
--------------------------------------------------------

A PHP Error was encountered

Severity: Warning

Message: mt_rand(): max(2) is smaller than min(6)

Filename: helpers/captcha_helper.php

Line Number: 144

Backtrace:

File: C:\wamp\www\project1\app\controllers\main.php
Line: 180
Function: create_captcha

File: C:\wamp\www\project1\index.php
Line: 292
Function: require_once

--------------------------------------------------------

When refreshing some times no error. ie. it occurred in a radom way.
Pls solve it.

I will not get this on CI 2 that i'm using for more than 3 years.

**Comment by aanbar** [comment]
Please post your captcha code here to make it possible to debug the issue.

**Comment by renishar** [comment]
public function viewCaptcha()
    {
        if (!$this->input->is_ajax_request())
        {
            //redirect(site_url(), 'refresh'); // commented for testing
        }
        $this->load->helper('captcha');
        $vals = array(
            'img_path'   => './assets/captcha/',
            'img_url'    => base_url().'/assets/captcha/',
            'img_width'  => 120,
            'img_height' => 40,
            'expiration' => 5
        );
        $cap = create_captcha($vals); // ci captcha for removing from captcha folder
        $this->session->set_userdata('cap_sess', $cap['word']);
        echo $cap['image'];
    }

**Comment by renishar** [comment]
when refreshing the captcha 10 times, this issue arises 3-4 times only....

**Comment by renishar** [comment]
Hi,

i'm using another captcha library 'antispam' along with ci captcha, because expiration not available in that library.

**Comment by renishar** [comment]
Hey.... i font the senario for the issue.
When i set 'img_width' belo 10 or 'img_height' below 5 the warning show.
pls chk with width and height to some smaller value (1px, 2px...)

**Comment by tlagard** [comment]
GitHub is for bugs. It is not a support forum.  Post this on http://forum.codeigniter.com

**Comment by narfbg** [comment]
Yes, for this to happen, you have to either have really, really small *width* and *height* values (which would make the captcha practically invisible) or a *width* value that's larger than *height* (which is completely illogical).

Neither is a valid use case.

**Comment by renishar** [comment]
Thanks, @narfbg 
That was the issue...

i use:

'img_width' => 1,
'img_height' => 1,

seems to be very small image.
