### ISSUE TITLE
CodeIgniter-2.1 - internationalization - Avoid segment url in the root

### ISSUE THREAD

**Issue by henry1778** [bcit-ci/CodeIgniter#3871]
https://github.com/bcit-ci/CodeIgniter/wiki/CodeIgniter-2.1-internationalization-i18n#special-uris

It's specified that: "The root URI (/) is by default a special URI.", but this library adds automatically the language segment if I call my root (ex: www.asdfgg.com becomes www.asdfgg.com/en/)

How can avoid this behavior?

**Comment by narfbg** [comment]
That is a third-party library and you should direct any questions about it to its author.
Also, we don't provide general support here - you're welcome if you have a valid bug to report, but you should ask your other questions on the [forums](http://forum.codeigniter.com/).
