### ISSUE TITLE
CI 3 won't compatible with passed in variable in non UTF-8 encoding.

### ISSUE THREAD

**Issue by vibbow** [bcit-ci/CodeIgniter#3873]
If a third-party website passed some parameter with non UTF-8 encoding (For example GBK), then CI 3 will filtered those parameter out. Even not give a chance to let developer manually convert the encoding.

**Comment by narfbg** [comment]
Be specific please ... this is way too broad.

**Comment by vibbow** [comment]
Hi,

We have a third party website need to push data to our website, and they are using GBK encoding to push data, not UTF8.

CI3 will clean all input parameter, and assume they are all UTF8 encoding. therefore it will break the passed in variable if are not UTF-8 encoding.

My temp solution is add a hook to convert those parameter to UTF8 at very begining, because I know where are they and what's their name.

But CI3 should have a better solution to let us convert input parameter encoding before clean the input parameter.

Regards

**Comment by narfbg** [comment]
All of this was implied ... I'll try putting it this way:

> CI doesn't "clean" the input automatically unless you tell it to, and when you do - it doesn't assume UTF-8, it assumes what you've configured as a charset.

Trying to prove that wrong would be specific. :)

**Comment by vibbow** [comment]
Hi,

Following is the stack trace I get:

system/core/Input.php
  function __construct() -> calling $this->_sanitize_globals()  (line 154)
  function _sanitize_globals() -> calling $this->_clean_input_data($val); (line 616)
  function _clean_input_data -> calling clean_string($str) (line 695)

system/core/Utf8.php
  function clean_string($str) -> calling mb_convert_encoding (line 96)

And here↑ is the place which non utf-8 encoding parameter are broken.

**Comment by narfbg** [comment]
The 'pre_system' hook is called before all of that, and `CI_Utf8::clean_string()` will never be called unless you've set `$config['charset']` to UTF-8 (although that is the default value).
