### ISSUE TITLE
AR Numeric table field is not escaped

### ISSUE THREAD

**Issue by michail1982** [bcit-ci/CodeIgniter#3877]
I have numeric fields in table like "1","2","654" etc
```php
$this->db->where('tab_name.'.654, 'notImportant')->get('my_table tab_name');
```
in CI2 query was 
```sql
select * from `my_table` `tab_name` where `tab_name`.`654`= 'notImportant';
```
in CI3  query fail 
```sql
select * from `my_table` `tab_name` where `tab_name`.654= 'notImportant';
```

**Comment by aanbar** [comment]
Try sending it as a string & see if it fixes the issue

```
$this->db->where('tab_name.'.'654', 'notImportant')->get('my_table tab_name');
```

**Comment by michail1982** [comment]
in my case it`s a dynamic param, and i know how to fix it, but a gues AR must escape field names by default (that is a point of issue)

**Comment by narfbg** [comment]
Does the query fail or do you say "fail" because it doesn't quote it?

**Comment by michail1982** [comment]
Query fail im mysql with strict mode enabled

**Comment by narfbg** [comment]
Can't reproduce (and your example gives a syntax error).

**Comment by michail1982** [comment]
```php
$numField = 654;
$this->db->where('tab_name.'.$numField, 'notImportant')->get('my_table tab_name');
```

**Comment by narfbg** [comment]
$ cat application/controllers/Welcome.php 
    <?php
    class Welcome extends CI_Controller {
    
    	public function index()
    	{
    		$this->load->database();
    		$numField = 654;
    		$this->db->where('tabname.'.$numField, 'notImportant')->get('my_table tab_name');
    	}
    }
    $ php index.php welcome/index
    
    Database error: A Database Error Occurred
    
    	Error Number: 1146
    	Table 'citest.my_table' doesn't exist
    	SELECT *
    FROM `my_table` `tab_name`
    WHERE `tabname`.`654` = 'notImportant'
    	Filename: controllers/Welcome.php
    	Line Number: 8

... and you really don't need to concatenate it, you can just write `'tab_name.654'`.

**Comment by michail1982** [comment]
wrong table alias
```php
 $this->db->where('tabname.'.$numField, 'notImportant')->get('my_table tabname');
```

**Comment by narfbg** [comment]
OK. In that case it doesn't get quoted.

However, fixing this would break a lot of stuff, so ... don't use an alias or quote it yourself.
