### ISSUE TITLE
Transaction and DB connection

### ISSUE THREAD

**Issue by iijak** [bcit-ci/CodeIgniter#3878]
1) What happens if initiate the transaction on a closed connection and start to execute queries? Connect reinitialized on first query and each of query will be autocommitted?
2) What happens if the connection fails during the transaction? Connection reinitialized, previous queries rollback and each of next queries will be autocommitted?

I apologize for not being word-perfect in English.

**Comment by narfbg** [comment]
Please ask your questions on the [forums](http://forum.codeigniter.com/), we don't provide support here, unless you have a bug to report.
