### ISSUE TITLE
Website has been down in nigeria for over 4months & Object array to session data error

### ISSUE THREAD

**Issue by Kendysond** [bcit-ci/CodeIgniter#3879]
Hello,
please your website www.codeigniter.com has been down for over 4 months in my country nigeria, i've complained earlier but got no response , now i just downloaded the latest version via github and alot of things have changed , please can you kindly attach the html documentation for me so i can follow up  with the updates 
![screen shot 2015-05-26 at 19 44 54 1](https://cloud.githubusercontent.com/assets/5365813/7820431/57c28464-03e0-11e5-84b5-ae9b67856711.png)
thank you!!.
and i just tried to add an object array to my sessiondata like i did with the earlier version 3 but its returning an error

A PHP Error was encountered

Severity: Warning

Message: Illegal offset type

Filename: Session/Session.php

**Comment by daviskoko** [comment]
Hi Douglas,
am in Nigeria & the URL is working perfectly. I suggest you clear your
browser cache or simply check if your IP or ISP has not been blacklisted.
As for the session error, sharing a more detailed iterative steps you took
may help.
However, here is the URL for session handling:
https://ellislab.com/codeigniter/user-guide/libraries/sessions.html

**Comment by jim-parry** [comment]
Your two issues should be addressed on forum.codeigniter.com, not here - github is for development.
Our main website does not use any IP blacklists, so I suspect your IP or ISP has been blacklisted somewhere else along the way, as daviskoko suggested.
The URL he provided for session handling, however, is for CodeIgniter 2.2; the current one is http://www.codeigniter.com/user_guide/libraries/sessions.html
