### ISSUE TITLE
Return NULL from $this->lang->line() instead of FALSE

### ISSUE THREAD

**Issue by softwarespot** [bcit-ci/CodeIgniter#3885]
Inside Lang.php -> line(), the function returns FALSE when a translation isn't found, though wouldn't it seem more logical to return NULL considering the return type is of string and not as bool?

**Comment by narfbg** [comment]
The return type is mixed, not string. But regardless, answers to questions like this would be highly subjective and hardly ever productive ...

**Comment by softwarespot** [comment]
In that case perhaps the return type should be mixed and not string
