### ISSUE TITLE
Access CI instance from routes callback function

### ISSUE THREAD

**Issue by d4mn** [bcit-ci/CodeIgniter#3886]
I have a problem while using callbacks in routing. I need to access CI instance to load some contents and I can't do this. using load_class also doesn't help because these components aren't only libraries. I need cache driver and some models so it's not possible to access CI instance in route callback. Am I doing something wrong in my logic or does CI miss this future? 

I have seen in other frameworks and most of them allows to access components from routing. Any optional variants I have?

**Comment by narfbg** [comment]
Sorry, but we don't provide support via GitHub, unless you have a bug to report. Please ask your questions on the [forums](http://forum.codeigniter.com/) instead.
