### ISSUE TITLE
reset_validation() with rules in a config file

### ISSUE THREAD

**Issue by skegel13** [bcit-ci/CodeIgniter#3887]
When using the form_validation->reset_validation() method, the rules set from the config file are removed. This prevents any future validations using the config rules.

An easy fix is to extend the method and remove the part where it resets the config.

    public function reset_validation()
    {
        $this->_field_data = array();
        /* $this->_config_rules = array(); */  //REMOVE THIS
        $this->_error_array = array();
        $this->_error_messages = array();
        $this->error_string = '';
        return $this;
    }

Instead of this, is there a way to reload the config file on reset_validation() calls?

**Comment by narfbg** [comment]
Ask your questions on the [forums](http://forum.codeigniter.com/) please, we only accept bug reports here.
