### ISSUE TITLE
get_request_header: wrong case in nginx

### ISSUE THREAD

**Issue by vaprea** [bcit-ci/CodeIgniter#3890]
When i use the function get_request_header() in nginx keys appears to be in ucfirst mode.
So if i use 'auth' as a key, get_request_header does not match because the key expected is 'Auth'

**Comment by boonstoppel** [comment]
I am experiencing the same issue. Different casing for different server environments.

**Comment by gmcinalli** [comment]
I've submitted a PR (https://github.com/bcit-ci/CodeIgniter/pull/4097) to fix a bug that cause `$this->headers` not been set.
