### ISSUE TITLE
cannot connect with database in public network

### ISSUE THREAD

**Issue by Delostik** [bcit-ci/CodeIgniter#3891]
My site was working in a schools subnet, when I set hostname with a IP address (for example, xxx.xxx.xxx.xxx), a warning raises:

Severity: Warning
Message: mysqli::real_connect(): (HY000/1045): Access denied for user 'root'@'yyy.yyy.yyy.yyy' (using password: YES)

yyy.yyy.yyy.yyy is our subnet's public ip address.

**Comment by pfote** [comment]
thats a issue with your mysql config, not CI

**Comment by LouisMilotte** [comment]
This is a configuration in your database. not codeigniter.

**Comment by Delostik** [comment]
but i use the sample example and work well in ci 2.x

**Comment by narfbg** [comment]
Doesn't matter what you use, CI can't magically gain access to the database.
