### ISSUE TITLE
default_controller not working for Controllers in subfolder in version 3.0

### ISSUE THREAD

**Issue by boonstoppel** [bcit-ci/CodeIgniter#3894]
If a controller class is in a sub folder the "default_controller" defined in config/routes.php will not find it because it only checks for the file to be present in folder "controllers" without checking the sub folder.

**Comment by narfbg** [comment]
Yes, this is explained in the [upgrade instructions](http://www.codeigniter.com/userguide3/installation/upgrade_300.html#directories-and-default-controller-404-override).

Also: #2849

**Comment by boonstoppel** [comment]
Andrey,

there are 2 sides of this problem. If you want to set the default
controller for a sub directory with the url being a subdirectory too then
your new solution works fine:

eg:
domain.com/admin -> would nicely load "controllers/admin/index"


But if your system is designed to load a sub controller without a subfolder
in the url path, the new system is very limiting:

eg:
some-other-domain.com-> can NOT load "controllers/other-project/index"


Do you understand the difference?

**Comment by narfbg** [comment]
Oh, I understand the difference very well ... but you don't seem to understand how it works, which you should if you had read the content I linked.

**Comment by boonstoppel** [comment]
no offense Andrey. I read the 2 link you sent, one points to very short
upgrade instructions without any mention of the problem I just described
and the second link points to another bug entry where the discussion was
closed unresolved.

Could you point me to the documentation where this issue is properly
addressed?

Thanks!

**Comment by narfbg** [comment]
The "problem" you described is that you can't point 'default_controller' to a *directory/class* pair.

The upgrade instructions very clearly explain that this is not supported.
The discussion on #2849 explains *why* it's not supported and it wasn't closed as "unreasolved", it was closed (just as this one), because it's not a valid issue - an unsupported feature is not a bug.

**Comment by boonstoppel** [comment]
I added my use case to explain why this would be a nice feature to have. If
you codeigniter decided that this is not worth implementing then be it. My
vote is to make this possible because it's very limiting otherwise.

No need to get so defense on this. We all just want the best for
codeigniter don't we?

**Comment by narfbg** [comment]
So many arguments that you're provoking with that comment ... I wouldn't know where to begin. I understand that you're unhappy with this, but don't criticize my behavior. Having the best intentions does not mean you didn't call for it.

**Comment by boonstoppel** [comment]
please explain.
