### ISSUE TITLE
session driver load fail,when in php5.4n

### ISSUE THREAD

**Issue by 2188666** [bcit-ci/CodeIgniter#3899]
these days,our project update from codeigniter 2.x to 3.0, today,I come across a problem,when I use php5.4n,it can not initial the session library,my nginx/fastcgi always stop working,I trace the code ,found session library can not rightly load,but when I use php5.3n or php5.5n,it worked correctly.so ,how can solve the problem

in the session database driver ,I found every time when run to [$this->_row_exists = TRUE;return $result;],then nginx show errors,fastcgi stop work.

	public function read($session_id)
	{
		if ($this->_get_lock($session_id) !== FALSE)
		{

                        ......
			$this->_fingerprint = md5($result);
			$this->_row_exists = TRUE;
			return $result;
		}

		$this->_fingerprint = md5('');
		return '';
	}

**Comment by narfbg** [comment]
Please post your questions on the [forums](http://forum.codeigniter.com/), we only accept bug reports here.
