### ISSUE TITLE
Unable to access an error message corresponding to your field name Address.(Anonymous function)

### ISSUE THREAD

**Issue by jamieburchell** [bcit-ci/CodeIgniter#3908]
Above error is shown when a field has no value and no required rule:

```
$this->form_validation->set_rules('address', 'Address', [
	'trim',
	[
		'validate_address',
		function($value) {
			return $this->validate_address($value);
		}
	]
]);
```
...

```
public function validate_address($value)
{
	$this->form_validation->set_message(__FUNCTION__, 'The address field is required');
	return false;
}
```

Same error using this format:

```
$v->set_rules('address1', 'Address',
	[
		'trim',
		[
			'validate_address',
			function($value) {
				return false;
			}
		]
	],
	[
		'validate_address' => 'Never shown if field is empty and no required rule'
	]
);
```

**Comment by shefi** [comment]
Have you tried setting the rules like this?

```php
$this->form_validation->set_rules('address', 'Address', [
    'trim',
    'validate_address'
]);
```

**Comment by jamieburchell** [comment]
Sure, but my examples are also supposed to work according to the documentation.

**Comment by Nitin-Tec** [comment]
public function sendmail()
{
	$this->form_validation->set_rules('username','Username','required|alpha');
	$this->form_validation->set_rules('password','Password','required|max_length[12]');
	$this->form_validation->set_rules('firstname','Firstname','required|trim|alpha');
	$this->form_validation->set_rules('lastname','Lastname','required|trim|alpha');
	$this->form_validation->set_rules('email','Email','required|valid_email|is_unique[user.email]');
	$this->form_validation->set_rules('dateofbirth','DOB','required|');
	$this->form_validation->set_rules('phn','Phone Number','required|numeric|max_length[12]');
	$this->form_validation->set_error_delimiters('<div class="text-danger">', '</div>');
	if($this->form_validation->run())
	{
		$this->load->library('email');
		$this->email->form(set_values('email'),set_values('firstname'),set_values('dateofbirth'),set_values('phn'));
		$this->email->to("neetin.bhardwaj1@gmail.com");
		$this->email->subject("Registration Greeting");

		$this->email->message("Thank you For Registration");
		$this->email->set_newline("\r\n");
		$this->email->send();

		if(!$this->email->send())
		{
			show_error($this->email->print_debugger());
		}
		else
		{
			echo "You Email has been sent Succesfully :)";
		}
	}
	else
	{
		return $this->load->view('admin/register');
	}	
}
 
![image](https://user-images.githubusercontent.com/64898553/84645310-fb1b3c80-af1d-11ea-9b6c-4d35f9576198.png)
sir can you suggest what is the reason why comes this error
