### ISSUE TITLE
User_agent:is_referral() is it correct??

### ISSUE THREAD

**Issue by shotdown** [bcit-ci/CodeIgniter#3912]
at line 506 of :system/libraries/User_agent.php
$this->referer = ($referer_host && $referer_host !== $own_host);

shouldn't it be
$this->referer = ($referer_host && $referer_host === $own_host);
?

**Comment by ZombieProtectionAgency** [comment]
Here is a direct link to the line, to save the extra clicking :)

https://github.com/bcit-ci/CodeIgniter/blob/bd1e61500383245aec702f645955a774604687c6/system/libraries/User_agent.php#L505

**Comment by mwhitneysdsu** [comment]
It wouldn't be a referral if HTTP_REFERER and base_url are the same host, so, at least on the surface, the existing code appears to be correct.

**Comment by ivantcholakov** [comment]
It is correct.
