### ISSUE TITLE
Codeigniter Session On Windows Azure

### ISSUE THREAD

**Issue by Kendysond** [bcit-ci/CodeIgniter#3914]
I've been trying to deploy codeignter on azure and i've been having one little issue,everything works fine for pages that have no codeigniter session,but pages that have the session library loaded,it returns the error,"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." I've searched all over but couldn't find any solution,
Thanks in advance because you guys always solve all my issues!.
![screen shot 2015-06-17 at 10 42 50](https://cloud.githubusercontent.com/assets/5365813/8204075/e222cff2-14dd-11e5-8233-a51899550779.png)

**Comment by jim-parry** [comment]
This is a support issue, and should be raised in a post on forum.codeigniter.com
Github is used for bug reports.
