### ISSUE TITLE
Upload library logging thresholds for errors caused by a user

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#3920]
This is a temporary configuration setting:
```php
$config['log_threshold'] = 1; // Error Messages (including PHP errors)
```

All the errors triggered by the Upload library are at this level. I had a look at some logs for finding programmer errors and they contain messages like this:

"The image you are attempting to upload doesn't fit into the allowed dimensions."

This error particularly is not an error within code, it is caused by a user. The visual interface tells the user what is wrong and this is enough. Logging such an error is noise for the purpose of bug-fixing.

I am proposing these errors:

* upload_invalid_dimensions
* upload_invalid_filesize
* upload_invalid_filetype

to be logged at threshold 2 'debug' - Debug Messages. Edit: These three are actually validation messages, they don't need developer's reaction.

**Comment by narfbg** [comment]
Makes sense ... and more validation errors should be added to that list. That would probably involve adding another parameter to `set_error()` though - will look into it later.

**Comment by ivantcholakov** [comment]
Thank you.
