### ISSUE TITLE
Unable to locate the specified class: Session.php

### ISSUE THREAD

**Issue by tmuks** [bcit-ci/CodeIgniter#3921]
Adding a hook as for pre_controller gives following error: Unable to locate the specified class: Session.php

hook.php: 
$hook['pre_controller'][] = array(
        'class'    => 'LoadConstants',
        'function' => 'index',
        'filename' => 'LoadConstants.php',
        'filepath' => 'hooks',
        'params'   => array()
);

LoadConstants.php: 
class LoadConstants extends CI_Controller {
	function __construct(){
		parent::__construct();
	}
.....

If I remove  extended CI_Controller it works well and adding it will throw above error 

This issue only appears in CI3 and not in older version 2.4

**Comment by LouisMilotte** [comment]
Did you enable hooks in the config?

Unless you are initializing another instance of that hook you do not need to append it as an array, simply call the hook array.

Also, While this isn't directly CI related, I would suggest adopting PSR; in that LoadConstants should be the file and class name.

PSR: http://www.php-fig.org/psr/psr-1/ Classes must use StudyCaps, methods use camelCaps and the use of an underscore should be reserved for variables/parameters.

**Comment by tmuks** [comment]
I agree with naming convention.

Yes, hooks are enabled in config.

CI_Controller is extended in Hook and Controller, so another instance creating issue

**Comment by narfbg** [comment]
So don't extend `CI_Controller` ... it's made for controllers, not hooks. Also, post your questions on the [forums](http://forum.codeigniter.com/), we only accept bug reports here.

**Comment by vikikhan88** [comment]
Don't use the parent constructor

public function __construct() {
    //parent::__construct();
    $CI =& get_instance();
}
