### ISSUE TITLE
Send email using smtp caused infinite loop

### ISSUE THREAD

**Issue by vibbow** [bcit-ci/CodeIgniter#3922]
Hi,

I just notice in some situation, send email using CI Email library by SMTP will cause the code drop into an infinite loop.

The problem is caused by file: \system\libraries\Email.php, function _send_data($data)

```
for ($written = 0, $length = strlen($data); $written < $length; $written += $result)
{
	if (($result = fwrite($this->_smtp_connect, substr($data, $written))) === FALSE)
	{
		break;
	}
}
```

If the connection is terminated during the process of send email, then the fwrite will always return "FALSE" (0)
$written += $result will always stuck at 0
$written < $length will never be happened.
Therefore the for loop will never been end.

The worse thing is my script is running by CLI, means no timeout, and the infinite loop will use 100% of one CPU core, forever, unless I kill it manually.

**Comment by narfbg** [comment]
The purpose of that `if` condition in there is to prevent exactly this - if `fwrite()` returns FALSE, the loop will be broken. Whatever is causing your issue, it's not this piece of code.

**Comment by vibbow** [comment]
http://php.net/manual/en/function.fwrite.php

Please read the first comment.
That's the exactly problem I have currently.

**Comment by LouisMilotte** [comment]
Are you using the same operator "===" because 0 === false is false. however, 0 == false is true

**Comment by narfbg** [comment]
@vibbow So you're saying `fwrite()` returns int(0) instead of bool(false) in case of a broken connection?

**Comment by vibbow** [comment]
Yes, sorry for my first comment didn't describe clearly.

And if the connection is broken, PHP will throw a `Notice` for `fwrite()`.

**Comment by narfbg** [comment]
What's the notice message?

It should be that `$this->_smtp_connect` isn't a valid resource, in which case it's also an invalid parameter for `fwrite()` and in that case boolean FALSE should be returned ...

**Comment by vibbow** [comment]
There are two different notice:
1. An established connection was aborted by the software in your host machine
2. An existing connection was forcibly closed by the remote host.

I think it's kind mean the $this->_smtp_connect is still a resource, just this resource's network is closed.

**Comment by narfbg** [comment]
Well, that's a quite strange behavior ...
This bug report seems to explain it to an extent: https://bugs.php.net/bug.php?id=39598

**Comment by vibbow** [comment]
What I'm doing now as a work around for this problem are:
1. check the fwrite's response, if the response is 0, then usleep a little while, so it won't loop too fast.
2. implement a timeout for the for loop.

**Comment by narfbg** [comment]
Great, thanks for the report & the suggestions! See the linked commit for the fix.
