### ISSUE TITLE
Hide CI from the web folder?!

### ISSUE THREAD

**Issue by dotku** [bcit-ci/CodeIgniter#3923]
I'm thinking if there is possible to hide application core code from the client?!
For example the directory map would display like this way:

/ci/
/abc.com/
/abc.com/index.php <- include ci core file for running

so while user is accessing the website, they would never be able to touch the CI folder; also, it might be a secure way to develop a webapp without touching any code in CI.

**Comment by narfbg** [comment]
Please ask your questions on the [forums](http://forum.codeigniter.com/), not here. Also, there are hundreds of suggestions that you could find about this by a simple google search ... make a little effort.
