### ISSUE TITLE
The session class has a problem and should be looked into closely

### ISSUE THREAD

**Issue by Elvis254** [bcit-ci/CodeIgniter#3927]
I am working on a web application using codeigniter 3 programming on windows 8.1 pro of course but am facing challenges it keeps on displaying a blank page when I try to login where data is saved in the session, am not even able to debug because no error is displayed. And also after this it will only work when I don't supply any uri e.g. http://localhost/jamii/index.php and not work if its http://localhost/jamii/index.php/client/home Please am interested in knowing what the problem is but a blank page is what I get. I can't debug.
Below is the code for login class, client class, and clients class look into it and help where you can.

Client

<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Client extends CI_Controller 
{
	public function __construct()
    {
        parent::__construct();
    }
    
	public function index()
	{
		if($this->clients->is_logged_in())
		{
			redirect('client/dashboard', 'refresh');
		}
		else
		{
			$data['page_header'] = "SMSJamii - Welcome";
			$this->load->view('client/home_page', $data);
		}
	}

	public function home()
	{
		if($this->clients->is_logged_in())
		{
			redirect('client/dashboard', 'refresh');
		}
		else
		{
			$data['page_header'] = "SMSJamii - Welcome";
			$this->load->view('client/home_page', $data);
		}
	}

	public function dashboard()
	{
		if($this->clients->is_logged_in())
		{
			$data['page_header'] = "SMSJamii - Dashboard";
			$this->load->view('client/dashboard_page', $data);
		}
		else
		{
			redirect('client/home', 'refresh');
		}
	}

	public function sendsms()
	{
		if($this->clients->is_logged_in())
		{
			$data['page_header'] = "SMSJamii - Send an SMS";
			$this->load->view('client/sendsms_page', $data);
		}
		else
		{
			redirect('client/home', 'refresh');
		}
	}

	public function sendapic()
	{
		if($this->clients->is_logged_in())
		{
			$data['page_header'] = "SMSJamii - Send a Pic";
			$data['error'] = "";
			$data['locations'] = $this->locations->get_all_filtered();
			$data['pictures'] = $this->pictures->get_all_by_client($this->clients->get_logged_in_client_info()->client_id, 10);
			$this->load->view('client/sendapic_page', $data);
		}
		else
		{
			redirect('client/home', 'refresh');
		}
	}

	public function settings()
	{
		if($this->clients->is_logged_in())
		{
			$data['page_header'] = "SMSJamii - Personal Information";
			$this->load->view('client/settings_page', $data);
		}
		else
		{
			redirect('client/home', 'refresh');
		}
	}

	public function changepassword()
	{
		if($this->clients->is_logged_in())
		{
			$data['page_header'] = "SMSJamii - Change Password";
			$this->load->view('client/changepassword_page', $data);
		}
		else
		{
			redirect('client/home', 'refresh');
		}
	}

	public function validateaccount()
	{
		if($this->clients->is_logged_in() && $this->clients->get_logged_in_client_info()->validated == 0)
		{
			$data['page_header'] = "SMSJamii - Validate Account";
			$this->load->view('client/validateaccount_page', $data);
		}
		else
		{
			redirect('client/home', 'refresh');
		}
	}
}

Login

<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Login extends CI_Controller 
{
	public function __construct()
    {
        parent::__construct();
    }
    
	public function index()
	{
		if($this->clients->is_logged_in())
		{
			redirect('client/dashboard', 'refresh');
		}
		else
		{
			$data['page_header'] = "SMSJamii - Login";
			$this->load->view('client/login_page', $data);
		}
	}

	public function access()
	{
		if($this->clients->is_logged_in())
		{
			redirect('client/dashboard', 'refresh');
		}
		else
		{
			$this->form_validation->set_rules('phonenumber', 'Phone Number', 'required|exact_length[9]');
			$this->form_validation->set_rules('password', 'Password', 'required|max_length[16]|min_length[6]');
			$this->form_validation->set_error_delimiters('<div class="alert alert-danger alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>', '</div>');

			if ($this->form_validation->run() == FALSE)
			{
				$this->index();
			}
			else
			{
				$login = $this->clients->login($this->input->post('phonenumber'), $this->input->post('password'));

				if($login)
				{
					redirect('client/dashboard', 'refresh');
				}
				else
				{
					$this->session->set_userdata('notloggedin', TRUE);
					redirect('login', 'refresh');
				}
			}
		}
	}
}

Clients

<?php 
defined('BASEPATH') OR exit('No direct script access allowed');

class Clients extends CI_Model 
{
	public function __construct()
    {
        parent::__construct();
    }

	/*
	Determines whether the given client exists
	*/
	function exists($client_id)
	{
		$this->db->from('clients_tb');	
		$this->db->where('client_id', $client_id);
		$query = $this->db->get();
		
		return ($query->num_rows()==1);
	}

	/*
	Determines whether the given client phone number exists
	*/
	function phone_exists($phonenumber)
	{
		$this->db->from('clients_tb');	
		$this->db->where('phonenumber', $phonenumber);
		$query = $this->db->get();
		
		return ($query->num_rows()==1);
	}
	
	/*
	Gets all clients
	*/
	function get_all($limit=10000, $offset=0)
	{
		$this->db->from('clients_tb');
		$this->db->limit($limit);
		$this->db->offset($offset);
		return $this->db->get();		
	}

	/*
	Counts all active clients
	*/
	function count_all()
	{
		$this->db->from('clients_tb');
		return $this->db->count_all_results();
	}
		
	/*
	Gets information about a client as an array.
	*/
	function get_info($client_id)
	{
		$query = $this->db->get_where('clients_tb', array('client_id' => $client_id), 1);
		
		if($query->num_rows()==1)
		{
			return $query->row();
		}
		else
		{
			//create object with empty properties.
			$fields = $this->db->list_fields('clients_tb');
			$client_obj = new stdClass;
			
			foreach ($fields as $field)
			{
				$client_obj->$field='';
			}
			
			return $client_obj;
		}
	}
	
	/*
	Inserts or updates a client
	*/
	function save(&$client_data, $client_id=false)
	{
		if(!$client_id or !$this->exists($client_id))
		{
			if($this->db->insert('clients_tb', $client_data))
			{
				return true;
			}
			
			return false;
		}
		
		$this->db->where('client_id', $client_id);
		return $this->db->update('clients_tb', $client_data);
	}
	
	/*
	Attempts to login client and set session. Returns boolean based on outcome.
	*/
	function login($phonenumber, $password)
	{
		$query = $this->db->get_where('clients_tb', array('phonenumber' => $phonenumber, 'password' => md5($password), 'deleted' => 0), 1);
		if ($query->num_rows() ==1)
		{
			$row = $query->row();
			$this->session->set_userdata('client_id', $row->client_id);
			return true;
		}
		return false;
	}
	
	/*
	Logs out a client by destorying all session data and redirect to home page
	*/
	function logout()
	{
		$this->session->sess_destroy();
		redirect('client/home', 'refresh');
	}
	
	/*
	Determines if a client is logged in
	*/
	function is_logged_in()
	{
		return $this->session->userdata('client_id') != false;
	}
	
	/*
	Gets information about the currently logged in client
	*/
	function get_logged_in_client_info()
	{
		if($this->is_logged_in())
		{
			return $this->get_info($this->session->userdata('client_id'));
		}
		
		return false;
	}
}

**Comment by narfbg** [comment]
We know there's an issue with file-based sessions on newer Windows setups, but it's caused by the file-system and there's nothing that can be done about it.

**Comment by Elvis254** [comment]
What do I do, I install windows 7 instead or a new copy of xxamp, please help.

**Comment by narfbg** [comment]
I don't know ... use database-based sessions while on Windows? As long as you're not using the 'files' driver it should work.

I believe the problem comes from how Windows achieves its fast-boot feature - it does constant writes while you're using it, so it can hybernate instead of shutdown afterwards ... and it has to do it fast. That doesn't play nice with the `flock()` calls. In fact, I've also had a problem where I couldn't write to an NTFS partition from Linux on a dual-boot setup until I turned off the fast-boot feature ...

Anyway, if you need help with something, you should post your questions on our [forums](http://forum.codeigniter.com/) instead. We only accept bug reports here and I normally wouldn't answer your question - I only did it because it probably is a common issue for many Windows users.

**Comment by Elvis254** [comment]
Thanks.

**Comment by Elvis254** [comment]
I realised am not able to use the session when am connected to the internet using mozilla firefox 36. Anyway its working on Google Chrome.
