### ISSUE TITLE
return value of insert

### ISSUE THREAD

**Issue by lesfleurs** [bcit-ci/CodeIgniter#3929]
According to the docs, the return value of insert is boolean on success.
I am doing a var dump of the return value of insert currently and it keeps returning an integer 0 even though the affected rows function and database both show that the insert is successful. I need a way of checking if the insert is successful. I have read that the afected_rows function should be avoided does not work well with sql server which is why i am not using it to check inserts.

**Comment by narfbg** [comment]
Is this on CI3 or 2.x?

**Comment by lesfleurs** [comment]
This is for codeigniter 3, after some digging, insert always returns integer 0 if no primary key is set on the table (Mysql) or if there is no auto increment. If there is a primary key and it is set to auto increment, insert returns the id of the most recent entry for successful insert otherwise it returns false as defined

**Comment by nayosx** [comment]
return $this->db->insert('my_table', $my_array);

**Comment by narfbg** [comment]
@lesfleurs Sorry, but I can't reproduce this and having looked twice over the calls initiated by `CI_DB_query_builder::insert()`, I see no possible way of it returning a non-boolean value.

Are you using it like @nayosx has shown above or are you doing something else?

**Comment by lesfleurs** [comment]
For some reason my insert call was returning the Id of the last successful insert. I am using it the way @nayosx described. It works great
