### ISSUE TITLE
codeigniter 2.2.2 session can't pass data to another controller

### ISSUE THREAD

**Issue by frank270** [bcit-ci/CodeIgniter#3931]
is anyone happen this as title?

I store session in database just as usual~

But when I update to 2.2.2

simply set_userdata in A controller, But I can't get the data in B controller!

**Comment by LouisMilotte** [comment]
Does this error occur in v3?

**Comment by frank270** [comment]
I've not try in V3

**Comment by LouisMilotte** [comment]
From comments: V2 will only be receiving security fixes not functionality. 

Also, this seems like a support ticket not bug report. o to forums for support.

**Comment by frank270** [comment]
sorry , about wrong place!
