### ISSUE TITLE
Compile where fails

### ISSUE THREAD

**Issue by avdata99** [bcit-ci/CodeIgniter#3932]
I need to fix query because *where* was compiled as:  
```
DELETE FROM `usuario_observadores` WHERE `id_usuario` = '1' AND id_observador `NOT` IN('3') 
```
Compile put bracket on **NOT** and not in **id_observador** field
I'm using **grocery_crud**, relating fields with **relation_n_n**.   

My fix:
https://github.com/avdata99/medusapp/commit/495364bce3e96e8fb3dab04791b3549a09c11587

**Comment by narfbg** [comment]
What's the QB code that resulted in this query?

**Comment by avdata99** [comment]
Some example:
```Array ( 
  [0] => Array ( [condition] => id_usuario = '5' [escape] => 1 ) 
  [1] => Array ( [condition] => AND id_observador NOT IN('4') [escape] => 1 ) )
```

**Comment by narfbg** [comment]
Just FYI, that was not what I asked for and barely helped ... I have to know how the query builder methods are *called*, not what they result in.
