### ISSUE TITLE
A feature request: Record the current URL on error logging

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#3933]
CI forum topic: http://forum.codeigniter.com/thread-62286.html

I modified this line:
https://github.com/bcit-ci/CodeIgniter/blob/3.0.0/system/core/Log.php#L207

as follows:

```php
		$message .= $level.' - '.$date.' --> '.$msg.(!is_cli() ? ' --> URL: '.CURRENT_URL : '')."\n";
```

The modification is suitable for my projects, it is here for illustration, for pure CodeIgniter it would be different and seemingly not so easy.

Edit: Getting greedy:

```php
		$message .= $level.' - '.$date.' --> '.$msg.(!is_cli() ? ' --> URL: '.CURRENT_URL : (isset($_SERVER['argv']) && is_array($_SERVER['argv']) ? ' --> Command: '.implode(' ', $_SERVER['argv']) : ''))."\n";
```

**Comment by narfbg** [comment]
Not worth the effort.
