### ISSUE TITLE
Bug found in DB_driver.php

### ISSUE THREAD

**Issue by rikdavis** [bcit-ci/CodeIgniter#3934]
Discovered a bug in system/database/DB_driver.php at line 1754 in the following code;
    if (strpos($item, '(') !== FALSE OR strpos($item, "'") !== FALSE)

Steps to replicate:
1. Within a model, create the following code;
    $this->db->select('CONCAT(somecol1, \' \', somecol2) AS full_col, somecol3');
    $this->db->where('id', $id);
    $qry = $this->db->get('some_table');
    * Rewrite this code to work in an actual mysql database & table.

2. You should get the following SQL error;

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM `employees` WHERE `id` = '7'' at line 2

SELECT CONCAT(f_name, ' ', `l_name)` AS `full_name`, `email_addr` FROM `employees` WHERE `id` = '7'

Inspect the query closely and the problem becomes quite clear.
                                                               v--Note where the closing tick is
SELECT CONCAT(f_name, ' ', `l_name)` AS `full_name`, `email_addr` FROM `employees` WHERE `id` = '7'

Replaced with the following fixes this;
    if(strpos($item, '(') !== FALSE OR strpos($item, "'") !== FALSE OR strpos($item, ')') !== FALSE)

Root cause:
The 'if' block checked for the opening parenthesis, but not the closing one. When I added the code that accounts for the closing one also, it fixed the issue perfectly.

Hope this helps.

**Comment by narfbg** [comment]
Just FYI, this is not a bug ... it's a lack of yet another dirty work-around.

**Comment by rikdavis** [comment]
Good to know. Thanks for that feedback. CodeIgniter is one of the most well done frameworks out there and even puts some full stack ones to shame. Great work to all of you!
