### ISSUE TITLE
all db_driver supported function `drop_table`?

### ISSUE THREAD

**Issue by ftwbzhao** [bcit-ci/CodeIgniter#3941]
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_forge.php#L457

```php
		$query = $this->_drop_table($this->db->dbprefix.$table_name, $if_exists);

		if ($query === FALSE)
		{
			return ($this->db->db_debug) ? $this->db->display_error('db_unsupported_feature') : FALSE;
		}
		elseif ($query === TRUE)
		{
			return TRUE;
		}
```

> Use `$this->_drop_table`, return type **never equals FALSE**.

So 

```php
		if ($query === FALSE)
		{
			return ($this->db->db_debug) ? $this->db->display_error('db_unsupported_feature') : FALSE;
		}
```

is dead code? Eliminated  it?

**Comment by narfbg** [comment]
That's the kind of thing that you should submit a pull request for ... seeing a *question* about a piece of code is really annoying.

**Comment by ftwbzhao** [comment]
got it
