### ISSUE TITLE
why not support redis for hash and list so on...

### ISSUE THREAD

**Issue by sexdon** [bcit-ci/CodeIgniter#3943]
I check all over the Cache_redis , did not found like 'hSet,hGet,lSet....' and so no. i had problem about this , weather need to write they by myself?

thank you

**Comment by narfbg** [comment]
The Cache library isn't a Redis library ... it doesn't implement everything that Redis does, it just uses it as yet another driver. If you need these methods, just use directly the phpredis extension.

Also, please post your questions on the [forums](http://forum.codeigniter.com/), we only accept bug reports here.
