### ISSUE TITLE
Radio input required rule form validation issue

### ISSUE THREAD

**Issue by byybora** [bcit-ci/CodeIgniter#3947]
**On CodeIgniter 3.0.0 Version**

I'm getting validation errors always even if i can get `groups` data success when i dump `$this->input->post('groups');` but i couldnt pass the CodeIgniter form validation process.

### Controller
````
$this->form_validation->set_rules('groups', 'Groups', 'required');
````
### Views
````
<input type="radio" name="groups" value="2" <?=set_radio('groups', 2, true)?>
<input type="radio" name="groups" value="3" <?=set_radio('groups', 3, false)?>
````

**Validation Error**

> the Groups field required

**Comment by narfbg** [comment]
Can't reproduce.

Please post your questions on the [forums](http://forum.codeigniter.com/) instead.
