### ISSUE TITLE
CI_DB_result not found

### ISSUE THREAD

**Issue by wrdhat** [bcit-ci/CodeIgniter#3962]
I working with pyroCMS but  when i upload to my hosting (GoDaddy) this error appear me.
Fatal error: Class 'CI_DB_result' not found in mysql_result.php but.

I look the file (mysql_result.php) and mysql_result.php extend of CI_DB_RESULT.
example:
          class CI_DB_mysql_result extends CI_DB_result{
          }
 
I use mysql for connection with the database, however if i use mysqli, show me the same error.

**Comment by narfbg** [comment]
Report this to PyroCMS.

**Comment by wrdhat** [comment]
Ok thanks
