### ISSUE TITLE
comments in application/config/autoload.php are incorrect 

### ISSUE THREAD

**Issue by sneakyimp** [bcit-ci/CodeIgniter#3964]
This may seem like nit picking but the comments in application/config/autoload.php are incorrect which leads to confusion:
```php
/*
| -------------------------------------------------------------------
|  Auto-load Libraries
| -------------------------------------------------------------------
| These are the classes located in the system/libraries folder
| or in your application/libraries folder.
|
| Prototype:
|
|	$autoload['libraries'] = array('database', 'email', 'session');
|
| You can also supply an alternative library name to be assigned
| in the controller:
|
|	$autoload['libraries'] = array('user_agent' => 'ua');
*/

$autoload['libraries'] = array('database', 'session');
```
"database" is clearly indicated as an option here but does not exist in the system/libraries or application/libraries folders. I have caught myself several times wondering whether "database" is in fact a library or a driver. Also, it is unclear what the difference is between a library and a driver. Based on the comments here about being "within their own subdirectory," I would imagine that Cache, Javascript, and Session are all drivers, whereas all the other individual files are libraries.

```php
/*
| -------------------------------------------------------------------
|  Auto-load Drivers
| -------------------------------------------------------------------
| These classes are located in the system/libraries folder or in your
| application/libraries folder within their own subdirectory. They
| offer multiple interchangeable driver options.
|
| Prototype:
|
|	$autoload['drivers'] = array('cache');
*/

$autoload['drivers'] = array();
```

Perhaps we could clarify these? It would likely reduce a lot of confusion IMHO.

**Comment by mwhitneysdsu** [comment]
If you check the autoloader, when going through `$autoload['libraries']`, the autoloader first checks for `'database'`, and, if found, loads the database library (even though it's not in the system's libraries directory), then removes the entry from the array before going on to attempt to load all of the libraries in the array.

You're only really going to put classes in the `'drivers'` list which extend `CI_Driver_Library`. In the built-in libraries, that means `Cache`, and nothing else. Session and Javascript are libraries which happen to use drivers, but those drivers don't even extend `CI_Driver_Library`, so the libraries don't use the loader's `driver()` method to load their drivers.

When looking at the documentation for a class, it tells you whether to use `$this->load->library()` or `$this->load->driver()` to load the class. This is an indication of which of these entries should be used for autoloading. Database is just a special case, in more ways that just this.

**Comment by sneakyimp** [comment]
Thanks very much for the helpful detail. That sounds unfortunately ad-hoc. 

I see that 'session' was only recently removed from drivers:
https://github.com/bcit-ci/CodeIgniter/commit/3a627d1951543b7e6ae3f3b3c93a013b33c8986e

I wonder if some of your wisdom here might be distilled into something brief and more accurate for these comments.

**Comment by narfbg** [comment]
The Session library was never a "driver" *in an official release*. If you ever thought it was, it's because you were using the 3.0-dev version and you use development versions on your own risk ... it's your responsibility to follow dev-version changes.

I have also never, ever seen any confusion about how to auto-load the database classes.

That being said, yes - the comments are a bit unclear in that they don't mention the 'database' classes as a special case and they don't describe that a "driver" must actually use `CI_Driver`. That "driver" concept is horrible and will go away in the future.

**Comment by sneakyimp** [comment]
I would imagine that removal of the autoloading of drivers -- something that could easily break an existing website -- is something that should happen with a major version change. (e.g., version 3.x to 4.x) and at the very least something that would happen with a minor version change (e.g., 3.0 to 3.1) and not something that would happen in a development branch for a single version.

I would also point out that the CodeIgniter home page (http://www.codeigniter.com/download ) directs users to the develop branch. The "download CI 3.0" link goes to the develop branch here:
https://github.com/bcit-ci/CodeIgniter/archive/3.0.0.zip
Is this branch expected to be unstable?

Perhaps then that link should be to some other branch (e.g., "master?"). It's not clear from the home page of the 'master' branch which version of CodeIgniter it refers to. Perhaps that is something we could add to the README file.

**Comment by jim-parry** [comment]
The codeigniter.com homepage directs users to the *3.0.0* download, and *not* to the develop branch. The only way to get the "develop" branch is to download the framework from github directly.

**Comment by narfbg** [comment]
@sneakyimp You're overthinking it, a lot, and taking this way off-topic ... Of course we're not just going to drop `$autoload['drivers']` in the next micro-version, this shouldn't be a discussion point at all.

And as @jim-parry said, the codeigniter.com/download points to the 3.0.0 download archive and not the develop branch - the fact that the ZIP archive itself is named 3.0.0.zip should tell you that.

**Comment by sneakyimp** [comment]
I was mistaken about the download link - I apologize. I love CI and have adopted it for a lot of new projects. Just got worried for a second about how rapidly it might be changing.

The helpful thing for me to do would be to try and assist in formulating a slightly better comment based on the helpful info here. Is that something you guys could use? I'm not sure if I can commit to this project or not. Let me know if that's something you guys would find helpful.
