### ISSUE TITLE
upload class encrypt_name does not working if overwrite is true

### ISSUE THREAD

**Issue by andersonunsonst** [bcit-ci/CodeIgniter#3965]
testing : ci 2.2.2

for example: foo.jpg

        $config['overwrite'] = TRUE;
        $config['encrypt_name'] = TRUE;
file_name return foo.jpg (weird)

but if i put in config..
        $config['overwrite'] = FALSE;
        $config['encrypt_name'] = TRUE;

return right result

**Comment by narfbg** [comment]
CI2 only receives security fixes now ... I don't understand exactly what you mean here, but even if it's a bug - it won't be fixed.

**Comment by andersonunsonst** [comment]
ok, i understand...
To documentation the File Uploading class say, if i set $config['encrypt_name'] to TRUE, the file name will be converted to a random encrypted string, but if set $config['overwrite'] to FALSE, the class does not convert the file name to encrypted string, it is wrong result...i lost a lot time to discovery this behavior


In upload.php at line 537, the method $this->set_filename, is set under "if($this->overwrite===FALSE)" , if overwrite array not set as FALSE, does not call the method set_filename and not  encrypting file name, this is a bug present in ci3 too

if ($this->overwrite === FALSE)
{
    $this->file_name = $this->set_filename($this->upload_path, $this->file_name);
    if ($this->file_name === FALSE)
    {
              return FALSE;
     }
}


ps. i'm sorry for my poor english

**Comment by narfbg** [comment]
Fixed for the 3.0.x version tree ... thanks.
