### ISSUE TITLE
Retrieve real IP of user using codeigniter

### ISSUE THREAD

**Issue by suvozit** [bcit-ci/CodeIgniter#3966]
I am running `CI 3.0rc3` on AWS behind a Loadbalancer

```
// the ip of the load balancer
echo $this->input->ip_address();

// the real client ip is
echo $this->input->server('HTTP_X_FORWARDED_FOR');
```

## Reference
http://stackoverflow.com/questions/14491043/retrieve-real-ip-of-user-using-codeigniter

**Comment by narfbg** [comment]
Your reference itself has the proper answer: http://stackoverflow.com/a/20678498/468027

**Comment by suvozit** [comment]
@narfbg Thank you. 😊
