### ISSUE TITLE
Validations height and width

### ISSUE THREAD

**Issue by sidaurukfreddy** [bcit-ci/CodeIgniter#3967]
Hi thanks for upgrading Codeignter, easy to use and learn, well i have some issue honestly not hard for experts programmer but for me as new at programming hard to make it, so here is my problem about uploading images in codeigniter

Code igniter has configuration about it, but there is some configuration need to fixed, let me give sample code http://pastebin.com/ZkxKNcaL

Look by read my code you can guess i need to make validations for height and width,
 the problem is validations height and width working well but images uploaded to folder !

Do i the only one feel this need to make sure width and height, Sorry for stupid issue, Thanks !

Freddy Sidauruk

**Comment by sidaurukfreddy** [comment]
Solved validation before upload here my script http://pastebin.com/TUL0v7sa

**Comment by narfbg** [comment]
For future reference, please note that you shouldn't post such questions here on GitHub ... we only accept bug reports here.

If you need help with something that's not a problem in the framework itself, post your questions on our [forums](http://forum.codeigniter.com/).
