### ISSUE TITLE
[3.0.0] inconsistent query results

### ISSUE THREAD

**Issue by isantolin** [bcit-ci/CodeIgniter#3971]
With this code:
```php
       $this->db->select('*');
        $this->db->from('contents');
        $this->db->where('idContent', '7test');
        $query = $this->db->get();

        $content = $query->row();
```
var_dump for $contents

```
object(stdClass)[23]
  public 'idContent' => string '7' (length=1)
  public 'IdUsuario' => string '0' (length=1)
  public 'Title' => string 'llll' (length=4)
  public 'Body' => string 'lllll' (length=5)
  public 'Fecha' => string '2015-06-29 19:47:08' (length=19)
  public 'IP' => string '127.0.0.1' (length=9)
```
Should not give any results because there is no idContent with a value "7test" on the database.
Note that occurs when specifies certain values "7sdsadsddsasaddsa" or "7awa". but when specifies an only numeric value "7634" or "72344" give no results (expected behavior)

**Comment by narfbg** [comment]
With some (if not most) databases, when you pass a non-numeric string for comparison with an integer field, any leading number characters in the string will be assumed as an integer and everything else is ignored. This is all on the database engine and can't be influenced by CI ...

Even PHP behaves that way:

    php > var_dump(7 == '7asd');
    bool(true)
