### ISSUE TITLE
Trouble with escape method in function “from” of Query Builder

### ISSUE THREAD

**Issue by metalfox6383** [bcit-ci/CodeIgniter#3973]
Hi.

I have a problem with the way of escape of Query Builder in Codeigniter 3.0. For example, this code:

echo $this->db->select('ROUND(3.456, 1) AS T1')->get_compiled_select();
Return:
    SELECT ROUND(3.456, `1)` AS `T1`

The function put backticks after a coma and out of parenthesis, but this is solved by setting FALSE the second parameter. But the function "from" put always backticks:

echo $this->db->from('(SELECT ROUND(3.456, 1)) AS T1')->get_compiled_select()
Return:
    SELECT * FROM (SELECT ROUND(3.456, `1))` AS `T1`

I'm using Codeigniter 3.0. The problem exists since Codeigniter 2.2. I need use the Query Builder beacuse it's very easy to use, but its escape method is troublesome. 

I try setting config '_protect_identifiers' to FALSE, but give more problems with insert, where and update functions.

Thanks.

**Comment by narfbg** [comment]
Query Builder isn't meant to work with raw SQL, which is exactly what `(SELECT ROUND(3.456, 1)) AS T1` is.

**Comment by metalfox6383** [comment]
Hi. Thanks for answer. Sorry, the page hide the backticks in my text. I re-edited.
My original query is more complex, but the example show the conflict with the backticks. For now, I solved my problem using db->query(), but the Query Builder is very simple. Greetings.
