### ISSUE TITLE
can't not findOne sub array mongodb 

### ISSUE THREAD

**Issue by luckyfor** [bcit-ci/CodeIgniter#3975]
I can try and not succes, please fix it.
When i use 
$this->mongo_db->where(array("tags_a.link"=>$link))
					->select(array('tags_a.link'))					
					->get('site',array("tags_a"=>$link));
Then result is array, but i want get 1 value.

**Comment by narfbg** [comment]
There's nothing to fix, CodeIgniter doesn't have a MongoDB driver/library.
