### ISSUE TITLE
Resolve the issues with stored_procedure()

### ISSUE THREAD

**Issue by narfbg** [bcit-ci/CodeIgniter#3981]
Currently, only the 'oci8' driver has this method and no others can use it, because it requires a "package" parameter (mandatory, first argument), which AFAIK no other RDBMS has a use case for.

`func_get_args()` is the only way to fix this mess in a backwards-compatible way.

Some pieces from #2047 may be useful.

**Comment by narfbg** [comment]
The method has been removed.

**Comment by ytetsuro** [comment]
@narfbg 
I am using CodeIgniter4 to create the OCI8 driver.
I am also porting the stored_procedure method.

I would like to know why you have removed the stored_procedure method.

**Comment by narfbg** [comment]
It simply doesn't fit into a database abstraction layer. Both in that it only existed for the oci8 driver, and its design was such that it couldn't be implemented for other drivers.

**Comment by kenjis** [comment]
@narfbg What about backward compatibility for users who are using it?

**Comment by narfbg** [comment]
What about it? It's obviously a BC break, nobody is unaware of that ... I don't understand what you mean.

**Comment by narfbg** [comment]
Just realized that I haven't liked related commits here, which likely would've answered some questions. Here's the upgrade instruction: https://github.com/bcit-ci/CodeIgniter/blob/f4c2c4cb533b0e9cc7a01d4ff29db829970fd60d/user_guide_src/source/installation/upgrade_320.rst#step-13-remove-usage-of-oci8-get_cursor-and-stored_procedure-methods

**Comment by ytetsuro** [comment]
@narfbg 

> It simply doesn't fit into a database abstraction layer.

Thank you for letting me know.
I understand.
