### ISSUE TITLE
 mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() instead

### ISSUE THREAD

**Issue by runningmark** [bcit-ci/CodeIgniter#3984]
this warning while using php 5.4

**Comment by narfbg** [comment]
Latest versions of CI no longer use that function. Please make at least a little effort before reporting something.

**Comment by runningmark** [comment]
but how come there is that error?

**Comment by LouisMilotte** [comment]
Because you're using a library of mysql you shouldn't be. Use MySQLi or PDO type mysql functions or simply stick with the CI 3 AD/DB Classes

**Comment by narfbg** [comment]
That the 'mysql' driver is deprecated is true, but he's not getting the error because of that. He's getting it because he's using an old CI version (which I already implied in my first comment).
