### ISSUE TITLE
'rewrite_short_tags' never works

### ISSUE THREAD

**Issue by torohill** [bcit-ci/CodeIgniter#3991]
`eval` is a language construct, hence it can't be tested with `function_exists` as the test always fails. This is currently done via `function_usable` in `Loader.php` line 908, when rewriting short open tags. 

It looks like the check for `suhosin.executor.disable_eval` in `function_usable` needs to be split off into a separate function, for use when checking if `eval` is available.

This is only an issue on PHP version prior to 5.4 so it may not be worth doing anything about it.

**Comment by narfbg** [comment]
I wouldn't call this an issue regardless of the PHP version.

**Comment by torohill** [comment]
`function_usable` will return false for 'eval', as the call to `function_exists` returns false (line 908 of `Loader.php`). So in the case where the PHP version is less that 5.4, `short_open_tags` is off, and `rewrite_short_tags` config is true, short open tags will not get rewritten. I don't think this is intended behaviour.

Sorry, I think the original title for the issue was not very good. Perhaps it should have been 'Short tags not rewritten because existence of eval can't be tested with function_exists (PHP < 5.4)'.

**Comment by narfbg** [comment]
Ah, yes ... that's a different thing.
