### ISSUE TITLE
Form validation set_rules not working with PUT, DELETE etc.

### ISSUE THREAD

**Issue by Jammyman** [bcit-ci/CodeIgniter#3997]
I just updated to Codeigniter 3 and noticed that Form validation library stopped working with my restful api. After some digging I noticed that data checking (in the beginning of set_rules function) has changed.

Old was to check just to check if we have any $_POST data:
```php
 // No reason to set rules if we have no POST data
if (count($_POST) == 0)
{
	return $this;
}
```

 New way is to check the method:
```php
// No reason to set rules if we have no POST data
// or a validation array has not been specified
if ($this->CI->input->method() !== 'post' && empty($this->validation_data))
{
	return $this;
}
```

Personally I like the idea that I could use Form validation library without form at all, since there already is way to validate array (other than $_POST). So this kind of checks might be totally unnecessary in the Form validation library? 

But if that's not good idea, how about adding restful methods there too like PUT, DELETE etc?

Right now I fix this by updating the variable: $_SERVER['REQUEST_METHOD'] = 'POST'; in routes after I have found the right path for my restful api, but of course this is not very good way to fix the problem :D

**Comment by softwarespot** [comment]
You can use form validation with a form. Here, read (this)[http://www.codeigniter.com/user_guide/libraries/form_validation.html?highlight=set_data#CI_Form_validation::set_data]

**Comment by Jammyman** [comment]
I just noticed the set_data function too, so I this issue is now solved ;)

**Comment by Jammyman** [comment]
Actually that don't solve my problem, since the problem is in the set_rules function.

**Comment by narfbg** [comment]
5ea646a9a1012168fde1a6a2b970d4168e2c11fc
