### ISSUE TITLE
Callback in form_validation not working

### ISSUE THREAD

**Issue by hamton** [bcit-ci/CodeIgniter#3998]
function verify () {
		$this->form_validation->set_rules('user', lang('User'),'callback_check');
                $this->form_validation->run()
}

public function check() {
return true;
}

Message: 'Unable to find callback validation rule: '

**Comment by chalchis** [comment]
i me too with similar problem en ci 2.2 usinf HMVC
http://www.mahbubblog.com/php/form-validation-callbacks-in-hmvc-in-codeigniter/

**Comment by hamton** [comment]
Yes, I found the solution in that post. :dancers:
