### ISSUE TITLE
The query builder, escaping degradation in "where" clause detected

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#4001]
```php
echo $this->db
    ->select('id')
    ->from('requests')
    ->where('active', 1)
    ->where('duration_date >=', 'CURDATE()', false)
    ->get_compiled_select();
```

In CodeIgniter 3.0.0 the result is as I expect it to be:

```sql
SELECT `id`
FROM `requests`
WHERE `active` = 1
AND duration_date >=CURDATE()
```

The current code CodeIgniter 3.0.1rc+ gives me wrong SQL:

```sql
SELECT `id`
FROM `requests`
WHERE `active` = 1
AND duration_date >= 'CURDATE()'
```

**Comment by narfbg** [comment]
Not degradation, but a bugfix - the escape parameter is for field name escaping only.

**Comment by ivantcholakov** [comment]
I see.

```php
echo $this->db
    ->select('id')
    ->from('requests')
    ->where('active', 1)
    ->where('duration_date >= CURDATE()', null, false)
    ->get_compiled_select();
```

**Comment by ivantcholakov** [comment]
But...

http://www.codeigniter.com/user_guide/database/query_builder.html#updating-data

There is the following example:

```php
$this->db->set('field', 'field+1', FALSE);
$this->db->insert('mytable'); // gives INSERT INTO mytable (field) VALUES (field+1)
$this->db->set('field', 'field+1');
$this->db->insert('mytable'); // gives INSERT INTO mytable (field) VALUES ('field+1')
```

Testing:

```php
$this->db->set('field', 'field+1', false);
echo $this->db->get_compiled_insert('mytable');
```

And the returned result is not expected:

```sql
INSERT INTO `mytable` (field) VALUES ('field+1')
```

-------------------------------

Use case:

I've got a page hit counter:

```php
        $this->_database
                ->set('hitcount', 'hitcount + 1', false)
                ->where('pageid', $page_id)
                ->where('isunique', $unique)
                ->update($this->_table);
```

I noticed recently that it stopped to increment, after some of the upgrades.

**Comment by narfbg** [comment]
Hmm ... well, if it didn't previously add backticks (assuming MySQL), it's obviously not designed for fields. That example is not just wrong but also completely illogical as you can't insert field+1 because field has no value.

I'm not sure about your use case though. This is surely not the way to solve it, but it should be allowed to happen in some way.

**Comment by ivantcholakov** [comment]
It has a similar set statement, as it is in the guide, that is all.
I hesitate about adding a new parameter $escape_value = TRUE as a possible way.

**Comment by narfbg** [comment]
No, that would be just bloat.

Here's a twist - it seemed strange to me that this appears to be an issue *now*, so I looked into what CI2 did and it turns out both `set()` and `where()` had an escape parameter back then and it did affect values, which is especially weird for `where()`.

I may just have to revert #3989.

**Comment by ivantcholakov** [comment]
Perhaps this is related too, maybe: https://github.com/bcit-ci/CodeIgniter/commit/43afc71b777b00cfc2638add6fa3c47d333c5e04

Maybe a revert would be better, otherwise people will complain.

**Comment by narfbg** [comment]
It is related (and linked in the #3989 thread) ... I was reverting it as you commented on it.

**Comment by narfbg** [comment]
2dfbe9997b28892342e826e9350a466e6bacfd2e
f7631f18d65eaf7f2b3aa5ee603e84008a681ffc
d4a50bd09ee38a25010ac58b17b8db37fc1ec0cb

**Comment by narfbg** [comment]
As it turned out that this was the intended behavior, I just applied it to `_like()` and `_where_in()` (the internal methods that accept variations of LIKE and IN() with OR/AND, NOT conditions).

**Comment by Dentxinho** [comment]
@narfbg 
Please look at this sample code:

```php
echo $this->db->where_in('COALESCE(status,0)', ['A', 1, '1'])->
                where_in('COALESCE(status,0)', ['A', '1', 1], FALSE)-> //afraid of `COALESCE(status,0)`
                set('status', NULL)->
                get_compiled_update('table');
```

On 3.0.2 the result is:
```sql
UPDATE `table` SET `status` = NULL WHERE COALESCE(status,0) IN('A', 1, '1') AND COALESCE(status,0) IN(A, 1, 1)
``` 
(note the literal without quotes)

While on 3.0.0 it was:
```sql
UPDATE `table` SET `status` = NULL WHERE COALESCE(status,0) IN('A', 1, '1') AND COALESCE(status,0) IN('A', '1', 1) 
``` 

I know that removing the ```FALSE``` parameter would work, but this may be a regression
