### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by it-can** [bcit-ci/CodeIgniter#4005]
After this commit I am getting a 404 error on my app...

fddbde69043a1623df8231f96a103af306f5e3db

**Comment by narfbg** [comment]
I said describe the conditions ... this tells me nothing.

**Comment by it-can** [comment]
Well first my webpage worked, after that commit it returns a 404 page... Nothing more nothing less... If i manually revert that commit it works again...

**Comment by narfbg** [comment]
I understand that, but you're not even making an effort.

Does it show a 404 error on *all* pages or is it just one page (I assume the home page)?
What's the `$_SERVER['REQUEST_URI']` value when it triggers the error?
What's your PHP version?

**Comment by it-can** [comment]
It shows on all pages
PHP 5.6

```
array(1) { ["path"]=> string(12) "dummy/admin/" }
```
