### ISSUE TITLE
Problem with database and new Session library

### ISSUE THREAD

**Issue by Jammyman** [bcit-ci/CodeIgniter#4011]
After upgrading to CI 3 I started getting random segfaults with database few times a day. Problem seem to occur with MySQL and also with MariaDB (CentOS & Nginx). 

I can't find anything on error logs, or no peaks on server load before it happens. Last rows before crash in query logs is related to updating the session and releasing the lock. 

Unfortunately database is the only method I can use at the moment. Have you guys heard if anyone had similar problems and maybe how to fix it?

**Comment by narfbg** [comment]
Please post your questions on the [forums](http://forum.codeigniter.com/) instead, we only accept bug reports via GitHub.
