### ISSUE TITLE
Add cache default setting in config.php

### ISSUE THREAD

**Issue by iyaozhen** [bcit-ci/CodeIgniter#4013]
I use cache in almost every model.
I find when I load cache driver, I will be set it. like this:
```
$this->load->driver('cache', [
    'adapter' => 'redis',
    'backup' => 'file',
    'key_prefix' => 'web_',
]);
```
If one day I need modify 'redis' to 'memcached', I have to modify every file, It is very trouble and risk.

So,  I suggesting add cache default setting in config/config.php.

**Comment by narfbg** [comment]
This functionality already exists. The Loader will search for a config file for each library ... you just need to create an *application/config/cache.php* file and put your settings in there (in an array called `$config` ...)

**Comment by iyaozhen** [comment]
I understand. Thx.
