### ISSUE TITLE
Throws an error while trying to load a helper

### ISSUE THREAD

**Issue by osvaldasvalutis** [bcit-ci/CodeIgniter#4014]
I have a helper file in "application/helpers". I've debugged "Loader/helper" and "file_exists" returns "true". However, the loader then checks for the same helper file in "system/helpers" and mistakenly throws an error, because there's no such helper file in the folder.

Any ideas?

**Comment by LouisMilotte** [comment]
what's the file name?

**Comment by osvaldasvalutis** [comment]
This happens on any custom helper.

**Comment by osvaldasvalutis** [comment]
Turns out I had some non-config style code in one of my config files and probably some of the system variables were overwritten. Sorry for the false alarm.
