### ISSUE TITLE
Routing and Cache

### ISSUE THREAD

**Issue by sh1ft-at-github** [bcit-ci/CodeIgniter#4019]
If I use routing like

ex:
$route['(:num)/(:any)'] = "product/view/$1";

http://example/123/Some exam_ple
CI will create a file cache at /123+Some%20exam_ple

Because there are hundreds of possible ids, hundreds of directories will be created. And each one of them would have others cached queries that could be avoided to be created if the cache dir was the  /product+view/

CI shouldn't using controller+action structure be better than route's segment?

**Comment by narfbg** [comment]
What if you have logic based on the route segments?
