### ISSUE TITLE
This is not an issue but need help on how to create empty rows in codeigniter?

### ISSUE THREAD

**Issue by Rajan1992** [bcit-ci/CodeIgniter#4021]
i am using PHP Codeigniter.In this i have a Table Retailer in which i have a field No of Users required by the Retailer. Is it possible that when admin creates the retailer the value he inserted in the field no of users, that much rows must be created in another table User. I just want to create that much empty rows in the user table which are mapped to the retailer id.The users in user table have one field Key which must be the unique key of retailer. I am new to codeigniter and dont have any logic how to do this. 
Controller:
public function edit ($id = NULL)
{
    // Fetch a user or set a new one
    if ($id) {
        $this->data['user'] = $this->reseller_m->get($id);
        count($this->data['user']) || $this->data['errors'][] = 'User could not be found';
    }
    else {
        $this->data['user'] = $this->reseller_m->get_new();
    }

    // Set up the form
    $rules = $this->reseller_m->rules_admin;
    $id || $rules['password']['rules'] .= '|required';
    $this->form_validation->set_rules($rules);

    // Process the form
    if ($this->form_validation->run() == TRUE) {
        $data = $this->reseller_m->array_from_post(array('sip_username','sip_password','key','allocation_block','name','email', 'password','phone','user_num','address','status','country','created','modified','balance'));
        $data['password'] = $this->reseller_m->hash($data['password']);
        $this->reseller_m->save($data, $id);
        redirect('admin/reseller');
    }

    // Load the view
    $this->data['subview'] = 'admin/reseller/edit';
    $this->load->view('admin/_layout_main', $this->data);
}

Model:
public function get_new(){
		$user = new stdClass();

	//			$user->id = '';
		$user->sip_username='';
		$user->sip_password='';
		$user->key='';
		$user->allocation_block='';
		$user->name='';
		$user->email = '';		
		$user->password = '';
		$user->phone=''; 
		$user->user_num=''; 
		$user->address = '';
		$user->status = '';
		$user->country=''; 
		$user->created = '';
		$user->modified	 = '';
		$user->balance = '';
		return $user;
	}

i have a base model where all the CRUD functions live.

**Comment by narfbg** [comment]
We don't provide general help here, ask your questions on the [forums](http://forum.codeigniter.com/) instead.
