### ISSUE TITLE
ReDoS (Regular Expression Denial of Service) / Code Injection Risk

### ISSUE THREAD

**Issue by Calico90** [bcit-ci/CodeIgniter#4023]
The second parameter `$separator` in function `increment_string` in file `system/helpers/string_helper.php` is not properly escaped for use in regular expressions. 

Nevertheless the parameter is injected directly into PHP's `preg_match` function on line 256.
`preg_match('/(.+)'.$separator.'([0-9]+)$/', $str, $match);`

This can cause a Denial of Service (ReDoS) and makes it possible to inject code into the regular expression. When the developer used this `increment_string` with a dynamic (user customizable) string and this string is not properly escaped, code injection is possible and a potentially ReDoS can be caused.

I would recommend to use PHP's `preg_quote` function to mitigate this vulnerability. 
Line 256 in file `system/helpers/string_helper.php` should be:
`preg_match('/(.+)' . preg_quote($separator) . '([0-9]+)$/', $str, $match);`

Also without the use of `preg_quote` it's not possible to call this `increment_string` function with one of the following delimiters ` . \ + * ? [ ^ ] $ ( ) { } = ! < > | : -`

----

This vulnerability seem to exists since CodeIgniter versions 2.1.0 and higher and also applies to stable releases 2.2.0 and 3.0.0.

*When this fix is pushed to the next stable release, I'll request a CVE number for this vulnerability and assign it to this issue on GitHub.* Also I will prepare a pull request for this fix.

*Generic information about ReDoS can be found here:*
- https://en.wikipedia.org/wiki/ReDoS
- https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS

**Comment by Calico90** [comment]
I just submit the pull-request here: https://github.com/bcit-ci/CodeIgniter/pull/4024

**Comment by narfbg** [comment]
@Calico90 

I liked your initial approach in #4020 and appreciate your enthusiasm, so I don't want to appear condescending here, but you're now showing something I very much dislike in (some) security researchers - you're too eager to label anything a vulnerability.

I do consider this a valid bug, most notably because the dash character is a hugely popular separator, but this function (or its separator parameter, to be more specific) was never intended to be used with user input, let alone without validation. Saying that this is any kind of a vulnerability is like saying that `preg_match()` itself is vulnerable and needs a CVE ID assigned ...
Sure, in the hands of a complete idiot, anything can lead to a security flaw, but we assume that our users aren't *that* unreasonable.

In fact, if you believe this to be a vulnerability, you shouldn't have disclosed it in public. :)

Also, you don't need to open an issue first if you intend to submit a pull request - the PR itself can serve for that purpose.

**Comment by Calico90** [comment]
@narfbg Thanks for the feedback. I appreciate the direct approach. "Saying that this is any kind of a vulnerability is like saying that preg_match() itself is vulnerable and needs a CVE ID assigned" is a not really the right comparison since it does affect the parameter of a CodeIgniter function and the parameter itself is obviously injectable. Also I don't like it myself when everything is labeled as a vulnerability but as i mentioned "When the developer used this increment_string with a dynamic (user customizable) string and this string is not properly escaped..." it's applies indeed on a quite custom (maybe unlikely) scenario and that makes it a LOW risk severity in my opinion. 

I'm fine with leaving the CVE on this, altough I think that this actually will classify for a CVE. That the parameter is misused of it's purpose doesn't mean it's not vulnerable. The whole purpose of IT security is doing unexpected stuff to stuff that expects the expected. Anyway, let's forget about the CVE on this one. 

About the public disclosure, since this is an open-source project. This would be the right place in my opinion to discuss such stuff. I'm not aware of another channel to discuss this with the development team, is there? 

*A bit off-topic: A Bug Bounty program on HackerOne could be nice and helpful. Researchers often hack for credits not just for money. On that platform are multiple open-source projects without cash bounties.*

*About the PR, I thought so already just found it out the hard way. Sorry!*

**Comment by narfbg** [comment]
> "Saying that this is any kind of a vulnerability is like saying that preg_match() itself is vulnerable and needs a CVE ID assigned" is a not really the right comparison since it does affect the parameter of a CodeIgniter function and the parameter itself is obviously injectable.

Yes, it's an obviously exaggerated comparison that I made, but I still stand at my rationale behind it. The fact that it's a parameter in a CodeIgniter function doesn't mean anything ... frameworks have primitives too, not everything is to be used with user input and this one is deffinately not.

We do have a private channel - our security@ email is in the readme file (and I just mentioned it to you in the other thread :)); and most open-source projects do, solely for accepting reports on security issues.

No worries on the PR thing, it happens to many.

**Comment by Calico90** [comment]
@narfbg No problem. If you will setup a HackerOne program. I'd like to be part of the team. Keep me posted please.
