### ISSUE TITLE
Nesting does not work

### ISSUE THREAD

**Issue by jklovanc** [bcit-ci/CodeIgniter#4033]
The level of nesting is indicated by the instance variable _trans_depth. It is set in the following three places;
1. Set to zero on initialization.
2. Incremented in trans_start() if _trans_depth is greater than 0.
3. Decremented in trans_complete() if _trans_depth is greater than 1.

How can _trans_depth ever transition from 0 to 1 if it has to be greater than 0 to do the transition?
How can _trans_depth ever get back to zero if it only decrements if it is greater than 1?

**Comment by narfbg** [comment]
Your second point isn't true ...

`trans_start()` will increment *and do nothing else* if depth is already greater than 0, but if it still increments it afterwards if that condition isn't met. See here: https://github.com/bcit-ci/CodeIgniter/blob/4e5ff1f7f8c1897526e9362fdcf7b574c1b3cdf9/system/database/DB_driver.php#L830

**Comment by jklovanc** [comment]
Looks like I insalled an older version. How can I see what version I gave and what is current.

**Comment by narfbg** [comment]
There's a `CI_VERSION` constant that tells you which version you're using and you can follow the releases [here](https://github.com/bcit-ci/CodeIgniter/releases), but the really latest code is always in the develop branch, which is what you browse by default on our repo.

**Comment by jklovanc** [comment]
What do I do about bugs in previous versions. For example, the _trans_dept issue is there in 2.2.3.

Thanks for all your help.

Joe Klovance
Software Engineer
T: 250.472.7644 ext. 110 |  F: 250.472.7664
E: joe@confmanager.com<mailto:joe@confmanager.com>
W: www.confmanager.com<http://www.confmanager.com/>
[Description: Twitter Buttons _ About]<https://twitter.com/ConfManager>

**Comment by narfbg** [comment]
Nothing really, we no longer provide active support for the 2.x version tree. We'd care about security patches for it until October, but it's otherwise abandoned.

You should upgrade to CI3 if you're still using 2.2.3.
