### ISSUE TITLE
Error in Documentation Code snippets.

### ISSUE THREAD

**Issue by ch3nkula** [bcit-ci/CodeIgniter#4034]
/* Author: Alangi Derick */
/* Date: Tue Aug 4, 2015 */
/* Email: alangiderick@gmail.com */
/* CodeIgniter Version: 3.0 */
/* Type: bug */

Description
===========

While going through the News tutorial in the CI documentation, i noticed that there is a problem with a this piece of code;

		<h2><?php echo $title ?></h2>

		<?php foreach ($news as $news_item): ?>

		        <h3><?php echo $news_item['title'] ?></h3>
		        <div class="main">
		                <?php echo $news_item['text'] ?>
		        </div>
		        <p><a href="<?php echo $news_item['slug'] ?>">View article</a></p>

		<?php endforeach ?>

To be specific, the line that has the problem is;

		<p><a href="<?php echo $news_item['slug'] ?>">View article</a></p>

This is because to view an article, the News controller has the view method which takes an argument which is the slug. But looking at the link, if we do;

		echo $news_item['slug'];

we shall see that only the slug is returned and when the link is clicked, CI says page not found and truely page not found because the page;

		http://localhost/CI_Project/index.php/News/[slug] 

does not exist.

- [slug] here is acting as the method and not the argument to the view method in the News class. So the link has to be changed to;

		<p><a href="<?php echo 'view'.$news_item['slug'] ?>">View article</a></p>

since there is a view methos in the News controller and so that we can then have a full URL as;

		http://localhost/CI_Project/index.php/News/view/[slug]

This fixes the problem in the tutorials and please the modifications should be made. It works for me!!!!!!!!

Additional Information
======================

I did the later(corrected link) on my machine and it worked after trying the earlier one and it didn't. So i will like the CI community to look into this tutorial again and then make the modification so as to avoid future confusions in this tutorials.

**Comment by narfbg** [comment]
If it doesn't work, you haven't fully followed the tutorial.

Your proposed modifications assume no custom routes are used, while the tutorial [does use routes](http://www.codeigniter.com/userguide3/tutorial/news_section.html#routing).

**Comment by ch3nkula** [comment]
From the way the tutorials are documented, it shows you can do the task
without route and then when you are done, you can then write the routes to
handle the tasks that was done without the route. Please tell me if i am
making a mistake.

Regards
Alangi Derick Ndimnain

**Comment by ch3nkula** [comment]
If you are talking about routes, then it is not the one you just sent an
link to. It must surely be the route for the static pages tutorial: Static
Pages Tutorial
<http://www.codeigniter.com/userguide3/tutorial/static_pages.html>.

News Section tutorial is a different tutorial all together so it is good to
do the tutorial by putting the full path to the file and then writing the
route if necessary.

Regards
Alangi Derick Ndimnain

**Comment by narfbg** [comment]
I am not talking about the static pages one. The link I gave you points specifically to a "Routing" section *in the "News section" tutorial page*.

And regardless, the two may not be the same document, they are a part of the same tutorial. Not to mention, excluding the new routes would be problematic for users who did the "Static pages" first and then didn't revert all of the changes to config/routes.php.

**Comment by ch3nkula** [comment]
Doing the "News Section" tutorial without the route like that courses a
problem when trying to view a news article pulled from the database and
shown in the index method(index page) in the News Controller.

To better understand what i am saying, just take some few minutes and do
the tutorial and see what happens. Please do it without the route.


Regards
Alangi Derick Ndimnain

**Comment by narfbg** [comment]
I've done the tutorial; you're not even trying to understand what I'm saying.

I know it doesn't work without the routes, you're NOT supposed to skip the routes and that's why there are instructions for that, which I linked.

**Comment by ch3nkula** [comment]
Ok i understand that part now. Thanks and will never skip the route again.

Regards
Alangi Derick Ndimnain
