### ISSUE TITLE
Links in  CI3 User Guide in horizontal "Table of Contents" not working after search is submited

### ISSUE THREAD

**Issue by dsivic** [bcit-ci/CodeIgniter#4043]
Links in  CI3 User Guide in horizontal "Table of Contents" not working after search is submited.
 "user_guide" segment in URL is missing.

**Comment by narfbg** [comment]
Confirmed.

@rufnex @jim-parry IIRC you guys worked together on the horizontal TOC, so I'm linking you. :)

**Comment by jim-parry** [comment]
I can fix this when I get

**Comment by jim-parry** [comment]
oops - accidentally closed it ... ropened.
