### ISSUE TITLE
Delete from multiple tables example in docs doesn't work

### ISSUE THREAD

**Issue by nextexile** [bcit-ci/CodeIgniter#4047]
```php
$tables = array('table1', 'table2', 'table3');
$this->db->where('id', '5');
$this->db->delete($tables);
```

http://www.codeigniter.com/user_guide/database/query_builder.html#deleting-data

The above example, taken directly from the docs, does not work. There is a thread where Narf mentions the "where" clause needs to be passed directly into the delete method when deleting from multiple tables. This example in the docs needs to be changed or CI needs to be changed to make this example valid.

**Comment by narfbg** [comment]
You should've linked that thread where Narf also [links a commit that fixes the issue](http://forum.codeigniter.com/thread-61774-post-320054.html#pid320054) and the fix is already released with CI 3.0.1.
