### ISSUE TITLE
Wrong sqlsrv_rows_affected in sqlsrv_driver.php

### ISSUE THREAD

**Issue by akhmadshaleh** [bcit-ci/CodeIgniter#4048]
In CI 2.X : wrong statment sqlsrv_rows_affected in sqlsrv_driver.php has written sqlrv_rows_affected.

/**
	 * Affected Rows
	 *
	 * @access	public
	 * @return	integer
	 */
	function affected_rows()
	{
		return @sqlrv_rows_affected($this->conn_id);
	}

**Comment by narfbg** [comment]
CI2 only receives security updates now (and until the end of October), no other changes to it are accepted.

https://github.com/bcit-ci/CodeIgniter/blob/2.2-stable/README.md
