### ISSUE TITLE
dbforge is not adding primary keys to mysql when field defined as string (CI 3.0)

### ISSUE THREAD

**Issue by fear025** [bcit-ci/CodeIgniter#4055]
In Codeigniter 3.0, when a field is defined as a string instead of an array, add_key() has no effect.
For example:
$this->dbforge->add_field('my_id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT');
$this->dbforge->add_field('my_string_field VARCHAR(255) NOT NULL');
$this->dbforge->add_key('my_id', TRUE);
$this->dbforge->create_table('my_table');

Generates this result with an error when using MYSQL.
Database error: A Database Error Occurred
        Error Number: 1075
        Incorrect table definition; there can be only one auto column and it must be defined as a key
        CREATE TABLE `my_table` (
        my_id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
        my_string_field VARCHAR(255) NOT NULL
) DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci

This error occurs because the Primary Key was never actually added to the SQL passed to MySQL.

The workaround for this is to always pass the key field as an array, such as this:
$this->dbforge->add_field(array(
	'my_id' => array(
		'type'	=>	'BIGINT',
		'constraint'	=> 20,
		'unsigned'		=> TRUE,
		'auto-increment'	=> TRUE
)));

**Comment by narfbg** [comment]
#3969
