### ISSUE TITLE
A bug in Captcha Helper

### ISSUE THREAD

**Issue by felipepossari** [bcit-ci/CodeIgniter#4058]
The Captcha helper wasn't working on Apache 2.0 (OS Fedora 22 x64).

Problem with the $$key on lines 89 and 91.
89 - $$key = $val;
91 - $$key = isset($data[$key]) ? $data[$key] : $val;

I changed the $$key to ${$key} and the helper worked
89 - ${$key} = $val;
91 - ${$key} = isset($data[$key]) ? $data[$key] : $val;

Could you check it?

**Comment by narfbg** [comment]
There is no difference between `$$key` and `${$key}` whatsoever; it's impossible that your change alters any kind of behavior.
