### ISSUE TITLE
Allow CamelCase on Model names

### ISSUE THREAD

**Issue by jsnoriegam** [bcit-ci/CodeIgniter#4059]
As the title implies... I know the documentation specify that only the first leeter in the model class name should be uppercase, but i don't really see the purpose on that and i don't think model class names need to be that strict.

I've removed the 293th line in core/loader.php lib on my projects and everything looks fine for the moment:

```php
$model = ucfirst(strtolower($model));
```

But maybe that break something somewhere else...

So if this is not against CI philosophy, please consider it.

Thanks.

**Comment by narfbg** [comment]
The question isn't whether they *need* to be that strict, but to have a single, consistent naming convention, i.e. all classes are named in Ucfirst.

`strtolower()` isn't applied to other classes, so I've removed that one.

**Comment by ProfNandaa** [comment]
Sounds good. Code also looks more beautiful with `Your_Model` as opposed to `Your_model`, IMHO. Thanks!

**Comment by vimalmistry** [comment]
I am getting error on linux hosting with model name like LoginModel.php
While in my local xampp its working fine.
note. I am using HMVC extention.

**Comment by jim-parry** [comment]
@vimalmistry That is a feature and not a bug. Your point should have been raised on the forum. The user guide says "Class names must have the first letter capitalized with the rest of the name lowercase."

**Comment by vimalmistry** [comment]
@jim-parry Thanks for reply. I made changes in my all code. Now I am using Login_model.php. :)
