### ISSUE TITLE
Change Form_validation by Validation

### ISSUE THREAD

**Issue by hedcler** [bcit-ci/CodeIgniter#4062]
Make more sense validate data inside model, and it not depend of post data to validate, if used "set_data" method.

What you think about this change?

**Comment by narfbg** [comment]
I don't understand what you mean.

**Comment by hedcler** [comment]
So, the core of you application is your model, and how this model will interact with other models, will make more sense validate all data on a model class, before insert it in database... For me Controllers in web application are handlers, and can control how models will interact, but if you think in responsibilities, the model is the responsible for validate data before save on database, all business rules must be on model...

Can you understand what I mean?

**Comment by narfbg** [comment]
No ...

**Comment by hedcler** [comment]
The class Form_validation make validations from form inputs, but if you has an external file, and it need to be imported from other channel, for example, another host, and you need make the same validations, but the controller will not intercept post data.

I think if the validation is only validation library, not necessarily form_validation, it make more sense.

**Comment by narfbg** [comment]
It's not called "Form Validation" for no reason *and* you can always use `set_data()` if you want to work with anything other than POST - no change is necessary.

**Comment by hedcler** [comment]
If it can be used for other type of validation, it should be called "validation" not "form validation"... 
but ok...
