### ISSUE TITLE
current application constants wouldn't be better in system core?

### ISSUE THREAD

**Issue by xenogenesi** [bcit-ci/CodeIgniter#4063]
Not an issue, just asking, I'm looking a trimmed down version of CI and its bootstrap sequence, the `application/config/constants.php` is one of the first files *needed* and loaded by the core (`core/CodeIgniter.php`), but the defines within looks to me more like *system* defines not *application*, wouldn't be better moving those within the core?

Something like that?

    if (file_exists(APPPATH.'config/'.ENVIRONMENT.'/constants.php'))
    {
    	require_once(APPPATH.'config/'.ENVIRONMENT.'/constants.php');
    }
    
    if (file_exists(APPPATH.'config/constants.php'))
    {
    	require_once(APPPATH.'config/constants.php');
    }
    
    require_once(BASEPATH.'core/Constants.php');

Shouldn't break anything.

**Comment by hedcler** [comment]
I think not, because you can has a shared core...

**Comment by xenogenesi** [comment]
Thanks to the `defined` in the current `config/constants.php` any application would be still able to override with the needed values.

Currently all the applications need to have this file, I wonder how many application really need to change those defines.

**Comment by narfbg** [comment]
Even if they look like system defines, few of these constants are actually used by the framework itself. In fact, I believe only one of them is currently used and it is specifically a configuration one ...

Either way, this would be change for the sake of change, which we don't do.
