### ISSUE TITLE
DIR_WRITE_MODE is should be '0777'?

### ISSUE THREAD

**Issue by yupmin** [bcit-ci/CodeIgniter#4064]
define('FILE_READ_MODE', 0644);
define('FILE_WRITE_MODE', 0666);
define('DIR_READ_MODE', 0755);
define('DIR_WRITE_MODE', 0755); // this line

**Comment by narfbg** [comment]
If anything, `FILE_WRITE_MODE` should be 0644 instead.

It's a config file, change it to whatever you need.
