### ISSUE TITLE
php7 and mssql database driver - mssql extension dropped from php7 core

### ISSUE THREAD

**Issue by hhellbusch** [bcit-ci/CodeIgniter#4074]
I'm not sure if there's plans to support PHP7, but if there is...

The MSSQL extension has been voted out of the core (see https://wiki.php.net/rfc/removal_of_dead_sapis_and_exts).  This means that the mssql database driver will not work with php7.  Other frameworks sql server extension wraps the sqlsrv (for when its running on windows) and dblib (for when its running on linux).  If sql server is to be supported with php7, it appears that this methodology will have to be adopted.

**Comment by narfbg** [comment]
We're aware of this, and it's irrelevant to CI.

**Comment by mwhitneysdsu** [comment]
CI3 already has a sqlsrv driver and a dblib sub-driver for the pdo driver.

**Comment by hhellbusch** [comment]
thanks - i didn't realize it was through the PDO driver.
