### ISSUE TITLE
Force Download IOS and Windows Phone

### ISSUE THREAD

**Issue by PgPedroGabriel** [bcit-ci/CodeIgniter#4076]
I'm using force_download funciton and this guy has same problem then me
http://goobbe.com/questions/657559/iphone-force-download-files

I am trying to allow the user to download a file.

When the file is downloaded it is displayed in the browser window instead of downloading it.

Does anyone know of a way to get the iPhone to download files instead of viewing them.

Also all the code that I have tried works great on Android Devices.

Thanks.

and he take this answer
	
You can't. Apple have deliberately prevented things like this to protect their iOS from hacks and malware; you have no access (unless you are a developer, in which case its restricted) to the handsets integrated data storage.

is truth?

**Comment by jim-parry** [comment]
Ask support questions on our forum ... forum.codeigniter.com
We use github for bug reports.
