### ISSUE TITLE
router default_controller not fallback to parent controller

### ISSUE THREAD

**Issue by andersonunsonst** [bcit-ci/CodeIgniter#4079]
in userguide say:
(in: Step 9: Update your config/routes.php file)

"Now, assuming that your website is located at example.com, you already know that if a user visits http://example.com/, the above setting will cause your ‘Main’ controller to be loaded.

However, what happens if you have an application/controllers/admin/ directory and the user visits http://example.com/admin/? In CodeIgniter 3, the router will look for a ‘Main’ controller under the admin/ directory as well. If not found, it will fallback to the parent (application/controllers/) directory, like in version 2.x."

it's not fallback, it's will produce 404 The page you requested was not found.

how to reproduce:

1- make a empty folder (e.g: admin)
2- put in routes: $route['default_controller'] = 'welcome/teste';
3- try access you-domain/index.php/admin
it's produces error 404 and not fallback to parent controller (application/controllers/)

ps. consider to use that as directory/controlle again it's really, really useful i use since 1.5.2

**Comment by jim-parry** [comment]
note: not clear from the original report, this is part of http://www.codeigniter.com/user_guide/installation/upgrade_300.html?highlight=step

I looked at the core/Router code, and did not see anything that would suggest the behaviour described in the upgrading instructions. Not sure if this a documentation problem or a bug in the Router class.

It sounds like this could be an opportunity for a unit test to prove/disprove the expected behaviour!

**Comment by andersonunsonst** [comment]
it's probably a bug in userguide...i look in core/Router too e not see anything, only a deprecated fetch_directory
but this requires that the controller is always stay in application/controller , and this is strange,
bug in other side the behaviour described in upgrading instructions is much more strange :p 

it's only a suggestion, I believe that this can be a optional where i put my defaut_controller

**Comment by narfbg** [comment]
The description was incorrect, indeed ... it's not even logical to fallback to /Main.php if the request was for /admin/.
