### ISSUE TITLE
HTTP authentications with FCGI Server API

### ISSUE THREAD

**Issue by khaosdoctor** [bcit-ci/CodeIgniter#4080]
HTTP Authentications won't work with FCGI server API because it does not set PHP_AUTH and HTTP_AUTH variables.

A simple workaround I found to this issue is changing .htaccess file and adding the following line:

     RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]

Making it:

```
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
RewriteCond %{SCRIPT_FILENAME} !-f
RewriteCond %{SCRIPT_FILENAME} !-d
RewriteCond $1 !^(index\.php|images|robots\.txt)
RewriteRule ^(.*)$ index.php/$1 [L]
```

However this workaround won't work with Apache 2.0 Server API types.

**Comment by aanbar** [comment]
What does this have to do with CodeIgniter?

**Comment by khaosdoctor** [comment]
.htaccess file is part of the CI package, at least on my distribuiton.
