### ISSUE TITLE
$_SERVER['REQUEST_URI'] Always Empty on IIS

### ISSUE THREAD

**Issue by eisenheimjelid** [bcit-ci/CodeIgniter#4081]
I'm coding a new project with Codeigniter 3.0 in Microsoft Internet Information Services 8.0 (MS IIS 8.0) with PHP 5.4, and i was found an Issue with $_SERVER['REQUEST_URI'] because is always empty, and routing is not functioning properly. After write the proper web.config for rewrite the rules in IIS, Codeigniter always respond $route['default_controller'] config controller. After debugging i did found in URI.php these lines (201):
if ( ! isset($_SERVER['REQUEST_URI'], $_SERVER['SCRIPT_NAME']))
{
	return '';
}
And always occur >> return ''; Codeigniter never received the correctly parameters for routing.  I think this occur on some configuration of the IIS, but i can't modify anything, so after some hours i found this solution:

Line 201:
I write this:
if (isset($_SERVER['QUERY_STRING'])) {
    $_SERVER['REQUEST_URI'] = $_SERVER['QUERY_STRING'];
} else {
    return '';
}
instead this:
return '';

I think this correction is necessary in the code of Codeigniter, for interoperability for other Servers, specially on IIS;  i did test this on Apache and well function, without errors.

**Comment by aanbar** [comment]
There's a setting in application/config/config.php

For this, you don't have to edit the core file manually.
This is an invalid issue.
