### ISSUE TITLE
Parameter Issue When Using PDO and DB2 ODBC With Wildcards

### ISSUE THREAD

**Issue by ilikenwf** [bcit-ci/CodeIgniter#4084]
I am currently using the standard ODBC pdo driver, as I've not really found documentation on using the IBM specific one - I'm not sure if that would make a difference. This type of query works perfectly in vanilla PHP. For both I'm using the IBM connector.

When doing a manual query, I'm running into an issue where the parameters are blanked out and converted to empty ticks.

    $baz = "test%";
    $this->db2->query("SELECT * FROM FOO WHERE BAR LIKE ?;', array($baz));

Translates to:
    SELECT * FROM FOO WHERE BAR LIKE '';

I went as far as testing this using the standard, vanilla PDO within codeigniter and ran into the same issue.

For some reason. Any ideas? Is there an overloaded base php function somewhere causing this, or is it something in the db driver somewhere?

Right now I'm manually escaping the variable because of what appears to be a bug.

**Comment by narfbg** [comment]
Which CI version is this on?

**Comment by ilikenwf** [comment]
The 3.0 stable branch.

**Comment by narfbg** [comment]
Can't reproduce, and the related logic is the same for all database drivers - it doesn't have anything to do with PDO.

I'll reopen if you manage to find the problem and show that it is indeed a CI bug, but that looks unlikely.

**Comment by ilikenwf** [comment]
While I haven't narrowed down the place this error occurs, I know 100% that
vanilla PDO works, so it has to be something inside CI.

Even using the vanilla method of connecting and querying I get this issue,
so I suspect something is being done to my strings somewhere.

Did you test using the single wildcard? I suspect the wildcard is somehow
breaking regex somewhere, or something, causing the entire string to be
wiped out.

**Comment by ilikenwf** [comment]
(fixed a typo above)

**Comment by narfbg** [comment]
> Even using the vanilla method of connecting and querying from within CI I get this issue, so I suspect something is being done to my strings somewhere.

What do you mean by "the vanilla method" here?

> Did you test using the single wildcard? I suspect the wildcard is somehow breaking regex somewhere, or something, causing the entire string to be wiped out.

I've tested with the exact example that you gave in the description, but regardless, the only variable in the regular expressions used in `CI_DB_driver::compile_binds()` is the bind marker (the question mark by default) and it goes through `preg_quote()`, so ...

**Comment by ilikenwf** [comment]
By vanilla, I mean not using any of the CI wrappers or classes and using
the bare PHP PDO library. It works fine as a standalone file, but within CI
I still get the issue.

I wonder if this is because my company's annoying usage of an iSeries and
it's character set are to blame. I would like to get to the bottom of this
eventually, I guess I'll try to figure it out and put in a pull request if
it ends up being CI.

**Comment by narfbg** [comment]
Well, CI couldn't possibly affect vanilla PDO behavior ... it does force the configured application charset to mbstring, iconv and `php.internal_encoding` (a new php.ini setting in PHP 5.6), but I don't see how that could affect database connections, and again - it's configurable.
