### ISSUE TITLE
system/core/URI.php CLI & permitted_uri_chars

### ISSUE THREAD

**Issue by syosoft** [bcit-ci/CodeIgniter#4085]
I ran into an issue where my CLI command:

php-cli index.php 'cli' 'aweberSubscribe' 'subscriber@email.address.com' 'Subscriber name' 'Subscribed when ordering \(BID:2\)'

was causing CI_URI::filter_uri to spit out the "The URI you submitted has disallowed characters". Even when i added \(\) to the $config['permitted_uri_chars'] string, it still triggered it, maybe I added it incorrectly...

However, my point is that I do not believe that CLI should be subject to CI_URI::_permitted_uri_chars. And if someone smarter than me thinks it does, then I think we should add a new config variable that allows us to list which chars are allowed in a CLI request.

The hack I implemented was to move the code found on line 107 of system/core/URI.php 

$this->_permitted_uri_chars = $this->config->item('permitted_uri_chars');

needed to be moved inside the "is not cli" else block. Alternatively, I believe a check for is_cli() inside CI_URI::filter_uri() would do the same.

**Comment by narfbg** [comment]
Agreed that some change is necessary here ... unsure of what exactly.

**Comment by syosoft** [comment]
Ultimately, I removed the hack and overloaded CI_URI::filter_uri. Seems to work fine, but yea, would be nice if core doesn't address this.

<?php defined('BASEPATH') OR die('No direct script access allowed');

class MY_URI extends CI_URI {
	public function __construct() {
		parent::__construct();
	}

	public function filter_uri(&$str)
	{
		if(is_cli()) : 
			return;
		endif;

		return parent::filter_uri($str);
	}
}

/* End of file MY_URI.php */
/* Location: ./application/core/MY_URI.php */

**Comment by feryardiant** [comment]
I also face the same problem here when I try to implementing [Climate](https://github.com/thephpleague/climate). Let say, i've set an argument for my migration lib

```php
$this->climate_lib->arguments->add('to', [
    'prefix' => 't',
    'longPrefix' => 'to',
    'description' => 'Migrate to version',
]);
```

then, I got this

![screenshot from 2015-09-15 05 08 50](https://cloud.githubusercontent.com/assets/508665/9863184/fdfffc1a-5b67-11e5-9b46-e8c670e32874.png)

Firstly I guess it's because of `CI_URI::_permitted_uri_chars`, but unsure yet.

Looking forward on it.
