### ISSUE TITLE
$formdate->year['selected'] not working

### ISSUE THREAD

**Issue by bthulung** [bcit-ci/CodeIgniter#4088]
$formdate->year['selected'] in FormDate library of codeigniter not working

https://github.com/bcit-ci/CodeIgniter/wiki/FormDate

**Comment by jim-parry** [comment]
FormDate is/was a third party tool, developed for a very early version of CodeIgniter.
Any issues with it should be taken up with the author ... this has nothing to do with CodeIgniter itself, thanks.
