### ISSUE TITLE
CSRF Token and Cookie never match

### ISSUE THREAD

**Issue by iamthestreets** [bcit-ci/CodeIgniter#4089]
I have CSRF enabled and it was working without any problems 2 weeks ago and then when I got back from a vacation it stopped working all of a sudden. I believe this to be a bug in Codeigniter 3 as I have not made any changes to my code.

The hidden field is being generated with a token in the value and a cookie is also being created but they do not match.

How can i get this resolved?

**Comment by narfbg** [comment]
Please ask such questions on the [forums](http://forum.codeigniter.com/) ... we don't provide general support here.
