### ISSUE TITLE
Documentation should suggest overriding native form validation messages in application/language instead of system/language 

### ISSUE THREAD

**Issue by ZhangYiJiang** [bcit-ci/CodeIgniter#4095]
Reading through the documentation for the form validation class, I found the following line: 

> All of the native error messages are located in the following language file: `system/language/english/form_validation_lang.php` 

> To set your own global custom message for a rule, you can either **edit that file**, or use the following method 

(emphasis mine) 

This seems dangerous, because upgrading will cause the changes to be wiped. It seems much safer to suggest the user to create an application language file, which, if I'm reading the language class documentation correctly, will override the system defined string, though I've not had the time to actually test this yet

**Comment by narfbg** [comment]
Good catch, thanks!
