### ISSUE TITLE
CI Query Builder WHERE doesn't add table prefix

### ISSUE THREAD

**Issue by blasto333** [bcit-ci/CodeIgniter#4096]
CODE:
		$this->db->select('categories.name as category, SUM(expense_amount) as amount', false);
		$this->db->from('expenses');
		$this->db->join('categories', 'categories.id = expenses.category_id','left');
		$this->db->where('expenses.deleted', 0);
		$this->db->group_by('categories.id');
		$this->db->where('expenses.expense_date BETWEEN '. $this->db->escape($this->params['date']). ' and '. $this->db->escape($this->params['date']. ' 23:59:59').' and location_id IN('.$location_ids_string.')');
		$this->db->order_by('expenses.id');

PRODUCES:

    SELECT phppos_categories.name as category, SUM(expense_amount) as amount 
    FROM `phppos_expenses` 
    LEFT JOIN `phppos_categories` ON `phppos_categories`.`id` = `phppos_expenses`.`category_id`
    WHERE `phppos_expenses`.`deleted` =0 AND expenses.expense_date BETWEEN '2015-09-02' and '2015-09-02 23:59:59' and `location_id` IN(1) GROUP BY `phppos_categories`.`id` ORDER BY `phppos_expenses`.`id`

NOTE that expenses.expense_date does NOT have table prefix. NOTE: I reported a similar bug with like queries....This needs to be looked at for all cases as this is not working correctly.

**Comment by narfbg** [comment]
For future reference, please link similar bugs when you know that they exist ... #4086.

Also, `like()` results in a WHERE condition and this is a compilation time issue ... it's neither a `where()` bug nor a `like()` bug, but one of proper operator detection. In this case, BETWEEN is the operator, while in the previous one it was LIKE.
