### ISSUE TITLE
When `sess_match_ip` is enabled, moving to a new IP address causes an error

### ISSUE THREAD

**Issue by natesilva** [bcit-ci/CodeIgniter#4102]
→ Yes, I have read the manual and enabled the additional `UNIQUE` index described there!

In `Session_database_driver.php`, in the `read()`, method, the logic to determine if the row exists seems wrong.

The query looks like this:

```php
$this->_db
	->select('data')
	->from($this->_config['save_path'])
	->where('id', $session_id);

if ($this->_config['match_ip'])
{
	$this->_db->where('ip_address', $_SERVER['REMOTE_ADDR']);
}	
```

So, if `match_ip` is enabled, this looks for a row where both `id` and `ip_address` match.

But the table definition (from <http://www.codeigniter.com/user_guide/libraries/sessions.html#database-driver>) has `id` as a primary key.

Thus there could *never* be two rows for a given `id` with different `ip_address`es.

That means the suggested constraint:

`ALTER TABLE ci_sessions ADD CONSTRAINT ci_sessions_id_ip UNIQUE (id, ip_address);`

…has no practical effect, because `id` must be unique anyway.

### Workaround

Something that works, and what I think the documentation may have been trying to say, is **changing the primary key** from `id` to `(id, ip_address)` if you plan to use `sess_match_ip`.

**Comment by narfbg** [comment]
8 days ago: 20573bd472bdeaa831074e563f239585554ffaf5
