### ISSUE TITLE
Call to a member function real_escape_string() on a non-object

### ISSUE THREAD

**Issue by wenpeng** [bcit-ci/CodeIgniter#4103]
After db->reconnect()

Fatal error: Call to a member function real_escape_string() on a non-object in E:\Wamp\vhosts\spider\system\framework\database\drivers\mysqli\mysqli_driver.php on line 374

Call Stack:
    0.0009     138768   1. {main}() E:\Wamp\vhosts\spider\index.php:0
    0.0482     183984   2. require_once('E:\Wamp\vhosts\spider\system\framework\core\CodeIgniter.php') E:\Wamp\vhosts\spider\index.php:292
    0.5466     981168   3. call_user_func_array:{E:\Wamp\vhosts\spider\system\framework\core\CodeIgniter.php:514}() E:\Wamp\vhosts\spider\system\framework\core\CodeIgniter.php:514
    0.5467     981392   4. Home->index() E:\Wamp\vhosts\spider\system\framework\core\CodeIgniter.php:514
  420.7509    2100168   5. Site_spider->start() E:\Wamp\vhosts\spider\system\controllers\Home.php:27
  426.5860    2108696   6. CI_DB_query_builder->insert() E:\Wamp\vhosts\spider\system\models\Site_spider.php:54
  426.5860    2108776   7. CI_DB_query_builder->set() E:\Wamp\vhosts\spider\system\framework\database\DB_query_builder.php:1607
  426.5862    2109600   8. CI_DB_driver->escape() E:\Wamp\vhosts\spider\system\framework\database\DB_query_builder.php:1296
  426.5863    2109600   9. CI_DB_driver->escape_str() E:\Wamp\vhosts\spider\system\framework\database\DB_driver.php:1026
  426.5863    2109632  10. CI_DB_mysqli_driver->_escape_str() E:\Wamp\vhosts\spider\system\framework\database\DB_driver.php:1061

A PHP Error was encountered

Severity:    Error
Message:     Call to a member function real_escape_string() on a non-object
Filename:    E:\Wamp\vhosts\spider\system\framework\database\drivers\mysqli\mysqli_driver.php
Line Number: 374

Backtrace:

It occurs occasionally. How to fix it?

**Comment by narfbg** [comment]
This is what ... your 10th issue/PR here? You should've learned by now that we don't answer "how to fix" questions; ask them on the [forums](http://forum.codeigniter.com/).
