### ISSUE TITLE
load library upload in sub folder

### ISSUE THREAD

**Issue by languorous001** [bcit-ci/CodeIgniter#4110]
i try to use upload library in controller on sub folder

load in construct
```php
public function __construct() {
    parent::__construct();
    $this->load->library('upload');
}
```

load in function
```php
public function uploadLandingPage () {
                $this->load->library('upload');
		$landingName = $this->input->post('landingName');

		$config['upload_path'] = './assets/';
		$config['allowed_types'] = 'jpg|png';
		$this->upload->initialize($config);

		$this->upload->do_upload('file');
}
```

load in construct and function it not work. and error 500 (Internal Server Error)

and i try to load in autoload.php is work :")

i not sure is a bug but i try to help.

**Comment by narfbg** [comment]
Post this on the [forums](http://forum.codeigniter.com/), not here. 9 times out of 10, when you're not sure if it's a bug - it's not.
