### ISSUE TITLE
function &get_instance(){}

### ISSUE THREAD

**Issue by HakureiMarisa** [bcit-ci/CodeIgniter#4111]
return CI_Controller::get_instance(); 
or
return &CI_Controller::get_instance();

**Comment by narfbg** [comment]
Or at least try to be clear.

**Comment by HakureiMarisa** [comment]
As the doc described at http://www.codeigniter.com/user_guide/general/creating_libraries.html
![1](https://cloud.githubusercontent.com/assets/7353277/9845335/b0f1146a-5afc-11e5-9a2e-51ede90a341e.png)

However, in my opinion,  to reference the original CodeIgniter object, the function `get_instance` 
should be defined as 

    return &CI_Controller::get_instance();

instead of

    return CI_Controller::get_instance();

And, I notice that in CI3.0 it doesn't use `&` as it declared, e.g. in line 69 , `system/database/DB.php` 

    foreach (get_instance()->load->get_package_paths() as $path)

I'm really ashamed with my poor English,  I hope  I have described my question clearly. Thanks!

**Comment by narfbg** [comment]
If you tried to declare a function that way, you'd see that this would be a syntax error: https://3v4l.org/eLAu4

Please don't ask such questions here ... it's a bug tracker, not a forum board. And if you want to improve something, test and verify it first.

**Comment by HakureiMarisa** [comment]
ah, I see. And thank you for your guidance.
