### ISSUE TITLE
load model but session error

### ISSUE THREAD

**Issue by languorous001** [bcit-ci/CodeIgniter#4112]
i load model here
```php
public function __construct() {
	parent::__construct();
	$this->load->model('backend/Landingexpress_model', 'Landingexpress_model');
}
```
i autoload session on database and error "Unable to locate the specified class: Session.php"
i delete load model my app is work

**Comment by narfbg** [comment]
Post your question on the [forums](http://forum.codeigniter.com/) please, this is a bug tracker.
