### ISSUE TITLE
Modernisation

### ISSUE THREAD

**Issue by delboy1978uk** [bcit-ci/CodeIgniter#4113]
I was quite excited just there when I saw Codeigniter 3, only to be quite disappointed. The code looks like it was written 5 years ago! 
Will we ever use Composer? Or have PSR compliant code? Or even just some namespacing? 
It would be great to be able to use packages from Packagist

**Comment by jim-parry** [comment]
Questions & opinions should be raised on forum.codeigniter.com
Github is used for bug tracking.
Your questions have been addressed there ... there is nothing to prevent developers from using those in their code, and some of that may make it into CI4.
