### ISSUE TITLE
data-ci-pagination-page is incorrect for "First" page when "< First" link is shown

### ISSUE THREAD

**Issue by blasto333** [bcit-ci/CodeIgniter#4116]
<div class="pagination hidden-print alternate text-center categories">
When using pagination library the html produced for data-ci-pagination-page incorrect for the "<  First" link is incorrect. It should be 0 when it shows 1.

Here is the html

    <a href="http://phppos/index.php/sales/categories/0" data-ci-pagination-page="1" rel="start">‹ First</a>

    <a href="http://phppos/index.php/sales/categories/0/8" data-ci-pagination-page="8" rel="prev">&lt;</a>

    <a href="http://phppos/index.php/sales/categories/0/7" data-ci-pagination-page="7">8</a>

    <a href="http://phppos/index.php/sales/categories/0/8" data-ci-pagination-page="8">9</a>    <strong>10</strong>
</div>

**Comment by narfbg** [comment]
How is 1 for *first* page incorrect?

**Comment by blasto333** [comment]
It appears to me data variable is not a page number bût an offset. If you look at html you will see the first one doesn't match what is in the URL and all the others do.

**Comment by feryardiant** [comment]
I had same problem here

**Comment by narfbg** [comment]
Well ... it's wrong that it's currently an offset, it shouldn't be. The "First" link is actually the only one with a correct value.

**Comment by blasto333** [comment]
I think it makes sense to be an offset front a front end perspective so you
know how to send requests to the server if you aren't using URL directly.
It should have both page and offset

--
Chris Muench
Sent from my iPhone

On Sep 16, 2015, at 5:30 AM, Andrey Andreev <notifications@github.com>
wrote:

Well ... it's wrong that it's currently an offset, it shouldn't be. The
"First" link is actually the only one with a correct value.

—
Reply to this email directly or view it on GitHub
<https://github.com/bcit-ci/CodeIgniter/issues/4116#issuecomment-140684875>.

**Comment by narfbg** [comment]
It's not a random attribute that you arbitrarily decide how to use ... it's there to tell JS libraries what the page number is.

**Comment by blasto333** [comment]
I didn't know what it was for and based on the data I saw I thought it was
for the current offset.

--
Chris Muench
Sent from my iPhone

On Sep 16, 2015, at 7:00 AM, Andrey Andreev <notifications@github.com>
wrote:

It's not a random attribute that you arbitrarily decide how to use ... it's
there to tell JS libraries what the page number is.

—
Reply to this email directly or view it on GitHub
<https://github.com/bcit-ci/CodeIgniter/issues/4116#issuecomment-140706891>.
