### ISSUE TITLE
Get database error with db_debug = false on MSSQL always return no error

### ISSUE THREAD

**Issue by andrejflorjancic** [bcit-ci/CodeIgniter#4120]
I use mssql database driver with db_debug set to false. If insert, update, ... return false, call to $db->error() returns always no error.

Can you repair this or just add to system/database/DB_driver public property _last_error and change next lines:

```
public function query($sql, $binds = FALSE, $return_object = NULL)
.....
// Grab the error now, as we might run some additional queries before displaying the error
$error = $this->error();
/* suggestion */
$this->_last_error = $error;
......
```

**Comment by narfbg** [comment]
I don't think *db_debug* has any effect on this ...
Which CI version are you talking about here?

**Comment by andrejflorjancic** [comment]
3.0.1

**Comment by narfbg** [comment]
OK ... can you give an example of this? Like, a failed query that you execute and the *exact* `var_dump($this->db->error())` output.

**Comment by andrejflorjancic** [comment]
$this->db->db_debug = false;
if (!$this->db->insert('table', ["field"=>"value"]))
var_dump($this->db->error());

returns on duplicate value this:
*array* *(size=2)*

  'code' => int 0
  'message' => string '' *(length=0)*


If you use SQL Server 2008 you can read error only once. So if you check DB
driver mssql_driver.php where function executes "SELECT @@ERROR AS code",
you will get zero on second attempt..

**Comment by narfbg** [comment]
That should do it.

**Comment by andrejflorjancic** [comment]
If I understand you correctly, the behavior of function error() is correct.
If so I don't understand how to intercept error code? With try / catch?

**Comment by narfbg** [comment]
There's a commit referenced right above my last comment ...

**Comment by andrejflorjancic** [comment]
Sorry.
