### ISSUE TITLE
DB class trouble with pcntl

### ISSUE THREAD

**Issue by beg163** [bcit-ci/CodeIgniter#4121]
hello, when I use DB class after pcntl_fork, there will be a Error: "2006 mysql server has gone away". Only the first sql can be executed successly. I think CI will close all mysql connections after execute any one sql. I tried "$this->db->db_connect();$this->db->query();$this->db->close();" and "$this->db->reconnect()", but both didn't work. At last ,I have to new Mysqli to finish it . So ,how to write this code in CI's case? thank you.

**Comment by narfbg** [comment]
This is just due to how the pcntl extension works, it's not CI's fault.

And we don't answer general help/support questions here ... please ask on the [forums](http://forum.codeigniter.com/) instead.
