### ISSUE TITLE
QueryBuilder missing OrderBy on Delete

### ISSUE THREAD

**Issue by aanbar** [bcit-ci/CodeIgniter#4122]
I was trying to delete with order by, but it seems that "$this->_compile_order_by()" wasn't included when generating the delete statement in query builder.

I know this applies to MySQL; I have no idea if other engines support this or not.

**Comment by narfbg** [comment]
PostrgreSQL and MSSQL don't support it (didn't bother checking others), and those are the next two most popular platforms, so ... no, won't happen.
