### ISSUE TITLE
Php join query variable declaration

### ISSUE THREAD

**Issue by y060121** [bcit-ci/CodeIgniter#4133]
Hai this is my join query in codeigniter, can we use a php variable inside joins for matching two ids?
The below code is not executing, the problemis '$val' can we declare a variable inside join?

$this->db->join("IHHT_Registration ihht","ihht.Ihht_id='$val'","left");

**Comment by narfbg** [comment]
Ask your questions on the [forums](http://forum.codeigniter.com/) please, this is a bug tracker.
