### ISSUE TITLE
Exception handler in PHP7

### ISSUE THREAD

**Issue by Nibbler999** [bcit-ci/CodeIgniter#4137]
set_exception_handler() changed behaviour in PHP7: https://secure.php.net/set_exception_handler - this breaks CI error display. You get the following error instead of the actual error:

    A PHP Error was encountered

    Severity: Error

    Message: Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in /var/www/html/system/core/Common.php on line 662 and defined in /var/www/html/system/core/Exceptions.php:190 Stack trace: #0 /var/www/html/system/core/Common.php(662): CI_Exceptions->show_exception(Object(Error)) #1 [internal function]: _exception_handler(Object(Error)) #2 {main} thrown

    Filename: core/Exceptions.php

    Line Number: 190

    Backtrace:

**Comment by arisdario** [comment]
Is there a fix for this?

**Comment by narfbg** [comment]
Do you not see the event log, which includes a commit with the fix?

**Comment by arisdario** [comment]
Yes, sorry my mistake, i see the #4137 , Thanks

**Comment by SinghOmkar** [comment]
code working fine on one system and generating the error on another.
I tried(#4137) but still getting the same error, changes in #4137 not working.
