### ISSUE TITLE
Use of fetchAll to count rows in PDO driver makes all queries return no results.

### ISSUE THREAD

**Issue by fdjohnston** [bcit-ci/CodeIgniter#4138]
Just noticed this issue after upgrading to CI 2.2.4.
After the upgrade I was unable to store any data in the session, and after a bunch of debugging I traced the issue back to changes made to the pdo_driver.php file.

In particular, these lines (beginning at 195):
```(php)
if (is_object($result_id) && $result_id->execute())
{
	if (is_numeric(stripos($sql, 'SELECT')))
	{
		$this->affect_rows = count($result_id->fetchAll());
	}
	else
	{
		$this->affect_rows = $result_id->rowCount();
	}
}
```

The line:

```(php)
$this->affect_rows = count($result_id->fetchAll());
```
will cause all PDO queries to return zero rows when ->row() is called later on.  You cannot make multiple calls to fetchAll().  All subsequent calls on the same PDOStatement object will return an empty array.  So, using it to grab the number of affected rows is kind of silly, since this guarantees that we will never get any actual results back.

I will be submitting a pull request to address this issue shortly.

**Comment by narfbg** [comment]
PDO in CI2 was experimental and is broken beyond repair. In addition, the 2.x version tree only accepts security patches now and will be discontinued after October 31st, so no use in trying to fix this.

**Comment by fdjohnston** [comment]
I disagree that it is broken beyond repair.  In fact, I use it quite successfully on a number of projects with only a few minor patches.

Good to know that it will be discontinued after Oct 31.  

I'll put my fix in this ticket rather than a pull request, just so anyone else who runs across this issue can see a potential fix:
Simply replace this:

```(php)
if (is_numeric(stripos($sql, 'SELECT')))
{
	$this->affect_rows = count($result_id->fetchAll());
}
else
{
	$this->affect_rows = $result_id->rowCount();
}
```

With this:
```(php)
if (is_numeric(stripos($sql, 'SELECT')))
{
	$this->affect_rows = count($result_id->fetchAll());
	$result_id->execute();
}
else
{
	$this->affect_rows = $result_id->rowCount();
}
```

And you're off to the races.  I realize that this is effectively running every select query twice, which is not ideal.  But this was the state of the PDO driver before the latest series of patches.

A better solution might be:
```(php)
if (!is_numeric(stripos($sql, 'SELECT')))
{
	$this->affect_rows = $result_id->rowCount();
}
```

As setting affected_rows really doesn't seem to have any affect on how things work, but I'm not entirely sure what other side effects that might have.

**Comment by fdjohnston** [comment]
Upon further reflection, the PDO driver worked just fine in CI 2.1.4, and is completely broken in 2.2.4.

It was this commit:
https://github.com/bcit-ci/CodeIgniter/commit/f97c6eddff171101c10723f8701d5b5a3554d124

That broke it completely.
It seems to me the decent thing to do would be to fix it for anyone who might still be trying to use CI 2*

**Comment by narfbg** [comment]
It may be fixable for your particular case, but not as a general solution that works for everybody. The commit that you referenced is an example of that - fixing one issue just causes another one to appear.
