### ISSUE TITLE
Cant access to libraries in MY_Model

### ISSUE THREAD

**Issue by scion4581** [bcit-ci/CodeIgniter#4139]
hi! I am using version CI 2.1.4. I face with problem that when i want access to some library in MY_Model that extends CI_Model I just get error like 

A PHP Error was encountered

Severity: Notice

Message: Undefined property: Register::$ion_auth

Filename: core/Model.php

Line Number: 51

Here in MY_Model constructor I want find out if user is logged with Ben Edmunds library Ion_auth.

Must to say that reason not in Ion_library. Here link to forum post where this trouble was disscused but 
solution was not found http://forum.codeigniter.com/archive/index.php?thread-40844-1.html

**Comment by jim-parry** [comment]
This is a support issue, and should be raised on http://forum.codeigniter.com/

Github is for CI3.x bugs, and we are only doing security updates for CI2.x now.
