### ISSUE TITLE
Internationalisation Enhancement(some possible language translation expansions)

### ISSUE THREAD

**Issue by zhanghongyi** [bcit-ci/CodeIgniter#4140]
When I went through libraries and helper functions,  I found some show_error() messages are not translated yet. I am trying to make a list of possible enhancements here, so that developers can pull requests once it is confirmed that they need to support the language feature.

1. path_helper.php
   * line 66: `show_error('The path you submitted must be a local server path, not a URL');`
   * line 76: `show_error('Not a valid path: '.$path);`
2. Encrypt.php
   * line 127: `show_error('In order to use the encryption class requires that you set an encryption key in your config file.');`
3. Pagination.php
   * line 422: `show_error('Your number of links must be a non-negative number.');`
4. Xmlrpc.php
   * line 42: `show_error('Your PHP installation does not support XML');`
5. Xmlrpc.php
   * line 42: `show_error('Your PHP installation does not support XML');`
   * line 47: `show_error('You must load the Xmlrpc class before loading the Xmlrpcs class in order to create a server.');`

This list might be incomplete and some of them may not need to be translated, or all of them...Your comments are really appreciated.

**Comment by narfbg** [comment]
Not only did I give *you* an answer to this already, [4 days ago](https://github.com/bcit-ci/CodeIgniter/pull/4124#issuecomment-141946639), but it's also the second time I reject an idea of yours and you follow that up with a second issue opened.

If you're trying to annoy me, you're doing a fine job.

**Comment by vkeranov** [comment]
Same as: https://github.com/bcit-ci/CodeIgniter/pull/4124

**Comment by zhanghongyi** [comment]
Sorry @narfbg, I did not mean to annoy you. I did not get that all show_error() messages are fatal and should not be translated at the first time. Because I do see some show_error() messages being translated, I misunderstood your reply that because they are in the construction function thus fatal, they should not be translated. 

Sorry for the troubles that I am making. Please forgive my ignorance...
