### ISSUE TITLE
Controller Multiple Directory Levels (on default_controller)

### ISSUE THREAD

**Issue by timothymarois** [bcit-ci/CodeIgniter#4142]
Multiple directory controller levels work, until you use it as the `$route['default_controller']`

Example: 
`$route['default_controller']   = 'page/home';`
This sends back "The page you requested was not found." 

Directory setup: /controllers/page/Home.php

In the url, if you go to /page/home/index or /page/home (both work perfectly), the issue only appears to not function as expected when using the default_controller within a multi-level directory setup, like going to the base url " / ", it doesnt know how to get into the default controller.

**Comment by narfbg** [comment]
It does work as expected and this is explained in the user guide and "reported" here YESTERDAY for the 20th fucking time!

Does nobody ever read documentation?

**Comment by timothymarois** [comment]
I'm not saying that `$route['default_controller']` doesn't work, I'm saying it does not work "as expected" when using routing to a sub-directory as the default controller. 

These do not describe how to use sub-directories within the default controller, when you are located on the base url, they only describe the use of default_controller when your url is specified with directories.  
http://www.codeigniter.com/user_guide/general/controllers.html#defining-a-default-controller
http://www.codeigniter.com/user_guide/general/controllers.html#organizing-your-controllers-into-sub-directories

Maybe I am missing something, or the documentation isn't clear. But as of the code, `default_controller` isn't working like the rest of the routing on the base url.

If you could please, kindly link the documentation that specifies the specific configuration I would need to have the `default_controller` work within sub-directories just like the normal routes do, that would be great. Thank you. 



**Example:** 
If I have controller directory setup like this:
controllers/page/home
controllers/home

If I go to the URL of `/home` or `/page/home`, I see the results of each controller
if I go to the base URL of the domain `/`, the default_controller takes over, 
if the default_controller is setup for `home` it shows me the `controllers/home`
if the default_controller is setup for `page/home` it shows me `404`

**Comment by narfbg** [comment]
Yea, I didn't misunderstand what you're saying.

I'd link as you asked, if I wasn't on my mobile right now, but I can tell you this as a fact: the very same document that *you linked* has never suggested that you could use a directory as part of the default_controller.

The only officially documented variation has always been **controller/method**, the fact that directories have ever worked in pre-3.0 versions was a bug and even despite it being a bug, it is explicitly mentioned (fairly detailed even) in the 3.0.0 upgrade instructions. I am literally explaining this for at least the 50th time in public.

Despite all that, somebody always argues that it doesn't work as expected. **It does!**

**Comment by timothymarois** [comment]
Okay thanks for the explanation, I found the upgrade information here
http://www.codeigniter.com/user_guide/installation/upgrade_300.html
that describes the bug you are talking about, and that default_controller is not meant to have directory functionality. I think I was used to using it from a past project when I used the pre-release version of 3. 

Thanks again!

**Comment by narfbg** [comment]
Improved the docs: ee2ece8f59338087cef911073d16b2ee407a31bb

Also, marking this as yet another duplicate of #2849.
