### ISSUE TITLE
XML-RPC localization

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/CodeIgniter#4146]
Looking at libraries/xmlrpc, I see that it has a show_error early on, which should be left alone, but then a number of subsequent error mesages that could profit from localization with language settings. It looks like the XML_RPC_Response messages make good candidates for localization, but the error codes need to be preserved because they are part of the XML response.

Does this sound worthy?

@zhanghongyi You were proposing some language settings enhancements earlier; if this issue is deemed deserving, it could be a good one for you to tackle :)

**Comment by zhanghongyi** [comment]
@jim-parry Thanks for pinging me. Your idea suggests a better candidate for localization than mine. If this sounds a worthwhile thing to do, I am always willing to help :)

**Comment by narfbg** [comment]
Surely a better candidate than @zhanghongyi's suggestions so far, indeed.

Still, translated error messages are supposed to be such that may end up being displayed to end users and I'd argue this isn't the case here. We're talking about a communication protocol that and end user shouldn't even know that you're using XML-RPC in the first place.

**Comment by jim-parry** [comment]
True ... but would the same not apply to the FTP language settings?
Applying language settings inside the XMLRPC libraries would clean them up, improving readability.
Just a thought :-/

**Comment by narfbg** [comment]
Yep, same goes for FTP.

Do you mean that the FTP library has translated error messages? Those haven't been introduced on my watch. :D

**Comment by jim-parry** [comment]
The FTP library does have translated error messages, yes.
Consistency would suggest they be treated the same, either removing that from the FTP library, or introducing it to the XMLRPC libraries.

**Comment by narfbg** [comment]
Well, you know my stance on obsession with consistency, but if I had to choose between the two, I'd remove the translations from `CI_FTP`.

**Comment by jim-parry** [comment]
I have raised a question on the forum to try to gauge the usage level and interest in this amongst the community. They might not even care, in which it can wait for later :)

**Comment by narfbg** [comment]
Linking the forum thread here: http://forum.codeigniter.com/thread-63173.html

However, I'd expect either no replies at all or "sure, we always want more stuff" kind of posts, which isn't really useful feedback. :/

**Comment by jim-parry** [comment]
I agree ... we'll see if anyone cares about the issue one way or the other :-/
