### ISSUE TITLE
urlencoded parameters should get decoded

### ISSUE THREAD

**Issue by KN4CK3R** [bcit-ci/CodeIgniter#4147]
```
class Test extends CI_Controller
{
	public function index($param = '')
	{
		var_dump($param);
		var_dump(urldecode($param));
	}
}
```
Call it with http://.../test/index/ö or http://.../test/index/%C3%B6 (every browser should call the encoded one and most display the decoded one) and you will get the output:
```
string '%C3%B6' (length=6)
string 'ö' (length=2)
```
I would expect to get the 'ö' directly. Currently CI forces me to manually urldecode every string parameter that could contain a special character.

**Comment by narfbg** [comment]
Can't happen, has been discussed here: #3593
