### ISSUE TITLE
SQL_CALC_FOUND_ROWS and offset / limit usage using Active Record

### ISSUE THREAD

**Issue by web-fu** [bcit-ci/CodeIgniter#4150]
Hi,
I want to notify a problem if you use a SELECT SQL_CALC_FOUND_ROWS and offset / limit using Active Record.

my_table is a table with more than 50 rows. For example 100

$this->db->select('SQL_CALC_FOUND_ROWS *', false);
$this->db->from('my_table');
$this->db->offset(0);
$this->db->limit(50);

$query = $this->db->get();
$result = $query->result(); //first 50 records
$total = $this->db->query("SELECT FOUND_ROWS() AS count")->row('count');  //return 50! Should be 100

The error is in system/database/drivers/mysql/mysql_driver.php

function _limit($sql, $limit, $offset)
	{
		if ($offset == 0)
		{
			$offset = '';
		}
		else
		{
			$offset .= ", ";
		}

		return $sql."LIMIT ".$offset.$limit;
	}

should be:

function _limit($sql, $limit, $offset)
	{
		return $sql . "LIMIT " . $offset . "," . $limit;
	}

**Comment by narfbg** [comment]
There's nothing wrong with that `_limit()` code and we don't accept non-security reports about CI 2.x anymore anyway.
