### ISSUE TITLE
Form validation callback function in helpers

### ISSUE THREAD

**Issue by vladkazantsev** [bcit-ci/CodeIgniter#4156]
Validating common things like dates submitted in a form across a large application would be easier if the callback function could leave in helpers. Currently a callback function is not recognized if stored in a helper file, but works if moved direct into the controller that does validation.

**Comment by narfbg** [comment]
There was an off-topic discussion on #3904 related to this. You can read it to get the details, but TL;DR: a callback and a regular function are different things.
