### ISSUE TITLE
Unable to locate specified file: Session.php

### ISSUE THREAD

**Issue by kirikoy** [bcit-ci/CodeIgniter#4157]
Tried, using the $autoload['drivers'] = array('session'); and $autoload['libraries'] = array('session'); nothing works. I inspected the system files, inside the libraries folder, the Session.php file is located inside a Session folder. Any solution for this?

**Comment by jim-parry** [comment]
This is a support issue, and not a bug. It should be raised on forum.codeigniter.com, thanks.
I don't have a specific link, but this question has come up several times.

**Comment by narfbg** [comment]
Duplicate of #3480.
