### ISSUE TITLE
Database- SaveOrUpdate

### ISSUE THREAD

**Issue by Varun-garg** [bcit-ci/CodeIgniter#4158]
We cannot do create or update with same code, for example a form is updated, we have to check if record exists with a particular id, then update it.

	function add_profile($data,$id) 
	{
	   $this->db->where('user_id',$id);
	   $q = $this->db->get('profile');

	   if ( $q->num_rows() > 0 ) 
	   {
	      $this->db->where('user_id',$id);
	      $this->db->update('profile',$data);
	   } else {
	      $this->db->set('user_id', $id);
	      $this->db->insert('profile',$data);
	   }
	}

I am using hibernate framework too. It allows to do this simply with its SaveOrUpdate function, which checks if record with same primary key exists and then updates it, otherwise inserts it. It would save a lot of time and code if this is available in CI.

**Comment by narfbg** [comment]
Yes you can; you just don't know how.

Please post such things on the [forums](http://forum.codeigniter.com/) and not here.
