### ISSUE TITLE
CI3 register_shutdown_function prevents other shutdown functions from being called

### ISSUE THREAD

**Issue by b-hobbs** [bcit-ci/CodeIgniter#4160]
Codeigniter's register_shutdown_function() is preventing my shutdown function from being called because the register function in core/Codeignter.php exits at the very end of _error_handler in Common:php line 636. Not sure if there is an intended way for custom shutdown function to be added but I add mine as a pre_system hook which isn't added to the shutdown queue until after Codeigniter's. 

From php doc (http://php.net/manual/en/function.register-shutdown-function.php):
>Multiple calls to register_shutdown_function() can be made, and each will be called in the same order >as they were registered. If you call exit() within one registered shutdown function, processing will stop >completely and no other registered shutdown functions will be called.

**Comment by narfbg** [comment]
`_shutdown_function()` calls `_error_handler()`, which only exits when a fatal error is detected ... just as PHP normally behaves.

Are you saying that you want your own shutdown handler to execute something in that particular case? I'm not sure if that's a safe thing to do.

**Comment by b-hobbs** [comment]
Yes, my shutdown function logs the fatal error and sends an email report.

**Comment by narfbg** [comment]
Fatal error are already being logged ... you can either extend `CI_Exception::log_exception()` to send an email with that, or just register your shutdown function in index.php.
