### ISSUE TITLE
Undocumented/Uninteded behaviour in URI parsing

### ISSUE THREAD

**Issue by druu** [bcit-ci/CodeIgniter#4169]
Assume this simple test-controller:
```php
class Home extends CI_Controller {
    public function test($p) {
        var_dump($p); die();
    }
}
```

When visiting the url `example.com/home/test/what is happening` you get the following outputs when `uri_protocol` is set to `AUTO`:

CI 2.x: `string 'what is happening' (length=17)`
CI 3.x: `string 'what%20is%20happening' (length=21)`

I would expect it to behave like CI 2.x's handling, but in fact you have to set the `uri_protocol` to `PATH_INFO`.

Now this is either missing in the Docs/Upgrade Guides, or an actual error in https://github.com/bcit-ci/CodeIgniter/blob/3.0-stable/system/core/URI.php#L119-L134

Last known working version: CI 3.0.0-rc1

**Comment by aanbar** [comment]
This was discussed in #3593 And was changed then

**Comment by druu** [comment]
Ah okay thanks for the heads up!

As @narfbg said `Also, the server variable to use for URI fetching is configurable, it's just the default that has changed.`   
That might've been worth noting in the upgrade guides...
Other than that, close this at will. :)

**Comment by narfbg** [comment]
Duplicate of #4147.
