### ISSUE TITLE
sqlsrv_driver > Change @@IDENTITY with SCOPE_IDENTITY()

### ISSUE THREAD

**Issue by Dimas-sc** [bcit-ci/CodeIgniter#4170]
In the sqlsrv_driver.php the function insert_id() doesn't work well in some cases, returning an unexpected ID. It can be solved changing @@IDENTITY with SCOPE_IDENTITY().

More info: http://www.databasejournal.com/features/mssql/article.php/10894_3307541_2/Getting-the-Wrong-Identity-in-Microsoft-SQL-Server-identity-Columns.htm

**Comment by narfbg** [comment]
Please explain what these "some cases" are.

And it's identi**t**y, no f in there - you made that typo 4 times... That's probably a bad thing to judge by, but it does give the impression that you're not quite familiar with what you're talking about, and in turn making me question whether I should take your suggestion seriously. Am I right to be worried about this?

**Comment by Dimas-sc** [comment]
Yes, I made a typo, so that's a bad thing to judge.

If you are interested in the topic you can refer to the link where you can read:
"@@IDENTITY is usually the first one suggested in books and news groups for discovering new identities. However, its real purpose is not at first evident and may produce the wrong identity. @@ IDENTITY will return the last identity used in your session, but across all scopes. Meaning if your statement causes a trigger to fire, and that trigger insert into a table with an identity field, the triggers new identity will be returned, not your statements new identity. For example, create a test table with an identity, and a trigger on the products table that will insert on the test table.
(...) The function SCOPE_IDENTITY returns the new identity created on any table in this session in this scope, giving us the new value we would expect."

If you use SQL Server Audit to audit a table named 'books' for example, when you insert a row CI won't return the new book ID but the Audit table new row ID.

PD> Sorry, I'm not fluent in English
