### ISSUE TITLE
Nested manual transactions do not decrement _trans_depth

### ISSUE THREAD

**Issue by dnapierata** [bcit-ci/CodeIgniter#4171]
Hello, I have an issue with the way nested database transactions are handled in CI. Currently the only methods that control _trans_depth are trans_start() and trans_complete() so when using manual transactions with trans_commit() and trans_rollback() nesting isn't supported. One way around this is to set _trans_status to FALSE prior to calling trans_complete() however, it is now a protected variable in CI 3. So what I'm proposing is to expose _trans_status by making it public / creating a setter function or  to decrement _trans_depth inside trans_commit() / trans_rollback() instead of trans_complete().

**Comment by narfbg** [comment]
This took some refactoring and was related to other bugs as well ... please tell when you test it. :)
