### ISSUE TITLE
Error with composite keys created in DBForge

### ISSUE THREAD

**Issue by irobotham** [bcit-ci/CodeIgniter#4173]
A bug fix in 3.0.1 means that it is not possible to create composite keys as the behaviour for passing in an array now creates multiple individual keys rather than one key across a number of columns.

The change was introduced via https://github.com/bcit-ci/CodeIgniter/pull/3968 but this changes behaviour originally added in https://github.com/bcit-ci/CodeIgniter/commit/75f405b64ec0dff23bcaf73c9bc805b3804f2863

The documentation states "Multiple column non-primary keys must be sent as an array." and gives the example:

```php
$this->dbforge->add_key(array('blog_name', 'blog_label'));
// gives KEY `blog_name_blog_label` (`blog_name`, `blog_label`)
```

As I see it, there are a couple of options:

1. Keep the fix and update the documentation to state that composite keys are not supported.
2. Revert the fix and update the documentation to advise users who want to create multiple keys to just make multiple add_key() calls
3. Introduce a new method to handle a use case - I suggest either add_keys() or add_composite_key() to provide the expected behaviour.

**Comment by narfbg** [comment]
Thanks.
