### ISSUE TITLE
Upload file array

### ISSUE THREAD

**Issue by igormages** [bcit-ci/CodeIgniter#4174]
Hi,

I'm trying to upload a array from a html form like this : 
```html
<input type="file" name="my_file_array[45]">
<input type="file" name="my_file_array[89]">
```

So I tried that but that's don't work : 
```php
$this->upload->do_upload('my_file_array[45]');
$this->upload->do_upload('my_file_array[89]');
```

Can someone help me please ?
Is't the syntax correct ?

Thanks !

**Comment by tonyciou** [comment]
Hi igormages
i got same problem,
reference: https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Upload.php
search "do_upload", You can find that CI not support multi upload.
I used https://github.com/stvnthomas/CodeIgniter-Multi-Upload to solved it!
I hope this may help you~
My English isn't very good, please don't mind...

**Comment by narfbg** [comment]
Ask your questions on the [forums](https://forum.codeigniter.com/) please, we only accept bug reports here.
