### ISSUE TITLE
Query Builder not apply set() cache

### ISSUE THREAD

**Issue by xpader** [bcit-ci/CodeIgniter#4175]
For example:

```php
$this->db->start_cache();
$this->db->set('colname', 'value');
$this->db->stop_cache();

$this->db->insert('sometable');
$this->db->insert('anothertable'); //the cache 'set' will lost
```

But the user guide said: 
> The following statements can be cached: select, from, join, where, like, group_by, having, order_by, set

http://www.codeigniter.com/user_guide/database/query_builder.html#query-builder-caching

In the Query Builder source code, there's no code to make cache of set() method, hope to fix it.

**Comment by narfbg** [comment]
Caching `set()` can be dangerous and rarely makes sense, so removed that from the docs.

**Comment by xpader** [comment]
What!!!!
