### ISSUE TITLE
CI - 3.0.1 - Issue with user guide, configuration file and session driver.

### ISSUE THREAD

**Issue by richard-hawkesford** [bcit-ci/CodeIgniter#4180]
The user guide states that using the sessions module with database storage requires these two configuration lines in the config.php

$config['sess_driver'] = 'database';
$config['sess_save_path'] = 'ci_sessions';

However the ‘sess_save_path’ configuration line does not work and causes an error in the sessions database file on line 160.

The error is caused by making a select without a from.

This is the check on line 112 of the sessions_database file.

// Note: BC work-around for the old 'sess_table_name' setting, should be removed in the future.
isset($this->_config['save_path']) OR $this->_config['save_path'] = config_item('sess_table_name');

I assumed from this that ‘sess_save_path’ was a typo and that I should use ‘save_path’ instead however this did not work either?

I had to use ‘sess_table_name’ in my configuration file to get this to work which as the comment suggests is obsolete.

**Comment by narfbg** [comment]
Not a typo and it works ... if it didn't we'd have at least a hundred bug reports for it since the 3.0.0 release.

If I had to guess, you probably haven't carefully followed the [upgrade instructions](http://www.codeigniter.com/userguide3/installation/upgrade_300.html), which have an important note stating that you must delete the old system/ directory first. If you just copy-paste over it, you're still using the old CI2 Session library.

**Comment by richard-hawkesford** [comment]
I removed every file off the FTP server and installed CI 3.0.2 using the $config['sess_save_path'] = 'ci_sessions'; 

This is the error

A Database Error Occurred

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE `id` = '6dea33a21aaea1cb7f52c62920c23e8988b73f01'' at line 2

SELECT `data` WHERE `id` = '6dea33a21aaea1cb7f52c62920c23e8988b73f01'

Filename: libraries/Session/drivers/Session_database_driver.php

Line Number: 160

Note there is no FROM in the select as explained above.

I did however see in the upgrade notes the following:

"For the ‘database’ driver, a fallback to $config['sess_table_name'] is in place"

This is not mentioned anywhere in the user guide and only in the upgrade notes, so new users will not have access to this information.

**Comment by narfbg** [comment]
And they shouldn't have access to that information ... you must remove that setting if you have it.

**Comment by richard-hawkesford** [comment]
In order to use the ‘database’ session driver, you must also create this table that we already mentioned and then set it as your $config['sess_save_path'] value. For example, if you would like to use ‘ci_sessions’ as your table name, you would do this:

$config['sess_driver'] = 'database';
$config['sess_save_path'] = 'ci_sessions';

Thats from the user guide user_guide/libraries/sessions.html

**Comment by narfbg** [comment]
Yes, the table won't create itself, that's completely natural ... why are you telling me this?

**Comment by richard-hawkesford** [comment]
--
-- Table structure for table `ci_sessions`
--

CREATE TABLE IF NOT EXISTS `ci_sessions` (
  `id` varchar(40) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `timestamp` int(10) unsigned NOT NULL DEFAULT '0',
  `data` blob NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ci_sessions_id_ip` (`id`),
  KEY `ci_sessions_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by richard-hawkesford** [comment]
The table is already created I’m trying to explain that neither  sess_save_path or save_path are working.

And that the only way to make this work was to fall back to sess_table_name

**Comment by narfbg** [comment]
I don't see how copy-pasting me instructions for table creation helps in any way to explain your problem.

**REMOVE THE 'sess_table_name' setting!** As in completely delete it, not leaving it empty.

**Comment by richard-hawkesford** [comment]
That was an SQL dump so you could see the table was created correctly.

My config file database block now looks like this:

$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = TRUE;

I have removed 

$config['sess_table_name'] = 'ci_sessions';

The page now looks like this

A Database Error Occurred

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE `id` = '0c77c3c04832bbfe12f4b26fe61beb14d984897e'' at line 2

SELECT `data` WHERE `id` = '0c77c3c04832bbfe12f4b26fe61beb14d984897e'

Filename: libraries/Session/drivers/Session_database_driver.php

Line Number: 160

**Comment by narfbg** [comment]
Of course it would look like this, you've left sess_save_path empty ...

**Comment by richard-hawkesford** [comment]
config file changed to:

$config['sess_driver'] = 'database';
$config['sess_save_path'] = 'ci_sessions';
$config['sess_cookie_name'] = 'philix_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = TRUE;

Page still shows error

**Comment by narfbg** [comment]
Dude, seriously?! The 5th line of that code is overwriting what you put on the 2nd.

Please post on the [forums](https://forum.codeigniter.com/) next time you have a problem. This is a bug tracker, we don't deal with everybody's random problems here.
