### ISSUE TITLE
Update batch with multiple where clause

### ISSUE THREAD

**Issue by jyothibhandari** [bcit-ci/CodeIgniter#4182]
I want to do a update batch with multiple where conditions.
Currently i am not able to do the same.

Request you to guide me the same.

**Comment by narfbg** [comment]
Ask your questions on the [forums](https://forum.codeigniter.com/) please, this is a bug tracker.

**Comment by pfote** [comment]
github issue tracker is for bugs not help request
please ask your questions in the forum or in IRC

**Comment by vikassbl** [comment]
This is not working 
ne or more rows submitted for batch updating is missing the specified index.
and locking time.
