### ISSUE TITLE
Drivers not fully documented

### ISSUE THREAD

**Issue by Charles-Garrison** [bcit-ci/CodeIgniter#4187]
In order to get a driver working properly, you must create an array of valid drivers, however this can not be found anywhere in the documentation.

Example of setting the valid drivers array
----------------------------------------------------
$this->valid_drivers = array( 'diver_name', 'another_driver_name' );

Documentation URL
--------------------------
http://www.codeigniter.com/user_guide/general/creating_drivers.html

**Comment by narfbg** [comment]
You say that like the page in question says anything useful at all ... it doesn't. :)

These "drivers" have proven to be confusing for people, and not at all as useful as initially thought. As such, I don't want more additions to encourage people to use them. If the Cache library didn't use `CI_Driver`, I'd erase all of it right now.

**Comment by Charles-Garrison** [comment]
Hi Andrey,

Although I understand what you are saying, and I tend to mostly agree, I do
feel like leaving the documentation incomplete is more confusing an a
bigger issue than encouraging people to use legacy code.  What about a
middle-ground solution?  Fully documenting the usage, but including message
that discourages the usage of Drivers since they will likely be phased out
in the coming versions?

Thanks,

Charles

**Comment by narfbg** [comment]
Well, I could agree to that, but here's the problem ... I'm not sure if there's anybody left who knows exactly how the "drivers" work in order to document them. You'd probably expect me to know it, but I don't; I don't even remember who introduced the feature.

**Comment by Charles-Garrison** [comment]
Fair enough. I don't know how to use the documentation system. So if I documented the drivers, would you consider plugging it in?






On Mon, Oct 26, 2015 at 3:22 AM -0700, "Andrey Andreev" <notifications@github.com> wrote:












Well, I could agree to that, but here's the problem ... I'm not sure if there's anybody left who knows exactly how the "drivers" work in order to document them. You'd probably expect me to know it, but I don't; I don't even remember who introduced the feature.

**Comment by narfbg** [comment]
Given that your additions are suitable - sure, I'll consider it.

**Comment by xiers** [comment]
Hi, there are some examples for CI.
https://github.com/oliverhr/CI2_Drivers_example/
https://github.com/xiers/CI3_Drivers_example/

 useful ?
