### ISSUE TITLE
PHP 5.4 session upload progress not supported

### ISSUE THREAD

**Issue by SoundlessCoder** [bcit-ci/CodeIgniter#4191]
Is it me or does Codeigniter not support the progress of the uploads with the native `$_SESSION` to keep track?

While creating a basic upload form with separate AJAX request to check the contents of `$_SESSION` just shows this:

    Array
    (
        [__ci_last_regenerate] => 1445598994
    )

I can confirm that `session.upload_progress.enabled` is enabled, and also have tested it without Codeigniter.

How can this be solved?

**Comment by narfbg** [comment]
It can't be "solved" without breaking other session functionalities. It is technically impossible when using a userspace session handler.

And even with the built-in ones, then there are many conditions under which session upload progress still wouldn't work.
