### ISSUE TITLE
CI_Email: Garbled non-ascii strings with spaces in email header when MB library is enabled

### ISSUE THREAD

**Issue by gadelat** [bcit-ci/CodeIgniter#4192]
Input "From": `Orange portál`

Output of [mb_encode_mimeheader](https://github.com/bcit-ci/CodeIgniter/blob/175b17c4b74d03a7578440d92a3ac9d80924ef78/system/libraries/Email.php#L1568): `Orange =?UTF-8?Q?port=C3=83=C2=A1l?=`
Shown in e-mail client as: `Orange portÃ¡l `

If MB_ENABLED !== TRUE && ICONV_ENABLED === TRUE:
Output of [iconv](https://github.com/bcit-ci/CodeIgniter/blob/175b17c4b74d03a7578440d92a3ac9d80924ef78/system/libraries/Email.php#L1588): `=?UTF-8?Q?Orange=20port=C3=A1l?=`
Shown in e-mail client as: `Orange portál`

So, from this I can see that I guess the problem is that UTF-8 string is not at the beginning. So I tried to remove the space from input and it was fine then:

Input "From": `Orange_portál`
Output of [mb_encode_mimeheader](https://github.com/bcit-ci/CodeIgniter/blob/175b17c4b74d03a7578440d92a3ac9d80924ef78/system/libraries/Email.php#L1568): `=?UTF-8?Q?Orange=5Fport=C3=83=C2=A1l?=`
Shown in e-mail client as: `Orange_portál`

This problem occurs in both "From" and "Subject" headers.

Swiftmailer handles this correctly.

**Comment by narfbg** [comment]
So you're suggesting to remove `mb_encode_mimeheader()` usage?

**Comment by gadelat** [comment]
Nah, I'm not suggesting solution, I'm sure you're more capable to come up with better solution. I guess it wouldn't hurt to look how other libraries solve this problem.

However, I suggest to at least prefer iconv over mb_* if both are available. So just switch those if/elseifs. Of course, it's very likely that if it will be left at that, someone will report this same bug where reporter has iconv disabled, but mb_* enabled.

**Comment by aanbar** [comment]
I've noticed there's a difference in output when you set internal encoding.

@gadelat Try adding this line before that return in question, if it works; then we have a solution.

```
mb_internal_encoding($this->charset);
```

**Comment by narfbg** [comment]
`mbstring.internal_encoding` does indeed affect `mb_encode_mimeheader()`, but I've already tested this:

    $ cat test.php 
    <?php
    mb_internal_encoding('UTF-8');
    var_dump(mb_encode_mimeheader('Orange portál', 'UTF-8', 'Q'));
    $ php test.php 
    string(30) "Orange =?UTF-8?Q?port=C3=A1l?="
    $

**Comment by gadelat** [comment]
Yeah I tried fiddling with internal_encoding before I posted this issue, no change :-/

**Comment by csksm** [comment]
The fix does not entirely solve the issue.
Turns out `iconv_mime_encode` is just as buggy as `mb_encode_mimeheader`.

Input: `Orange portál Orange portál`
Expected: `Orange portál Orange portál`
Actual: `Orange portál Orang=?UTF-8?Q?e=20port?=ál`

**Comment by narfbg** [comment]
@csksm Can't reproduce.
