### ISSUE TITLE
composer_autoload config bug

### ISSUE THREAD

**Issue by dexterns88** [bcit-ci/CodeIgniter#4197]
When you set $config['composer_autoload'] = TRUE; vendor autoload doesn't load into app you mast insert path to vendor folder then work.
Like:
$config['composer_autoload'] =  FCPATH . '/vendor/autoload.php';

CI version 3.0-stable

**Comment by narfbg** [comment]
Quote from the config.php description of composer_autoload:

>| Enabling this setting will tell CodeIgniter to look for a Composer
>| package auto-loader script in application/vendor/autoload.php.

**Comment by mytharcher** [comment]
I also met this. The first think of mine about `composer.json` should be used in web root path. But this configuration need to put that file into `application` folder. Really hard to understand.

**Comment by feryardiant** [comment]
@dexterns88 yes, mine also use the same [config](https://github.com/projek-xyz/ci-startapp/blob/develop/app/config/config.php#L133) as yours and I don't think it's a bug anyway.

@mytharcher [my](https://github.com/projek-xyz/ci-startapp/tree/develop) `composer.json` is in the `FCPATH` and it's work fine :grin:

**Comment by mytharcher** [comment]
Thanks @feryardiant . I now works with `$config['composer_autoload'] = FCPATH . 'vendor/autoload.php';` fine!
