### ISSUE TITLE
Allow custom result objects to be mapped after constructor

### ISSUE THREAD

**Issue by mattstrom** [bcit-ci/CodeIgniter#4199]
Because of how PHP's MySQL driver implements mysql_fetch_object(), database columns are mapped into the object before its constructor is called (see http://php.net/manual/en/function.mysql-fetch-object.php#82643). Therefore if a custom object's constructor has logic that does something like initialize the object with defaults, the database values are overwritten.

Whereas CodeIgniter 3.0 does this (https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_result.php#L220):

``` php
while ($row = $this->_fetch_object($class_name))
{
    $this->custom_result_object[$class_name][] = $row;
}
```

CodeIgniter 2.2 instead iteratively mapped database columns into the new custom object after it had fetched the object. From https://github.com/bcit-ci/CodeIgniter/blob/2.2-stable/system/database/DB_result.php#L80

``` php
while ($row = $this->_fetch_object())
{
    $object = new $class_name();

    foreach ($row as $key => $value)
    {
        $object->$key = $value;
    }

    $result_object[] = $object;
}
```

Perhaps there could be an additional flag in the custom_result_object() method that would indicate that database columns should be iteratively mapped into the new object rather than using fetch_object() with the class name provided.

**Comment by narfbg** [comment]
What kind of defaults? Why would you do that in a constructor instead of this:

    class Foo
    {
        public $bar = 'baz';
    }

**Comment by mattstrom** [comment]
Dates are a notable limitations, since expressions cannot be used in member declaration.

The way that we are using the custom objects is similar to an ORM, in which an entity can be instantiated, manipulated, and then persisted to the database. Now certainly dates can be set outside of the constructor after the object is instantiated, but it is convenient to encapsulate the initialization of dates in the constructor so that logic is consistent amongst all usages.

We did come up with a workaround for our use cases; we just wrapped the constructor logic in an if block that checks if the primary key is set. If it is, we assume that the object has been populated by the database and therefore does not need to initialize defaults.

```php
public function __construct() {
    if (!isset($this->id)) {
        $this->date = new \DateTime();
        // More defaults
    }
}
```

However, I would contend that if an ORM is integrated into CodeIgniter in the future, this quirk will be an issue.

**Comment by narfbg** [comment]
Well, we surely won't be integrating an ORM into CI, so that's not an issue.

This may still require some action though, so I'll leave it open until we decide what to do with it.

**Comment by adam-bell** [comment]
This is the case for all of the fetch object variants. There is a comment on the PDO fetch object docs which might give insight into the benefits:

http://php.net/manual/en/pdostatement.fetchobject.php#117731

by assigning the properties before constructing, it avoids issues overwriting private variables (and presumably avoids triggerings magic setter functions)
