### ISSUE TITLE
Already loaded session class, with cart library

### ISSUE THREAD

**Issue by kvlknctk** [bcit-ci/CodeIgniter#4201]
error log : 
DEBUG - 2015-10-31 00:52:14 --> Session routines successfully run
DEBUG - 2015-10-31 00:52:14 --> Session class already loaded. Second attempt ignored.

Cart.php Line 59 
$this->CI->load->library('session', $config);

and i called session library with autoload.php 

its debug problem ?

**Comment by narfbg** [comment]
This is a bug tracker, please ask your questions on the [forums](http://forum.codeigniter.com/) instead.
