### ISSUE TITLE
clean POST data 

### ISSUE THREAD

**Issue by yxwzaxns** [bcit-ci/CodeIgniter#4202]
in system/core/Input.php 613 rows    
    if (is_array($_POST) && count($_POST) > 0)
		{
			foreach ($_POST as $key => $val)
			{
				$_POST[$this->_clean_input_keys($key)] = $this->_clean_input_data($val);

			}

		}

if $key can't preg_match('/^[a-z0-9:_\/|-]+$/i', $key) ,the $this->_clean_input_keys($key) will return false,so if poat data is ]:123,then the POST data will become 

    array(2) {
  ["]"]=>
  string(3) "123"
  [1]=>
  string(3) "123"
}

the key [ still to use

**Comment by narfbg** [comment]
If anything should be changed here, it's that `_clean_input_keys()` should be removed altogether.

**Comment by yxwzaxns** [comment]
the function can't filter anything Special symbols，if I post { '['="a"} ,I will use $this->input->post('[') get it

**Comment by narfbg** [comment]
#4101

**Comment by yxwzaxns** [comment]
ok,I know
