### ISSUE TITLE
I love CodeIgniter very much ! But is it FULLY compatible with PHP 7 ?

### ISSUE THREAD

**Issue by duruitang** [bcit-ci/CodeIgniter#4203]
PHP 7.0.0 RC 6 Released

The PHP development team announces the immediate availability of PHP 7.0.0 RC 6. This is the eleventh pre-release of the new PHP 7 major series.

**Comment by jim-parry** [comment]
If you find an incompatability with CodeIgniter and PHP7, github is the proper place to report it.
If this is just a question, or you want to initiate a discussion, please do so on forum.codeigniter.com!

**Comment by DevotionGeo** [comment]
Yes, it is compatible. I ran it on bitnami's wamp stack with php 7, and it worked for my applications, though I didn't use it in production.
