### ISSUE TITLE
MySql syntax error when using dbforge->modify_column

### ISSUE THREAD

**Issue by ron-dadon** [bcit-ci/CodeIgniter#4204]
When using this function, according to the documentation, the 'name' key in the field definition array is optional, but using this function without this key causes a syntax error in MySql due to the MySql syntax requiring "ALTER TABLE table_name CHANGE old_col_name new_col_name new_col_definition".

Looking at CI2 source code, it seems that in CI2 there was a foreach loop that filled the field definition arrays that were missing this key with the current field name, and that loop is missing in CI3.

I'm wondering if there is a mistake in the code or in the documentation, meaning - the 'name' key is mandatory in CI3.

**Comment by narfbg** [comment]
Can you give an example of what you're trying to do and what error does it trigger?

**Comment by ron-dadon** [comment]
I'm try to do an "installation" for my application, that checks if the table exists, and if so, only remove/adds/modifies columns without deleting all the data in the table.

For example, I have a 'clients' table, with fields 'id','name','uid','created'.
I get all the table fields using `db->list_fields()`, and than use `dbforge->add_column` to add new columns, `dbforge->drop_column` to remove unused columns, and `dbforge->modify column` on all the other columns.

For example, I send the following array to the `modify_column` function (the ID field never gets changed, so is not relevant in the array):
```php
$fields = array(
    'uid' => array('type' => 'varchar', 'constraint' => 40),
    'name' => array('type' => 'varchar', 'constraint' => 100),
    'created' => array('type' => 'int', 'contraint' => 11, 'null' => true)
);
$this->dbforge->modify_column('clients', $fields);
```

When this code runs, I get:
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VARCHAR(40)' at line 1.

Looking at the SQL query created by CI, I get the following:
ALTER TABLE `clients` CHANGE `uid` VARCHAR(40)

Which is wrong, because CHANGE requires old_col_name and new_col_name.
According to CI3 documentation on DB_Forge, the `name` key in the field definition array is optional and should be used if I want to change the field name - but here I only want to change the field type/constraint for example.

Looking at CI2 source for DB_Forge, it seems that in CI2, there was a loop that iterates over the $fields array, and if the 'name' key is missing, it would have add it with the same name as the column, so my $fields array would look like this after the loop:
```php
$fields = array(
    'uid' => array('type' => 'varchar', 'constraint' => 40, 'name' => 'uid'),
    'name' => array('type' => 'varchar', 'constraint' => 100, 'name' => 'name'),
    'created' => array('type' => 'int', 'contraint' => 11, 'null' => true, 'name' => 'created')
);
```

**Comment by narfbg** [comment]
Database classes are not extendable, that won't work.

**Comment by ron-dadon** [comment]
I tried id, simply adding MY_DB_Forge.php to the core folder, and declaring the following works for me :)

```php
class MY_DB_forge extends CI_DB_forge {

    /**
     * Column Modify
     *
     * @param	string	$table	Table name
     * @param	string	$field	Column definition
     * @return	bool
     */
    public function modify_column($table, $field)
    {
        if (is_array($field)) {
            foreach ($field as $k => &$f) {
                if (!isset($f['name'])) {
                    $f['name'] = $k;
                }
            }
        }
        return parent::modify_column($table, $field);
   }

    /**
     * Process column
     *
     * @param	array	$field
     * @return	string
     */
    protected function _process_column($field)
    {
        return $this->db->escape_identifiers($field['name'])
        .(isset($field['new_name']) ? ' ' . $this->db->escape_identifiers($field['new_name']) : '')
        .' '.$field['type'].$field['length']
        .$field['unsigned']
        .$field['default']
        .$field['null']
        .$field['auto_increment']
        .$field['unique'];
    }
}
```

**Comment by narfbg** [comment]
No it doesn't. There's no condition allowing DBForge to be extended or overriden.

The only way it could work is if you've manually patched the loader to allow it.

**Comment by ron-dadon** [comment]
I guess you are right, I'm using HMVC extension that overrides the loader, so I guess that is why I overriden DB_Forge without a problem.

Thank's for your support.

**Comment by mwhitneysdsu** [comment]
The MX Loader used by Wiredesignz HMVC doesn't modify the loading of DBForge. It modifies the loading of the database library/driver, but doesn't permit extending/overloading those classes, either. I checked a couple of other HMVC implementations, and haven't found one that attempts to do this, probably because it isn't necessary to modify the database/DBForge functionality to implement HMVC (the modification to the database() method in Wiredesignz HMVC is to ensure the db property is assigned to the CI super object defined in MX/Base.php).

**Comment by ivantcholakov** [comment]
@mwhitneysdsu I've got modifications that load database related files from alternative locations. They don't extend classes, just swap files, which was easy for implementation at that time. But personally I never needed such a feature so far.

**Comment by narfbg** [comment]
@ron-dadon Are you sure that you haven't modified anything?

Because, all three of 'mysql', 'mysqli' and 'pdo/mysql' drivers are built to actually use `MODIFY` instead of `CHANGE` when there's no 'new_name'.

**Comment by ron-dadon** [comment]
We are using Wiredesignz HMVC at my workplace, and I've check, and the previous team modified the `MX_Loader` class and that is why I was able to use `MY_DB_Forge`.
On the other hand, the CI3 system folder was left unchanged for sure (I've compared the files with the current CI3 release).

@narfbg Looking into those 3 drivers (we use mysqli), their `CI_DB_*_forge` classes extends the `CI_DB_Forge` class, but does not override the `modify_column` function, and the `modify_column` function in the `CI_DB_Forge` creates a `CHANGE` query (look into `CI_DB_Forge` class line 642).
The `_process_column` function in `CI_DB_mysqli_forge` class does have the 'new_name' check in line 191, but because `modify_column` function never creates this key, it's never being used.

**Comment by narfbg** [comment]
`modify_column()` doesn't create a `CHANGE` query, it passes the string 'CHANGE' to `_alter_table()`, which in turn does this:

https://github.com/bcit-ci/CodeIgniter/blob/939f1a27f3e70170326f6acbc50c0e1c96e52fd3/system/database/drivers/mysqli/mysqli_forge.php#L162

**Comment by ron-dadon** [comment]
Figured out our problem :confused: 

We've upgraded to CI3 about 2 months ago, and the previous team have implemented their own MY_DB_mysqli_* classes (god knows why), and they were CI2 compatible :confounded:

Sorry for the mix-up, and thank you for your patience :thumbsup:

I'm closing the issue.
