### ISSUE TITLE
system/core/Config.php 3.0 There is an error in line 89

### ISSUE THREAD

**Issue by yuwenlong** [bcit-ci/CodeIgniter#4209]
// Set the base_url automatically if none was provided
		if ($this->config['base_url'] == '')
		{
			if (isset($_SERVER['HTTP_HOST']))
			{
				$base_url = isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) !== 'off' ? 'https' : 'http';
				$base_url .= '://'. $_SERVER['HTTP_HOST'];
				$base_url .= str_replace(basename($_SERVER['SCRIPT_NAME']), '', $_SERVER['SCRIPT_NAME']);
			}

			else
			{
				$base_url = 'http://localhost/';
			}

			$this->set_item('base_url', $base_url);
		}

**Comment by yuwenlong** [comment]
Need to change the previous code, or an error occurs, it can not determine the IP address, because there are many virtual hosts an IP next

**Comment by narfbg** [comment]
This code has never existed in 3.0.x and I don't understand what you're trying to say anyway.

**Comment by yuwenlong** [comment]
branch 3.0-stable system/core/Config.php is error.

Analyzing IP is wrong, because there are a lot of virtual machines. You can test under local tie the domain name, as bash_url () will become 127.0.0.1, resulting in a reference to CSS and JS failure.

The need to replace the following code into a branch of the 2.2-stable or dev.

if (empty($this->config['base_url']))
		{
			if (isset($_SERVER['SERVER_ADDR']))
			{
				$base_url = (is_https() ? 'https' : 'http').'://'.$_SERVER['SERVER_ADDR']
					.substr($_SERVER['SCRIPT_NAME'], 0, strpos($_SERVER['SCRIPT_NAME'], basename($_SERVER['SCRIPT_FILENAME'])));
			}
			else
			{
				$base_url = 'http://localhost/';
			}
			$this->set_item('base_url', $base_url);
		}

**Comment by narfbg** [comment]
Everything is wrong, depending on the use case. The IP address is the only safe option and won't be changed.

Read the upgrade instructions and properly configure 'base_url'.
