### ISSUE TITLE
$this->form_validation->run() with no rules fails, used to pass

### ISSUE THREAD

**Issue by emilebourquin** [bcit-ci/CodeIgniter#4210]
I have a form with 3 arrays of checkboxes. It is acceptable for none of the checkboxes to be checked, some of them to be checked, or all of them to be checked.

The rules array looks like this:

```
$config['THE_FORM_VALIDATION_RULES'] = array(

   array('field' => 'allowed[]', 
         'label' => 'Allowed', 
         'rules' => ''), 

   array('field' => 'chosen[]', 
         'label' => 'Chosen', 
         'rules' => ''), 

   array('field' => 'default_checked[]', 
         'label' => 'Default Checked', 
         'rules' => ''), 

   );
```

There are no rules for any of the 3, because, again, it is allowable for none of the checkboxes to be checked. However, each entry has to be there so that the form data can be repopulated on error (without them, form repopulation does not work);

In the CI 2.x branch, a call to $this->form_validation->run() with these rules would pass. In the 3.x branch, it fails.

I have tracked the failure back to a chunk of code in Form_validation set_rules:

```
		// No fields or no rules? Nothing to do...
		if ( ! is_string($field) OR $field === '' OR empty($rules))
		{
			return $this;
		}
		elseif ( ! is_array($rules))
		{
			// BC: Convert pipe-separated rules string to an array
			if ( ! is_string($rules))
			{
				return $this;
			}

			$rules = preg_split('/\|(?![^\[]*\])/', $rules);
		}
```

CI 2.x simply did this:

```
		// No fields? Nothing to do...
		if ( ! is_string($field) OR  ! is_string($rules) OR $field == '')
		{
			return $this;
		}
```
For the moment, I can get away with making 'allowed[]' be required, but it would be more correct for it to work with no rules for any of the 3 entries.

Perhaps there is some other rule I am missing that could describe an array of numeric values?

**Comment by narfbg** [comment]
You're not supposed to have empty rules and it's not at all necessary to define FV rules to repopulate a form.

**Comment by emilebourquin** [comment]
"... it's not at all necessary to define FV rules to repopulate a form."

For form repopulation (on form error) to work, there must at least be some sort of entry for the field in the rules, something like:

```
   array('field' => 'allowed', 
         'label' => 'Allowed', 
         'rules' => ''), 
```

set_checkbox (and the other set_ functions, I would guess) does not work to repopulate the previously changed state of a checkbox, when there is a form error, if there is no entry in the rules for the checkbox field. This is the case in CI2 and CI3.

Steps to recreate;

1) Have a form with a text input and a checkbox
2) Have a FV 'required' rule for the text input, but no entry in the rules for the checkbox
3) The record comes out of the database with the text input prefilled, and the checkbox checked.
4) Clear the text input (a form error), and uncheck the checkbox. Click submit
5) A form error is shown (text input required), but the checkbox is currently in the checked state, even though I unchecked the checbox in step 4.

If a FV entry is added for the checkbox field, even with a blank rule, the checkbox properly reflects the unchecked state in step 5, when the form error is shown (for the empty text input).

I use set_checkbox like this in my form:

```
<?= set_checkbox('item_active', '1', ($item->active ? TRUE : FALSE)); ?>
```

Having said all that, I'm changing any empty checkbox rule to instead use in_list[1] , where the checbox value is '1'.

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/starter-public-edition-3/blob/v3.0.90/platform/application/helpers/checkbox_helper.php

**Comment by narfbg** [comment]
You know, I actually see the issue now, and it has nothing to do with what you're claiming it is.

I'll repeat: It is not necessary to define FV rules in order to populate a form.

It's not even necessary to load the Form validation library to do that. Yet, your reply again starts with the *precondition* that you must have empty rules to allow it. Well ... to be fair, I'm half-right and you are half-wrong. ;)

There's a bug in `set_checkbox()`, `set_radio()` (the helper functions) that prevents *specifically* checkboxes and radio buttons to be dynamically set to an *'unchecked'* state, *when/if 'checked' is the default*.

Still, defining empty rulesets is not a use case that has ever been considered. You should think of it as something with undefined behavior, not something to use.

**Comment by emilebourquin** [comment]
Thanks for looking into this and getting a fix in place.

I wasn't necessarily saying that empty rules were needed, my though process went something more like this:

Long ago, under CI2:
Hmm, on form error, form repopulation for checkboxes using set_checkbox doesn't work properly if there is no entry at all for the checkbox field in the array passed to set_rules. 

I'll put an entry in for the checkbox field, but since I don't care if it's checked or not, I'll make the ruleset for the checkbox empty. Hey, look at at that, form repopulation works properly now for checkboxes.

Later, under CI3:
I've ended up with a form that has 3 arrays of checkboxes, and the rulesets for each checkbox array are empty. This used to pass form validation in CI2, but no longer does in CI3. I'll open an issue about it.


My statements were less about "this is exactly the problem", and more about "I'm observing a difference between CI2 and CI3 that is not called out in https://www.codeigniter.com/userguide3/installation/upgrade_300.html , I'll let someone know.

Thanks again for your work on this issue, and for all your hard work on CI3, I really appreciate it.

**Comment by phalox** [comment]
To me the empty-rules use case, should be 'fixed'. It takes half an hour to figure out why the hell the code isn't working.

A simple error message would be incredibly helpful.

**Comment by narfbg** [comment]
da55e5c5608cfc7ea1703e7b9b0357dfe10c5ab7
