### ISSUE TITLE
form_password 密码是明文需要提交前加密

### ISSUE THREAD

**Issue by seikai10** [bcit-ci/CodeIgniter#4211]
form_password 数值在form_submit前密码是明文能否加密传输.
(
Form_password value in the form_submit password is clear text can be encrypted before transmission
)

**Comment by silams** [comment]
你确定外国友人能看懂中文？（/TДT)/

**Comment by silams** [comment]
1、登录页走HTTPS；
2、密码提交前通过 JavaScript 加密。
     由于 JavaScript 代码暴露在客户端，因此一般通过不可逆的加密方法加密密码，而对于任何摘要式的加密算法，都可以通过类似 md5 字典的方式直接查表获知弱密码，所以要混入 salt 以增加制作字典的成本。可想而知，解密只是时间成本的问题。因此这里的重要前提是“对安全性要求不高”。如何验证密码呢？一个可行的方法是，客户端提交 md5(password) 密码（如上所述，此方法只是简单保护了密码，是可能被查表获取密码的）。服务端数据库通过 md5(salt+md5(password)) 的规则存储密码，该 salt 仅存储在服务端，且在每次存储密码时都随机生成。这样即使被拖库，制作字典的成本也非常高。密码被 md5() 提交到服务端之后，可通过 md5(salt + form['password']) 与数据库密码比对。此方法可以在避免明文存储密码的前提下，实现密码加密提交与验证。这里还有防止 replay 攻击（请求被重新发出一次即可能通过验证）的问题，由服务端颁发并验证一个带有时间戳的可信 token （或一次性的）即可。当然，传输过程再有 HTTPS 加持那就更好了。最后，为什么要密码控件？原因之一是上面说的，要防止密码在提交前被截获。

著作权归作者所有。
商业转载请联系作者获得授权，非商业转载请注明出处。
作者：janlay
链接：http://www.zhihu.com/question/20060155/answer/13857741
来源：知乎

**Comment by jim-parry** [comment]
Sorry, but we can only handle English here.

**Comment by seikai10** [comment]
Problem solving。
form_submit() + js ，Encryption
