### ISSUE TITLE
queries being garbled

### ISSUE THREAD

**Issue by QuakePhil** [bcit-ci/CodeIgniter#4214]
I'm working on a reproducable test-case, but for now I can only spell out the problem:

We're using batch_insert, and this works with limit 50, but when we do limit 51 we get an error similar to this:

A Database Error Occurred
		Error Number: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0, `id`, `ip_address`, `timestamp`, `data`) VALUES ((0.0009,'R91','','MC',NULL,8' at line 1</p><p>INSERT INTO `sessions` (0, `id`, `ip_address`, `timestamp`, `data`) VALUES ((0.0009,'R91','','MC',NULL,838,'300','','xxx',NULL,'xxx','030915',0.00037902330556371,'ST','','36','','4','40','xxx','51'), '2e1329e6c9be3c4e25434e875552e7f4df17ecc2', '10.16.11.197', 1446667498, '__ci_last_regenerate|i:1446667497;')</p><p>Filename: libraries/Session/drivers/Session_database_driver.php</p><p>Line Number: 220</p>	</div>
</body>

Notice the malformed query has a "0" key and what looks like a nested array value.  Has anyone else even seen this behaviour before?  My hunch is that it is a bug introduced by 3.0.x CI

**Comment by QuakePhil** [comment]
We also saw a different query (a select query that time) being "injected" with values from a session table update as well.  I don't have that result saved, but the result above I think we can reproduce

**Comment by narfbg** [comment]
CI doesn't have a 'batch_insert' ...

It has `insert_batch()`, if that's what you mean, but there's no "limit" associated with it.

**Comment by QuakePhil** [comment]
That's right, I meant insert_batch.  When I mentioned limit, I was talking about our summary query, the garbling starts once we start iterating over the summary query and doing detail queries.  If our detail queries don't grow past a certain count, the error doesn't happen.

What I don't understand, is how CI could possibly generate the error message which I copy-pasted in my original post...  Note: my application code does not reference the sessions table

**Comment by narfbg** [comment]
I'm afraid I'd have to see that application code in order to do anything but blind guesses ...

**Comment by QuakePhil** [comment]
We're going to try to disable sess_use_database for now in a hunch to try and work around the issue.

I'll try to construct a reproduceable test-case, and maybe get a screenshare for app code in the future although that might be more difficult

**Comment by narfbg** [comment]
The code needs to be copy-pasted (or linked, but publicly accessible) here ... I'm not interested in your actual data or anything possibly sensitive - you can mask whatever you deem "secret" - but with no technical details provided, this just isn't a valid bug report.

**Comment by adam-bell** [comment]
My guess is that the code in #4213 will fix this, and that your query is causing a memory error or some other exit from the app.

The session save handler will run, with the QB cache, causing the bizarre query
