### ISSUE TITLE
Multiple vcard file download in Codeigniter 

### ISSUE THREAD

**Issue by aniket0210** [bcit-ci/CodeIgniter#4221]
vcard export download in Codeigniter works only once.
I want my user to select multiple contacts and export their details in vcard format.This is my controller:

            function get_contacts_email_vcard()
            {
                $this->load->library('vcard');                
                $datavcard = $this->getvcard($this->user_model->get_email_contacts());
            } 
            function getvcard($dat)
            {
                $datavcarddata = array();
                foreach($dat as $data){
                $datavcarddata['display_name'] = $data->name;                                                 
                $datavcarddata['cell_tel'] = $data->mobile_no;                
                $datavcarddata['email1'] = $data->email;   
                if (is_array($datavcarddata))
                {    
                    $this->vcard->vcard($datavcarddata);
                }
                else
                {
                    $this->vcard->vcard();
                }
                $this->vcard->zipdownload();
                }
                return $datavcarddata;
            } 
This is my view

    <li><a href="<?php echo base_url(); ?>auth/get_contacts_email_vcard">vCard(Address Book)        </a></li>
This is my model:

    function get_email_contacts(){
    $this->db->select('*');
            $this->db->from('contacts');
            $this->db->where('user_id', $this->session->userdata('user_id'));
            $this->db->order_by('date_created', 'DESC');
            $query = $this->db->get();
            $result = $query->result();
            return $result;
    }

The issue I am facing is that this works only once. Only the data of the last contact from my database gets downloaded in a zip file. I want to create different zip files or vcf files for different contacts.<b> And i also want to create a single zip file containing all the vcf files.</b>

**Comment by narfbg** [comment]
Sorry, but this is not StackOverflow ... we only accept bug reports here.

Any other questions that you might have, you should ask on the [forums](http://forum.codeigniter.com/).
