### ISSUE TITLE
Why I cannot run prepared sql statements using CodeIgniter's PDO (SQLITE) database object?

### ISSUE THREAD

**Issue by prahladyeri** [bcit-ci/CodeIgniter#4222]
I'm trying to connect to sqlite database using php pdo driver in the code-igniter framework (version 3.0). At the beginning of the controller, I check whether tables exist and if not, I just create them using `prepare` statement:

		$this->load->database();
		$query = $this->db->get("SQLITE_MASTER");
		$count = count($query->result_array());
		if ($count === 0) {
				$sql  = "CREATE TABLE PAGES(PAGENAME VARCHAR(255), PROJNAME VARCHAR(255), MENUTEXT VARCHAR(255))";
				$stmt = $this->db->prepare($sql);
				$stmt->execute();
				echo "NEW TABLES CREATED!";
		}

But this gives me the error:

     Message: Call to undefined method CI_DB_pdo_sqlite_driver::prepare()

However, instead of `prepare()` and `execute()`, I use the `query()` function, it works flawlessly. Why is that? Since I'm building a production level app, performance considerations will push me to use the `prepare` statement sooner or later, so what should I do?

**Comment by narfbg** [comment]
Because.

This is a bug tracker. If you need help with figuring out something, ask on the [forums](http://forum.codeigniter.com/) instead.
