### ISSUE TITLE
Found error query combine join and group by

### ISSUE THREAD

**Issue by dyazin** [bcit-ci/CodeIgniter#4224]
Error Number:

ERROR: column "user_profile.ID" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT "user_profile".*, "trx_bidding"."ID" as "IDtrx", "trx... ^

SELECT "user_profile".*, "trx_bidding"."ID" as "IDtrx", "trx_bidding"."IDbidding", "trx_bidding"."IDuser" as "idus", "trx_bidding"."price", "trx_bidding"."dbidd", "trx_bidding"."tbidd", "trx_bidding"."status", "trx_bidding"."winner_by", "trx_bidding"."prosentase", "trx_bidding"."quantity" FROM "trx_bidding" JOIN "user_profile" ON "user_profile"."IDuser"="trx_bidding"."IDuser" WHERE "trx_bidding"."IDbidding" = 'ef0fe547d987a7a716292482ce0ec57c' GROUP BY "user_profile"."company"

Filename: C:/xampp/htdocs/ebiding/application/models/M_bidding.php

Line Number: 274

**Comment by narfbg** [comment]
This is just how SQL works, it's not the framework's problem.

**Comment by dyazincahya** [comment]
in posthreSQL i found the problem -_-
function get_preview($id) {
			$this->db->select('
				user_profile.ID as ID_user_profile,	user_profile.IDuser as IDuseror, user_profile.foto, user_profile.fname,	user_profile.lname,	user_profile.company, user_profile.addres, user_profile.city, user_profile.country, user_profile.pkp, user_profile.state, user_profile.zip_code, user_profile.area_code, user_profile.offc_phone, user_profile.offc_fax, user_profile.mobile_phone, user_profile.npwp,user_profile.email, user_profile.spek_business, 
				trx_bidding.ID as IDtrx, trx_bidding.IDbidding, trx_bidding.IDuser, trx_bidding.price, trx_bidding.dbidd, trx_bidding.tbidd, trx_bidding.status, trx_bidding.winner_by, trx_bidding.prosentase, trx_bidding.quantity
			');
			$this->db->from('trx_bidding');
			$this->db->join('user_profile','user_profile.IDuser=trx_bidding.IDuser', 'left');
			$this->db->where('trx_bidding.IDbidding', $id);
			$this->db->group_by("trx_bidding.IDuser");
			$query = $this->db->get();
    
			return $query->result();
		}

**Comment by dyazin** [comment]
in postgreSQL i found the problem -_- , please help , thanks before .
.
function get_preview($id) {
			$this->db->select('
				user_profile.ID as ID_user_profile,	user_profile.IDuser as IDuseror, user_profile.foto, user_profile.fname,	user_profile.lname,	user_profile.company, user_profile.addres, user_profile.city, user_profile.country, user_profile.pkp, user_profile.state, user_profile.zip_code, user_profile.area_code, user_profile.offc_phone, user_profile.offc_fax, user_profile.mobile_phone, user_profile.npwp,user_profile.email, user_profile.spek_business, 
				trx_bidding.ID as IDtrx, trx_bidding.IDbidding, trx_bidding.IDuser, trx_bidding.price, trx_bidding.dbidd, trx_bidding.tbidd, trx_bidding.status, trx_bidding.winner_by, trx_bidding.prosentase, trx_bidding.quantity
			');
			$this->db->from('trx_bidding');
			$this->db->join('user_profile','user_profile.IDuser=trx_bidding.IDuser', 'left');
			$this->db->where('trx_bidding.IDbidding', $id);
			$this->db->group_by("trx_bidding.IDuser");
			$query = $this->db->get();
    
			return $query->result();
		}

**Comment by dyazin** [comment]
if you belive, you can try it yourself.

**Comment by narfbg** [comment]
It's not a matter of believing.

This is not a site where you seek help, it's a bug tracker (and you're not reporting a bug). If you're seeking help, try asking your questions on the [forums](http://forum.codeigniter.com/) instead.

**Comment by dyazin** [comment]
in forum i'm don't create new post -_-
