### ISSUE TITLE
base_url return server ip instead of server host

### ISSUE THREAD

**Issue by iqbalfn** [bcit-ci/CodeIgniter#4226]
In CI 3.0.3 `base_url` return IP server instead of domain name. It cause broken link on shared hosting, or multiple domain in the some IP server.

**Comment by narfbg** [comment]
Yes.

**Comment by ppc52776** [comment]
Is is correct behavior?

**Comment by iqbalfn** [comment]
Yes it is, you better fill $config['base_url'] with your domain name.

**Comment by mrashad10** [comment]
Well you ever fix this? and restore the good easy way to not set the $config['base_url'] manually
