### ISSUE TITLE
base_url() Mac OS X

### ISSUE THREAD

**Issue by sumodevelopment** [bcit-ci/CodeIgniter#4231]
CodeIgniter 3.0.3 - Website release

If `base_url` is not defined in config it is populated as `http://::1` on Mac OS X. Removing that entry from my local host file results in `http://127.0.0.1`

Tested version 3.0.2 correctly display `base_url` as `http://localhost:8888`

**Comment by narfbg** [comment]
Read the upgrade instructions.

**Comment by sumodevelopment** [comment]
My apologies. Thank you very much, I understand now.
