### ISSUE TITLE
Transactions still broken in 2.2.6

### ISSUE THREAD

**Issue by paulcanning** [bcit-ci/CodeIgniter#4234]
There was a fix for this, https://github.com/bcit-ci/CodeIgniter/issues/5, and it may have been added, but it is still missing in 2.2.6 (I just downloaded the ZIP fresh, and checked the mysqli driver)

**Comment by narfbg** [comment]
2.x is no longer supported, sorry.

**Comment by paulcanning** [comment]
If I have quite a large app built in v2, how difficult is it to migrate to v3?

**Comment by narfbg** [comment]
There's no straightforward answer to that ... here are the upgrade instructions: http://www.codeigniter.com/userguide3/installation/upgrade_300.html

But please ask your questions on the [forums](http://forum.codeigniter.com/) instead, we only deal with bug reports here.
