### ISSUE TITLE
Support for array uri parameters

### ISSUE THREAD

**Issue by Mechazawa** [bcit-ci/CodeIgniter#4238]
Currently `Input::_clean_input_keys` [here](https://github.com/bcit-ci/CodeIgniter/blob/035c21accc6831ac6bf64151afcdf80ca68b0367/system/core/Input.php#L725-L739) makes sure that uri array parameters are impossible such as `?foo[bar]=asd&foo[baz]=blah`. There is no way to disable this validation or explicitly allow `Input::get` to return an array. 

So for example for the uri `http://example.com/?foo[bar]=asd&foo[baz]=blah`

```php
$foo = $this->get('foo'); 
$foo == array('bar' => 'asd', 'baz' => 'blah');
```

**Comment by narfbg** [comment]
Such parameters work perfectly fine, and `_clean_input_keys()` has nothing to do with that anyway.
