### ISSUE TITLE
User agent library "is_referral()" not working

### ISSUE THREAD

**Issue by murzid** [bcit-ci/CodeIgniter#4243]
In the past (CI2) it's work fine
```php
public function is_referral()
{
	if ( ! isset($_SERVER['HTTP_REFERER']) OR $_SERVER['HTTP_REFERER'] == '') {
		return FALSE;
	}
	return TRUE;
}
```

But in CI3 referer output always empty (false)
```php
$this->agent->is_referral()
```
So i can't do it something like this
```php
// always false
if ($this->agent->is_referral()) {
	redirect ( $this->agent->referrer() );
} else {
	redirect('unknown');
}
```
It's always redirect to unknown. But URL is not empty (correct HTTP Referrer)
```php
// it's not empty
$this->agent->referrer();
```
What's wrong? :confused:

**Comment by narfbg** [comment]
Under what conditions do you expect it to be true?

**Comment by murzid** [comment]
After submitted form or some actions button (edit, delete, change status, etc)
Basicaly, i want go back to record list (last page) after click an action. 

For example, i have page with pagination. I need to do some actions in page-3 like delete record, so after delete process is completed i want go back to page-3 using HTTP_REFERER instead write URI manualy for redirect

**Comment by narfbg** [comment]
Sorry, but I'm not asking how you want to use it ... This is a bug tracker, I'm asking for the relevant conditions under you expect it to be true but it is not.
The HTTP_REFERER value and your base_url would be a good start.

**Comment by murzid** [comment]
Sorry, I'm just want is_referral() working again in CI3 just link the old one (CI2)
I don't know how to fix it. I solve my problem using old functions (CI2)

**Comment by narfbg** [comment]
Well, then please post your questions on the [forums](http://forum.codeigniter.com/) next time.

As I said, this is a bug tracker.
