### ISSUE TITLE
Form_validation, set_data() -> get_data()

### ISSUE THREAD

**Issue by michesbianan** [bcit-ci/CodeIgniter#4249]
The set_data() method of this class is great especially in Thin-Controllers-Fat-Models dev approach. 

With data preppers added in the rules, it will be great if the $validation_data property will also be  reset as with the $POST as in _reset_post_array() method. 

Ultimately, it will be great also to have a method get_data() rather than accessing the public $validation_data property.

**Comment by narfbg** [comment]
Duplicate of #2436.
