### ISSUE TITLE
[Export to Excel 2013]Encoding error

### ISSUE THREAD

**Issue by tthanhlong** [bcit-ci/CodeIgniter#4250]
I have tried the export to excel from this link; https://github.com/bcit-ci/CodeIgniter/wiki/Export-to-Excel-2013. It sounds good until return data included Japanese characters (Hiragana, Katakana and Kanji). It returned me "ă‚­ăƒƒăƒ”ăƒ¼",.. or something like this,... How can I fix it?

**Comment by jim-parry** [comment]
That helper is not part of the CodeIgniter framework, but is mentioned on our wiki. You might try reaching out to the wiki contributor, or you might post a question on forum.codeigniter.com

Issues are are for bugs in the framework, sorry.
