### ISSUE TITLE
function _remove_evil_attributes() will replace some form data incorrectly

### ISSUE THREAD

**Issue by yanhuichao** [bcit-ci/CodeIgniter#4253]
I;m using version 2.2.0. the issue is that a normal form data submit from browser will be replaced with  whitespaces under the regex expression in function _remove_evil_attributes(): 
> $str = preg_replace("/<(\/?[^><]+?)([^A-Za-z<>\-])(.*?)(".implode('|', $attribs).")(.*?)([\s><])([><]*)/i", '<$1 $3$5$6$7', $str, -1, $count);

the form data before processed by the obove regex in _remove_evil_attributes()  is as follow:
> `<p>测试</p><p><br/></p><p><img src="http://qy-demo-img.b0.upaiyun.com/uploads/20151118/hh47iafjxphcfvlzax0dgwg85ok79kft.png!poststd" style=""/></p><p><img src="http://qy-demo-img.b0.upaiyun.com/uploads/20151118/o05lvjjxmv8qnv7viufds8yr7239zx03.png!poststd" style=""/></p><p><br/></p>`

after replaced the data was as follow: 
> `<p>   试</p><p><br/></p><p><img src="http://qy-demo-img.b0.upaiyun.com/uploads/20151118/hh47iafjxphcfvlzax0dgwg85ok79kft.png!poststd" /></p><p><img src="http://qy-demo-img.b0.upaiyun.com/uploads/20151118/o05lvjjxmv8qnv7viufds8yr7239zx03.png!poststd" /></p><p><br/></p>`

as you see the character '测' was lost , is this a bug or something wrong with my form  data ?

**Comment by narfbg** [comment]
Well, don't use 2.2.0; use 3.0.latest.
