### ISSUE TITLE
xss_filtering (deprecated? )

### ISSUE THREAD

**Issue by DevotionGeo** [bcit-ci/CodeIgniter#4255]
The warning message in the CodeIgniter's comments for $config['global_xss_filtering'] says,
" WARNING: This feature is DEPRECATED and currently available only for backwards compatibility purposes! "

What does that mean? Is only global xss filtering (setting xss filtering globally through config.php) deprecated or the xss filtering is completely deprecated and the method xss_filtering() will be removed from the security class completely?

**Comment by cygmris** [comment]
Instead of enabling global xss filtering, consider using $this->securit->xss_clean() when rendering data which is a better way to not to mass up users' input,.
as [Documents](http://www.codeigniter.com/user_guide/libraries/input.html?highlight=xss) says,
> The ‘global_xss_filtering’ setting is DEPRECATED and kept solely for backwards-compatibility purposes.  XSS escaping should be performed on output, not input!

**Comment by narfbg** [comment]
This is a bug tracker, not a Q&A website ... you know that.
