### ISSUE TITLE
Slashes in variables are not possible in routes

### ISSUE THREAD

**Issue by dominicimhof** [bcit-ci/CodeIgniter#4258]
I'm working on a custom CMS for a client. The goal is, that everything, that comes after the domain-part, will be passed to the method. E.g. http://example.org/foo/bar should call the show function in the Pages class with the variable $slug equals 'foo/bar'.

The following code doesn't work as expected but is documented under https://codeigniter.com/user_guide/general/routing.html?highlight=routes#regular-expressions

**routes.php**
```php
$route['(.+)'] = 'pages/show/$1';
```

**Pages.php**
```php
public function show($slug)
{
    var_dump($slug);
}
```

Output: `string 'foo' (length=3)`

This behavior comes from the following line in the core/Router.php file: https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/Router.php#L415.

Does somebody know, how I can fix this? Thank you 😊

**Comment by narfbg** [comment]
This idea was dismissed at some point and I guess we didn't properly update the docs - fixed that in the above referenced commit.

However, the last line in your description gives the impression that you came here just looking for help ... Please note that we only handle bug reports here.
