### ISSUE TITLE
CI3.x, CI_Security::get_random_bytes(): Consider random_bytes() in PHP7 as a possible option too.

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#4260]
PHP7 introduces the function random_bytes() http://php.net/manual/en/function.random-bytes.php and they claim that it "Generates cryptographically secure pseudo-random bytes". If so, CI_Security::get_random_bytes() could test presence of random_bytes() (maybe combined with a PHP7+ test) and try to use it first.

For not breaking the logic of CI_Security::get_random_bytes(), the exceptions that random_bytes() might trigger have to be captured, so, if random_bytes() can not do the job, the other existing alternatives to be tried, before giving up and returning FALSE.

Edit: Sample usage: https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/Random.php#L59

**Comment by narfbg** [comment]
This has been in my todo list for awhile.

**Comment by ivantcholakov** [comment]
Likely there is one more spot, the function password_hash(), about $options['salt'], system/core/compat/password.php

**Comment by ivantcholakov** [comment]
Sorry, it is not.

**Comment by ivantcholakov** [comment]
A second thought about the password_hash() fallback implemetation: I think a check for random_bytes() also would be nice in order the project https://github.com/paragonie/random_compat to be applicable.

Within the Encryption library I can see these lines for second consideration, random bytes generation can be unified:
https://github.com/bcit-ci/CodeIgniter/blob/3.0.6/system/libraries/Encryption.php#L403
https://github.com/bcit-ci/CodeIgniter/blob/3.0.6/system/libraries/Encryption.php#L466

---------------------------------------

Maybe a single function within Common.php would do the job for the other places?

**Comment by narfbg** [comment]
The single function is called ``random_bytes()`` ... people shouldn't be taught to use a different one.
