### ISSUE TITLE
php5.6 upload.php file_ext: xlsx ERROR: upload_invalid_filetype

### ISSUE THREAD

**Issue by zming619** [bcit-ci/CodeIgniter#4266]
nginx version: nginx/1.8.0
php-fpm version:5.6.15
CI version: /**
 * CodeIgniter Version
 *
 * @var string
 *
 */
        define('CI_VERSION', '3.0.0');

now, i can see ; 

// php
var_dump($_FILES);

array(5) {
  ["name"]=>
  string(29) "data.xlsx"
  ["type"]=>
  string(65) "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  ["tmp_name"]=>
  string(14) "/tmp/phpGLl6GF"
  ["error"]=>
  int(0)
  ["size"]=>
  int(30455)
}

// CI 3.0.0
system/library/Upload.php line: 1205;  
$mime = @finfo_file($finfo, $file['tmp_name']);

echo $mime;  // value is application/octet-stream; charset=binary

// Is the file type allowed to be uploaded?
if ( ! $this->is_allowed_filetype())
{
	$this->set_error('upload_invalid_filetype');
	return FALSE;
}

What should I do？

**Comment by zming619** [comment]
My OS : CentOS release 6.7 (Final) x86_64

**Comment by narfbg** [comment]
Ask your questions on the [forums](http://forum.codeigniter.com/) please, this is a bug tracker.

(and no, this isn't a bug)

**Comment by zming619** [comment]
bug or not bug???

**Comment by narfbg** [comment]
isn't = is not

**Comment by zming619** [comment]
can you help me?

**Comment by narfbg** [comment]
NO! Post your question on the [forums](http://forum.codeigniter.com/)!
