### ISSUE TITLE
PHP 5.3.29 CodeIgniter

### ISSUE THREAD

**Issue by tru3d3v** [bcit-ci/CodeIgniter#4276]
Anyone have an information what version CodeIgniter for PHP 5.3.29 ?

**Comment by jim-parry** [comment]
github is for bugs. support issues should be asked on forum.codeigniter.com

Per https://github.com/bcit-ci/CodeIgniter#server-requirements, the minimum version for CodeIgniter 3 is 5.2.4, so it will also work on 5.3.29. We recommend PHP 5.5 or later.
