### ISSUE TITLE
is_supported with memcached error

### ISSUE THREAD

**Issue by Kaabi** [bcit-ci/CodeIgniter#4277]
using is_supported with memcached driver is getting fatal error since CI 3.0.1 or above
currently testing on CI 3.0.3 is only return fatal error due to new addServer function

Code
```
if (!$this->cache->memcached->is_supported())
        {
            echo "Not Supported";
        }
```

Result

```
Fatal error: Call to a member function addServer() on a non-object in /var/www/box/system/libraries/Cache/drivers/Cache_memcached.php on line 130
A PHP Error was encountered

Severity: Error

Message: Call to a member function addServer() on a non-object

Filename: drivers/Cache_memcached.php

Line Number: 130
```

**Comment by Filisko** [comment]
$this->load->driver('cache');
if ($this->cache->memcached->is_supported())
{
    echo "Ok";
}

Does that work to you?

**Comment by Kaabi** [comment]
@narfbg if you punishing @bjjay why you close this issue while you didn't merge #4376, do I have to create new Issue ?

**Comment by narfbg** [comment]
How is this issue closed?

**Comment by Kaabi** [comment]
@narfbg sorry mybad I get confused between this and other issue though both closed

**Comment by cmeenatchisundaram** [comment]
@narfbg
Do we require to load the driver like below before using the is_supported() function...
$this->load->driver('cache', array('adapter' => 'memcached'));

**Comment by narfbg** [comment]
No.

**Comment by cmeenatchisundaram** [comment]
@narfbg 
   I looked on the properties of $this obj. But there is no cache object on it when i am trying to use in controller. So i felt that, need to load the cache object. 

I too got the error when i am trying to use it directly like below : 

if(!$this->cache->memcached->is_supported()){
}

Could you tell me, What to do if we don't require to load the cache obj?

**Comment by narfbg** [comment]
What do you mean what to do? It's a bug report, obviously something doesn't work right.

**Comment by cmeenatchisundaram** [comment]
This means, Is the $this obj suppose to have the cache obj? I am trying to fix this issue.

**Comment by narfbg** [comment]
There's a pull request referenced above that contained a fix, object instances have nothing to do with it.

**Comment by narfbg** [comment]
#4066 is relevant.
