### ISSUE TITLE
Session Driver Warning on my Server.

### ISSUE THREAD

**Issue by pateltejasmca** [bcit-ci/CodeIgniter#4280]
A PHP Error was encountered

Severity: Warning

Message: unlink(/tmp/ci_session0a3110c1f5608726f2c4de8893ae51497a3ce53c): Operation not permitted

Filename: drivers/Session_files_driver.php

Line Number: 354

Backtrace:

File: /home/matrimonialdevsa/public_html/index.php
Line: 292
Function: require_once

**Comment by afbora** [comment]
Do you checked out?

http://stackoverflow.com/questions/29278597/codeigniter-session-error-unlink-operation-not-permitted

**Comment by pateltejasmca** [comment]
Thnks man @afbora
