### ISSUE TITLE
Pass vaiables between views

### ISSUE THREAD

**Issue by shanavas786** [bcit-ci/CodeIgniter#4282]
Scenario: adding an element in view 1. Say <p id='a'> </p>. 
I would like to add some JavaScript code for handling say click event on the above element. 
I want the javascript code to be added to the footer which is defined in view 2.

My suggestion is to create a static class variable which can be used to pass data between views.

**Comment by jim-parry** [comment]
Any such javascript code is part of your view, and nothing to do with the framework.
If you are looking for comments or suggestions, please raise the topic on forum.codeigniter.com.
