### ISSUE TITLE
Missing argument 1 for alternator()

### ISSUE THREAD

**Issue by chalda-pnuzig** [bcit-ci/CodeIgniter#4283]
In userguide: 
> To use multiple separate calls to this function simply call the function with no arguments to re-initialize.

But in string_helper there is:
```php
	function alternator($args)
```
Please change it with 
```php
	function alternator()
```
Thanks

**Comment by jim-parry** [comment]
Your suggestion would break alternator(). If you are looking for method/function overloading, not supported in PHP.
What *is* missing is a unit test for alternator() in the string_helper.

**Comment by narfbg** [comment]
Wouldn't break it ... the declared parameter is ignored and the function uses `func_get_args()` instead.

**Comment by chalda-pnuzig** [comment]
Thanks
