### ISSUE TITLE
Feature request: Tinyint as boolean

### ISSUE THREAD

**Issue by jzafrilla** [bcit-ci/CodeIgniter#4285]
Hi, recently i have to use tinyints fields as a boolean. I use codeigniter-rest-server and in my json reponses tinyint values must be represented as "true|false".

I had to edit DB_Result.php to process the result using field_data():

```
foreach($obj as $key => $value){
	foreach($fieldTypes as $field){
		if($field->name==$key&&$field->type==1){ //TINYINT
			if($obj->$key!=null&&$obj->$key==1){//value = 1
				$obj->$key=true;
			}else{ //  [NULL|false|ohter values]
				$obj->$key=false;
			}
		}
	}
}
´´´
Do you think this behavior must be in the config file from database.php|config.php| etc? What do you think about it?

**Comment by jim-parry** [comment]
There is no rest-server in the framework.
If you need different behaviour than provided, you might look at extending DB_Result ... http://www.codeigniter.com/user_guide/general/core_classes.html#extending-core-class
If you have issues using your rest-server, raise them on forum.codeigniter.com
