### ISSUE TITLE
unescape mysqli query

### ISSUE THREAD

**Issue by faiyip** [bcit-ci/CodeIgniter#4288]
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Welcome extends CI_Controller {

	public function demo( ){
		$this->load->database();

		
		print( "<pre>" );
		$c = new TestClass( "hello" );
		print( "the string value of c is : ". $c ."\n");
		
		$sql = "SELECT ? ";
		
		$this->db->query( $sql, array( $c ) );
		
		print( $this->db->last_query( )."\n" );
		print( $this->db->_error_message( )."\n" );
/*
from config.
	define('CI_VERSION', '2.2.5');
	$db['default']['dbdriver'] = 'mysqli';
the above will produce "SELECT hello";
the argument hello is not escaped, which is a security issue
this only happened to class that has a __toString method.
*/
		

		$xml_string = "<xml><abc><![CDATA[x123456789]]></abc></xml>";
		
		print( htmlspecialchars( $xml_string )."\n" );
		
		$xml = @simplexml_load_string( $xml_string, 'SimpleXMLElement', LIBXML_NOCDATA );
		//because SimpleXMLElement has toString method
		var_dump( $xml );
		
		//because SimpleXMLElement has toString method
		var_dump( $xml->abc );
		
		$sql = "SELECT ? ";
		$this->db->query( $sql, $xml->abc );
		print( $this->db->last_query( )."\n" );
		print( $this->db->_error_message( )."\n" );
		
		print( "</pre>" );
		
/*
http://php.net/manual/en/simplexmlelement.tostring.php
*/
	}
	
}

class TestClass
{
    private $foo;

    public function __construct($foo)
    {
        $this->foo = $foo;
    }

    public function __toString()
    {
        return $this->foo;
    }
}

/* End of file welcome.php */
/* Location: ./application/controllers/welcome.php */

**Comment by narfbg** [comment]
CodeIgniter 2.x is no longer supported.
