### ISSUE TITLE
sess_expire_on_close

### ISSUE THREAD

**Issue by dejurin** [bcit-ci/CodeIgniter#4290]
I know, what in 3 version this param sess_expire_on_close was delete.
How remove session after close browser?
Okay. I know if set config sess_expiration = 0 session close ...

but if I make

$this->config->set_item('sess_expiration', 0);
$this->load->library('session');

not work, load only 
$config['sess_expiration'] = 600; --> config.php
![2015-12-06 01 30 06](https://cloud.githubusercontent.com/assets/4470015/11610863/f04ad9e6-9bb8-11e5-9c9a-9a6fe1dc486f.png)
config.php
![2015-12-06 01 31 14](https://cloud.githubusercontent.com/assets/4470015/11610865/12f7d7c8-9bb9-11e5-927c-601b1f3264d2.png)
but when I show var_dump($this->config->item('sess_expiration')); I see  = 0, but if I close browser and open again session live..., if I change sess_expiration = 0 in config.php file - session die after close browser.

**Comment by jim-parry** [comment]
github is for bugs. Ask support questions on forum.codeigniter.com, thanks.
