### ISSUE TITLE
3.0.3 mysqli扩展 写法问题导致内存溢出

### ISSUE THREAD

**Issue by xuj** [bcit-ci/CodeIgniter#4295]
3.0.3 mysqli扩展目录下mysqli_driver.php第168行 有这样的写法：
empty($mysqli->query("SHOW STATUS LIKE 'ssl_cipher'")->fetch_object()->Value)
这个方法有时返回的数据过于庞大，会返回
ERROR - 2015-12-05 07:08:26 --> Severity: Error --> Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) /system/database/drivers/mysqli/mysqli_result.php 168

**Comment by jim-parry** [comment]
Use English, please. We have no idea what you are trying to say.
If this is a support issue, raise it on forum.codeigniter.com, as github is for bugs.

**Comment by doubone** [comment]
@hyxj1220  我也遇到了内存泄漏的问题，报错和你发的一样。 在环境上注释了这行发现还是在报错？？？
