### ISSUE TITLE
"duplicate db instances in profiler"

### ISSUE THREAD

**Issue by michail1982** [bcit-ci/CodeIgniter#4301]
in MY_Model (https://github.com/jamierumbelow/codeigniter-base-model) local database instances stored in varible $_database, so when profiler compile databases I got count(MY_Model instances)  + 1 databases.
I add before https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Profiler.php#L216 
```php
foreach ($dbs as $dbo) { if ($dbo===$mobject) { continue 2; } }
```
i Gues it`s would be helpful

**Comment by narfbg** [comment]
Please post such things on the [forums](http://forum.codeigniter.com/) and not here ... this is neither a bug report, nor a (viable) feature request.
