### ISSUE TITLE
limit and offset mssql driver problem

### ISSUE THREAD

**Issue by raku** [bcit-ci/CodeIgniter#4306]
Using this:
<pre><code>protected function _version()
	{
		return 'SELECT VERSION() AS ver';
	}</code></pre>

for getting sql server version is wrong.

This will return you a version like:

<pre><code>Microsoft SQL Server 2012 (SP1) - 11.0.3128.0 (X64) 
	Dec 28 2012 20:23:12 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: )</code></pre>

and this will always return false on version_compare().

I propose to use this:

<pre><code>public function version()
	{
                if (isset($this->data_cache['version']))
		{
			return $this->data_cache['version'];
		}

		$query = $this->query("SELECT left(cast(serverproperty('productversion') as varchar), 4) AS ver")->row();
		return $this->data_cache['version'] = $query->ver;
	}</code></pre>

**Comment by narfbg** [comment]
Thanks for reporting the issue, the fix is referenced above.

However, please be more accurate next time ... I just spent 20 minutes testing what `VERSION()` returns (which is what you wrote) while we actually used `@@VERSION`.

**Comment by raku** [comment]
sorry, my bad
