### ISSUE TITLE
Table set_template is not doing anything

### ISSUE THREAD

**Issue by DSMatichuk** [bcit-ci/CodeIgniter#4307]
I've been struggling get set_template working for hours. I cannot find any examples of it working and it is definitely not doing anything on my server. It actually has no effect at all. It is as if I did not set it. I only get the default table settings which are rally bad. I hope someone has a clue what I should do or how to trouble shoot this.

**Comment by narfbg** [comment]
There are examples in the official documentation.

Please post such questions on the [forums](http://forum.codeigniter.com/) instead, this is a bug tracker.

**Comment by DSMatichuk** [comment]
narfbg, I learned it from the official documentation which only shows a single line of code to alter the template. I did that and the modification did not make it into the result and the official documentation does not suggest anything I could do different. It must be a bug because there is only one way to do it and that one way does not get a result.

**Comment by jim-parry** [comment]
@DSMatichuk Post your question on forum.codeigniter.com, with your code that isn't working. I suspect several people will have suggestions.

**Comment by DSMatichuk** [comment]
Posted 2 days ago. No response. One person told me to set the template first, which is not helpful because my code clearly shows that I'm setting the template according to the documentation. So, I think its a bug.

**Comment by DSMatichuk** [comment]
http://forum.codeigniter.com/thread-63827.html

**Comment by narfbg** [comment]
I can't reproduce it - it's not a bug.
