### ISSUE TITLE
Upload Class gives wrong width and height if portrait image uploaded

### ISSUE THREAD

**Issue by jonnydevv** [bcit-ci/CodeIgniter#4308]
![_mg_2121](https://cloud.githubusercontent.com/assets/2188826/11716051/9a89b3fc-9f36-11e5-86da-c24b6eb7491c.JPG)
I don't know wheter a bug or not but after upload a portrait image, it gives me the width and height and a landscape image. Image is uploaded correctly, but i need to know the width and height, so i can use image_lib library to make diferente sizes copies of uploaded image.

        $this->CI =& get_instance();
        $this->CI->load->library('upload');

        $image = array();
        $this->CI->load->library('image_lib');
        $this->CI->upload->initialize($this->set_tmp_upload_options($folder));

        if (!$this->CI->upload->do_upload('fileinput'))
        {
            return false;
        }
        else
        {
            $image_data = $this->CI->upload->data();
            $filename = $this->CI->upload->data('file_name');
            $image = array('file_name' => $filename);

            $origWidth = $image_data['image_width'];
            $origHeight = $image_data['image_height'];}

**Comment by narfbg** [comment]
Without the image itself provided, I can't verify this.

**Comment by jonnydevv** [comment]
I've update post with image.
Thanks in advance.

**Comment by narfbg** [comment]
I didn't want a 6MB image to be directly *displayed* in the issue here, but that does actually help - even here it is displayed as a landscape photo.

Also:

    php > var_dump(exif_read_data('https://cloud.githubusercontent.com/assets/2188826/11716051/9a89b3fc-9f36-11e5-86da-c24b6eb7491c.JPG')['Orientation']);
    int(8)

Look-up that '8' value [here](http://www.impulseadventure.com/photo/exif-orientation.html) and you'll see that there is the necessary info to tell you that the image should be rotated, but that's just outside of the scope for a file uploading class.

**Comment by jonnydevv** [comment]
Oh i see. I didn't want to be resizing image to avoid losing any propeties/meta from image that's why a 6mb image. Thank you very much

**Comment by narfbg** [comment]
Yea, the metadata was what I wanted to look at, so it's a good thing you didn't resize it. What I meant was that a link to an external URL with the image is generally better - just FYI.
