### ISSUE TITLE
Change output cache folder 

### ISSUE THREAD

**Issue by eusdb** [bcit-ci/CodeIgniter#4309]
in the constructer of a controller class, i try to change the cache folder:  

     public function __construct() {
                parent::__construct();
                $this->config->set_item('cache_path', APPPATH. '/cache/cards/');
                $this->output->cache(7200);

The files are created in the desired folder. The cache files are however not used but newly generated at each request.

**Comment by narfbg** [comment]
You can't change the cache path at this point ... cached output is detected before controllers (and when that happens, it is still using the value from your config.php), because that's the whole point - not to execute dynamic logic if the response is already cached.
