### ISSUE TITLE
CI_DB_driver missing error() function signature

### ISSUE THREAD

**Issue by lkho** [bcit-ci/CodeIgniter#4313]
this function is being called within the class but does not have a proper declaration, i.e.:
```
    /**
     * Error
     *
     * Returns an array containing code and message of the last
     * database error that has occurred.
     *
     * @return    array
     */
    public function error()
    {
        return array('code' => NULL, 'message' => NULL);
    }
```
this cause problems to auto-completion and warnings emitted by IDEs.

**Comment by narfbg** [comment]
Added, but just for the record - IDEs needing something is horrible reasoning.
