### ISSUE TITLE
A PHP Error was encountered - touch()

### ISSUE THREAD

**Issue by dylanpiera** [bcit-ci/CodeIgniter#4316]
A PHP Error was encountered

Severity: Warning

Message: touch(): Unable to create file ci_session\ci_session4d6e9678ca4ae1f1c37eea97d52656357d938e39 because No such file or directory

Filename: drivers/Session_files_driver.php

Line Number: 234

Backtrace:

Any idea what might be wrong?

**Comment by afbora** [comment]
https://github.com/bcit-ci/CodeIgniter/issues/3664

**Comment by narfbg** [comment]
Please post your questions on the [forums](http://forum.codeigniter.com/) instead, this is a bug tracker.
