### ISSUE TITLE
File session expires randomly?

### ISSUE THREAD

**Issue by it-can** [bcit-ci/CodeIgniter#4317]
It seems that since last updates the file sessions randomly expire? Anyone else experiencing this?

**Comment by narfbg** [comment]
What do you mean by "last updates"?

**Comment by it-can** [comment]
commits since 11 dec 2015

**Comment by narfbg** [comment]
That doesn't really answer my question. I don't know which branch you are using, nor the last time you've pulled commits ... And if the Redis driver is fine, you're obviously not talking about all the drivers too, and I don't know which one you're talking about.

Also, do you not have any error logs?

**Comment by it-can** [comment]
develop... no error logging... Seems just to expire..

**Comment by narfbg** [comment]
Don't use develop; use 3.0-stable.

**Comment by it-can** [comment]
3.0-stable has the same session changes as develop right?

**Comment by narfbg** [comment]
No, it's not the same ...

**Comment by it-can** [comment]
I see this error now:

```
A PHP Error was encountered

Severity: Warning

Message: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/Applications/MAMP/tmp/php)

Filename: Unknown

Line Number: 0

Backtrace:
```

**Comment by narfbg** [comment]
You're not supposed to leave it to null ...
Is there really no backtrace or did you just leave that part out?

**Comment by narfbg** [comment]
And the directory needs to be writable as well ...

**Comment by it-can** [comment]
It is writable and all, and there was no backtrace... weird huh...

**Comment by narfbg** [comment]
And no logs? (I supposed you do have turned them on)

Help me out here, this will go on forever if I have to ask you specific questions for every little detail ... can you do some manual debugging? This message means that `CI_Session_files_driver::write()` returns `$this->_failure`, but there are multiple conditions that can cause that.

**Comment by it-can** [comment]
ok will try to find some stuff, logging doesn't show anything at this point

**Comment by ivantcholakov** [comment]
@narfbg When I commented yesterday or the other day, I experienced the same symptoms: Sudden session expiration and the error "Failed to write session data (user).". But I did not reported them, sorry.

You have already fixed this in 3.0-stable branch.

**Comment by ivantcholakov** [comment]
This commit: https://github.com/bcit-ci/CodeIgniter/commit/bb71dbadb7441a97a09e1e6d90fbddc884af67d1

After it the described problems disappeared in my place.

This one is not related, but should be implemented in develop branch too: https://github.com/bcit-ci/CodeIgniter/commit/2d6d9ab0bfeb546d8c9d7924af7ccc095f798e41

**Comment by narfbg** [comment]
*Nobody* is supposed to use develop and it would be really annoying if I had to push every commit twice, which is why I'm only periodically merging from 3.0-stable into develop. The only reason why it is the default branch is so that I don't have to tell everybody that they need to submit their BC-breaking pull requests to another branch.

**Comment by it-can** [comment]
ok @narfbg will switch to 3.0-stable ;-) Thanks btw

**Comment by narfbg** [comment]
I thought you switched and *then* showed me that error message, no?

**Comment by it-can** [comment]
Nope, always used develop on my projects but will switch to 3.0-stable to be on the safer side of things
