### ISSUE TITLE
empty post on routed page

### ISSUE THREAD

**Issue by jayjfletcher** [bcit-ci/CodeIgniter#4321]
Hello, 

Using 3.0.3, I noticed that if I have a form submit to a routed page the $_POST comes back as empty.

for example
//route file
```php
$route['contactus'] = 'controller/method';
```
//form
```html
<form action="http://localhost/contactus/" method = "post">

```
submitting such a form will give me an empty $_POST and input->post

is this by design?

If I switch the action to a non routed page, it works fine.

**Comment by jayjfletcher** [comment]
I've found that it's actually a server issue, although I'm not sure what's causing the issue.

Tried on WAMP and EasyPHP
Works on EasyPHP but not WAMP. 

Just can't pinpoint the difference in server config that would cause this. 

Any ideas?

**Comment by narfbg** [comment]
Please post such questions on the [forums](http://forum.codeigniter.com), this is a bug tracker.
