### ISSUE TITLE
current_url() error

### ISSUE THREAD

**Issue by xingweiboy** [bcit-ci/CodeIgniter#4325]
My url is "http://localhost/orange/", but  the current_url() returns "http://::1/orange/index.php"

**Comment by kenjis** [comment]
It is not a bug.
See https://codeigniter.com/user_guide/installation/upgrade_303.html#step-2-make-sure-your-base-url-config-value-is-not-empty

**Comment by jim-parry** [comment]
Post support questions on forum.codeigniter.com
We use github for bug tracking
