### ISSUE TITLE
unserialize(): Error at offset 0 of 131 bytes

### ISSUE THREAD

**Issue by JCSama** [bcit-ci/CodeIgniter#4326]
I've got this notice when I try to read data from cache using file cache adapter:
```php
$this->cache->get('file_id');
Result : 
Severity: Notice
Message: unserialize(): Error at offset 0 of 131 bytes
Filename: drivers/Cache_file.php
Line Number: 276
```

**Comment by narfbg** [comment]
That means the data in the cache file is corrupted, but I don't see how this could be caused by CI.

**Comment by JCSama** [comment]
the cache file was created by cache class `$this->cache->save('file_id', $some_data);` so it's related to CI

**Comment by narfbg** [comment]
I'm not saying it's not related to CI, I'm saying I don't see how could it be *caused* by CI - that's a different thing. And not to be offensive, but please don't use such rhetorical arguments ... It's the same as saying "My car broke while it was on this road, therefore it's the road's fault".

There are a lot of things that you can do to corrupt a file and feel free to prove me wrong, but I just don't see how `CI_Cache` could've done that.
