### ISSUE TITLE
update_string (and possibly others) clobber SQL with backticks in 3.0.1 (worked fine in 2.x)

### ISSUE THREAD

**Issue by QuakePhil** [bcit-ci/CodeIgniter#4329]
Consider this snippet:

    $sql = $this->db->update_string('test', array('column' => 'value'), 'id = ?');

It will generate

    $sql = "UPDATE `test` SET `column` = 'value' WHERE `id` = `?`"

which then becomes something like

    "UPDATE `test` SET `column` = 'value' WHERE `id` = `10`"

Mysql will then error out with "Unknown column 10" because the value in the where clause is backticked in error.

**Comment by QuakePhil** [comment]
I have fixed this here https://github.com/QuakePhil/CodeIgniter/commit/273a818ac98568404339ebb228d03e14e149e084

and issued a PR

**Comment by narfbg** [comment]
I don't understand how that question mark becomes a 10?
