### ISSUE TITLE
mysqli db_driver can't return connect error code and message

### ISSUE THREAD

**Issue by namjeongho** [bcit-ci/CodeIgniter#4331]
I can't get mysqli connect error code and message, when connection error occurs.

In mysqli_driver.php
Codeigniter use $this->conn_id variable in error() method like below
      $this->conn_id->connect_errno

But not assign the mysqli object to $this->conn_id in db_connect() method when connection fails.
So mysqli db driver's error() method can't return connect_errno and connect_error.

**Comment by namjeongho** [comment]
I think DB_driver's member variable '$conn_id' should be preserved to get conn_id->connect_errno event though connection fails.

**Comment by mwhitneysdsu** [comment]
mysqli_driver's [error method](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/drivers/mysqli/mysqli_driver.php#L452) checks whether `$this->conn_id->connect_errno) is empty, but never checks whether `$this->conn_id` itself is false. If it did this, it could either attempt to use `mysqli_connect_errno()` and `mysqli_connect_error()` to get the error information, or get the error number/message when the connection fails and store it in a private property to be retrieved when error() is called and `$this->conn_id === FALSE`.

Also, `simple_query()` in [DB_driver](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_driver.php#L730) doesn't check the result of `$this->initialize()` (which returns FALSE in the case of a connection error) before calling `$this->_execute($sql)`, which, at least in the MySQLi driver, doesn't check whether `$this->conn_id` is false before calling `$this->conn_id->query()`.

**Comment by narfbg** [comment]
Fixed with the above-referenced commit.

@mwhitneysdsu You're linking to the develop branch which is for 3.1-dev and was recently changed to throw exceptions instead of returning FALSE.
