### ISSUE TITLE
Long get_lock times with 3.0.1

### ISSUE THREAD

**Issue by QuakePhil** [bcit-ci/CodeIgniter#4332]
Seeing long times for get_lock sometimes:

    6.1876  	SELECT GET_LOCK('63cae926484ea98ca6466ec10c1979b225d1af32', 300) AS ci_session_lock 

Other times it completes in 0.0x seconds.  There are at most 2 users using this particular build.

Can someone please drop some clues as to what gives?  CI 3.0.1

**Comment by narfbg** [comment]
Are you reporting a bug or ...?

If so, please provide more information.
If not, please close the issue and post on the [forums](http://forum.codeigniter.com/) instead - we don't provide general support here.
