### ISSUE TITLE
Why base_url definition in core/config.php use SERVER_ADDR instead of SERVER_NAME?

### ISSUE THREAD

**Issue by codecrafting-net** [bcit-ci/CodeIgniter#4341]
I was wondering why the base_url definition in core/config.php use `$_SERVER['SERVER_ADDR']` instead of `$_SERVER['SERVER_NAME']` ? Some servers don't provide by default the SERVER_ADDR to php, and why use ip instead of name?

**Comment by narfbg** [comment]
This is not a Q&A website but a bug tracker.
Ask similar questions on the [forums](http://forum.codeigniter.com/) instead.
