### ISSUE TITLE
Check file name before upload

### ISSUE THREAD

**Issue by circuitmamu** [bcit-ci/CodeIgniter#4344]
My permitted url characters set in config is as per below
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

So when I upload the file via up-loader 
$config['file_name'] = $filedetails['filename']['name'];
$this->upload->initialize($config);

So I want to check that if file name has a permitted characters or not if not then is any function to change non permit-able characters to any allowed characters

As Example
File Name : example-file-name#7.jpg
In this example # and - is special characters but # is not allowed so before upload or copy the file to server I just want to change whatever non acceptable characters to my allowed character

If I change those characters from # to _ that is not acceptable
New File : example-file-name_7.jpg

Is those function is available then please let me know via quick reply

**Comment by narfbg** [comment]
Sorry, but we don't provide support here - we only accept bug reports.
Please post your questions on the [forums](http://forum.codeigniter.com/) instead.
