### ISSUE TITLE
Session cookie is being set for every AJAX call

### ISSUE THREAD

**Issue by xa0c** [bcit-ci/CodeIgniter#4348]
Hi CI team.
Just noticed that all server replies for AJAX requests contain session cookie. Is it how it supposed to work?

**Comment by jim-parry** [comment]
This "issue" is not a bug, but a misconfiguration. It has been brought up numerous times on forum.codeigniter.com

**Comment by xa0c** [comment]
You mean CI misconfiguration?
Here is my cfg:
````php
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'web_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;
````
I guess its all defaults, except custom session name.

I've checked forums, and what I've understood is that people had problem with session being expired. And that https://github.com/bcit-ci/CodeIgniter/commit/ff37ffe164443e53b24d529f967a1bdf065bff3a commit fixed that. I tried to disable that check for ajax origin, to see how regeneration works for ajax. I waited for 'sess_time_to_update' timeout and sent ajax request. The reply from server didn't contain Set-Cookie header. But if immediately after 1st request I'll send another one (in 5 seconds for example) the reply will contain Set-Cookie header with regenerated session.

So is it a problem in my CI config? Or its something php-core related? Or CI_Session?
Thanks.

**Comment by jim-parry** [comment]
Your session save path is NULL, which is wrong. It needs to name to folder where cookies should be saved. Trying to write to NULL will fail, so the session is reset for each call. This was the solution for several of the threads on the forum.

**Comment by xa0c** [comment]
Just checked CI internals. If session_save_path is NULL it just gets value from `ini_get('session.save_path')`
Anyway, I tried to specify path in config. Nothing changed. I still get Set-Cookie headers in server replies for every ajax request.
I guess we have misunderstood each other. I don't have session expiration issue. I just get new session cookies for every ajax request.
