### ISSUE TITLE
about core/Common.php load_class for 3.03

### ISSUE THREAD

**Issue by hongbin-hsu** [bcit-ci/CodeIgniter#4350]
Cannot instantiate abstract class MY_Model in

whan i setting abstract class in project core;

<h4>A PHP Error was encountered</h4>
    <p>Severity: Error</p>
    <p>Message:  Cannot instantiate abstract class MY_Model</p>
    <p>Filename: core/Common.php</p>
    <p>Line Number: 196</p>
    <p>Backtrace:</p>

**Comment by jim-parry** [comment]
Support questions should be asked on forum.codeigniter.com.
fwiw, CodeIgniter does not support abstract classes directly.

**Comment by narfbg** [comment]
How's that?

Btw, please don't write "3.03" ... I see that a lot, it's 3.0.3 - three separate numbers.

**Comment by ivantcholakov** [comment]
IMO the whole new fragment
if ( ! class_exists('CI_Model', FALSE)) { ... }
would be nice to be implemented as a separate protected method _load_system_model_classes() or sort of.

The fragment contains paths, scanning for files may be customized conveniently with overriding this separate method, without touching the system file.

**Comment by narfbg** [comment]
I was just asking if the issue is resolved for the OP ... I just tested manually and it works.

As for your suggestion, I did think about that before writing the patch and I don't see the point in doing that.

**Comment by ivantcholakov** [comment]
I use HMVC with customizations, I needed to touch the system file while embracing this change. For me personally it is not a big deal, ok.

**Comment by narfbg** [comment]
Not that I care about HMVC, but why and how did you manage this change previously? Rewriting `load_class()`?

**Comment by ivantcholakov** [comment]
Sorry for posting links to my repository, but this is the easiest way to show what I did.

Directly within the system file: Here is the additional method with customization, I have an additional path to check:
https://github.com/ivantcholakov/starter-public-edition-3/commit/fd5bf3ad1d06d20806d70e63697e4aef37b3e359

Here I apply the new method on HMVC code:
https://github.com/ivantcholakov/starter-public-edition-3/commit/7527017399ed81d90feb32475d96ea12cf140e5d

**Comment by ivantcholakov** [comment]
Hah, I saw a mistake of mine in the second commit, I did not replace a fragment fully. It is not important topic here.

**Comment by ivantcholakov** [comment]
And yes, HMVC extends CI_Loader, the successor class is MX_Loader.

**Comment by narfbg** [comment]
It's not that hard to override ...

    public function model($model, $object_name = NULL, $connect = FALSE)
    {
        class_exists('CI_Model', FALSE) OR $this->_load_system_model_classes();
        return parent::model($model, $object_name, $connect);
    }

**Comment by ivantcholakov** [comment]
I will try your suggestion.

**Comment by ivantcholakov** [comment]
It is something similar, in my particular case I simply moved the custom method within the successor class. Also I tested the new code on an application with database, it works.

So, my suggestion was not needed, your code if fine. Thank you, @narfbg
