### ISSUE TITLE
file upload doesn't allow .xlsx file in linux

### ISSUE THREAD

**Issue by roaminghome** [bcit-ci/CodeIgniter#4351]
I searched for this issue and tried every fixes that are discussed here. But no fix works. The file uploading class gives an error of "The filetype you are attempting to upload is not allowed.". The same works on windows platform, but not on linux. Is there any specific reason for this?

**Comment by narfbg** [comment]
Please note that this is a bug tracker, not a StackOverflow-like forum where you'd seek help.
