### ISSUE TITLE
Call Hook & Pass Data

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter#4356]
I use the hooks library in my own packages, but I would like to pass data to some of these hooks. I'm considering making the changes in the hooks class and then doing a pull request.

Is this something other people would find useful? I've never done these changes to an open source project before.

**Comment by narfbg** [comment]
What do you mean by that exactly? Hooks already have definable parameters to use.

**Comment by EpicKris** [comment]
```
$hook_data = 'Pass data to hook for hook to process.';

$EXT->call_hook('custom_hook', $hook_data);
```

I hope this clears things up a bit, so that it is possible to pass extra data when calling a hook, as far as I'm aware this isn't something that's currently possible?

**Comment by narfbg** [comment]
I asked for "exactly", not for "a bit" ... :)

But regardless, how'd you solve the conflict between configuration-defined parameters and those that you want to pass to `call_hook()` (which is an undocumented method btw, you're not supposed to rely on it)?

**Comment by EpicKris** [comment]
I'm at work at the moment, but essentially the second parameter of the function handling the hook has the hook data that's passed through the `call_hook` function.

I'll show an example later today or tomorrow to demonstrate what I'm trying to accomplish.

**Comment by narfbg** [comment]
I can see that from your example above ... that doesn't answer my question.

**Comment by EpicKris** [comment]
I guess I don't fully understand what you're asking... sorry. Since it's undocumented and shouldn't be relied on, is there a better alternative to what I am attempting to do, it seems like hooks are what I'm looking for but are only available to the core system?

**Comment by cristiantantar** [comment]
I think @EpicKris want an Event Dispatcher like system and he misunderstood the Hooks. 
Read carefully: http://www.codeigniter.com/user_guide/general/hooks.html
You want something like this: https://github.com/nathanmac/CodeIgniter-Events

**Comment by EpicKris** [comment]
What @cristiantantar commented seems like what I'm looking for, it seems very similar to hooks, could something like this be part of CodeIgniter? I'd be willing to create it.

**Comment by narfbg** [comment]
What I'm asking is how would you solve the possible *conflict* between parameters defined in config/hooks.php and those that you'd pass via `call_hook()`.

For example, if you've got this:

    $hook['foo'] = array(
            'class'    => 'Someclass',
            'function' => 'foo',
            'filename' => 'Someclass.php',
            'filepath' => 'hooks',
            'params'   => array('bar')
    );

    // ... later on:

    $whatever->call_hook('foo', 'baz');

Would that hook use 'bar' or 'baz' as its parameter and why?

**Comment by EpicKris** [comment]
What I was thinking was to pass the parameters defined in the `config/hooks.php` as the first parameter and then pass the parameters that are passed via `call_hook()` as the second parameter.

```
function foo($data, $hook_data)
{
    $data; // 'bar'
    $hook_data; // 'baz'
}
```

**Comment by narfbg** [comment]
That resolves the conflict, but creates another problem - if I want to use your feature, I must define my hook functions with 2 parameters even if I only need one.

**Comment by EpicKris** [comment]
That's the same conclusion I've come to unfortunately, it could work by me merging the data and the hook data with the hook data being it's own key altogether.
```
function foo($data)
{
    $data;
    // array( 'bar', 'hook_data' => array( 'baz' ) )
}
```

Of course this could cause conflicts if `hook_data` happens to be a parameter defined in the `config/hooks.php`, but does minimise conflicts in the majority of use-cases.

**Comment by narfbg** [comment]
Yea, I'm not really happy with that ... conflicts need to be resolved, not just minimized. Plus, there are no conflicts currently - the proposed feature creates them.

**Comment by EpicKris** [comment]
A little more complicated, but what about passing the data depending on what data has been defined?

For parameters only defined in `config/hooks.php`:
```
function foo($data)
{
    $data; // 'bar'
}
```

For parameters only passed via `call_hook()`:
```
function foo($hook_data)
{
    $hook_data; // 'baz'
}
```

For parameters defined in `config/hooks.php` and passed via `call_hook()`:
```
function foo($data, $hook_data)
{
    $data; // 'bar'
    $hook_data; // 'baz'
}
```

**Comment by narfbg** [comment]
No ... if it doesn't always work the same way, it's bad.

Sorry, I don't see a way for this to be implemented sanely, without BC breaks. As @cristiantantar noted, you're trying to make a Hooks system work as an Event Dispatcher - two similar concepts, but different still.

To achieve the same effect, you can use an object to store that data (using a class for the hook), so it will be available to the hook function when it is called.

**Comment by EpicKris** [comment]
That's a fair assessment, what about implementing a native event dispatcher library instead of attempting to utilise the hooks system?

**Comment by narfbg** [comment]
That's something for CI4.
