### ISSUE TITLE
How to prevent Welcome page duplication

### ISSUE THREAD

**Issue by remotehelp** [bcit-ci/CodeIgniter#4359]
Welcome page duplication:
```http://mysite.local
http://mysite.local/welcome
http://mysite.local/welcome/
http://mysite.local/welcome/index
```
How to prevent Welcome page duplication for all controllers?

**Comment by narfbg** [comment]
This is a bug tracker, please ask your questions on the [forums](http://forum.codeigniter.com/) instead.
