### ISSUE TITLE
base_url 自动生成时由于使用了IP地址导致与域名不一致 for 3.03

### ISSUE THREAD

**Issue by zoujingli** [bcit-ci/CodeIgniter#4360]
base_url 自动生成时由于使用了IP地址导致与访问时域名地址不一致，程序将不再适用于Vhost服务环境运行，希望可以使用域名来生成 base_url，继续使用 HTTP_HOST 来代替 SERVER_ADDR

**Comment by jim-parry** [comment]
English, please.

**Comment by zoujingli** [comment]
If base_url is empty, Config will automatically generate this value, using SERVER_ADDR to replace the HTTP_HOST, resulting in the system link and access to the domain name of the link is not consistent. When using VHOST, there will be some inconvenience.
