### ISSUE TITLE
If base_url is empty,When using VHOST, there will be some inconvenience. for 3.03

### ISSUE THREAD

**Issue by zoujingli** [bcit-ci/CodeIgniter#4361]
If base_url is empty, Config will automatically generate this value, using SERVER_ADDR to replace the HTTP_HOST, resulting in the system link and access to the domain name of the link is not consistent. When using VHOST, there will be some inconvenience.

For example: 
access to http://localhost/,
base_url=http://127.0.0.1/ in the system

**Comment by kenjis** [comment]
It is specification for security, not a bug.
Set `http://localhost/` to `base_url`.

Please read http://www.codeigniter.com/user_guide/installation/upgrade_303.html#step-2-make-sure-your-base-url-config-value-is-not-empty
> Auto-detection is never reliable and also has security implications, which is why you should always have it manually configured!

**Comment by zoujingli** [comment]
Since the proposed manual configuration of base_url, the default configuration is naturally not important, but I still want to be able to retain access to the domain name, rather than the IP address.

**Comment by zoujingli** [comment]
I think this is not a serious security problem, if you really want to consider the domain name security, you can add a security domain name configuration items, if the configuration of the security domain name just to allow access to these domain names.

**Comment by narfbg** [comment]
Duplicate of #4209, #4226, #4231.
Won't be changed even if a thousand more people complain about it - security has higher priority.

**Comment by zoujingli** [comment]
I don't think using HTTP host will have security problems, if you insist to use IP to generate a URL, users can only to modify the framework to realize the automatic mechanism of the base URL, every project need to manually configure the domain name, seemed to be somewhat tasteless, for a server to say, in most cases not only run a project.

**Comment by aloMalbarez** [comment]
any hint on what are those "security implications"? 
If I develop my own autodetect for easy code sharing and deploy on multiple domins/paths it would be nice to know.

**Comment by narfbg** [comment]
It introduces a host header injection.

**Comment by aloMalbarez** [comment]
Thanks for the clarification, so I'm going to limit autodetection to dev/QA environments and enforcing config on production.
