### ISSUE TITLE
Codeigniter session error in Redis using PHP 7.0

### ISSUE THREAD

**Issue by degp** [bcit-ci/CodeIgniter#4362]
When I store session data in the Database, there are no errors. But if I switch to Redis, I get an error every time session tries to regenerate via session_regenerate_id, in my case every 300 sec. But if I refresh the page again, Redis get updated and page loads without errors.

    A PHP Error was encountered
    Severity: 4096
    Message: session_regenerate_id(): Failed to create(read) session ID: user (path: tcp://localhost:6379?auth=xxxx)
    Filename: Session/Session.php
    Line Number: 625

**Comment by narfbg** [comment]
Related to #4179.

@degp Can you confirm if the commit referenced above fixes the issue?

**Comment by degp** [comment]
@narfbg yes! it is working.

**Comment by skys215** [comment]
I'm facing same problem under PHP7.1.4, CI3.1.6-dev on macOS Sierra.

**Comment by victory7** [comment]
I have the same problem and also error "Unable to obtain lock for [sessionKey] after 30 attempts, aborting.
I'm on CI 3.1.9 (latest now), PHP 7.0.0 , php-redis 4.2.0 , redis 3.2.12 .
After acquiring this error the request waits for 30 seconds and after that my session is destroyed and the user is logged out.
This happening on different URLs.

**Comment by kaamoss** [comment]
I have also run into this exact same issue on PHP 7.2 and CI 3.1.9 , this is only an issue for me on concurrent ajax requests.

**Comment by ostrolucky** [comment]
Same here on PHP 7.0 and CI 3.1.10, also with concurrent ajax requests

**Comment by schmoove** [comment]
Has anyone found a resolution for the `Session: Unable to obtain lock for ci_session:xxx` issue?

We are also seeing this on PHP 7.4.20 and CI 3.1.11, and it is always related to concurrent ajax requests.

**Comment by victory7** [comment]
The best solution for me was to close the session (session_write_close) at the beginning of the method or wherever updating the session ended. It releases session lock for other concurrent requests.
