### ISSUE TITLE
What is the equivalent way of generating CI salted passwords in Java ?

### ISSUE THREAD

**Issue by ebubep** [bcit-ci/CodeIgniter#4366]
Hello, I have a legacy Code Igniter app which I need to integrate with a Java app.
The passwords are salted in CI but I need to be able to authenticate users in the Java app against the already existing salted passwords.

What is the equivalent way of generating CI salted passwords in Java ?
Thank you.

**Comment by narfbg** [comment]
There's no such thing as a "CI salted password", CodeIgniter doesn't provide tools to do that.

And this is a bug tracker ... if you want to ask a question, please do that on our [forums](http://forum.codeigniter.com/) or [StackOverflow](https://stackoverflow.com/).

**Comment by ebubep** [comment]
Ok, thank you . 

    On Friday, January 8, 2016 11:59 AM, Andrey Andreev <notifications@github.com> wrote:
 

 There's no such thing as a "CI salted password", CodeIgniter doesn't provide tools to do that.And this is a bug tracker ... if you want to ask a question, please do that on our forums or StackOverflow.—
