### ISSUE TITLE
Can we have an extra method in form validation class like 'is_present' 

### ISSUE THREAD

**Issue by ravikrishnangupta** [bcit-ci/CodeIgniter#4370]
Most of the time we needs to check that the entered Email is present in the table or not. For this we have to make our own methods to check that from database. Could we add a new method in form validation class like 'is_present' to check that while validating the form.

**Comment by kenjis** [comment]
This is a bug tracker. Please ask your question on the <http://forum.codeigniter.com/>.

**Comment by runningmark** [comment]
is_unique[tablename.column_name]

**Comment by narfbg** [comment]
No, and please use the search bar to see if a similar request doesn't exist yet - this has been requested numerous times before, last time being [less than two weeks ago](https://github.com/bcit-ci/CodeIgniter/pull/4347).
