### ISSUE TITLE
Ajax not sending data to controller.

### ISSUE THREAD

**Issue by anilkreddya** [bcit-ci/CodeIgniter#4372]
Hi when I use ajax to send form data to controller I'm not getting the date to controller but when I disable ajax and directly submit the form, I'm getting the POST data, I enabled profiler to see if I'm getting data.

My Ajax script is:
```javascript
<script>
    $(document).ready(function (){
        $("#forgotpassword").submit(function (e){
            e.preventDefault();
            var data = $(this).serialize();
            console.log(data);

            $.post( "welcome/forgotpassword", data, function( response ) {
                alert(response);
            }, "json");
        });
    });
</script>
```

And in controller I'm using,
```php
public function forgotpassword()
{
	$email = $this->input->post('email');
	$this->output->enable_profiler(TRUE);

	if($this->Authentication_model->setSecurityToken($email)){
		$this->Email_model->sendForgottenPasswordEmail($email);
	}else{
		echo "Details not found";
	}
}
```

I tried different ways of submitting data, but no use. I'm facing this issue for all ajax calls.

I'm using WAMP 2.5 and CI v3.0.3

**Comment by kenjis** [comment]
This is a bug tracker. Please ask your question on the <http://forum.codeigniter.com/>.
