### ISSUE TITLE
Session "Session_database_driver" read my last db condition

### ISSUE THREAD

**Issue by majaode** [bcit-ci/CodeIgniter#4374]
This error occurred when my database query error. This is my database error debug:

	A Database Error Occurred

	Error Number: 1054

	Unknown column 'ward_name' in 'where clause'

	SELECT COUNT(*) AS `numrows` FROM `room` WHERE `room`.`is_deleted` =0 AND (`room_id` LIKE '%al%' OR `room_code` LIKE '%al%' OR `room_name` LIKE '%al%' OR `room_location` LIKE '%al%' OR `room_function` LIKE '%al%' OR `room_bad` LIKE '%al%' OR `ward_name` LIKE '%al%' OR `class_name` LIKE '%al%')

	Filename: E:/workspace/public_html/sirs/rest/application/models/Rooms_model.php

	Line Number: 100

	A Database Error Occurred

	Error Number: 1054

	Unknown column 'room.is_deleted' in 'where clause'

	UPDATE `user_sessions` SET `timestamp` = 1452421087 WHERE `room`.`is_deleted` =0 AND (`room_id` LIKE '%al%' OR `room_code` LIKE '%al%' OR `room_name` LIKE '%al%' OR `room_location` LIKE '%al%' OR `room_function` LIKE '%al%' OR `room_bad` LIKE '%al%' OR `ward_name` LIKE '%al%' OR `class_name` LIKE '%al%') AND `id` = 'af21c55041a0c709b7e3f784e0dd6e33e9a344bc'

	Filename: libraries/Session/drivers/Session_database_driver.php

	Line Number: 247

**Comment by narfbg** [comment]
Which CI version are you using? What did you call to trigger the query failure?

**Comment by majaode** [comment]
I use CodeIgniter-3.0.3
In my model, I use $this->db->where()

	$this->db->where($this->table . '.' . $this->is_deleted, 0);	// exclude deleted record
	if ( $this->fiql ) $this->db->where($this->fiql);
	if ( $this->search ) $this->db->where($this->search);
	
	// count all
	return $this->db->count_all_results($this->table);
	
Produce sql:
	
	SELECT COUNT(*) AS `numrows` FROM `room` WHERE `room`.`is_deleted` =0 AND (`room_id` LIKE '%al%' OR `room_code` LIKE '%al%' OR `room_name` LIKE '%al%' OR `room_location` LIKE '%al%' OR `room_function` LIKE '%al%' OR `room_bad` LIKE '%al%' OR `ward_name` LIKE '%al%' OR `class_name` LIKE '%al%')

Since my table doesn't have field called 'ward_name' (forgot to add a join table), this error occured.

	Unknown column 'ward_name' in 'where clause'

And then this error occured

	Error Number: 1054

	Unknown column 'room.is_deleted' in 'where clause'

	UPDATE `user_sessions` SET `timestamp` = 1452421087 WHERE `room`.`is_deleted` =0 AND (`room_id` LIKE '%al%' OR `room_code` LIKE '%al%' OR `room_name` LIKE '%al%' OR `room_location` LIKE '%al%' OR `room_function` LIKE '%al%' OR `room_bad` LIKE '%al%' OR `ward_name` LIKE '%al%' OR `class_name` LIKE '%al%') AND `id` = 'af21c55041a0c709b7e3f784e0dd6e33e9a344bc'

	Filename: libraries/Session/drivers/Session_database_driver.php

	Line Number: 247
