### ISSUE TITLE
CI_Load::_ci_object_to_array() - a proposal for optimization

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#4379]
CI_Load::_ci_object_to_array() method has the following text:

```php
	protected function _ci_object_to_array($object)
	{
		return is_object($object) ? get_object_vars($object) : $object;
	}
```

 and it is used within CI_Loader class only at two places. It is about translation data from object to array for feeding views.

When view data is an array (I think this is the dominant case), a copy of that array it is made within the method and then it is returned back. This brief memory consumption is not necessary.

I am proposing the code of this method to be kept for BC for a while, but method's usage to be replaced with direct checks like:

```php
if (is_object($vars))
{
    $vars = get_object_vars($vars);
}
```

**Comment by narfbg** [comment]
You can't keep it for BC, but not use it ... that's quite the contradiction.

**Comment by ivantcholakov** [comment]
I mentioned about keeping for BC, because I've seen that this method is used by an external project too.

https://bitbucket.org/wiredesignz/codeigniter-modular-extensions-hmvc/src/b889da049fd78bd5beff8d7ef70916b60c3d6665/third_party/MX/Loader.php?at=codeigniter-3.x&fileviewer=file-view-default#Loader.php-300

For me particularly keeping the method is not important.

**Comment by narfbg** [comment]
Well, I don't really care for this proposed change, but if the method is not used by CI - it gets removed.

I'll leave it for you to submit a pull request if you really want this, and you can target *develop* for 3.1.0 to address the BC concern.

**Comment by ivantcholakov** [comment]
When I find the time I will remove it.
