### ISSUE TITLE
Fatal error: Cannot access private property

### ISSUE THREAD

**Issue by henry-h** [bcit-ci/CodeIgniter#4380]
When I declare private property with same name as library and load the library causes the following errors:
```
A PHP Error was encountered
Severity: Error
Message: Cannot access private property Welcome::$email
Filename: core/Loader.php
Line Number: 1275
```
How to reproduce:
```php
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Welcome extends CI_Controller {

	// Private property with name email
	private $email = null;
	 
	public function index()
	{
		// Load email library 
		$this->load->library('email');

		$this->load->view('welcome_message');
	}
}
```

**Comment by jim-parry** [comment]
This is a support question for forum.codeigniter.com, and not a bug in the framework.
When you load the email library, that injects an "email" property into your controller, clobbering the property you have defined.
http://www.codeigniter.com/user_guide/general/libraries.html
