### ISSUE TITLE
quiry builder group where issue

### ISSUE THREAD

**Issue by VirusEcks** [bcit-ci/CodeIgniter#4381]
starting a group then using where clause then or_where with ('tbl.tbl_col is', 'NULL') generates wrong clause with 'IS NOT `NULL`' instead of 'IS `NULL`'

**Comment by Filisko** [comment]
It should be like that I think: ('tbl.tbl_col', 'NULL') without "is"

**Comment by VirusEcks** [comment]
no
for a correct mysql query it has to be 'is' 
and null has to be un qouted

**Comment by narfbg** [comment]
Nope, it generates `is 'NULL'`.

If you want to check for nulls, you need to pass `NULL`, as in a literal null value, not the string 'NULL'. And you're not supposed to put 'is' in there.

**Comment by VirusEcks** [comment]
from the docs

    Custom key/value method:

    You can include an operator in the first parameter in order to control the comparison:

    $this->db->where('name !=', $name);
    $this->db->where('id <', $id); // Produces: WHERE name != 'Joe' AND id < 45

'IS' is supposed to be supported as well

**Comment by narfbg** [comment]
Again, you don't get 'IS NOT' when you type 'IS'.
And I don't really understand where you get the impression that 'IS' is supposed to be supported - the docs that you've pasted yourself don't show that.

`IS` is not usable with anything else but `NULL`, so it doesn't even make sense to pass `NULL` (which again, you are not even doing correctly) as the second parameter - you can just type the whole thing in the first parameter.
On the other hand `where('name !=', NULL)` will be translated into `name IS NOT NULL` and `where('name', NULL)` yields `name IS NULL`, so there's that.
