### ISSUE TITLE
PHP7 and mktime compatibility

### ISSUE THREAD

**Issue by Beninho** [bcit-ci/CodeIgniter#4387]
In my website, i'm using the date_helper, but with on new PHP7, i've some errors with it.
mktime() expects parameter 1 to be integer, string given

I'm using the "mysql_to_unix" function.
New mktime need integer, so i cast to int parts of date.
Example 

return mktime(
			intval(substr($time, 8, 2)),
			intval(substr($time, 10, 2)),
			intval(substr($time, 12, 2)),
			intval(substr($time, 4, 2)),
			intval(substr($time, 6, 2)),
			intval(substr($time, 0, 4))
		);
I've never used the Pull Request system, sorry.

**Comment by narfbg** [comment]
You're not using it properly ...

Duplicate of #4289.
