### ISSUE TITLE
problem with index.php removal

### ISSUE THREAD

**Issue by harlet** [bcit-ci/CodeIgniter#4388]
I just tested CI 3.0.4 and CI 3.0.3. Clean install on shared server. Duplicated the welcome controller, renamed, the file and the name of the class. added the same ,htacces., edit config file, etc...

On CI 3.0.4 accessing : /test. Shows 404
On CI 3.0.3. Shows the controller.

Thank you for this wonderful framework!

**Comment by narfbg** [comment]
I can see why you'd think this is some kind of a bug in 3.0.4, but it's not. There's no change in 3.0.4 that could possibly cause this.

Post on the [forums](http://forum.codeigniter.com/) if you're seeking help with debugging this.
