### ISSUE TITLE
Form_validation. commit data not support $_GET

### ISSUE THREAD

**Issue by runphp** [bcit-ci/CodeIgniter#4394]
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Form_validation.php#L419

why not support for $_GET ?

**Comment by kenjis** [comment]
See http://www.codeigniter.com/user_guide/libraries/form_validation.html#validating-an-array-other-than-post

This is a bug tracker. Please ask your question on the <http://forum.codeigniter.com/>.
