### ISSUE TITLE
Unclear error message when seconds parameter in update_batch is an empty array

### ISSUE THREAD

**Issue by fabsn182** [bcit-ci/CodeIgniter#4399]
When calling `$this->db->update_batch('table', $arr, 'column'))` CI will report if `$arr` is set but empty and db_debug is TRUE: `You must use the "set" method to update an entry.`

While I shall and will check if `$arr` is empty before calling the method, the error message should be clearer. Maybe even ignore the fact that $arr is empty when it is neither NULL nor FALSE?

**Comment by narfbg** [comment]
What's unclear about it?

**Comment by fabsn182** [comment]
In my opinion, the method shouldn't throw that error, if $arr is specified but empty. If I call update_batch with the second parameter being `NULL` or `FALSE`, the message would be clear and imho expected since I intended to add the data through a different method (`set` or `set_update_batch`)

If $arr is defined as array but empty, the update_batch call will fail but the message won't help me finding the reason for this error.

**Comment by narfbg** [comment]
That doesn't answer my question ... I'll rephrase: What *would* be a helpful message in your opinion?

**Comment by fabsn182** [comment]
Check for `$arr === NULL OR $arr === FALSE`.
If so, return a message like `You must use the "set" method when omitting data` or something like that. 

Otherwise `$arr` is set but empty, return a message saying so. Maybe just do so if db_debug is TRUE: `You must not us empty data`?!
If db_debug is turned off, silently ignoring the fact that $arr is empty would be fine for me personally, since there's nothing to be updated. Also the method could then return 0 because no row was affected instead of FALSE but I don't know if that would be unclear and inconsistent.
