### ISSUE TITLE
session expires ajax call is presen

### ISSUE THREAD

**Issue by Shamonshamonsha** [bcit-ci/CodeIgniter#4400]
Session is expired automatically when ajax call is present.
version is 3.0.3

**Comment by narfbg** [comment]
You'll have to give us more information than that ...

**Comment by narfbg** [comment]
Apparently, you're just looking for someone to help you with configuration ... https://stackoverflow.com/questions/35033464/session-expires-in-codeigniter-when-ajax-call-is-present-ci-version-3-0-3

Please note that this is a bug tracker, we don't provide general support here.
