### ISSUE TITLE
how to change controller loading behavior?

### ISSUE THREAD

**Issue by KickassCoxa** [bcit-ci/CodeIgniter#4404]
Holla, i came to problem because i am facing 404 - page not found issue when i try to access page wich is in sub directory.

I have fallowing structure:

controllers/communications.php
controllers/communications/conversations.php
controllers/communications/messaging.php
controllers/communications/discussions.php

when i access http://localhost/project-name/communications

everything works fine, because loaded controller is communications,php

but when i try to access http://localhost/procject-name/communications/messaging i get error because codeigniter loads controllers/communications.php and then looks for method 'messaging'.

my question is, how could i change codeigniter controller loding behavior, so it would look if there are path sub-directories at first case, instead of trying to load first controller that is uri segment

**Comment by narfbg** [comment]
Sorry, but this is a **bug tracker**, we don't provide general support here. Please use our [forums](http://forum.codeigniter.com/) or [StackOverflow](https://stackoverflow.com/) instead.

I already told you this the last time you did the same thing: https://github.com/bcit-ci/CodeIgniter/issues/3707#issuecomment-86889732
