### ISSUE TITLE
redis session expires after {session.gc_maxlifetime} sec when sess_expiration is set to 0

### ISSUE THREAD

**Issue by pradeepdsmk** [bcit-ci/CodeIgniter#4405]
I upgraded my CI build to 3.0.4 for redis sessions support. Everything is working out of box and it is awesome. However the session was lost when I logged into my app and was idle for 30min. 

I checked that my sess_expiration is set to 0 but still the session was lost.

After some research, it appears that, this is happening because of the following lines of code.

    CI_Session::_configure(array $params = array()) 
    {
        ...
        if (empty($expiration))
        {
            $params['expiration'] = (int) ini_get('session.gc_maxlifetime');
        }
        ...
    }

    CI_Session_redis_driver::write($session_id, $session_data) 
    {
        ...
        if ($this->_redis->set($this->_key_prefix.$session_id, $session_data, $this->_config['expiration']))
        { ... }
        ...
    }

I checked using log messages in my app and with redis client that the keys in redis are getting a ttl of 1800. 
I have session.gc_maxlifetime set to 1800 in my php.ini
I am expecting that the session remains active as long as the page is open in the browser even though the user is idle. Am I missing something here

**Comment by narfbg** [comment]
You are missing something, indeed.

There's no practical way to detect (server-side) when a browser is closed and thus, allowing a session to live *literally* as long as the browser is closed would mean for sessions to *never* expire.
