### ISSUE TITLE
Yeoman Generator for CodeIgniter

### ISSUE THREAD

**Issue by Rubenvanhoeyveld** [bcit-ci/CodeIgniter#4406]
Hi guys,

I'm not sure if you're familiar with Yeoman, but it could actually be nice to be able to generate a new CodeIgniter project from command line...

More information on how to set-up a generator: http://yeoman.io/generators/

I would definitely use this!

**Comment by narfbg** [comment]
Sorry, but this is by far outside of our project scope.

Any of our contributors would be welcome to create such generator as a third-party resource (and I'm quite sure such solutions already do exist), but it's not going to be a part of CI itself.
