### ISSUE TITLE
Create Enum

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter#4409]
Thoughts about adding an enum class type to be able to use enums in CodeIgniter?

I think this would be particularly useful for database field types.

**Comment by narfbg** [comment]
DB Forge already has (unofficial) support for enum fields, but even if it didn't ... it wouldn't happen via a class.

Also, if you're looking for "thoughts" again in the future, please open a thread on the [forums](http://forum.codeigniter.com/) instead.

**Comment by EpicKris** [comment]
Thanks for directing me to the forums, but would it not be a good feature to have official support for enums in the database forge class?

**Comment by narfbg** [comment]
Depends on what you mean by "good" and "official" ...

I said it's unofficial because it's not documented and not really tested, but we'd still, for example, accept bugfixes for it if something's broken about it.

**Comment by EpicKris** [comment]
By official I mean documented, but in any case, where can I find and use this? I would like to check it out! :+1:
