### ISSUE TITLE
database query helper insert column name with space

### ISSUE THREAD

**Issue by laimonas16** [bcit-ci/CodeIgniter#4412]
when passing associative array to insert data via database query helper array keys with spaces get interpreted incorrectly. might be related to this issue #2755 

example:
`$data = array("column name" => 'value');`
`$this->db->insert('table',$data);`

produces:
`INSERT INTO "table" ("column" "name") VALUES ('value')`

**Comment by laimonas16** [comment]
similar thing if key has parenthesis

example:
`$data = array("column_(1)_name" => 'value');`
`$this->db->insert('table',$data);`

produces:
`INSERT INTO "table" (column_(1)_name) VALUES ('value')`

**Comment by narfbg** [comment]
Same thing as #2755.
