### ISSUE TITLE
CI 3.0.4 removing index.php from url is not Working

### ISSUE THREAD

**Issue by icebergdelphi** [bcit-ci/CodeIgniter#4413]
Hi to all, i'm trying to remove the index.php from the URL, but this is not working, i have a project with CI 2.0 and works perfectly, but i don´t know what i'm doing wrong in the new version, i 've been doing this steps:

1.- Open config.php and do following replaces

$config['index_page'] = "index.php"
to
$config['index_page'] = ""

2.-  in config.php
  $config['uri_protocol'] = "REQUEST_URI"

3.-My httacces in:
Path:
Your_website_folder/
application/
assets/
system/
.htaccess <——— this file
index.php

-------------------------------------------------------------------
  DirectoryIndex index.php
RewriteEngine on

RewriteCond %{REQUEST_URI} !^(index\.php)$
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*) ./index.php [L]

Thank you.

**Comment by narfbg** [comment]
Post this on the [forums](http://forum.codeigniter.com/) instead, this is a bug tracker.
