### ISSUE TITLE
log_message() is undefined when called in a controller

### ISSUE THREAD

**Issue by hungtruongquoc** [bcit-ci/CodeIgniter#4414]
I have the following controller: 

```
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Log extends CI_Controller {

	/**
	 * Index Page for this controller.
	 *
	 * Maps to the following URL
	 * 		http://example.com/index.php/welcome
	 *	- or -
	 * 		http://example.com/index.php/welcome/index
	 *	- or -
	 * Since this controller is set as the default controller in
	 * config/routes.php, it's displayed at http://example.com/
	 *
	 * So any other public methods not prefixed with an underscore will
	 * map to /index.php/welcome/<method_name>
	 * @see https://codeigniter.com/user_guide/general/urls.html
	 */
	public function index()
	{
		if(function_exists('log_message')){
			// $this->load->view('welcome_message');
			log_messsage('info', 'In Log controller');
		}
	}
}
```

I got following error: 

```Fatal error: Call to undefined function log_messsage() in /Applications/MAMP/htdocs/tripplanner/application/controllers/Log.php on line 25```

CodeIgniter version 3.0.4
Platform: Mac OS X El Capitan
PHP 5.6.10

**Comment by xinzhanguo** [comment]
the function name  is `log_message`
not `log_messsage`

you write wrong

**Comment by jim-parry** [comment]
We use github for bug tracking, not support, which is through forum.codeigniter.com

Check your spelling of the alleged missing function that you call.

**Comment by hungtruongquoc** [comment]
Thank you for your quick reply. Sorry for posting the wrong place.
