### ISSUE TITLE
Form Validator : valid_url rule not working with IPv6 host

### ISSUE THREAD

**Issue by Seb33300** [bcit-ci/CodeIgniter#4415]
Hi

The valid_url form validator rule is not able to validate URL when host is an IPv6 address.
http://www.codeigniter.com/user_guide/libraries/form_validation.html?highlight=form#rule-reference

For instance:
`http://[::1]/sample-url`

is a valid IPv6 host URL equivalent to 
`http://localhost/sample-url`

More details: https://www.ietf.org/rfc/rfc2732.txt

**Comment by narfbg** [comment]
This was PHP's fault, details are within the patch itself.
