### ISSUE TITLE
fatal error when using new mongodb php library with session redis driver

### ISSUE THREAD

**Issue by lanlin** [bcit-ci/CodeIgniter#4420]
I save some user base info with the CI's session redis driver, like userid, company_id... in an array.
All of these named xxx_id in the array are MongoDB's ObjectID, but when i save these data to session redis i got this error.

> Fatal error: Uncaught exception 'Exception' with message 'Serialization of 'MongoDB\BSON\ObjectID' is not allowed' in [no active file]:0 Stack trace: #0 [internal function]: session_write_close() #1 {main} thrown in [no active file] on line 0.

Here the new mongodb php library https://github.com/mongodb/mongo-php-library

And here is a sinple demo that will cause same fatal error

```php
$a = [ 'a' => new \MongoDB\BSON\ObjectID()];
$this->session->set_userdata($a);
```

But, when using mongodb legacy driver for php, all things fine.
I don't know how to solve it.

**Comment by narfbg** [comment]
Sorry, but this is not a CodeIgniter issue.

If you're just looking for help with something, ask your questions on our [forums](http://forum.codeigniter.com/) instead. We only accept bug reports here.
