### ISSUE TITLE
Post DB Connect Hook

### ISSUE THREAD

**Issue by skunkbad** [bcit-ci/CodeIgniter#4421]
I have had instances where having a post DB connect hook would be useful, such as setting a timezone in a server environment where I cannot otherwise access MySQL config. Another forum member was having the same issue here: [http://forum.codeigniter.com/thread-64249.html](http://forum.codeigniter.com/thread-64249.html), although his/her preference was to have a DB config option.

Yes, we already have some early running hooks, but the earliest we can send a query is later than autoloaded libraries can use a DB connection, should they have such actions called through their constructors.

Narf, it seems that you are the one making the decisions. So I wanted to ask first if you would please consider such a hook. The placement of such a hook could be near the bottom of DB_driver->initialize.

I'll do the work and submit a pull request if you are not opposed to this.

**Comment by narfbg** [comment]
No.

**Comment by skunkbad** [comment]
How about a DB config option?
