### ISSUE TITLE
Feature request: Finding out latest version of CodeIgniter programmatically

### ISSUE THREAD

**Issue by Tilogorn** [bcit-ci/CodeIgniter#4423]
As I provide kind of an Admin Panel in a current project I'm interested if there is an API (or sth similar) to get the latest stable version number of CodeIgniter to display a Owncloud-like warning `"There is a new version available"`?

Is there a common need for this or is it just me?

If it's just me: I would implement it for myself as circumstantial as possible (Retrieving latest version through HTML-Code of codeigniter.com, comparing it to `CI_VERSION`, wrapping it in a helper-function).

But if somebody else is interested: I would appreciate an API or at least a `<span id="ci_version">3.x.x</span>` on the website for making a function like the described more beautiful/efficient.

Another thought: Maybe there is a github-solution for this? The downloads on codeigniter.com point to `https://github.com/bcit-ci/CodeIgniter/archive/3.x.x.zip`. Maybe they provide an API for e.g. the latest archived zip? I can't find a solution via Google, but maybe somebody else knows one...

**Comment by Tilogorn** [comment]
Commenting myself on the latest paragraph: Github provides a [Releases API](https://developer.github.com/v3/repos/releases/) which is [an empty array for CodeIgniter](https://api.github.com/repos/bcit-ci/CodeIgniter/releases). Maybe including the needed POST-Request in your release-process would provide the needed feature in an easy way?

**Comment by narfbg** [comment]
GitHub APIs do provide the necessary data for what you want to work.

But please note that we don't provide general support here and your "feature request" is not related to our codebase. You should post such requests on our [forums](http://forum.codeigniter.com/) instead.

**Comment by natsu90** [comment]
I'm second for this. It is not related to the codebase, but it require Github access to add release.
https://github.com/blog/1547-release-your-software
https://help.github.com/articles/about-releases/
https://help.github.com/articles/creating-releases/

**Comment by Tilogorn** [comment]
For anyone who finds this via a search engine: The issue #3421 was a hint why the GitHub-API doesn't show any releases for CodeIgniter. 

See the following for a complete update detection code, for e.g. a administration dashboard:

```php
/* Retrieve CodeIgniter repository releases */
$opts = ['http' => ['method' => 'GET','header' => ['User-Agent: PHP']]];
$context = stream_context_create($opts);
$json = file_get_contents("https://api.github.com/repos/bcit-ci/CodeIgniter/tags", false, $context);
$tags = json_decode($json, true);

/* Extract latest version */
$versions = array();
foreach ($tags as $tag) {
	array_push($versions, $tag['name']);
}
usort($versions, 'version_compare');
$latestVersion = end($versions);

echo "Your version is: " . CI_VERSION . "<br>";
echo "The latest online version is: " . $latestVersion . "<br>";

/* Comparison */
switch(version_compare(CI_VERSION, $latestVersion)){
	case -1:
		//myVersion < latestVersion
		echo "Update needed";
		break;
	case 0:
		//myVersion < latestVersion
		echo "Latest version installed";
		break;
}
```
Can easily be wrapped in a helper function or sth. similar
