### ISSUE TITLE
CodeIgniter's user guide page not found 404 error in first install

### ISSUE THREAD

**Issue by Rumo-Arf** [bcit-ci/CodeIgniter#4425]
![default](https://cloud.githubusercontent.com/assets/11865340/12783140/04aec846-cac3-11e5-85bb-bb8f2d62f75f.PNG)

I just installed CI and saw the page welcome. This is good but.. when I clicked user guide then...

![default](https://cloud.githubusercontent.com/assets/11865340/12783164/1ca07846-cac3-11e5-8665-7fffe449aa1f.PNG)

well... There is no directory named 'user_guide' actually but 'user_guide_src' is.

![default](https://cloud.githubusercontent.com/assets/11865340/12783190/4c567766-cac3-11e5-962d-4a113f4b3e34.PNG)

Did I something wrong??

**Comment by Rumo-Arf** [comment]
I found a 'user_guide' directory in offical site (https://www.codeigniter.com/) but why isn't git?

**Comment by narfbg** [comment]
Because you're supposed to use the final version, not the current git state.

Please note that we don't provide general support here. If you seek help with something, ask your questions on our [forums](http://forum.codeigniter.com/) instead.
