### ISSUE TITLE
Upload class: file_ext_tolower misleading or buggy

### ISSUE THREAD

**Issue by ke352802081770314** [bcit-ci/CodeIgniter#4430]
The file_ext_tolower is documented as "If set to TRUE, the file extension will be forced to lower case"
For the upload data, the fields are documented as
file_name 	Name of the file that was uploaded, including the filename extension
file_ext 	Filename extension, period included
My expectation of this was that
1. file_name always contains file_ext at its end, since it says it includes "the filename extension"
2. therefore, by setting file_ext_tolower I can achieve that the file is stored with a lowercased extension.

It turns out that only the data element file_ext is lowercased, and no longer corresponds to the end of file_name, while file_name and the actual file stored retain the original (e.g. uppercase) extension.
I feel that the documentation is misleading (it implies that file_ext is a part of file_name, and therefore would also be lowercased by using this option) and also this behaviour is unhelpful, if I need the file with a lowercased extension, I cannot simply rename it afterwards without running into a risk of name conflict, which the Upload class was intended to protect me from by creating a unique name, but it does this with the uppercased extension. 
Example: person A uploads A1234.jpg, then person B uploads A1234.JPG, Upload class sees no need to adjust, but if I then rename A1234.JPG to A1234.jpg, I would overwrite the previous file, and thus I would have to add filename uniquify code in my application when Upload class was supposed to do this task for me.

If you want to retain the current behaviour, I suggest that you clarify the documentation for file_ext_tolower: "only the file_ext data element will be affected by this setting, not the file name used to store the uploaded file in. file_ext will no longer be identical to the extension included in file_name if you set this option."
Many thanks in advance for your consideration.

**Comment by narfbg** [comment]
Um, may I suggest that you clarify what you mean?

**Comment by ke352802081770314** [comment]
There is a "File Uploading Class" as documented in https://www.codeigniter.com/userguide3/libraries/file_uploading.html
When I use it as follows:
    $config = array(
        'upload_path' => '/home/blog/raw/',
        'allowed_types' => 'jpg',
        'file_ext_tolower' => TRUE,
    );
    $this->load->library('upload', $config);

and I upload DSCF1745.JPG, my expectation would be that the uploaded file is named DSCF1745.jpg but $this->upload->data returns:
Array ( [file_name] => DSCF1745.JPG [file_type] => image/jpeg [file_path] => /usr/home/blog/raw/ [full_path] => /usr/home/blog/raw/DSCF1745.JPG [raw_name] => DSCF1745.JPG [orig_name] => DSCF1745.JPG [client_name] => DSCF1745.JPG [file_ext] => .jpg [file_size] => 3004.03 [is_image] => 1 [image_width] => 4000 [image_height] => 3000 [image_type] => jpeg [image_size_str] => width="4000" height="3000" ) 
and the file is indeed named DSCF1745.JPG
What I expected to happen is  [file_name] => DSCF1745.jpg etc.

**Comment by ke352802081770314** [comment]
I also just noticed that contrary to documentation, "raw_name" which I would have expected to contain "DSCF1745", includes the extension.

**Comment by narfbg** [comment]
Ok, how is it with that patch?

**Comment by ke352802081770314** [comment]
Works as expected! Wow! I'm absolutely stunned by your quick response and action!
Fantastic work. Many thanks.

**Comment by nikokolev** [comment]
Not working for me at all! Not on a localhost and neither on a server, even if the fileinfo php extension is on on both. I'm continuing to get the uppercase values, with file_ext_tolower set to TRUE! What I'm missing?

`$this->load->library('upload');
					
					// Upload cover
					$config['upload_path'] = './resources/img/content';
					$config['allowed_types'] = 'jpg';
					$config['overwrite'] = false;
					$config['file_ext_tolower'] = true;
					$config['remove_spaces'] = true;
					
					$this->upload->initialize($config);
					
					if ( ! $this->upload->do_upload('cover')) { // Error } else { // Ok }`

Another thing that this brings is that..if I have a file named myfile.JPG and myfile.jpg, CodeIgniter isn't able to see that they're the same file..which is ultimately what would be likely it does if only file_ext_tolower was working properly.

**Comment by narfbg** [comment]
What OS does that server run?

**Comment by nikokolev** [comment]
These are the headers that I get:
Server:Apache/2.4.23 (Unix) OpenSSL/1.0.1e-fips Phusion_Passenger/4.0.58 mod_bwlimited/1.4
X-Powered-By:PHP/5.6.30
