### ISSUE TITLE
db UPDATE issue

### ISSUE THREAD

**Issue by bribar** [bcit-ci/CodeIgniter#4435]
This is a really weird issue and I'm not sure if its codeigniter active record or the server. It happens when updating a record for a specific TEXT field. When saving a string that contains "select from" in it, it throws a database error. "Select from" or "select From" doesn't throw error. A string like "Go to the database and select all gray cars with four doors from the cars table." would throw an error too. If from comes before select, that won't throw an error.

I notice my local environment doesn't throw an error. Any suggestions? Or point me in the right direction if it isn't codeigniter?

**Comment by fiblan** [comment]
Can you give us more details on error you get?

**Comment by bribar** [comment]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'id` IS NULL' at line 1

I am using an ajax request. I will save fine if I don't include those words in the string. My guess is the syntax is breaking cause I know id is getting passed to the server.

**Comment by narfbg** [comment]
@bribar That doesn't really tell us anything.

We don't know your code nor the SQL query that's being executed ... we can't just guess what's happening, you'll have to give us more than a generic error message.
