### ISSUE TITLE
Question about Cookies disabled in browser

### ISSUE THREAD

**Issue by skobeo** [bcit-ci/CodeIgniter#4436]
When cookies are disabled in browser, doing a controller post with csrf return a 500 error, which seems to be logical. But i can't find where and when in the flow i can catch that cookies are disabled. Putting log debug in front off controller indicates that nothing entered in controller.
Using CI 2.26.

**Comment by narfbg** [comment]
Please note that this is a bug tracker and we don't provide general support here. Post your questions on our [forums](http://forum.codeigniter.com/) instead.
