### ISSUE TITLE
MongoDB Driver for Session

### ISSUE THREAD

**Issue by intekhabrizvi** [bcit-ci/CodeIgniter#4446]
Hello,

i wrote MongoDB based session driver for Codeigniter and can be found at https://github.com/intekhabrizvi/codeigniter-mongodb-session-driver

I took extra care to wrote codes as per codeigniter's standard. Do let me know if you care and my codes are worthy enough to be merged into codeigniter repo, i will add those files into my codeigniter fork and send you PR else no hard feeling.

Thanks

**Comment by narfbg** [comment]
No, sorry.
