### ISSUE TITLE
Bug in query builder: on clause in join method escapes IS NULL

### ISSUE THREAD

**Issue by rbcpl** [bcit-ci/CodeIgniter#4449]
When using IS NULL in the ON clause of a join, CodeIgniter escapes IS NULL to " \`IS\` \`NULL\`", which leads to an invalid SQL statement.  

```
$this->db->join("table", "field1 IS NULL")
```
Only when explicitly setting the "escape" argument to FALSE it works. Using IS NULL in the query builder where method seems to be OK. #

**Comment by narfbg** [comment]
How does `JOIN table ON field1 IS NULL` even make sense?

**Comment by rbcpl** [comment]
In our case the ON clause also contains other conditions, among them one containing IS NULL.  The above mentioned `JOIN table ON field1 IS NULL` was only exemplary, but would also makes sense if you want to join a table where a certain field is NULL, of course depending on your database design.  Nevertheless, the above mentioned behaviour is a bug which occurred while migrating from CI2 to CI3.
