### ISSUE TITLE
post_system hook called before page render

### ISSUE THREAD

**Issue by serazoli** [bcit-ci/CodeIgniter#4450]
in application/config/hooks.php
```php
$hook['post_system'] = function()
{
    $CI =& get_instance();
    $class = $CI->router->fetch_class();
    sleep(10);
    file_put_contents('/tmp/tmp.txt', "Text after 10 sec $class");
};
```
in application/config/config.php
```php
$config['enable_hooks'] = TRUE;
```
In my app i use: https://github.com/chriskacerguis/codeigniter-restserver
I got response in browser only after 10 sec
(I use this extesion for testing https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo)

I use latest stable version Codeigniter 3.0.4
php 5.5.9

**Comment by narfbg** [comment]
"Page rendering" isn't something that CI, nor any PHP code has control of - that happens in the browser.

The *output* is sent before post_system is called, you can see that at the bottom of *system/core/CodeIgniter.php*, so this is not a CodeIgniter problem. You're probably interfering with that by using output buffering, but that's something you are responsible of taking care for - it's your configuration. :)

**Comment by serazoli** [comment]
thanks
