### ISSUE TITLE
Form validation - min_lenght / max_lenght

### ISSUE THREAD

**Issue by alexstan57** [bcit-ci/CodeIgniter#4451]
Hi,

I'm currently upgrading my project from version 2.x to 3.x.

The login page (which uses form validations) behaves suddently strange by saying that there's a problem with the min/max lenght of my field.

> Unable to access an error message corresponding to your field name Username.(min_lenght)

Truying to isolate the problem, I finally made a new project by taking EXACTLY your example:
[http://www.codeigniter.com/user_guide/libraries/form_validation.html?highlight=form_validation#CI_Form_validation](url)

Everything is working except when I add a validation rule on min_lenght and max_lenght.

$this->form_validation->set_rules('username', 'Username', 'trim|required|min_length[5]|**max_length[12]'**);

Many thanks for your help,
Alex

`
<?php

class Form extends CI_Controller {

        public function index()
        {
				$this->load->helper(array('form', 'url'));

				$this->load->library('form_validation');

				$this->form_validation->set_rules('username', 'Username', 'required|min_lenght[3]');
				$this->form_validation->set_rules('password', 'Password', 'required',
                        array('required' => 'You must provide a %s.')
                );
				$this->form_validation->set_rules('passconf', 'Password Confirmation', 'required');
				$this->form_validation->set_rules('email', 'Email', 'required');

				if ($this->form_validation->run() == FALSE)
				{
					$this->load->view('myform');
				}
				else
				{
					$this->load->view('formsuccess');
				}
			}
}
`

**Comment by narfbg** [comment]
The word "length" is written with a 'th', not 'ht' ...

Please note that this is a bug tracker and you should debug and verify that something is actually a bug before writing about it here. If you're seeking help with something, ask on our [forums](http://forum.codeigniter.com/) instead.

P.S.: Also, the Markdown syntax for links is `[description text](http://address)`, you've flipped those when trying to link to the FV docs, just like you've done with the 'th'. :)

**Comment by alexstan57** [comment]
You're perfectly right, sorry for the mistake, it works...

Cheers

2016-02-11 19:42 GMT+01:00 Andrey Andreev <notifications@github.com>:
