### ISSUE TITLE
File upload documentation wrong (or simply unclear)

### ISSUE THREAD

**Issue by JuanjoSalvador** [bcit-ci/CodeIgniter#4455]
In CodeIgniter's documentation, File Upload Class (http://www.codeigniter.com/user_guide/libraries/file_uploading.html) there is some errors respect the new version of CI.

Instead to create a new Upload class (controller), the good way is using the Upload library in our controller.

**Comment by narfbg** [comment]
There's nothing erroneous about it. It's a set of examples aiming to show how the whole thing works in a simple way, not a recommendation of exactly how you should do it.
