### ISSUE TITLE
system\helpers\form_helper.php 3.0.4

### ISSUE THREAD

**Issue by mauroconde** [bcit-ci/CodeIgniter#4456]
Line 794   return ($input === 'value') ? ' checked="checked"' : '';
Line 794 should be? return ($input === $value) ? ' checked="checked"' : '';

Line 847  return ($input === 'value') ? ' checked="checked"' : '';
Line 847  should be? return ($input === $value) ? ' checked="checked"' : '';

**Comment by narfbg** [comment]
Duplicate of #4426.
