### ISSUE TITLE
internationalization problem.

### ISSUE THREAD

**Issue by jonathandion** [bcit-ci/CodeIgniter#4458]
Hi guys,

I followed the internationalization [guide](https://github.com/bcit-ci/CodeIgniter/wiki/CodeIgniter-2.1-internationalization-i18n) but I have an issue.

Every time I try to access the index page (example : http://localhost:8000) I got : 

> Cannot modify header information - headers already sent by ...

but when I accessing http://localhost:8000/fr or http://localhost:8000/en everything is working fine.

I would like to add '/en' on the index page but how ? Should I use $routes or change something on my  htaccess file?

I would like to help.

Thanks.

**Comment by narfbg** [comment]
Please note that this is a bug tracker. Any other questions, not related to a problem in the framework itself, you should ask on our [forums](http://forum.codeigniter.com/) instead.
