### ISSUE TITLE
Money value in form validation

### ISSUE THREAD

**Issue by junaidpv** [bcit-ci/CodeIgniter#446]
It would be very nice if money value validation is also in form validation. Existing rules 'integer' and/or 'decimal' cannot be used for the purpose.

I implemented it in my application by extending CI_Form_validation:

``` php
<?php
class MY_Form_validation extends CI_Form_validation {

     public function __construct($rules = array()) {
         parent::__construct($rules);
     }

     public function is_money($input) {
         return (bool) preg_match('/^[0-9]+(\.[0-9]{0,2})?$/', $input);
     }
 }
```

then extended rule messages (I don't know exact, but this worked for me):

``` php
<?php
include_once BASEPATH . 'language/english/form_validation_lang.php';
$lang['is_money']           = "The %s field must contain a price (money) value.";
```

**Comment by colourstone** [comment]
Just wanted to thank you for this. It works perfectly!
Have a great day,
Brent
