### ISSUE TITLE
wrong detected mobile browser with user_agent library - MALGJS;

### ISSUE THREAD

**Issue by widyou** [bcit-ci/CodeIgniter#4461]
I used user_agent library for mobile browser like this:

```
// check mobile browser
$this->load->library('user_agent');`
$result = $this->agent->is_mobile();
```

but IE11 browser in LG OEM devices with Windows 10 agent value like this:
`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; MALGJS; rv:11.0) like Gecko`

'MALGJS' means LG OEM Windows Devices. (like notebook)

in User_agent.php -> _set_mobile():

```
if (FALSE !== (stripos($this->agent, $key))) // stripos('... MALGJS; ...', 'lg')
{
        $this->is_mobile = TRUE;
        $this->mobile = $val;
        return TRUE;
}
```

then some IE in LG notebook redirect mobile page.

**Comment by anovsiradj** [comment]
you make pull request here: https://github.com/bcit-ci/CodeIgniter/edit/develop/application/config/user_agents.php

**Comment by flexsingit** [comment]
![firefox_wallpaper](https://cloud.githubusercontent.com/assets/25687998/25117512/1c2c5430-2430-11e7-86e6-7b48aab9bc8d.png)
