### ISSUE TITLE
escape_like_str()

### ISSUE THREAD

**Issue by Glennmen** [bcit-ci/CodeIgniter#4462]
When in my like query I use the escape_like_str() to escape !, _ and % characters but the query gives a wrong result. When I do a like query directly in phpMyAdmin it works perfectly.

The escape_like_str() adds a ! in front of !, _ and %.
! => !!
_ => !_
% => !%

But in MySQL this doesn't work, it will search for !! and not give me any results.

**Comment by Glennmen** [comment]
I noticed that the escape_like_str() function doesn't add ESCAPE '!' to the query.

The query builder $this->db->like() does this automaticly. 
Maybe add this the ESCAPE '!' to the example query?

**Comment by Glennmen** [comment]
Adding ESCAPE '!' does solve the problem for % and _
But I can't search for values containing the !

I am still searching for a solution.

**Comment by mwhitneysdsu** [comment]
You should post your question in the [forums](http://forum.codeigniter.com/), and probably include the actual code you are trying to use and what you expect to receive as output. In most cases, you wouldn't call `escape_like_str()` directly, or you would only use it for a specific portion of your SQL.

**Comment by yuchonghua** [comment]
How can I deal with it?

**Comment by narfbg** [comment]
By reading the documentation.
