### ISSUE TITLE
无法调用service里的User_service.php 服务

### ISSUE THREAD

**Issue by nisang** [bcit-ci/CodeIgniter#4463]
PHP Fatal error:  Call to a member function list_user_to_redis() on a non-object in /application/code/application/cron/Myclass.php on line 19

Fatal error: Call to a member function list_user_to_redis() on a non-object in /application/code/application/cron/Myclass.php on line 19

A PHP Error was encountered

Severity: ErrorMessage:  Call to a member function list_user_to_redis() on a non-objectFilename: /application/code/application/cron/Myclass.phpLine Number: 19

Myclass.php
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class MyClass
{
	function user_to_redis($params = array())
	{
		// 写用户基础信息到redis
		$this->CI =& get_instance();
		$this->CI->load->service('user_service');
		$result = $this->CI->user_service->list_user_to_redis();
		if(!$result){
			throw new Exception('失败');
		}
		return 'ok';
	}

}

**Comment by nisang** [comment]
User_service 为自定义并已继承MY_Service

**Comment by jim-parry** [comment]
English, please. If this is not a bug, raise the problem on forum.codeigniter.com, also in English.
Thanks.

**Comment by nisang** [comment]
confirmed，this is not a bug.this problem is file path cause，can't found User_service.php in server.
