### ISSUE TITLE
If i call a file from hooks folder its running good but i am calling on same file from a controllers folder its giving me error called Unable to locate the specified class: Session.php

### ISSUE THREAD

**Issue by arifabbass** [bcit-ci/CodeIgniter#4468]

**Comment by narfbg** [comment]
This is a bug tracker, please post your questions on our [forums](http://forum.codeigniter.com/) instead.

**Comment by arifabbass** [comment]
Why you closed this question. It means its not a right website. sorry i am not coming again thank you buy.....!!!!!
