### ISSUE TITLE
what is ORM compatible with codeigniter 3.0.4 ??

### ISSUE THREAD

**Issue by TeamOussama** [bcit-ci/CodeIgniter#4469]
i try gas orm ! datamapper!! and doctrine all this ORMs not compatible or not have good documentation.
and i don't find any tutorial integration in google!!
so  please helpe me!!

**Comment by narfbg** [comment]
This is a bug tracker. If you need help with something, you should ask on our [forums](http://forum.codeigniter.com/) instead.
