### ISSUE TITLE
Controller is rejecting post variable with ampersand

### ISSUE THREAD

**Issue by ronlinet** [bcit-ci/CodeIgniter#4484]
My form contains a checkbox with a value 'Niagara Falls & Region'. 
When I check this checkbox and I submit the form to the controller I end up with 'Disallowed Key Characters' error. 
I have added the ampersend and underscore to my permitted_uri_chars in config.php 
`$config['permitted_uri_chars'] = 'a-z 0-9~%.:_&\-\',';`
but error is still there.
Is there any walk around to exclude the post variable from permitted_uri_chars filter?
If not why is the underscore and ampersand not being excluded from uri filtering?

**Comment by narfbg** [comment]
POST vars have nothing to do with URLs and therefore 'permitted_uri_chars' has nothing to do with this. In addition, the "Disallowed Key Characters." error is triggered by *keys*, not values.

**Comment by ronlinet** [comment]
yes  @narfbg the error : 
`Disallowed Key Characters.Niagara_Falls_&_Region` 
I am checking the array keys now

**Comment by ronlinet** [comment]
This is the html content of checkbox the value is integer. Why and where is CI grabbing the string  : 
```

		 		<div>
			 		&nbsp;&nbsp;&nbsp;<input name="Niagara Falls &amp; Region" value="32" id="32 " title="Niagara Falls &amp; Region" link="#" type="checkbox">Niagara Falls &amp; Region<br>
	      			</div>
			</div>
```

**Comment by narfbg** [comment]
You can't go around this and there's no reason to use such keys, it's very much intentional.

**Comment by narfbg** [comment]
... or you can, by upgrading, because this error is no longer triggered in CI3.
Which means that you're using an unsupported version.

**Comment by ronlinet** [comment]
@narfbg your analyze is correct. 
Yes we are dealing with an outdated 2.0 version and yes the upgrade is a reasonable long term option.
However now I have to go for an immediate fix for the prod environment ? So far the only fix I see is to hack  function _clean_input_keys in system/core/Input.php .

**Comment by narfbg** [comment]
@ronlinet The upgrade is a reasonable immediate option as well - it takes less than an hour.

But that being said, this is a bug tracker and you shouldn't post such questions here. If you need help with something, please write on our [forums](http://forum.codeigniter.com/) instead.

Also, please don't link to the EllisLab website, the official manual is at codeigniter.com.
