### ISSUE TITLE
Downgrade certain log messages to INFO

### ISSUE THREAD

**Issue by sprakashtd** [bcit-ci/CodeIgniter#4486]
The following messages are being logged for every request with ERROR and DEBUG logging enabled in CI. These should be downgraded to INFO so that the log doesn't fill up... 

DEBUG - 2016-02-26 09:30:59 --> Total execution time: 0.1316
DEBUG - 2016-02-26 09:31:02 --> Config file loaded: /home/.../application/config/config_site.php
DEBUG - 2016-02-26 09:31:02 --> Total execution time: 0.1184
DEBUG - 2016-02-26 09:31:05 --> UTF-8 Support Enabled
DEBUG - 2016-02-26 09:31:05 --> Global POST, GET and COOKIE data sanitized

**Comment by narfbg** [comment]
This is similar to #1528, but for another set of messages ...

If you care enough for this, please submit a pull request with the necessary changes. There's no use in it being an issue thread.
