### ISSUE TITLE
In ver. 3.0.4 when enable_query_strings is TURE only default controller working 

### ISSUE THREAD

**Issue by radiart** [bcit-ci/CodeIgniter#4488]
In fresh installation of ver. **3.0.4** when **enable_query_strings** is **TRUE**  only default controller working, when I run any other route I always getting default controller.

I tried all options in **uri_protocol** and many different .htaccess files and always see the same problem...

Any idea how to fix it?

**Comment by narfbg** [comment]
It works as intended, you likely didn't really read-up on what this option does.

Please ask your questions on the [forums](http://forum.codeigniter.com/) instead, we can't offer help for general questions here.
