### ISSUE TITLE
Are there any plans to push out a 3.0.5 any soon?

### ISSUE THREAD

**Issue by daN4cat** [bcit-ci/CodeIgniter#4490]
As per subject, we are pending on a fix merged in 3.0.5 is opensourcepos code and I would like to close the upgrade to CI3 taking 3.0.5.

Any plan to release it soon?

Thanks.

**Comment by narfbg** [comment]
Sorry, but this is a bug tracker and we don't answer such questions here. We can't allow this to turn into a helpdesk service.

**Comment by daN4cat** [comment]
OK, sorry about the noise.
