### ISSUE TITLE
Problem with $config['subclass_prefix']

### ISSUE THREAD

**Issue by abuhurairalakdawala** [bcit-ci/CodeIgniter#4493]
When we set `$config['subclass_prefix'] = '';` I am unable to load user defined helpers inside application/helper location. It gives the error Unable to load the requested file.

But when we set any value to this config variable eg: `$config['subclass_prefix'] = 'ANY_';`, it loads the helper correctly.

Why do this happens?

**Comment by narfbg** [comment]
Because you're not supposed to set it to an empty string ... Please note that this is a bug tracker, if you want to ask a question, do it on our [forums](http://forum.codeigniter.com/) instead.
