### ISSUE TITLE
result array should return false instead of empty array when error occurs

### ISSUE THREAD

**Issue by sphinxzhai** [bcit-ci/CodeIgniter#4496]
$query->result() return empty array when table is empty, this is confusing.

**Comment by narfbg** [comment]
An empty table is not an error.

**Comment by sphinxzhai** [comment]
sorry for the confusing description. I mean $query->result()  returns empty array when table is empty. $query->result() still returns empty array when error occurs. This is confusing. I think  $query->result()  should return false when error occurs.

**Comment by narfbg** [comment]
Define what you mean by "error" then - that's unclear.
