### ISSUE TITLE
PHPExcel + Zend : Export in excel take large time for 9000+ data

### ISSUE THREAD

**Issue by Harrrrry** [bcit-ci/CodeIgniter#4497]
Hi,

I am using phpexcel with zendframwork 1 in my application, when I try to export the data (9000+), the browser always loading no result found.
What I have to do, I think the problem related to phpexcel because the same query work fine in when I run directly in database.

Can anyone please help me, I am stuck

**Comment by abude** [comment]
I don't understand why this is a codeigniter issue ?!

**Comment by Harrrrry** [comment]
ohh sorry, please ignore
