### ISSUE TITLE
problem with htmlspecialchars and iso-8859-1 encoding in form_prep() function (form_helper)

### ISSUE THREAD

**Issue by martinnicolas** [bcit-ci/CodeIgniter#4500]
The function has a call to htmlspecialchars() without using any encoding, not even the established in config.php file. This creates problems when populating forms with data from a mysql table using latin1_swedish_ci collation.

I made the following changes to get it work:

$str = htmlspecialchars($str, ENT_QUOTES, 'ISO-8859-1');

**Comment by narfbg** [comment]
This is no longer the case in CI 3.x and you should upgrade ASAP, as well as check for newer versions and fixes before reporting something - right now you're reporting an issue for an unsupported version.

**Comment by martinnicolas** [comment]
My mistake, sorry. I was working with CI 3.0.4 and 2.2.6 in simultaneous. It will not happen again! :)
