### ISSUE TITLE
Uri routing doesn't check HTTP verbs when URI match "magic routing"

### ISSUE THREAD

**Issue by sergioalcaraz** [bcit-ci/CodeIgniter#4501]
Hello, I have set up a route with HTTP verb such as:
I expect the controller method is executed only when the HTTP verb is POST but runs the same if the verb is GET, PUT or another.
That is not checking if the HTTP verb is specified in the configuration file routes.php
This only happens to me when URI segments is equal to the "magic routing" that performs codeigniter.

For example
Suppose I have the following
Controller: Customers
Method: create
And routes
This route is not verified the HTTP verb, and any verb is executed
$route['customers/create'] ['post'] = 'customers/create';
On this route the HTTP verb is verified, and don't execute the 
$route['customers/new_customer'] ['post'] = 'customers/create';
Thank you

**Comment by narfbg** [comment]
It does check them, they don't match, no other route matches and so it falls back to the "magic" routing.
