### ISSUE TITLE
SQL Query returns 0 rows but should be one

### ISSUE THREAD

**Issue by Tewdyn** [bcit-ci/CodeIgniter#4505]
Hello,
I have to following SQL query:
`SELECT `email`, `email`, `id`, `password`, `active` FROM `users` WHERE `email` = 'admin@admin.com' ORDER BY `id` DESC LIMIT 1`
If I run the query through codeigniter like this:
```
		$query = $this->db->select('email, id, password, active')
		                  ->where('email', $identity)
		                  ->limit(1)
		    			  ->order_by('id', 'desc')
		                  ->get($this->tables['users']);
```
`$query->num_rows() returns `0

If I run the same query directly in the mysql console (same user, password) it returns one row like it should.

Any help is appreciated

**Comment by Rakesh69** [comment]
$result=$query->num_rows();
return $result->result();

it will work perfectly

**Comment by narfbg** [comment]
Please ask such questions on our [forums](http://forum.codeigniter.com/) instead. This is a bug tracker.
