### ISSUE TITLE
CI 3.0+ SimpleSAMLPHP authentication doesn't work

### ISSUE THREAD

**Issue by hosseinis** [bcit-ci/CodeIgniter#4508]
I've tried this with different versions of CI (3.0.0 and 3.0.4) and I hope I can have an answer for it here. I use SimpleSAMLPHP [Saml](https://simplesamlphp.org/) for my project and it seems have issues on CI version > 3.0. If SimlpleSAMLPHP is included in the third-party folder then the following fails:

> public static function setTrackId($trackId)
>      {
>          self::$trackid = $trackId;
>      }
> 

It is unable to set the static “$trackid" variable.  This seems to be a general issue with static variables in other places on CI3 as well.
The tracked variable is defined as:

> const NO_TRACKID = '_NOTRACKIDYET_';
>     /**
>      * This variable holds the track ID we have retrieved from the session class. It can also be NULL, in which case
>      * we haven't fetched the track ID yet, or self::NO_TRACKID, which means that we are fetching the track ID now.
>      */
>     private static $trackid = self::NO_TRACKID;

I noticed also if I don't load the session library, then Saml authentication works. However I can't keep session and stuff without having CI session.

I wonder if you are aware of this or care to check and provide a fix for this.I wanted to report it since I would like to move my projects over to 3.0.

Please let me know if you want me to provide additional information.

**Comment by narfbg** [comment]
There's no issue with static variables, that's just not possible - with that you're rather describing a symptom, something that happens *after* whatever else is already broken.
From a quick glance at [simplesamlphp/simplesamlphp](https://github.com/simplesamlphp/simplesamlphp), it looks like you can't use it if another PHP session (in this case started by CI) is already started, although there could be options to work around that.

Either way, this is a bug tracker and third-party libraries are not CodeIgniter's concern. If you're seeking help, please open a thread on our [forums](http://forum.codeigniter.com).
