### ISSUE TITLE
Blocking error in ActiveRecord

### ISSUE THREAD

**Issue by nrobuk** [bcit-ci/CodeIgniter#4509]
Good day!
I am just portate my project from CI v1 to CI v3.
Need help with blocking problem with SELECT_SUM function.
Example:
'$sql->select_sum($this->parts_table . ".price * " . $this->basket_table . ".ordered", 'total_sum');'
The result is:
>Error Number: 42000/1064
>
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`tbl_order_basket`.`ordered`) AS `total_sum` FROM `tbl_order` JOIN `tbl_order_ba' at line 1

the problem with parsing string
>SELECT SUM('tbl_model_part'.'price *' 'tbl_order_basket'.'ordered') AS 'total_sum'

**Comment by jim-parry** [comment]
Post support questions on forum.codeigniter.com, thanks.
We use github for bug tracking.

**Comment by nrobuk** [comment]
But this is a bug and steps for reproduce.

**Comment by jim-parry** [comment]
@narfbg What do you think?

**Comment by narfbg** [comment]
Not sure ... we've never really supported expressions.

**Comment by nrobuk** [comment]
In the first version of CI expression did not give the error.

**Comment by narfbg** [comment]
I'm aware of that, but that doesn't mean it was a *supported* use case - it's designed to work with a single field name, not expressions.

**Comment by nrobuk** [comment]
Ok. I think you have three ways to fix this :)
1) add boolean parameter to function "as-is"=true|false
2) fix parse function %)
3) I can find problem and make a patch for you :)

**Comment by narfbg** [comment]
... or zero, because you can't fix what's not broken.

As I said - `select_sum()` and its other aggregate function counterparts only accept a *field name*.

**Comment by nrobuk** [comment]
I am fixed my problem by replacing function "protect_identifiers" in class CI_DB_driver ver 3.0.5 on same function from version 1.7.3 with some name fixes. It is works for now.... I will continue tests

**Comment by narfbg** [comment]
Don't monkey-patch the framework ... how're you going to update it later?

Just use `select()`.

**Comment by nrobuk** [comment]
I am found the function with problem for you? Your's turn too find how to fix it and make code more flexible. 
No need to get angry and try to insult me ​​:) it's very difficult to do. Your framework is very good and I just want him to become even better. Best wishes from Russia.

**Comment by narfbg** [comment]
How on earth did I try to insult you?

**Comment by nrobuk** [comment]
Maybe I just thought , I'm sorry :) 
if you want continue, contact me on skype robuknv. I'll be glad to hear you :) my Bulgarian colleague :)
