### ISSUE TITLE
Security class replacement counteracts validation

### ISSUE THREAD

**Issue by justanotherprogrammer0** [bcit-ci/CodeIgniter#4510]
In certain scenarios, the replacement done by the security class to sanitize can cause the string to exceed the expected length.

Take the following example:
`<script>alert('tst');</script>`
With validation, I use the rule max_length[30].  When validation runs, it will be successful as that string is <= 30 characters.  Then, sanitizing runs, and this string will be replaced with:
`[removed]alert('tst');[removed]`
which is now 31 characters.  If I was storing to a database field that only allows 30 characters, this replacement just broke my query.

While I appreciate the sanitizing this class does, replacing a suspicious string with a longer string AFTER validation has already run it problematic.Although I realize this is an edge case, it is still a flaw that can cause unexpected errors.  I get that it is attempting to let you know something was removed, but this replacement needs to either happen prior to validation, or replaced with something else.  I don't know what the ideal approach would be to solve this.

**Comment by DavisMiculis** [comment]
What if you run sanitizing first, and then string length validation?

**Comment by justanotherprogrammer0** [comment]
That would still require a modification to Codeigniter, as it is the one that runs the `CI_Form_validation` class, then the `CI_Security` class.

**Comment by narfbg** [comment]
Then don't use global_xss_filtering - it's deprecated.
And don't use `xss_clean()` on inputs - we already advise against this in the documentation.

**Comment by justanotherprogrammer0** [comment]
Even though I have been using CI3 for a while now, I had missed that was deprecated.  Sorry about that...I guess I should have asked in the forum before filing it as a bug.  Thank you for your response - setting `global_xss_filtering` to false solved my problem.  I was aware of the `xss_clean()` portion.
