### ISSUE TITLE
$route['default_controller'] does not work if using controller in folder

### ISSUE THREAD

**Issue by himphen** [bcit-ci/CodeIgniter#4511]
For example when I set a controller in folder, i.e.
`$route['default_controller'] = "folder/class";`
It will always return 404 error.

After my study, CI finds wrong file so it trigger 404 error in system/core/Router.php line 303.
When I echo `APPPATH.'controllers/'.$this->directory.ucfirst($class).'.php'`, it return `/var/www/html/web/application/controllers/Folder.php`.

**Comment by himphen** [comment]
I just read the doc and it mentioned this is not a bug. So I closed this issue.

**Comment by narfbg** [comment]
Marking as duplicate of #2849.
