### ISSUE TITLE
DB_Driver:: _field_data() has not exists?

### ISSUE THREAD

**Issue by pentagonal** [bcit-ci/CodeIgniter#4512]
I was Built With CI 3 , and use mysqli as driver , and then call field_data()
but no luck .. it was surprise me, I got an error becasue method _field_data() has not exists on mysqli_driver.php

I was try to search code on current repo :

https://github.com/bcit-ci/CodeIgniter/search?utf8=%E2%9C%93&q=_field_data%28

and then I was found the problem is on **DB_Driver** that **mysql_driver** and another files does not have method `_field_data`
```php
	/**
	 * Returns an object with field data
	 *
	 * @param	string	$table	the table name
	 * @return	array
	 */
	public function field_data($table)
	{
		$query = $this->query($this->_field_data($this->protect_identifiers($table, TRUE, NULL, FALSE)));
		return ($query) ? $query->field_data() : FALSE;
	}
```

on much of driver does not have method `_field_data` isn't right? or just me?

this actually line :
https://github.com/bcit-ci/CodeIgniter/blob/3.0-stable/system/database/DB_driver.php#L1374

**Comment by narfbg** [comment]
The drivers that don't have `_field_data()` have a `field_data()` method instead, directly overriding the parent that you've linked.
