### ISSUE TITLE
Upload .mov video extension.

### ISSUE THREAD

**Issue by Gujarats** [bcit-ci/CodeIgniter#4517]
I'm tying to upload video file in .mov file extension other video file such as mp4, flv is working but when tyring to upload .mov it doesn't work.

here is my code : 

```
public function add_video(){
    if (isset($_FILES['video']['name']) && $_FILES['video']['name'] != '') {
        unset($config);
        $date = date("ymd");
        $configVideo['upload_path'] = './video';
        $configVideo['max_size'] = '9000000000';
        $configVideo['allowed_types'] = 'mov|avi|flv|wmv|mp3|mp4';
        $configVideo['overwrite'] = FALSE;
        $configVideo['remove_spaces'] = TRUE;
        $video_name = $date.$_FILES['video']['name'];
        $configVideo['file_name'] = $video_name;

        $this->load->library('upload', $configVideo);
        $this->upload->initialize($configVideo);
        if(!$this->upload->do_upload('video')) {
            echo $this->upload->display_errors();
        }else{
            $videoDetails = $this->upload->data();
            $data['video_name']= $configVideo['file_name'];
            $data['video_detail'] = $videoDetails;
            $this->load->view('/upload_video/show', $data);
        }

    }else{
        echo "Please select a file";
    }
  }
```

The error message that I'm getting after upload .move video is this 
**The filetype you are attempting to upload is not allowed.**
I would love to ask how to fix this in Codeigniter, yes using the * sign in allowed type fix the issue but that would be allowing user to upload all the extention file. 
Thank you

NOTE : I'm using Codeigniter 3.0.4

**Comment by narfbg** [comment]
This is a common problem that depends on your server environment, not a CodeIgniter bug.

Please open a thread on our [forums](http://forum.codeigniter.com/) instead.

**Comment by Gujarats** [comment]
Oh okay, thanks for the link that lead me to the forum.
