### ISSUE TITLE
Help needed with translating urls

### ISSUE THREAD

**Issue by valjar** [bcit-ci/CodeIgniter#4529]
HI!
I'm working on [uri language identifier](https://github.com/bcit-ci/CodeIgniter/wiki/uri-language-identifier). I don't see option how to translate url/contoller also.  
So let say i have two languages (en, si).
http://mypage.com/si/contact
http://mypage.com/en/contact
Everything works fine, but i whould like to translate url also, so when the language is /si/, i whould like that url of contact looks like this
http://mypage.com/si/kontakt
How to achieve desired effect? Probably with routs, but i need help how.

Thank you in advance!
Regards,
Davor

**Comment by narfbg** [comment]
This is a bug tracker, we don't provide the kind of help you're looking for.

Post on our [forums](http://forum.codeigniter.com/) instead.
