### ISSUE TITLE
form_validation issue

### ISSUE THREAD

**Issue by keulu** [bcit-ci/CodeIgniter#4535]
Hi guys, 

Since ci 3.0.5, i can't validate my phone number (french phone but it doesn't matter)

array(
    'field' => 'phone',
    'label' => '"Téléphone"',
    'rules' => 'exact_length[10]|numeric',
),

in CI 3.0.4,in my mind, it's validate empty field, but i did my update to CI3.0.5 yesterday, and a customer send me a mail today with that bug.

can you check that ?

**Comment by kakysha** [comment]
What we need to check? Your bug?

**Comment by keulu** [comment]
if it's normal with that rule that you can't validate empty field. (maybe it's the normal way)

**Comment by narfbg** [comment]
Sorry, but this is a bug tracker, not a place for personal requests.
Please post on our [forums](http://forum.codeigniter.com/) instead.

**Comment by keulu** [comment]
i'm not here for my bug... i'm not asking help to resolve that.

but ok... np...

**Comment by keulu** [comment]
well in fact, it's maybe not a bug but it's not in your change log. 

and it's since version 3.0.1
