### ISSUE TITLE
Join escapes floating point numbers

### ISSUE THREAD

**Issue by hoersten** [bcit-ci/CodeIgniter#4536]
Sometimes when doing a join including floating point numbers in MySQL, the Query Builder escapes the floating point numbers.  This is a bug in 3.0.4 and 3.0.5, it was NOT a bug in 2.1.4.

    $this->db->select('applications.zip')  
    ->from('applications')
    ->join('zipcodes', 'applications.zip = zipcodes.postal_code AND zipcodes.longitude between (-73.9967 - 10 / abs(cos(radians(40.7484))*69)) AND (-73.9967 + 10 / abs(cos(radians(40.7484))*69))  AND zipcodes.latitude between (40.7484 - 10 / 69) AND (40.7484 + 10 / 69)');
    $this->db->get();
    print_r($this->db->last_query());

Generates the SQL:

    SELECT `applications`.`zip`
    FROM `applications`
    JOIN `zipcodes` ON `applications`.`zip` = `zipcodes`.`postal_code` 
    AND `zipcodes`.`longitude` between (-73.9967 - 10 / abs(cos(radians(40.7484))*69)) AND (`-73`.`9967` + 10 / abs(cos(radians(40.7484))*69)) 
    AND `zipcodes`.`latitude` between (40.7484 - 10 / 69) AND (`40`.`7484` + 10 / 69)

Instead of the SQL, specifically the 2nd parameters to between

    SELECT `applications`.`zip`
    FROM `applications`
    JOIN `zipcodes` ON `applications`.`zip` = `zipcodes`.`postal_code` 
    AND `zipcodes`.`longitude` between (-73.9967 - 10 / abs(cos(radians(40.7484))*69)) AND (-73.9967 + 10 / abs(cos(radians(40.7484))*69)) 
    AND `zipcodes`.`latitude` between (40.7484 - 10 / 69) AND (40.7484 + 10 / 69)

**Comment by hoersten** [comment]
Current workaround is to not use between, but instead >= and <=.

    $this->db->select('applications.zip')  
    ->from('applications')
    ->join('zipcodes', 'applications.zip = zipcodes.postal_code AND (zipcodes.longitude >= (-73.9967 - 10 / abs(cos(radians(40.7484))*69)) AND zipcodes.longitude <= (-73.9967 + 10 / abs(cos(radians(40.7484))*69))) AND (zipcodes.latitude >= (40.7484 - 10 / 69) AND zipcodes.latitude <= (40.7484 + 10 / 69))');
    $this->db->get();
    print_r($this->db->last_query());

**Comment by narfbg** [comment]
If it didn't escape floating point numbers, it would escape something else - function names, parentheses, mathematical operators, etc. The Query Builder is simply not designed to work with complex expressions.

CI 2.x didn't have this "bug" because it didn't try to escape at all.

Use the $escape parameter that almost all QB methods have to disable escaping.
