### ISSUE TITLE
CSRF and main session name conflict?

### ISSUE THREAD

**Issue by fulopm** [bcit-ci/CodeIgniter#4537]
Hello!

Today I tried to turn on the global csrf protection, and after I have set the parameter in the config file, I tried all forms in my webapp, and none of them worked. After a long time searching for solution, revealed that the error was a name conflict, both csrf protection sessions and main sessions name were set to the same. After I renamed one, it was began to work. Was it a bug, or the natural behaviour of sessions? Well, sorry if the second one is the truth, and please close my issue then. Thank you.

**Comment by narfbg** [comment]
CI's CSRF protection doesn't use sessions, nor do the cookie names used for session and csrf_token match by default - you have to intentionally make them identical in order to create this issue.

**Comment by fulopm** [comment]
I named them accidentally, but yes, the occurrence of this issue is rare maybe. :) Thanks!
