### ISSUE TITLE
codigniter model issue

### ISSUE THREAD

**Issue by pathic666** [bcit-ci/CodeIgniter#4538]
when i was looking to run 'nonImg_QA'  controller index page there was an error - Unable to locate the model you have specified: nonimg_qa_model..
my model class name file is nonImg_QA_model
class name as NonImg_QA in model file ...src working in localhost..please fine my error ..

**Comment by narfbg** [comment]
This is a bug tracker, we don't provide help for such requests here.
Please post on our [forums](http://forum.codeigniter.com/) instead.
