### ISSUE TITLE
[Feature request] Form validation: "dependable validation" with callbacks

### ISSUE THREAD

**Issue by ofry** [bcit-ci/CodeIgniter#4545]
Hello.

Form validation works great on forms with independent fields.

But if fields are dependent?

For sample, I have 4 fields. Form should be valid, if:
function(field1) < function(field2) < function(field3) < function(field4) if all of them not empty.

If field is empty, it should be skipped from this inequality.

Or field is required only if another field have a specific value...

> Any native PHP function that accepts one parameter can be used as a rule, like ``htmlspecialchars()``, ``trim()``, etc.

So I need to use functions which accepts many parameters as rule.

**Comment by narfbg** [comment]
This is already possible with anonymous functions (or in some cases with clever usage of existing rules). We can't add more and more logic for every edge case like this one, and I'm pretty sure it would break some existing rules like regexp_match anyway.

**Comment by ofry** [comment]
Than there is a big lack of documentation. Can you provide me the sample how it's possible with anonymous functions? I see only sample with one parameter in documentation.

`$this->form_validation->set_rules(
        'username', 'Username',
        array(
                'required',
                array(
                        'username_callable',
                        function($str)
                        {
                                // Check validity of $str and return TRUE or FALSE
                        }
                )
        )
);`

**Comment by narfbg** [comment]
There's no lack of documentation - anonymous functions are a PHP feature and we document what CI provides, not how PHP works.

    $field1 = $this->input->post('field2');
    $field2 = $this->input->post('field2');
    $field3 = $this->input->post('field3');
    $callback = function() use ($field1, $field2, $field3) {
        // Your logic here
    };

... and it's not like a controller callback couldn't lookup other fields via `$this->input->post()`.
