### ISSUE TITLE
using where(); without an assosiative parameter name breaks queries using between

### ISSUE THREAD

**Issue by rafaga** [bcit-ci/CodeIgniter#4546]
this bug its weird ...
constructing a query using $this->db->where(""," DATEDIFF(dd, act_Actividad.fecha_ini, act_Actividad.fecha_fin) BETWEEN 0 AND 14 ");. and executing the final query give it a syntax error on database manager.

this is the result:
 ... DATEDIFF(dd, act_Actividad.fecha_ini, act_Actividad.fecha_fin) BETWEEN0 AND 14 ...
but if instead i do:
     $this->db->where(""," DATEDIFF(dd, act_Actividad.fecha_ini, act_Actividad.fecha_fin) BETWEEN '0' AND 14 ");
this is resolved to: 
... DATEDIFF(dd, act_Actividad.fecha_ini, act_Actividad.fecha_fin) BETWEEN '0' AND 14 ...

**Comment by narfbg** [comment]
It's not a bug ... you're not supposed to use an empty string as the first parameter.
