### ISSUE TITLE
I have found a bug in session class

### ISSUE THREAD

**Issue by ShavidzeT** [bcit-ci/CodeIgniter#4547]
Depending on codigniter:
```php
$array_items = array('username' => '', 'email' => '');
$this->session->unset_userdata($array_items);
```
This function doesn't work correctly, because using associative massive doesn't clear session.
I hope we can solve this problem

**Comment by narfbg** [comment]
You're telling it to unset `$_SESSION['']` and `$_SESSION['']` again - that's not a bug.

**Comment by adamos42** [comment]
Hmm, a bit misleading on the documentation: "This method also accepts an array of item keys to unset", the item keys should be "session item keys" to avoid confusion.

**Comment by narfbg** [comment]
No it shouldn't.

The word "session" brings no additional meaning; if anything is to be changed in there it's to remove the word "item", which is also redundant.
