### ISSUE TITLE
[Feature Request] Way to manually put form validation error messages

### ISSUE THREAD

**Issue by ofry** [bcit-ci/CodeIgniter#4548]
This is related on #4545 

After "first validation" (independent fields) and prepping the form data, I want to do extended validation with dependent fields.

I can do it via code like:
```
if ($this->form_validation->run() == FALSE) {
//show form with data
}
else if (extended_validation() == FALSE) {
//show form with data
}
else {
//do something with data
}
```

But I need to put my custom error message about failing extended validation will be shown in
`echo validation_errors();`

Can you provide this way?

**Comment by narfbg** [comment]
You already can set messages for custom validation rules, and this has nothing to do with #4545.

Next time, please open a thread on the [forums](http://forum.codeigniter.com/) instead.
