### ISSUE TITLE
 CI 2.2.6 upload file demo not working?

### ISSUE THREAD

**Issue by seaguest** [bcit-ci/CodeIgniter#4549]
I am using codeigniter 2.2.6 for my server (I am a newbie in CI), when I tried to make the upload file demo work, but nothing happened when I clicked on the submit button.

Here is the user guide that I followed:

[http://www.codeigniter.com/userguide2/libraries/file_uploading.html](url)

the view file:

    <html>
    <head>
    <title>Upload Form</title>
    </head>
    <body>
    
    <?php echo $error;?>
    
    <?php echo form_open_multipart('upload/do_upload');?>
    
    <input type="file" name="userfile" size="20" />
    
    <br /><br />
    
    <input type="submit" value="upload" />
    
    </form>
    
    </body>
    </html>

the controller:

    <?php
    class Upload extends CI_Controller {
    	function __construct() {
    		parent::__construct ();
    		$this->load->helper ( array (
    				'form',
    				'url' 
    		) );
    	}
    	function index() {
    		echo CI_VERSION;
    		
    		$this->load->view ( 'upload_form', array (
    				'error' => ' ' 
    		) );
    	}
    	
    	function do_upload() {
    		$config ['upload_path'] = './uploads/';
    		$config ['allowed_types'] = 'gif|jpg|png';
    		$config ['max_size'] = '100';
    		$config ['max_width'] = '1024';
    		$config ['max_height'] = '768';
    		
    		$this->load->library ( 'upload', $config );
    		
    		echo "step 1";
    		
    		if (! $this->upload->do_upload ()) {
    			echo "step 2";
    			
    			$error = array (
    					'error' => $this->upload->display_errors () 
    			);
    			
    			$this->load->view ( 'upload_form', $error );
    		} else {
    			echo "step 3";
    				
    			$data = array (
    					'upload_data' => $this->upload->data () 
    			);
    			
    			$this->load->view ( 'upload_success', $data );
    		}
    	}
    }
    ?>

I can see the browse and submit button, after I select a file, the file name is correctly displayed but when I click on submit, nothing happens, it looks like that the submit click is not handled.

As you can see, I set 3 echo "step ." to follow the flow, but none of them get printed, I don't know why.

Could anyone help? please explain me the logic behind that button click handling.

  [1]: http://www.codeigniter.com/userguide2/libraries/file_uploading.html

**Comment by narfbg** [comment]
CI2.x is no longer supported.

And also, this is a bug tracker. Please open a thread on our [forums](http://forum.codeigniter.com/) instead.
