### ISSUE TITLE
[Bug] Grouped rules of form validation doesn't working

### ISSUE THREAD

**Issue by ofry** [bcit-ci/CodeIgniter#4550]
Quote from documentation.

> Creating Sets of Rules
> 
> In order to organize your rules into “sets” requires that you place them into “sub arrays”. Consider the following example, showing two sets of rules. We’ve arbitrarily called these two rules “signup” and “email”. You can name your rules anything you want:
> 
> $config = array(
>         'signup' => array(
>                 array(
>                         'field' => 'username',
>                         'label' => 'Username',
>                         'rules' => 'required'
>                 ),
>                 array(
>                         'field' => 'password',
>                         'label' => 'Password',
>                         'rules' => 'required'
>                 ),
>                 array(
>                         'field' => 'passconf',
>                         'label' => 'Password Confirmation',
>                         'rules' => 'required'
>                 ),
>                 array(
>                         'field' => 'email',
>                         'label' => 'Email',
>                         'rules' => 'required'
>                 )
>         ),
>         'email' => array(
>                 array(
>                         'field' => 'emailaddress',
>                         'label' => 'EmailAddress',
>                         'rules' => 'required|valid_email'
>                 ),
>                 array(
>                         'field' => 'name',
>                         'label' => 'Name',
>                         'rules' => 'required|alpha'
>                 ),
>                 array(
>                         'field' => 'title',
>                         'label' => 'Title',
>                         'rules' => 'required'
>                 ),
>                 array(
>                         'field' => 'message',
>                         'label' => 'MessageBody',
>                         'rules' => 'required'
>                 )
>         )
> );
> 
> Calling a Specific Rule Group
> 
> In order to call a specific group, you will pass its name to the run() method. For example, to call the signup rule you will do this:
> 
> if ($this->form_validation->run('signup') == FALSE)
> {
>         $this->load->view('myform');
> }
> else
> {
>         $this->load->view('formsuccess');
> }
> 
> 

Way to reproduce.

1) Create controller, create $config with some rules and error messages.

And validate form via
```
$this->form_validation->set_rules($config);
if ($this->form_validation->run() == FALSE)
```

All will work fine.

But create
$errorconf = array(
'config' => $config
);

and try to validate via:

```
$this->form_validation->set_rules($errorconf);
if ($this->form_validation->run('config') == FALSE)
```

This code `$this->form_validation->run('config')` will return FALSE all times without any errors displayed in 

`echo validation_errors();`

**Comment by ofry** [comment]
CI 3.0.5

**Comment by narfbg** [comment]
The part of the documentation that you're quoting is a **sub-section** of "Saving Sets of Validation Rules to a Config **File**".

This is your third invalid bug report in a row, and last time I [asked you](https://github.com/bcit-ci/CodeIgniter/issues/4548#issuecomment-198687354) to open a forum thread exactly so that we avoid this. Please take a note.
