### ISSUE TITLE
v2.2.6 captcha infinite loop and missing characters

### ISSUE THREAD

**Issue by MzHub** [bcit-ci/CodeIgniter#4553]
I know 2.x only gets security updates, but I'll raise this in case someone else gets bitten by it.

_EDIT: Alright, I re-read the notice, and it said 2.x is not updated **at all** after 31. Oct 2015, so I now realize I should not have raised this issue. Feel free to close it, sorry._

The first is that `create_captcha` has been backported, but the `$defaults` array in it was not. This can likely cause other issues as well, but for me it manifested as a captcha without text at all, because `word_length` is a new parameter that was undefined.

Once I added the defaults from 3.x to fix that, I got to a nastier bug, where [this](https://github.com/bcit-ci/CodeIgniter/commit/b2fef1405913348957ea0823c254799109e7abf9#diff-a04014aa22c4cfdbe54475e4fd211053R149) row causes an infinite while loop:

```PHP
if (($rand_index = unpack('C', $bytes[$byte_index++])) > $rand_max)
```

`$rand_index` gets assigned an array instead of a number. I added `array_pop()` around `unpack` to fix it for my app, not a clean solution though.

**Comment by narfbg** [comment]
2.x does NOT get security updates anymore!

2.2.6 was the last ever 2.x release and it is officially abandoned.
