### ISSUE TITLE
Any plan to add support for php7.0

### ISSUE THREAD

**Issue by vrkansagara** [bcit-ci/CodeIgniter#4555]
Hello CodeIgniter team.

 Any plan to add support for php7.0

**Comment by DavisMiculis** [comment]
CodeIgniter already supports PHP 7. I've been running few CodeIgniter apps on PHP 7.0.3 without any problems.

**Comment by jim-parry** [comment]
Questions like this should be asked on our [forum](http://forum.codeigniter.com). We use github issues for bug tracking.
