### ISSUE TITLE
Markdown error in the documentation (form validation)

### ISSUE THREAD

**Issue by vichenze** [bcit-ci/CodeIgniter#4557]
There is an error here : https://www.codeigniter.com/userguide3/libraries/form_validation.html#callbacks-your-own-validation-methods

>  just add it normally after the method name between square brackets, as in: “callback_foo* * [bar] * *”

The double * are shown instead of rendering [bar] with a strong font.

**Comment by narfbg** [comment]
FYI, that's ReST or reStructured Text, not Markdown.

**Comment by narfbg** [comment]
FYI, that's ReST or reStructured Text, not Markdown.
