### ISSUE TITLE
Session not destroyed upon closing Firefox

### ISSUE THREAD

**Issue by JasonLighthunter** [bcit-ci/CodeIgniter#4558]
I encountered the following:
under the options of firefox I have "When firefox start: show my windows and tabs from last time"
my session part of config.php is as follows:
`$config['sess_driver'] = 'database';`
`$config['sess_cookie_name'] = 'ci_session';`
`$config['sess_expiration'] = 0;`
`$config['sess_save_path'] = 'ci_sessions';`
`$config['sess_match_ip'] = FALSE;`
`$config['sess_time_to_update'] = 300;`
`$config['sess_regenerate_destroy'] = FALSE;`

when i reopen the browser after clossing the session is still the same as it was before closing.
This behavior does not appear in a clean install of chrome or when I set "When firefox starts" to the "show blank page option."

**Comment by narfbg** [comment]
We can't control Firefox ...

**Comment by Samudrika** [comment]
I have similar kind of requirement. 
I have mentioned "session_expire=0" in config file of my application. And on browser close session is destroyed. 

But if in Firefox "show my windows and tabs from last time" is selected , then on closing the browser session is not being destroyed. 

So Is there any solution for it?
