### ISSUE TITLE
CI 3.0.6 escape_like_str incorrectly escapes underscores (_)

### ISSUE THREAD

**Issue by blasto333** [bcit-ci/CodeIgniter#4559]
In CI 3.0.6 underscores are escaped by `!` instead of `\` resulting in issue where query doesn't return results expected.

Example query:
```
$this->db->from('customers');
$this->db->join('people','customers.person_id=people.person_id');	
$this->db->where("(first_name LIKE '%".$this->db->escape_like_str($search)."%' or 
last_name LIKE '%".$this->db->escape_like_str($search)."%' or 
email LIKE '%".$this->db->escape_like_str($search)."%' or 
phone_number LIKE '%".$this->db->escape_like_str($search)."%' or 
account_number LIKE '%".$this->db->escape_like_str($search)."%' or 
company_name LIKE '%".$this->db->escape_like_str($search)."%' or 
CONCAT(`first_name`,' ',`last_name`) LIKE '%".$this->db->escape_like_str($search)."%' or 
CONCAT(`last_name`,', ',`first_name`) LIKE '%".$this->db->escape_like_str($search)."%' or 
CONCAT(`last_name`,', ',`first_name`, ' (',".$this->db->dbprefix('customers').".person_id,')') LIKE '%".$this->db->escape_like_str($search)."%'
) and deleted=0");		

```

`SELECT * FROM `phppos_customers` JOIN `phppos_people` ON `phppos_customers`.`person_id`=`phppos_people`.`person_id` WHERE (`first_name` LIKE '%find!_me%' or `last_name` LIKE '%find!_me%' or `email` LIKE '%find!_me%' or `phone_number` LIKE '%find!_me%' or `account_number` LIKE '%find!_me%' or `company_name` LIKE '%find!_me%' or CONCAT(`first_name`,' ',`last_name`) LIKE '%find!_me%' or CONCAT(`last_name`,', ',`first_name`) LIKE '%find!_me%' or CONCAT(`last_name`,', ',`first_name`, ' (',phppos_customers.person_id,')') LIKE '%find!_me%') and `deleted` =0 ORDER BY `last_name` ASC LIMIT 20`

**Comment by narfbg** [comment]
Duplicate of #4462.

**Comment by blasto333** [comment]
I don't see a workaround in #4462; it is just updated documentation on what I think is incorrect functionality for escaping. See http://stackoverflow.com/a/17102616

**Comment by narfbg** [comment]
Well, read the documentation ...

**Comment by blasto333** [comment]
Can't you just change line 338 in DB_driver.php

FROM:
`protected $_like_escape_chr = '!';
`
TO:
`protected $_like_escape_chr = '\';`

**Comment by narfbg** [comment]
I can, but I shouldn't and I won't.

The escape character isn't the problem, the existence of `escape_like_str()` is.

**Comment by blasto333** [comment]
Ok I will do the workaround
