### ISSUE TITLE
Session and long polling

### ISSUE THREAD

**Issue by matrox445** [bcit-ci/CodeIgniter#4560]
Hello,

I've just update my app from CI 2.2 to CI 3.0.6. By the way, thanks for keeping CI alive !
Everything work fine, except pages with long polling.
 
Here's how i test it : 

Load a page. Launch a long polling (xhr) for 30 seconds. Try to reload the page. The page will refresh only at the end of the long polling call. 

**Log of the first load :**

```
Loading Time: Base Classes  	0.0171
Controller Execution Time 	0.0469
Total Execution Time  	        0.0647
```

**Log of the refresh :**

```
Loading Time: Base Classes  	0.0172
Controller Execution Time       29.0245
Total Execution Time  	        29.0424
```

**The problem seems to be this request :** 

**28.9773**  _SELECT GET_LOCK('bfa50f3e52f4ed5967e97e0fe5120bb7bfbc1da2', 300) AS ci_session_lock_, where query time is always the long polling remaining time.

I use database sessions.

Sorry for my english, hope you will understand my problem...

Regards

**Comment by narfbg** [comment]
This is not a bug. What you're describing as a "problem" is the intended behavior.

Please post on our [forums](http://forum.codeigniter.com/) instead.
