### ISSUE TITLE
redirect() work unexpectedly when another site_url() exists

### ISSUE THREAD

**Issue by maisumakun** [bcit-ci/CodeIgniter#4561]
I am creating systems using CodeIgniter and WordPress, integrated together.

WordPress also has function [`site_url()`](https://codex.wordpress.org/Function_Reference/site_url), so loading CI's `url_helper` after WordPress causes `site_url()` to remin WordPress version. (this is expected, though)

What I wondered is, another functions in `url_helper` (such as `redirect()`) depend on `site_url()`. So, in this environment, CodeIgniter's helper functions call WordPress' `site_url()`, resulting in unexpected behaviors.

I think it is rare case, but using `CI_Config::site_url()` the dependency can be easily removed.

**Comment by narfbg** [comment]
You're not supposed to mix CI and WP; that's not a use case we'll support.
