### ISSUE TITLE
Fatal error: Call to undefined method Memcached::quit()

### ISSUE THREAD

**Issue by jeffstoner** [bcit-ci/CodeIgniter#4562]
This isn't a bug with CodeIgniter but wanted to get it logged here in case someone searched for it, then they'll find a workaround. I'll post this in the forums, too.

I'm testing the 3.0.6 release and came across this error on all of my pages that use the Memcached caching driver.

Symptom: release 3.0.6 of CodeIgniter added a destructor to the Cache_memcached.php driver that calls close() (if using the memcache) or quit() (if using memcached.) If you use a sufficiently old version  of the memcached PECL extension (such as EPEL's php-pecl-memcached RPM for RHEL6) then you will get this error message.

Cause: the quit() method was not added to the memcached PECL extension until version 2.0.0.

**Comment by narfbg** [comment]
If it's not a bug, then don't "log" it here.
And if you wanted to do that so it comes up when people search for it ... well, if you had searched, you'd find [this](https://github.com/bcit-ci/CodeIgniter/pull/4522#issuecomment-196849320).

**Comment by narfbg** [comment]
It is a bug though ... I just pushed the fix.

I also removed part of your description - please **DO NOT** ever suggest people manually edit the framework.
