### ISSUE TITLE
Little problem about class name of model in CodeIgniter

### ISSUE THREAD

**Issue by satyakresna** [bcit-ci/CodeIgniter#4566]
Hi, i have some problem about class name of model in CI. When create a model, ex. "User_model.php" (name as file) and create class name User_model, and it works when i testing.
But, when i create model, ex "user_model.php" (name as file) and create class name User_model, it also works when i testing.

If i do the second option, i think it's not consistent. Because, the documentation said that it must like the first option. I know this is the little problem, but i think it's inconsistent. I hope the team can fix this problem asap and i hope CI can be a competitive framework along Laravel, Yii, and other.

Note: i use CI version 3.X

**Comment by narfbg** [comment]
That's something you're personally annoyed by, not a problem in any other way.
