### ISSUE TITLE
Memcached fix

### ISSUE THREAD

**Issue by sasbass** [bcit-ci/CodeIgniter#4567]
On **CI_Session_memcached_driver** method **open**
put this check
if(!class_exists('Memcached')){
            die('<strong>Memcached</strong> class not installed.<br/>
                Please install first <strong>Memcached</strong> on your server.');
        }
        
		$this->_memcached = new Memcached();

**Comment by narfbg** [comment]
You are responsible to know that Memcached isn't available on the server before you configure CodeIgniter to use it ...

**Comment by sasbass** [comment]
If I use however Memcache no Memcached? what happens then?

**Comment by narfbg** [comment]
Nothing different ... you'd be trying to use something that the library doesn't support.

**Comment by sasbass** [comment]
can you do for Memcache?

**Comment by narfbg** [comment]
No.

**Comment by sasbass** [comment]
Why?

**Comment by narfbg** [comment]
Because I don't have a Memcache instance, nor the time, desire and/or obligation to do so.
