### ISSUE TITLE
$this->db->where($string) NOT escaping input

### ISSUE THREAD

**Issue by thlassche** [bcit-ci/CodeIgniter#4572]
The documentation states:

All values passed to this function are escaped automatically, producing safer queries.

This, however, is not true.

For example, this breaks:

```
$string = "'foo";

$this->db->where("name = $foo");
```

This is a huge security risk. Any comments on this?

Tested and confirmed on both v2 and v3

**Comment by narfbg** [comment]
Values - variables that you pass in via the second parameter, which is very intentionally called `$value`.

Not arbitrary partial SQL ... it's not magic.
