### ISSUE TITLE
CI 3.0.6 causing segmentation fault with new mongo php library

### ISSUE THREAD

**Issue by Zelfapp** [bcit-ci/CodeIgniter#4574]
**Steps to reproduce CI bug referenced here:** https://github.com/mongodb/mongo-php-library/issues/153:

- Download my bare bones CI testing repo https://github.com/Zelfapp/ci_mongo
  - Install the [new mongo php driver](http://docs.php.net/manual/en/mongodb.installation.php)
  - Repo already has the new mongo php library
  - Repo has 2 files for testing:
    - https://github.com/Zelfapp/ci_mongo/blob/master/application/controllers/Mongodriver.php (Inside CI framework)
    - https://github.com/Zelfapp/ci_mongo/blob/master/mongo.php (Outside CI framework)
  - Need to adjust Constants in both for mongo instance.
  - Note: mongo php library is autoloaded from https://github.com/Zelfapp/ci_mongo/blob/master/application/config/autoload.php

**or manually test/install on a fresh CI 3.0.6 install:**

- Install the [new mongo php driver](http://docs.php.net/manual/en/mongodb.installation.php)
- Install the [new mongo php library](https://github.com/mongodb/mongo-php-library)
- Autoload mongo php library by adding `require 'vendor/autoload.php';`. (e.g. https://github.com/Zelfapp/ci_mongo/blob/master/application/config/autoload.php)
- Use code below to install test mongo documents and to:
  - Test code in a controller in CI framework. Create a CI controller called Mongodriver.php and place test code in. (e.g. https://github.com/Zelfapp/ci_mongo/blob/master/application/controllers/Mongodriver.php)
  - Test code as a standalone file at root of CI directory outside of CI framework. Create a php file called mongo.php and place test code in. (e.g. https://github.com/Zelfapp/ci_mongo/blob/master/mongo.php)

The code will work outside of CI framework, but will cause a segmentation fault when called from with CI framework.

```php

<?php

define('URI', 'mongodb://localhost:27017');
define('NS', 'test.gh153');

$bulk = new MongoDB\Driver\BulkWrite;
$bulk->insert([
    "created_at" => "2016-03-21T11:18:57-07:00",
    "financial_status" => "paid",
    "cancel_reason" => null,
    "tags" => "1188, FORT BELVOIR VA, kiosk, Processing-Kiosk, Processing-Picking",
]);
$bulk->insert([
    "created_at" => "2016-03-19T13:22:10-07:00",
    "financial_status" => "paid",
    "cancel_reason" => null,
    "tags" => "1188, FORT BELVOIR VA, kiosk, Processing-Kiosk, Processing-Picking",
]);
$bulk->insert([
    "created_at" => "2016-03-19T07:55:44-07:00",
    "financial_status" => "paid",
    "cancel_reason" => null,
    "tags" => "1188, FORT BELVOIR VA, kiosk, Processing-Kiosk, Processing-Picking",
]);
$bulk->insert([
    "created_at" => "2016-03-04T13:08:53-08:00",
    "financial_status" => "paid",
    "cancel_reason" => null,
    "tags" => "1188, FORT BELVOIR VA, kiosk, Processing-Kiosk, Processing-Picking",
]);
$bulk->insert([
    "created_at" => "2016-03-01T07:35:50-08:00",
    "financial_status" => "paid",
    "cancel_reason" => null,
    "tags" => "1188, Fort Belvoir  VA, kiosk, Processing-Picking",
]);

$manager = new MongoDB\Driver\Manager(URI);
$manager->executeBulkWrite(NS, $bulk);

$query = new MongoDB\Driver\Query(
    [
        'cancel_reason' => null,
        'financial_status' => ['$ne' => 'pending'],
        'tags' => new MongoDB\BSON\Regex("kiosk", 'i'),
        'created_at' => ['$gte' => '2016-03-01T03:00:00-04:00', '$lte' => '2016-04-01T02:59:59-04:00'],
        '$or' => [
            ['tags' => new MongoDB\BSON\Regex("Fort Belvoir VA", 'i')],
        ],
    ],
    [
        'limit' => 3,
        'skip' => 0,
        'projection' => ['_id' => 0],
    ]
);

$cursor = $manager->executeQuery(NS, $query);

var_dump($cursor->toArray());
```

**Comment by narfbg** [comment]
I know "crashes in CI and doesn't crash outside of it" makes this look like it's CodeIgniter's fault, but that's not how it works ...

Userspace code is not supposed to cause a segfault in PHP, under any conditions. If you see a PHP segmentation fault, it's either a PHP bug or a bug in the extension that you're using - 100%.

Just to help you understand why running your code doesn't (yet!) crash outside of CI, I'll quote the [Wikipedia page for Segmentation fault](https://en.wikipedia.org/wiki/Segmentation_fault#Causes):

> The proximate cause is a memory access violation

Which makes sense, because running CodeIgniter means running more code and therefore using more memory (and more chances for accessing the wrong memory address) as opposed to the case where you'd execute it in a raw PHP script.  
Chances are, you'll be able to reproduce this segfault with any framework.
