### ISSUE TITLE
base_url/site_url can not work well in virtual host

### ISSUE THREAD

**Issue by mrasong** [bcit-ci/CodeIgniter#4576]
the new version(3.x) of CI changed the `base_url` method from `_SERVER['HTTP_HOST']` to `_SERVER['SERVER_ADDR']`.
It works well for IPV6 severs and unique IP user.
but, we virtual host user can not get a correctly URL by this change.

I check the file `/system/core/Config.php ` between line 91 to 104,

just as I see, CI use `_SERVER['SERVER_ADDR']` instead of `_SERVER['HTTP_HOST']`.
that's why my url  `http://my.host/path/to/file`  in the 3.x version return me an url like `http://	[::1]/path/to/file` or `http://127.0.0.1/path/to/file`.

**Comment by kenjis** [comment]
The behavior is by design, not a bug. Set your base URL.
See http://www.codeigniter.com/user_guide/installation/upgrade_300.html#step-19-make-sure-your-base-url-config-value-is-not-empty

**Comment by mrasong** [comment]
@kenjis I' got it, thx.

**Comment by narfbg** [comment]
Duplicate of #4209.
