### ISSUE TITLE
session has bug

### ISSUE THREAD

**Issue by wolinyy** [bcit-ci/CodeIgniter#4578]
session use memcached driver:
    1、sometime response need 5 seconds;
    2、sometime timeout 30 seconds and log show：Session: Error while trying to obtain lock for xxx

session use files driver:some browser sessionid always change.

**Comment by wolinyy** [comment]
Version is 3.0.3

**Comment by wolinyy** [comment]
Version is 3.0.3

**Comment by narfbg** [comment]
Please upgrade to the latest version and provide more details for the issue if it persists.

**Comment by wolinyy** [comment]
Have found the reason, memcached:touch () there is a problem。
PHP 5.4.45
pecl-memcached-2.2.0
memcached-1.4.4

some browser sessionid always change because linux web date + cookie_lifetime < browser time
