### ISSUE TITLE
Welcome page showing wrong version number

### ISSUE THREAD

**Issue by intekhabrizvi** [bcit-ci/CodeIgniter#4580]
Hello,
I just downloaded a zip from 3.0-stable branch and as soon as i run the welcome control, i see CodeIgniter Version 3.0.7-dev.

Why stable branch is showing dev marking, is this a normal behavior ??

**Comment by narfbg** [comment]
Yes, it's normal - it's a *branch*, not a tag.

Please note that this is a bug tracker. If you have a question or are not 100% sure that something is a bug - post on our [forums](http://forum.codeigniter.com/) instead.
