### ISSUE TITLE
Unable to access an error message corresponding to your field name pan_number.(panValidation)

### ISSUE THREAD

**Issue by Jyotie** [bcit-ci/CodeIgniter#4581]
I have googled and tried to fix this problem. 
1> Auto loaded security
2> Not using xss_clean
3> Callback Function is : 

function dayValidation($dayVaue) {
        $day_regex = "/^(0[1-9]|[12][0-9]|3[01])$/";
        /* return preg_match($day_regex, $dayVaue); */
        if (!preg_match($day_regex, $dayVaue)) {
            $this->form_validation->set_message('dayValidation', 'Invalid Date');
            return false; // invalid day
        } else {
            return true;
        }
    }

4> In application/language/english put the file : MY_form_validation_lang.php with error messages
5> in application/libraries/ put file : MY_form_validation.php with 
public $CI; 
 public function __construct($rules = array()) {
        parent::__construct($rules);
        $this->CI->lang->load('MY_form_validation');
    }

    function run($module = '', $group = '') {
        (is_object($module)) AND $this->CI = &$module;
        return parent::run($group);
    }

And still the error is coming. Dont know whats going on. Please help

**Comment by narfbg** [comment]
This is a bug tracker, we don't answer to general help requests here.

Please post on our [forums](http://forum.codeigniter.com/) instead.
