### ISSUE TITLE
password_*() fallback functions and mbstring.func_override

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#4582]
mbstring.func_override is taken into account in some places in password_hash(). But there are cases of strlen() usage that are unsolved:

https://github.com/bcit-ci/CodeIgniter/blob/4d2628e8aab6d0673ac0a010acbfaa9d76b7d568/system/core/compat/password.php#L76

https://github.com/bcit-ci/CodeIgniter/blob/4d2628e8aab6d0673ac0a010acbfaa9d76b7d568/system/core/compat/password.php#L184

https://github.com/bcit-ci/CodeIgniter/blob/4d2628e8aab6d0673ac0a010acbfaa9d76b7d568/system/core/compat/password.php#L238

**Comment by narfbg** [comment]
These occurences handle all-ASCII data; mbstring.func_override has no effect in those cases.
