### ISSUE TITLE
Attachments are not displayed on iOS stock Email client

### ISSUE THREAD

**Issue by r4ngy4l** [bcit-ci/CodeIgniter#4583]
### The issue happens in the following scenario

1. Construct an HTML email
2. Attach image(s) to the email
3. Make image(s) attached in the previous step to be shown as the part of the email's body (for example a logo on the top)
4. Add other attachments, which are not intended to be shown as a part of the email's body. (for example report in pdf format)

### The Result

Inline images are displayed correctly, but attachments added in step#4 are hidden in iOS's email client.

### The Problem with the current implementation

To make an attachment to be shown inline in the email body, the following code is needed:

```php
$filename = 'images/inline_image.png';
$this->email->attach($filename);
$cid = $this->email->attachment_cid($filename);
// $cid is used in the html
// as the value of an src attribute of an <image> tag for example
```

It goes wrong when `attachment_cid` function is called, because it sets the root multipart to related.
The structure of the message will be the following:

```
multipart/related
  inline_image.png
  report1.pdf
  report2.pdf
  ...
```

According to https://tools.ietf.org/html/rfc2387 the `multipart/related` is 

> used to indicate that each message part is a component of an aggregate whole. It is for compound objects consisting of several inter-related components - **proper display cannot be achieved by individually displaying the constituent parts**.

 (source: https://en.wikipedia.org/wiki/MIME)

As all of the attachments will be the direct child of `multipart/related`, even the "normal" attachments won't be displayed by the stricter email clients (for example iOS's stock email client).

**Comment by robertonline** [comment]
#4585 has been created to fix this issue

**Comment by narfbg** [comment]
Please explain what the problem is first.
Not just what doesn't work, but why it doesn't work; and subsequently.

**Comment by robertonline** [comment]
The description of the problem has been updated. Please let me know if you need more details.
