### ISSUE TITLE
CI3 php cli mode - access session data

### ISSUE THREAD

**Issue by Mariick** [bcit-ci/CodeIgniter#4584]
Hi everyone,

I need to access codeigniter session data in a php cli daemon which use codeigniter (Websocket server), i can get the session ID (ci_session) from websocket library, however apparently codeigniter deny access to session in cli mode : 
libraries/Session/Session.php : 
```
if(is_cli()){
    ....
    return;
}
```
There is any official 'workaround' or i need to do some ugly hacks ?

**Comment by jim-parry** [comment]
Support questions should be raised on forum.codeigniter.com ... we use github issues for bug tracking.
