### ISSUE TITLE
I can't use session with PDO mysql database in Codeigniter 3

### ISSUE THREAD

**Issue by manee1982** [bcit-ci/CodeIgniter#4587]
it give me this error:

A Database Error Occurred
Error Number: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `id` = '6b618ef793bc26b7f3de713e86b54c19508a44af'' at line 2
SELECT `data` WHERE `id` = '6b618ef793bc26b7f3de713e86b54c19508a44af'
Filename: libraries/Session/drivers/Session_database_driver.php
Line Number: 166

**PDO configuration in database config file:**
$db['default'] = array(
	'dsn'	=> 'mysql:host=localhost;dbname=MyDatabase',
	'hostname' => 'localhost',
	'username' => 'root',
	'password' => 'myPassW0rd',
	'database' => '',
	'dbdriver' => 'pdo',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

**Server version: 5.5.47-0ubuntu0.14.04.1 - (Ubuntu)**

**Comment by manee1982** [comment]
**Sorry i was rush,** this mistake was in the session-config in config.php file. so i have to add
**_**$config['sess_use_database']	= FALSE;
$config['sess_table_name'] = 'ci_sessions';**_**
to the $config

**Comment by narfbg** [comment]
Yes, you did rush it.

But no, you should NOT add any lines to the config files that don't exist yet. If you actually read the documentation, you'd know that.
