### ISSUE TITLE
form validation errors not shown when ajax & get method

### ISSUE THREAD

**Issue by tiny-rejoan** [bcit-ci/CodeIgniter#4590]
http://stackoverflow.com/questions/36733896/codeigniter-ajax-form-validation-in-modal-not-working

**Comment by skunkius** [comment]
Can't comment on stackoverflow, so I write here - first thing first, check your request with die(var_dump($_GET)). Second, try change to POST.

**Comment by tiny-rejoan** [comment]
POST work, as I hints already in title and receiving data using $this->input->get(). So these should not be issue, Problem is in validation_errors() even tried form_error('truck_plateno')

**Comment by skunkius** [comment]
Just suggestion - replicate everything without AJAX, add all errors to flashdata, even var_dump($this->session->flashdata()) and check if it's working.

**Comment by narfbg** [comment]
This is a bug tracker, not a place to post your SO questions.
