### ISSUE TITLE
apcu

### ISSUE THREAD

**Issue by twn39** [bcit-ci/CodeIgniter#4592]

**Comment by twn39** [comment]
why close this issue? @narfbg

**Comment by narfbg** [comment]
You *just now* updated the title and description, which originally (at the time I closed it, seconds after it was open) were only "apcu" as the title and absolutely no description text. I don't appreciate you pretending like that's not the case.

And I would've closed it anyway, as it is of very low quality and is neither a bug report nor a meaningful feature request. We use GitHub issues for *bug tracking* and not as a general Q&A service. If you've got questions, ask them on our [forums](http://forum.codeigniter.com/) instead.
