### ISSUE TITLE
Pass by reference not allowed to error

### ISSUE THREAD

**Issue by ukuser34** [bcit-ci/CodeIgniter#4594]
Slightly wierd quirk of the system but I had (incorrectly) set my variable with a reference in one of my controllers as such:

`$this->table1_downloads(&$start,$excel,$kitID,$dates);`

I fully appreciate that this is wrong because pass by reference to a function is now deprecated however for some reason CI completely crashed. No error reporting/logging (on level 4) and browser just redirected. No PHP/error/output.

Not a major issue but took quite a while of debugging to find it because I wasn't being told what was wrong.

**Comment by narfbg** [comment]
This is not even related to CI.
