### ISSUE TITLE
form_dropdown does not select selected - form helper 

### ISSUE THREAD

**Issue by TresErres** [bcit-ci/CodeIgniter#4596]
Hi there,

I've an issue with this code:
```php
form_dropdown(
    'language', 
    ['español' => 'Español', 'english' => 'English'], 
    'español, 
    'class="form-control" id="language"'
);
```
It supposed to get `español` selected but it does not do it.

I dig into `form_helper` down to line `408`, if I do the following code it works, but not with the system helper.

```php
form_dropdown(
    'languaje',
    [
        'español' => 'Español', 
        'english' => 'English'
    ],
    ['español']
);

function form_dropdown($data = '', $options = array(), $selected = array(), $extra = '')
{
    foreach ($options as $key => $val) {
        var_dump(in_array($key, $selected));
        die();
    }
}
```
Any clues? 

Thank you!

**Comment by narfbg** [comment]
Please ask your questions on our [forums](http://forum.codeigniter.com/) instead, this is a bug tracker.

**Comment by TresErres** [comment]
Hi there, I'm not requesting for help, sorry if it appears to be. It's an issue.

**Comment by jim-parry** [comment]
@TresErres This is not a CI bug. Your third parameter is specified incorrectly, missing the closing single quote ->     **'español,**

**Comment by TresErres** [comment]
Updated the typo coping the example.

**Comment by TresErres** [comment]
And do what ever with the issue; I won't come any more.
