### ISSUE TITLE
Why do I get the ip incorrect use ci

### ISSUE THREAD

**Issue by qiang5062250** [bcit-ci/CodeIgniter#4599]
Why do I use $ this-> input-> address () Get ip is :: 1, but I also get to use $ _SERVER ip but not without frame and normal. What is the situation

**Comment by qiang5062250** [comment]
is ok

**Comment by narfbg** [comment]
Please note that this is a bug tracker; if you want to ask a question, do it on our [forums](http://forum.codeigniter.com/) instead.
