### ISSUE TITLE
Delete from multiple tables issue

### ISSUE THREAD

**Issue by hiyao** [bcit-ci/CodeIgniter#4600]
When delete from multiple tables is done, I found $qb_where is not reset.
I'm not sure this is a issue. 

test code is 
```
$tables = array('table_a', 'table_b');
$this->db->where('id', 1);
$this->db->delete($tables);
```

in DB_query_builder.php line 2142:
```
elseif (is_array($table))
{
	empty($where) && $reset_data = FALSE;

	foreach ($table as $single_table)
	{
		$this->delete($single_table, $where, $limit, $reset_data);
	}

	return;
}
```

I try overwrite this code to check if $tables is not last element, then set FALSE with $this->delete() variable $reset_data.
```
elseif (is_array($table))
{
	//empty($where) && $reset_data = FALSE;

	foreach (array_values($table) as $table_key => $single_table)
	{
		$this->delete($single_table, $where, $limit, (($table_key == (count($table)-1))? $reset_data: FALSE));
	}

	return;
}
```

**Comment by narfbg** [comment]
That's because you're not supposed to use it like that.

If you want to pass multiple tables to `delete()`, you must also pass the where conditions using the second parameter.

**Comment by hiyao** [comment]
Document tell us can do that. Maybe need to modify delete example with multiple tables.

http://www.codeigniter.com/user_guide/database/query_builder.html#deleting-data

**Comment by narfbg** [comment]
And the document is not incorrect - the example works perfectly fine.
Also relevant: #4047

It is just your expectations that are contradicting - you cannot reasonably expect that a previous `where()` call would be magically preserved for multiple tables, but then reset afterwards.
`qb_where` is either reset or not.

**Comment by hiyao** [comment]
ok, I understand that code isn't a good solution.

My point is that when I finish delete with multiple tables, then execute other query, the second query has return a wrong result.

example1 - the second query return current query:
```
$tables = array('table_a', 'table_b');
$this->db->delete($tables, array('id' =>  1));

$this->db->get_compiled_select('table_a');
```

result:
```
SELECT * FROM `table_a`
```

example2 - the second query return wrong query:
```
$tables = array('table_a', 'table_b');
$this->db->where('id', 1);
$this->db->delete($tables);

$this->db->get_compiled_select('table_a');
```

result:
```
SELECT * FROM `table_a` WHERE `id` = 1
```

**Comment by narfbg** [comment]
Yes, I know ... and that's why you shouldn't use it that way.

**Comment by hiyao** [comment]
Thank you for your reply. :)
