### ISSUE TITLE
Out of memory in subviews

### ISSUE THREAD

**Issue by PhoenixFnX** [bcit-ci/CodeIgniter#4608]
Hello, 

I'm using subviews and I get an out of memory when I have big view data objects.
The problem is that even I dont need objects in the subview, the object get loaded into memory a second time at the subview call.

In the view:
```
$data = array();
$data["categoriesAndFields"] = $categoriesAndFields;
$data["properties"] = $properties;
get_instance()->load->view($view, $data);
```

The in the Loader.php class, there is the following:
```
if (is_array($_ci_vars))
{
	$this->_ci_cached_vars = array_merge($this->_ci_cached_vars, $_ci_vars);
}
extract($this->_ci_cached_vars);
```

The problem is my `$this->_ci_cached_vars` contains a big array with 55000 values. This was loaded a first time through  `$_ci_vars` var and this extract function, it passed. 

But for the subview, it is now in `$this->_ci_cached_vars` and extracts throws outofmemory.

Do I miss something or there is here a way to improve memory management ? 

PS : Do I need to call `get_instance()->load->clear_vars();` before each subview call if I donc need parent variables ?

**Comment by jim-parry** [comment]
Please raise support questions on forum.codeigniter.com
We use github issues for bug tracking.

**Comment by PhoenixFnX** [comment]
I was seeing this as a memory management bug or evolution...
