### ISSUE TITLE
$this->agent->browser() in Microsoft Edge returns "Chrome".

### ISSUE THREAD

**Issue by fillsanches** [bcit-ci/CodeIgniter#4609]
Hello,
Using CI 3.0.6
$this->agent->browser() in Microsoft Edge version 25.10586.0.0 returns "Chrome".

**Comment by ScottHelme** [comment]
This change should have fixed that: https://github.com/bcit-ci/CodeIgniter/commit/a5e58eb5b246fcf9dd323527c57d02f4219479c8

Edge is now detected as 'Spartan'.

**Comment by fillsanches** [comment]
Thanks @ScottHelme
