### ISSUE TITLE
Ellislab URL Still redirecting to old version Doc

### ISSUE THREAD

**Issue by isantolin** [bcit-ci/CodeIgniter#4611]
Hi:
Any from Ellislab can do a redirect from old doc
- https://ellislab.com/codeigniter/user-guide/

to new doc?
- http://www.codeigniter.com/user_guide/

**Comment by jim-parry** [comment]
This has already been raised and anserwered on our forum...
http://forum.codeigniter.com/thread-64139.html?highlight=google
