### ISSUE TITLE
SMTP 503 Already authenticated implementation

### ISSUE THREAD

**Issue by fattalgazi** [bcit-ci/CodeIgniter#4613]
Hello,

I am sending email queues in a loop and I have config/email.php file that includes smtp configurations.

I have 

```
$config['smtp_keepalive'] = TRUE;
````

in my config file.

In php loop, first email goes successfully, but in second loop it gives me this error : 

```
Failed to send AUTH LOGIN command. Error: 403 4.5.1 Error: already authenticated
Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.
```

So my smtp server responds me 403 error, I investigated email library in system folder, it tries to reauth everytime in loop, and that line indicates that if server returned 503 error, no error, continue to send.

https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Email.php#L2126

But my server responds 403 instead of 503. 

So I replaced, 

```
if (strpos($reply, '503') === 0)	// Already authenticated
```

with

```
if (strpos($reply, '503') === 0 OR strpos($reply, '403') === 0)	// Already authenticated
```

Now, loop works fine. Every mail goes successfully, but i am confused, am i doing right or it is something wrong with my smtp servers ?

**Comment by narfbg** [comment]
403 usually indicates other, "real" authentication errors and thus, it's not a good idea to check for it in that fashion.

Please test with the commit referenced above.

**Comment by narfbg** [comment]
@fattalgazi PING

**Comment by fattalgazi** [comment]
Sorry for delay, I have no environment to test this right now, I will reopen the issue in the future if something wrong happened. Thanks.

**Comment by narfbg** [comment]
That's ... not very nice, 3.0.7 will ship this patch for everybody.
