### ISSUE TITLE
Nothing returned when using query builder

### ISSUE THREAD

**Issue by KenAlin** [bcit-ci/CodeIgniter#4614]
Hi there,
I'm pretty new to Code Igniter, but something does bother me ... it seems that some query built using query builder doesn't work.

I have a table (named *table1* here), and I need to select data from it, considering *name* column.

```php
// Returns nothing
$query = $this->db->get_where('table1', array('name' => strtoupper($this->db->escape($name))));

// Nothing here too
$sql = "SELECT * FROM table1 WHERE name = ?;"; 
$query = $this->db->query($sql, array(strtoupper($this->db->escape($name)))); 

// Return values
$sql_name = strtoupper($this->db->escape($name));
$sql = "SELECT * FROM table1 WHERE name = {$sql_name};";
$query = $this->db->query($sql);

// Values are used here
$data['json'] = json_encode($query->result_array(), JSON_UNESCAPED_UNICODE);
```

I'm using a Postgresql database.

I think I'm using code provided by the [documentation](http://www.codeigniter.com/user_guide/database/query_builder.html) in a correct way, but maybe I'm somewhere wrong.

**Comment by stefkes** [comment]
Try putting this line after you run the queries to see the full query that was generated.

`echo $this->db->last_query();`

Compare the queries that return nothing to do the ones that do return something. Do you see any obvious errors?

**Comment by narfbg** [comment]
Please post this on our [forums](http://forum.codeigniter.com/) instead, this is a bug tracker - general help requests are not welcome here.
