### ISSUE TITLE
Codeigniter app on openshift not working

### ISSUE THREAD

**Issue by Rehmanjeff** [bcit-ci/CodeIgniter#4618]
I have a fine running app on localhost using WAMP server but my app is not running correctly on live server, 404 page appears with "The page you requested was not found." ( http://testcode-researcherloby.rhcloud.com/ ) 
i can't seem to get what goes wrong in controller or anything else.

This is the path setting in my config.php file

`$config['base_url'] = "http://" . $_SERVER['HTTP_HOST'];`

This is my route.php settings:

`$route['default_controller'] = 'user_authentication';`

And as i have read other threads people were missing constructor call in their class but i have all fine there as it's still working on localhost. Any help would be appreciated

**Comment by narfbg** [comment]
Please post this on our [forums](http://forum.codeigniter.com/) instead, this is a bug tracker - general help requests are not welcome here.
