### ISSUE TITLE
Travis-ci breaks for PHP 5.3

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/CodeIgniter#4621]
I am not familiar enough with travis-ci and its configuration to feel comfortable dealing with this.

The PHP 5.3.3 database unit tests fail with
_ The openssl extension is required for SSL/TLS protection but is not availab  
  le. If you can not enable the openssl extension, you can disable this error  
  , at your own risk, by setting the 'disable-tls' option to true.        
_

This may be a moot point once we get to 3.1.0, but it is worth fixing in the meantime.

We are not the only ones experiencing the problem. I found some other reports, which might shed light on the solution...

- https://github.com/composer/composer/issues/2026
- https://github.com/travis-ci/travis-ci/issues/1268
- https://www.phpbb.com/community/viewtopic.php?f=461&t=2354201

**Comment by narfbg** [comment]
I already fixed this [yesterday](https://github.com/bcit-ci/CodeIgniter/commit/fd8349f0328cb6c0cd56fd19c931fd79a707faa8).
