### ISSUE TITLE
Error	 : Only variables can be passed by reference

### ISSUE THREAD

**Issue by abosmond** [bcit-ci/CodeIgniter#4630]
I'm trying to import CodeIgniter project in MS Visual Studio 2010 & Phalanger. When I'm run the project I got error : Only variables can be passed by reference in most of file.

example on oci8_driver.php : 
protected function _list_columns($table = '')
	{
		if (strpos($table, '.') !== FALSE)
		{
			**sscanf**($table, **"%[^.].%s"**, $owner, $table);
		}

I investigate a lot in sscanf function, but I can't figure out how to repair it. Can you help me?

**Comment by narfbg** [comment]
Sorry, we don't support Phalanger.

Also, this is our bug tracker - not a place to seek general help - please only post about confirmed bugs.

**Comment by abosmond** [comment]
Nevermind. Sorry, I just confuse with my problem.
