### ISSUE TITLE
question routing

### ISSUE THREAD

**Issue by unitxt** [bcit-ci/CodeIgniter#4636]
hi, i have a question,

why this works?

website.com/1000/photo/1

but this not:

website.com/user/photo/1

the first one use numbers and the second letters , in the second dont parse the var, i have :

$route['(:any)'] = 'profile/view/$1';
$route['(:any)/photo/(:num)'] = 'profile/photo/$1';

**Comment by hebrew878** [comment]
i think changing the order will work?

$route['(:any)/photo/(:num)'] = 'profile/photo/$1';
$route['(:any)'] = 'profile/view/$1';

**Comment by unitxt** [comment]
hi  @hebrew878  thanks, i try it but dont works

**Comment by narfbg** [comment]
This is a bug tracker; please ask your questions on our [forums](http://forum.codeigniter.com/) instead.
