### ISSUE TITLE
form_validation rules issue

### ISSUE THREAD

**Issue by janul** [bcit-ci/CodeIgniter#4639]
Hi,
tested with rev e13fa9f from stable branch.

1.  First issue
     sample:
   ` $this->form_validation->set_rules('somename', 'blabla, 'alpha');
`
even if input is empty and doesn exist and I haven't set 'required' the 'alpha' rule is triggered

2. Second issue:
`$this->form_validation->set_rules('somename', 'blabla, 'trim|alpha');`
When 'trim' is added then even if I don't have such input ('somename') in the form it's created with empty value and 'alpha' rule is triggered.

these issue started after recent lib update

**Comment by janul** [comment]
fyi the rev which works is 4ac24c2
Thanks

**Comment by janul** [comment]
Could you please confirm if the issue I  raised is a CI bug or the change was intentional 
Thanks

**Comment by narfbg** [comment]
0fae625de48885b565362fe5d62cd6ce4fd76faa was the commit that broke this (please don't call it "rev" or "revision", this isn't SVN :))

#4633 is therefore relevant ... though not obvious due to its confusing description.
