### ISSUE TITLE
can't get file ext from clipbroad paste img

### ISSUE THREAD

**Issue by lqmcn** [bcit-ci/CodeIgniter#4642]
sometime,paste img from clipbroad to upload img.but, it's no ext from clipborad.then,alert a tip "The filetype you are attempting to upload is not allowed."

I have to rewrite this function 
![ext](https://cloud.githubusercontent.com/assets/18345995/15467171/b1411b34-210f-11e6-8c62-71c91d60b6a5.jpg)

**Comment by platedodev** [comment]
Did you rewrite it? push your code. If you not I can make a fix.

**Comment by platedodev** [comment]
Did you rewrite it?, push your code If so, If you didn't then I'll fix it.

**Comment by lqmcn** [comment]
@platedodev okay,I'll push my code to CodeIgnitor today

**Comment by lqmcn** [comment]
i find get_extension rewrited by @Andrey Andreev。
i change it a little,code pull request ,but built failure

**Comment by narfbg** [comment]
No ... we're not defaulting to '.png' just to accomodate for one specific use case. The error you're getting may not even be caused by this.

Please open a thread on our [forums](http://forum.codeigniter.com/) instead.

P.S.: Screenshots of code are horrible, don't do that again.
