### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by kountouretis** [bcit-ci/CodeIgniter#4644]
Fatal error: Call to undefined function id_clean() in C:\xampp\htdocs\fitness\modules\trainers\models\mtrainers.php on line 14

I receive this erro when i am login as administrator and try to edit a trainer, also i receive the same error when i try to delete the trainer

**Comment by jim-parry** [comment]
This is not a CodeIgniter problem.
Ask support questions on our forum - we use github for bug tracking.
