### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by kountouretis** [bcit-ci/CodeIgniter#4645]
When i try to delete trainer i receive this error 

A Database Error Occurred
Error Number: 1146
Table 'fitness.omc_order' doesn't exist

SELECT * FROM (`omc_order`) WHERE `trainer_id` = 10

**Comment by narfbg** [comment]
For the [second time in 24 hours](https://github.com/bcit-ci/CodeIgniter/issues/4644) - this is not a CodeIgniter issue.

This is a bug tracker, NOT a place to search for help with random problems. Please respect that.
