### ISSUE TITLE
count_all_results produces incorrect results

### ISSUE THREAD

**Issue by blasto333** [bcit-ci/CodeIgniter#4647]
count_all_results is returning the wrong value in many cases in CI 3.0.6

QUERY BUILDER:

		$this->db->select('items.item_id, items.name, categories.id as category_id,categories.name as category,location, company_name, item_number,size, product_id, 
		IFNULL('.$this->db->dbprefix('location_items').'.cost_price, '.$this->db->dbprefix('items').'.cost_price) as cost_price, 
		IFNULL('.$this->db->dbprefix('location_items').'.unit_price, '.$this->db->dbprefix('items').'.unit_price) as unit_price,
		SUM(quantity) as quantity, 
		IFNULL('.$this->db->dbprefix('location_items').'.reorder_level, '.$this->db->dbprefix('items').'.reorder_level) as reorder_level, 
		description', FALSE);
		$this->db->from('items');
		$this->db->join('suppliers', 'items.supplier_id = suppliers.person_id', 'left outer');
		$this->db->join('categories', 'items.category_id = categories.id', 'left outer');
		$this->db->join('location_items', 'location_items.item_id = items.item_id and location_id IN('.$location_ids_string.')', 'left');
		$this->db->where('items.deleted', 0);
		$this->db->group_by('items.item_id');
		
		if ($this->params['supplier'] != -1)
		{
			$this->db->where('suppliers.person_id', $this->params['supplier']);
		}
		
		if ($this->params['category_id'] != -1)
		{
			$this->db->where_in('categories.id', $category_ids);
		}
		
		if ($this->params['inventory'] == 'in_stock')
		{
			$this->db->where('quantity > 0');
		}
		
		if ($this->params['inventory'] == 'out_of_stock')
		{
			$this->db->where('quantity <= 0');
		}
		
		$this->db->where('is_service !=', 1);
		$this->db->order_by('items.name');
		
		$ret = $this->db->count_all_results();
		
		echo $this->db->last_query();

3.0.4 (Returns 38) (Correct)

SELECT COUNT(*) AS `numrows` FROM ( SELECT phppos_items.item_id, phppos_items.name, phppos_categories.id as category_id, phppos_categories.name as category, location, company_name, item_number, size, product_id, IFNULL(phppos_location_items.cost_price, phppos_items.cost_price) as cost_price, IFNULL(phppos_location_items.unit_price, phppos_items.unit_price) as unit_price, SUM(quantity) as quantity, IFNULL(phppos_location_items.reorder_level, phppos_items.reorder_level) as reorder_level, description FROM `phppos_items` LEFT OUTER JOIN `phppos_suppliers` ON `phppos_items`.`supplier_id` = `phppos_suppliers`.`person_id` LEFT OUTER JOIN `phppos_categories` ON `phppos_items`.`category_id` = `phppos_categories`.`id` LEFT JOIN `phppos_location_items` ON `phppos_location_items`.`item_id` = `phppos_items`.`item_id` and `location_id` IN(1) WHERE `phppos_items`.`deleted` =0 AND `is_service` != 1 GROUP BY `phppos_items`.`item_id` ORDER BY `phppos_items`.`name` ) CI_count_all_results

3.0.6 (Returns 1) (Incorrect)
`SELECT COUNT(*) AS `numrows` FROM `phppos_items` LEFT OUTER JOIN `phppos_suppliers` ON `phppos_items`.`supplier_id` = `phppos_suppliers`.`person_id` LEFT OUTER JOIN `phppos_categories` ON `phppos_items`.`category_id` = `phppos_categories`.`id` LEFT JOIN `phppos_location_items` ON `phppos_location_items`.`item_id` = `phppos_items`.`item_id` and `location_id` IN(1) WHERE `phppos_items`.`deleted` =0 AND `is_service` != 1 GROUP BY `phppos_items`.`item_id``

**Comment by narfbg** [comment]
Patch is referenced above.

But ... aside from the fact (evident by your other submissions) that you're always pushing the Query Builder to its limits while it is made for way simpler queries, I should ask you to put more effort into identifying problems before reporting them.

It is of course better for me to have as much information as possible, but it's also counter-productive when most of it is irrelevant and half of the work is noise-cancelling. Filtering that out would've shown you that 3.0.4 is also affected by this bug (because it is caused by GROUP BY), but another one (ORDER BY related) is simply masking it in your huge query.
