### ISSUE TITLE
xss_clean system function probley not work

### ISSUE THREAD

**Issue by sayanthanpera** [bcit-ci/CodeIgniter#4649]
i used to remove XSS vulnerability like
`$_GET=$this->security->xss_clean($_GET);` 

case1 : my get url
`?PeopleName="><script>alert()%3B<%2Fscript>&PeopleSurname=&PeopleUserName=&PeopleEmail=`
but not remove script tag

but case2 : my get url
`PeopleName=&PeopleSurname="><script>alert()%3B<%2Fscript>&PeopleUserName=&PeopleEmail=`
script tag removed..

i find problems in system function (file:-system/core/security.php function:-xss_clean)
`if (is_array($str))
{
        while (list($key) = each($str))
	{
		$str[$key] = $this->xss_clean($str[$key]);
	}
	return $str;
}`

i modified system function like 

`if (is_array($str))
{
foreach($str as $key=>$value)
{
	$str[$key] = $this->xss_clean($str[$key]);
			}
			return $str;
		}`

problems array of first element not come into the wile loop.. i fixed that using foreach then proppely work xss_clean

**Comment by narfbg** [comment]
Can't reproduce.
