### ISSUE TITLE
Cannot pass variables from Controller to Model

### ISSUE THREAD

**Issue by terrylinooo** [bcit-ci/CodeIgniter#4655]
I posted an topic on official forum, because I cannot post screenshot here.

http://forum.codeigniter.com/thread-65319.html

CodeIgniter 2 works good but CodeIgniter 3 doesn't.

**Comment by jim-parry** [comment]
Use the forum for support. We use github for bug tracking.

**Comment by terrylinooo** [comment]
I believe it is a bug, but you decide to close this thread, good luck CodeIgniter

**Comment by jim-parry** [comment]
This is not a bug - see the two replies to your forum thread (at the time this was written).
Good luck @terrylinooo
