### ISSUE TITLE
Could not identify the Post request

### ISSUE THREAD

**Issue by JKair** [bcit-ci/CodeIgniter#4656]
I use `postman` to post data.
but `$this->input->post()` is empty,it work in laravel.
I check the `$GLOBALS`
```
["_GET"]=>
  array(1) {
    ["sdfsad"]=>
    string(8) "asdfsadf"
  }
["_POST"]=>
  array(0) {
  }
.......
["REQUEST_METHOD"]=>
      string(3) "POST"
.......
```

In `core/Input.php line 256`,the code is `return $this->_fetch_from_array($_POST, $index, $xss_clean);`,maybe it can get the method from `REQUEST_METHOD`,no only `$_POST` or `$_GET`

What should I do to solve this problem.
thanks.

**Comment by sasbass** [comment]
If your XSS is 'true' then i see this problem.
I make this and everything is working normal.
Just turn off xss.
class MY_Input extends CI_Input {

    public function __construct() {
        $this->_POST_RAW = $_POST;
        parent::__construct(); 
    }

    public function post($index = null, $xss_clean = TRUE) {
        
        if(!$xss_clean){
            return $this->_POST_RAW[$index];
        }
        
        return parent::post($index, $xss_clean); 
    }    
}

**Comment by narfbg** [comment]
This ... doesn't even make sense. Closing.
