### ISSUE TITLE
Migrations Issue

### ISSUE THREAD

**Issue by advoor** [bcit-ci/CodeIgniter#4659]
With multiple migrations, the same file names cannot be used again. E.g. I had the following two migration files:

001_modify_orders.php
002_modify_orders.php

When downgrading : 

```
if ( ! $this->migration->version(0) )
        {
        	show_error($this->migration->error_string());
        }

```
The following error occurs: This are multiple migrations with the same version number: 0.

Changing the file name ( and then class name ) fixes this, but looking at the error, it looks like there's an unintended error.

**Comment by narfbg** [comment]
This issue doesn't exist in CI3.
2.x is no longer supported.
