### ISSUE TITLE
Can't load helper if set config['subclass_prefix']=''

### ISSUE THREAD

**Issue by aszx0413** [bcit-ci/CodeIgniter#4661]
I want to load the core controller and set the filename as application/core/Controller.php. So I leave $config['subclass_prefix'] an empty string. 
But after that the CI CAN'T load the application/helpers/xxx_helper.php anymore. Not if u coding $this->load->helper('xxx'), neither set the autoload.php file to autoload the helper

**Comment by narfbg** [comment]
So don't set the subclass prefix to an empty string, you're not supposed to do that.
