### ISSUE TITLE
Major bug find in xss_clean that lead to xss attack on website developed in codeigniter 3

### ISSUE THREAD

**Issue by meankurjain** [bcit-ci/CodeIgniter#4663]
The following state will not prevent us from xss attack

$result = $this->security->xss_clean("&lt;script&gt;alert('abc');&lt;/script&gt;");

Please reply asap as i am in middle of my project developed in codeigniter 3.

**Comment by narfbg** [comment]
Can't reproduce.

**Comment by meankurjain** [comment]
Hi,

Try following this you can reproduce: 

$result = $this->security->xss_clean("&amp;lt;script&amp;gt;alert('abc');&amp;lt;/script&amp;gt;");

**Comment by narfbg** [comment]
That's an already escaped string, there's nothing to modify in it.

**Comment by meankurjain** [comment]
But if we saved it like that and the urldecode it then it results in successful xss attack.

**Comment by narfbg** [comment]
HTML-decode, not URL-decode, but that's irrelevant.

It being encoded is the whole point, of course it's going to execute when you reverse the escaping.

**Comment by MackieeE** [comment]
What is it that you're expecting it to do? It's not going to remove the js if you're wondering, which in itself not an xxs attack.

**Comment by meankurjain** [comment]
Test%26lt%3Bscript%26gt%3Balert%28%27abc%27%29%3B%26lt%3B%2Fscript%26gt%3B
