### ISSUE TITLE
Major bug find in xss_clean that lead to xss attack on website developed in codeigniter 3

### ISSUE THREAD

**Issue by meankurjain** [bcit-ci/CodeIgniter#4664]
The following state will not prevent us from xss attack

$result = $this->security->xss_clean("&amp;lt;script&amp;gt;alert('abc');&amp;lt;/script&amp;gt;");

Please reply asap as i am in middle of my project developed in codeigniter 3.

**Comment by narfbg** [comment]
Please don't open a new issue for everything; continue in #4663.

**Comment by vkeranov** [comment]
Why you're opening so many issues about the same question?
