### ISSUE TITLE
Returning typed row object fails in function 'custom_result_object($class_name)' when using DB cache.

### ISSUE THREAD

**Issue by gvdvenis** [bcit-ci/CodeIgniter#4665]
Let start with an example: This snippet comes from my hypothetical 'Game' model. It just returns the first Game record from the 'game' table and returns an object of type Game.
```php
    /**
     * @return Game
     */
    function get_game()
    {
        $query = $this->db->get('game');
        return $query->row(0, 'Game');
    }
```
An issue arises when i turn on database caching. It boils down to the function 
`\CI_DB_result->custom_result_object`
```php
public function custom_result_object($class_name)
	{
		if (isset($this->custom_result_object[$class_name]))
		{
			return $this->custom_result_object[$class_name];
		}
		elseif ( ! $this->result_id OR $this->num_rows === 0)
		{
			return array(); //--> when using cached db result this will be returned...
		}
         ...
```
The problem is that when i load a cached result it contains no result_id, so this code will always return an empty array.

When i remove the `! $this->result_id OR ` from the above code, the function continues as expected, mapping all my rows to the Game class.

AFAIKT there is no apparent downside to removing this condition from the if clause so can i suggest to go ahead implement this fix or would there be any unforeseen downsides to this 'fix'?

**Comment by narfbg** [comment]
There are potential downsides. `custom_result_object()` is a lot more complex than the "regular" `result_object()` and `result_array()` methods and will remain uncacheable.

In fact, I'm considering deprecation of `CI_DB_Cache` anyway. It's not that widely used, pretty dumb and in most cases you're better off with the DB's own cache.
