### ISSUE TITLE
PHPUnit passing $ as a parameter to CodeIgniter causing crash when running with code coverage

### ISSUE THREAD

**Issue by danielalbertsami** [bcit-ci/CodeIgniter#4666]
We are using PHPStorm 2016, PHPUnit 4.8, and CodeIgniter 3.0.6 after performing an upgrade from CI 2. When running with Code Coverage on one of our systems, running unit tests causes a crash in the instantiation of the URI class. The unit tests pass with no issues otherwise, while running with normal Run and normal Debug. Only with coverage does this error occur. This appears to be because PHPUnit is passing a command line argument with a '$' within it, and CodeIgniter appears to read this as a URI rather than a CLI parameter. 

The bug's nature is further verified by adding '$' to the list of allowed URI characters within the config.php file, which then allows unit tests to run with coverage.

**Comment by narfbg** [comment]
So what are you suggesting?

**Comment by jtneal** [comment]
Why is CLI still holding parameters accountable to permitted_uri_chars anyway?

I thought issue #4085 was resolved and covers this situation.

**Comment by narfbg** [comment]
#4085 does resolve it, in another branch/version tree.

I don't see anything happening here for 3.0.x, so closing.
