### ISSUE TITLE
CI3+NGINX+PHP-FPM7 > No error logging in file

### ISSUE THREAD

**Issue by jsieler** [bcit-ci/CodeIgniter#4667]
Hello Community!

We noticed strange behavior on new PHP7 version. We used PHP5 a while and everything worked well, but after we merged to PHP7, Codeigniter behaves itself a bit strange.

Following:
If we add some code, that causes an exception, any symbol, removing semicolon, etc., Codeigniter throws an error in browser like it should be. But, server log file, has no error at all. We logging all access and error logs with nginx, each per domain.

The same version, and code of Codeigniter on PHP5 version behaves as it should be. Throws an error and writing the same error into log file.

So, you would say, "your server is configured wrong". But, NO, because testing same with just plain PHP with single "echo" line is working well. Also screwing index.php of Codeigniter is working well too and produce exception and log file.

Could it be that CI3 is not fully PHP7 ready?!

**Comment by narfbg** [comment]
Removing a semicolon or adding a random character produces a syntax error, not an exception - what happens in that case is outside of CodeIgniter's control.

We do log exceptions, regardless of the version: https://github.com/bcit-ci/CodeIgniter/blob/3.0.6/system/core/Common.php#L642

**Comment by jsieler** [comment]
Is there any way to route CI errors to log as ordinary PHP errors?

**Comment by narfbg** [comment]
No.

**Comment by jsieler** [comment]
I see that CI is logging errors within own log file, with "log_exception" and "message_log", but why is thereno possibility to use server log file with http://php.net/manual/ru/function.error-log.php
