### ISSUE TITLE
Cannot upload pdf file with numeric filename like 2016

### ISSUE THREAD

**Issue by filjoseph1989** [bcit-ci/CodeIgniter#4669]
Hi, I have a code here

```
if ( ! $this->upload->do_upload('myfile')) {
  $result = array('error' => $this->upload->display_errors('<div class="alert alert-danger">','</div>'));
} else {
  # some code
}

```
When I try to upload a file, a pdf file having a filename containing mostly numbers, no letters, CodeIgniter will return this.

`$result = array('error' => $this->upload->display_errors('<div class="alert alert-danger">','</div>'));`

Is it a bug or security features?

**Comment by narfbg** [comment]
This is a bug tracker; you have to be sure that something is a bug *before* posting.
Please ask similar questions on our [forums](http://forum.codeigniter.com/) instead.
