### ISSUE TITLE
mysql 5.7 with php 7 and ssl settings for database

### ISSUE THREAD

**Issue by xargr** [bcit-ci/CodeIgniter#4670]
hi! I setup a new vps machine with php 7 mysql 5.7 and last version codeigniter. In the machine install a free ssl let's encrypt. All works fine but database dont connect with popular settings.. what could be wrong???

i trust connect with native php and pdo and works... but ci dont connect...

my config/database.php

```
$active_group = 'default';
$query_builder = TRUE;
 
$db['default'] = array(
'dsn'   => '',
'hostname' => '127.0.0.1',
'username' => 'root',
'password' => 'mysqlpass',   
'database' => 'myproject',
'dbdriver' => 'mysqli',
'dbprefix' => '',
'pconnect' => FALSE,
'db_debug' => TRUE,
 'cache_on' => FALSE,
 'cachedir' => '',
 'char_set' => 'utf8',
 'dbcollat' => 'utf8_general_ci',
 'swap_pre' => '',
 'encrypt' => FALSE,
 'compress' => FALSE,
 'stricton' => FALSE,
 'failover' => array(),
 'save_queries' => TRUE
 );

```

**Comment by Everterstraat** [comment]
Let's encrypt certificates doesn't support ip addresses, can it have to do with that?!

**Comment by xargr** [comment]
I do not think... With simple pdo connection work with ip and connect fine with same settings...

**Comment by narfbg** [comment]
This is a bug tracker, not a help ticket system.
Please post such questions on our [forums](http://forum.codeigniter.com/) instead.
