### ISSUE TITLE
"log_message" has no third parameter "$php_error"

### ISSUE THREAD

**Issue by jsieler** [bcit-ci/CodeIgniter#4671]
Looking at the documentation, it states there is third parameter:
https://www.codeigniter.com/user_guide/general/errors.html#log_message

Looking at the function itself:
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/Common.php#L468

There is no third parameter... So, what is wrong?

**Comment by narfbg** [comment]
That parameter has never been used.
