### ISSUE TITLE
sess_regenerate_destroy

### ISSUE THREAD

**Issue by bribar** [bcit-ci/CodeIgniter#4672]
I have a AJAX heavy site. User session data gets deleted or destroyed. This seems like the most recent information I found, http://stackoverflow.com/questions/29770389/session-id-regeneration-not-working-for-concurrent-requests (Narf's comments in particular). It doesn't seem to work for me using CI 3.0.4, logout's occur frequently.

Config

`$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 0;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;`

I have tried other methods suggested, such as creating own library to override sess_update(), but that doesn't seems to do the trick. Am I missing something? Any solid work arounds for 3.0 version of codeigniter?

**Comment by narfbg** [comment]
Please note that this is a bug tracker, we don't provide general help here.

Post your questions on our [forums](http://forum.codeigniter.com/) instead.
