### ISSUE TITLE
PDO_DBLIB alway show warning

### ISSUE THREAD

**Issue by desmothenes** [bcit-ci/CodeIgniter#4674]
when pdo_dblib connect this warning alway show

```
Severity: Warning --> PDO::__construct(): SQLSTATE[IM001]: Driver does not support this function: driver does not support setting attributes /xxx/system/database/drivers/pdo/pdo_driver.php 133
```

**Comment by narfbg** [comment]
Does it show the warning if you replace `$this->options` with `array()` on that line?

**Comment by desmothenes** [comment]
no warning show if i replace $this->options with array().

**Comment by narfbg** [comment]
Great, thanks.

The referenced commit should fix it.
