### ISSUE TITLE
delete_files happily ignores symlinks

### ISSUE THREAD

**Issue by fehnomenal** [bcit-ci/CodeIgniter#4675]
The `delete_files` function from the file helpers does not recognize whether a directory is in reality a symlink and deletes recursively all files (and directories if told so) inside it.

I'm not sure this is the intended behavior but if it is there should be at least a warning.

I stumbled about this in version 2.2.1 but also on the latest dev branch there is no sight of `is_link`.

**Comment by narfbg** [comment]
Patch is referenced above.

However, please note that the 2.x version tree is no longer supported and you shouldn't be using it. Plus, multiple security releases have been made since 2.2.1.
