### ISSUE TITLE
Feature request: Changing behavior of extract() in CI_Loader::_ci_load()

### ISSUE THREAD

**Issue by sskaje** [bcit-ci/CodeIgniter#4676]
in CI_Loader::_ci_load();

data variables are extracted to make view scripts can access directly by using:

```php
<?php
...
extract($this->_ci_cached_vars);

?>
```

In this case, array key such as 'page.title', which is not valid as a php variable, is skipped by extract().

The solution is replacing extract() with following code:
```php
<?php
...
		foreach ($this->_ci_cached_vars as $_ci_key=>$_ci_val) {
			$$_ci_key = $_ci_val;
		}

```

BTW, I've tested the performance:
Data were generated by 
```
<?php

$alphabet = range('a', 'z');

$data = [];

foreach ($alphabet as $_v1) {
	foreach ($alphabet as $_v2) {
		foreach ($alphabet as $_v3) {
			$data[$_v1 . $_v2 . $_v3] = mt_rand();
		}
	}
}

$s = var_export($data, 1);

file_put_contents(__DIR__ . '/data.php', '<' . '?php $data=' . $s . ';');
```

result

```
root@dev-21:/tmp/extract# php bench.php extract
0.0060708522796631
root@dev-21:/tmp/extract# php bench.php foreach
0.0037441253662109
```

bench scripts can be found: https://github.com/sskaje/bench_extract_foreach

**Comment by narfbg** [comment]
What's the point?

**Comment by sskaje** [comment]
@narfbg 

```
$this->load->view('tpl', ['page.header'=>'test header']);
```

This can not be accessed in tpl by:
```
<?=${'page.header'}?>
```

**Comment by narfbg** [comment]
So don't use dots. The fact that you need to access those as dynamic vars should speak for itself - it should be avoided, not encouraged.
