### ISSUE TITLE
codeigniter returns nothing for third party referral to codeigniter url.

### ISSUE THREAD

**Issue by emiglobetrotting** [bcit-ci/CodeIgniter#4677]
I am building an app that integrates facebook and twitter oauth logins integrated into Codeigniter.

I want to get landing page referral url (which is the login page: http://localhost/project/). For facebook i can get the landing page referral url with 

    $this->agent->referrer()

I expected the same behaviour when trying to login with Twitter, but Twitter opens its login url and then redirects to a callback url (which is my landing page).

Even as that I am expecting to get the twitter login url as my referral url, but

    $this->agent->referrer() //returns nothing

The twitter referral url i am expecting should be something like this

    https://api.twitter.com/oauth/authenticate?oauth_token=ymDzDQAAAAAAvcr6AAABVYwO3BE

I have been searching how to get third party referral to codeigniter url.

**Comment by jim-parry** [comment]
Support questions should be asked on forum.codeigniter.com, please.
We use githuub for bug tracking.
