### ISSUE TITLE
Documentation wrong nagivation Zip -> Next

### ISSUE THREAD

**Issue by dkhalife** [bcit-ci/CodeIgniter#4682]
If you go to http://www.codeigniter.com/user_guide/libraries/zip.html 

And hit the Next button, the expected outcome is that you land on the Database section (http://www.codeigniter.com/user_guide/database/index.html) 

Instead you are taken to the Helpers section (http://www.codeigniter.com/user_guide/helpers/index.html) and the Database section is completely skipped

**Comment by narfbg** [comment]
I can see why you could think that, and I do agree that "Next" there pointing to the Database Reference would be better.

**But**, it's not wrong - there's no defined "expected outcome", nor skipped - the XML Helper points to it.
