### ISSUE TITLE
function _escape_identifiers in OCI8 Driver maybe not true

### ISSUE THREAD

**Issue by virutmath** [bcit-ci/CodeIgniter#4686]
I've try edit code in line 1363 of DB_driver.php
```
if ($protect_identifiers === TRUE)
			{
				echo $item.$alias;
				$item = $this->_escape_identifiers($item);
				echo $item.$alias;
			}
```

And result show on screen maybe not expected

```
MYSCHEMA.TABLE.*
"MYSCHEMA".TABLE".*
```

Because this, my query is false : `Message: oci_parse(): ORA-01740: missing double quote in identifier`

I think maybe something in `_escape_identifiers` function wrong and need fix

**Comment by narfbg** [comment]
You're talking about CI2, which is no longer supported.
