### ISSUE TITLE
Add "switching" language infrastructure to the language library / helper 

### ISSUE THREAD

**Issue by dkhalife** [bcit-ci/CodeIgniter#4694]
Most of the time, the use of the language library in order to localize a website is tied to a mechanism for switching the current language displayed.

It would be of a great advantage to include this mechanism as part of CI.

I suggest a couple of additions as part of this change:
- Language helper: A function that could generate the needed HTML to switch language, with options allowing to either use custom images, only text or a combination of both.
- Language library: Upon initialisation look for some `?lang=en` parameter or something, validate that the target language exists, save it to the session (whether that's just via cookie, or user session..) and if all goes well, apply the language before autoloading the language files.

The library could maintain the option of manually loading a language file for a particular language to leave some flexibility to the developer.

**Comment by narfbg** [comment]
This has been discussed before, I believe in the forums.

Bottom line is that there are too many ways to implement language switching, all of which perfectly valid, and it's a bad idea for CI to favor one over the others.
