### ISSUE TITLE
\system\core\Security.php 中这段代码 "$str = preg_replace_callback('/<\w+.*/si', array($this, '_decode_entity'), $str);"  会引起死循环

### ISSUE THREAD

**Issue by xuj** [bcit-ci/CodeIgniter#4698]
我用get 方式传递content参数content=<script>alert('xxx')</script>, 后端使用$this->input->get(NULL, TRUE); 预处理所有参数，但遇到content中有javascript代码时，总是死循环 直到，http 504。后追踪发现
是这段代码引起的$str = preg_replace_callback('/<\w+.*/si', array($this, '_decode_entity'), $str);，，望核实，处理 thanks

**Comment by jim-parry** [comment]
Use English please. Not a clue what you are talking about.

**Comment by xuj** [comment]
me too .just when I'm not saying

**Comment by tianhe1986** [comment]
一楼的仁兄，我试了试用同样的方式传递参数，没有能够重现你的问题。或许你得提供更多的信息，比如php版本,CI 版本，使用的字符集等。

PS：有问题先去论坛(http://forum.codeigniter.com/forum-19.html)问下，不要直接就在 github上开issue吧^_^

I can not reproduce the problem in the same way you passing parameters. Could you provide some detailed info such as php version, CI version or charset ?
