### ISSUE TITLE
Add intellisense support for CI in VSCode

### ISSUE THREAD

**Issue by dkhalife** [bcit-ci/CodeIgniter#4700]
I recently started using VSCode and I find it suites me wonderfully for web projects.

However, IntelliSense doesn't work out of the box for CI so it. Upon reading the [docs](https://code.visualstudio.com/docs/extensions/overview) it seems that one can extend VSCode in order to accomplish richer support for libraries.

I would like to personally contribute to bringing this to life but since i haven't done anything like this before, I'd like a little bit of guidance, perhaps it's even easier than I think it is. 

Has anyone previously built extensions for VSCode or worked with IntelliSense or any kind of code completion ?

**Comment by mwhitneysdsu** [comment]
I haven't tried it myself, but I do see that someone has at least started working on an [extension to provide code completion for PHP](https://marketplace.visualstudio.com/items?itemName=HvyIndustries.crane).

Personally, I've found that 90% of the struggle with getting code completion working in a given editor is getting it to understand which language I'm using and where the framework resides. Of course, once I get through that, I find that a lot of the rest of it is that I'm not patient enough to actually use it.

**Comment by narfbg** [comment]
Please note that we're using GitHub Issues as a *bug tracker*.
You should post such things on our [forums](http://forum.codeigniter.com/) instead.
