### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by chosa91** [bcit-ci/CodeIgniter#4704]
In the documentation is "where_or" but in the library is it "or_where".

**Comment by jim-parry** [comment]
Which version of the user guide? which page?

**Comment by chosa91** [comment]
https://github.com/bcit-ci/CodeIgniter/wiki/Using-MongoDB-in-Codeigniter

**Comment by jim-parry** [comment]
That is something on the wiki, totally out of our control, and not a bug of any sort with the framework.
If that article has a maintainer, you might contact them directly.
Being a wiki, you (or anyone) can change the page directly.

Note: the method names shown there are those that the MongoDB library developer might have used - there is no requirement that they follow our naming!
