### ISSUE TITLE
Session library not loading correctly from hook

### ISSUE THREAD

**Issue by adrianovaroli** [bcit-ci/CodeIgniter#4707]
I'm running into (I think) a similar problem to https://github.com/bcit-ci/CodeIgniter/issues/2202:
I have a hook, configured as
```
$hook['post_controller_constructor'] = array(
        'class'    => 'Auth',
        'function' => 'check_session',
        'filename' => 'Auth.php',
        'filepath' => 'controllers/cpan',
        'params'   => array(),
);
```
This is the hook's method code:
```
public function check_session() {
        $env = $this->uri->segment(1);
        if ($env == 'frontend') { // we exclude frontend controllers
            return;
        }
        $class = $this->router->class;
        $method = $this->router->method;
        if ($class == 'auth') {
            if (in_array($method, array('do_login', 'do_logout', 'view_change_password', 'save_change_pass_html'))) {
                return;
            }
        }

        $sess_id = $this->session->userdata('id');
        $sess_perfil = $this->session->userdata('perfil');
        $sess_needs_reset = $this->session->userdata('needs_reset');

        if (empty($sess_id)) {
            $all = $this->session->all_userdata();
            $this->view_login('Ud no tiene permiso para ver este módulo');
            $this->output->_display();
            exit();
        }

        if ($sess_needs_reset == true && ! in_array($method, array('view_login', 'do_login', 'view_change_password', 'save_change_pass_html'))) {
            $base_path = reduce_double_slashes($this->config->base_url() . index_page());
            $this->session->set_flashdata('msg', 'Debe cambiar su clave antes de poder ingresar.');
            redirect($base_path . '/cpan/auth/view_change_password');
        }
    }
```
That method tries to read data from the session, but I keep running into the error 

> Unable to locate the specified class: Session.php

I've tried 

- changing the hook type from `pre_controller` to `post_controller_constructor` and `post_controller`, 
- using a direct `$CI` reference in the method, 
- loading the library directly in the method and not with autoload

but I always get the same error. Could it be that the `load_class` method in `Common.php` is not checking inside the Session subdirectory?

**Comment by mwhitneysdsu** [comment]
This error usually comes up when you load a class which extends `CI_Controller` which is not the controller handling the current route (in other words, you called a controller from a controller, or possibly used a controller to handle a hook).

However, if that is not the case, maybe some of this will help, but this should probably be posted in the [forum](http://forum.codeigniter.com) instead.

As indicated in the [manual entry for Hooks](http://www.codeigniter.com/user_guide/general/hooks.html#hook-points), most of the code in that method wouldn't work in a `pre_controller` hook. A `post_controller_constructor` hook might work, if you load the session in your controller's constructor.

In any case, you should include something like the following if there are routes in your application which don't use sessions:

```php
if ( ! class_exists('CI_Session', FALSE)) 
{
    // do something different when the session library hasn't been loaded
}
```

**Comment by adrianovaroli** [comment]
"Using a controller to handle a hook" was the problem. I solved this by moving the method to a separate class in hooks/.
Thanks.
