### ISSUE TITLE
system/Database/BaseConnection.php Change in getFieldNames() method

### ISSUE THREAD

**Issue by Portaflex** [bcit-ci/CodeIgniter#4708]
getFieldNames() method sistematically looses $this->connID unless calling $this->initialize() again.

After this:
```
public function getFieldNames($table)
	{
		// Is there a cached result?
		if (isset($this->dataCache['field_names'][$table]))
		{
			return $this->dataCache['field_names'][$table];
		}
		//... rest of the funcion ...//
```
We have to call $this->initialize() again:
```
public function getFieldNames($table)
	{
		// Is there a cached result?
		if (isset($this->dataCache['field_names'][$table]))
		{
			return $this->dataCache['field_names'][$table];
		}
		if (empty($this->connID))
		{
		    $this->initialize();
		}
               //... rest of the function ...//
```
As you know, I'm not proficient in making pullrequest. ;-)

**Comment by Portaflex** [comment]
By the way, I'm getting 0.1178 sec of execution time instead of 0.0701 sec with CI3. Exactly the same page except for a little less logic in CI4. In fact, not big deal, but we are "increasing". Thanks.

**Comment by vkeranov** [comment]
There is no file system/Database/BaseConnection.php

**Comment by jim-parry** [comment]
This issue belongs in the CodeIgniter4 repo :-/

**Comment by vkeranov** [comment]
And do we have CI4 repo?

**Comment by jim-parry** [comment]
CI4 repo: https://github.com/bcit-ci/CodeIgniter4

**Comment by Portaflex** [comment]
Oka. Issue changed to CI4 repo. Sorry.
