### ISSUE TITLE
Email smtp attachment problem

### ISSUE THREAD

**Issue by it-can** [bcit-ci/CodeIgniter#4710]
Hi,

don't know where the problem is, but when I use Mandrill with SMTP in CodeIgniter I can send emails, but the attachments are always empty (body etc is correct). When switching to phpmailer it works, so there seems to be nothing wrong with Mandrill's SMTP... Does anyone have the same problem or a solution?

**Comment by narfbg** [comment]
Please use our [forums](http://forum.codeigniter.com/) instead and only come here when you have 100% determined a bug.

**Comment by razorlegacy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  michaelm.nyc@gmail.com
    Domain michaelmohammed.com has exceeded the max emails per hour (10/10 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:55116 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server.hellhorror.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bPTxJ-0002Ow-81
	for mike@michaelmohammed.com; Tue, 19 Jul 2016 08:16:57 -0400
Date: Tue, 19 Jul 2016 05:16:17 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1468930577;
	bh=ms/NocaXxtOazv3ZQazmUmOz3B2EA+Ejmk3eVffQuRc=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ZTtXC7G9rcXOin3wCP2ViWDxJDcWSqcjjnPcv8R8TFBNfegClEwFPskZq1/FyRBSN
	 Wh0lcDA3bXlc7vK945fz354oT8iJX+0gwvnOZzV+R3T/wmwCAf/eb865SpzcAwz9IS
	 1nRgIsQON7xzSF3U8pK8yupKUc2UVcDvqahX4Gts=

**Comment by razorlegacy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  michaelm.nyc@gmail.com
    Domain michaelmohammed.com has exceeded the max emails per hour (11/10 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:18759)
	by server.hellhorror.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-0abc-mike=michaelmohammed.com@sgmail.github.com>)
	id 1bPTxM-0002Ox-OK
	for mike@michaelmohammed.com; Tue, 19 Jul 2016 08:17:00 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=JIC8Far0a0J6Gg+ywxrZOvKmyA4=; b=eeep/ArNdLCaBu1s
	jx82cTEKVUtdWMTLPy7YpplAjt6DA4e0Qad6Rk3sLy9PqovBjjgMMddsaJGEEXx4
	KSiMhF9+6D1u437O6wHcM/ep7NgbOOi2lvFj1y6DO945va4i6ckReUrlMzFmUSAk
	V9odjseB/wM1fmbaKYxR81MksQg=
Received: by filter0816p1mdw1.sendgrid.net with SMTP id filter0816p1mdw1.483.578E1A11E
        2016-07-19 12:16:17.339675926 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id PgsQVoJ5TkmdJ2rbwvMpcg
	for <mike@michaelmohammed.com>; Tue, 19 Jul 2016 12:16:17.214 +0000 (UTC)
Date: Tue, 19 Jul 2016 05:16:17 -0700
