### ISSUE TITLE
Nested mail command issue with SMTP

### ISSUE THREAD

**Issue by koichirose** [bcit-ci/CodeIgniter#4712]
I have this same issue here, but with the standard Codeigniter email library: https://github.com/PHPMailer/PHPMailer/issues/125
In short: if the email could not be sent, all subsequent tries fail (even with different email recipients, I'm inside a loop sending emails), I guess because the SMTP connection stays open.

This could probably be solved by calling 'reset'/'quit' here, before returning false: https://github.com/bcit-ci/CodeIgniter/blob/3.0.6/system/libraries/Email.php#L1955

I can't call the 'reset' command manually (`$this->email->_send_command('reset');`) because it's a protected method.

Is this a bug? If not, how can I fix it?
I don't think setting `$this->email = null;` and reloading the email library in the next loop could fix it, since the SMTP connection would still be open, but I'm trying it anyway.

**Comment by narfbg** [comment]
Can you test with 6ecbeb006cd82b58d15d5c92ad7e21ab02ede06a please?

**Comment by koichirose** [comment]
@narfbg Yes, I can confirm it works with https://github.com/bcit-ci/CodeIgniter/commit/6ecbeb006cd82b58d15d5c92ad7e21ab02ede06a .

Quickly tested with something like this:

```php
		$addresses = [
			'some_valid_username@gmai.com', //notice the misspell
			'some_valid_username@gmail.com',
		];

		$config = array(
			'useragent' => 'email',
			'protocol' => 'smtp',
			'smtp_host' => 'MY_HOST',
			'smtp_port' => 25,
			'smtp_user' => 'MY_USER',
			'smtp_pass' => 'MY_PASSWORD,
			'mailtype' => 'html',
			'newline' => "\r\n",
			'from' => 'MY_SENDER',
			'charset' => 'utf-8',
		);

		foreach ($addresses as $k => $address) {
			echo '<br><br>sending to '.$address.'<br>';

			$subject = 'testing smtp for address '.$k.' - '.uniqid();
			$message = 'this is a test for address '.$k;
			$this->load->library('email');
			$this->email->initialize($config);
			$this->email->from($config['from'], 'smtp_test');
			$this->email->to($address);
			$this->email->subject($subject);
			$this->email->message($message);

			if ($this->email->send()) {
				echo 'mail sent to '.$address.'<br>';
			}
			else {
				echo 'failed mail to '.$address.'<br>. debug: '.$this->email->print_debugger();
			}
		}
```

Works with your commit (fails first, sends second), doesn't on master (fails first, nested mail command error with the second address).

Let me know if you need anything else. Thank you!

**Comment by narfbg** [comment]
Don't assume you have anything to do with master.

**Comment by koichirose** [comment]
What do you mean? I was just noting that my test correctly worked on the new commit and didn't on master. Anyway, thank you.

**Comment by narfbg** [comment]
Yes, I was telling you that there's no reason to expect that it would work on master.
Hence, no reason to test on master, nor mention that it doesn't work on master.
