### ISSUE TITLE
[Possible Bug] When using 'USING()' in Query Builder

### ISSUE THREAD

**Issue by codetrash** [bcit-ci/CodeIgniter#4719]
I have this Query Builder (using CI Version 3.0.4)

`->join($this->table_product.' d', 'FIND_IN_SET(d.no_int_product,a.main_product)')`

Which will produce

`JOIN m_product d ON FIND_IN_SET(d.no_int_product, a.main_product)`

And its OK for MySQL 

and then I upgraded to CI 3.0.6 Where USING() syntax has been supported. Yet the Query becomes

`JOIN m_product d USING(FIND_IN_SET(d.no_int_product, a.main_product))`

Where its NOT OK for mysql (Error),

**right now, to tackle this issue I use**

`->join($this->table_product.' d', '1=1 AND FIND_IN_SET(d.no_int_product,a.main_product)')`

**Comment by narfbg** [comment]
This is a MySQL-specific function and a very rare use case - we don't support such things.
