### ISSUE TITLE
Using Reflection Method instead of `call_user_func`

### ISSUE THREAD

**Issue by cyberhck** [bcit-ci/CodeIgniter#4720]
I've done benchmark on this topic:
```
<?php
class foo {
    public function bar($var) {
        return true;
    }
}
$runs = 1000000;
$instance = new foo();
$reflection = new ReflectionMethod('foo', 'bar');
$start = microtime(true);
for($i=0; $i<$runs; $i++){
    call_user_func_array(array(&$instance, 'bar'),array('maybe'));
}
$middle = microtime(true);
for($i=0; $i<$runs; $i++){
    $reflection->invoke($instance,array('maybe'));
}
$end = microtime(true);
echo "First finished in ".(($middle-$start)*1000). " milli seconds\n";
echo "Second finished in ".(($end-$middle)*1000). " milli seconds\n";
```
Here, reflection has around same performance as `call_user_func_array`, in `PHP 7` whereas in older version, reflection is faster, since we can introduce more stuffs with this, I'd propose to use reflection function while calling the specific method.

If it's required, I'll submit PR myself.

**Comment by narfbg** [comment]
... what are you talking about?

**Comment by cyberhck** [comment]
Right now, the way specific method gets invoked is using `call_user_func_array` which is a little slower than using reflection method, it's somewhere inside `system/core/CodeIgniter.php`

**Comment by narfbg** [comment]
I understand you're saying `ReflectionMethod` is faster, it's the *where* and "we can introduce more stuffs" parts that I'm not getting.
Either way, you're welcome to submit pull requests for optimizations on a case-by-case basis.

*However*, your benchmark is biased in that you're only instantiating `ReflectionMethod` once.

**Comment by cyberhck** [comment]
Yes, I'm also instantiating `foo` once, which is exactly what happens in `system/core/CodeIgniter.php` we initialize an object then use `call_user_func_array`. If you want, I'll test by instantiating both of them.

**Comment by narfbg** [comment]
I'm not questioning `foo` instantiation - that's fine.

But if you can't claim that:

    $reflection = new ReflectionMethod('foo', 'bar');
    $reflection->invoke($instance, array('whatever'));

is faster than:

    call_user_func_array(array(&$instance, 'bar'), array('whatever'));

... but then only compare `$reflection->invoke()` against `call_user_func_array()`. It's just not the same thing.
