### ISSUE TITLE
CI3 Feature Request, MySQL drivers: Add a possibility directly to set sql_mode per session.

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#4727]
In MySQL 5.7 some default options about sql_mode got changed. For example here is the case I've got:

Development machine:
MySQL 5.7.13
SELECT @@sql_mode;
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

Production server:
MySQL 5.5.48
SELECT @@sql_mode;
(returns empty string)

There is a database connection setting:
['stricton'] TRUE/FALSE - forces 'Strict Mode' connections - good for ensuring strict SQL while developing
When it is true, STRICT_ALL_TABLES option gets enforced. When it is false, STRICT_ALL_TABLES and STRICT_TRANS_TABLES get disable. These are the cases this option covers currently. But I need to ensure that my development and production MySQL servers behave identically.

--------------------------------------------

Could ['stricton'] be made to accept string type that enumerates the sql_mode options directly?

Edit: An additional circumstance is that I migrate old code.

**Comment by narfbg** [comment]
No, this is a legacy MySQL-only functionality and aside from bug fixes we're not making additions to such features.

Also, if you want identical behavior between environments, run identical software versions.

Relevant: #4349
