### ISSUE TITLE
[CI_Email] for smtp protocol in EHLO command hostname is missing

### ISSUE THREAD

**Issue by matiasmirandabrito** [bcit-ci/CodeIgniter#4729]
When you use 
`$config['protocol'] = 'smtp';`

in order to connect to the server is necessary to specify a hostname for the commands EHLO/HELO, this command is sent it by _send_command function, lines 2065 and 2069 of Email.php CI_Email class

`$this->_send_data('EHLO '.$this->_get_hostname());`

here, the hostname is provided by the function _get_hostname()

```
protected function _get_hostname()
        {
                if (isset($_SERVER['SERVER_NAME']))
                {
                        return $_SERVER['SERVER_NAME'];
                }

                return isset($_SERVER['SERVER_ADDR']) ? '['.$_SERVER['SERVER_ADDR'].']' : '[127.0.0.1]';
        }
```

as you can see, if SERVER_NAME **is set**, the function returns that value, otherwise tries with SERVER_ADDR and finally if it's not set then fallback to [127.0.0.1].
In my case, I'm running NGINX and I've not set the fastcgi_param SERVER_NAME/ADDR, then the function returns an empty value for hostname, so the SMTP server response is

> 501 Syntax: EHLO hostname

in order to fix that I used **!empty()**  instead of **isset()** to look for a valid value of SERVER_NAME/ADDR 

Here is the pull request #4728

**Comment by narfbg** [comment]
You're not supposed to have an empty server name or address while running an HTTP server - that's not a valid use case.

**Comment by matiasmirandabrito** [comment]
If you don't have a value in SERVER_NAME/ADDR is a perfect valid use case for an HTTP Server, and your application must be secure on any layer, so your function must be secure also, in this case, the function _get_hostname() uses an external value and also has a default value 127.0.0.1, so, you shouldn't return an invalid value for a hostname in any case, especially when your function provides a required value  for an external command as SMTP EHLO/HELO.
The description of the function says

> Get Hostname
> There are only two legal types of hostname - either a fully
> qualified domain name (eg: "mail.example.com") or an IP literal
> (eg: "[1.2.3.4]").

but for the case that you aren't set a value for SERVER_NAME/ADDR (which is a valid use case for HTTP Server) your functions returns an invalid value _empty_
If you code a unit test for that case, it will fail..

**Comment by narfbg** [comment]
> If you don't have a value in SERVER_NAME/ADDR is a perfect valid use case for an HTTP Server

No, it's not. You can't reach a nameless, addressless server - there would be no way of pointing your browser to it. 

You could have no SERVER_NAME, in which case it should be assumed to equal the SERVER_ADDR (Apache does this by default), but it can't exist and be empty.

The fact that some kind of software out there allows you to do that doesn't make it a "perfectly valid" use case. It's a dirty hack at best, and in fact, since you're talking about stuff being "secure" - there are serious security implications to leaving the SERVER_NAME empty.

And you're going even further to state that you can have an empty SERVER_ADDR as well - this is completely absurd.

**Comment by matiasmirandabrito** [comment]
It's a valid case because if you are using fastcgi, those variables are not required at all. You must send it explicity (and manually), I'm talking of a configuration nginx fpmphp (fastcgi), not Apache that assumes those values.
When I said "secure" I referred to the expected value that a function must return for a given input. That function has not a valid behaviour since hostname can't be an empty value, and, also contradicts his own description....

**Comment by narfbg** [comment]
> It's a valid case because if you are using fastcgi, those variables are not required at all.

Again, that *some* software doesn't require you to explicitly configure them, doesn't mean anything. SERVER_NAME is an essential part of the CGI protocol - you don't get to make arbitrary conclusions about it based on what you are forced to configure or not.
The very fact that nginx actually creates the variable even if you don't provide it should speak volumes.

> You must send it explicity (and manually), I'm talking of a configuration nginx fpmphp (fastcgi), not Apache that assumes those values.

Yes, everything in nginx is explicit. That doesn't mean anything.

And I have not said that you are talking about Apache. I gave an *example* of software that obviously doesn't give you the option to do what you're claiming to be a "perfectly valid" use case.

> When I said "secure" I referred to the expected value that a function must return for a given input.

That is not what "secure" means in the context of programming. Terminology is important.

> That function has not a valid behaviour since hostname can't be an empty value, and, also contradicts his own description....

Please don't make side comments based on the assumption that you're right and I'm wrong. You have to prove that you are right first.
Also, "his" is a gendered pronoun. Functions don't have genders.

**Comment by matiasmirandabrito** [comment]
The principal reason is that in a given environment, with given requirements you can have not setted a server name or addr, get_hostname takes care of that situation with a default value, assuming that the external value is correctly setted, in my opinion, not is a stable behaviour (or secure, or consistent, or reliable). I mean, as a client I can't be sure that a call to ->get_hostname(); will return me a valid hostname, even when its description says explicitly that there are only two valid values for a hostname. (btw when I said "client" I'm talking about OOP, not talking about business..)

> Please don't make side comments based on the assumption that you're right and I'm wrong. You have to prove that you are right first.

I give you a scenario, some conditions and some preconditions, where an unstable behaviour is present, the only thing that I see is that you are defending your position saying that an external configuration is wrong, you're blaming the environment configuration, instead doing the correct treatment if a value is not valid

>  Also, "his" is a gendered pronoun. Functions don't have genders.

Sorry for my English, I meant "the function contradicts **its** own description".... 
At read this comment, seems you're not being collaborative and only you want to argue with me, that is not the spirit of the open source, I mean, I don't want to collaborate with you anymore.

I'm sorry but, I don't want discuss with you, the reasons are there.

Regards.

**Comment by narfbg** [comment]
> The principal reason is that in a given environment, with given requirements you can have not setted a server name or addr, get_hostname takes care of that situation with a default value

That environment is CLI, where literally neither exists and not set but empty. You're again making assumptions.

> in my opinion, not is a stable behaviour (or secure, or consistent, or reliable).

- "stable" is a relative term and meaningless in this context.
- "secure" means, again, something completely different and unrelated to what we're discussing.
- "consistent" is, in my observation, something people use as an argument when they have no arguments.
- "reliable" is relative as well.

> I mean, as a client I can't be sure that a call to ->get_hostname(); will return me a valid hostname, even when its description says explicitly that there are only two valid values for a hostname.

Fine, I will concede that in a broken environment, you can't be sure about that.
What you have is what I consider a broken environment and we don't support such cases.

> (btw when I said "client" I'm talking about OOP, not talking about business..)

When we're talking about SERVER_NAME and SERVER_ADDR, we're talking about HTTP - I'm far from thinking that you'd mean business.
Though, it's good that you're clarifying that you meant something else.

> I give you a scenario, some conditions and some preconditions, where an unstable behaviour is present, the only thing that I see is that you are defending your position saying that an external configuration is wrong, you're blaming the environment configuration, instead doing the correct treatment if a value is not valid

Yes, I am blaming the environment, and you seem to be defending the position that the environment is never at fault.

Sorry, I will never agree with you on this.

> At read this comment, seems you're not being collaborative and only you want to argue with me, that is not the spirit of the open source, I mean, I don't want to collaborate with you anymore.

You know you're not being collaborative either - you're not trying to prove your claims, but just using different words to directly contradict mine.

Yes, I will argue about every incorrect thing. Are you claiming that accepting incorrectness is in the spirit of open-source? Furthermore, are you claiming that another person trying to correct a mistake of yours is not in the spirit of open-source? :)

This is a petty, off-topic argument, indeed. But you're taking it the wrong way.

> I'm sorry but, I don't want discuss with you, the reasons are there.

That's ok. From my POV, this was never a discussion in the first place.
