### ISSUE TITLE
ini_set(): Use of mbstring.internal_encoding is deprecated-\system\core\CodeIgniter.php-249

### ISSUE THREAD

**Issue by arunjainmca** [bcit-ci/CodeIgniter#4730]
I am using apache 2.4.17 & php 5.6.16. Getting the below error:

ini_set(): Use of mbstring.internal_encoding is deprecated-C:\xampp\htdocs\ios\system\core\CodeIgniter.php-249

while using system Exception class. Any help would be appreciated.

Thanks

**Comment by narfbg** [comment]
The framework suppresses this notice. You shouldn't be getting it if you haven't modified our code and we can't do anything else about it.
Please ask your questions on our [forums](http://forum.codeigniter.com/) instead; this is a bug tracker.
