### ISSUE TITLE
Database warning using PDO DBLIB "driver does not support setting attributes"

### ISSUE THREAD

**Issue by CrazyCodeUK** [bcit-ci/CodeIgniter#4731]
Seems to be the same issue as [https://github.com/bcit-ci/CodeIgniter/issues/4674] which is listed as fixed for 3.0.7

I am using CI 3.1.0

The error i am getting is:

`A PHP Error was encountered

Severity: Warning

Message: PDO::__construct() [pdo.--construct]: SQLSTATE[IM001]: Driver does not support this function: driver does not support setting attributes

Filename: pdo/pdo_driver.php

Line Number: 133`

I have tried with both the configs below with the same effect:
`$db['kx'] = array(
	'dsn'	=> 'dblib:host=house;dbname=germ',
	'username' => '****',
	'password' => '****',
	'dbdriver' => 'pdo',
	'db_debug' => TRUE
);`
and
`$db['kx'] = array(
	'dsn'	=> 'dblib:host=house;dbname=germ',
	'hostname' => 'house',
	'username' => '****',
	'password' => '****',
	'database' => 'germ',
	'dbdriver' => 'pdo',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);`
with the executing code being:
`        $kxdb = $this->CI->load->database('kx',TRUE);
        return $result = $kxdb->query("EXEC ClientUKC_RoomExport")->result();`

**Comment by narfbg** [comment]
[That line is empty](https://github.com/bcit-ci/CodeIgniter/blob/3.1.0/system/database/drivers/pdo/pdo_driver.php#L133).

Also, please don't open a new issue when you can comment on an old one.
