### ISSUE TITLE
Memcached session driver false warning on write

### ISSUE THREAD

**Issue by niglu** [bcit-ci/CodeIgniter#4732]
Codeigniter issues a warning when writing a session for the first time.

"Message: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (localhost:11211)"

However, everything seems to work just fine. Just an unnecessary warning.

This seems to originate around line 214 in Session_memcached_driver.php.

Observations:
 * I'm using Google App Engine - if nobody else can reproduce, this might be a platform issue
 * When changing Memcached::RES_NOTFOUND on line 214 to Memcached::RES_NOTSTORED (as it used to be before 8215e2fcf828964b232e9f48befac4f08fa11187, problem goes away. But I don't know enough about Memcached or CI to be sure I'm not breaking anything else here.

**Comment by narfbg** [comment]
See #3919.

**Comment by niglu** [comment]
Forget what I said here, it does not work at all... I just changed the the code to be more readable during debugging and accidentally made it work partially. Will write more at #3919
