### ISSUE TITLE
an Notice error on php v5.6

### ISSUE THREAD

**Issue by yozman** [bcit-ci/CodeIgniter#4734]
`/system/core/Loader.php`

on line `1405`

```
protected function &_ci_get_component($component)
{
    $CI =& get_instance();
    return $CI->$component;
}
```

should change to

```
protected function &_ci_get_component($component)
{
    $CI =& get_instance();
    $component = $CI->$component;
    return $component;
}
```

**Comment by narfbg** [comment]
I am not blindly applying patches.

You need to explain what the problem is, in detail.

**Comment by yozman** [comment]
@narfbg
 there is the message:

```
A PHP Error was encountered

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Loader.php

Line Number: 1405

Backtrace:

File: C:\Users\flyboy\Documents\GitHub\sinoci\app\Models\Site\ShowWelcome.php
Line: 11
Function: add_package_path

```

**Comment by narfbg** [comment]
This is far from a detailed explanation, and I can't reproduce it.

**Comment by yozman** [comment]
@narfbg

when I want to use
`$this->load->add_package_path()`
on PHP 5.6 with `error_reporting(-1)`

there is a Notice
```
A PHP Error was encountered

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Loader.php

Line Number: 1405

Backtrace:

File: C:\Users\flyboy\Documents\GitHub\sinoci\app\Models\Site\ShowWelcome.php
Line: 11
Function: add_package_path
```

then I find the way to fix it:
change `/system/core/Loader.php`
on line `1405`

```
protected function &_ci_get_component($component)
{
    $CI =& get_instance();
    return $CI->$component;
}
```

should be

```
protected function &_ci_get_component($component)
{
    $CI =& get_instance();
    $component = $CI->$component;
    return $component;
}
```

**Comment by narfbg** [comment]
I *can't reproduce* the problem that you're describing.

**Comment by ajm113** [comment]
Just a shot in the dark, but it could be the way you are setting up or using CodeIgniter. I've ran CI many times on PHP 5.x and never gotten this error. Could you post some sample code when you are using ```$this->load->add_package_path()```?

**Comment by JordanP** [comment]
> File: C:\Users\flyboy\Documents\GitHub\sinoci\app\Models\Site\ShowWelcome.php
He seems to be running Windows.
