### ISSUE TITLE
Undefined index log_path and in core/Log.php

### ISSUE THREAD

**Issue by rk4an** [bcit-ci/CodeIgniter#4735]
Hi,

I'm running CodeIgniter 3.1 on Ubuntu 14.04 LTS, this error was present on previous version of CodeIgniter too for me, I don't know if it's a bug or a bad configuration, any idea please?
![image](https://cloud.githubusercontent.com/assets/322320/17210992/d988f4a0-54c6-11e6-8af7-3d4548385c82.png)

**Comment by narfbg** [comment]
This is a bug tracker. If you're looking for help, try our [forums](http://forum.codeigniter.com/) instead.

Also, please don't use screenshots.
