### ISSUE TITLE
Image library is broken in 3.1.0

### ISSUE THREAD

**Issue by monsterlane** [bcit-ci/CodeIgniter#4736]
The addition of escapeshellargs on this line breaks image processing: https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Image_lib.php#L889

It's double quoting the paths: "'...'" instead of '...'

That line should read:

`$cmd .= ' '.escapeshellarg($this->full_src_path).' '.escapeshellarg($this->full_dst_path).' 2>&1';`

**Comment by sv3tli0** [comment]
What is your system as I know escapeshellarg works a little bit different under Windows .. 
Perhaps a system difference is causing the problem, not the php code as its written..

**Comment by monsterlane** [comment]
I'm on a Mac and encapsulating the parameters in double quotes then single quotes doesn't work. It may be hard to see but its doing this:

[doublequote][singlequote]parmeter[singlequote][doublequote]
