### ISSUE TITLE
"hasFile" function

### ISSUE THREAD

**Issue by rafa-acioly** [bcit-ci/CodeIgniter#4738]
I'm working on a project that i do a lot of stuff's with files send by user and i realize that doesn't exist a function to verify if exist a key on `$_FILES` on upload class.
I will be very happy to make this push if approved.

**Comment by narfbg** [comment]
`isset($_FILES['file'])`

**Comment by rafa-acioly** [comment]
`$this->upload->hasFile("key");` return bool.
what do you think?
