### ISSUE TITLE
how to fix "Cannot modify header information - headers already sent by Filename: libraries/Session.php

### ISSUE THREAD

**Issue by anharku** [bcit-ci/CodeIgniter#4740]
A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\\xxx.php:522)

Filename: libraries/Session.php

Line Number: 675

How to fix this message?
i want make Avant bootstrap and join my codeigniter

![error](https://cloud.githubusercontent.com/assets/4042666/17268631/125be8b6-565a-11e6-9560-90b8d4ad4260.jpg)

**Comment by sumanta-ghosh** [comment]
@anharku this not an issue of codeigniter. If you add any space/line before php starting(<?php) tag in controller it may show this type of error.

**Comment by narfbg** [comment]
This is a bug tracker, we don't provide general help here.
Please ask your questions on our [forums](http://forum.codeigniter.com/) instead.

**Comment by MarcioQuimbundo** [comment]
error_reporting(0) will not solve the problem, but it will clean the output error
