### ISSUE TITLE
Issue with storing string with a backslash(\) in session.

### ISSUE THREAD

**Issue by themanish** [bcit-ci/CodeIgniter#4741]
**Example**
    
    function step1() {
        $data = array(
            'level_1' => array(
                'level_2' => 'abc\def'
            ),
        );
        $this->session->set_userdata("data", $data);
    }
    function step2() {
        echo '<pre>';
        print_r($this->session->all_userdata());
    }

**Comment by narfbg** [comment]
I don't see an issue here (and you're not being descriptive, to say the least).

Whatever the problem you're having, it's not a bug in CodeIgniter, and so you should ask for help on our [forums](http://forum.codeigniter.com/) instead.
