### ISSUE TITLE
An uncaught Exception was encountered  Type: RuntimeException  Message: Unable to locate the model you have specified: CI_auth

### ISSUE THREAD

**Issue by desire1982** [bcit-ci/CodeIgniter#4743]
An uncaught Exception was encountered

Type: RuntimeException

Message: Unable to locate the model you have specified: CI_auth

Filename: C:\wamp\www\CodeIgniter\ci_reg\system\core\Loader.php

Line Number: 344

Backtrace:

File: C:\wamp\www\CodeIgniter\ci_reg\application\controllers\Welcome.php
Line: 8
Function: model

File: C:\wamp\www\CodeIgniter\ci_reg\index.php
Line: 315
Function: require_once

I am a beginner in codeigniter. My website shows me this error. I want help for my problem and see which file work. it is also a help to solve this problem in codeigniter, please show me this link.

**Comment by narfbg** [comment]
This is a bug tracker, not a helpdesk system.
Please ask your questions on our [forums](http://forum.codeigniter.com/) instead.
