### ISSUE TITLE
Problems on custom validation rules with array input data

### ISSUE THREAD

**Issue by gastongr** [bcit-ci/CodeIgniter#4745]
Hello, when using custom validation rules defined in MY_Form_validation on input fields with array data, the data is passed as a string to the validation function.

Also when the field data is a multi-dimensional array the validation function is not called at all.

**Comment by narfbg** [comment]
Hi,

This is a bug tracker, and we don't like [double](http://forum.codeigniter.com/thread-65857.html) [posting](http://forum.codeigniter.com/thread-65859.html).

**Comment by gastongr** [comment]
And this is a bug report.

What you refer as double posting are actually two different posts describing two different problems, i joined them in this single issue here at github.

The first one could be a bug, the second might be a known limitation where you have to fully specify the field name in order for the validation rules to be fired. For example, using the field name data[] while defining the rules wont validate data[0]['name']

It's my intention to provide helpful feedback on the described situation, i hope you can undestand the double posting.

Regards

**Comment by narfbg** [comment]
A bug report should include a very clear explanation of the problem, technical details, ways to reproduce and, in general, information that undoubtedly shows the problem is indeed caused by a bug.

It is quite obvious that you've provided none of that, and posting about the same problem(s) on multiple platforms to reach us is counter-productive. Especially when you've allowed zero time for reply via whichever channel you've used first.

**Comment by gastongr** [comment]
> A bug report should include a very clear explanation of the problem, technical details, ways to reproduce and, in general, information that undoubtedly shows the problem is indeed caused by a bug.

I agree with that most of the time, but in this case the situation can be perfectly described in a single sentence.  If you care to read.

I didn't posted on multiple channels to reach you.
Posting on the forums aims to reach the community looking for help or advice.
Posting here aims to report the issue to the developers, you do whatever you want from here on.

**Comment by narfbg** [comment]
>> A bug report should include a very clear explanation of the problem, technical details, ways to reproduce and, in general, information that undoubtedly shows the problem is indeed caused by a bug.
>
> I agree with that most of the time, but in this case the situation can be perfectly described in a single sentence. If you care to read.

I don't appreciate the snarky implication that I didn't even read your 2-sentence opening post. Nor the fact that you're still not providing any further feedback.

Just in case I haven't been clear enough - you have not shown a single credible clue of a bug here. What you say is "perfectly described in a single sentence" raises more questions than it answers, as usage of `MY_Form_validation` means that you're modifying the behavior of the library, no longer guaranteeing that it behaves like intended to.

You have not shown a single code example of what doesn't work like you expect it to.
You've provided literally zero technical details, not even a version number.
Your usage of wording such as "*might be* a bug" shows that even you are unsure of your own claims.

See where I'm coming from?

> I didn't posted on multiple channels to reach you.
> Posting on the forums aims to reach the community looking for help or advice.
> Posting here aims to report the issue to the developers, you do whatever you want from here on.

1. This is a community-driven project, reaching the community does mean reaching us.
2. If you want to ask the community for help, at least let that community help you in determining wheter you are indeed looking at a bug.
