### ISSUE TITLE
3.1.0 Email Library Corrupting PDF Attachments

### ISSUE THREAD

**Issue by SyntaxSniffer** [bcit-ci/CodeIgniter#4747]
When attaching MPDF generated PDF's to an email in 3.1.0 the header for the pdf file itself is modified and the beginning of the file is truncated.

I am attaching a screenshot to show what I mean.

Reverting only the email library file back to 3.0.6 in the system folder resolves the issue.

Version 3.0.6 - Expected Output
![3 0 6](https://cloud.githubusercontent.com/assets/2049188/17409184/1750985e-5a3c-11e6-8c5f-c61fa412cf7b.PNG)

Version 3.1.0 - Invalid file format
![3 1 0](https://cloud.githubusercontent.com/assets/2049188/17409192/22f95b14-5a3c-11e6-94d2-586ec7f0a912.PNG)

**Comment by narfbg** [comment]
Use the search bar please: #4739

**Comment by skycyclone** [comment]
对比正常的邮件原文和ci发出的邮件原文，发现CI发出的附件“Content-Transfer-Encoding: base64”和附件的正文内容编码间缺少一个换行符，
查看CI的内核/libraries/Email.php文件，
1470行，.'Content-Transfer-Encoding: base64'.$this->newline

在后面再添加一个".$this->newline"问题解决。

另，在1471行，.(empty($this->_attachments[$i]['cid']) ? '' : 'Content-ID: <'.$this->_attachments[$i]['cid'].'>'.$this->newline.$this->newline)
可以看出，如果指定了附件的id，貌似会换行两次，如果没有指定，附件将无法下载。

需要修改内核文件才解决问题，这个bug比较低级，希望官方尽快处理，我的版本是3.1.0
