### ISSUE TITLE
PDO Error 00000 in drivers/Session_database_driver.php under HHVM + pdo/pgsql

### ISSUE THREAD

**Issue by Simpliant** [bcit-ci/CodeIgniter#4751]
A Database Error Occurred
Error Number: 00000
SELECT "data" FROM "ci_sessions" WHERE "id" = 'redacted'
Filename: libraries/Session/drivers/Session_database_driver.php
Line: 169 - > 
```
if ( ! ($result = $this->_db->get()) OR ($result = $result->row()) === NULL) 
```
Throws 00000 (means "OK") no error / 0 rows in select.

HipHop VM 3.11.1 (rel) + https://github.com/PocketRent/hhvm-pgsql - PostgreSQL 9.5 
hhvm-pgsql extension can only be summoned in CI as 'pdo' in the config/database.php and not 'prostgre'

Same query running form cli.
```
db=#  SELECT "data" FROM "ci_sessions" WHERE "id" = 'redacted'
db-# ;
 data 
------
(0 rows)
```

**Comment by narfbg** [comment]
That's an HHVM problem, not ours.
