### ISSUE TITLE
Call not defined methods in a controller, how?

### ISSUE THREAD

**Issue by fiblan** [bcit-ci/CodeIgniter#4752]
I need to use the __call in a controller to call not defined methods.

Probably use `is_callable` in Sanity checks (CodeIgniter.php) resolve but:
  https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/CodeIgniter.php#L423
Even now  you can not use is_callable? 
@narfbg 522c73623 your comment refers to php 5.2 issues [?]

**Comment by narfbg** [comment]
You "need" to use `__call()`.

I don't know what else to say about this ... this issue shouldn't have been created in the first place.

**Comment by fiblan** [comment]
Thank you for your reply. 
Sorry but my question was only "if" it's possible (now 2016) to fix your workaround (2012) and then to permit  call not defined methods with __call().
thanks
