### ISSUE TITLE
Using SERVER_ADDR for base_url is inconvenient 

### ISSUE THREAD

**Issue by aanbar** [bcit-ci/CodeIgniter#4753]
I have just noticed that now CodeIgniter set base_url to an IP address by default using ``$_SERVER['SERVER_ADDR']`` while it was using HOST_NAME

If I understand correctly it was changed due to security concerns; My Question is why wasn't it changed to something like ``$_SERVER['SERVER_NAME']`` which isn't vulnerable & wouldn't break compatibility

**Comment by Ema4rl** [comment]
From what I read in the upgrade guides, it was basically set to `$_SERVER['SERVER_ADDR']` so that you'll be forced to set your `$config['base_url']` to an appropriate base.

**Comment by kenjis** [comment]
`$_SERVER['SERVER_NAME']` could be also vulnerable.
