### ISSUE TITLE
Working with index metadata for a given table

### ISSUE THREAD

**Issue by pkarunyu** [bcit-ci/CodeIgniter#4756]
Yipee!! My first attempted contribution to the CI framework, after 7 years of active use!!

**How it started**
I found myself in a situation where I needed to drop and re-create an index on very many tables, but wanted to check if that index exists first.

I assumed since the function `field_exists` exists, then `index_exists` exists, but it did not. I checked the code and it didn't seem too hard to implement, so I tried it.

Basically, this feature would be closely modelled on `field_exists`. This is what I learnt:

**TODO**
* `index_exists` would depend on `list_indexes`
* `list_indexes` depends on `_list_indexes`
* For completeness, I would want to have `index_data`
    
**Questions**

1. The [contribution guide](https://github.com/bcit-ci/CodeIgniter/blob/develop/contributing.md) says `If you change anything that requires a change to documentation then you will need to add it.`, does this mean that, if accepted, the eventual pull request should also include changes to the following sub-sections of the database section of the user guide?
  * [metadata](https://github.com/pkarunyu/CodeIgniter/blob/develop/user_guide_src/source/database/metadata.rst)
  * [DB driver reference](https://www.codeigniter.com/userguide3/database/db_driver_reference.html)
2. The  contribution guide says `One thing at a time: A pull request should only contain one change`, does my suggested changes above constitute `one change`?
3. Do I need to make the change in all the 12 database drivers?

Now, I did attempt to make this change on the MySQL, MySQLi and Postgre database drivers, and it seems to work fine. I will initiate a PR for the change to the MySQLi driver, for review and further guidance.

**Comment by narfbg** [comment]
> I found myself in a situation where I needed to drop and re-create an index on very many tables, but wanted to check if that index exists first.

Most databases support `IF EXISTS`. Also, I don't understand why you want to do this with PHP.

> I assumed since the function `field_exists` exists, then `index_exists` exists, but it did not. I checked the code and it didn't seem too hard to implement, so I tried it.
>
> Basically, this feature would be closely modelled on `field_exists`

`field_exists()` is way more likely to be called on a regular basis. For example, an application may dynamically determine whether it should `SELECT` a certain field or not, probably for BC maintenance purposes.

I'm not at all convinced that `index_exists()` would be beneficial in the same way to our users.

> - `index_exists` would depend on `list_indexes`

That would be sub-optimal.

> - `list_indexes` depends on `_list_indexes`

This would be an implementation detail, only relevant to be discussed as part of a patch (pull request).

> - For completeness, I would want to have `index_data`

Sorry, we don't do things "for completeness" ... Having more features and code means more maintenance efforts and needs to be justified.

> 1. The [contribution guide](https://github.com/bcit-ci/CodeIgniter/blob/develop/contributing.md) says `If you change anything that requires a change to documentation then you will need to add it.`, does this mean that, if accepted, the eventual pull request should also include changes to the following sub-sections of the database section of the user guide?
>  * [metadata](https://github.com/pkarunyu/CodeIgniter/blob/develop/user_guide_src/source/database/metadata.rst)
>  * [DB driver reference](https://www.codeigniter.com/userguide3/database/db_driver_reference.html)
> 2. The  contribution guide says `One thing at a time: A pull request should only contain one change`, does my suggested changes above constitute `one change`?
> 3. Do I need to make the change in all the 12 database drivers?

1. Yes, this is mandatory.
2. Arguable.
3. Yes, but ...

  - It probably can't be supported under odbc
  - Taking into account pdo sub-drivers, there are more than 12 drivers.

> Now, I did attempt to make this change on the MySQL, MySQLi and Postgre database drivers, and it seems to work fine. I will initiate a PR for the change to the MySQLi driver, for review and further guidance.

Opening an issue when you also intend to create a pull request splits the conversation and is counter-productive ... please don't do that in the future.
Also, you pull request - #4747 - lacks information describing the feature, making it hard to find when somebody is searching. And puts me in a hard position too - I don't need this issue laying around, but I can't close it because it's the only thing giving context to your PR.

**Comment by pfote** [comment]
wouldnt that be more standard-wise and portable to implement using information_schema? but, as narf said, doubt thats a issue for most users

**Comment by narfbg** [comment]
> wouldnt that be more standard-wise and portable to implement using information_schema?

That's what I meant by saying "sub-optimal". :)

**Comment by pkarunyu** [comment]
> Most databases support IF EXISTS. Also, I don't understand why you want to do this with PHP.

In MySQL 5.5, the queries below do not work:

```sql
ALTER TABLE `table_name` DROP INDEX IF EXISTS `index_name`;
ALTER TABLE `table_name` CREATE INDEX IF NOT EXISTS `index_name` (`column_name`);
```

I have a database with 700 tables, 500 of which are dynamically created in PHP and are 99% similarly named. I wanted to loop through these 500 tables, dropping a specific index and column if it existed, and recreating the column and index in a better way.

> field_exists() is way more likely to be called on a regular basis. For example, an application may dynamically determine whether it should SELECT a certain field or not, probably for BC maintenance purposes.
> I'm not at all convinced that index_exists() would be beneficial in the same way to our users.

Correct. In my few years of using CI, I've only had need to check if an index exists only once, day before yesterday.

> That would be sub-optimal.
> Sorry, we don't do things "for completeness" ... Having more features and code means more maintenance efforts and needs to be justified.

I followed the style used for `field_exists` in DB_driver.php, which then calls `list_fields` still in DB_driver.php, which then calls `_list_columns` in mysqli_driver.php. Extrapolating that logic for consistency, then I would have `index_exists` calling `list_indexes` which would then call `_list_indexes`, except for the dilemma I mentioned to @tianhe1986 (and an example of a split conversation). And since we have the function `field_data`, IMHO it would be consistent then to have `index_data`.

So maybe I should have said "consistency" instead of "completeness".

> Opening an issue when you also intend to create a pull request splits the conversation and is counter-productive ... please don't do that in the future.

Noted.

> Also, you pull request - #4747 - lacks information describing the feature, making it hard to find when somebody is searching. And puts me in a hard position too - I don't need this issue laying around, but I can't close it because it's the only thing giving context to your PR.

Understood. I think then both can be closed or archived, seeing as this feature lacks global appeal?

Thanks for the guidance, much appreciated @narfbg and @pfote

**Comment by narfbg** [comment]
>> Most databases support IF EXISTS. Also, I don't understand why you want to do this with PHP.
>
> In MySQL 5.5, the queries below do not work:
> 
>    ALTER TABLE `table_name` DROP INDEX IF EXISTS `index_name`;
>    ALTER TABLE `table_name` CREATE INDEX IF NOT EXISTS `index_name` (`column_name`);

I said "most", being unsure if MySQL supports it, but there's always an alternative using `information_schema`.

> I have a database with 700 tables, 500 of which are dynamically created in PHP and are 99% similarly named. I wanted to loop through these 500 tables, dropping a specific index and column if it exists, and recreating the column and index in a better way, hence the PHP loop.

Well, you've put yourself in that hell of a situation ... :)

>> That would be sub-optimal.
>> Sorry, we don't do things "for completeness" ... Having more features and code means more maintenance efforts and needs to be justified.
>
> I followed the style used for `field_exists` in DB_driver.php, which then calls `list_fields` still in DB_driver.php, which then calls `_list_columns` in mysqli_driver.php. Extrapolating that logic for consistency, then I would have `index_exists` calling `list_indexes` which would then call `_list_indexes` ...

I do understand how you got to that, `field_exists()` itself is old code that probably nobody cares for and as such is far from a fine example.

> And since we have the function `field_data`, IMHO it would be consistent then to have `index_data`.
>
> So maybe I should have said "consistency" instead of "completeness".

Same thing, if not worse - "consistency" is usually an argument used to mask lack of objective arguments. :)

> I think then both can be closed or archived, seeing as this feature lacks global appeal?

I'd say so, yes.

**Comment by pkarunyu** [comment]
> I said "most", being unsure if MySQL supports it, but there's always an alternative using information_schema.

Correct, there are other ways to go about checking if an index exists.

> Well, you've put yourself in that hell of a situation ... :)

Tell me about it! I did manage to do what I wanted though, using other means.

> I do understand how you got to that, but field_exists() itself is old code that probably nobody cares for and as such is far from a fine example.

Maybe... I would say that at least one person really cares for `field_exists` and uses it rather frequently ;-)

> Same thing, if not worse - "consistency" is usually an argument used to mask lack of objective arguments. :)

We did come up with a better implementation for this with @tianhe1986, [here](https://github.com/bcit-ci/CodeIgniter/pull/4757/#discussion_r74215788). But this is now a moot point, no?

**Comment by narfbg** [comment]
A moot point indeed.
