### ISSUE TITLE
codeigniter session userdata from page to page working before but eventually lost on page redirect

### ISSUE THREAD

**Issue by emiglobetrotting** [bcit-ci/CodeIgniter#4767]
It seems something has gone wrong with my Codeigniter internal. I was able to access session variables from one page to another. But something made me to reinstall PHP and Database (MariaDB).

After the installation my Codeigniter project start losing session data from one page to another page. I did checked if session is actually creating in ci_sessions table; and behold it does; and i can access the session variable from the same page it was set with userdata and not flashdata.

For example 

Tt.php

    <?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

    class Tt extends CI_Controller
    {
	    public function __construct()
	    {
		    parent::__construct();
	    }
	    public function index()
	    {
		    $this->session->set_userdata('aa','emi');
            /* if header redirect is commented out and i echo the below
            echo $this->session->userdata('aa'); //will display "emi" */
            /*but if header redirect is not commented out and redirect to Vv.php controller*/
		    header("Location: vv"); /*echo $this->session->userdata('aa'); shows nothing in Vv.php controller*/
	    }
    }

Vv.php

    <?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

    class Vv extends CI_Controller
    {
	    public function __construct()
	    {
		    parent::__construct();
	    }
	    public function index()
	    {
		    echo $this->session->userdata('aa'); //shows nothing
	    }
    }

I haven't set anything else other than uninstalling and installation of  php and database (MariaDB). But before then I can access session variable set in Tt in Vv, and vice versa.

Session setting in config.php is below:

    $config['sess_driver'] = 'database';
    $config['sess_cookie_name'] = 'ci_session';
    $config['sess_expiration'] = 7200;
    $config['sess_save_path'] = 'ci_sessions';
    $config['sess_match_ip'] = FALSE;
    $config['sess_time_to_update'] = 300;
    $config['sess_regenerate_destroy'] = FALSE;

Database Setting in database.php

    $active_group = 'default';
    $query_builder = TRUE;

    $db['default'] = array(
	  'dsn'	=> '',
	  'hostname' => '127.0.0.1',
	  'username' => 'root',
	  'password' => '<mypassword>',
	  'database' => 'appname',
	  'dbdriver' => 'mysqli',
	  'dbprefix' => '',
	  'pconnect' => FALSE,
	  'db_debug' => (ENVIRONMENT !== 'production'),
	  'cache_on' => FALSE,
	  'cachedir' => '',
	  'char_set' => 'utf8',
	  'dbcollat' => 'utf8_general_ci',
	  'swap_pre' => '',
	  'encrypt' => FALSE,
	  'compress' => FALSE,
	  'stricton' => FALSE,
	  'failover' => array(),
	  'save_queries' => TRUE
    );

I've tried everything possible but still no luck to get it working back, I don't know if it is MariaDB lock on read. I will be glad if someone can suggest a solution. Also on [Stackoverflow](http://stackoverflow.com/questions/38936961/codeigniter-session-userdata-from-page-to-page-working-before-but-eventually-los).

**Comment by narfbg** [comment]
This is a bug tracker, we don't answer to general help requests here.
We also don't like cross-posts.

**Comment by indeepaherath** [comment]
If you are using a older version of codeigniter 3 with php 7. upgrade it to a newer version. that'll fix your problem

**Comment by Alkasih** [comment]
Yes, CI 2.x.x is not working good with php 7, upgrading to new version of CI will fix the problems.

**Comment by barotrahulh123** [comment]
@Alkasih i have same problem but used new version of codeigniter is not possible beacuse its taking to much time give another solution without changing version of ci and php

**Comment by narfbg** [comment]
Again, this is a bug tracker. You're not supposed to seek random advice here, let alone demand "another solution" because you're not responsible enough to do upgrades.

Running CI2 today is not acceptable, and the upgrade procedure is made as easy as possible. I don't care if you say it takes too much time - that's a lie; it takes only a few hours in the worst case, and you get countless bug fixes that will *save* you time later.

Just get to it.
