### ISSUE TITLE
Number Helper

### ISSUE THREAD

**Issue by arielcannal** [bcit-ci/CodeIgniter#4769]
I suggest adding the following methods to this helper:
function is_even ($number){
if ($number % 2 == 0) {
  return true;
}
return false;
}

function is_odd ($number){
if ($number % 2 != 0) {
  return true;
}
return false;
}

**Comment by softwarespot** [comment]
Just so you know, this can be a one-liner

**Comment by arielcannal** [comment]
Yes! I generally use the way you said, but I realized that creating the helper, the development of the application is faster and more intuitive.
Sorry: Google Translate

**Comment by narfbg** [comment]
We don't add helpers for one-liners, that's pointless.
