### ISSUE TITLE
Can't load library or model in controller with same name

### ISSUE THREAD

**Issue by pawelkg** [bcit-ci/CodeIgniter#4771]
When trying to load library or model with name is same as cotroller, library/model don't load.

Example:
` class Test extends CI_Controller {
    public function index()
    {
        $this->load->library('test');
        $this->test->method();
    }
} `

It returns error on line "$this->test->method()":

> Severity: Notice
> Message: Undefined property: Test::$test

In CI Logs there is DEBUG entry:
> Test class already loaded. Second attempt ignored.

When try to load model 'Test' it throw exception:
> Type: RuntimeException
> Message: Class Test already exists and doesn't extend CI_Model

Test on CI 3.1.0 and PHP 5.6 and PHP 7.0

**Comment by narfbg** [comment]
Of course you can't have 2 classes with the same name.

**Comment by ring0li** [comment]
$this->load->model("new_db/user_interest_model");

        unset($this->user_interest_model);
        $this->load->model("old_db/user_interest_model");

why??
