### ISSUE TITLE
base_url() on error pages not working?

### ISSUE THREAD

**Issue by AzaZPPL** [bcit-ci/CodeIgniter#4774]
Is it intended that we can't call base_url() on custom error pages. I've found this thread http://forum.codeigniter.com/thread-1694.html where it says you should add a `require_once`. Why would I need to do this if I have already autoloaded the helper?

Someone from stackoverflow asking the same question. http://stackoverflow.com/questions/38048365/base-url-function-wont-work-on-error-pages-even-after-autoloading

**Comment by narfbg** [comment]
You haven't "already autoloaded" it, you have *configured* it to be auto-loaded, which happens after these error checks.

**Comment by AzaZPPL** [comment]
I see that makes sense. But how would one fix this users problem? We cant call the `base_url()` from `require_once BASEPATH . '/helpers/url_helper.php';` because I think in the url_helper we need what is after the error checks.

Do we just open the config file and check with regex?

What is the correct way to fix this users issue?

**Comment by narfbg** [comment]
This is a bug tracker, we don't provide such advice here. You should ask your questions on our [forums](http://forum.codeigniter.com/) instead.
