### ISSUE TITLE
Unable to locate the specified class: Session.php

### ISSUE THREAD

**Issue by leolicai** [bcit-ci/CodeIgniter#4775]
There is a library  to get application all controllers and all public functions.
There is a part of code get the class and path:
`
    /**
     * Get the all controllers
     *
     * @return array
     */
    public static function getControllers() {
        $path = APPPATH . 'controllers' . DIRECTORY_SEPARATOR;
        $list = array();
        if (is_dir($path)) {
            if ($dh = opendir($path)) {
                while (($file = readdir($dh)) !== false) {
                    if(preg_match('/php$/i', $file)) {
                        $list[substr($file, 0, -4)] = $path . $file;
                    }
                }
                closedir($dh);
            }
        }
        return $list;
    }
`
There is detail get the public methods
`
    /**
     * Get controller map
     *
     * @return array
     */
    public static function mapControllers() {
        $list = self::getControllers();
        $map = array();
        if(empty($list)) {
            return $map;
        }

        $cc = get_class(get_instance());
        foreach($list as $class => $path) {
            if(!class_exists($class, FALSE)) {
                include_once($path);
            }

            //$map[$class] = get_class_methods($class);

            //**
            $obj = null;
            if($cc == $class) {
                $obj =& get_instance();
            } else {
                $obj = new $class();
                log_message('debug', 'created obj:' . get_class($obj));
            }
            //*/

            $map[$class] = get_class_methods($obj);

        }
        return $map;
    }
`

In the some controller
call: mapControllers();
There is a error:
Unable to locate the specified class: Session.php

**Comment by narfbg** [comment]
Not our problem.
