### ISSUE TITLE
Why include library don't work in cli mode？ 

### ISSUE THREAD

**Issue by fanhefan** [bcit-ci/CodeIgniter#4779]
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Daemon extends MY_Cli_Controller {

    public $fuc;
    public $pid;

    public function __construct() {
        
        $this->load->library('Pidfile');
    }
 
----------------------------
error Message:     Call to a member function library() on null

In cli mode , can't use $this->load->library(),$this->uri->segment(4,1)  ?

**Comment by narfbg** [comment]
Please note that this is a bug tracker.

Questions like yours should be asked on our [forums](http://forum.codeigniter.com/) or sites like StackOverflow.
