### ISSUE TITLE
error in php7

### ISSUE THREAD

**Issue by hzb** [bcit-ci/CodeIgniter#4783]
In php 7, I get this error

```
A PHP Error was encountered
Severity: Notice
Message: Only variables should be assigned by reference
Filename: core/Loader.php
Line Number: 150
```

There's no error in php5.6.

My development environment:

CI version: 3.1.0
Apache, PHP7

**Comment by narfbg** [comment]
[That line](https://github.com/bcit-ci/CodeIgniter/blob/3.1.0/system/core/Loader.php#L150) is a comment.
