### ISSUE TITLE
Create multiple classes that extend CI_Form_validation not using the default name MY_Form_validation

### ISSUE THREAD

**Issue by giltroymeren** [bcit-ci/CodeIgniter#4794]
I am using CI 3.x and I wanted to create multiple validation classes for forms. 

I just learned from [this StackOverflow thread](http://stackoverflow.com/questions/16002237/code-igniter-custom-field-validation-not-working) that only the name `MY_Form_validation.php` (given the default prefix `MY_` is set in the configuration) is allowed.

If this is legitimate why isn't this supported? I just want to create separate validation classes for different business logics and I want to keep all my validations in their classes, not in the controllers.

If not, is this mentioned in the documentation?

I am looking forward to your support.

**Comment by MackieeE** [comment]
Have you post this on the CodeIgniter forums? That's probably a more appropriate place to ask this.

**Comment by anovsiradj** [comment]
how about: /application/third_party/CustomFValidation.php

**Comment by narfbg** [comment]
This is a bug tracker, not a support ticketing system.

As already pointed out, our [forums](http://forum.codeigniter.com/) are a the place to ask such questions.
