### ISSUE TITLE
Form Validation Rules Not Trimmed

### ISSUE THREAD

**Issue by Garanaw** [bcit-ci/CodeIgniter#4796]
I'm not really sure if the issue comes from CodeIgniter or Ion_Auth library. Anyways, the form validation wasn't running even with all the fields written properly. What I did was to var_dump the $row field in Form_Validation->_execute method, and I discovered that the rules weren't trimmed properly. I added this lines to fix it (the method starts in line 567):

````
	// Line 567, File system/libraries/Form_validation.php
	protected function _execute($row, $rules, $postdata = NULL, $cycles = 0){

		foreach ($rules as $key => $value) {
			$rules[$key] = trim($value); // I think this line is not necessary, I left it though just in case
		}
		foreach ($row['rules'] as $key => $value) {
			$row['rules'][$key] = trim($value); // This is the necessary line to fix the bug
		}
		// The rest of the code goes here
	
	}

**Comment by narfbg** [comment]
This is not a bug.
See #3031.
