### ISSUE TITLE
Dirty code in system/core/Input.php

### ISSUE THREAD

**Issue by hamazaspavetisyan** [bcit-ci/CodeIgniter#4798]
In function "request_headers" there is line below. Better to have IF statement. Some editors give syntax error on that line.

			isset($_SERVER['CONTENT_TYPE']) && $this->headers['Content-Type'] = $_SERVER['CONTENT_TYPE'];

**Comment by narfbg** [comment]
Then those editors need to fix their linters.

**Comment by hamazaspavetisyan** [comment]
Good idea, Codeigniter is open source project, so we need to have code that corresponds to some coding standards, especially when using IF statement is actually is the same as using boolean expression as a statement.
