### ISSUE TITLE
parse error showing even when app is in production

### ISSUE THREAD

**Issue by avinashseth** [bcit-ci/CodeIgniter#4802]
**created error**
`class Bottle extends CI_Controller
{
     function a()
     {
          /
      }
}`

**error**
`Parse error: syntax error, unexpected '/' in /location/application/controllers/Bottle.php on line 11`

**index.php**
`define('ENVIRONMENT','production');`
`switch (ENVIRONMENT)
{
	case 'development':
		error_reporting(-1);
		ini_set('display_errors', 1);
	break;

	case 'testing':
	case 'production':
		ini_set('display_errors', 0);
		if (version_compare(PHP_VERSION, '5.3', '>='))
		{
			error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT & ~E_USER_NOTICE & ~E_USER_DEPRECATED);
        }
        else
        {
			error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_USER_NOTICE);
		}
	break;

	default:
		header('HTTP/1.1 503 Service Unavailable.', TRUE, 503);
		echo LOCALHOST ? 'The application environment is not set correctly.' : $oops_message;
		exit(1); // EXIT_ERROR
}`

**Comment by narfbg** [comment]
... not all errors are catchable.
