### ISSUE TITLE
Problem with stored procedure

### ISSUE THREAD

**Issue by abuhurairalakdawala** [bcit-ci/CodeIgniter#4809]
I have a stored procedure with update and select statements.

I used method below :
```
$this->db->trans_start();
$get = $this->db->query('CALL proc_name(?,?)',array(10,'random chars'));
// the procedure above have 2 update statements and 3-4 select statements
$this->db->trans_complete();
$result = $get->result();
```

My transaction is successful, I also get data from select statements, but the update statements never update my tables.

**Comment by narfbg** [comment]
And how did you determine that this is a CodeIgniter problem?

**Comment by abuhurairalakdawala** [comment]
same stored procedure is working with Core PHP and not working in CI.

**Comment by narfbg** [comment]
That's very broad ... *how exactly* do you do it with raw PHP?

**Comment by abuhurairalakdawala** [comment]
I have done the in the simplest way in mysqli below :

```
<?php 

  //connect to database
  $connection = mysqli_connect("localhost", "root", "password", "dbname");

  //run the store proc
  $result = mysqli_query($connection, "CALL my_proc(13,'1A3e21')") or die("Query fail: " . mysqli_error($connection));

  //loop the result set
  while ($row = mysqli_fetch_array($result)){   
      echo $row[0] . " - " . + $row[1]; 
  }

?>
```


... And it works correctly

but not with CI

**Comment by abuhurairalakdawala** [comment]
Sorry,
the problem is with PDO.
Its not working with transaction.

**Comment by narfbg** [comment]
What CI version are you using?

**Comment by abuhurairalakdawala** [comment]
CI 3.1.0

**Comment by abuhurairalakdawala** [comment]
And now things are working fine...
Before trans_start();
Below query to be executed...
`$this->db->query("SET AUTOCOMMIT=0");`

**Comment by narfbg** [comment]
That's the query executed by `trans_start()`? What do you mean before?

**Comment by abuhurairalakdawala** [comment]
The sequence must be like this..

```
$this->db->query("SET AUTOCOMMIT=0");
$this->db->trans_start();
$get = $this->db->query('CALL '.$name.'('.$params.')', $data);
$this->db->trans_complete();
$result = $get->result();
```

Otherwise its not working...

**Comment by abuhurairalakdawala** [comment]
One more thing is there a possibility in Codeigniter to fetch multiple select statements from stored procedure, since it is not executing the way I wrote in previous reply. 
The $get->result(); gets the first select statements result set only.

**Comment by narfbg** [comment]
Even if that was technically possible (which it isn't), there's no way for CodeIgniter to even know how many statements are executed by a stored procedure.

**Comment by AresAndy** [comment]
Hello,
I'm encountering the same problem still. If before the transaction start command one does not do 
```SET AUTOCOMMIT = 0```, it will fail complaining of calling autocommit() on boolean. I am not running a stored procedure, I'm trying to do lots of inserts in a safe manner. And even then, with the autocommit var set to zero, changes are not commited to DB. I don't know if it's a PDO problem, I only know my xdebug session will end up catching an exception in the driver folders supplied with CI.

Are we missing something?

**Comment by bistpuskar** [comment]
I have written in codeigniter and i got following error..Please help how to fix it
![screenshot from 2019-02-20 09-30-34](https://user-images.githubusercontent.com/47051640/53065074-3fe1bf80-34f2-11e9-8c8c-295f8b0c2350.png)

public function getuser($users_id){
			$get_user_stored_proc = "CALL get_user(?,?)";
			$query = $this->db->get_where($get_user_stored_proc,array('users_id'=>$users_id));
			return $query->row_array();
		}

		public function update_user($user, $users_id){
			$this->db->trans_start();
			$update_user_stored_proc = "CALL update_user(?,?)";
			$this->db->where($update_user_stored_proc, $users_id);
			$this->db->trans_complete();
			return $this->db->update('users', $user);
		}

**Comment by abuhurairalakdawala** [comment]
The way you called stored procedure is wrong.
You should do the following way:

```
$this->db->trans_start();
$this->db->query('CALL update_user(?, ?)', $params);
$this->db->trans_complete();
return $this->db->update('users', $user);
```
