### ISSUE TITLE
Name requirement of Controller and Model is different when extending core lib

### ISSUE THREAD

**Issue by dangyuluo** [bcit-ci/CodeIgniter#4811]
CI version: 3.1.0
PHP version: 7.0.4

I trying to extend the original CI_Controller and CI_Model to meet some of my demands. But when I do this, I found that the name requirement of extending these two core libraries is different from each other. 

First, I created a file called `MY_Controller.php` in `/application/core`, and then create a class whose name does not start with the default required `MY_`:
```php
class A_Controller extends CI_Controller {
public function __construct()
	{}
}
```

You see, though I did not meet the naming requirement (which can be seen here [Create Core Libraries](http://www.codeigniter.com/user_guide/general/core_classes.html#extending-core-class)) it actually works. 

But it behaves differently when extending CI_Model. If my `MY_Model.php` is like this:
```php
class A_Model extends CI_Model {
public function __construct()
	{}
}
```

Codeigniter will throw an error telling me that:
```Message: /var/www/application/core/MY_Model.php exists, but doesn't declare class MY_Model```

So is this is bug of Codeigniter, or are the naming strategies, or to say requirements, of extending CI_Controller and CI_Molde treated differently ?

**Comment by smallp** [comment]
CI treats extending CI_Controller and CI_Model differently. In CodeIgniter.php, it requires your MY_Controller.php file but don't check whether the class exist or not. However, in Loader.php, it requires your MY_Model.php file and checks whether the class exist or not. So, here shows the message.
