### ISSUE TITLE
Could db be protected?

### ISSUE THREAD

**Issue by fiddler0305** [bcit-ci/CodeIgniter#4812]
I don't want   $controller->model->db->method() valid
I want $model->db be protected,  only $model->db->method() valid
how to do?

**Comment by ajm113** [comment]
1. What in the world are you even attempting to accomplish? Assuming you want do [this](http://www.codeigniter.com/user_guide/general/models.html?highlight=models)? (First Example)
2. This is a bug tracker, not a discussion forum.
3. Register [here ](http://forum.codeigniter.com/) for CI usage inquiries.
