### ISSUE TITLE
CI_DB_driver::escape() - destroying opening sequences starting with %0, %1

### ISSUE THREAD

**Issue by Kyitrai** [bcit-ci/CodeIgniter#4815]
Strings passed to `$this->db->escape()` are losing the opening 2 to 3 characters if they happen to start with `%0` or `%1`. I believe [Line 1121 in system/database/DB_driver.php](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_driver.php#L1121) is the culprit, and may simply be missing the optional 'false' flag when being called. SQL is not url-encoded and so should not be destroying sequences such as `%00` ... `%08`, `%10`, etc.

```
$val = '*12*';
$val = str_replace('*', '%', $val);
$val = ' LIKE ' . $this->db->escape($val);
```

Result: `LIKE '%'`
Expected: `LIKE '%12%'`

**Comment by narfbg** [comment]
Every driver overrides that method.

**Comment by Kyitrai** [comment]
You might want to do a more thorough check. This is not the case with the mssql driver, which my application is utilizing. I can find no overrides of anything to do with `escape`.

**Comment by narfbg** [comment]
Indeed, you are correct.
