### ISSUE TITLE
Table Libraries clear()

### ISSUE THREAD

**Issue by 784238ddda92fee476352f3ccaa6cca2** [bcit-ci/CodeIgniter#4816]
Hi!.
Library system/Table is call method clear() but not clear $this->caption variable.

**Comment by gxgpet** [comment]
Yes, it appears to be a small bug.

Meanwhile a fix is released, use `->set_captation(NULL)` after `clear()`.

**Comment by narfbg** [comment]
**If** we agree that this is a bug, which I'm not convinced it is.

Your own pull request - #4826 - alters the documentation to say that `clear()` affects captions, which it currently doesn't.
