### ISSUE TITLE
default controller inside subfolder not working

### ISSUE THREAD

**Issue by webhacking** [bcit-ci/CodeIgniter#4829]
Currently i am using codeigniter3.

**Comment by webhacking** [comment]
http://stackoverflow.com/questions/30397000/default-controller-inside-subfolder-codeigniter-3-not-working

**Comment by narfbg** [comment]
Duplicate of #2849. There's a number of these, please use the search bar. 

What you did is report as a bug first, then google, and never searched if it hasn't already been reported here - this is completely backwards.

**Comment by narfbg** [comment]
... and as it turns out, **you** have made another duplicate of it 5 months ago: #4622
