### ISSUE TITLE
How can i remove cache files?

### ISSUE THREAD

**Issue by webhacking** [bcit-ci/CodeIgniter#4831]
I am trying to delete cache file and I get the error below

`Unable to delete cache file`

And here is my source codes on `My_Controller`

```
$this->output->cache(1);
$this->output->delete_cache();
```

**Comment by webhacking** [comment]
Current i am using Codeigniter3

**Comment by narfbg** [comment]
This is a bug tracker.

We don't answer such questions here.

Ask them on our [forums](http://forum.codeigniter.com) instead.
