### ISSUE TITLE
Reserved keyword 'numeric' as method name in Form_validation library - php7

### ISSUE THREAD

**Issue by simha95** [bcit-ci/CodeIgniter#4837]
I observed that in php7 'numeric' is reserved keyword for future use, but it is used as method name in **Form_validation** library. 
Right now there is no issue in php7.0 also, may be it can effect in further versions. Any thoughts about to avoid such keywords in further CI 3.x versions?

**Comment by narfbg** [comment]
Another new thing in PHP 7 is the context-sensitive lexer, which allows such keywords to be used for (in this case) function names, as that doesn't create a conflict with the language syntax.

What you can't use 'numeric' for is class names and possibly constants.

**Comment by simha95** [comment]
Thanks, just learnt about 'context-sensitive lexer'. :)
