### ISSUE TITLE
xmlrpc timeout

### ISSUE THREAD

**Issue by infinity0n3** [bcit-ci/CodeIgniter#4843]
I'm having problems with getting no_data error from xmlrpc. Thing is that the remote function can take a long time as it's connected to 3D pritner and controls it's operations. One of those atomic operations can take up to 100 seconds.
Timeout used in CI 3.0.0 xmlrpc (client) library only set's connection timeout but not read/write timeout.
Based on PHP manual (http://php.net/manual/en/function.fsockopen.php) one needs to add
stream_set_timeout($fp, $this->timeout) to avoid the request to use default timeout for read/write.

**Comment by narfbg** [comment]
@jim-parry I'm leaving this one up to you.

**Comment by jim-parry** [comment]
Issue confirmed. Working up a fix for it.

**Comment by infinity0n3** [comment]
Issue resolved in #4855 commit.
