### ISSUE TITLE
default validations are skipping when using callback model method

### ISSUE THREAD

**Issue by jangidgirish** [bcit-ci/CodeIgniter#4845]
**CI_VERSION: 3.1.0**
When i am using modal method in validation callback, the default validations are skipping, modal method is working fine, but _**required**_ default rule is skipping, 
```
 $validations = [
            [
                'field' => 'username',
                'label' => 'Username/email',
                'rules' => ['required', [
                          'vf_callable', [$this->user_model, '_validateForgotPassword']
                      ]
                 ]
            ]
        ];
        $this->form_validation
                ->set_rules($validations)
                ->set_error_delimiters('<span class="help-block">', '</span>');
        if ($this->form_validation->run() === TRUE) {
            
        }
```

**Comment by gxgpet** [comment]
You can check [here](https://www.codeigniter.com/userguide3/libraries/form_validation.html) if you are missing something. :)

There are a lot more people that can answer such questions on [forums](forum.codeigniter.com).

**Comment by jangidgirish** [comment]
yes, i implemented from tutorial [ref](http://www.codeigniter.com/user_guide/libraries/form_validation.html?highlight=form_validation#callable-use-anything-as-a-rule)

**Comment by gxgpet** [comment]
I understand. But my point here is that you should ask about your project's issue/problem questions on [forum](http://forum.codeigniter.com/); this section is strictly only for CI bugs/issues.

**Comment by jangidgirish** [comment]
hum, good idea, but it's is looking like bug, that's why i posted here.

**Comment by narfbg** [comment]
Can't reproduce.

Please *make sure* that something is a bug before posting it here. I know you thought it may be a bug, but I am telling you this for a reason - 9 times out of 10, "maybe" turns out to be "isn't".

**Comment by jangidgirish** [comment]
thanks for reply, sorry i didn't dig more before posting here, but i have founded something now
when i am using callback method in rules, like this
`['required', ['vf_callable', [$this->user, '_validateForgotPassword']]]`
then 
the form validation library `_prepare_rules` method is sending beside `trim`, `required` rules from callbacks rules, that's why the both rules are calling after callback rules
_prepare_rule() is returning
```
Array
(
    [0] => Array
        (
            [0] => vf_callable
            [1] => Array
                (
                    [0] => User Object
                        (
                        )

                    [1] => _validateForgotPassword
                )

        )

    [1] => required
)
```
i think, order should same what i have setup in controller

**Comment by narfbg** [comment]
That is an implementation detail, not something that you should care about at all.

I still don't see a problem here ...

**Comment by moscoquera** [comment]
i just faced with this "problem", you should reconsider respect the original rules order because the pipe/cascading concept is misleading if CI modifies rules order (calling callbacks first), in my case i need to run two custom rules (one rule is defined extending form_validation and the second one is a callback), i need my rules executing in an exact order to properly show errors to the users and don't confuse them.
