### ISSUE TITLE
Form Validation required with form_upload

### ISSUE THREAD

**Issue by sabist** [bcit-ci/CodeIgniter#4846]
form_upload is set required by Form validation lib  but always is false

**Comment by narfbg** [comment]
Elaborate please ... this tells us nothing.

**Comment by aanbar** [comment]
@sabist 
Form Validation does not validate file uploads, Usually when you validate a form you're checking $_POST array, but for file upload you'll have to check $_FILES array 

Form Validation does not have the ability to check both arrays at the same time, So you'll have to do it manually.
