### ISSUE TITLE
query binding a 0

### ISSUE THREAD

**Issue by ccd2008** [bcit-ci/CodeIgniter#4848]
Often when I input a 0 into the query binding it fails. It just continues to try and use the query while leaving that particular binding as a ? which of course fails. This was an error that occurred between version 2 and 3. I can only imagine it is as simple as being too loose of a conditional statement somewhere.

**Comment by narfbg** [comment]
Often? That's really vague ... please provide an example that we can reproduce it with.

**Comment by ccd2008** [comment]
$special = 0;
$this->db->query("SELECT * from companies where id = ?", $special);

That is basically all I need to drop into a function and it fails with this error:

A Database Error Occurred

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1

SELECT * from companies where id = ?

**Comment by narfbg** [comment]
This usage is not documented ... you should be passing an *array* containing values to bind.

**Comment by ccd2008** [comment]
Interesting. Pretty sure it used to be documentation at one point. It definitely worked flawlessly in codeigniter 2. All other values dropped in to that variable besides 0 or null will still work in codeigniter 3.

**Comment by narfbg** [comment]
I'm not saying it hasn't worked at some point, but it deffinately has never been documented.

dae08b59fd808c3baf838161223fdba2a80f1610
