### ISSUE TITLE
Path resolving issue

### ISSUE THREAD

**Issue by AmitMY** [bcit-ci/CodeIgniter#4849]
In `core/Codeigniter.php` lines 402, 408, there is a reference to this path:
`APPPATH.'controllers/'.$RTR->directory.$class.'.php'`
Normally, this works, but for users using custom loaders (like I use HVMC), it creates a problem on some machines.
It tries to access `application/controllers/../modules/countries/controllers/Countries/index`
Which on some machines translate correctly to `application/modules/countries/controllers/Countries/index`
And on some returns 404

A solution to that is using your own path resolver, something like:
Replace 402-408
```
function resolve_path($path) {
	$stack = [];
	foreach(explode('/', $path) as $segment)
		if($segment == "..")
			array_pop($stack);
		else
			$stack[] = $segment;
	return implode('/', $stack);
}
$controller_path = resolve_path(APPPATH.'controllers/'.$RTR->directory.$class.'.php');

if (empty($class) OR ! file_exists($controller_path))
{
	$e404 = TRUE;
}
else
{
	require_once($controller_path);
```

Any way, this is an issue needs addressing, I am confident I am not the first to encounter it

**Comment by narfbg** [comment]
Sorry, but we don't support HMVC. That's a third-party package that you're relying on and this is not an issue at all as far as we're concerned.

**Comment by AmitMY** [comment]
It is a loader extension.
If you allow extending the loader, you probably should support relative loading paths.

This is not an HMVC issue, but a loader issue

**Comment by narfbg** [comment]
Um, no ... this is something that you're arbitrarily calling a "loader issue", and you're making quite the stretch to reach that conclusion.

We allow (have provisions for) `CI_Loader` extensions, which deals with everything *but* controllers, which is very much intentional.
