### ISSUE TITLE
Having problems extending the migrations class

### ISSUE THREAD

**Issue by AmitMY** [bcit-ci/CodeIgniter#4850]
I need to add a method `show_diff($v1, $v2)` to the migration class.
You write
> You can extend native libraries.
> Note: The Database classes can not be extended or replaced with your own classes. All other classes are able to be replaced/extended.

As I normally do, I tried to extend `CI_Migration` in the `core` folder. When that did nothing, I created a library called `Migration.php` having `class MY_Migration extends CI_Migration`
This throws an error: `Fatal error: Class 'CI_Migration' not found in`

So I guess my questions are:
- Is there a way to resolve this, and extend the class?
- Is this class regarded as a "database class"?

Thanks

**Comment by gxgpet** [comment]
Hi :)

Please post this question on [forums](http://forum.codeigniter.com/).

As a note, you should name it `MY_Migration.php`, and not `Migration.php`. If this doesn't solve, better ask on forums.

**Comment by fanatikhamsi** [comment]
yes i try rename your file, 
its start with MY_
or 
change your config line $config['subclass_prefix'] = 'MY_';

**Comment by narfbg** [comment]
I see two things that you've done wrong, both directly violating what's explained in [the manual](https://codeigniter.com/userguide3/general/creating_libraries.html#extending-native-libraries).

(what you "normally do" isn't correct)

That being said, we use GitHub issues for bug tracking only. We don't provide general support here, you should ask for that on our [forums](http://forum.codeigniter.com/) instead.

@gxgpet @fanatikhamsi ... and as you tried to give tips while I'm writing this comment - please don't do that again. There's no point in telling people to ask for help on the forums if you'd be helping them from here.
