### ISSUE TITLE
db->call_function fails for all oci8 calls

### ISSUE THREAD

**Issue by zknightfsw** [bcit-ci/CodeIgniter#4853]
Because of the way call_function is setup, when you do $this->db->call_function() for the oci8 driver, all calls fail. More or less because there's no such function prefixed with oci8_...

I looked at the actual code behind and I see you guys already have a hack in for the postgres driver, but not for anything else. I feel like this function could use some changes, like an option to send your own prefix to it, instead of letting it automatically choose it based on your driver.

**Comment by narfbg** [comment]
That function is useless ... I don't know who or why put it there, it is surely way before I came in.

We may as well remove it, and hence - no point in trying to fix anything about it now.

**Comment by zknightfsw** [comment]
Well, unless you guys plan on adding mysqli_next_result to the mysqli driver, then this function does still serve some purpose.

**Comment by narfbg** [comment]
If you want to call `mysqli_next_result()`, you call `mysqli_next_result()`, not `db->call_function('next_result')` ... that's why I said it's useless.

**Comment by zknightfsw** [comment]
Oh....you mean calling mysqli_next_result($this->db->conn_id); outside of the driver? I get why you'd see it was useless.


Thanks.
