### ISSUE TITLE
DBFORGE "text" column creation/modification is buggy

### ISSUE THREAD

**Issue by AmitMY** [bcit-ci/CodeIgniter#4854]
If I try to create a new table with the following column, or modify the following column, it does not go well.
> {
>    "type": "text",
>    "constraint": "65535"
> }

Creates

> {
>    "type": "mediumtext",
>    "constraint": "16777215"
> }

I am not sure why it does that.

**Comment by narfbg** [comment]
You can't control the length of a "text" field ...

I have to ask you again, please go through our [forums](http://forum.codeigniter.com/) first and only come here when you are **absolutely 100% sure** that something is a bug.
