### ISSUE TITLE
Feature request: ability to disable mime check in Uploads library

### ISSUE THREAD

**Issue by infinity0n3** [bcit-ci/CodeIgniter#4856]
In do_upload function where the filetype is checked `is_allowed_filetype` there is no other way to disable the mime check then to modify the core library by changing `is_allowed_filetype()` to `is_allowed_filetype(TRUE)`.

This is needed for the following reason.
The _applications/config/mimes.php_ can be extended manually but we need it do be extended automatically by calling a helper from applications. When calling `$CI =& get_instance();` from mimes.php it breaks down as in _get_mimes()@core/Common.php_ it uses `include(...'/mimes.php')` and maybe therefore has not access to CI instance.
Allowed_types can be passed to uploads library from anywhere so they can be easily generated.
However I don't see mimes.php can call a helper function. Maybe I'm not seeing something or doing something wrong. In which case I apologize for the fuss.  

If this is too much to change then a quick fix would be to allow uploads library to disable mime check from `__construct($config)` as `is_allowed_filetype` already has been programmed to do support this.

**Comment by AmitMY** [comment]
> Please note that GitHub is not for general support questions! If you are having trouble using a feature of CodeIgniter, ask for help on our forums instead.
> 
> If you are not sure whether you are using something correctly or if you have found a bug, again - please ask on the forums first.

The correct place for CI 3 feature requests is the [CI 3 Forum]( http://forum.codeigniter.com/forum-17.html)

**Comment by narfbg** [comment]
@infinity0n3 Actually, there already **is** a way to disable the server-side mime check and it is documented.

**Comment by infinity0n3** [comment]
"detect_mime" only disables mime [detection](https://github.com/bcit-ci/CodeIgniter/blob/3.0-stable/system/libraries/Upload.php#L452) not mime checking.
Mime checking is done in [is_allowed_filetype](https://github.com/bcit-ci/CodeIgniter/blob/3.0-stable/system/libraries/Upload.php#L885) in do_upload however ignore_mime parameters is by default fixed to FALSE as there is [not parameter](https://github.com/bcit-ci/CodeIgniter/blob/3.0-stable/system/libraries/Upload.php#L464) supplied.

**Comment by narfbg** [comment]
That's how type-restrictions work, it wouldn't make sense any other way. If you don't want to check file types, you just don't put restrictions on them.

That there's an unused parameter may be a minor annoyance, but nothing else really.

**Comment by infinity0n3** [comment]
Agree that disabling type checking completely is a way. And I get it, this is not the forum (have check there already, all of the posts).

Just simple, from person to person. Is it possible to populate mimes in mimes.php dynamically in a proper CI way by using helpers as described in the beginning of this issue?
After this I'm letting it go and go with a workaround.

**Comment by narfbg** [comment]
"Person to person" is even worse than coming here for general support questions ... this is a public space. But no, there's no way to do that with the limitations you've put on it.

**Comment by infinity0n3** [comment]
Thanks...
