### ISSUE TITLE
Form_validation set_rules documentation

### ISSUE THREAD

**Issue by dafriend** [bcit-ci/CodeIgniter#4858]
The class reference [documentation for set_rules](http://www.codeigniter.com/user_guide/libraries/form_validation.html#CI_Form_validation::set_rules) does not mention the optional fourth parameter $errors.

The use of the fourth param is used in at least once - in the "Setting Error Messages" section's example.
This example might be a good place to mention the fourth param more explicitly.

**Comment by narfbg** [comment]
6513701f21e72fadbbadc4bfea501dd871fa5149
