### ISSUE TITLE
auto_loading model and library problem

### ISSUE THREAD

**Issue by hsali** [bcit-ci/CodeIgniter#4870]
I have changed the line in autoload.php file. I am trying to call the this model in my controller. This is not working. 
     $autoload['model'] = array("M_functions"=>"function");

If I call this model in the controller manually. It works fine.

     $this->load->model("M_functions","function");

## Error 

`
A PHP Error was encountered

Severity: Notice

Message: Undefined property: Diagnose::$function

Filename: controllers/Diagnose.php

Line Number: 21

Backtrace:

File: /var/www/html/hfs/application/controllers/Diagnose.php
Line: 21
Function: _error_handler

File: /var/www/html/hfs/index.php
Line: 315
Function: require_once
Fatal error: Call to a member function password_generator() on null in /var/www/html/hfs/application/controllers/Diagnose.php on line 21
A PHP Error was encountered

Severity: Error

Message: Call to a member function password_generator() on null

Filename: controllers/Diagnose.php

Line Number: 21

Backtrace:
`

I have function name password_generator() in the M_functions model.  Same thing is happening for libraries also. I have manually load the session, form_validation library. 

###For input library. 

    $autoload['libraries'] = array('database','../core/input','encrypt');

I have  to call the library like this. If I was trying to call without relative path. input library is also not working.

I have CodeIgniter 3.1.0. I have compared my Loader.php file with latest developed branch and 3.1.0 branch file. Both are same. 
someone suggest this[ solution. ](https://github.com/bcit-ci/CodeIgniter/issues/3733)

**Comment by hsali** [comment]
when I try to autoload the library session. 

I have this error. 

Unable to locate the specified class: Session.php

**Comment by hsali** [comment]
Due to autoloading problem. I am unable to load the use hooks in my application properly.

**Comment by narfbg** [comment]
Please post this on our [forums](http://forum.codeigniter.com/) instead, this is a bug tracker.

**Comment by hsali** [comment]
why don't you answer these kind of question which are related to bug.

**Comment by gxgpet** [comment]
@hsali When you have an error, it is not necessarily a bug :P that's why you should try on forums.

**Comment by hsali** [comment]
But, it's kind of bug. Because I have tried mostly answers. Those didn't work for me.
