### ISSUE TITLE
Using set_batch_update with expression error

### ISSUE THREAD

**Issue by gigkokman** [bcit-ci/CodeIgniter#4871]
Error message
```
Severity: Notice

Message: Undefined index: `ITEM_ID`

Filename: database/DB_query_builder.php

Line Number: 1947
```

My database configure

```
$db['default'] = array(
	'dsn'	=> '',
	'hostname' => 'localhost',
	'username' => 'user',
	'password' => 'pass',
	'database' => 'mydatabase',
	'dbdriver' => 'mysqli',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);
```

Update field value with expression.
```
$update = array(
    array('ITEM_ID'=>1, 'QUANTITY'=>'(QUANTITY-1)'),
    array('ITEM_ID'=>2, 'QUANTITY'=>'(QUANTITY-2)'),
 );
$this->db->set_update_batch($update, 'ITEM_ID', FALSE);
$this->db->update_batch('ITEM', NULL, 'ITEM_ID');
```

**Comment by narfbg** [comment]
Please test with the commit above.

**Comment by tianhe1986** [comment]
@narfbg  It seems that you made a mistake…… Maybe you need revert this fix.

@gigkokman 
I read your code and find your wrongly use.

your code 
```
$this->db->set_update_batch($update, 'ITEM_ID', FALSE);
$this->db->update_batch('ITEM', NULL, 'ITEM_ID');
```

should change to 

```
$this->db->set_update_batch($update, 'ITEM_ID');
$this->db->update_batch('ITEM', NULL, 'ITEM_ID');
```

In `update_batch()`,  it uses `$this->_protect_identifiers`,which default to be `TRUE`, to determine whether to do the escaping work .	, .

And your code, with the `FALSE` param,  force it not escaping. So if your `$this->_protect_identifiers` is `TRUE`, they come into conflict.

My suggestion is just using

`$this->db->update_batch('ITEM', $update, 'ITEM_ID');`

**AND DO NOT USE `$this->db->set_update_batch(XXX)`**

**Comment by narfbg** [comment]
@tianhe1986 Yea, know.

But @gigkokman's usage is not incorrect, even if very rare.
