### ISSUE TITLE
Can't set url_suffix with $this->config->set_item()

### ISSUE THREAD

**Issue by usmanahmed** [bcit-ci/CodeIgniter#4872]
In my project, I have set configurations in MY_Controller like:
$this->config->set_item('base_url', 'http://www.example.com');
$this->config->set_item('url_suffix', '.html');

When I set the url_suffix inside config.php, CodeIgniter ignores url_suffix which is the right behavior. If the path is http://www.example.com/controller/method/some_link.html, CodeIgniter only gets the some_link. not .html. That's fine.

But when I set url_suffix with $this->config->set_item('url_suffix', '.html');, CodeIgniter doesn't ignore .html and gets full some_link.html, which is not the right behaivior.

**Comment by narfbg** [comment]
What you want is the *impossible* behavior.

**Comment by narfbg** [comment]
Also, we don't like [double posting](http://forum.codeigniter.com/thread-66467.html).
