### ISSUE TITLE
mssql_connect vs sqlsql_connect

### ISSUE THREAD

**Issue by Fcases** [bcit-ci/CodeIgniter#4873]
since php 5.4+ are dropping mssql_connect, can we expect a driver for sqlsrv_connect ?

**Comment by narfbg** [comment]
I don't remember a time where we didn't have one ... you could've at least checked.

**Comment by Fcases** [comment]
i did, all the versions i see in the mssql_driver.php it's regarding mssql_connect,

**Comment by Fcases** [comment]
sorry your right.. a big doh
