### ISSUE TITLE
session sid_regexp in error length

### ISSUE THREAD

**Issue by RicherYang** [bcit-ci/CodeIgniter#4874]
CI 3.1.1 set the session ID must at less length 40 letter.( _sid_regexp )

But when hash_function = 1 (SHA1) the session_id() is 160-bit digest.
when hash_bits_per_character = 4 it goto 40 char
when hash_bits_per_character = 5 it goto 32 char
when hash_bits_per_character = 6 it goto 27 char

**Comment by narfbg** [comment]
Please test to see if 2f760877c313871e5066b93b0b1aa76428c09fb6 really fixes this.

**Comment by RicherYang** [comment]
that can't fix the `_sid_regexp` error.
BUT I get a new error " Notice: Undefined variable: bits "

My system is php 7.0.11 ( `PHP_VERSION_ID 70011` )
in php.ini set `session.hash_function = 1` and `session.hash_bits_per_character = 5`

in the fix use `$sid_length = $bits * $bits_per_character;` to calculate the sid length.
may change to `$sid_length = (int) ceil($bits / $bits_per_character);`

**Comment by narfbg** [comment]
How about now?

**Comment by RicherYang** [comment]
It work nice on my system.

**Comment by narfbg** [comment]
Great, thanks.
