### ISSUE TITLE
Form validation callback gets called two times

### ISSUE THREAD

**Issue by JoonasC** [bcit-ci/CodeIgniter#4876]
I found a problem, where a form validation callback gets called two times.
Link to stackoverflow thread: http://stackoverflow.com/questions/40252540/codeigniter-form-validation-callback-gets-called-two-times

**Comment by JoonasC** [comment]
@narfbg could you tell me why you closed this? Also i have added a simpler version of the code on stackoverflow.

**Comment by narfbg** [comment]
This may sound rude, but if you can't be bothered to do anything more than a SO link, I can't be bothered to explain my actions either.

**Comment by JoonasC** [comment]
@narfbg Oh, sorry about that. I'm going to post a new issue, once i've done some more research on the problem.
