### ISSUE TITLE
form_validation rule with "matches[]" needs "required" to work

### ISSUE THREAD

**Issue by jjvdgeer** [bcit-ci/CodeIgniter#4879]
I am in the process of upgrading CodeIgniter from 2.2.6 to 3.0.6.

I have a form to edit user-data. It has 2 passwordfields, the idea being that if they're left empty, the users password is not changed. However, if they're filled out, they must be identical. I have the following rules for that:

```php
$this->form_validation->set_rules('password', 'Password', '');
$this->form_validation->set_rules('passconf', 'Confirm password', 'matches[password]');
```

This worked fine under 2.2.6, but it is not working under 3.0.6. It reports the passwords are not identical even if they are. If both are left empty, it validates and therefore works, though.

I found I could resolve the validation problem of them supposedly not being equal by setting the rule to required:

```php
$this->form_validation->set_rules('password', 'Password', 'required');
```

But this has the unwanted effect that you now always have to change the password as well, which is not what I want.

**Comment by narfbg** [comment]
It doesn't need the 'required' rule, you just need to have *some* rule set on both fields - defining a field to be validated, but then setting no validation rules for it makes no sense. It's more likely a programmer's error than anything else, and hence why it fails.

See #3736 for more info.

**Comment by jjvdgeer** [comment]
OK, then I can have a workaround. Still feel that it is strange, because if I remove the set_rules call for the password-field, then it still fails. I can accept that trying to set the rules to empty is not supported, but it still does not work if I don't try to set those rules at all.

**Comment by narfbg** [comment]
... that's the same thing.

**Comment by jjvdgeer** [comment]
OK, so I now set it to callback_dummy_rule and have a dummy_rule that returns TRUE always. It works...

Hm, I suppose I could set a minimum-length as well. Didn't require that before, and I'm not really very interested to set that kind of limits, but they don't hurt, so I'll go for that instead.
