### ISSUE TITLE
Update notifier for critical security/bug fixes

### ISSUE THREAD

**Issue by JoonasC** [bcit-ci/CodeIgniter#4880]
Hello, right now there isn't any kind of update checking functionality in codeigniter.
There could at least be a notifier for critical security/bug fixes, e.g mysql injection,xss,csrf,etc...
Right now you're supposed to wait until the next build of codeigniter comes out, and as a result a lot of apps using ci can be hacked within the timespan it takes to the next build...
Also, you'd have to regularly check the ci website for a new build, and some people don't do that so a notifier would be useful.
Also @narfbg could you address the issue #4876 that you closed without explanation?
Thanks

**Comment by gxgpet** [comment]
@JoonasC Check [this](https://www.codeigniter.com/userguide3/contributing/index.html?highlight=contribute#tips-for-a-good-issue-report). You should post helpful information about an issue, such as steps to reproduce, what happened/what did you expect to happen, error messages etc. Sharing a Stackoverflow entry won't help detecting and fixing the issue. Do it on your own. :)

Also, this one, #4880, is not addressing any issue...

**Comment by JoonasC** [comment]
@gxgpet yes, this is an improvement request. #4876 is an issue i ran into.

**Comment by gxgpet** [comment]
@JoonasC #4876 is a link to a Stackoverflow post, not an issue report. :P

**Comment by narfbg** [comment]
Sorry, but we can't make announcements for anything but new releases (or what you call "builds").
