### ISSUE TITLE
URI Routing bug!

### ISSUE THREAD

**Issue by Epexa** [bcit-ci/CodeIgniter#4882]
### If add to existing function any URI segment in URL without routes.php not shown error 404!

**I download version 3.1.1, extract and run! Default Welcome controller! No modifications!**

Example controller "**Welcome**", function "**index**".
http://site/index.php/ - ok!
http://site/index.php/welcome/ - ok!
http://site/index.php/welcome/index/ - ok!
**http://site/index.php/welcome/index/dawd/dawdaw/dawd - ok!!! Why? In version 3.1.0 shown error 404!**

**Comment by narfbg** [comment]
3.1.0 did the same thing, as did all past versions too.

**Comment by gxgpet** [comment]
Actually, on 3.1.0 this is not really happening ... Just tested right now.

**Comment by gxgpet** [comment]
Update: it looks like this is occurring while you are writing in URL the method as well. For instance, the example provided by @Epexa won't trigger if you remove `index` from URL. And yes, it is happening in 3.10 as well.

**Comment by narfbg** [comment]
There's no "3.10".

**Comment by Epexa** [comment]
@gxgpet  Yes, i checked all 3.x versions, it is happening also!

Example if rename "index" function to "test" function, it's still going on!

http://site/index.php/welcome/**test**/dawd/dawdaw/dawd

It is possible somehow disable ?

**Comment by Epexa** [comment]
@narfbg Is this correct logic? Endless links if do not use routes.php.

**Comment by Epexa** [comment]
Please check URL http://www.codeigniter.com/docs/index/why/its/happens/it/wrong/logic - it work ok!

**Comment by narfbg** [comment]
@Epexa ...

It's not "wrong logic", it's how it has *always* worked.
It's not a bug and there's no way around it if you don't declare your routes manually.
It won't change.

Please don't turn this into a chatroom.

**Comment by Epexa** [comment]
@narfbg Ok, thanks!

**Comment by gxgpet** [comment]
@narfbg I've missed a "." ... :)
