### ISSUE TITLE
SQL Error on Where Statement when Using Query Builder Class

### ISSUE THREAD

**Issue by imbagila** [bcit-ci/CodeIgniter#4884]
First of all I'm sorry for my bad English and I'm new in github so is gonna be long and probably bad post here.

So first I use this code to show the number of rows :
```
// Query
$this->db->select();
$this->db->from('tb_bosp, tb_siswa, tb_kelas');
$this->db->where('tb_bosp.nis = tb_siswa.nis');
$this->db->where('tb_siswa.id_kelas = tb_kelas.id_kelas');
$this->db->where('id_thn_ajar', $thn_ajar);
$this->db->where('tingkat', $tingkat);
$this->db->where('bulan_bosp', date('m'));

// Get query
$query = $this->db->get();

// Return query
return $query->num_rows();
```
(`$thn_ajar` and `$tingkat` value is on parameter function)

And then I got this error :
> Error Number: 1064
> 
> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`NULL` AND `tb_siswa`.`id_kelas` = `tb_kelas`.`id_kelas` AND `id_thn_ajar` = '1'' at line 3
> 
> SELECT * FROM `tb_bosp`, `tb_siswa`, `tb_kelas` WHERE `tb_bosp`.`nis` = `tb_siswa`.`n IS NOT` `NULL` AND `tb_siswa`.`id_kelas` = `tb_kelas`.`id_kelas` AND `id_thn_ajar` = '1' AND `tingkat` = 'X' AND `bulan_bosp` = '10'
> 
> Filename: E:/Program Files/xampp/htdocs/akua/codeigniter/database/DB_driver.php
> 
> Line Number: 691

After that I go to CodeIgniter system folder and open this file :
Location : `my_project_folder/codeigniter/database/DB_driver.php`
( I was changed my system folder name to codeigniter)

I try to remove this and it works (no error showing) :
```
682. elseif (preg_match('/\s*(!?=|<>|IS(?:\s+NOT)?)\s*$/i', $k, $match, PREG_OFFSET_CAPTURE))
683. {
684.   	$k = substr($k, 0, $match[0][1]).($match[1][0] === '=' ? ' IS NULL' : ' IS NOT NULL');
685. }
```
But I undo that instead because when I remove that codes I realize that is gonna be error in future on my project. So the last option I should change my model code into this, and it works :
```
// Query
$query =	'SELECT * ';
$query .=	'FROM tb_bosp, tb_siswa, tb_kelas ';
$query .=	'WHERE tb_bosp.nis = tb_siswa.nis ';
$query .=	'AND tb_siswa.id_kelas = tb_kelas.id_kelas ';
$query .=	'AND id_thn_ajar = "' . $thn_ajar . '" ';
$query .=	'AND tingkat = "' . $tingkat . '" ';
$query .=	'AND bulan_bosp = "' . date('m') . '"';

// Get query
$query = $this->db->query($query);

// Return query
return $query->num_rows();
```
Note : Error showing because this code : `$this->db->where('tb_bosp.nis = tb_siswa.nis');`
This is a bug or just my code is wrong?

**Comment by rougin** [comment]
You should this post in the [forums](http://forum.codeigniter.com/) instead here in order to get help.

**Comment by narfbg** [comment]
@rougin That's not an automatic reply we give to everybody. Some people do come here with legitimate bug reports.
