### ISSUE TITLE
Codeigniter form validation library, callback methods get called more than set

### ISSUE THREAD

**Issue by JoonasC** [bcit-ci/CodeIgniter#4885]
So i ran into this problem, i'm using codeigniter form validation library and i want some callback rules to execute after other callback rules. When i tried to do this i noticed the earlier callback methods that had been called first were called a second time when the second `form_validation->run()` check was running. This caused the form validation to return false, even though all the data entered was correct. I decided to test the issue with this bugtest code:
```
<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Bugtest extends CI_Controller
{
	function dosomething()
	{
		$this->load->library("form_validation");
		$this->form_validation->set_rules("test1", "test1", "required|callback_test1");
		$this->form_validation->set_rules("test2", "test2", "required|callback_test2");
		$this->form_validation->set_rules("test3", "test3", "required");
		if($this->form_validation->run() === FALSE)
		{
			exit("fail1|".validation_errors());
		}
		else
		{
			echo "success1|";
			$this->form_validation->set_rules("test3", "test3", "callback_test3");
			if($this->form_validation->run() === FALSE)
			{
				exit("fail2|".validation_errors());
			}
			else
			{
				exit("success2");
			}
		}
	}
	function test1($test1)
	{
		echo "call|";
		return TRUE;
	}
	function test2($test2)
	{
		echo "call2|";
		return TRUE;
	}
	function test3($test3)
	{
		echo "call3|";
		return TRUE;
	}
}
?>
```
When i run this i get: `call|call2|success1|call|call2|call3|success2`, which means that the previous rules are getting checked too.
Am i just doing it wrong, or is there a bug in codeigniter? Is there a way to check rules after other rules?
Thanks

**Comment by narfbg** [comment]
You are doing it wrong, indeed.

Also, please note that this is a bug tracker. Unless you're 100% sure that something is a bug, post it on our [forums](http://forum.codeigniter.com/) instead.
