### ISSUE TITLE
Image library doesn't work with Imagemagik in CI >=3.1.0

### ISSUE THREAD

**Issue by monsterlane** [bcit-ci/CodeIgniter#4902]
https://github.com/bcit-ci/CodeIgniter/issues/4736

Your fix does not work. You forgot to include the space at the start of the line.

https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Image_lib.php#L889

Should be:

`$cmd .= ' '.escapeshellarg($this->full_src_path).' '.escapeshellarg($this->full_dst_path).' 2>&1';`

**Comment by narfbg** [comment]
... and your feedback is 3 months late. :)

**Comment by monsterlane** [comment]
Well you could have just copy and pasted what I wrote the first time ;)

**Comment by narfbg** [comment]
I don't do "copy-paste development" ...

**Comment by monsterlane** [comment]
That's a funny excuse for not testing your code :P

**Comment by narfbg** [comment]
Yea ... good luck having an environment covering ALL of CI. :)
