### ISSUE TITLE
Documentation for set_cookie clarification

### ISSUE THREAD

**Issue by richardwo** [bcit-ci/CodeIgniter#4904]
Documentation at https://codeigniter.com/user_guide/libraries/input.html#CI_Input::set_cookie could do with clarification.
It says 'Only the name and value are required.' technically this is true however a cookie isn't created in the browser unless a value for expire is provided as well.

Line 401 of system/core/Input.php checks expiry date and sets a past date if its not numeric. Although this cookie header is sent down to the browser - the browser won't create a cookie that's already expired.

**Comment by narfbg** [comment]
Unfortunately, this isn't just about documentation.

Calling `set_cookie()` *without* explicitly passing an expiry time shouldn't result in the cookie being deleted. Fixing the behavior would be a BC break though, so we'll have to address this in 3.2.0.
