### ISSUE TITLE
insert code 

### ISSUE THREAD

**Issue by dayrui** [bcit-ci/CodeIgniter#4906]
`$code = "my code '\CodeIgniter\Autoloader\'";
        $this->db->table('test')->insert([
            'text' => $code
        ]);`

this database result:
`my code 'CodeIgniterAutoloader'`
\
It's gone.

**Comment by narfbg** [comment]
Wrong place, you're looking for the CodeIgniter4 repo.
But also, it's very unclear what you're trying to say. Try to explain it better when you report it there.
