### ISSUE TITLE
CURLRequest.php have a bug maybe?  Look at the following.

### ISSUE THREAD

**Issue by jayson755** [bcit-ci/CodeIgniter#4907]
> It's on the 660 line.

`  if (! empty($config['form_params']) && is_array($config['form_params']))
		{
			$curl_options[CURLOPT_POSTFIELDS] = http_build_query($config['form_params']);

			if (empty($this->header('Content-Type')))
			{
				$this->setHeader('Content-Type', 'application/x-www-form-urlencoded');
			}
		}`
_$this->header(), but without this method in this class, This is write wrong?_

**Comment by lonnieezell** [comment]
First off - wrong repo. This is the repo for CI3 and the bug you're reporting should be reported in the [CI4 repo](https://github.com/bcit-ci/CodeIgniter4). 

Second - nope. Not a bug. CURLRequest extends other classes which is where that method can be found.
