### ISSUE TITLE
About base_url() when using Ajax

### ISSUE THREAD

**Issue by liubusian** [bcit-ci/CodeIgniter#4909]
Hi,
Now, `base_url()` will get the `$_SERVER['SERVER_ADDR']`
see system/core/Config.php line 95
[https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/Config.php#L95](url)

```php
if (empty($this->config['base_url']))
{
	if (isset($_SERVER['SERVER_ADDR']))
	{
		if (strpos($_SERVER['SERVER_ADDR'], ':') !== FALSE)
		{
			$server_addr = '['.$_SERVER['SERVER_ADDR'].']';
		}
		else
		{
			$server_addr = $_SERVER['SERVER_ADDR'];
		}
			$base_url = (is_https() ? 'https' : 'http').'://'.$server_addr
					.substr($_SERVER['SCRIPT_NAME'], 0, strpos($_SERVER['SCRIPT_NAME'], basename($_SERVER['SCRIPT_FILENAME'])));
		}
		else
		{
			$base_url = 'http://localhost/';
	}

	$this->set_item('base_url', $base_url);
}
```

but in old version:

```php
if (empty($this->config['base_url']))
	{
		// The regular expression is only a basic validation for a valid "Host" header.
		// It's not exhaustive, only checks for valid characters.
		if (isset($_SERVER['HTTP_HOST']) && preg_match('/^((\[[0-9a-f:]+\])|(\d{1,3}(\.\d{1,3}){3})|[a-z0-9\-\.]+)(:\d+)?$/i', $_SERVER['HTTP_HOST']))
		{
			$base_url = (is_https() ? 'https' : 'http').'://'.$_SERVER['HTTP_HOST']
					.substr($_SERVER['SCRIPT_NAME'], 0, strpos($_SERVER['SCRIPT_NAME'], basename($_SERVER['SCRIPT_FILENAME'])));
		}
		else
		{
			$base_url = 'http://localhost/';
		}

		$this->set_item('base_url', $base_url);
	}
```
when I use Ajax, I get error:

> 'Access-Control-Allow-Origin' header is present on the requested resource. Origin

because 'HOST' are different from 'IP Address'
even if the 'host' direction the same ip.

having idea? I think that using `$_SERVER['HTTP_HOST']` is better than `$_SERVER['SERVER_ADDR']`.

sorry, my english is too bad.

Thanks.

**Comment by bkpandeymca** [comment]
You are requesting ajax from some other host, i think may be you are requesting from an hybrid app. that is why the issue is occurring, in default servers do not allow cross origin requests 

Enable CORS from Server by .htaccess file if you are using Apache, for nginx use config file of nginx.

for apache add
**Header set Access-Control-Allow-Origin "*"**

in .htaccess and restart the server.

for nginx

http://enable-cors.org/server_nginx.html

**Comment by narfbg** [comment]
No, **don't** set allow-origin to `*` - that would beat the entire purpose of CORS.

Do configure your `base_url`, don't rely on auto-detection.

Also, this is a bug tracker. Unless you have a bug to report, please post on our [forums](http://forum.codeigniter.com/) instead.
