### ISSUE TITLE
Fatal error mongodb with Codeigniter

### ISSUE THREAD

**Issue by jamipraveeen** [bcit-ci/CodeIgniter#4913]
Please help me in solving this problem
Fatal error: Uncaught Error: Call to undefined method Mongo_db::_show_error() in C:\xampp\htdocs\arcane\application\libraries\mongo_db.php:11 Stack trace: #0 C:\xampp\htdocs\arcane\system\core\Loader.php(1099): Mongo_db->__construct() #1 C:\xampp\htdocs\arcane\system\core\Loader.php(975): CI_Loader->_ci_init_class('mongo_db', '', NULL, NULL) #2 C:\xampp\htdocs\arcane\system\core\Loader.php(216): CI_Loader->_ci_load_class('Mongo_db', NULL, NULL) #3 C:\xampp\htdocs\arcane\application\controllers\templates\home.php(12): CI_Loader->library('mongo_db') #4 C:\xampp\htdocs\arcane\system\core\CodeIgniter.php(308): Home->__construct() #5 C:\xampp\htdocs\arcane\index.php(201): require_once('C:\\xampp\\htdocs...') #6 {main} thrown in C:\xampp\htdocs\arcane\application\libraries\mongo_db.php on line 11
![error page](https://cloud.githubusercontent.com/assets/20150985/20424596/bc6fc2b6-ad9c-11e6-9c4f-f8986389a305.png)

**Comment by jim-parry** [comment]
Mongodb is not a supported database. You should ask for help on forum.codeigniter.com.
