### ISSUE TITLE
function   nice_date in date_helper may have a bug

### ISSUE THREAD

**Issue by jiangshanmeta** [bcit-ci/CodeIgniter#4917]
for example ,when I use like this
```
nice_date('20161123','Y-m-d')
```

,what I want is 2016-11-23,but this function outputs 1970-01-01.

the original code for this case is:
```
if (preg_match('/^(\d{2})\d{2}(\d{4})$/i', $bad_date, $matches))
{
	return date($format, strtotime($matches[1].'/01/'.$matches[2]));
}
```

and I think the right code is 

```
if (preg_match('/^(\d{4})(\d{2})(\d{2})$/i', $bad_date, $matches))
{
	return date($format, strtotime($matches[1].'/'.$matches[2].'/'.$matches[3]));
}
```

**Comment by narfbg** [comment]
Indeed, thanks for reporting it - a commit containing the fix is referenced above.

However, PHP's advancements have made this function obsolete and I'm also [deprecating it now](610be9dc25bcfd06f30d70139701e86b8c3ad400). You can use this instead:

    DateTime::createFromFormat('Ymd', '20131123')->format('Y-m-d');
