### ISSUE TITLE
Combining UPDATE and LIMIT doesnt work

### ISSUE THREAD

**Issue by mykelaballe** [bcit-ci/CodeIgniter#4918]
CodeIgniter version: 3.0.6

I'm using Active Records. I only want to update a single record even though the WHERE matched multiple records. In order to achieve this as per stackoverflow, is to combine UPDATE and LIMIT. But it seems to not work on my side. It will still update all records based on the WHERE clause

![update limit](https://cloud.githubusercontent.com/assets/22584900/20550246/a0c2a2c4-b16e-11e6-8f8f-032438338f13.png)

**Comment by Seb33300** [comment]
Which database driver are you using?

The LIMIT on UPDATE is not available with all database drivers.
For instance, it is not available on postgreSQL and was disabled on theirs drivers:
https://github.com/bcit-ci/CodeIgniter/blob/67b40a561111a5a65faa245cd4c575e8d945cfb8/system/database/drivers/pdo/subdrivers/pdo_pgsql_driver.php#L307
https://github.com/bcit-ci/CodeIgniter/blob/67b40a561111a5a65faa245cd4c575e8d945cfb8/system/database/drivers/postgre/postgre_driver.php#L525

**Comment by narfbg** [comment]
Some things to do when reporting a bug:

- Make sure you're using the latest stable version. That is currently 3.1.2 (you're 3 versions behind) and ultimately it doesn't matter if there's a bug in 3.0.6.
- Show *code*, NOT screenshots. Images can be temporarily unavailable or entirely deleted from their location and are sometimes hard to render on e.g. mobile devices - that can't happen with text directly written here. Also, you can't copy-paste code from images ... this here is fairly simple, but if you had shown 50 lines of code in a screenshot, we'd have to waste a lot of time just re-typing your code.
- Provide all necessary details. We support a LOT of database platforms, different versions of them and often the PHP version also matters.
- Use the correct terms ... it's called "Query Builder", not "Active Records". It's hard to take a report seriously when it can't even label things right.

**Comment by danilobrinu** [comment]
@mykelaballe you use bad practice in coding. Its no a bugs, is your fault. Please read PSR to write good code.

**Comment by ivantcholakov** [comment]
FYI: http://www.sqlite.org/compile.html#enable_update_delete_limit

**Comment by almatins** [comment]
so, now we can update this issue status to: closed, maybe?
