### ISSUE TITLE
word_wrap always put a new line char to the end of the string

### ISSUE THREAD

**Issue by orionstar** [bcit-ci/CodeIgniter#4919]
word_wrap always put a new line char to the end of the string besides of the string is multibyte or not.

Tested with: CI 3.1.2 on Windows 8.1 PHP 5.6.17 and Debian 5.5.20

**Comment by narfbg** [comment]
```
$ grep -ri 'function word_wrap' *
system/helpers/text_helper.php:	function word_wrap($str, $charlim = 76)
system/libraries/Email.php:	public function word_wrap($str, $charlim = NULL)
```

... which one?

Why does it matter if it's a multibyte string or not?
Why is it a problem if it adds a newline?

**Comment by orionstar** [comment]
The one in the Text helper.

I didn't check the implementation sometimes multibyte causes problems with text related stuff so I mentioned it...

It is a problem because I parse the text further, line by line. I can solve a problem with a trim or with an array pop after I explode the string, but I think that new line char shouldn't be there in the first place.

**Comment by narfbg** [comment]
So it's a problem for your current, isolated use case. Is that the only reason you think it shouldn't be in there?

If you do look at the implementation, you'd see that the newline there is very much intentional. Why should that be changed for everybody else? Do you have any technical arguments for that?

**Comment by orionstar** [comment]
Yes, I created this issue, so it's my problem, you're right... and yes it's isolated beacuse it's the first time in the last 5 year or so when I need this specific function...

I don't have a "technical" reason, only some logical one...
Let's take a use case: you have word_wrap-ed string and then you want to print it out to a fixed size block... what do you do? nl2b (or something like that) but there is an extra new line after the text which isn't fit to the design...

**Comment by narfbg** [comment]
We can't make changes based on somebody's particular design ...
