### ISSUE TITLE
Extending CI_Exceptions

### ISSUE THREAD

**Issue by LeoMartinDev** [bcit-ci/CodeIgniter#4921]
Hello,
I'm trying to extend CI_Exceptions to use my view renderer.

MY_Exceptions (application/core):

```
class MY_Exceptions extends CI_Exceptions {

	public function __construct()
	{
	    parent::__construct();
	    $this->load->library('SOMELIBRARY');
	}
```
Output:

`Notice: Undefined property: MY_Exceptions::$load in `

How can I access the load method ?

**Comment by jim-parry** [comment]
This is a support question, for the forum and not github.
I see you have already asked it there.
