### ISSUE TITLE
Possible Image_lib bug

### ISSUE THREAD

**Issue by koichirose** [bcit-ci/CodeIgniter#4924]
I just noticed that there's a bug here:
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Image_lib.php#L889

The generated command ($cmd) is:
`/usr/bin/convert -quality 90 -resize 200x113'/path_to_source_img.jpg' 'path_to_dst_img.jpg'`

As you can see there's no space between the resize option and the path to source.
Adding a space fixes it: `$cmd .= ' '.escapeshellarg ...`

**Comment by narfbg** [comment]
Duplicate of #4902.
