### ISSUE TITLE
When call set_header() more than once, get_header() returns the first one

### ISSUE THREAD

**Issue by kenjis** [bcit-ci/CodeIgniter#4927]
```php
$this->output->set_header('Content-Type: application/csv; charset=UTF-8');
$this->output->set_header('Content-Type: text/html; charset=UTF-8');
var_dump($this->output->get_header('Content-Type'));
```

The result is `string(30) "application/csv; charset=UTF-8"`.
But the real Content-Type header is `text/html; charset=UTF-8`.

Is it a bug?

**Comment by narfbg** [comment]
Yes and no ...

It's uncommon to do this, but some headers are allowed to be sent multiple times. On the other hand, we don't check the second parameter of `set_header()` for that, and it should be what determines this behavior.

Ultimately, you shouldn't be doing this in the first place, but we can patch it still.

**Comment by kenjis** [comment]
We have the code like it. In a parent controller we set the default content-type, and only in a few controller classes we set another content-type.
The code works without any problem for the browser, but we get our test (which uses `get_header()` value) failed.

> but we can patch it still.

Okay, I will try to patch and send PR.

**Comment by narfbg** [comment]
Already did it myself, thanks.

**Comment by kenjis** [comment]
@narfbg Thanks!
