### ISSUE TITLE
Will there be any possible harm if I put exit; at the end of the index.php?

### ISSUE THREAD

**Issue by trungdq88** [bcit-ci/CodeIgniter#4933]
Apparently, requests to my CodeIgniter application can save up to **300ms** if I put `exit;` at the end of `index.php`.

```php
    /*
     * --------------------------------------------------------------------
     * LOAD THE BOOTSTRAP FILE
     * --------------------------------------------------------------------
     *
     * And away we go...
     */
    require_once BASEPATH.'core/CodeIgniter.php';

    /* End of file index.php */
    /* Location: ./index.php */

    exit; // <~~ save me ~300ms request time, from ~900ms to ~600ms
```

I know, it's weird, I can't think of any reasonable explanation for this. I'm on my way finding the answer and try to reproduce the behavior in an isolated environment. But in the meantime, in case there is any obvious reason that I am unaware of, I want to ask...

**Will there be any possible harm if I put exit; at the end of the index.php in CodeIgniter 3.0?**

**Comment by narfbg** [comment]
This sounds really fishy.

But regardless, you should post such things on our [forums](https://forum.codeigniter.com/) instead. This is a bug tracker.
