### ISSUE TITLE
Can we extend email protocols other than sendmail and smtp to Mail APIs

### ISSUE THREAD

**Issue by iamchathu** [bcit-ci/CodeIgniter#4934]
Is there any way to extend email class's protocol other than sendmail and SMTP?

So we can change protocol to MailGun or SendGrid APIs and send the mail via APIs

**Comment by narfbg** [comment]
This is a bug tracker, we don't answer such questions here.
Please post on our [forums](https://forum.codeigniter.com/) instead.
