### ISSUE TITLE
codeigniter compatiblity with php 

### ISSUE THREAD

**Issue by DBARUNNER** [bcit-ci/CodeIgniter#4936]
is codeigniter 2.2.6 compatibl with php 5.6.6 ? i have used codeigniter 2.2.6 with php 5.5 it work fine for me now i want to migrate from PHP  5.5 to  PHP 5.6.6 ifraid if not support because many my MIS is based on codeigniter 2.2.6

**Comment by narfbg** [comment]
CodeIgniter 2.x is abandoned since October 2015. Don't use it.

Also, this is a bug tracker. If you have questions, please post them on our [forums](https://forum.codeigniter.com/) instead.

**Comment by chalchis** [comment]
On my test server php 5.6.2
I have not had problems with IC 2.2

**Comment by narfbg** [comment]
This is not a forum board.
