### ISSUE TITLE
CI_Migrations and PDO db driver

### ISSUE THREAD

**Issue by NeoLegends** [bcit-ci/CodeIgniter#4939]
I'm migrating an old CI 2.0-Codebase to CI 3.1 and I'm having issues with the PDO MySQL DB driver.

We have auto latest migration enabled and whenever `CI_DB_pdo_mysql_driver->list_tables` is executed, an error occures telling me that the database has not been selected. Seems like a missing call to 
`$driver->db_select()` or something.

PS: When I change the SQL generated in `CI_DB_pdo_mysql_driver->list_tables` from 
```sql
$sql = 'SHOW TABLES';
```
 to
```sql
$sql = 'SHOW TABLES FROM '.$this->escape_identifiers($this->database);
```
things start to work again until the first real DB query, where the same error with the missing selected DB occurs. Can somebody confirm (or / and fix) this?

**Comment by NeoLegends** [comment]
Things do work, if I include a `dsn`-string, with hostname _and_ database name. Specifying only one attribute in the DSN-String doesn't work. It also stops working with the error above, if I add the DSN string and remove the entries for the DB and host name from the settings hash (as far as I understand this, it should still work, because the information is now in the DSN string).

**Comment by narfbg** [comment]
... yes, either use the DSN or not. Can't combine.

Please note that this is a bug tracker, you shouldn't open issues first and debug later. For generic questions like this one, you can post on our [forums](http://forum.codeigniter.com/) instead.
