### ISSUE TITLE
Ci framework will be lost under the php7.1 session.

### ISSUE THREAD

**Issue by yuwenlong** [bcit-ci/CodeIgniter#4940]
Ci framework will be lost under the php7.1 session.
Different controllers, session_id will be different.
`$config['sess_driver'] = 'files';`

In the php7.0. * Environment, there is no such problem.

**Comment by narfbg** [comment]
No it won't.

**Comment by yuwenlong** [comment]
Yes, I just finished testing

**Comment by yuwenlong** [comment]
@narfbg Yes, I just finished testing

**Comment by narfbg** [comment]
Well, if you believe you've found a problem - share the details with us.

Spooky-sounding titles like "CI framework will be lost" helps nobody.

**Comment by visuttaja** [comment]
I did some Xdebugging and found that session variables get forgotten between calls.
Windows 10 .This was between Apache 2.4.25 php 7.1.4 and 'CI_VERSION', '3.0.5'. I don' t know who is to blaim.
Two CI sites had same behaviour.
Settings ? PHP?CI? even XDebug??Apache?! I have no clue but then when I roll back to these:
php-5.6.30-Win32-VC11-x64
php_xdebug-2.5.1-5.6-vc11-x86_64.dll
everything seems to be back on the track.
