### ISSUE TITLE
set_value for a multiselect uses $default, on form error, when everything in the multiselect was previously unchosen

### ISSUE THREAD

**Issue by emilebourquin** [bcit-ci/CodeIgniter#4946]
I'm an old-school 2.x CodeIgniter user, in which set_value for a multiselect did not work at all, so kudos on getting set_value working for multiselect.

I have an edit-user form in which there is a non-required host_owner multiselect. When I open the user for edit, and unchoose any default-chosen host_owners, and the form encounters an error upon submit, the default host_owners are still selected, because, of course, when a multiselect with nothing selected is POST'ed , nothing is actually POST'ed, much like an unchecked checkbox. Since nothing is POST'ed, the default $default_host_owners takes over. I need to be able to unselect all host_owners, and have that stick upon form errors.

To clarify:
1) Click to edit a user
2) host_owners[] multiselect has $default_host_owners selected
2) Unselect all values of the host_owners[] multiselect
3) Fail to fill out a required textbox, or some such error
4) Click submit
5) host_owners[] multiselect is back to having $default_host_owners selected

Here's the line from the form:

`<?= form_multiselect('host_owners[]', $host_owners, set_value('host_owners[]', $default_host_owners), 'id=inputHostOwners class="multiselect-host_owners" size="10"'); ?>`

I've come up with a workaround in the controller to set $default_host_owners to NULL if $this->input->post() is true, but I also have a tentative fix for the form_helper's set_value function that I want to run by you;

line 697 of system\helpers\form_helper.php (set_value function) is currently:

`isset($value) OR $value = $default;`

I have changed it to:

`(isset($value) OR $CI->input->post()) OR $value = $default;`

and it does the trick for my multiselect.

Do you see any downsides? Is this something that could make its way into CodeIgniter?

**Comment by narfbg** [comment]
`set_value()` sets the `value` attribute, it is not suitable for this.

For `select` tags, there's `set_select()`, but ... there's an inherent limitation to field names ending in `[]`.

PHP will convert the inputs to arrays, and because the indexes depend on order of appearance in the request, there are cases where it is practically impossible to pinpoint the exact value.

**Comment by emilebourquin** [comment]
set_select seems useful only if I'm already foreach'ing through the default values? I'm hoping to avoid that.

I suppose I could always do 

`<?= form_multiselect('host_owners[]', $host_owners, set_value('host_owners[]', ($this->input->post() ? NULL : $chosen_host_owners)), 'id=inputHostOwners class="multiselect-host_owners" size="10"'); ?>`

All these seem to be a hack, I'm hoping to find a way to not have the default value take effect if data has been POST'ed, just not the multiselects data (i.e. all have been unchosen).

**Comment by narfbg** [comment]
I don't understand what you mean with that "foreach'ing" ... `set_select()` is what you're supposed to use here.

**Comment by emilebourquin** [comment]
Like

`<?= form_multiselect('host_owners[]', $host_owners, set_select('host_owners[]', $default_host_owners), 'id=inputHostOwners class="multiselect-host_owners" size="10"'); ?>`

?
That doesn't seem to be working.

The manual for set_select [https://www.codeigniter.com/userguide3/helpers/form_helper.html#set_select](url) shows set_select being used on each value of the multiselect, that never made much sense to me, whe I have all the multiselect values in an array, within the view.

**Comment by anandlinast** [comment]
when i go for edit form previously selected value not calling selected one but it returns default select option 

 <select name="department">
		  <option>Select </option>
              <?php if(count($department)):?>
			  <?php foreach($department as $departments):?>
			  <option value=<?php echo $departments->name;?>> <?php echo $departments->name; set_select('name',$edit->department);?></option>
			  <?php endforeach; ?>
			  <?php else: ?>
			  <?php endif; ?>

		  </select>

**Comment by narfbg** [comment]
@emilebourquin My sincere apologies for not replying to you. I guess I needed to think more about it, but never got around to looking back at this.

Not really sure what to say ... You can't have both do-default and don't-do-default for the same condition, regardless of whether you use `set_select()`, `set_value()` or whatever else.

@anandlinast Please learn to use the GitHub formatting tools correctly. I had to click "Edit" on your post (and I did the necessary corrections) to understand what you're talking about, because your code wasn't displayed as such.

Either way:

1. You're not using `set_select()` correctly.
2. This is a completely unrelated thread and it's inappropriate to hijack it.
3. This is a bug tracker; please ask your questions on our [forums](https://forum.codeigniter.com/) instead.

**Comment by emilebourquin** [comment]
@narfbg Thanks for the reply, I do appreciate it. I do understand what you are saying, that it seems odd to have do-default, and don't-do-default behaviors on seemingly the same condition (form validation failed), but they aren't actually the same condition. The first is "form validation failed because this is the first time the user has seen the form, use the default", and the second is "form validation has failed because there are errors ion the POSTed form, use what was POSTed". In this second case, what was POSTed for the multiselect was Nothing, so use Nothing when repopulating the multiselect, not the default.

**Comment by narfbg** [comment]
That logic already exists in `set_select()`.

**Comment by emilebourquin** [comment]
Agreed, but set_select makes me step through each value of the multiselect, calling set_select on it. set_value does not.

Basically, what I am saying is:

`<?= form_multiselect('host_owners[]', $host_owners, set_value('host_owners', $chosen_host_owners), 'id="inputHostOwners" class="multiselect-host_owners" size="10"'); ?>`

works, to set all of the default values in the multiselect. The downside of set_value is that if I deselect everything in the multiselect, then have a form error, the multiselect is repopulated with the default values, not the "Nothing Selected" that was POSTed.

`<?= form_multiselect('host_owners[]', $host_owners, set_select('host_owners', $chosen_host_owners), 'id="inputHostOwners" class="multiselect-host_owners" size="10"'); ?>`

does not work, because it does not take an array for the second parameter, it takes a string.

I'm hoping to just pass an array of values to set_value (which does work), or set_select(which does not work), and not have to call set_select on every value of the multiselect, as shown at https://www.codeigniter.com/userguide3/helpers/form_helper.html#set_select

**Comment by emilebourquin** [comment]
Looking further into it, I guess my problem may really be with form_multiselect.

`<?= form_multiselect('host_owners[]', $host_owners, $chosen_host_owners, 'id="inputHostOwners" class="multiselect-host_owners" size="10"'); ?>`

does work, but on form_error, the multiselect is not populated with the previously chosen values, it is populated with the default values. On form error, it should be populated with the previously selected values, or nothing, if nothing is POSTed for it.

**Comment by narfbg** [comment]
`set_value()` can't do what you're trying to do with it. It may happen to work in some cases, but it wasn't really intended to - it was designed to populate the `value` attribute of an input.

`form_multiselect()` may indeed be buggy though. There's too much logic packed into it, and that's kinda why I hate the entire form helpers collection - the simple ones are useless, while the actually useful ones are so complicated that there's almost a guarantee something won't work.

**Comment by emilebourquin** [comment]
Understood, and thanks for the insight. Also, thanks for all of your hard work on CodeIgniter over the years, we really appreciate it.

**Comment by narfbg** [comment]
You're welcome.

Though, not sure what to do with this issue now ... This is a bug tracker after all; you being satisfied with some explanation doesn't conclude the conversation. Guess I'll leave it open for someone to possibly take on a solution in the future.
