### ISSUE TITLE
Custom Config file with empty array gives exception

### ISSUE THREAD

**Issue by citrix123** [bcit-ci/CodeIgniter#4951]
Hi ,
I tried creating my own custom config file, with empty array like 
$config['xyz'] = array();

as i load this config either manually or via autoload,
it raises an exception.

Is this issue or expected 
If expected we should add this in Documentation as well.

Thanks,
Rahul

**Comment by narfbg** [comment]
More details please.

**Comment by citrix123** [comment]
I created a custom config file named selectionConfig.php in /application/config  and inside it i kept $config['xyz'] = array();

and then i tried to load it manually as well as adding it in 
$autoload['config'] = array('selectionConfig');

Than it raised a unhandled exception.

Hope i explained, Let me know if any other details needed

**Comment by narfbg** [comment]
Most obviously, you should tell what that exception is ...

**Comment by citrix123** [comment]
I guess this is invalid issue .. I am not able to reproduce it again.

Thanks @narfbg 
I will close this ticket
