### ISSUE TITLE
Optional or occasional ignoring of cached 'table_names' list by table_exists()

### ISSUE THREAD

**Issue by danielrhodeswarp** [bcit-ci/CodeIgniter#4953]
Okey dokey, well I'm the first to admit that my particular use case is stretching the sensible use of migrations by quite a bit (lots of dropping and recreating multiple copies of the same table that just have different names).

However, I see that table_exists() depends on a cached 'table_names' list. The problem in a migrations context (esp. if you are running from scratch right to the end) is that this will be cached with fewer tables in it that you end up with after migrating.

Would it be useful or interesting to have an option for table_exists() [and I suppose anything else relying on 'table_names'] to get the 'table_names' from source and bypass the cache?

UPDATE: Well I've just realised after writing all this that there is another or different issue here which is "Why don't DB tables created with migrations update the 'table_names' list"?

:-/

**Comment by danielrhodeswarp** [comment]
As something of an update, create_table() in DB_forge.php does indeed seem to alter the 'table_names' list **but only** if it is not empty.

I'm just wondering if there's any special or magical reason for that logic?

If I remove that logic, my use case of wanting to call table_exists() in a migrations context works!

**Comment by narfbg** [comment]
The intent was to leave the cache untouched if it was yet to be populated ... It's just that an empty array means it *is* populated, but there were no tables in the database.

**Comment by narfbg** [comment]
Referencing 593ce680b87fadb05af6ba13c857ef8b16303bcf as I missed the `#` sign in front of the issue number in the commit message.

**Comment by danielrhodeswarp** [comment]
Many thanks for that, glad you've got it sorted.
