### ISSUE TITLE
DB builder bug

### ISSUE THREAD

**Issue by mehaX** [bcit-ci/CodeIgniter#4954]
I tried to build an sql using
`return $this->db
            ->select("p.*, if(up.user_id=p.created_by, 1, 0) as owner")
            ->from('user_project up')
            ->join('projects p', 'p.id=up.project_id and p.status=1')
            ->where('up.user_id', 3571)
            ->get()->result_array()`

But the query output was as on the photo
![screenshot from 2016-12-20 13-51-46](https://cloud.githubusercontent.com/assets/6259185/21351183/84124a0a-c6bb-11e6-8048-1e9dd0bf3d26.png)

**Comment by narfbg** [comment]
Use the escape parameter.
