### ISSUE TITLE
Image won't be Read when Try to Stored into Database with Blob Datatype using Query Builder

### ISSUE THREAD

**Issue by imbagila** [bcit-ci/CodeIgniter#4956]
I was working on a simple CRUD data which is upload image feature inside in, and will be stored into database as blob datatype. So this is my first code :

```
/**
 * Create data
 * 
 * @return	boolean
 */
public function create()
{
	// Data non-image
	$no_urut = htmlspecialchars(trim( $this->input->post('no_urut', TRUE) ));
	$nama_calon = htmlspecialchars(trim( $this->input->post('nama_calon', TRUE) ));

	// Image
	$gambar = $_FILES['foto_calon']['tmp_name'];
	$gambar = file_get_contents($gambar);
	$gambar = addslashes($gambar);

	// Object array
	$object = array(
		'id_calon'	=> NULL,
		'nama_calon'	=> $nama_calon,
		'foto_calon'	=> $gambar,
		'no_urut'	=> $no_urut,
		'suara'	=> 0
	);

	// Query builder
	$this->db->insert('tb_calon', $object);

	// Check is data successfully created or not ?
	return ($this->db->affected_rows() > 0) ? TRUE : FALSE;
}
```

The data was successfully saved, but the image is won't be read inside web. I also tried to download the image from database, and save it as a file, and it wouldn't be opened too. This is how I read the image with blob datatype from database in HTML :
`<img src="<?php echo 'data:image/jpeg;base64,' . base64_encode($row->foto_calon); ?>" />`

Then I try to using normal CodeIgniter query like this :
```
/**
 * Create data
 * 
 * @return	boolean
 */
public function create()
{
	$query = '';

	// Data non-image
	$no_urut = htmlspecialchars(trim( $this->input->post('no_urut', TRUE) ));
	$nama_calon = htmlspecialchars(trim( $this->input->post('nama_calon', TRUE) ));

	// Image
	$gambar = $_FILES['foto_calon']['tmp_name'];
	$gambar = file_get_contents($gambar);
	$gambar = addslashes($gambar);

	// Query
	$query .= 'INSERT INTO `tb_calon` (`id_calon`, `nama_calon`, `foto_calon`, `no_urut`, `suara`) ';
	$query .= 'VALUES (NULL, "' . $nama_calon . '", "' . $gambar . '", "' . $no_urut . '", "0");';

	// Execute the query
	$this->db->query($query);

	// Check is data successfully created or not ?
	return ($this->db->affected_rows() > 0) ? TRUE : FALSE;
}
```

Data was successfully saved, then I try to read the image in HTML code, and it works perfectly. I was tried with some different images, but it always won't be read when I try to using query builder. Is it a bug or just my code is wrong ?
Thanks before.

**Comment by narfbg** [comment]
Your code is wrong.

Please note that this is a bug tracker. You should *verify* that something is a bug before posting here.
For anything else, please post on our [forums](https://forum.codeigniter.com/) instead.
