### ISSUE TITLE
Bugs when in a library use $this->CI

### ISSUE THREAD

**Issue by sismi** [bcit-ci/CodeIgniter#4959]
Hello,
I use the 3.1.2 and in my library putted in `__construct` 

> $this->CI =& get_instance();

and in the class use 

> Ex1: $this->CI->form_validation
> Ex2: $this->CI->input,
> Ex3: $this->CI->security
> etc etc

Every work BUT when I use `$this->CI->security->get_csrf_token_name()` the name of csrf started with **"ci_[name_of_crsf]"**

It's a bug?

**Comment by narfbg** [comment]
No, it's not a bug. I don't even understand what the problem is with that.

Please post on our [forums](https://forum.codeigniter.com/) instead, and only come here when you are sure you have a bug to report.
