### ISSUE TITLE
Always invalid email when idn_to_ascii function exists. [SOLVED]

### ISSUE THREAD

**Issue by mstojanovv** [bcit-ci/CodeIgniter#4965]
Hello.

Problem in Codeigniter version # 3.1.2
PHP Version 7.0

I have some strange problem with the email validation method.
system/libraries/form_validation.php on line number 1232 there line:

`
if (function_exists('idn_to_ascii') && sscanf($str, '%[^@]@%s', $name, $domain) === 2)
{
     $str = $name.'@'.idn_to_ascii($domain);
}
`

When the email string comes inside this statement (when function id_to_ascii exists) the validation always returns as invalid email. 

I tried to remove this line and works good.
Any ideas about this?

Thanks.

**Comment by mstojanovv** [comment]
Seems like it was server related issue and the hosting provider fixed it.

**Comment by narfbg** [comment]
This is not a forum board.
