### ISSUE TITLE
Bug of _update_batch in system\core\databse\DB_query_builder.php in 3.1.2 

### ISSUE THREAD

**Issue by cczzcc** [bcit-ci/CodeIgniter#4974]
Version: 3.1.2
Download from https://www.codeigniter.com
If using update_batch, you will get 
`<p>Severity: Notice</p>
<p>Message:  Undefined index: id</p>
<p>Filename: database/DB_query_builder.php</p>
<p>Line Number: 1949</p>`

Line 1944, index was escaped, but not used in Line 1949 `$ids[] = $val[$index];`
So whatever you pass to this function, you will always get this error.
It is OK in CI 3.0

**Comment by gxgpet** [comment]
Version of CI used?

**Comment by cczzcc** [comment]
3.1.2

**Comment by gxgpet** [comment]
See #4892.
