### ISSUE TITLE
DB_query_builder::get_compiled_select() useless in current state when use of order_by

### ISSUE THREAD

**Issue by partikule** [bcit-ci/CodeIgniter#4980]
get_compiled_select() cannot be used to get the compiled select before use of order_by method.

Explanation : 
Because _compile_order_by() transforms $this->qb_orderby in a string, it is not possible to add any other "order_by" after a get_compiled_select() call.
This behavior makes get_compiled_select() with the attribute $reset set to FALSE useless in some specific usage.

One approach :
```
	protected function _compile_order_by()
	{
		if (is_array($this->qb_orderby) && count($this->qb_orderby) > 0)
		{
			$orderby = array();

			for ($i = 0, $c = count($this->qb_orderby); $i < $c; $i++)
			{
				$field = $this->qb_orderby[$i]['field'];

				if ($this->qb_orderby[$i]['escape'] !== FALSE && ! $this->_is_literal($this->qb_orderby[$i]['field']))
				{
					$field = $this->protect_identifiers($this->qb_orderby[$i]['field']);
				}

				$orderby[] = $field.$this->qb_orderby[$i]['direction'];
			}

			return "\nORDER BY ".implode(', ', $orderby);
		}
		elseif (is_string($this->qb_orderby))
		{
			return $this->qb_orderby;
		}

		return '';
	}

```

**Comment by narfbg** [comment]
Please demonstrate the problem, not the solution.

**Comment by partikule** [comment]
The problem : 
get_compiled_select() cannot be used to get the compiled select before use of order_by method.

As it is perhaps not clear enough : 
1. Use the DB query builder to build a select, add one order_by to it,
2. Call get_compiled_select(),
3. Add another order_by to the previously started query

**Comment by partikule** [comment]
Btw... sorry if giving a solution is not a good thing...

**Comment by narfbg** [comment]
I was simply asking for a short code example ... The explanation was further confusing because you stated it was "unusable", and if that was true, we'd have coundless bug reports for it.
You just have a bizzare use case, that doesn't make it unusable for everybody else.

Anyway, see if the commit referenced above resolves it.

**Comment by partikule** [comment]
Thanks for your answer.
What you suggest resolves it I guess (not tested), but take care on line 2505, $i is not defined.

`$this->qb_orderby[$i] = $this->qb_orderby[$i]['field'].$this->qb_orderby[$i]['direction'];
`
Btw, the method _compile_order_by() is the only one which is modifiing the "qb" internal var, which is a little bit strange.

To answer to your first comment, my apologizes, I was a little bit hard by saying the method is not usable. I was thinking this method could be called even the query is not completely built up (for example, when more than one method are involved in the build of the query and the method)
From the point of view I got, get_compiled_select() could be called at any time without altering the data used by the builder to build the final query.

**Comment by narfbg** [comment]
That [line 2505](https://github.com/bcit-ci/CodeIgniter/blob/fc9102874a50fdf53a732b1c645c49e0a5a39812/system/database/DB_query_builder.php#L2505) in question is inside the `for()` loop ... `$i` can't be undefined there. But I do prefer that you actually test the patch before applying it to the main branch.

`_compile_order_by()` isn't the only method that modifies its internal vars, but it was the only one to turn the entire var into a string.

**Comment by partikule** [comment]
OK, I'll test it tomorrow morning (GMT+1 time).
Btw, to not modify the internal vars could be a good approach. If not, how to ensure that get_compiled_select do what it is supposed to : return the compiled select in order to "have a look", whatever "bizarre" this look can be ?

**Comment by narfbg** [comment]
You're not supposed to "have a look", you're only supposed to want the end result - this is why I said your use case was bizzare.

The patch here still modifies the internal vars, it just does it in a way that they're still reusable ... `_compile_group_by()` for example, does the same.

**Comment by partikule** [comment]
OK, great, tested, it works.
Btw, previously (PHP 5.sh...), I was using DB_active_rec::_compile_select() to get exactly this : One view at one given step, of the current query.
The usecase can look curious, but it can be used to do some stuff with the main select, like building some key.
Anyway, if the purpose looks strange, should I better extend the CI lib and add one "display_current_compiled_select()" method or do you think the current method is supposed to be used in my "bizarre" way ? :-)

**Comment by partikule** [comment]
Btw, whatfor should I'm supposed to get the final compiled select only ? Look at it and find it beautiful... ? If it is buggy, CI will tel me without I need to ask for... but you know that.

**Comment by narfbg** [comment]
I don't know what for ... I guess some people would want to log them queries. 

Once you put a piece of code out there, you never know how it may be used and your use case, while strange, was easily fixable without side effects - otherwise I wouldn't care for it.

**Comment by partikule** [comment]
You mean that if it wasn't easy to fix, you wouldn't have care ?
You're good, guy ! :-D

**Comment by narfbg** [comment]
The query builder is a very complex thing and trying to change something in it often results in something else breaking ... Given that, of course I wouldn't care for something that I see as an edge case at best.
