### ISSUE TITLE
validating required file upload not working

### ISSUE THREAD

**Issue by lloricode** [bcit-ci/CodeIgniter#4988]
//not working 
$this->form_validation->set_rules(array(
         array(
                'label' => 'Image',
                'field' => 'upload_image_file',
                'rules' => 'required'
            )
));

//so i just created a function and call it on rules
   'rules' => 'callback_handle_upload'
//function
   function handle_upload() {
        if (isset($_FILES['upload_image_file']) && !empty($_FILES['upload_image_file']['name'])) {
            return true;
        } else {
            // throw an error because nothing was uploaded
            $this->form_validation->set_message('handle_upload', "You must upload an image!");
            return false;
        }
    }

**Comment by narfbg** [comment]
`$_FILES` is not `$_POST`, of course it can't work.
