### ISSUE TITLE
url_title function breaks unicode on lowercase

### ISSUE THREAD

**Issue by daveherman71** [bcit-ci/CodeIgniter#4993]
When using the url_title() helper function with the lowercase parameter set to TRUE any string with unicode characters gets converted incorrectly.

```
echo url_title("Hugo Naudé; The Mountain", "-", TRUE);

// Incorrect result: hugo-naud�-the-mountain
```

The fix is to replace the code on line 508 in the url_helper.php from:

`$str = strtolower($str);`

to:

`$str = mb_strtolower($str);`

```
echo url_title("Hugo Naudé; The Mountain", "-", TRUE);

// Correct result: hugo-naudé-the-mountain
```

**Comment by narfbg** [comment]
That wouldn't be a valid URL character either way.
See #1332.
