### ISSUE TITLE
Ajax login issue

### ISSUE THREAD

**Issue by cretupaul** [bcit-ci/CodeIgniter#4995]
Hi! I am trying to make a login using ajax, but when i want to save the session data, it shows me that everything is set, but when i refresh the page everything is lost and my session data it is empty. Do you have any idea to help me in this problem?

**Comment by narfbg** [comment]
This is a bug tracker.
Post your questions on our [forums](https://forum.codeigniter.com/) instead.

**Comment by cretupaul** [comment]
Ok. Thank you!
