### ISSUE TITLE
Unable to locate the specified class: Session.php

### ISSUE THREAD

**Issue by monski** [bcit-ci/CodeIgniter#5000]
Not sure if im only the one experiencing this, but after an upgrade to 3.x we are getting this error

$autoload['drivers'] =array('session');

**Comment by gxgpet** [comment]
[Session](https://codeigniter.com/userguide3/libraries/sessions.html) is a library, not a driver. So, it's not a bug.

**Comment by jim-parry** [comment]
This has come up on the forum, which is the proper place to get help with CodeIgniter.

**Comment by kamijha** [comment]
Check Once on this **Codeigniter(your CI root folder)\system\libraries\Session.php**  is exists or not, if not download a new codeigniter with the same version you are using and just copy the session.php to your running root directory.

**Comment by narfbg** [comment]
> Session is a library, not a driver. So, it's not a bug.

It works either way.

> This has come up on the forum, which is the proper place to get help with CodeIgniter.

... and not only on the forums. There's **8** other issues here with titles containing the same error message, if not exactly matching this one.

Use the search bar people.

> Check Once on this Codeigniter(your CI root folder)\system\libraries\Session.php is exists or not, if not download a new codeigniter with the same version you are using and just copy the session.php to your running root directory.

Not only will this not solve the problem; it will make it worse - in the 99% case, *system/libraries/Session.php* existing **is** the problem.
