### ISSUE TITLE
how to set PDO::MYSQL_ATTR_USE_BUFFERED_QUERY in codeigniter

### ISSUE THREAD

**Issue by prashantnirgun** [bcit-ci/CodeIgniter#5001]
I am using Codeigniter 3.1 Version and trying to use MySQL 5.5. When I am calling Stored Procedure back to back 2 times its giving the error. Anybody know how to fix this ? **** code ****************

public function foo()
    {
       //test_sp,test1_sp;
        echo "called sp1 <br>";
        $sql = "CALL test_sp()";
        $query = $this->db->query($sql);
        var_dump( $query->result());

        echo "<br> called sp2 <br>";
        $sql2 = "CALL test1_sp()";
        $query2 = $this->db->query($sql2);
         var_dump($query2->result());
    }
********** out put ***********

Error Number: HY000/2014

Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.

CALL test1_sp() Filename: controllers/Test.php Line Number: 27

**Comment by narfbg** [comment]
This is a bug tracker.
Post such questions on our [forums](https://forum.codeigniter.com/).
