### ISSUE TITLE
Useless code at DB_Driver.php file

### ISSUE THREAD

**Issue by marchiore** [bcit-ci/CodeIgniter#5004]
Today i was looking the Codeigniter source code and i found something weird. if it is really wrong i will send a pull request:

[DB_driver.php Line 1976](https://github.com/bcit-ci/CodeIgniter/blob/master/system/database/DB_driver.php#L1976-L1984)

```
/**
 * Dummy method that allows Query Builder class to be disabled
 * and keep count_all() working.
 *
 * @return	void
 */
protected function _reset_select()
{
}
```
Why this method is necessary? Because i saw that it is called on **count_all** function:

[DB_driver.php Line 1214](https://github.com/bcit-ci/CodeIgniter/blob/master/system/database/DB_driver.php#L1205-L1230)
```
/**
 * "Count All" query
 *
 * Generates a platform-specific query string that counts all records in
 * the specified database
 *
 * @param	string
 * @return	int
 */
public function count_all($table = '')
{
	if ($table === '')
	{
		return 0;
	}
	$query = $this->query($this->_count_string.$this->escape_identifiers('numrows').' FROM '.$this->protect_identifiers($table, TRUE, NULL, FALSE));
	if ($query->num_rows() === 0)
	{
		return 0;
	}
	$query = $query->row();
	$this->_reset_select();
	return (int) $query->numrows;
}
```

**Comment by narfbg** [comment]
It's not wrong; `CI_DB_query_builder` has the actual implementation.

`CI_DB_driver` has it only to avoid stupid errors.
