### ISSUE TITLE
Session files drive garbage collection error

### ISSUE THREAD

**Issue by daveherman71** [bcit-ci/CodeIgniter#5007]
I'm encountering a "Permission denied" error if a file lock exists on a session file during the garbage collection cycle (hopefully my terminology is correct here).

My config settings are:

```
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 0;
$config['sess_save_path'] = 'R:\Temp';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;
```

Details of the error:

```
Severity:    	Warning
Message:    	unlink(R:\Temp\ci_sessione68b0d0avvbmsf835t9pr8bo0019e18e): Permission denied
Filename:    	drivers/Session_files_driver.php
Line Number:    384
```

My fix is to simply suppress the reporting of the error by prefixing the unlink function with an @ symbol. I then assume that the operating system will eventually resolve the file lock and the session file will be deleted in a subsequent GC cycle.

```
Line 384:	@unlink($this->_config['save_path'].DIRECTORY_SEPARATOR.$file);
```

Perhaps this fix can be included in the next commit?

**Comment by tianhe1986** [comment]
@daveherman71 

I reproduced your situation with the following methods

```
	public function test_session1()
	{
		sleep(3);
		$this->load->library('session');
	}
	
	public function test_session2()
	{
		$this->load->library('session');
		sleep(3);
	}
```
and php(v5.6.25) gc config
```
session.gc_probability = 1
session.gc_divisor = 1
session.gc_maxlifetime = 2
```

I opened two window in my explorer, the first visit `test_session1`, and the second `test_session2`, 
then I refreshed the first window rapidly many times within 3 seconds, and then refreshed the second once. The second window showed the same error message as yours.

But it may be a bad use case, I should initialize session in controller constructor or auto-load it.

So, how do you initialize session, and your gc config ?

**Comment by daveherman71** [comment]
I'm using PHP 7.0.9 on Windows 2008 R2 with an unmodified GC config and I'm initiating the session by simply loading the CI Session library. In my case I'm using the wincache driver.

```
session.gc_probability = 1
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
```

To replicate the error you can simply open the CI session file in notepad and at the session expiry (in my case this is 24 minutes) the error will occur.

I do clean up the sessions during the log out process but my problem occurs when a user's session becomes dormant, for instance, when he ignores the session or has navigated away from the application without logging out. If the session file is locked for some reason then another user will encounter the error during the GC process.

As there appears to be no reason for the second user to receive the error it just causes confusion which is what I'm trying to avoid.

BTW, I don't know why the OS locked the session file.

**Comment by narfbg** [comment]
The file is locked because you have it open with Notepad ... That's the entire point of locking - preventing file modifications from multiple processes at the same time. This doesn't happen when users just navigate away from pages as the file is locked when the request starts and unlocked when it ends.

There's nothing to be fixed here.

**Comment by daveherman71** [comment]
You've missed the point completely. I didn't have the file open in notepad - I only said you can replicate the problem if you open the file in notepad.

As I stated, I don't know why the OS locked the file I just noted that the file was locked when the driver tried to delete it and then failed with an error. The point - as per my original post - is that an error is being thrown in this instance and I have suggested a way to avoid the error from being thrown.

Its part of the core and I shouldn't have to rewrite the library to first check if a lock exists before trying to delete it - especially when it's not necessary. If you have an alternative suggestion then please let me know.

**Comment by narfbg** [comment]
The error is being triggered because something's wrong. You have to find out what it is, not hide it.

**Comment by daveherman71** [comment]
What's wrong is that the code operates on the mistaken assumption that it only needs to rely on the file's last modified time before trying to delete it without considering the possibility that a lock may exist. I haven't considered the best of doing this which is why I suggested simply suppressing the error in my original post.

**Comment by narfbg** [comment]
You're not going to convince me with that kind of argument.

The assumption is logical and not the problem. If there's any problem at all, we'll only find it when we know *why the file is locked* when it's not supposed to have been touched in the past X minutes.
