### ISSUE TITLE
sess_regenerate_destroy

### ISSUE THREAD

**Issue by skycyclone** [bcit-ci/CodeIgniter#5008]
Session Library 

config  sess_driver = database;
config  sess_cookie_name = cookie_name;
config  sess_expiration = 3600;
config  sess_save_path = ci_session;
config  sess_match_ip= false;
config  sess_time_to_update = 300;
config  sess_regenerate_destroy = true;

When 300s later, all old session will be destroy and create a new session ID, now, the value of this new session id  is NULL , bug the current session variable has not expired(3600s) ,The current session is not inherited by the new id.

Affect
The user logon is forced to log off even if I want to be 3600 seconds later.

**Comment by narfbg** [comment]
It is very hard to understand what you're trying to say. Please try explaining it better.

**Comment by uguraktas** [comment]
can you explain topic ?
