### ISSUE TITLE
imagecopy() expects parameter 1 to be resource, boolean given

### ISSUE THREAD

**Issue by shihasck** [bcit-ci/CodeIgniter#5011]
Why this error is displaying.

*******************************************************************************
A PHP Error was encountered

Severity: Warning

Message: imagecopy() expects parameter 1 to be resource, boolean given

Filename: libraries/Image_lib.php

Line Number: 1217

Backtrace:

File: /Applications/MAMP/htdocs/rookieninja/application/controllers/Register.php
Line: 474
Function: watermark

File: /Applications/MAMP/htdocs/rookieninja/application/controllers/Register.php
Line: 231
Function: do_upload_img

File: /Applications/MAMP/htdocs/rookieninja/index.php
Line: 315
Function: require_once
******************************************************************************

Even if I use **error_reporting(0);** then also it is showing. Please solve this issue.

**Comment by Lyricalz** [comment]
This seems to be issue with your code

`imagecopy() expects parameter 1 to be resource, boolean given`

You're passing a boolean as a parameter (most likely return false), output the value of the variable and you can self debug

**Comment by shihasck** [comment]
I'm calling this watermark function only if there is some input value there. And for me if there is a input value this warning is not there. But when the value is not there, then this warning is displaying. Here is my code:

              `if($_FILES['portfolioimg']['size'])`
              `{`
                `$portfolioimg = $this->do_upload_img();`
              `}`

    `function do_upload_img()`
    `{`
        `if(isset($_FILES['portfolioimg']['size']) != 0){`
           `$name_array = array();`
           `$files = $_FILES;`
           `$cpt = count($_FILES['portfolioimg']['name']);`

           `$config['wm_type'] = 'overlay';`
           `$config['wm_overlay_path'] = './assets/img/watermark.png';`
           $config['quality'] = 50;
           $config['wm_vrt_alignment'] = 'middle';
           $config['wm_hor_alignment'] = 'center';

           for($i=0; $i<=$cpt-1; $i++)
           {           
               $_FILES['userfile']['name']= $files['portfolioimg']['name'][$i];
               $_FILES['userfile']['type']= $files['portfolioimg']['type'][$i];
               $_FILES['userfile']['tmp_name']= $files['portfolioimg']['tmp_name'][$i];
               $_FILES['userfile']['error']= $files['portfolioimg']['error'][$i];
               $_FILES['userfile']['size']= $files['portfolioimg']['size'][$i];    

               $imgnam = rand(10,1000000);
               $ext = pathinfo($files['portfolioimg']['name'][$i], PATHINFO_EXTENSION);
               if($this->upload->initialize($this->set_upload_options($imgnam))){
                   $data = $this->upload->do_upload();
                   $config['source_image'] = './assets/portfolio_img/' . 'Rookie_'.$imgnam.'.'.$ext;
                   $this->image_lib->initialize($config);
                   $this->image_lib->watermark(); 
                   $name_array[] = $this->upload->data('file_name');
               } else {
                   $this->session->set_flashdata('falsemsg','Only jpg, jpeg, png files are allowed to be uploaded.');
               }
               
           } 
           return $name_array;
        }else{
          return false;
        }
    }

**Comment by narfbg** [comment]
This is a bug tracker.
Please ask your questions on our [forums](https://forum.codeigniter.com/) instead.
