### ISSUE TITLE
Mongo driver has been superseded and change to Mongo-db package.

### ISSUE THREAD

**Issue by nguyenminh797** [bcit-ci/CodeIgniter#5012]
https://pecl.php.net/package/mongo/ -> Currently It has been superseded

How we change to 
https://pecl.php.net/package/mongodb

for Replace ?

**Comment by gxgpet** [comment]
CodeIgniter has no native support for MongoDB. If you have questions which are not framework-related issues, please post them on [forums](http://forum.codeigniter.com/).
