### ISSUE TITLE
witch one is better In this two MVC diagram Models?

### ISSUE THREAD

**Issue by nimahkh** [bcit-ci/CodeIgniter#5014]
we are design two kind of MVC models that you can see in picture below . in first diagram , we have one controller that can work on routers ." Decide Library " , is for deciding that witch model wee need for Route that comes to controller . 

in second diagram , we have one controller that has some Sub Controller by the routes , each sub controller can decide witch model can be include . 
sorry if i cant explain good . 
my question is that witch one is better for bigData ? 
<img src="https://i.stack.imgur.com/fAH1x.png" />

**Comment by narfbg** [comment]
This is a bug tracker.

Please post your questions on our [forums](https://forum.codeigniter.com/) instead.
