### ISSUE TITLE
Fatal error: Call to a member function real_escape_string() 

### ISSUE THREAD

**Issue by haroldmch** [bcit-ci/CodeIgniter#5015]
Fatal error: Call to a member function real_escape_string() on boolean in myfolder\system\database\drivers\mysqli\mysqli_driver.php on line 385

![f11a854a98df4fcab86ec5794b59c470](https://cloud.githubusercontent.com/assets/25024897/22849998/db66ed3e-efe1-11e6-99e6-e8bcce1f4f7a.png)

**Comment by jim-parry** [comment]
Support questions should be asked on our [forum](http://forum.codeigniter.com/)
