### ISSUE TITLE
PNG Image Not Uploading Other format working fine

### ISSUE THREAD

**Issue by ersunnyroy** [bcit-ci/CodeIgniter#5028]
Dear Sir, 

           except png image all other images are working fine ..!! 
this is my upload function 

public function do_upload($input)
        {
				$folderName = date('M-Y');
				$pathToUpload = 'uploads/agents/' . $folderName;
				//echo $pathToUpload;exit;
				if ( ! file_exists($pathToUpload) )
				 {
						$create = mkdir($pathToUpload, 0777);
						//$createThumbsFolder = mkdir($pathToUpload . '', 0777);
						if (!$create)
						return;
				 }
                $config['upload_path']          = $pathToUpload;
                $config['allowed_types']        = 'gif|jpg|png|bmp';
                $config['max_size']             = 1000;
                $config['max_width']            = 1024;
                $config['max_height']           = 768;

                $this->load->library('upload', $config);

                if (!$this->upload->do_upload($input))
                {
                        $error = array('error' => $this->upload->display_errors());

						print_r($error);
                       // $this->load->view('upload_form', $error);
                }
                else
                {
                        $data = array('upload_data' => $this->upload->data());

                        //echo '<pre>';print_r($data['upload_data']);exit;
						return $data['upload_data'];
                }
        }

**Comment by narfbg** [comment]
This is a bug tracker, not a support ticketing system.
Please post such things on our [forums](https://forum.codeigniter.com/) instead.
