### ISSUE TITLE
 Array to string conversion Error

### ISSUE THREAD

**Issue by nollyvenon** [bcit-ci/CodeIgniter#5032]
I get the following error

A PHP Error was encountered

Severity: Notice

Message: Array to string conversion

Filename: database/DB_query_builder.php

Line Number: 676

Backtrace:

File: C:\wamp\www\stockfeb2017\app\models\Products_model.php
Line: 66
Function: where

File: C:\wamp\www\stockfeb2017\app\controllers\Products.php
Line: 635
Function: getProductOptionsWithWH 

How can I sort this?

**Comment by gxgpet** [comment]
If you need help regarding your own project, please post it on [forums](http://forum.codeigniter.com/), as this is intended only for CI-related issues, not for personal support.

**Comment by nollyvenon** [comment]
thanks

**Comment by iamonuwa** [comment]
Create a gist file if you still having the issue, drop the link matrix4u2002@gmail.com. I'll follow it up for you
