### ISSUE TITLE
Problem with CSRF Token & Form_validation

### ISSUE THREAD

**Issue by farsadf** [bcit-ci/CodeIgniter#5036]
Hello,
After digging for a while to fix it i think there is a conflict with these two features of library:
I've tried to create a simple login form using form_open (form helper) with CSRF enabled with following config: 

```
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'csrf_token';
$config['csrf_cookie_name'] = 'csrf_cookie';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();
```
I've also enabled form_validation library to check the data but after first time of loading it, the post parameter won't be passed to it, so i've handled it using set_data parameter:

```
public function post_login() {
	$this->form_validation->set_data($_POST);
	
	$this->form_validation->set_rules('username', 'Username', 'required|max_length[32]');
	$this->form_validation->set_rules('password', 'Password', 'required');

	if($this->form_validation->run()) {
		
	} else
		$this->load->view('welcome/login');
}
```

Everything works fine except the validation_errors() function which always return an empty string.
By the way i've used HTTP verbs routing, and this is my route:
`$route['welcome/login']['POST'] = 'welcome/post_login';`

So is there anything that i've lost?! or maybe the $_POST array won't get passed to validation_errors() function.

**Comment by farsadf** [comment]
by the way: If i do a die() on my view page everything woks fine

**Comment by narfbg** [comment]
This is a bug tracker.
Please post such questions on our [forums](https://forum.codeigniter.com/) instead.
