### ISSUE TITLE
Base 64 attachment with mime type

### ISSUE THREAD

**Issue by aqueeel** [bcit-ci/CodeIgniter#5038]
I cannot send base64 string as attachment. pdf inside email shows error.

**Comment by narfbg** [comment]
This is a bug tracker.
Please post your questions on our [forums](https://forum.codeigniter.com/) instead.

**Comment by aqueeel** [comment]
In codeigniter Email class, when we pass mime type as an argument the following code executes.

```
$file_content =& $file; // buffered file

$this->_attachments[] = array(
        'name'      => array($file, $newname),
        'disposition'   => empty($disposition) ? 'attachment' :    $disposition,  // Can also be 'inline'  Not sure if it matters
        'type'      => $mime,
        'content'   => chunk_split(base64_encode($file_content)),
        'multipart' => 'mixed'
    );
```
chunk_split(base64_encode($file_content)) will break the base64 file that we passed to $this->email->attach() function.

So that I changed the code to

    $file_content =& $file; // buffered file
    $file_content = ($this->_encoding == 'base64') ? $file_content   :  chunk_split(base64_encode($file_content));
Now attachment array as:

 ```
$this->_attachments[] = array(
        'name'      => array($file, $newname),
        'disposition'   => empty($disposition) ? 'attachment' :  $disposition,  // Can also be 'inline'  Not sure if it matters
        'type'      => $mime,
        'content'   => $file_content,
        'multipart' => 'mixed'
    );

```
Now when I intialzed email with :

   ```
$config['_bit_depths'] = array('7bit', '8bit','base64');
   $config['_encoding'] = 'base64'
   $this->load->library('email',$config);
```
May be I'm doing the wrong way, but it works.

  ` $this->email->attach($base64,'attachment','report.pdf','application/pdf');     
`
