### ISSUE TITLE
Codeigniter 3.1.x Session Issue

### ISSUE THREAD

**Issue by jimit-ikraft** [bcit-ci/CodeIgniter#5039]
i can used codeigniter 3.1.x.

i get one problem my session crashed when edit data and add data in database .

in log file i get this error 

`Session: The session cookie was not signed.`

i used form helper and form_validation i donot know where my session crashed.

i used autoload session lib.

session working on record list view when i edit or add record so session crashed.

so please help me. 

my config 

`$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;
$config['sess_encrypt_cookie']=FALSE;

$config['global_xss_filtering'] = FALSE;`

i means when form data post that time session lost 
thanks

**Comment by narfbg** [comment]
This is a bug tracker.
Please post your questions on our [forums](https://forum.codeigniter.com/) instead.
