### ISSUE TITLE
set_radio, set_check

### ISSUE THREAD

**Issue by dmgig** [bcit-ci/CodeIgniter#5041]
I'm not quite sure of the purpose of this check of the form method in the form_helper::set_radio and form_helper::set_checkbox.

What it has done for me is prevent it from working with GET forms. Seems odd that this check of the method is not also checked if the submitted value is an array.

```php
if ($CI->input->method() === 'post')
{
	return ($input === $value) ? ' checked="checked"' : '';
}
```

I've overridden it with my own methods, but seems like it should be removed altogether?

**Comment by narfbg** [comment]
> Seems odd that this check of the method is not also checked if the submitted value is an array.

The value comes from `$_POST`, so if `$_POST[$field]` is an array, we know that this check would match.
But with anything other than arrays, an unchecked radio/checkbox will simply not be submitted, resulting in `$value = null`, which is the same thing as the form not being submitted at all, so the only way to check that is to look at the request method.
