### ISSUE TITLE
skip validating done validate

### ISSUE THREAD

**Issue by lloricode** [bcit-ci/CodeIgniter#5045]
sir @narfbg, i have one form but 2 models,  

1st model will return that include in insert in 2nd model

1st model validate done OK
2nd model validate done OK (but the first model re-validate again, that will going failed[return FALSE])

so the issue is the email validation was ok in first model, then after in second model the first model was include the validate.again

, my question, sir @narfbg ,  can we skip the validated fields?

**Comment by gxgpet** [comment]
Sir Narf won't like that you are asking support questions here, as this is intended only for CodeIgniter-related issues. If you need help with your project/problem, please ask on [forums](https://forum.codeigniter.com/).

**Comment by lloricode** [comment]
@gxgpet thanks, you remind as well :)
