### ISSUE TITLE
Autolink and Arabic Letters in URL

### ISSUE THREAD

**Issue by khashabawy** [bcit-ci/CodeIgniter#5047]
if you have an arabic letters in URL autolink dont take this into account for example 

`https://soundeals.com/community/tag/%D9%85%D9%8A%D9%83%D8%B1%D9%88%D9%81%D9%88%D9%86`

or

`https://soundeals.com/community/tag/ميكروفون`

appears like

[https://soundeals.com/community/tag/](https://soundeals.com/community/tag/)ميكروفون 

instead of 

[https://soundeals.com/community/tag/ميكروفون](https://soundeals.com/community/tag/ميكروفون)

**Comment by narfbg** [comment]
The URL-encoded (first) example does get converted to a link.

Arabic letters on the other hand, are not valid URL characters and as such it's natural that they don't get caught - that's why URL encoding exists in the first place.

**Comment by khashabawy** [comment]
if i have a text  that contains arabic letters inside it for example 

> Arabic letters on the other hand, are not valid URL characters and as such it's natural that they don't get 
https://soundeals.com/community/tag/ميكروفون
caught - that's why URL encoding exists in the first place.

and i want to run the auto_link for this text 

It should detect and apply urlencode to the links before putting them in the href of the <a> tag

**Comment by khashabawy** [comment]
i think github has done it automatically 👍 , we need auto_link in codeiginter to do the same

**Comment by narfbg** [comment]
What GitHub does is GitHub's business.

**Comment by khashabawy** [comment]
this is not a professional reply i am trying to report a bug here !!!

**Comment by khashabawy** [comment]
auto_link function should detect and urlencode the URL before putting it in the `href `paremeter

**Comment by narfbg** [comment]
That you think something is a bug doesn't mean it is. I don't have to agree with you, no matter if you consider that professional or not.

**Comment by khashabawy** [comment]
can you explain how can this not be a bug ?

**Comment by narfbg** [comment]
I already did, you just ignored what I said - arabic characters are not valid URL characters.

**Comment by khashabawy** [comment]
I did not ignore it , i just want to say if we urlencoded them (Arabic Characters) the url will become a valid url , thats why i suggest urlencoding the text in the href parameter

this is a non encoded and not valid
https://soundeals.com/community/tag/ميكروفون

this is encoded and valid
https://soundeals.com/community/tag/%D9%85%D9%8A%D9%83%D8%B1%D9%88%D9%81%D9%88%D9%86

**Comment by narfbg** [comment]
Yea, and if we URL-encode that, there's no reason why we wouldn't URL-encode everything else ... At that point, the entire input becomes a link.

Hence, the only sane thing to do is to only catch URLs that are already valid.

**Comment by khashabawy** [comment]
okay , now i would like to ask for a personal help if you please can.

i would like to find a way to catch URLs that contain Arabic Letters , because i have faild to do this

**Comment by narfbg** [comment]
The place to do that would be on our [forums](https://forum.codeigniter.com/) or a site like StackOverflow. We only deal with bug reports here, sorry.

**Comment by khashabawy** [comment]
okay , waiting your help there 👍 
https://forum.codeigniter.com/thread-67561.html

**Comment by khashabawy** [comment]
solution found in the thread , hop it is applied to the core 

thanks narf
