### ISSUE TITLE
Undefined property: CI_DB_pdo_odbc_driver::$db in subdrivers/pdo_odbc_driver.php on line 171

### ISSUE THREAD

**Issue by ourmandave** [bcit-ci/CodeIgniter#5050]
Server:
CI 3.1.3
php 5.6.30
centos 7

Using PDO through freetds odbc dsn to connect to sql server express on win10.

Using function `$this->db->escape()` throws Undefined property error.

Original line in 171 in subdrivers/pdo_odbc_driver.php

`$this->db->display_error('db_unsupported_feature');`

I took out the `->db` and it works.

`$this->display_error('db_unsupported_feature');`

Displays: 

A Database Error Occurred
Unsupported feature of the database platform you are using.
Filename: models/Ex_system_model.php
Line Number: 64

This is line 64 in Ex_system_model.php
 ` $sql = "SELECT ProductID, ProductNo, ProductName from Products where ProductName = " . $this->db->escape($name) . " order by ProductNo";`

(If I don't use `$this->db->escape($name)` the query works.)

The database.php config is:

`$active_group = 'default';
$query_builder = TRUE;

$db['default'] = array(
	'dsn'	=> 'odbc:myExapp',
	'hostname' => '',
	'username' => 'myUsername',  <-- changed to protect innocent
	'password' => 'myPassword',
	'database' => '',
	'dbdriver' => 'pdo',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),  <-- currently 'development'
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);`

**Comment by narfbg** [comment]
Weird - I didn't receive an email notification for this issue.
Fix commited.
