### ISSUE TITLE
Session variable not working in other controller

### ISSUE THREAD

**Issue by himelali** [bcit-ci/CodeIgniter#5051]
I set a session variable in my login controller after successful login. When I check for the variable in my dashboard controller no session data is found.
When I check the session in the login controller, session data exists. It does not exist when I check the dashboard controller. I have also tried using database sessions but same problem occur here.
I am using CodeIgniter 3.1.3 with HMVC (Module Based MX Controller) and use some other library PHPMailer DomPDF (Both are loaded by autoload.php). Both library are work fine. I have checked in Database, Many times I have found 2 different session ID generated in other controller in the same time after 5 min it has been changed. When my computer has restarted or cookie deleted, then works fine, after sometime this problem has occur. 

I have checked session with $_SESSION, $this->sesssion->all_userdata(), $this->session->userdata; both output are different in different controller.

I have load session library in autoload.php created and updated by composer. 

# My Config File for Session

```
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = APPPATH . 'cache/';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;
```

![1](https://cloud.githubusercontent.com/assets/13802501/23888782/f4d15c88-08b3-11e7-9751-501fbce6768f.PNG)
![2](https://cloud.githubusercontent.com/assets/13802501/23888781/f4d109c2-08b3-11e7-85b4-33bd5eb5534b.PNG)
![3](https://cloud.githubusercontent.com/assets/13802501/23888783/f4d31adc-08b3-11e7-9d5f-d2191d441596.PNG)
![4](https://cloud.githubusercontent.com/assets/13802501/23888784/f4d977b0-08b3-11e7-9dc3-a8dc9de6175b.PNG)

**Comment by narfbg** [comment]
This is a bug tracker, please [keep this on the forums](https://forum.codeigniter.com/thread-67579.html).
If you didn't get responses there, it's probably because you're not explaining the problem well enough.
