### ISSUE TITLE
Working with WAMP on local but not with LINUX server on live site.

### ISSUE THREAD

**Issue by gokulphp** [bcit-ci/CodeIgniter#5052]
I have downloaded this MPDF library and integrated with my project with Codeinginter. It is working great on local server with WAMP.

When I have uploaded on live server (Amazon LINUX server) and tried to generate PDF, got error "The abc.com page isn’t working". To check exact error, enabled Development mode of CI and found below error:

**Message: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/abc/public_html/index.php:58)**

Did search for this issue and found this error produce generally because of white space in controller. I checked for that and found everything is fine.
Another possibility is that, class is ended with "?>", closing php tag. But, that also not case with my code.

So, clueless how to resolve it.

Also, when downloaded, found some required TTF files are not available under ttfonts folder.

Any help is much appreciable.

**Comment by narfbg** [comment]
This is a bug tracker.
Please ask your questions on our [forums](https://forum.codeigniter.com/) instead.
