### ISSUE TITLE
PHP 7.1.2 issue mcrypt_get_iv_size

### ISSUE THREAD

**Issue by erikk1986** [bcit-ci/CodeIgniter#5054]
Hi,

I'm using the new PHP 7 but according to the docs the mcrypt extension has been deprecated. The following exception message is shown:

`Severity: 8192

Message: Function mcrypt_get_iv_size() is deprecated

Filename: libraries/Encrypt.php

Line Number: 297`

Will there be a fix for CI 3 or will this only be fixed in CI 4 ?

**Comment by narfbg** [comment]
Not only is there already a "fix", but it was put in place with 3.0.0 ... that's 2 years and 10 releases ago.
Read the note very prominently put at the top of this page: https://codeigniter.com/userguide3/libraries/encrypt.html

**Comment by erikk1986** [comment]
Feeling dumb right now.....

So sorry for bottering you!

**Comment by narfbg** [comment]
Don't beat yourself over it. Just take a note to always do some basic research first. :)
