### ISSUE TITLE
null at set_flashdata() array broke flashdata()?

### ISSUE THREAD

**Issue by fmertins** [bcit-ci/CodeIgniter#5056]
Hi there, using CI 3.0.3 with database session.

When doing this:
`$this->session->set_flashdata(array('foo' => 'bar', 'bar' => null));`

After the redirect, when getting the flashdata with:
`$this->session->flashdata()`

I get an empty array...

If I modify the "bar" key to something not null, like:
`$this->session->set_flashdata(array('foo' => 'bar', 'bar' => ''));`

When getting the flashdata it comes with the correct array...

Is this behavior correct?

**Comment by gxgpet** [comment]
CI 3.0.3 isn't the latest CI version anymore, you should upgrade.

**Comment by fmertins** [comment]
Humm, but already looked at https://www.codeigniter.com/user_guide/changelog.html for "flashdata" occurrences and dind't find any bug fix... The last occurrence is at 3.0.0 version.
For my point of view, this behavior is dangerous because it seems having a null value at the array, brokes the flashdata() method :-(

**Comment by gxgpet** [comment]
Because "flashdata" is part of Session lib. And this lib was changed enough times since 3.0.3... That's why no fix can be created -- if would be necessary in the case of a real bug. You must use the latest version of the framework.

**Comment by fmertins** [comment]
OK tks
