### ISSUE TITLE
is_cli function fails to determine cli condition when running from cron

### ISSUE THREAD

**Issue by kergma** [bcit-ci/CodeIgniter#5058]
The `is_cli` function incorrectly determines cli condition in some server environments, making it impossible to run controller/method code from cron job.

here is detailed description and solution:
http://www.binarytides.com/php-check-running-cli/

I tested this in several environments and confirm that it's working and reliable, please add this check into your `is_cli()` implementaion:

    if( empty($_SERVER['REMOTE_ADDR']) and !isset($_SERVER['HTTP_USER_AGENT']) and count($_SERVER['argv']) > 0) 
    {
        return true;
    };

Thank you !

**Comment by narfbg** [comment]
Thanks, but there's nothing wrong with the current condition.

In fact, the condition you're proposing is more error-prone, as `$_SERVER['HTTP_USER_AGENT']` comes from the `User-Agent` HTTP header, meaning that it doesn't exist if clients don't send it - a broken CLI environment is way less common than the lack of any header (bar the mandatory `Host` one).

If anything's incorrect, that'd be running the CGI SAPI under CLI, as it is designed for web access and thus what you're suggesting is a work-around at best.

That being said, I don't mind having work-arounds for isolated problems as long as they're rock solid and don't have the potential to cause side effects, but anything that relies on `$_SERVER` doesn't meet that criteria for this issue. If you've got other suggestions - please do share.

P.S. When linking to external resources such as blog posts, please do it as a reference and not as the only means of explaining the problem.

**Comment by kergma** [comment]
When the application is run from cron job in some server environmens, the php (and thus CI) may fail to recognize this situation, and CI router ignores command line parameters and always falls back to default controller/method. Unfortunately it is impossible to make php or CI to behave in cli way from the application scope, and if you have no control on server environment, the only method is to tweak CI code, which I would like to avoid.

The other possible solution is to use some special environment variable to force CI to work in cli mode, for example, if you add the following code to `is_cli` implementation:

    if ( getenv('CI_FORCE_CLI') ) return true;

then I will be able to include this variable in cron line and get it work as expected:

    * * * * * CI_FORCE_CLI=1 cd path/to/app; php index.php controller method parameters

**Comment by narfbg** [comment]
It's not about PHP failing to detect anything, you're simply using the wrong PHP binary. There are different executables for web and CLI.  
I don't know how that environment is setup; the admin(s) may've provided you with one named 'php-cli' or with none at all (intentionally or not).

There's always going to be some weird edge case like this and we can't just add override options. CI is very flexible in that regard already - you can easily override our `is_cli()` with your own, without modifying the framework code. Just declare/include your own function in index.php.
