### ISSUE TITLE
How to change controllers directory

### ISSUE THREAD

**Issue by yozman** [bcit-ci/CodeIgniter#5065]
I have my on project structure for CI like [this](/sinoci/sinoci)

I want to move controllers to `app` folder
and use `App\Controllers` namespace

how can I do that?

**Comment by jim-parry** [comment]
We use github for bug tracking. Support questions should be asked on our forum.
CI3 core components are not namespace-aware, and I don't have a good answer to your question ... someone on the forum might have a suggestion :)
