### ISSUE TITLE
Call to a member function load() on string

### ISSUE THREAD

**Issue by zuiyangqingzhou** [bcit-ci/CodeIgniter#5071]
I use like this:
$this->lang->load('error', 'english');
then show:
PHP Fatal error:  Call to a member function load() on string

CI version: 3.0.4
php version 5.6.30

**Comment by danilodorgam** [comment]
@zuiyangqingzhou 
I simulated your code.
But the same error did not appear

**Comment by tianhe1986** [comment]
@zuiyangqingzhou 
Please offer more codes.
Seems like you have set `$this->lang` to be a string in your controller/model.

**Comment by zploskey** [comment]
Can you reproduce this on the latest released version or the develop branch?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by narfbg** [comment]
This is a bug tracker, and the problem you have is within your own code; you can seek help on our [forums](https://forum.codeigniter.com/) instead.

**Comment by zuiyangqingzhou** [comment]
There is a error_lang.php file in the directory ‘application/language/english/’, I just load this file in this way:$this->lang->load('error', 'english');  then occurred an error: 'PHP Fatal error:  Call to a member function load() on string in my.php'.
I can't find what's causing it, I have implemented it in another way. Anyway, thank you very much
