### ISSUE TITLE
Issue in Codeigniter ==  Fatal error: Contact Admin in Unknown on line 0

### ISSUE THREAD

**Issue by Inshra-1327-f10B** [bcit-ci/CodeIgniter#5072]
can someone help me in this issue my website suddenly respond me like this 
**Fatal error: Contact Admin in Unknown on line 0**
i have no idea what went wrong

**Comment by narfbg** [comment]
This is a bug tracker.
Ask your questions on our [forums](https://forum.codeigniter.com/) instead.
