### ISSUE TITLE
sendmail email does nothing when popen isn't usable.

### ISSUE THREAD

**Issue by falkartis** [bcit-ci/CodeIgniter#5078]
If you try to send an email with sendmail protocol and the popen function isn't usable, eg disabled by the server admin, the email library doesn't even generate an error. And I sit there hitting F5 and waiting for emails.

In the file system/libraries/Email.php near the line 1900 (https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Email.php#L1900) after the if statement 

`if ( ! function_usable('popen')	OR FALSE === ($fp = @popen($this->mailpath.' -oi '.$from.' -t', 'w')))`

you have following comment and `return false`

`// server probably has popen disabled, so nothing we can do to get a verbose error.`

OK the ` ! function_usable('popen')` call suppress the native php error message since it won't try to call `popen` this is fine but I don't agree with `so nothing we can do to get a verbose error`.

**Comment by narfbg** [comment]
Do you have a concrete suggestion?

**Comment by falkartis** [comment]
Just something simple like printing or logging a correspondent error message.

What is strange is that I didn't get the `lang:email_send_failure_` error message from the `_spool_email()` function. Just a blank page, no error, no log. I also called the `print_debugger()` method. Now I'm using the old standard php mail protocol, works fine.

**Comment by narfbg** [comment]
Looking at the [code](https://github.com/bcit-ci/CodeIgniter/blob/3.1.4/system/libraries/Email.php#L1835), I don't see how it's possible that the error message isn't triggered.

**Comment by falkartis** [comment]
Yes, I know, I've read it, I also don't understand it. Also something like `$this->_set_error_message('lang:email_no_popen');` could help other people in the future. Anyway, I've done a workaround, so, if you like you can close this issue.
