### ISSUE TITLE
Image_lib->crop() results server error(error 500) for some image

### ISSUE THREAD

**Issue by hendrawd** [bcit-ci/CodeIgniter#5079]
**What i expecting:**
All crop will be ok

**What happened instead:**
Crop error for some images. You can download the original image to test from https://www.dropbox.com/s/8vfppb3mdvjokjz/FTT_2017-03-30_10.47.18.180_862305030312003.jpg?dl=0

**The code**
```php
$img_path = FCPATH . 'images/pics/' . $file_name;
$img_thumb = FCPATH . 'images/pics/thumb/';
$img = getimagesize($img_path);
$_width = $img[0];
$_height = $img[1];

if ($_width < $_height) {
    // echo "portrait";
    $axis = ($_height - $_width) / 2;
    $config['width'] = $_width;
    $config['height'] = $_width;
    $config['x_axis'] = 0;
    $config['y_axis'] = $axis;
} elseif ($_width > $_height) {
    // echo "landscape";
    $axis = ($_width - $_height) / 2;
    $config['width'] = $_height;
    $config['height'] = $_height;
    $config['x_axis'] = $axis;
    $config['y_axis'] = 0;
} else {
    // echo "square";
    $config['width'] = $_width;
    $config['height'] = $_width;
    $config['x_axis'] = 0;
    $config['y_axis'] = 0;
}

$config['source_image'] = $img_path;
$config['new_image'] = $img_thumb;
$config['maintain_ratio'] = FALSE;

$this->image_lib->initialize($config);

if (!$this->image_lib->crop()) { // this line will always make server error
    $this->image_lib->display_errors();// this line isn't even called
}
```

**Comment by narfbg** [comment]
Look at your error logs ... "Server error 500" tells us nothing, but "there's an error on the server side".

**Comment by hendrawd** [comment]
**Error Log**
`[Wed Apr 05 18:04:40.846912 2017] [:error] [pid 27619] [client xxx.xxx.xxx.xxx:63410] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 3456 bytes) in /var/www/fotato/system/libraries/Image_lib.php on line 515, referer: http://myserver.com`

**Comment by hendrawd** [comment]
I don't think it has to do with image size. Because the image size that i shared is 2.1MB and it's failed, when i use other image with size 3.1MB it's success

**Comment by narfbg** [comment]
... there you go.

**Comment by gxgpet** [comment]
@hendrawd On this section, only CodeIgniter gets hints about fixing it's issues/bugs. :)

**Comment by narfbg** [comment]
Reduce memory usage? :)

You can ask for help on our [forums](https://forum.codeigniter.com/), but this isn't an issue with a specific solution.

**Comment by hendrawd** [comment]
OK, thanks a lot. I will try to breakdown the code and reducing memory usage. What i can do for now is removing memory limit using `ini_set('memory_limit', '-1');`  Actually i am not an advanced web developer and i am not the one that write the initial code, so sorry for my stupidity and limited knowledge.
