### ISSUE TITLE
Web Page Caching still load cached files when not enabled

### ISSUE THREAD

**Issue by Seb33300** [bcit-ci/CodeIgniter#5083]
Hi,

If a page have been cached using the web page caching (`$this->output->cache($n);`), the cached page is still loaded after we disabled the web page config functionality unless we delete the cached file.

I think the cached files should not be loaded if we didn't enable the web page caching.

**Comment by narfbg** [comment]
This behavior is [documented](https://codeigniter.com/userguide3/general/caching.html) and there's a reason for it - to know whether `$this->output->cache()` is called, we'd have to execute all of your code before printing the possibly cached output.  
The entire point of caching is to skip code execution.
