### ISSUE TITLE
insert_batch() not working completely

### ISSUE THREAD

**Issue by krishnadeveloper** [bcit-ci/CodeIgniter#5086]
I have two array, one with same keys and second array with different different keys. insert_batch function working fine when keys of array is the same, but not working fine when keys are different. Please check below

**1. Array with same keys (insert_batch() working fine)**

 Array
 (

    [0] => Array
        (
            [trainer_id] => 2
            [plan_id] => 2
            [week] => week1
            [mon] => {"time":"1:00 AM","item":"a","description":"a"}
            [created_at] => 2017-04-11 13:27:30
            [updated_at] => 2017-04-11 13:27:30
        )

    [1] => Array
        (
            [trainer_id] => 2
            [plan_id] => 2
            [week] => week2
            [mon] => {"time":"1:00 AM","item":"b","description":"b"}
            [created_at] => 2017-04-11 13:27:30
            [updated_at] => 2017-04-11 13:27:30
        )

    [2] => Array
        (
            [trainer_id] => 2
            [plan_id] => 2
            [week] => week3
            [mon] => {"time":"1:00 AM","item":"c","description":"c"}
            [created_at] => 2017-04-11 13:27:30
            [updated_at] => 2017-04-11 13:27:30
        )

    [3] => Array
        (
            [trainer_id] => 2
            [plan_id] => 2
            [week] => week4
            [mon] => {"time":"1:00 AM","item":"d","description":"d"}
            [created_at] => 2017-04-11 13:27:30
            [updated_at] => 2017-04-11 13:27:30
        )

 )

All keys of inner array are same in above array of array and insert_batch() is working fine for above array.

**2. Array with different-different keys(insert_batch() is not working fine)**

  Array
  (

    [0] => Array
        (
            [trainer_id] => 2
            [plan_id] => 2
            [week] => week1
            [mon] => {"time":"1:00 AM","item":"a","description":"a"}
            [created_at] => 2017-04-11 13:17:27
            [updated_at] => 2017-04-11 13:17:27
        )

    [1] => Array
        (
            [trainer_id] => 2
            [plan_id] => 2
            [week] => week2
            [tue] => {"time":"1:00 AM","item":"b","description":"b"}
            [created_at] => 2017-04-11 13:17:27
            [updated_at] => 2017-04-11 13:17:27
        )

    [2] => Array
        (
            [trainer_id] => 2
            [plan_id] => 2
            [week] => week3
            [wed] => {"time":"1:00 AM","item":"d","description":"d"}
            [created_at] => 2017-04-11 13:17:27
            [updated_at] => 2017-04-11 13:17:27
        )

    [3] => Array
        (
            [trainer_id] => 2
            [plan_id] => 2
            [week] => week4
            [thur] => {"time":"1:00 AM","item":"d","description":"d"}
            [created_at] => 2017-04-11 13:17:27
            [updated_at] => 2017-04-11 13:17:27
        )

)

Please check the just above array carefully because some keys are different in this array and insert_batch() is not working for this array. 

DB Table Structure 

![image](https://cloud.githubusercontent.com/assets/12271529/24907457/fa9448ce-1ed9-11e7-8c4c-fd3f0d74202c.png)

**Your quick response to this will be highly appreciated.**
Thanks.

**Comment by gxgpet** [comment]
Tell us more: what version of CI are you using?

**Comment by krishnadean** [comment]
Codeigniter 3x

**Comment by gxgpet** [comment]
My bad.

`insert_batch()` is using `INSERT INTO {table} ({columns}) VALUES ({values}), ({values}), ...`. Your use case won't work, since columns-values must have consistency (i.e. same columns and their own values).

**Comment by krishnadean** [comment]
Hi All & @gxgpet , I have fixed my issue after change the line of code in "system\database\DB_query_builder.php"

Replace the code in the the file DB_query_builder.php, Path : "system\database\DB_query_builder.php"
protected function _insert_batch($table, $keys, $values)
	{
		return 'INSERT INTO '.$table.' ('.implode(', ', $keys).') VALUES '.implode(', ', $values);
	}


**By below code** 

protected function _insert_batch($table, $keys, $values)
	{
		if(is_array($values))
		{
			$values = implode(',',$values);
		}
		return 'INSERT INTO '.$table.' ('.implode(', ', $keys).') VALUES '.implode(', ', $values);
	}

**Comment by gxgpet** [comment]
There is no issue at all... You should use a consistent array when using `insert_batch()`.

Also, please use [CI forums](https://forum.codeigniter.com/) if you need solutions to your own problems/issues since this place is only for CI-related bugs/issues.

**Comment by krishnadeveloper** [comment]
@gxgpet , Have you checked the issue with above arrays, which array, i have give in my question?

**Comment by krishnadeveloper** [comment]
Error shows like below

![image](https://cloud.githubusercontent.com/assets/12271529/24942227/4499ee4a-1f6d-11e7-8650-1ac0a6f14a0f.png)

**Comment by gxgpet** [comment]
@krishnadeveloper Did you read [what I wrote](https://github.com/bcit-ci/CodeIgniter/issues/5086#issuecomment-293312682)?

There is no issue at all, it's only a problem related to your project. For that, please use the [forums](https://forum.codeigniter.com/) to ask for help.

**Comment by krishnadeveloper** [comment]
@gxgpet , This is not issue about my project. You can also use both arrays then you can test according to both arrays. 

I am also looking in to that. Thanks.

**Comment by krishnadeveloper** [comment]
@narfbg , I would like to request you to check my issue. So please check

**Comment by flyhait** [comment]
i have the same issue and i need an [answer](https://www.homeworktiger.com) how to fix it

**Comment by DakuTree** [comment]
Ran into this same issue. Would probably be useful if the [documentation](https://www.codeigniter.com/user_guide/database/query_builder.html?highlight=insert_batch#CI_DB_query_builder::insert_batch) was updated to mention this limitation, as the error really doesn't say much about what the actual issue is.

As for a possible solution, wonder if it would be possible to have CI fallback to using the ```DEFAULT```  keyword for missing columns in cases like these?

**Comment by gxgpet** [comment]
@DakuTree There is no issue with CI... The only issue is that you are not filling your arrays with columns' default values, whatever they would be and you expect CI to do that.

The [documentation](https://www.codeigniter.com/user_guide/database/query_builder.html?highlight=insert_batch#inserting-data) shows very clear an example of how this method is working by showing the actual SQL code produced.

**Comment by narfbg** [comment]
@krishnadeveloper This is a bug tracker.

When you open an issue, you're submitting a bug report and *not* a support ticket.
And anybody responding here does it in their free time, and on good will alone. You cannot request us to be "quick", nor that some particular person looks into your problem. *Especially* since it was already explained to you that this is not a bug.

Please use our [forums](https://forum.codeigniter.com/).

**Comment by krishnadeveloper** [comment]
@narfbg ,Thank you for give me kind of information and consider it in your bug list.
