### ISSUE TITLE
Image Resizing file name without extension

### ISSUE THREAD

**Issue by fattalgazi** [bcit-ci/CodeIgniter#5089]
According to that line : 

https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Image_lib.php#L568

"**new_image**" parameter must have an extension, but when user try to upload an image without an extension, that line manipulates the upload path folder. (it assumes new_image parameter is the folder name and it appends source image name to the end)

Let me give an example;

````
$image_resizing_config                   = array();
$image_resizing_config['image_library']  = 'gd2';
$image_resizing_config['source_image']   = "/var/www/html/bla.dev/user_content/image_original";
$image_resizing_config['new_image']      = "/var/www/html/bla.dev/user_content/image_original_thumbnail";
$image_resizing_config['thumb_marker']   = "";
$image_resizing_config['create_thumb']   = TRUE;
$image_resizing_config['maintain_ratio'] = TRUE;
$image_resizing_config['width']          = 200;
$image_resizing_config['height']         = 200;

$this->load->library('image_lib', $image_resizing_config);
if (!$this->image_lib->resize())
{
    echo $this->image_lib->display_errors();
}
````

This will give an error : 

**"Unable to save the image. Please make sure the image and file directory are writable"**, 

because it tried to upload the thumbnail to the : 

**"/var/www/html/bla.dev/user_content/image_original_thumbnail/image_original"** path, but there is no such a folder.

**Comment by narfbg** [comment]
Don't trust user input, file names included.
