### ISSUE TITLE
preg_match(): Compilation failed: nothing to repeat at offset 1 error in live server 

### ISSUE THREAD

**Issue by vinodrightpath** [bcit-ci/CodeIgniter#5090]
A PHP Error was encountered

Severity: Warning

Message: preg_match(): Compilation failed: nothing to repeat at offset 1

Filename: core/Router.php

Line Number: 399

Backtrace:

File: /home/somascan/public_html/prakasamlive.com/index.php
Line: 317
Function: require_once

**Comment by narfbg** [comment]
https://codeigniter.com/userguide3/general/routing.html
