### ISSUE TITLE
Issue on Arch Based Distros

### ISSUE THREAD

**Issue by MarlonJD** [bcit-ci/CodeIgniter#5093]
I installed and setup LAMP + PhpMyAdmin. I did mod_rewrite etc. now I'm can access to rewrite and I did permission. But I can access without post in controller ($this->input->post('buton_ismi') or $this->uri->segment(1)) but I cannot access with these classes (uri or input). It's non-sense about the helper or library adding to codes. It's nothing like that please keep reading the issue

PHP: 7.1.4
OS: ARCH Linux/Manjaro

I'm only adding

    echo $this->uri->segment(1);
    $this->load->view('welcome_message');

I can access without error on debian, ubuntu, windows with xampp or without xampp.
But arch giving me error like this

    A PHP Error was encountered

    Severity: Notice

    Message: Undefined property: Depo::$uri

And access log:

    ::1 - - [16/Apr/2017:21:41:45 +0300] "GET /CI/index.php/Welcome HTTP/1.1" 500 1047

And there is no error log in logs. Mysqli is working I can take datas from database but If I want to add uri or input classes it giving error. It's non-sense about the changing code because it's already working codes. There could be issue on php extensions or missing extensions or apache or something like that. If you'll wonder this issue please download codeigniter from their website and only change applications/controllers/welcome.php and add echo $this->uri->segment(1); before the view. You can expect the issue if you are using manjaro or arch linux. Please help ? Any idea why?

**Comment by jim-parry** [comment]
We use github for bug tracking. Your issue sounds like an installation/setup problem, and should be addressed on our forum.
Agreed that your situation seems strange, since the Uri class is automatically loaded.
You might want to include your "Depo" source code in your forum post.

**Comment by MarlonJD** [comment]
I found fix. "I to i" from the URI in array cannot getting low letters like "uri" . It's changing the to urI from to core. It's causing locale on the system. I changed en_US. It's fixing this, and there is also fix in core files. Adding mb_strtolower() to is_loaded() function in the common.php fixing issue.
