### ISSUE TITLE
Cannot retrieve saved emoji from mysql

### ISSUE THREAD

**Issue by vahidvdn** [bcit-ci/CodeIgniter#5101]
I could be able to save emoji into `mysql` with `utf8mb4_unicode_ci` collation. (Also can see in phpmyadmin). But when I run a query with php (Codeigniter), I get a single question mark (?) instead of emoji. Any idea?

![emoji](https://cloud.githubusercontent.com/assets/11078601/25312253/2f0c93dc-282a-11e7-817c-6b576f85af3a.png)

My query:

```
$query = $this->db->query("SELECT * FROM emoji");
```

Or even:

```
$query = $this->db->query("SET character_set_client=utf8mb4");
$query = $this->db->query("SELECT * FROM emoji");
```

Any idea?

**Comment by vahidvdn** [comment]
I forgot to add these  two lines:

```
$query = $this->db->query("SET character_set_connection=utf8mb4");
$query = $this->db->query("SET character_set_results=utf8mb4");
```

**Comment by narfbg** [comment]
Please note that this is a bug tracker and in the future, post your questions on our [forums](https://forum.codeigniter.com/) instead.

**Comment by AdaLiszk** [comment]
Btw why do you change the character set manually instead setting in the config?

**Comment by vahidvdn** [comment]
@AdaLiszk That's a good idea. I'm going to try.
Thanks.
