### ISSUE TITLE
Issue with migrations and MySQL database names with non-standard characters.

### ISSUE THREAD

**Issue by BrunoDeBarros** [bcit-ci/CodeIgniter#5106]
Some of my databases have `.` in their name, and the current migrations library doesn't work with them (this changed in 473130a226219dac6ef5c59b625b0e1361b292b3). The `.` character, while unusual for a DB name, is allowed in MySQL, so there's no reason for it not to work in CI.

CI is using escape_identifiers() now (I'm upgrading an old CI2 project, this wasn't the behaviour before), which makes sense to do in possible user-input situations, but the database's name is written in the config file and doesn't change; there should be no need to escape it (or, if escaping it, at least we should not escape allowed characters).

**Comment by narfbg** [comment]
#2755 #3719
