### ISSUE TITLE
URI.php not decode segments values

### ISSUE THREAD

**Issue by emyei** [bcit-ci/CodeIgniter#5107]
When URI string have encoded chars, the protected function _set_uri_string at CI_URI class, not decode segments values. 
Example:
If primary key have space characters, then URI strings seems as:
http:.../view/NEW%20YORK

I have solved this, modifying:
...
			foreach (explode('/', trim($this->uri_string, '/')) as $val)
			{
				$val = trim($val);
				// Filter segments for security
				$this->filter_uri($val);
...
For:
...
			foreach (explode('/', trim($this->uri_string, '/')) as $val)
			{
				$val = urldecode(trim($val));
				// Filter segments for security
				$this->filter_uri($val);
..

**Comment by narfbg** [comment]
This is the intended behavior.
