### ISSUE TITLE
mcrypt deprecated php 7.1

### ISSUE THREAD

**Issue by animfahmy** [bcit-ci/CodeIgniter#5109]
`Severity: 8192

Message: Function mcrypt_get_iv_size() is deprecated

Filename: libraries/Encrypt.php

Line Number: 298`
`Severity: 8192

Message: Function mcrypt_create_iv() is deprecated

Filename: libraries/Encrypt.php

Line Number: 299`
`Severity: 8192

Message: Function mcrypt_encrypt() is deprecated

Filename: libraries/Encrypt.php

Line Number: 300`

Anyone get this issue with php 7.1?

Thanks

**Comment by jim-parry** [comment]
You should not be using Encrypt - there is an important notice at the top of the user guide page for it.
Use the Encryption library instead.

**Comment by animfahmy** [comment]
okey, thank you for your advice
