### ISSUE TITLE
cache based on query not on the page

### ISSUE THREAD

**Issue by hiteshbal91** [bcit-ci/CodeIgniter#5110]
Is there any way or future implementation plan for caching the DB query not based on the page which is currently working?

Suppose I have hooks which does some heavy loading from DB, So I want to cache this heavy operation but if I cache this operation it is cached for the each page user visits, rather than just for the query.

Thanks.

**Comment by gxgpet** [comment]
How about of using the Cache directly? :)

**Comment by narfbg** [comment]
No.

**Comment by hiteshbal91** [comment]
Hi All,

My requirement is like I have to preload the data from DB which is only once consider it as users.
Where I will be showing metadata for every object in database such as modified_by, created_by from the users which are already loaded.

It is like cache which is loaded once and for users update I can again reload the data.
