### ISSUE TITLE
Image_lib crop bug

### ISSUE THREAD

**Issue by visioncode** [bcit-ci/CodeIgniter#5113]
I upgraded from CI 2 to CI 3 today and noticed that my cropping function was not working correctly anymore. At my javascript interface, I post width, height, x and y axis to my php controller which crops the image. When my height/weight is a decimal value, the crop fails.

See example below:
```
$config['source_image'] = FCPATH.'test_gd.jpg';
$config['new_image'] = FCPATH.'test_gd_cropped.jpg';
$config['width'] = 337.5;
$config['height'] = 450;
$config['maintain_ratio'] = FALSE;
$config['overwrite'] = TRUE;
$config['x_axis'] = 184.5;
$config['y_axis'] = 56.25;

$this->image_lib->initialize($config);
$this->image_lib->crop();
```

In system/Image_lib.php I noticed line 491:
`elseif (in_array($key, array('width', 'height'), TRUE) && ! ctype_digit((string) $val))
{ continue; }`

Because ctype_digit is FALSE with decimal values, width and height are cleared and replaced through original height/width of the source image (which fails for cropping).

Maybe you can fix this ..

Thanks!

**Comment by narfbg** [comment]
It's not a bug, you're not supposed to split pixels.
