### ISSUE TITLE
database failover connecting behavior

### ISSUE THREAD

**Issue by lebanggit** [bcit-ci/CodeIgniter#5114]
I have database config:

$db['default'] = array(
	'dsn'	=> '',
	'hostname' => 'google.com',
	'username' => 'root',
	'password' => '',
	'database' => 'site_abc',
	'dbdriver' => 'mysqli',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);
$db['default']['failover'] = array(
	array(
		'hostname' => 'localhost',
        'username' => 'root',
        'password' => '',
        'database' => 'site_abc',
        'dbdriver' => 'mysqli',
        'dbprefix' => '',
        'pconnect' => TRUE,
        'db_debug' => TRUE,
        'cache_on' => FALSE,
        'cachedir' => '',
        'char_set' => 'utf8',
        'dbcollat' => 'utf8_general_ci',
        'swap_pre' => '',
        'encrypt' => FALSE,
        'compress' => FALSE,
        'stricton' => FALSE
	)
);

I deliberately misconfigured the main connection for testing the failover feature. But it does not work.

I got error:

> A PHP Error was encountered
> Severity: Warning
> Message: mysqli::real_connect(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
> Filename: mysqli/mysqli_driver.php
> Line Number: 201

**Comment by gxgpet** [comment]
Who would ever think that Google's DB access credentials are `root` and ` `?

**Comment by lebanggit** [comment]
> I deliberately misconfigured the main connection for testing the failover feature. But it does not work.

**Comment by narfbg** [comment]
The error message doesn't mean it doesn't work.

**Comment by adomasalcore3** [comment]
@lebanggit 
> $db['default'] = array(
[...]
'stricton' => FALSE,
'failover' => array(),
[...] );

Have you seen the config item: 
>'failover' => array(),

?

**Comment by lebanggit** [comment]
how to simulate for this.

**Comment by narfbg** [comment]
Turn off `db_debug`.
