### ISSUE TITLE
PHP >= 7 session problem

### ISSUE THREAD

**Issue by phaidon** [bcit-ci/CodeIgniter#5118]
After I changed to php 7.0 I get from time to time the following error:

HP Fatal error: Class CI_Session_files_driver contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (SessionHandlerInterface::read) in C:\..\system\libraries\Session\drivers\Session_files_driver.php on line 49

A restart of apache solves the issue for a while. The same thing happens with php 7.1

I am using CodeIgniter 3.1.4. I did not change the system dir.

The the session files are stored in a folder. $config['sess_driver'] = 'files';

Any idea? Thanks a lot for your help.

It just happens with one of my websites. An other website that is not visited so much is not affected.

**Comment by narfbg** [comment]
https://stackoverflow.com/questions/42503240/intermittent-php-abstract-class-error

**Comment by Sozialarchiv** [comment]
Thank you for the fast reply.

**Comment by aniket-bheeshma** [comment]
Yes, this is big issue. I faced same and solved this, see http://tekina.info/solving-session-problems-codeigniter-upgrading-php-version/
