### ISSUE TITLE
my session lost after redirect  when set sess_cookie_name 

### ISSUE THREAD

**Issue by sdfarshid** [bcit-ci/CodeIgniter#5122]
when  I set this config 

$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = '';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = sys_get_temp_dir();
$config['sess_match_ip'] = TRUE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

my session after redirect  is 
    [__ci_last_regenerate] => 1495024626
    [style_name] => style2
    [holding_id] => 1
    [lang_id] => 1
    [lg_style] => rtl
    [user_pro] => Array
        (
            [upro_ID] => 12
            [upro_uacc_fk] => 15
            [upro_ex_time] => 0
        )

But  When  i set  this  config 

$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 0;
$config['sess_save_path'] = sys_get_temp_dir();
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

my session after redirect  lost 

Array
(
    [__ci_last_regenerate] => 1495024729
)

How can I fix it ??

**Comment by narfbg** [comment]
This is a bug tracker, please post on our [forums](https://forum.codeigniter.com/) instead.
