### ISSUE TITLE
xss_clean security library

### ISSUE THREAD

**Issue by colethorsen** [bcit-ci/CodeIgniter#5125]
There is an issue in the xss_clean function where it might be a little over aggressive in stripping content.

when you run the string "100% becomes" through the xss_clean function the section on lines 377-387 strip out "% be" and the string becomes " 100�comes" this happens in any instance where the 2 characters following a percent are a-f 0-9.

I understand what this is preventing, and I'm assuming that it considers the space for good reason. So I'm not overly sure what the solution here would be.

**Comment by narfbg** [comment]
Inconvenient, indeed. But I don't see a way around #4877 without this ...

**Comment by colethorsen** [comment]
Well if that is the case wouldn't limiting the replacement to within a tag, or within a parameter inside a tag solve the issue?

**Comment by narfbg** [comment]
That's easier said than done, and while the example in #4877 uses an attribute value, it is not really clear if that's the only vector ...

**Comment by wrmond** [comment]
#4877  hot-fix is terrible idea. should check ahead if in attribute value first

**Comment by Zae** [comment]
Hi guys and gals,

I know this issue was closed a while back already, but is there anyway you could maybe look into this again?

I'm hitting this bug because I'm trying to sanitize a rich text field, but now people can't type % in their text, because it creates weird utf-8 characters.

see my ticket at [graham campbells security package](https://github.com/GrahamCampbell/Laravel-Security/issues/36)

**Comment by narfbg** [comment]
@Zae Refer to my previous comment ... Until it is proven that this is only limited to attribute values, it's not changing.

**Comment by Agimovel** [comment]
This sucks...I'm making work arounds on this but don't know if will affect security.

No solutions yet?

**Comment by mckaygerhard** [comment]
well seems guys from opensourcepos received same response .... "works for me" -> wont-fix!

**Comment by skorp** [comment]
@francoisjacquet  think the first preg_replace should be changed to this not?
 ```
$str = preg_replace('#%((?:[a-f]){2,})#i', '%25$1', $str);
 ```
because else it captures only the latest iteration


i think i will use this modification to allow strings like this: '... 60% about ....'

```
....
if (stripos($str, '%') !== false)
		{
			do
			{
				$oldstr = $str;
				$str = rawurldecode($str);
				$str = preg_replace_callback('#%(?:\s*[0-9]\s*[0-9a-f])#i', array($this, '_urldecodespaces'), $str);

			}
			while ($oldstr !== $str);
			unset($oldstr);
		}
		....
```

**Comment by mckaygerhard** [comment]
intersting.. thanks @skorp anyone that can confirm wich code works?

**Comment by francoisjacquet** [comment]
Hello @skorp 

Thank you for your feedback.
To answer your question: the first regex only matches the first occurrence, indeed. But we are in a while loop, so...

Also, I was wrong about the fact that URL encoded characters only begin with a *number*. Some do begin with letters. But as far as XSS are concerned, `<` and `>` characters do begin with a letter: `%3C` and `%3E`.

So, after a review, please prefer @skorp 's solution.
