### ISSUE TITLE
[Feature Request] [CI 4.0] CI Could have an "Installer Library" and "Update Library"

### ISSUE THREAD

**Issue by adomasalcore3** [bcit-ci/CodeIgniter#5127]
Installer Library
- Make an library for the end user, like an client, for one "application"
- - "auto" install db
- - "auto" install configs
Update Library
- Create a form of update where the programer defines an URL and if an version is avaliable, ask admin to update "automaticly"

**Comment by jim-parry** [comment]
Feature requests should be raised on the forum.
Also, this is the CI3 repository ... you might be looking for https://github.com/bcit-ci/CodeIgniter4

**Comment by adomasalcore3** [comment]
@jim-parry thanks for your reply
i didn't saw the [https://github.com/bcit-ci/CodeIgniter4](url), cause there is an milestone for the version 4 here.
also, i've didn't knew about that `Feature requests should be raised on the forum.`
thanks by the way.
