### ISSUE TITLE
ci_session_lock table dosen't exist on My database

### ISSUE THREAD

**Issue by webhacking** [bcit-ci/CodeIgniter#5129]
Currently, Codeigniter requests queries - one of them is below - every second. However, the table `ci_session_lock` does not exist and because of these queries, the other queries get delayed.

SELECT GET_LOCK('178333703bf84e4d6fba6154fce6f55bba64e99d', 300) AS ci_session_lock

This query time is :
80.227811813354

The other queries are done within 30.

**Comment by pfote** [comment]
thats not a table but a alias for the lock CI wants to aquire, and its a 
oretty lightweight operation so it surely is not the cause
somethin else on your mysql server is goin wrong, that the get_lock() 
takes that long is a ffect of that problem but not the cause

however, this is surely not a CI bug, so please refer to the Forums or 
the #codeigniter irc chan for help, the mysql community might even be a 
better option as this is clearly mysql related

**Comment by webhacking** [comment]
@pfote Thanks
