### ISSUE TITLE
Methods declared "private" no longer trigger 404

### ISSUE THREAD

**Issue by twistedpixel** [bcit-ci/CodeIgniter#5131]
Is this intended? I couldn't see it noted anywhere in the upgrade guide. This definitely worked in 3.0.4.

In 3.1.4, I receive the error `Message: call_user_func_array() expects parameter 1 to be a valid callback, cannot access private method Page::test()`

It's not a big deal; I am well aware we can use `_test()` I just wanted to check it was an intentional "break" (I use inverted commas because I don't think it was ever actually a feature).

**Comment by narfbg** [comment]
Not intended ... this is what happens when we give people [what they ask for](https://github.com/bcit-ci/CodeIgniter/commit/7bc882384ef4c442fb4edd699c8dd15bbd22e429) instead of what they need.
