### ISSUE TITLE
Not showing migration errors

### ISSUE THREAD

**Issue by skys215** [bcit-ci/CodeIgniter#5132]
Hi,

I was writing migrations these days. 
And something weird happened when I run migration: some of the table was migrated, but some didn't.
After debugging, I found [here](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_forge.php#L349)  has no `else clause` written.
That cause no error was neither displayed nor logged.

I added such code after the `if{...}` to show the error while migration.
```php
       else{
            echo $table.': '.$this->db->error()['message'];
            exit;
        } 
```

Hope there is a official implementation of showing error when migration fails.
Thanks.

**Comment by narfbg** [comment]
You write the migrations, and you decide whether and *what* error message should be shown, not the framework.
