### ISSUE TITLE
tailable cursor requested on non capped collection

### ISSUE THREAD

**Issue by kruti369** [bcit-ci/CodeIgniter#5133]
When i use this library and execute  query like i am getting error
"error processing query: ns=testdb.mongo_users batchSize=10 limit=10Tree: $and Sort: {} Proj: {} tailable cursor requested on non capped collection"

**Comment by narfbg** [comment]
I don't know what "this library" is, but you're certainly in the wrong place.

**Comment by DharmalingamViky** [comment]
am also facing this issue ERROR [stderr] (Thread-690)  tailable cursor requested on non capped collection'
