### ISSUE TITLE
cache store issue

### ISSUE THREAD

**Issue by shubhampatel30** [bcit-ci/CodeIgniter#5136]
in CI, when we start storing cache file for a particular controller, and first time when we user login and use this controller, it will be created a cache file related to this controller and second time when reload the page it uses this cache file. 

But when user login in other browser with different info, it also share the samr cache file for newly login user either than create new new cache file for recent login user.Means it use same user data in both browser. It's a big issue regarding user security.

**Comment by narfbg** [comment]
Caching is not magic. It's not always a good thing.

**Comment by shubhampatel30** [comment]
ok thanks

**Comment by shubhampatel30** [comment]
can we store cache for specific thread in CI.
