### ISSUE TITLE
Custom Exception Types

### ISSUE THREAD

**Issue by luckydonald** [bcit-ci/CodeIgniter#5137]
Hey, I've seen some of the migrations to exceptions going on. #4189
Seeing PR #4220, you throw many `RuntimeException`s.
Maybe you could create some sublasses to the standard exceptions to make that more verbose?

In [that example](https://github.com/bcit-ci/CodeIgniter/pull/4220/files#diff-52ac820fcb46a62efd324a9e44f8cbd7R589), instead of a plain `RuntimeException` maybe a `FileNotFoundException`?
```php
class FileNotFoundException extends RuntimeException
```

What are your thoughts about that?

**Comment by luckydonald** [comment]
Coming from python, a often used practice is to even have a base exception type which is used throughout the library.

Maybe like this?
```php
class CI_Exception extends Exception { /* ... */ }

class FileNotFoundException extends CI_Exception { /* ... */ } // like #4216
class DatabaseException extends CI_Exception { /* ... */ }  //  like #4172
```
(#4216 #4172)

**Comment by narfbg** [comment]
We'd have to migrate everything to exceptions first, this looks way ahead in time.
But either way - not a fan of declaring countless exception classes for countless error cases.
