### ISSUE TITLE
where i extends Controller, and rewrite __construct, get error

### ISSUE THREAD

**Issue by deliangyang** [bcit-ci/CodeIgniter#5138]
TypeError
Argument 3 passed to App\Core\MY_Controller::__construct() must be an instance of CodeIgniter\Log\Logger, none given, called in /Users/deliang/Work/work/CodeIgniter4/system/CodeIgniter.php on line 706

**Comment by jim-parry** [comment]
This is the wrong repo. You want https://github.com/bcit-ci/CodeIgniter4.
Or, this sounds more like a mistake on your part, and should perhaps be posted on the forum.
We use github issues to track bugs and approved work packages.
