### ISSUE TITLE
session problem in localhost

### ISSUE THREAD

**Issue by a4ankii** [bcit-ci/CodeIgniter#5140]
Getting the error in codeigniter 2.1.3.
"An Error Was Encountered

In order to use the Session class you are required to set an encryption key in your config file."
i am getting this error even after setting up the encryption key.
please help me out Asap.

**Comment by narfbg** [comment]
This is a bug tracker, we don't provide help here. Ask your questions on our [forums](https://forum.codeigniter.com/) instead, and stop using CI2 - it's abandoned.

Also, don't ask strangers on the internet to do something for you "ASAP".
