### ISSUE TITLE
Issue on PHP 5.6.3 and Codeigniter 3.1.4

### ISSUE THREAD

**Issue by aa6my** [bcit-ci/CodeIgniter#5147]
I have issue on production server with latest codeigniter version which is 3.0.4

```
Fatal error: Call to a member function getMessage() on integer in /home/xxx/system/core/Common.php on line 65
A PHP Error was encountered
Severity: Error
Message: Call to a member function getMessage() on integer
Filename: core/Common.php
Line Number: 653
Backtrace:
```

**Comment by narfbg** [comment]
Latest version is 3.1.4, not 3.0.4.

Looks like something has set `_exception_handler()` to be your *error* (not exception) handler. But that something is not CI, and this is a bug tracker ... if you need help, please ask for it on our [forums](https://forum.codeigniter.com/) instead.
