### ISSUE TITLE
Extending Cache Driver / Cache

### ISSUE THREAD

**Issue by huehnerhose** [bcit-ci/CodeIgniter#5148]
I wanted to extend the redis cache driver and used the same pattern i used for extending for example the benchmarking class. 

My extended driver didn't get load. 

I created a file in `application/core/PREFIX_Cache_redis.php` containing a `PREFIX_Cache_redis` class extending the `CI_Cache_redis` class. I also done this for `Cache` 

Both classes don't get loaded. I tried to find my way through `Loader.php` and think that the `_ci_load_stock_library` Function doesn't try to load `PREFIX_class`.

**Comment by narfbg** [comment]
It doesn't work quite like that, and this is documented.
If you need to ask someone for help, please do it on our [forums](https://forum.codeigniter.com/).
