### ISSUE TITLE
null return when loading static class externally

### ISSUE THREAD

**Issue by alonagar** [bcit-ci/CodeIgniter#5151]
I am using a native Autoload - by Phil Sturgeon, that triggered by calling to a lib:
i.e.
calling to `User_lib::getUser();` will load the class automatically.

I am also having auto loading through a __get() magic function in a parent I had created called "MY_Controller" so just calling to $this->user_lib->get_user()  will load it.

here is the line of code in My_Controller:__get()
```
function __get($property){
...
if($suffix=='lib'){
   $this->load->library($property);
}
...
//property here will be `user_lib`
return $this->$property;
```

This works great, as long as I am calling only static calls, or using 
$this->user_lib->do_something()
User_lib::getUser();

but create a bug in the next situation, if I am calling: 

`User_lib::getUser();`

and then:
```
$this->user_lib->do_something()
```

I will get an Exception:
"msg": "Call to a member function get_user() on null"

I had tracked down the problem to this line in the /system/core/loader.php  
CI_Loader::_ci_load_library() line - 1052
```
			// Safety: Was the class already loaded by a previous call?
			if (class_exists($class, FALSE))
			{
				// Before we deem this to be a duplicate request, let's see
				// if a custom object name is being supplied. If so, we'll
				// return a new instance of the object
				if ($object_name !== NULL)
				{
					$CI =& get_instance();
					if ( ! isset($CI->$object_name))
					{
						return $this->_ci_init_library($class, '', $params, $object_name);
					}
				}

				log_message('debug', $class.' class already loaded. Second attempt ignored.');
				return;
			}
```

as you can see in line 1057 `if ($object_name !== NULL)` it just checks if we are trying to load the class into a new name, but there is no checking for if the class loaded by CI.

on line 1067 there is `return;` and this is the null that I am getting

suggest to fix it by adding the next code before line 1067 (`return;`)
```
if ( ! isset($CI->$class)){
    return $this->_ci_init_library($class, '', $params, $object_name);
}

```

Thanks!

**Comment by narfbg** [comment]
Sorry, but that's a side-effect caused by your and/or third-party code ... we can't treat it as a bug.
