### ISSUE TITLE
mcrypt is deprecated in PHP 7.1.x

### ISSUE THREAD

**Issue by scriptsdemostack** [bcit-ci/CodeIgniter#5157]
Hello!
I'm using CI's encription library in my CI based app. it's working fine on PHP 5.x versions. but today I tested that app against PHP v7.1.5 and got list of mcrypt depricated warning list. and heared that mcript library gonna remove from PHP 7.2. 

<img src="https://image.prntscr.com/image/5Yy1YQLQQ0mfhnSB14dzvA.png">

Thanks.

**Comment by narfbg** [comment]
You'd have to explicitly tell the library to use mcrypt ... OpenSSL is the default.

**Comment by flavienbwk** [comment]
Here is a way to solve the problems : 

```
	/**
	 * Encrypt using Mcrypt
	 *
	 * @access	public
	 * @param	string
	 * @param	string
	 * @return	string
	 */
	function mcrypt_encode($data, $key)
	{
		$salt = 'cH!swe!retReGu7W6bFQ0F9QHZF908QZHFQ9PZFhsfçhpq_sfqhfçzà_h';
		$iv_size = openssl_cipher_iv_length("AES-256-CBC-HMAC-SHA256");
		$hash = hash('sha256', $salt . $key . $salt);
		$iv = substr($hash, strlen($hash) - $iv_size);
		$key = substr($hash, 0, 32);
		$encrypted = base64_encode(openssl_encrypt($data, "AES-256-CBC-HMAC-SHA256", $key, OPENSSL_RAW_DATA, $iv));

		return $encrypted;
	}

	// --------------------------------------------------------------------

	/**
	 * Decrypt using Mcrypt
	 *
	 * @access	public
	 * @param	string
	 * @param	string
	 * @return	string
	 */
	function mcrypt_decode($data, $key)
	{
		$salt = 'cH!swe!retReGu7W6bFQ0F9QHZF908QZHFQ9PZFhsfçhpq_sfqhfçzà_h';
		$iv_size = openssl_cipher_iv_length("AES-256-CBC-HMAC-SHA256");
		$hash = hash('sha256', $salt . $key . $salt);
		$iv = substr($hash, strlen($hash) - $iv_size);
		$key = substr($hash, 0, 32);
		$decrypted = openssl_decrypt(base64_decode($data), "AES-256-CBC-HMAC-SHA256", $key, OPENSSL_RAW_DATA, $iv);
		$decrypted = rtrim($decrypted, "\0");

		return $decrypted;
	}
```

**Comment by narfbg** [comment]
@flavienbwk This isn't a place to post random solutions.

Especially when it comes to cryptography, you shouldn't post such things anywhere. It's a field of its own, a hard one, and just because something you made "works", doesn't make it secure.

And finally, *Encrypt.php* is the old, deprecated library that nobody should be using anymore. We've only kept it for backwards compability. You should be using *Encryption.php* which supports and defaults to OpenSSL.
