### ISSUE TITLE
Feature request: Throw error when passing an array to log_message() as it causes PHP to hang

### ISSUE THREAD

**Issue by richardwo** [bcit-ci/CodeIgniter#5158]
In error I passed an array to the log_message function. The server just hangs and doesn't respond. 
Code to reproduce:

```
class Test extends CI_Controller {

	public function index()
	{
		$myarray = array();
		log_message("debug", $myarray);
		echo 'This has worked';
	}

}
```

The documentation is clear that a string should be passed to log_message so this isn't a bug but it would be nice to throw an error instead of leaving the server hanging.
(Environment: Ubuntu 14.04)

**Comment by narfbg** [comment]
I get it, but no ... we can't do that, sorry.
