### ISSUE TITLE
matches, min_length, max_length gives 500 internal server error

### ISSUE THREAD

**Issue by flexsingit** [bcit-ci/CodeIgniter#5161]
Hello,

All the validation rules having parameters in them are giving internal server error ,

$this->form_validation->set_rules('password', 'Password', 'required|min_length[6]|max_length[12]');
$this->form_validation->set_rules('confirm_password', 'Password Confirmation', 'required|min_length[6]|max_length[12]|matches[password]');

**Comment by narfbg** [comment]
Can't reproduce.  
We also have unit tests that cover this.  
Don't [spam other issues](https://github.com/bcit-ci/CodeIgniter/issues/1957#issuecomment-310606867).  
Error 500 means server-side error, which in turn gives us zero info.

What the hell are we supposed to do with no details provided at all?

**Comment by flexsingit** [comment]
whenver i am removing the min_length and other such validations it works but when i put them back i am having internal server error. I don't think that server needs to do here.
Please let me know what sorts of details you need from me ?

**Comment by narfbg** [comment]
Meaningful PHP error messages.

**Comment by flexsingit** [comment]
Well! i just tested them on the php version 5.5.9-1and the same code works, some thing is broken on php 5.6 for these rules. This is the only sort of details that i have. 

Thanks for your support.

**Comment by narfbg** [comment]
We do run those unit tests on all supported PHP versions: https://travis-ci.org/bcit-ci/CodeIgniter

**Comment by flexsingit** [comment]
Well! i respect all the help that you provided. 

But can some one make a chagne to the documentation saying that mbstring should be installed in order to use those functions ?

**Comment by GDmac** [comment]
It's already in the documentation: http://php.net/manual/en/mbstring.installation.php

**Comment by flexsingit** [comment]
Thanks for responfing guys. 

But my concern is that inmany other frameworks like  YII they used to have a requirements page which provides the complete list of the extensions which needs to be installed with the framework. 

However on the requirements page of CI they haven't mentioned that mbstring is required in order to work on CI. 

Am i wrong on this?

Regards

**Comment by narfbg** [comment]
You're running CI2, aren't you?
