### ISSUE TITLE
Loader.php _ci_load_library method has a bug

### ISSUE THREAD

**Issue by ppanphper** [bcit-ci/CodeIgniter#5164]
![image](https://user-images.githubusercontent.com/6057923/27582913-3bdf7afc-5b65-11e7-89a9-d4f0ba24b91f.png)
if first loaded library set object_name Initialized library.
second loaded library not set object_name, result is return. 
so, loaded library fail.

:) sorry, I do not speak English, hope you can understand what I mean！

**Comment by narfbg** [comment]
Please test with the commit linked above.

Also, for future reference - please provide actual code and/or text instead of screenshots.

**Comment by GrahamDj** [comment]
Isn't it maybe better to always load a library as an alias?

`if( $object_name === NULL )`
`{`
`    $object_name = $library;`
`}`

`$this->_ci_load_library($library, $params, $object_name);`
`return $this;`

**Comment by ppanphper** [comment]
@narfbg 

eg:
$this->load->library('test', null, 'test1');
$this->load->library('test');
because first load library included 'test' class,
so second load library don't included 'test' class, and no set object_name, then return void.

I use version is 2.2.1, may be used method not be the same.

**Comment by ppanphper** [comment]
Fixed the bug in the version 2.2.1

if (in_array($filepath, $this->_ci_loaded_files))
{

	// Before we deem this to be a duplicate request, let's see
	// if a custom object name is being supplied.  If so, we'll
	// return a new instance of the object
	$CI =& get_instance();
	$strLowerClass = strtolower($class);
	$classVar = $this->getClassVar($strLowerClass, $object_name);
	if ( ! isset($CI->$classVar))
	{
		return $this->_ci_init_class($class, '', $params, $object_name);
	}
	$is_duplicate = TRUE;
	log_message('debug', $class." class already loaded. Second attempt ignored.");
	return;

}



`protected function getClassVar($class, $object_name) {`
        `if (is_null($object_name))`
	`{`
		`$classvar = ( ! isset($this->_ci_varmap[$class])) ? $class : $this->_ci_varmap[$class];`
	`}`
	`else`
	`{`
		`$classvar = $object_name;`
	`}`
	`return $classvar;`
`}`

**Comment by narfbg** [comment]
@GrahamDj No.
@ppanphper CI2 is no longer supported. Stop using it.

**Comment by ppanphper** [comment]
@narfbg Production project... :(

**Comment by narfbg** [comment]
That only means you need to upgrade quicker.

**Comment by GrahamDj** [comment]
@narfbg 
Your fix does not work on stock libraries

**Comment by ppanphper** [comment]
@narfbg second param if set '', isset($property) is true

**Comment by narfbg** [comment]
@GrahamDj Good point, fixed in next commit.
@ppanphper Figured that out while fixing the stock libs ... also fixed.

**Comment by GrahamDj** [comment]
Just wondering but why is this not a correct fox for the issue?

$prefix = 'CI_';
		
if( ( class_exists($prefix.$class, FALSE) || class_exists($class, FALSE) ) && empty($object_name) )
{
	$object_name = strtolower($class);
}

**Comment by narfbg** [comment]
What we're fixing here is an erroneous property existence check, while what you suggested is forcefully modifying another variable, which alters other logic down the line. Nobody said it's incorrect code, but it does more than we need - a hacky *approach* towards bug fixing. That's how you end up with a bugfix causing 2 new bugs.

It may turn out to be just fine, but I haven't evaluated or tested it. If it happens to reduce complexity, we may do that as well, but not as a part of this bugfix.

**Comment by GrahamDj** [comment]
@narfbg 
Thanks for the info

**Comment by GrahamDj** [comment]
Maybe I'm missing something but I don't think this does anything

`isset($this->_ci_varmap[$property]) && $property = $this->_ci_varmap[$property];`

No where can I find the requested class being added to the array _ci_varmap

But it is being added to the array _ci_classes on line 1278

**Comment by narfbg** [comment]
It's a pre-defined list: https://github.com/bcit-ci/CodeIgniter/blob/be0280d02a408a8b4aeb6aee10d9dd936f978ce2/system/core/Loader.php#L122

**Comment by GrahamDj** [comment]
Ah yes, I now see whats going on :)

**Comment by Spidi** [comment]
It's worth noting that after this fix (i.e. between 3.1.5 and 3.1.6) if you have two libraries that load each other you will always hit a nested loop limit as the libraries will endlessly try and load each other. Just for anyone upgrading from earlier versions of codeigniter, using some "interesting" coding techniques, to the latest.
