### ISSUE TITLE
Possible bug - Form validation

### ISSUE THREAD

**Issue by hamlington** [bcit-ci/CodeIgniter#5165]
Hi,

Not sure if this is a bug or I have done something incorrect, I am using the discrete methods on the form validation library, the following code seems to have a minor bug:

if($this->form_validation->min_length($pword,8)===false){$this->form_validation->set_message('oldPassword',$this->lang->line('form_validation_min_length')); return(false);}

this doesn't seem to add the number 8 to the param field in the message:
'The {field} field must be at least {param} characters in length.'

does appear to be working in terms of actually checking the min number and the message does appear, just the param is missing the value, the field part appears correctly in the message.

Any ideas?

thanks

Paul.

**Comment by narfbg** [comment]
Not a bug.

If you're looking for help, please post on our [forums](https://forum.codeigniter.com/) instead.

**Comment by hamlington** [comment]
Any explanation to what the problem is here, not a very helpful answer, I said it might have been a bug but as there is no real explanation in the guide to how you call this method I was just guessing, when searching online I couldn't find any explanation to it either.

**Comment by narfbg** [comment]
It's not a very helpful answer because this is a bug tracker, and we don't provide help here.
We do that on our [forums](https://forum.codeigniter.com/), which is why I suggested you ask there.

I'm sorry if you're not happy with that, but it is what it is.

**Comment by hamlington** [comment]
wont be wasting anymore time here.
