### ISSUE TITLE
Query Builder fail when field names have whitespaces

### ISSUE THREAD

**Issue by n3rvio** [bcit-ci/CodeIgniter#5171]
I am using a table in MySQL like this;

```
CREATE TABLE IF NOT EXISTS `TestTable` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`Entry No_` INT(11) NOT NULL,
	`Posting Date` DATETIME NOT NULL,
	PRIMARY KEY (`ID`));

INSERT INTO `TestTable` (`ID`, `Entry No_`, `Posting Date`) VALUES
	(1, 33216, '2017-07-04 13:26:34'),
	(2, 63543, '2017-07-05 13:26:46');
```

When I try to get records by filtering from \`Entry No_\` the SQL query that is generated is erroneous;
```
$this->db->where('Entry No_', '33216');
$query = $this->db->get('TestTable');
```
**SQL>** SELECT * FROM \`TestTable\` WHERE Entry No_ '33216'
**Bad, CodeIgniter assume there are two tables, bad syntax and not included '='**

I have tried these other ways, and all of them are wrong:
## TEST 1
```
$this->db->where('`Entry No_`', '33216'); 
```
**SQL>** SELECT * FROM \`TestTable\` WHERE \`Entry No_\` '33216'
**Bad syntax, '=' not included**

## TEST 2
```
$this->db->where('Entry_No_', '33216');
```
**SQL>** SELECT * FROM \`TestTable\` WHERE \`Entry_No_\` = '339111'
**Good syntax query, but the table not exist..**

## TEST 3
```
$this->db->where('Entry\ No_', '33216');
```
**SQL>** SELECT * FROM \`TestTable\` WHERE Entry\ No_ '33216'
**Bad name table.**

## TEST 4
```
$this->db->where('"Entry No_"', '33216');
```
**SQL>** SELECT * FROM \`TestTable\` WHERE "Entry No_" '33216'
**Bad syntax**

I am using CodeIgniter-3.1.5 in LAMP server.

**Comment by narfbg** [comment]
Same thing as #1649, #2755 ... it was never supported.

**Comment by n3rvio** [comment]
Why?
MySQL supports names of tables and fields with spaces, this should not be a limitation in CodeIgniter.

I know that using spaces for names of tables or fields is not a good practice. 
In my case, the SQL database is from ERP software (Microsoft Dynamics Nav), and I'm afraid I can't make major modifications here.

I'll look for another way to read data from my ERP ..

Thanks
