### ISSUE TITLE
Table alias for subquery

### ISSUE THREAD

**Issue by jhon312020** [bcit-ci/CodeIgniter#5176]
While adding the sub query then the main query automatically add table prefix to sub query once again.
For example:
I wrote the sub query and get it using get_compiled_select method. the table name is orders. So it will append the prefix for each column of the table. such as `tbl_orders`.`id`. While append the query to main query. The main query also add table prefix like  'tbl_orders.tbl_`id' then it throws the unknown column error. Kindly help us to fix the problem.

**Comment by narfbg** [comment]
This is a bug tracker, we don't provide support here. Please post on our [forums](https://forum.codeigniter.com/) instead.
