### ISSUE TITLE
PHP 7.1.6 Session Cookie Unsets

### ISSUE THREAD

**Issue by khgoldberg** [bcit-ci/CodeIgniter#5177]
Frankly, I don't fully understand the `_configure_sid_length()` method, but I found while running CentOS 7 with PHP 7.1.6, that my session cookie was getting reset every browser refresh.

I traced it to this condition:

`OR ! preg_match('#\A'.$this->_sid_regexp.'\z#', $_COOKIE[$this->_config['cookie_name']])`

which led me to the `_configure_sid_length()` method and your comments about PHP 7.1 which supported my conclusion.

I've commented out this condition in my code, and the session cookie now persists properly (though clearly there is a condition not being addressed since I've commented out the `preg_match`).

In any case, I thought I'd point it out in case it's something you can fix.

And thanks for an amazing piece of software!

**Comment by narfbg** [comment]
Please provide your `session.sid_length` and `session.sid_bits_per_character` values.

**Comment by khgoldberg** [comment]
session.sid_length:40
session.sid_bits_per_character :4 

Oh, and I'm using CI 3.1.5

**Comment by narfbg** [comment]
With those settings, you should be getting 40 hexadecimal digits and `$this->_sid_regexp = '[0-9a-f]{40}';`, which matches perfectly. The only scenario to reject legitimate cookies is if they were previously generated with a different configuration.

Can you verify that?

**Comment by khgoldberg** [comment]
Ok.
Here's what I can tell you.

cookie_name:ci_session
$_COOKIE[cookie_name]:e6058f135fa438a9388980c89b468e86
PHP_VERSION_ID:70106
session.sid_length:40
session.sid_bits_per_character:4 

However, when I look at phpinfo(), it shows
session.sid_bits_per_character | 4 | 4
session.sid_length | 32 | 32

Which makes sense when you look at the cookie which is 32 characters.

Since my PHP Version is > 70100, the following code is executed which looks like it's setting a "local" version of the sid_length to 40

`		{`
`			$bits_per_character = (int) ini_get('session.sid_bits_per_character');`
`			$sid_length         = (int) ini_get('session.sid_length');`
`			if (($bits = $sid_length * $bits_per_character) < 160)`
`			{`
`				// Add as many more characters as necessary to reach at least 160 bits`
`				$sid_length += (int) ceil((160 % $bits) / $bits_per_character);`
`				ini_set('session.sid_length', $sid_length);`
`			}`
`		}`

So my _guess_ is that the cookie is being set prior to the sid_length being set which is why the regular expression fails every time since the cookie is 32 characters, not 40.

Another detail that may be relevant is that this is an upgrade from CI 2.1.3.
I'm pretty sure I followed all the instructions diligently and actually upgraded in three steps (2.2.6, 3.0.6, 3.1.5) -- certainly deleting the system folder before replacing it - but that could be relevant if what I wrote above doesn't make sense.

**Comment by narfbg** [comment]
That can only happen if you are manually calling `session_start()`, before loading the session library and/or have `session.auto_start` enabled. Which means the library wouldn't work anyway ... this isn't a CI bug.

If you need more help, please post on our [forums](https://forum.codeigniter.com/) as we only deal with bug reports here.
