### ISSUE TITLE
Is it safe to use the Shopping Cart class?

### ISSUE THREAD

**Issue by ChangePlaces** [bcit-ci/CodeIgniter#5179]
I read in the docs that the class has been deprecated, but also elsewhere that the reason it was deprecated was due to security problems with insecure session handling from version 2.0 which apparently has been fixed in 3.x. 

Is this still the case? Should I avoid using it?

**Comment by narfbg** [comment]
Deprecated means deprecated ... I don't know what "elsewhere" is, but the only authoritative resources (i.e. ones you should trust) are on codeigniter.com.

Also, this is a bug tracker. In the future, please post your questions on our [forums](https://forum.codeigniter.com/) instead.

**Comment by ChangePlaces** [comment]
for reference: https://stackoverflow.com/questions/31077476/is-it-safe-to-use-codeigniter-shopping-cart

I'm very aware what 'deprecated' means, that was not my question and in no way even attempts to answer the question. Also, this is an issue tracker, not a bug tracker. The difference being "issues means issues"...

Also, you never know who you're talking to. In the future, please use a less passive-aggressive tone instead.

**Comment by narfbg** [comment]
> I'm very aware what 'deprecated' means, that was not my question and in no way do you even attempt to answer the question

It's not a detailed answer, but it does answer the question.
If you don't think it does, then you're certainly not that aware of what "deprecated" means.

> or show you have any knowledge of the problem at hand

I've been maintaining CI for the past ~5 years and it was me who deprecated `CI_Cart`. You will not find a person more knowledgeable on this.

> Also, this is an issue tracker, not a bug tracker. The difference being "issues means issues"...

No, this is GitHub putting the label "Issues" on a feature that their service provides. We choose to use the said feature as a bug tracker, and bug tracker alone. Hence why we redirect **all** support-like questions to our [forums](https://forum.codeigniter.com/). Please respect our rules.

> Also, you never know who you're talking to. In the future, please use a less passive-aggressive tone instead.

I am not known for being the friendliest person on Earth, that is true. But while my previous reply wasn't the detailed answer I'm guessing you expected, it was still respectful. You on the other hand are being openly aggressive.

**Comment by ChangePlaces** [comment]
It's fair to say you're behaving like an idiot and I assume you have... "issues". 

Congratulations on all that you've written above. You are trying to come across as superior yet unable to answer a question on this, and I quote, "Issue tracker". You may even call it a tomato, but it's an issue tracker. You're wrong (though it's going to be easier to move the blame onto me, rather than accept that)

The CI foundation should keep you the furthest away from the public as it possibly can - you have the social skills of... a tomato and are doing a big disservice to CI. You evidently don't understand the concept of 'respectful' if you think your first answer is 'respectful (I actually lol'd out loud).

**Comment by jim-parry** [comment]
@ChangePlaces 

https://www.codeigniter.com/community says 
"The Github repository is where you can file bug reports (Github issues), or where you can submit pull requests for enhancements to or fixes for the framework. Github is *not* for support or help, use the forum instead.

Github issues are also used for tracking planned and approved enhancements, often tied into specific releases."

If you have an "issue" with using Github issues this way, bring it up on the forum.

**Comment by narfbg** [comment]
No, no ... this may not be worth responding to, but it ain't getting buried.

Here's the deleted comment from @ChangePlaces:

> It's fair to say you're behaving like an idiot and I assume you have... "issues".
>
> Congratulations on all that you've written above. You are trying to come across as superior yet unable to answer a question on this, and I quote, "Issue tracker". You may even call it a tomato, but it's an issue tracker. You're wrong (though it's going to be easier to move the blame onto me, rather than accept that)
>
> The CI foundation should keep you the furthest away from the public as it possibly can - you have the social skills of... a tomato and are doing a big disservice to CI. You evidently don't understand the concept of 'respectful' if you think your first answer is 'respectful (I actually lol'd out loud).

**Comment by ChangePlaces** [comment]
So, to point out it was deleted by @jim-parry 

So, @jim-parry I assume narf is above you in the chain of ranks by undeleting something you deleted.

All these fuss and words and yet still no answer. This is the real CodeIngiter community, folks.

**Comment by gxgpet** [comment]
I shouldn't interfere, but not Jim or Narf used words such as "behaving like an idiot", 'I assume you have... "issues"', "you have the social skills of... a tomato"...

Since this is a public discussion, it would be really nice not to insult others, no matter what are their (or our) opinions. :)

**Comment by narfbg** [comment]
So let me get this straight ...

You try to tell me and the entire CI team how we should be using GitHub, because you can't be bothered to respect any rules.  
You call me passive-aggressive because my replies aren't the ass licking you get from customer support agents.  
You call me an idiot who has issues, and compare me to a tomato.  
You're now commenting on some imaginary chain of ranks within CI, just so you have something else to say about us. In fact, you even edited that last comment only to say again that I'm being passive aggressive.

And after all of this, you have the nerve to complain about not getting "constructive answers"?! Here's one thing I'll tell you about this community that you can't even spell the name of: people like you are not welcome in it.
