### ISSUE TITLE
Query Builder count_all_results not working when joining tables each having same column name

### ISSUE THREAD

**Issue by blasto333** [bcit-ci/CodeIgniter#5180]
Query builder code

    $this->db->from('message_receiver');
    $this->db->join('messages','messages.id=message_receiver.message_id');	
    $this->db->where('receiver_id',1);		
    $this->db->where('message_read',0);		
    $this->db->where('deleted',0);
    $this->db->limit(20);
    $this->db->offset(0);
    $ret = $this->db->count_all_results();

Ci 3.1.5 output of SQL query:

    SELECT COUNT(*) AS `numrows` FROM 
    ( SELECT * FROM `phppos_message_receiver` 
    JOIN `phppos_messages` ON `phppos_messages`.`id`=`phppos_message_receiver`.`message_id` 
    WHERE `receiver_id` = '1' AND `message_read` =0 AND `deleted` =0 LIMIT 20 ) CI_count_all_results

Database ERROR:
**Duplicate column name 'id'**

CI 3.1.4 output of SQL query:

    SELECT COUNT(*) AS `numrows` FROM `phppos_message_receiver` 
    JOIN `phppos_messages` ON     
    `phppos_messages`.`id`=`phppos_message_receiver`.`message_id` WHERE `receiver_id` = '1' 
		AND `message_read` =0 AND `deleted` =0 LIMIT 20

NO ERROR

Summary:

It seems CI 3.1.5 is putting the query as a sub select which causes issues when 2 tables with the same column "id" in both tables.

**Comment by narfbg** [comment]
See #5155.

**Comment by blasto333** [comment]
I don't agree with this fix; it breaks perfectly valid queries in 3.1.4

**Comment by narfbg** [comment]
SQL being valid is one thing. `count_all_results()` returning the correct number is different.

**Comment by blasto333** [comment]
Would your recommendation to fix be to make sure all queries that use
count_all_results with joins to now do select (*)

--
Chris Muench

On Jul 11, 2017, at 8:46 AM, Andrey Andreev <notifications@github.com>
wrote:

SQL being valid is one thing. count_all_results() returning the correct
number is different.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bcit-ci/CodeIgniter/issues/5180#issuecomment-314431981>,
or mute the thread

**Comment by narfbg** [comment]
No, there's nothing to fix here. `count_all_results()` is meant to be applied to full queries, and without specifying the fields to select, your query is ambiguous on the `id` field.

**Comment by blasto333** [comment]
In my my case how would I go about fixing?
What are full queries?
--
Chris Muench

On Jul 11, 2017, at 8:53 AM, Andrey Andreev <notifications@github.com>
wrote:

No, there's nothing to fix here. count_all_results() is meant to be applied
to full queries, and without specifying the fields to select, your query is
ambiguous on the id field.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bcit-ci/CodeIgniter/issues/5180#issuecomment-314433780>,
or mute the thread

**Comment by narfbg** [comment]
Use `select()` ... You'd know this if you spent more than 1 second reading my reply.
