### ISSUE TITLE
CodeIgniter unable to connect to Oracle 12c

### ISSUE THREAD

**Issue by shadeven** [bcit-ci/CodeIgniter#5184]
We recently upgraded the database from Oracle 11g to 12c. However one of the applications developed using CodeIgniter2 throws exception as below:

`ERROR_ - 2017-07-12 16:50:35 --> Severity: Warning --> oci_connect(): ORA-28040: No matching authentication protocol /system/database/drivers/oci8/oci8_driver.php 230`

It seems the build-in database driver `oci8` does not support Oracle 12c. 
Please advise. Thanks in advance.

**Comment by narfbg** [comment]
Not a CodeIgniter issue.

Also, please don't [cross-post](https://forum.codeigniter.com/thread-68448-post-345208.html#pid345208).
