### ISSUE TITLE
Making Output::set_output to parse json automatically...

### ISSUE THREAD

**Issue by markskayff** [bcit-ci/CodeIgniter#5186]
Hey, first time posting here. 
What about making the Output::set_output($param1) to parse its $param1 as json when the Output::set_content_type() matches json.

I'm telling this because now you have to do Output::set_output(json_encode($param1)) when you already setup the content type to "application/json".

**Comment by narfbg** [comment]
It's not as easy as that ...

There's multiple possible flags that one may want passed to `json_encode()`.
Plus, if we do JSON, we'd also have to do XML and any other popular format.

It's also a BC break. And last, but not least, this would probably probably (further) violate [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle).

Easy doesn't equal good. :)
