### ISSUE TITLE
Error 404 Page Not Found en Debian 8

### ISSUE THREAD

**Issue by Gooyeth** [bcit-ci/CodeIgniter#5187]
Hello, my page shows the error 404 in Debian, however in Windows it works correctly.

Apache 2.4
PHP 5.6
All modules and extensions required actived.

.htaccess

```
<ifModule mod_rewrite.c>
	RewriteEngine On

	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteRule ^(.*)$ ./index.php?/$1 [L]
</ifModule>
```

apache.conf
```
<Directory /home/gooyeth/apache/>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>

<VirtualHost *:80>
	 ServerAdmin webmaster@localhost
	 DocumentRoot /home/gooyeth/apache/web
</VirtualHost>
```

**Comment by gxgpet** [comment]
Looks like you're having a problem with server configuration, and it's not a CodeIgniter issue/bug.

If you need help for your project, please post it on the [forums](https://forum.codeigniter.com/).

**Comment by narfbg** [comment]
Indeed, this has nothing to do with CodeIgniter.
