### ISSUE TITLE
Hide Button on Codeigniter

### ISSUE THREAD

**Issue by sanditheresia** [bcit-ci/CodeIgniter#5189]
I am beginner of codeigniter

 target="__blank" href="<?php echo $burl.'/print_delivery?id='.$value['order_id']; ?>" class="btn btn-success md-trigger">

I want to hide this button action when status is completed

this is my screen shoot
![ci](https://user-images.githubusercontent.com/20878118/28259300-c8aeb2f0-6aff-11e7-8c34-ca07e15dc3c7.png)

and this is my controller
public function print_delivery()
	{
		$id_order = $this->input->get('id');

		$this->load->model('Order');
		$this->Order->updatePrintStatus($id_order);

**Comment by jim-parry** [comment]
We use github issues for bug tracking. Support questions should be asked on our [forum](https://forum.codeigniter.com/), thanks.
