### ISSUE TITLE
Minified version of safe_mailto() function

### ISSUE THREAD

**Issue by FaridAghili** [bcit-ci/CodeIgniter#5192]
Here is the minified version of safe_mailto() function which I use instead of the original function, I've named it safe_mailto_minified().

`
if ( ! function_exists('safe_mailto_minified'))
{
	function safe_mailto_minified($email, $title = '', $attributes = '')
	{
		$title = (string) $title;

		if ($title === '')
		{
			$title = $email;
		}

		$x = str_split('<a href="mailto:', 1);

		for ($i = 0, $l = strlen($email); $i < $l; $i++)
		{
			$x[] = '|'.ord($email[$i]);
		}

		$x[] = '"';

		if ($attributes !== '')
		{
			if (is_array($attributes))
			{
				foreach ($attributes as $key => $val)
				{
					$x[] = ' '.$key.'="';
					for ($i = 0, $l = strlen($val); $i < $l; $i++)
					{
						$x[] = '|'.ord($val[$i]);
					}
					$x[] = '"';
				}
			}
			else
			{
				for ($i = 0, $l = strlen($attributes); $i < $l; $i++)
				{
					$x[] = $attributes[$i];
				}
			}
		}

		$x[] = '>';

		$temp = array();
		for ($i = 0, $l = strlen($title); $i < $l; $i++)
		{
			$ordinal = ord($title[$i]);

			if ($ordinal < 128)
			{
				$x[] = '|'.$ordinal;
			}
			else
			{
				if (count($temp) === 0)
				{
					$count = ($ordinal < 224) ? 2 : 3;
				}

				$temp[] = $ordinal;
				if (count($temp) === $count)
				{
					$number = ($count === 3)
							? (($temp[0] % 16) * 4096) + (($temp[1] % 64) * 64) + ($temp[2] % 64)
							: (($temp[0] % 32) * 64) + ($temp[1] % 64);
					$x[] = '|'.$number;
					$count = 1;
					$temp = array();
				}
			}
		}

		$x[] = '<'; $x[] = '/'; $x[] = 'a'; $x[] = '>';

		$x = array_reverse($x);

		$output = "<script>var l=new Array();";

		for ($i = 0, $c = count($x); $i < $c; $i++)
		{
			$output .= "l[".$i."]='".$x[$i]."';";
		}

		$output .= "for(var i=l.length-1;i>=0;i=i-1)"
			."if(l[i].substring(0,1)==='|')document.write(\"&#\"+unescape(l[i].substring(1))+\";\");"
			."else document.write(unescape(l[i]));"
			.'</script>';

		return $output;
	}
}
`

safe_mailto() output:
![image](https://user-images.githubusercontent.com/8607021/28416301-b63f9d76-6d68-11e7-9600-35498d5652fa.png)

safe_mailto_minified() output:
![image](https://user-images.githubusercontent.com/8607021/28416345-d8ecec98-6d68-11e7-8f07-fb9ca28a1d8d.png)

I think it's a good idea to use the minified version in built in CodeIgniter functions, it could be replaced with original function.

As you see it's exactly the same as the original safe_mailto() function, just without "\n" and a little more chars.

Thank you.

**Comment by narfbg** [comment]
Sorry, but no - we need our code to be readable.

Also, please avoid using screenshots unless you absolutely need to.
