### ISSUE TITLE
Form validation library validate by callback rules behavior

### ISSUE THREAD

**Issue by SergeySmile** [bcit-ci/CodeIgniter#5198]
Hello. I'm updating project from codeigniter v2 to v3.
And found interesting behavior how form validation library works with callback rules in v3.

Problem:
If field is not required it will be anyway validate by callback even field is empty or not isset in POST.
But in the same time if field has numeric rule and field value is empty or not isset in POST - validation skips.

It's different behavior in same mechanism for built-in rules and my own. 
In codeigniter 2 if field was not required and had empty POST data - all validate is skipped:
```
// Is the field required?  If not, if the field is blank  we'll move on to the next test
if ( ! in_array('required', $ex, TRUE))
{
	if ( ! isset($_POST[$field]) OR $_POST[$field] == '')
	{
		continue;
	}
}
```
What is the reason of new behavior? It's make a hard to understand how app will work.

**Comment by narfbg** [comment]
A lot of things have changed, but this is not one. CI2 also did execute callbacks for rules that are not required.
The earliest CI version tracked here is 2.0.3 and it doesn't contain the code snipped you've posted; a google search suggests that it is from a late 1.x release.

Also, for support-like request like this one, please post on our [forums](https://forum.codeigniter.com/) instead.

**Comment by SergeySmile** [comment]
The main issue's goal not about codeigniter 2 or 3. Codeigniter 2 behavior was for example.
I wrote about codeigniter2 because old behavior of validation library was more obvious.

I  don't understand why rule: 'greater_than[5]' for 'test_field' return TRUE if 'test_field' is not isset in POST.

It means that 'greater_than' not executed if field is not set in POST but in same time any my own callback will execute anyway even if field is not isset in post. It's so curiously.
I expect that if i field must be filled up i will use REQUIRED.
