### ISSUE TITLE
generate captcha img by base64code

### ISSUE THREAD

**Issue by hyperlau** [bcit-ci/CodeIgniter#5200]
I add some code to captcha_helper.php to generate captcha img by base64code,it very useful and easy to use:
`$vars=array(
            'base64'=>true, // just add this option,false by default 
            'word_length'=>4,
            'img_width' => '200',
            'img_height'=> '40',
            'font_path'=>$this->CI->config->item('cap_font_path'),
            'font_size'=>26,
            'img_id'=>$cap_id
        );  
        $cap=create_captcha($vars);
        return $cap;
`
return img like this :
`<img id="fw066zq1WFl2aRLZF3vv0VEhSGjZhJ" src="data:image/png;base64,/9j/4AAQSkZJRgABAQEAYABgAA...0IqKdj//Z" style="width: 200; height: 40; border: 0;" alt="captcha">`
it's so easy!
[Uploading captcha_helper.php.zip…]()

**Comment by narfbg** [comment]
You haven't really uploaded anything.

But if you do want to contribute your code, please read our [contributions guide](https://github.com/bcit-ci/CodeIgniter/blob/develop/contributing.md) and do it via a pull request.
