### ISSUE TITLE
Authentication not working with php 7.1

### ISSUE THREAD

**Issue by italo1983** [bcit-ci/CodeIgniter#5205]
Hi, 
when using PHP 7.1 and latest Sprint version the session class does not work properly and users are redirected to the login page. I've substituted the Session folder inside system/libraries/ with the one from the latest CI 3 version and all seems to work properly now!

**Comment by narfbg** [comment]
This is CodeIgniter, not Sprint.

**Comment by italo1983** [comment]
Ops... sorry bad browser tab opened!
