### ISSUE TITLE
Remove incorrect comment about mime_content_type

### ISSUE THREAD

**Issue by toby-howell** [bcit-ci/CodeIgniter#5206]
The [`mime_content_type`](https://secure.php.net/manual/en/function.mime-content-type.php) function is not deprecated, but [this](https://github.com/bcit-ci/CodeIgniter/blob/6cdfed28389842c30d3d9a0022de4aa1791b23e9/system/libraries/Upload.php#L1313) comment states that it is.

[Here](https://bugs.php.net/bug.php?id=71367) is the PHP bug report for the documentation error.

**Comment by narfbg** [comment]
Thanks. But please submit pull requests if you care enough about stuff like this ... it's not worth opening an issue.
