### ISSUE TITLE
Add file name/path with line number to the log row on log file?

### ISSUE THREAD

**Issue by dnizh93** [bcit-ci/CodeIgniter#5207]
How about to add name / path / route to the log row?
It will make easier for us to find where the logs are written

This is the current log
DEBUG - 2017-07-27 06:03:58 --> UTF-8 Support Enabled
DEBUG - 2017-07-27 06:03:58 --> No URI present. Default controller set.
DEBUG - 2017-07-27 06:03:59 --> Session class already loaded. Second attempt ignored.

After add the path, it will be
DEBUG - 2017-07-27 06:03:58 - system/core/CodeIgniter.php on line 100 --> UTF-8 Support Enabled
DEBUG - 2017-07-27 06:03:58 - system/core/CodeIgniter.php on line 200  --> No URI present. Default controller set.
DEBUG - 2017-07-27 06:03:59 - application/controller/Welcome.php on line 300 --> Session class already loaded. Second attempt ignored.

Just a suggestion
Thanks

**Comment by narfbg** [comment]
It is possible that we'd backtrace the line to the `log_message()` call, but unless you call it manually, that means pointing you to internal CI code - not something you should be dealing with.
