### ISSUE TITLE
Need help about  path

### ISSUE THREAD

**Issue by 5987dogking** [bcit-ci/CodeIgniter#5211]
My CI project 
127.0.0.1/CI
The path is CI/
When URL 127.0.0.1/CI /show/1
The path is CI/show
but I want it still CI/

routes.php
$route['default_controller'] = 'welcome';
$route['wish/(:num)'] = 'welcome/wish/$1';

Welcome.php
class Welcome extends CI_Controller {
	public function index()
	{
		$this->load->view('index.html');
	}
	public function show($a){
		$this->load->helper('url');
		$data['title'] = 'help';
		$data['id'] = $a;
		$this->load->view('page',$data);
	}
}

**Comment by narfbg** [comment]
This is a bug tracker.

Please post on our [forums](https://forum.codeigniter.com/) instead.
