### ISSUE TITLE
Output errors if first line of Common.php is empty

### ISSUE THREAD

**Issue by mspringsits** [bcit-ci/CodeIgniter#5212]
I do get many strange output errors if the first line of Common.php is empty.

This only occurs on some PHP versions, but not all. Could not determine the orginal source, but if deleting the empty first line(which was placed there by me by mistake), it seems to work.

```
A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/reservierungssystem_frauenhuber/system/core/Common.php:2)

Filename: core/Security.php

Line Number: 280

Backtrace:

File: /Applications/MAMP/htdocs/reservierungssystem_frauenhuber/index.php
Line: 315
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/reservierungssystem_frauenhuber/system/core/Common.php:2)

Filename: core/Common.php

Line Number: 711```

**Comment by narfbg** [comment]
So ... why are you opening this issue then?

**Comment by mspringsits** [comment]
well, we edited the Commons file because of the statuscodes.
If there is an empty line at the beginning, I either get that empty line in my response or it simply fails... therefore it guess it is considerable to have a look at this... sorry if am wrong

**Comment by narfbg** [comment]
You're not supposed to edit stock framework files.  
This is a bug tracker. You explained an issue that you have both *created and resolved yourself*, and isn't worthy even of a [forum](https://forum.codeigniter.com/) topic.  

A look at what? An empty line is output, and you can't send headers after output. That's how HTTP and PHP work. Nobody should or could do anything about this.  
In fact, "headers already sent" is possibly the most googled-for PHP warning ever ...

**Comment by mspringsits** [comment]
it seemed to be the only way to pass custom HTTP codes for our REST API. No need to be upset, I only wanted to help - nothing more
