### ISSUE TITLE
Broken pipe error in the email library

### ISSUE THREAD

**Issue by vichenze** [bcit-ci/CodeIgniter#5213]
I faced an issue today regarding the email library. I have configured it to send emails through Pepipost SMTP, and they had connectivity issue today (according to them).
And so I end up with a log file full of 
`ERROR - 2017-08-01 17:10:33 --> Severity: Warning --> fwrite(): SSL: Broken pipe /var/www/vhosts/xxx/vendor/codeigniter/framework/system/libraries/Email.php 2131`

for thousands of line.

It seems there can be such an issue with fwrite when writing to a distant file and loosing the connection. 
http://php.net/manual/de/function.fwrite.php#96951

There is a previous bug report regarding this problem, but it has been closed : https://github.com/bcit-ci/CodeIgniter/issues/2822

**Comment by narfbg** [comment]
#2822 wasn't just closed; it was closed with a fix.
#3922 noted another related issue, which is also already fixed.
