### ISSUE TITLE
Help with Form Validation (Creating Sets of Rules)

### ISSUE THREAD

**Issue by hjJunior** [bcit-ci/CodeIgniter#5216]
I'm using  `form_validation.php` in `application/config/` folder with subs arrays

	$config = array(
		'siga_login' => array(
			array(	
					"field" => 'usuario',
					"label" => '"Usuário (Login)"',
					"rules" => 'xss_clean|trim|required|min_length[2]|max_length[60]|strtolower'
			),	
			array(	
					"field" => 'senha',
					"label" => '"Senha de acesso"',
					"rules" => 'xss_clean|trim|required|min_length[4]|max_length[30]'
			)
		),
	       // And more ... 
	);

My problem is that method `run()` don't validate using my rules, first I set the data (I know that the default is $_POST, but it's okay)

	$this->form_validation->set_data($_POST);
	if($this->form_validation->run('siga_login')===FALSE){
		// Action if has validate errors
		return;
	}else{
		// It's Okay
	}

I have extended the `Form_validation` but, everthing ok, I just added some new functions.

	class MY_Form_validation extends CI_Form_validation {

		private $enableCaptcha = true;

		public function __construct($rules=array())
		{
			parent::__construct($rules);
			$ci = &get_instance();
			$ci->load->library('recaptcha');
		}
	}

And I'm loading in `config/autoload.php`

	$autoload['libraries'] = array('database','session','encryption','form_validation');

**Comment by narfbg** [comment]
Sorry, this is a bug tracker - we don't provide help here.
Please post on our [forums](https://forum.codeigniter.com/) instead.
