### ISSUE TITLE
Form Validation Error: Callback being called even if required field is empty

### ISSUE THREAD

**Issue by marcosbaesse** [bcit-ci/CodeIgniter#5218]
Hi, I've got this problem in some form validations, I still do not know if this is a bug from CodeIgniter. 

**The problem is**:
In validation of required fields that also need pass over callbacks validations, the callback is being called even if the required field is empty.

**Example**:

```php
// $_POST['email'] is empty, 

$this->form_validation->set_rules('email', 'Email test', 'trim|required|callback_test');

.......

public function test($email)
{
    // this function should not be called if the email is empty, but it is being called
    die('Email is not empty');
}
```

**Comment by narfbg** [comment]
Not a bug.
