### ISSUE TITLE
navigator.sendBeacon() trips CSRF Protection

### ISSUE THREAD

**Issue by kojimajr** [bcit-ci/CodeIgniter#5220]
I'm using a polyfill for `navigator.sendBeacon()` which falls back to a synchronous javascript request for part of my project. However, I am getting a _403 Forbidden_ error. Turning off CSRF Protection alleviates the issue. This feels like expected behavior, since sendBeacon is still developing and due to the nature of CSRF protection, and I will likely just white-list the URI. However, is there another workaround/fix for this, or just the way the cookie crumbles?

**Comment by narfbg** [comment]
I don't even know what `navigator.sendBeacon()` is, but if you don't send the CSRF token, you get a 403 response ...

**Comment by kojimajr** [comment]
Okay this is what I figured, thank you.
For posterity: [MDN for Navigator.sendBeacon](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon)

> The navigator.sendBeacon() method can be used to asynchronously transfer a small amount of data over HTTP to a web server.
