### ISSUE TITLE
Multiple Join

### ISSUE THREAD

**Issue by prasetyo-jeanu** [bcit-ci/CodeIgniter#5222]
$this->db->select('k.name, uk.id, kerugian, reimburse')
				 ->from("unit_kerja as uk")
		                 ->join("karyawan as k","uk.karyawan = k.id AND ",'left')
		                 ->join("kerugian_reimburse as kr","uk.id = kr.unit_kerja", 'left')
				 ->where("periode",$periode);

 Result :
SELECT `k`.`name`, `uk`.`id`, `kerugian`, `reimburse` FROM `unit_kerja` as `uk` LEFT JOIN `karyawan` as `k` ON `uk`.`karyawan` = `k`.`id` **AND** LEFT JOIN `kerugian_reimburse` as `kr` ON `uk`.`id` = `kr`.`unit_kerja` WHERE `periode` = '3' ORDER BY `tgl_masuk`

correct:
SELECT `k`.`name`, `uk`.`id`, `kerugian`, `reimburse` FROM `unit_kerja` as `uk` LEFT JOIN `karyawan` as `k` ON `uk`.`karyawan` = `k`.`id`  LEFT JOIN `kerugian_reimburse` as `kr` ON `uk`.`id` = `kr`.`unit_kerja` WHERE `periode` = '3' ORDER BY `tgl_masuk`
without **AND**

**Comment by narfbg** [comment]
You put the `AND` there, not CI.
