### ISSUE TITLE
Apache Php MySQL stack installation Issue

### ISSUE THREAD

**Issue by bill-goldberg** [bcit-ci/CodeIgniter#5223]
I have a stack installation for apache php and mysql on my windows machine.
the root directory is htdocs where i put the codeigniter directory.
the codeigniter is successfully installed as i can see the welcome page.
But when i click on "user guide" it shows me the directory listing instead of showing the user guide for codeigniter.
![codeigniter](https://user-images.githubusercontent.com/23611136/29352980-56d6aa9a-8286-11e7-8ead-240fa844a485.jpg)

**Comment by bill-goldberg** [comment]
![codeigniter](https://user-images.githubusercontent.com/23611136/29353056-8d8cc916-8286-11e7-9dbd-fd074b492b88.jpg)

**Comment by narfbg** [comment]
This is an Apache configuration issue, not a CI one.

Also, please note that this is a bug tracker. Ask your questions on our [forums](https://forum.codeigniter.com/) instead.
