### ISSUE TITLE
xss_clean() issue when percent sign before space and hex characters

### ISSUE THREAD

**Issue by nicolasduranl** [bcit-ci/CodeIgniter#5225]
The following part of the `xss_clean()` function in `core/Security.php` return bad characters that can generate issues later:

```PHP
/*
 * URL Decode
 *
 * Just in case stuff like this is submitted:
 *
 * <a href="http://%77%77%77%2E%67%6F%6F%67%6C%65%2E%63%6F%6D">Google</a>
 *
 * Note: Use rawurldecode() so it does not remove plus signs
 */
if (stripos($str, '%') !== false)
  {
        do
	{
		$oldstr = $str;
		$str = rawurldecode($str);
		$str = preg_replace_callback('#%(?:\s*[0-9a-f]){2,}#i', array($this, '_urldecodespaces'), $str);
	}
	while ($oldstr !== $str);
		unset($oldstr);
	}
```

When receiving an input with a percent sign, followed by any space, then two or more hex characters, for example:

```PHP
"hi 10% abcdefgh" // returns "hi 10�cdefgh"
"this is 50% delicious" // returns "this is 50�licious"
```

This is happening because the regex `'#%(?:\s*[0-9a-f]){2,}#i'` is detecting any hex character after the percent symbol with a space between, then in the `_urldecodespaces` function:

```PHP
protected function _urldecodespaces($matches)
	{
		$input    = $matches[0];
		$nospaces = preg_replace('#\s+#', '', $input);
		return ($nospaces === $input)
			? $input
			: rawurldecode($nospaces);
	}
```

running `rawurldecode` after removing spaces causes decoding errors; because, in the example above there is no character `%de` in URL encoding

I'm not completely sure why to encode the characters even when they are separated by spaces. At first, removing `\s*` from the regex solve the issue so, is there any security implication about doing that? Any other recommendation?

**Comment by narfbg** [comment]
Duplicate of #5125.
