### ISSUE TITLE
Issue with Sessions using PHP 7.1

### ISSUE THREAD

**Issue by timothymarois** [bcit-ci/CodeIgniter#5228]
I've been using php 7.0 for a while and everything works fine and still does (with sessions), but I noticed something when I upgraded to 7.1 for about a week, sessions were being created every page view instead, not sure if this is a php thing or a CI related issue. But 7.0 works great, upgrading to 7.1 caused all sessions to create a new session every page view, really bogged down one of my servers having over 1 million session files in the session directory. I downgraded to 7.0 and everything is working once again.

**Comment by narfbg** [comment]
OK ...

Were there any error messages? Debug messages? Did you check any logs? HTTP request/response payloads? What's your CI version?

**Comment by timothymarois** [comment]
@narfbg Ok let me get back to you with some more info. I restored it due to live traffic. but I'll set up a test and see if I can reproduce it.

**Comment by timothymarois** [comment]
And for reference I am using version CI `3.1.0`

**Comment by gregavola** [comment]
I'm seeing issues with this in php 7.1 as well, a session file is being created if the user is logged out. Is that correct? Don't remember that from the older CI versions. Shouldn't sessions files be created only if they are logged in?

The files look like this: `__ci_last_regenerate|i:1503076061;`, `__ci_last_regenerate|i:1503076817;`

Any guidance @narfbg @timothymarois?

**Comment by narfbg** [comment]
This is the same as #4830 ... you wouldn't have this problem if you ran the latest CI version. Please don't report issues for older versions.

@gregavola CI has no knowledge of a logged-in state; only you do.

**Comment by gregavola** [comment]
@narfbg I'm using 3.1.5 which is the latest. Where is documented to only enable sessions for logged in users? We're getting long requests for things like: `CI_Session_files_driver::read`.

**Comment by Tekrajs** [comment]
same problem. I had project running fine with php 5.6 . When I upgraded to 7.1.1 . My session stopped to work. How to fix this?

**Comment by narfbg** [comment]
Did you read the replies? UPGRADE.

**Comment by Tekrajs** [comment]
Yeah It is solved by changing the system folder of ci  with the ci-3.1.5
