### ISSUE TITLE
Error on ODBC Driver. Call to undefined method CI_DB_odbc_driver::select

### ISSUE THREAD

**Issue by codecrafting-net** [bcit-ci/CodeIgniter#5229]
The ODBC Driver it's kind broken on the version 3.1.5. Executing a simple `$this->db->select()` raised the following error on PHP: `Call to undefined method CI_DB_odbc_driver::select()`. Digging on the odbc_driver.php it seems that the class should extend from `CI_DB` instead of `CI_DB_driver` as it is. Changing the parent class this problem solves, but another problem appears on the method `_escape_str`. Any query that I making its showing that this feature its unsuported. To that part I don't know if is a error or what it is supposed to be, but it seems that on the past was `remove_invisible_characters($str)`

My envriontment:
- CodeIgniter 3.1.5
- PHP 5.6.12
- SQL SERVER 2012
- IIS 8
- Windows Server 2012

**Comment by gxgpet** [comment]
@codecrafting-net The parent class for `CI_DB_odbc_driver` is intentional. See #5197.
