### ISSUE TITLE
email->send() return false but still send the email in localhost

### ISSUE THREAD

**Issue by ankitkumarsuthar** [bcit-ci/CodeIgniter#5231]
I am sending an email with email template of address.  
This is how i check that email is send ot not.

`if ($this->email->send()) {`
	`log_message ( 'info', 'Email Sucessfully Sent');`
`} else {`
`log_message ( 'error', 'Failed To Send Interview Notification. Email Debug: ' . print_r ( $this->email->print_debugger ( array ('headers','subject') ), TRUE ) );`
`}`

I have checked in debugger that `$this->email->send()` return `FALSE`  but email get send. 

Here is the Error Log:

ERROR - 2017-08-19 12:48:40 --> Failed To Send Interview Notification. Candidate Interview Schedule Email Debug: 220-mocha4004.mochahost.com ESMTP Exim 4.86_1 #1 Sat, 19 Aug 2017 05:48:33 -0500 
220-We do not authorize the use of this system to transport unsolicited, 
220 and/or bulk e-mail.
<br /><pre>hello: 250-mocha4004.mochahost.com Hello localhost [117.220.211.173]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-AUTH PLAIN LOGIN
250-STARTTLS
250 HELP
</pre><pre>from: 250 OK
</pre><pre>to: 250 Accepted
</pre><pre>data: 354 Enter message, ending with "." on a line by itself
</pre><br /><pre>quit: 250 OK id=1dj1Ix-000VJh-Fs
</pre>The following SMTP error was encountered: 250 OK id=1dj1Ix-000VJh-Fs
<br />The following SMTP error was encountered: <br />Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.<br /><pre>Date: Sat, 19 Aug 2017 12:48:30 +0200
From: &quot;Interview Schedule&quot; &lt;MYEMAIL.com&gt;
Return-Path: &lt;MYEMAIL&gt;
To: RECEIVEREMAIL
Subject: =?ISO-8859-1?Q?=49=6E=74=65=72=76=69=65=77=20=53=63=68=65=64=75=6C=65?=
Reply-To: &lt;MYEAMIL.com&gt;
User-Agent: CodeIgniter
X-Sender: MYEMAIL
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;54238177ea5a9a@gmail.com&gt;
Mime-Version: 1.0

**Comment by narfbg** [comment]
Which CI version are you using?
What do you mean by "email template of address"?

**Comment by ankitkumarsuthar** [comment]
Sir, I am using Version 3.1.5. And  I am sending Email With Template which contains the related address So i have written "email template of address"

**Comment by ankitkumarsuthar** [comment]
This Problem came mainly in localhost.

**Comment by narfbg** [comment]
Increase your smtp_timeout.

**Comment by iamRahul1973** [comment]
> Increase your smtp_timeout.

That solved my problem... Hoooo
