### ISSUE TITLE
Apache configuration trips CSRF protection

### ISSUE THREAD

**Issue by objecttothis** [bcit-ci/CodeIgniter#5232]
Hi everyone.  I am working on the opensourcepos project which currently uses CodeIgniter 3.1.2.  The problem I have is that server hardening is causing CSRF to trip on the line `Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure` in my apache 2.4 httpd.conf  which does XSS attack protection [Details Here](https://geekflare.com/httponly-secure-cookie-apache/)

When I comment that line out in the httpd.conf CSRF does not trip.  Is there a way to make the two play nice together? It's valuable to have it in there because if developers on my server aren't using best practices with non-CI applications I'd like to handle it at the server level.  I am running a FAMP stack on FreeBSD 11.0 with MySQL 5.7 and php 5.6.31

**Comment by narfbg** [comment]
Sorry, we only deal with bug reports here and this is not one. You could ask support questions on our [forums](https://forum.codeigniter.com/).
