### ISSUE TITLE
Sessions in PHP7.1 with CI 3.1.5

### ISSUE THREAD

**Issue by gregavola** [bcit-ci/CodeIgniter#5234]
Currently, within the Session library when using file  - we see `CI_Session_files_driver::read` taking up to 20s to process. We have tried using Redis, and see the same thing on `CI_Session_files_driver::_lock`.

I've done the following:
1) Add `session_write_close();` to Sessions.php anytime I touch the session object before returning
2) Added `php_value session.gc_probability 10 php_value session.gc_divisor 100` to my `.htaccess`  to kick off garabage collection.
3) Use my own folder for `session_save`, and put it outside the web directory, and gave `www-data` access as the owner.

Sessions are pouring in, and getting removed so I know GC is working, but I see still see these performance issues on requests tracked in NewRelic where it takes 13-20s at some times to read the file (open it for lock).

An `ls -l` shows the following on the sessions folder:

```drwxrwxrwx  2 www-data root 1126400 Aug 23 04:34 session```

I assume this is a IO issue, where the file is being written and read from the same time, but 1) should address this. Anytime a session is touched (read or write) I add `session_write_close();`. I applied this on:
- `public function sess_destroy()`
- `public function userdata($key = NULL)`
- `public function set_userdata($data, $value = NULL)`
- `public function unset_userdata($key)`

All these function do  a `session_write_close()` before return.

Any other ideas on performance issues or this is a bug?

**Comment by narfbg** [comment]
It's just the locks blocking concurrent execution, which is exactly what should happen and is not a bug.

None of the 3 things you've done and listed could "solve" the issue; they're not even related. In fact, by arbitrarily adding `session_write_close()` calls everywhere you just break everything ... That function has a specific purpose, it's not a magic performance issue solver.

Please post your help requests on our [forums](https://forum.codeigniter.com/). We only deal with bugs here.

**Comment by gregavola** [comment]
@narfbg Sorry to re-comment this, but I'm confused on what you are implying.

If 1 request is coming in - and we access the Session data, are you saying that if we ask for the Session multiple times in the same request, that's where the issue lies?

**Comment by narfbg** [comment]
No. You will never have that problem in a single request.

It's when you have *multiple, concurrent* requests that it happens. And that is by design, and explained in the user guide: https://codeigniter.com/userguide3/libraries/sessions.html#a-note-about-concurrency

**Comment by gregavola** [comment]
@narfbg Right, so I'm still at a loss on how to prevent locking. We still see long load times on pages, due to that locking issue.

So what is CI's recommendation on how to prevent this? `session_write_close()` simply doesn't work in the Session.php file, as then you can't log out a user.

I'm not trying to be harsh here - I just need to know what CI's recommends to avoid this locking issue. If a user hits a page, the session is open and closed after script is completed correct?

This would mean that if the same user (with the same session, made the same request concurrently), their session file would have a lock on it, which would cause the slow down. You would think this wouldn't happen very frequently.

**Comment by Paradinight** [comment]
Not in the Session.php. In you Controller.
https://forum.codeigniter.com/thread-68765-post-347278.html#pid347278

Pls use the forum.
