### ISSUE TITLE
Bug in CI_DB_sqlsrv_driver pagination with SQL Server < v.11

### ISSUE THREAD

**Issue by s2software** [bcit-ci/CodeIgniter#5236]
Scenario:
- db driver: sqlsrv
- SQL Server v. 10 (2008)
- Paginated list

Here the code (example with an hypothetic cars table):
```
$this->db->select('cars.*');
$this->db->from('cars');
$this->db->order_by('cars.name');
$this->db->limit(10, 20);
$query = $this->db->get();
```

Produces this query:
`SELECT "cars".* FROM (SELECT ROW_NUMBER() OVER(ORDER BY "cars"."name") AS "CI_rownum", "cars".* FROM "cars") "CI_subquery" WHERE "CI_rownum" BETWEEN 21 AND 30`

With this error:
_The column prefix 'cars' does not match with a table name or alias name used in the query._

Bug is in the `CI_DB_sqlsrv_driver::_limit` function.
A general solution could be replacing this code:
```
return 'SELECT '.$select." FROM (\n\n"
	.preg_replace('/^(SELECT( DISTINCT)?)/i', '\\1 ROW_NUMBER() OVER('.trim($orderby).') AS '.$this->escape_identifiers('CI_rownum').', ', $sql)
	."\n\n) ".$this->escape_identifiers('CI_subquery')
	."\nWHERE ".$this->escape_identifiers('CI_rownum').' BETWEEN '.($this->qb_offset + 1).' AND '.$limit;
```

with this:

```
return "SELECT * FROM (\n\n"
	.preg_replace('/^(SELECT( DISTINCT)?)/i', '\\1 ROW_NUMBER() OVER('.trim($orderby).') AS '.$this->escape_identifiers('CI_rownum').', ', $sql)
	."\n\n) ".$this->escape_identifiers('CI_subquery')
	."\nWHERE ".$this->escape_identifiers('CI_rownum').' BETWEEN '.($this->qb_offset + 1).' AND '.$limit;
```
Why repeating the field names? Every columns (asterisk or column fields) is already exposed in the subquery. (The only think to mind is that query will always return the `CI_rownum` column too)

**Comment by narfbg** [comment]
We do mind returning `CI_rownum` when it can be avoided; there's even inline comments explaining that this is exactly what we're trying to do there.

Please see if the referenced commit fixes the issue.

**Comment by s2software** [comment]
It works and it's evidently a better solution. Thank you!
