### ISSUE TITLE
Pagination class bug

### ISSUE THREAD

**Issue by Den4X** [bcit-ci/CodeIgniter#5238]
On \system\libraries\Pagination.php line 357 need to change
`if (is_array($params['attributes'])`
to
`if (is_array($params['attributes']) && !empty($params['attributes']))`

without this check attributes from pagination config will erased on pagination->initialize if new attributes not sent

**Comment by narfbg** [comment]
Sorry, I don't understand what the problem is.

**Comment by masterZSH** [comment]
don't worry,if $params['attributes'] is empty ,is_array($params['attributes'])==false.

**Comment by narfbg** [comment]
Depends on what is meant by "empty". `is_array(array())` will return `true`.

That still doesn't explain what the problem is though. Closing after 2 months without feedback.
