### ISSUE TITLE
Session login problems with PHP file_get_contents and CURL

### ISSUE THREAD

**Issue by lucav90** [bcit-ci/CodeIgniter#5241]
Hi,

I have created an ajax controller with static data to set the login session for a user. If i go to this controller with browser (link: http: // localhost: 8888 / index.php / sessions / ajax / setsession) works and the session works correctly: the user is logged on my soft.

The AJAX controller code:

```
$this->load->library('session');

$session_data = array(
    'user_type' => '1',
    'user_id' => '1',
    'user_name' => 'Luca',
    'user_email' => 'lucatest@test.it',
    'user_company' => ''
);
$this->session->set_userdata($session_data);
```

If i try to do this with php (file_get_contents) or php (curl), the system does not work, the sessions are not created and the user is not logged.

I have read the session library and i think there is a block on your code or similar stuff.

Is this the problem? What is the solution?

Please help me to solve.

**Comment by narfbg** [comment]
I have no idea what you're talking about, but it is 100% not a CI bug, and this is a bug tracker.

Please post your questions on our [forums](https://forum.codeigniter.com/) instead.
