### ISSUE TITLE
CSRF protection - useless

### ISSUE THREAD

**Issue by Webotvorba** [bcit-ci/CodeIgniter#5244]
Hello,

csrf is useless. If you set up curl request where you set up cookie and post param with same values you can load the page witohout problems even if you should get: the action you requested is not allowed.

curl:

```
$poststring = 'csrf_test_name=123';
        $ch = curl_init ($url);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 30);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt ($ch, CURLOPT_POST, true);
        curl_setopt ($ch, CURLOPT_POSTFIELDS, $poststring);
        curl_setopt($ch, CURLINFO_HEADER_OUT, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array("Cookie: csrf_cookie_name=123"));
        $output = curl_exec ($ch);
        curl_close($ch);
```

**Comment by narfbg** [comment]
It's not useless, nor is what you're showing a CSRF attempt.
*You* are creating your own cookie/postfield pair; another site cannot create cookies on your behalf.

**Comment by Webotvorba** [comment]
Ok lets have an example:

http://demo.webotvorba.sk/auth 

This is login page with csrf protection.

http://93.170.77.38/cron/test_csrf - separate server which runs this curl:
```

$url = 'http://demo.webotvorba.sk/auth';
        $poststring = 'email=email@email&password=1234&csrf_test_name=123';
        $ch = curl_init ($url);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 30);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt ($ch, CURLOPT_POST, true);
        curl_setopt ($ch, CURLOPT_POSTFIELDS, $poststring);
        curl_setopt($ch, CURLINFO_HEADER_OUT, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array("Cookie: csrf_cookie_name=123"));
        $output = curl_exec ($ch);
        curl_close($ch);

        var_dump($output);
```

Since this request is from another source I should get error - the action you requested is not allowed. But it loads the website. So I think the csrf is not working.

In this case I could make this script run X times per second and make huge load on database and server.

**Comment by narfbg** [comment]
That is not another source. Whether you send the payload directly via cURL, or via submitting a browser form rendered by `demo.webotvorba.sk` - you are the source (client) in both cases.

You could easily setup any script to send repeated requests to any site, and it will still result in the server having to process them, regardless of what kind of a request it is. That is not CSRF, and even if you did get an error response, it would still result in higher server load.

CSRF is an attack on you, the client and the goal is to trick you into submitting a request that you didn't want to. And our mechanism protects you exactly from that, using a technique called a "double-submit cookie" - one of the recommended by OWASP: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Double_Submit_Cookie

(scroll up to the top of that page to read a more detailed explanation of what CSRF is)
