### ISSUE TITLE
Codeigniter form validation not working

### ISSUE THREAD

**Issue by git-vik** [bcit-ci/CodeIgniter#5245]
I am trying to validate get request data using ajax and here is url
http://localhost/getprivate/admin/logenquiry?firstname=Hello&lastname=World&contactno=1231231231&email=hello@world.com&subject=Hello&message=World&country=World
and here is my code
```php
	public function logenquiry(){
		$this->form_validation->set_rules('firstname', 'First Name', 'trim|required');
		$this->form_validation->set_rules('lastname', 'Last Name', 'trim');
		$this->form_validation->set_rules('contactno', 'Contact Number', 'trim|required');
		$this->form_validation->set_rules('email', 'Email', 'trim|required');
		$this->form_validation->set_rules('subject', 'Subject', 'trim');
		$this->form_validation->set_rules('message', 'Message', 'trim');
		$this->form_validation->set_rules('country', 'Country', 'trim|required');
		if(  $this->form_validation->run() == true ){
			echo "success";
		}else{
			$ret = array(
				'status' => 'error',
				'message' => 'Please fill all the mandatory fields',
				'error' => $this->form_validation->error_array()
				);
			echo json_encode($ret);
		}
	}
```
Output:
{"status":"error","message":"Please fill all the mandatory fields","error":[]}

this code is failing even when i am sending all the data through get and errors field is empty.
I am using Codeigniter Version 3.1.5

**Comment by gxgpet** [comment]
Obviously, form validator is working by default with POST variables and not GET. :)

Still, if you have questions regarding your project (and not CodeIgniter bugs), please post them on [the forums](https://forum.codeigniter.com/).

**Comment by git-vik** [comment]
Ok thanks.
