### ISSUE TITLE
How can i run a raw query?

### ISSUE THREAD

**Issue by junaidinsolutiondots** [bcit-ci/CodeIgniter#5250]
**please help me how can i build below query in it**
db.persons.find({$and: [{ Email: {$eq : "test@gmail.com"}, $or: [{gmail_token: {$ne: null}}, {outlook_token: {$ne: null}}]}]})

**Comment by jim-parry** [comment]
Support questions should be asked on our [forum](https://forum.codeigniter.com/), thanks.

**Comment by junaidinsolutiondots** [comment]
@jim-parry Thanks. I will fix it. 
$this->mongo_db->where(
                array(
                    '$and' => array(
                        array(
                            'Email' => array('$eq' => 'test@gmail.com'),
                            '$or' => array(
                                array('gmail_token' => array('$ne' => null), 'outlook_token' => array('$ne' => null))
                            )
                        )
                    )
                )
)->get('persons');
