### ISSUE TITLE
Unable to load the requested language file: language/english/database_lang.php

### ISSUE THREAD

**Issue by darkmog2** [bcit-ci/CodeIgniter#5253]
Hello,
I have download the zip of coldeigniter and i have make all configuration. I have this error but i don't have in the zip and my folder a file which have this name database_lang.php

Sorry of my english i am a young french

**Comment by jim-parry** [comment]
Support questions should be asked on our [forum](https://forum.codeigniter.com/), thanks.
There is no "database_lang", but there is "system/language/english/db_lang.php" ... could be what you are looking for.

**Comment by darkmog2** [comment]
Thank you for your reply
