### ISSUE TITLE
Fatal error: Cannot access protected property CI_Form_validation::$CI in...

### ISSUE THREAD

**Issue by Suguru-Tokuda** [bcit-ci/CodeIgniter#5254]
I'm having an issue to upload the website to stable host. When I work on a local host, the website works without problem but once it's uploaded to stable host it gives this fatal error. I checked "class My_Form_My_Form_validation extends CI_Form_validation" and $CI is declared as public already. It would be great if anyone can solve this problem.

**Comment by jim-parry** [comment]
Please use our [forum](https://forum.codeigniter.com/index.php) for support questions. This problem has been addressed there multiple times.

**Comment by Suguru-Tokuda** [comment]
Thanks for your reply. Can you please send me the specific link for this issue? I can't find it in the forum.

**Comment by jim-parry** [comment]
Searching on the forum for "protected property" gives 
https://forum.codeigniter.com/thread-63438.html?highlight=protected+property
... third entry in the list, and it sounds a lot like your situation.

**Comment by Suguru-Tokuda** [comment]
Thanks a lot. I will refer to it.

Sorry for taking your time, but I noticed that once I uploaded my application files to stablehost and run it, some modules are not correctly loaded. The error is:

Fatal error: Call to a member function ... on a non-object.

Is it also related to the same issue?
