### ISSUE TITLE
Flashdata doesn't work with array

### ISSUE THREAD

**Issue by cigzigwon** [bcit-ci/CodeIgniter#5255]
So if you do this:
<code>
$this->session->set_flahdata('alert', [
  'state' => 'danger',
  'message' => 'Error!',
]);
</code>

It persists in the session data. I think at this point you should just return an error state when passing an array as a value. I've already refactored my controller to use two flashdata keys: 'alert_state' and 'alert_message'.

So throwing an exception would be ideal. However it would be most beneficial to support my use case above because we typically want to have one field that will do things like render a bootstrap or growl alert and we want multiple values in one session var because you need extra data to output the correct UI state.

Also, I noticed you make alot of your own libs. It would be nice to see the email class code to be removed and allow for using things like swiftmailer instead. I t/hink you guys should considerring outsourcing code like that of the Laravel framework. $this->email could be an instance of swift.

Chris

**Comment by narfbg** [comment]
Your title says something doesn't work, but the description says it works and then branches out to irrelevant stuff ...

**Comment by renolooijmans** [comment]
You probably want to retrieve the flashdata like $this->session->flashdata('alert')['state'].

It does work, just not the way you think it works. The way you expect it to work doesn't really make sense either. You could have easily figured this out by debugging $this->session->flashdata('alert')...

**Comment by cigzigwon** [comment]
@renolooijmans You can verify that your usage is working as expected? Because I was debugging dumping out the session in the session class. It persisted forever until I switched to the way I was using it as I mentioned above. It's not clear how it "should" work.

If I want to jam an array into flash data to use once, why does it keep persisting until I dump? That's where I made it to. I don/'t really mind.. it's a nice to have and furthermore I don't use CodeIgniter in any newer projects mainly because it does not have a dependency injection container.

**Comment by HenryKim2022** [comment]
> You probably want to retrieve the flashdata like $this->session->flashdata('alert')['state'].
> 
> It does work, just not the way you think it works. The way you expect it to work doesn't really make sense either. You could have easily figured this out by debugging $this->session->flashdata('alert')...


**Can u plz give me example if i have these data & want the getFlashdata hav an array?
#This is in controller:**
```
session()->setFlashdata('err', [
	'first_na' => $this->request->getPost('first_na'),
	'last_na' => $this->request->getPost('last_na'),
	'username' => $this->request->getPost('username'),
	'level' => 5,
	'no_hp' => $this->request->getPost('no_hp'),
	'email' => $this->request->getPost('email'),
	'password' => $this->request->getPost('password'),
	'errors' => \Config\Services::validation()->getErrors()
]);
```


**#This is in view:**
```
<!-- Err Toast -->
<?php
$errors = session()->getFlashdata('err', ['errors']);
if (!empty($errors)) { ?>
	<ul>
		<div id="toast-container" class="toast-top-right">
			<?php foreach ($errors as $error) : ?>
				<script>
					toastr.options = {
						"closeButton": true,
						"debug": false,
						"newestOnTop": false,
						"progressBar": false,
						"positionClass": "toast-top-right",
						"preventDuplicates": true,
						"showDuration": "300",
						"hideDuration": "3000",
						"timeOut": "3000",
						"extendedTimeOut": "1000",
						"showEasing": "swing",
						"hideEasing": "linear",
						"showMethod": "fadeIn",
						"hideMethod": "fadeOut"
					}
					toastr.error("<b><?= esc($error); ?></b>");
				</script>

			<?php endforeach; ?>
		</div>
	</ul>
<?php } ?>
```


**Output:**
```
ErrorException (Array to string conversion)
```

**How to apply it in view?**





###EDIT### 
 **_I GOT IT WORKING 👍_** 
**In controller:**
```
$data = array(
	'first_na' => $this->request->getPost('first_na'),
	'last_na' => $this->request->getPost('last_na'),
	'username' => $this->request->getPost('username'),
	'level' => 5,
	'no_hp' => $this->request->getPost('no_hp'),
	'email' => $this->request->getPost('email'),
	'password' => $this->request->getPost('password'),
	'errors' => \Config\Services::validation()->getErrors()
);
session()->setFlashdata($data);
```


**In view:**
```
<?php $errors = session()->getFlashdata('first_na');
if (!empty($errors)) {
	echo $errors;
} ?>
<?php $errors = session()->getFlashdata('last_na');
if (!empty($errors)) {
	echo $errors;
} ?>
```
