### ISSUE TITLE
Number helper byte_format using wrong prefixes

### ISSUE THREAD

**Issue by rmilecki** [bcit-ci/CodeIgniter#5258]
If you take a look at `number_helper.php` it's dividing number by values like 1024, 1048576, etc. These are 2^n numbers, so this code should use [binary prefixes](https://en.wikipedia.org/wiki/Binary_prefix). We should have: `kibibyte_abbr` (`KiB`), `mebibyte_abbr` (`MiB`), `gibibyte_abbr` (`GiB`) and `tebibyte_addr` (`TiB`).

Abbreviations like `KB`, `MB`, `GB` and `TB` should be used only when dividing by 1000, 1000000, 1000000000 and 1000000000000.

**Comment by narfbg** [comment]
`KB`, `MB`, etc. are not incorrect (`kB`, `mB` ... would be).

Plus, chances are this would only confuse people.
