### ISSUE TITLE
Unknown column 'NULL' in 'field list'

### ISSUE THREAD

**Issue by emilebourquin** [bcit-ci/CodeIgniter#5259]
Summary: Query Builder is escaping the NULL in my (for example) "SELECT a, b, x, NULL AS y" that is several levels down in a multi-level query, even when FALSE is passed as the second parameter to this->db->select. Adding 'NULL' to $_reserved_identifiers in DB_driver.php solves the problem.

Detail: I am using get_compiled_select several times in a Query Builder query that then UNION ALLs two of the lower level queries together (thus the SELECT NULL AS x, which is necessary in a UNION so that the result sets of the two queries being UNIONed have the same columns in them).

I'll attempt to give the crucial parts of the multi-level query here, without dumping the entire, massive query on you:

```
private function _do_subquery()
{
$this->db->select('a, b, x, NULL AS y', FALSE);
$this->db->from('x_activity');
...
$x_subquery = $this->db->get_compiled_select();

$this->db->select('a, b, NULL AS x, y', FALSE);
$this->db->from('y_activity');
...
$y_subquery = $this->db->get_compiled_select();

$union_subquery = $x_subquery.' UNION ALL '.$y_subquery;

/* At this point, the $union_subquery is ok, the NULLs in 
'NULL AS x' and 'NULL AS y' are not escaped with backticks */

$this->db->select('a, b, SUM(x) AS x_sum, SUM(y) as y_sum', FALSE);
$this->db->from('('.$union_subquery.') AS aggregated_data');
$this->db->group_by('a, b');
$final_subquery = $this->db->get_compiled_select();

/* It is at this point that the NULLs are being escaped. As far as I can see, 
there is no way to control this, as there is no parameter to pass to 
$this->db->from('('.$union_subquery .') AS aggregated_data'); to disable escaping. */

return $final_subquery;
}
```

However, by adding 'NULL' to $_reserved_identifiers in DB_driver.php, the NULLs are no longer escaped:

`protected $_reserved_identifiers	= array('*', 'NULL');`

Is this a reasonable fix, that doesn't cause other problems? It seems that not escaping NULL as an identifier is a reasonable thing to do, but I'd rather ask the experts here.

**Comment by narfbg** [comment]
Sorry, but QB is not meant to be used in that way. With such a query, you're better off writing it yourself.

**Comment by emilebourquin** [comment]
Actually, I was surprised at how well QB worked with this multi-level query! Basically, what I'm asking is not really about QB, but if it's ever acceptable to escape NULL as a database/table/column identifier (I'm using it as a column identifier here). If not, is it safe to add 'NULL' to $_reserved_identifiers , and if so, can this be added to core CI code?
