### ISSUE TITLE
Codeigniter Web Page Caching is not working

### ISSUE THREAD

**Issue by officiallyakshayagrawal** [bcit-ci/CodeIgniter#5261]
Hi,

I've turned on Web Page Caching in my Controller file for a few methods. 

HOWEVER, the cache files being written to the applications/cache folder are a mere 16 bytes each - The actual cache files are never being written and hence never being used. 
They all end in something like "1505378556TS--->" and are named something like "77bb543e7e5bbc75641078a38cfb1dcb"

The pages ARE being generated through a view and it is NOT a permissions issue because the Db cache files are getting written there just fine.

OS: CentOS 6

Can this have something to do with PHP Handlers?
Is this a known issue? What more information would you need from my end to be able to fix this?

Thanks

**Comment by narfbg** [comment]
CI 3 doesn't write `<timestamp>TS--->` caches.

CI 2 did, and it is no longer supported.
