### ISSUE TITLE
Autodetection for base_url()

### ISSUE THREAD

**Issue by Assimilationstheorie** [bcit-ci/CodeIgniter#5263]
Hello Friends! My first Issue here! A little bit nervous! :)

The Code for base_url() in config.php is:

`$config['base_url'] = 'mySite';`

But thats not very practicable. Why not like this:

```
define('APP_URL', ($_SERVER['SERVER_PORT'] == 443 ? 'https' : 'http') . "://{$_SERVER['SERVER_NAME']}".str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']));

$config['base_url'] = APP_URL;
```

Works fine on Dev and Live-Systems.

Why the CodeIgniter-Devs doesn't implements this years ago?

**Comment by narfbg** [comment]
It did exist years ago; we removed it because it's a security flaw.

Please use the search bar to check for similar issues before posting new ones.
