### ISSUE TITLE
Error  "set" method to update an entry.

### ISSUE THREAD

**Issue by Karador1995** [bcit-ci/CodeIgniter#5264]
I am trying to import data from an Excel file to Mysql, but it is not inserting the data, I think the syntax is wrong, some help please

Controller

    `public function guardar_horario(){

       if (!empty($_FILES['file']['name'])) {

       $pathinfo = pathinfo($_FILES["file"]["name"]);

       if (($pathinfo['extension'] == 'xlsx' || $pathinfo['extension'] == 'xls') 
           && $_FILES['file']['size'] > 0 ) {

        // Temporary file name
       $inputFileName = $_FILES['file']['tmp_name']; 

      // Read excel file by using ReadFactory object.
      $reader = ReaderFactory::create(Type::XLSX);

    // Open file
    $reader->open($inputFileName);
    $count = 1;

    // Number of sheet in excel file
    foreach ($reader->getSheetIterator() as $sheet) {

        // Number of Rows in Excel sheet
        foreach ($sheet->getRowIterator() as $row) {

            // It reads data after header. In the my excel sheet, 
            // header is in the first row. 
            if ($count > 1) { 

                // Data of excel sheet
                $data['hrs_ini'] = $row[0];
                $data['hrs_ter'] = $row[1];
                $data['lunes'] = $row[2];
                $data['martes'] = $row[3];
                $data['miercoles'] = $row[4];
                $data['jueves'] = $row[5];
                $data['viernes'] = $row[6];
                $data['sabado'] = $row[7];

           $this->db->insert('horario',$row[0],$row[1],$row[2],$row[3],$row[4],$row[5],$row[6],$row[7]);

           //$sql="INSERT INTO estudiantes (nombre_es, apellido_pa, apellido_ma) 
            //VALUES('$row[0]','$row[1]','$row[2]')";
           //$resultado=mysqli_query($conn,$sql);

                //print_r($data);

              }
              $count++;
           }
       }

        // Close excel file
       $reader->close();

       } else {

       echo "Please Select Valid Excel File";
      }

       } else {

       echo "Please Select Excel File";

         }
        }
      }`

**Comment by narfbg** [comment]
This is a bug tracker for CodeIgniter.  
Your issue is not even related to CodeIgniter.

Please post it on a site like StackOverflow, or our [forums](https://forum.codeigniter.com/).
