### ISSUE TITLE
Database Encryption

### ISSUE THREAD

**Issue by flakjacket95** [bcit-ci/CodeIgniter#5266]
Hello. I have been using Codeigniter for the past 5 years now and I absolutely love it. 

Over those 5 years, I've only actually needed this feature once but, I wonder about it's feasibility through the database functionality.
My examples are for MySQL but, I'm sure there are equivalents for other database engines.

MySQL supports table level encryption but, would it be possible to add query level encryption support for the base database engine. My though is that maybe a config variable toggles this and then every query that requires it has the aes encrypt, decrypt piece added automatically using the encryption key in the configuration.

https://dev.mysql.com/doc/refman/5.5/en/encryption-functions.html#function_aes-encrypt

Is this possible at all? Of course, it's easily implementable manually too.

**Comment by narfbg** [comment]
No ... this is way out of the scope of our project.
