### ISSUE TITLE
passing variable refferance to view.

### ISSUE THREAD

**Issue by dineshpatra** [bcit-ci/CodeIgniter#5268]
I have edited the ```vars``` method in ```system/core/Loader.php``` to following.

```php
        public function vars($vars, &$val = '')
        {
                $vars = is_string($vars)
                        ? array($vars => $val)
                        : $this->_ci_prepare_view_vars($vars);

                foreach ($vars as $key => &$val)
                {
                        $this->_ci_cached_vars[$key] = &$val;
                }

                return $this;
        }
```
This helps me passing variable reference to view. Like following code in my base controller:

```php
$this->load->vars([  "JS_VARIABLES"      => &$this->jsConfig  ]);
```

Please correct me if any wrong I have done.

**Comment by narfbg** [comment]
Here's the three things you did wrong:

1. Using references when you don't need them.
2. Modifying core framework files.
3. Posting about it here. This is a bug tracker.
