### ISSUE TITLE
@ini_set('iconv.internal_encoding', $charset); provoking a "ERR_EMPTY_RESPONSE" error

### ISSUE THREAD

**Issue by tchule** [bcit-ci/CodeIgniter#5274]
I've had a problem of Apache not responding after restarting a Debian Vagrant Box that was previously working.

No log, no dump, no error info. 

After some debugging session, the culprit seem to be the line "@ini_set('iconv.internal_encoding', $charset);"  in CodeIgniter.php.

I'm using PHP 7.0.23-1~dotdeb+8.1 with CodeIgniter 3.1.2. 
Updating to 3.1.5 doesn't solve the problem.

This seems related to : https://github.com/bcit-ci/CodeIgniter/pull/5115

I've worked around the problem by testing the PHP version in the code.

**Comment by narfbg** [comment]
We can't do anything unless we know *how* that line might be the culprit.

**Comment by zploskey** [comment]
What is the value of `$charset`? If you remove the @ from before the iniset command what is the result?

**Comment by tchule** [comment]
$charset is empty. which might not be good ... ^^

The error is causing segmentation faults : child pid 28886 exit signal Segmentation fault (11)

I have removed the @ but because of the segmentation fault I have no log.

**Comment by tchule** [comment]
$charset is empty because i've messed up my config files. 
I've upgraded from CodeIgniter 1.x and I've different config files and one of the was missing the $charset config.

Maybe just a non-null check would be sufficient. Segmentation fault is a pain to debug.

**Comment by narfbg** [comment]
Segmentation faults are not supposed to ever happen; if you have one - that's a PHP bug.
