### ISSUE TITLE
Backup content is not enclosed

### ISSUE THREAD

**Issue by ubeljan** [bcit-ci/CodeIgniter#5276]
Hello,

While making a backup form the database the content is not enclosed by '.
Example:
INSERT INTO `tr_acties` (`id`, `naamKort`, `naamLang`, `kleur`, `afb`) VALUES (1, bellen, Bellen, #6BBE23, telefoon.png);
Instead of 
INSERT INTO `tr_acties` (`id`, `naamKort`, `naamLang`, `kleur`, `afb`) VALUES ('1', 'bellen', 'Bellen', '#6BBE23', 'telefoon.png');

This is seen in version 3.1.6 as in the development version of 27-09-2017.

Greetings,
Ubel Jan van Wijhe

**Comment by narfbg** [comment]
What PHP and MySQL versions is that on?

**Comment by ubeljan** [comment]
Hello,

The first system is with PHP Version 5.5.9-1ubuntu4.22 and MySQL server versie | 5.5.57-0ubuntu0.14.04.1

The second system is a Centos system with PHP 5.6.31 and MySQL mysqlnd 5.0.11-dev.

The fields you saw were varchar fields.

Greetings,
Ubel Jan van Wijhe

**Comment by narfbg** [comment]
Thanks. Though ... that turned out to be irrelevant; I found the issue already.

**Comment by narfbg** [comment]
Was caused by the patch for #5260. See referenced commit for the fix.

**Comment by franko108** [comment]
I have the same problem on 3.1.6, it's not clear will it be fixed?
All the best

**Comment by narfbg** [comment]
How's it not clear?

**Comment by sanjayacloud** [comment]
Hello,
I have create a database backup using codeigniter $this->load->dbutil(); This Work fine and I can download my database backup. But I try to restore this backup and I got below error..

SQL query:

INSERT INTO app_user (id, user_name, email, password, role, status) VALUES (10, Admin.sgh, admin@supreme.lk, 202cb962ac59075b964b07152d234b70, 0, 0)
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@supreme.lk, 202cb962ac59075b964b07152d234b70, 0, 0)' at line 1

Can you help me to resolve this error. I am using codeigniter 3.1.6 Version..

**Comment by sanjayacloud** [comment]
Any one know how to resolve this error?

**Comment by sanjayacloud** [comment]
Any one know how to resolve this error?

**Comment by franko108** [comment]
@sanjayacloud you can upgrade your CI to the last stable version from this github, then database backup works properly.
