### ISSUE TITLE
if tablename is a sole number, the querybuilder db->get() fails to escape the tablename string

### ISSUE THREAD

**Issue by hcbd** [bcit-ci/CodeIgniter#5291]
If your tablename is something like: 001 or another sole number. The querybuilder makes an illegal query on the (mysql) database, because it does not escape the tablename as required by mysql:

https://dev.mysql.com/doc/refman/5.7/en/identifiers.html
>  Identifiers may begin with a digit but unless quoted may not consist solely of digits. 

$this->db->get('001') --> fails
$this->db->get('\`001\`') --> works (and is my workaround)

is this a bug or by design?

if this is by design, I would like to see the documentation updated next to the function db->get() about this behaviour.

(CI_Version: 3.1.6)

**Comment by narfbg** [comment]
It is neither, though I'd probably classify it as a bug in the changelog.

Numbers are horrible table/column name identifiers, which is why almost nobody uses them and thus why nobody has even thought of making this work. I guess it's fine for the given example - the string `001` - but if it was just `1`, we'd never know when that is intentional and when it is an error.

**Comment by pfote** [comment]
note: not 100% sure about table names, but just a number is not a valid 
column name in the SQL standard. it must start with a letter, or one of 
the chars '_', '@', '#' if i remember correctly

**Comment by hcbd** [comment]
Since numbers are horrible name identifiers: I've already changed the tablename to have a letter before the number. 
But:
Would it not be good practice to just escape all tablenames?
or does this go against the SQL standard?

**Comment by narfbg** [comment]
This is not about "good practice", it's just not as simple as that.

The query builder has very complex logic, and the function that determines what is escaped or not is shared between table and column names. It's not an easy thing to escape table names but not escape field names and even harder to predict whether you actually want such a table name or just passed the wrong variable.  
While it may not look hard to do this for `get()` and `from()`, the same logic must be applied to table names detected in the middle of a string (e.g. when you write `select('001.foo')`), it has to work well combined with other QB features like table name prefixing, query caching, etc.

There's enormous potential that the patch would cause other bugs, while the benefit is questionable and maybe useful for 2 people ever. It's just not worth the effort.
