### ISSUE TITLE
ERROR: lastval is not yet defined in this session

### ISSUE THREAD

**Issue by DanielTheGeek** [bcit-ci/CodeIgniter#5299]
Deployed my CI app to Heroku and configured it to use PostgreSql however i keep on getting:

` pg_query(): Query failed: ERROR: lastval is not yet defined in this session`

iabs.scriptorigin.com

https://screenshots.firefox.com/E5owmx2uCIpk8g9G/iabs.scriptorigin.com

[V: CI3]

**Comment by narfbg** [comment]
Sorry, but you'll have to give us a lot more than this ...

We don't know your PostgreSQL server version, your client version, your PHP version, nor your CI version ("CI3" says nothing ... there are 14 CI3 releases to date)

And more importantly, we don't know your code and how you've triggered that error.

**Comment by DanielTheGeek** [comment]
Oops, sorry for not making this as detailed as it should be.

I'm using;
PostgreSql 9.6.1
CI 3.1.6
PHP 7.0.*

I think the problem is CI not being able to cast MySql syntax to PostgreSql as my app allows user install on various database platforms. However the database tables are being created using the Db Forge class, I had to manually check for the database type and use the appropriate syntax as BIGINT, TINYINT and LONGTEXT aren't available for PostgreSql dbs. 
When I checked the apps data store, the tables were created but the no data was inserted (the error popped out after the tables were created), so the error must be associated with data insertion (auto increment).
Here's a sample code:
$id = $this->db->insert_id();

$data = [
    [
       'option_name' => 'site_name',
       'option_value' => 'test app',
       'option_status' => '1'
    ],
    // Other entries
]

if ( $this->db->table_exists( 'table_name' ) {
    $this->db->insert_batch( 'options', $data );
 return true;
   } else {
    return false;
    }

**Comment by narfbg** [comment]
Your very first line calls `insert_id()`, and the error message tells you exactly that - there's no id to be returned yet.

This isn't a bug.

**Comment by DanielTheGeek** [comment]
Oops, my bad again... Thanks for pointing that out @narfbg

**Comment by ericsonvb** [comment]
the problem is : your table no have a key primary in format serial

**Comment by Felicia-Doumani** [comment]
> the problem is : your table no have a key primary in format serial

That worked for me! Thanks
