### ISSUE TITLE
idn_to_ascii() on PHP 7.2

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#5300]
CodeIgniter 3.1.6, PHP 7.2.0RC3

As of PHP 7.2 the constant INTL_IDNA_VARIANT_2003 is deprecated.
https://wiki.php.net/rfc/deprecate-and-remove-intl_idna_variant_2003

The function idn_to_ascii() as is currently used throws the warning:

```
A PHP Error was encountered
Severity: 8192
Message: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated
...
```

There are three places to be updated:

Email library, the method valid_email()
https://github.com/bcit-ci/CodeIgniter/blob/3.1.6/system/libraries/Email.php#L1035

With the following snippet:

```php
        $this->load->library('email');
        echo $this->email->valid_email('test@Bloß.de') ? 'yes' : 'no';
```

I tried this modification that seems to me ok:

```php
	public function valid_email($email)
	{
		if (function_exists('idn_to_ascii') && defined('INTL_IDNA_VARIANT_UTS46') && $atpos = strpos($email, '@'))
		{
			$email = self::substr($email, 0, ++$atpos).idn_to_ascii(self::substr($email, $atpos), 0, INTL_IDNA_VARIANT_UTS46);
		}

		return (bool) filter_var($email, FILTER_VALIDATE_EMAIL);
	}
```

The second place that would need a similar modification is CI_Email::valid_email()
https://github.com/bcit-ci/CodeIgniter/blob/3.1.6/system/libraries/Email.php#L1852

And the third pace is CI_Form_validation::valid_email()
https://github.com/bcit-ci/CodeIgniter/blob/3.1.6/system/libraries/Form_validation.php#L1230

**Comment by narfbg** [comment]
Thanks, I've pushed a patch for this.

**Comment by udin-ordinary** [comment]
hello all,
for idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated
just add this in system/libraries/form_validation.php in line 1234

```
	public function valid_email($str)
	{
		if (function_exists('idn_to_ascii') && preg_match('#\A([^@]+)@(.+)\z#', $str, $matches))
		{
			$str = $matches[1].'@'.idn_to_ascii($matches[2],IDNA_NONTRANSITIONAL_TO_ASCII,INTL_IDNA_VARIANT_UTS46);
		}

		return (bool) filter_var($str, FILTER_VALIDATE_EMAIL);
	}
```

correct me any mistake.
its work for me with CI.3.1.7

many thanks,

udin

**Comment by narfbg** [comment]
CI 3.1.7 doesn't have this issue; I don't understand why you're suggesting modifications at all.

**Comment by udin-ordinary** [comment]
dear narfbg,

yes it does...iam facing that problem with CI 3.1.7 with PHP 7.2 on Xampp...so if any others face it that works for me.

many thanks for your reply.

**Comment by narfbg** [comment]
No, it doesn't.

Particularly on PHP 7.2 the only way to trigger that notice is if you have an ICU version lower than 4.6, at which point there's literally nothing you can do about it.

Read more here: https://forum.codeigniter.com/thread-69780.html

**Comment by datamweb** [comment]
@narfbg 
This is also a problem for me.
PHP ver:7.2
CI ver: 1.3.9

**Comment by digitaloutback** [comment]
Same here PHP 7.2 CI 3.1.8

**Comment by vaultdweller123** [comment]
why is this closed? this is not fixed. i got this error on my server but works on local weird!? fix pls!

**Comment by AG0001** [comment]
Same here PHP 7.2.1 & CI 3.1.8 . "valid_email()" has a serious issue .

**Comment by saadi09** [comment]
I'm facing same issue its working fine on same version in localhost but when i place my project live on server it stuck with this error, kindly suggest me the best possible solution.

**Comment by vaultdweller123** [comment]
@saadi09 the solution i did was to override the CI core function to validate email. Go to system/libraries/Email.php and find the validate_email function and replace with this. you can also rename it for backup and paste this below it.

public function validate_email($email){
	if ( ! is_array($email))
	{
		$this->_set_error_message('lang:email_must_be_array');
		return FALSE;
	}

	foreach ($email as $val)
	{
		if ( ! $this->valid_email($val))
		{
			$this->_set_error_message('lang:email_invalid_address', $val);
			return FALSE;
		}
	}

	return TRUE;
}

public function valid_email($email){
	return (bool) filter_var(trim($email), FILTER_VALIDATE_EMAIL);
}

**Comment by saadi09** [comment]
Thanks :) it works pretty fine now although I'm using my own validation library rather than this one.

**Comment by allayGerald** [comment]
for anyone still getting this for php > 7.2 try checking if INTL_IDNA_VARIANT_UTS46 constant is defined
I added these lines on system/libraries/Email.php and  system/libraries/Form_validation.php

`if(!defined('INTL_IDNA_VARIANT_UTS46'))
{
    define ('INTL_IDNA_VARIANT_UTS46', 1);
}`

**Comment by raenk** [comment]
Well, this is my case with this error:
`ERROR - 2020-02-07 15:35:11 --> Severity: 8192 --> Function mcrypt_create_iv() is deprecated public_html/system/core/Security.php 578
DEBUG - 2020-02-07 15:35:11 --> Global POST, GET and COOKIE data sanitized
ERROR - 2020-02-07 15:35:11 --> Severity: 8192 --> idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated public_html/system/libraries/Form_validation.php 1249
`

PHP version:
`[root@one logs]# php -v
PHP 7.2.27 (cli) (built: Jan 22 2020 09:31:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
`

LIBICU version:
`[root@one logs]# yum install libicu
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package libicu-50.2-3.el7.x86_64 already installed and latest version
Nothing to do
[root@one logs]# 
`

CodeIgniter version:
`const CI_VERSION = '3.1.11';`

I think I don't meet the criteria for the diagnosis here. Am i missing anything?

**Comment by narfbg** [comment]
Yes, you shouldn't be getting the warning with libicu 50. The version you have installed right now might differ from the one your PHP is linked against - that's my only guess.

**Comment by raenk** [comment]
> Yes, you shouldn't be getting the warning with libicu 50. The version you have installed right now might differ from the one your PHP is linked against - that's my only guess.

Thanks for your reply. I'll look in that direction.

**Comment by f4r424hm3d** [comment]
I had the same problem after this solution it's solved but $this->session->set_flashdata('smsg', 'Mail has been sent successfully.'); is not working. please help.
