### ISSUE TITLE
Codeigniter session does not work on LIVE server

### ISSUE THREAD

**Issue by shadotech** [bcit-ci/CodeIgniter#5302]
I have an application built with codeigniter using the sessions class and storing session data in a database.but when I UPLOAD into LIVE SERVER and I try to login into the system with different users and different COMPUTER and Browser, I wonder why all users have the same session data as the first login into the system.
my configuration files are 

**$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_sessions';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;** 
Please I need support

**Comment by narfbg** [comment]
This is a bug tracker, we don't provide support here. You can ask your questions on our [forums](https://forum.codeigniter.com/) instead.

But really, you just need to read the in-config manual.
