### ISSUE TITLE
CI_Email::from() ignores the display name in the email address

### ISSUE THREAD

**Issue by daveherman71** [bcit-ci/CodeIgniter#5303]
Version 3.1.6

When specifying an email address that contains a display name the from() method in the Email class ignores that display name. The following example code illustrates my point:

```
$email_address = "Name of Sender <email@sender.com>";

$this->load->library('email');

$this->email->from($email_address);

$this->email->to('someone@example.com');
$this->email->subject('Email Test');
$this->email->message('Testing the email class.');
$this->email->send();

```

The recipient then receives and email that looks something like this:
```
From: email@sender.com
Sent: 18 October 2017 10:08 AM
To: someone@example.com
Subject: Email Test

Testing the email class.
```

My work around is to parse the email address and look for a display name in the event that one is not provided, as follows:

Line 483 - 486 in the Email class:
```
if (preg_match('/\<(.*)\>/', $from, $match))
{
	$from = $match[1];
}
```

I have changed to:
```
if (preg_match('/\<(.*)\>/', $from, $match))
{
	$from = $match[1];

	// If $name is empty (ie. empty string or NULL) then try and get the display name

	if (empty($name))
	{
		$name = trim(str_ireplace('<' . $match[1] . '>', '', $from));
	}
}
```
The resulting message then correctly reflects the sender's email address and display name, as follows:
```
From: Name of Sender <email@sender.com>
Sent: 18 October 2017 10:08 AM
To: someone@example.com
Subject: Email Test

Testing the email class.
```

Hopefully this helps someone and is useful enough to be incorporated in the Email class.

**Comment by narfbg** [comment]
The `from()` method has an explicit `$name` parameter for this.
