### ISSUE TITLE
Garbage Collector on Session File driver issue

### ISSUE THREAD

**Issue by pawelkg** [bcit-ci/CodeIgniter#5305]
Garbage Collector on Session File driver can skip some files. On FPM mode i have session.hash_bits_per_character set to different value than in CLI mode. This couse that session ID have different length, and GC don't take all files on time check. Simply on GC run it don't see files generated in different mode.

**Comment by narfbg** [comment]
Unless you're running `session_gc()` with a cronjob, that's irrelevant - GC is triggered by the web process on a pseudo-random, probability basis.

And if you are running a cronjob, well ... what do you expect CI to do about that? It's not magic, you have to have a consistent environment configuration.
