### ISSUE TITLE
Sessions not setting in local server, works fine on live server

### ISSUE THREAD

**Issue by shanilsoni** [bcit-ci/CodeIgniter#5307]
So I have this issue that sessions are not working in local server, I tried a lot of posts but none of them worked for me.

Config.php code is below:
```
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;
```

Session array is loaded in autoload.php file. Code to set session is:
`$this->session->set_userdata('user',$result);`

Strange issue is when I set this, two or three files are created under ci_session folder. One of them does consist my data but that doesn't have a session variable in it, see what one of them contains:
`user|a:6:{s:2:"no";s:1:"1";s:4:"name";s:11:.....` 
Second file contains:
`__ci_last_regenerate|i:1508506467;`

The first file should have been started with the line second file contains but it's not the case.

Can you help in this? I'm not able to get any help for it.

**Comment by narfbg** [comment]
This is a bug tracker, we don't provide the help you're looking for here. Please post on our [forums](https://forum.codeigniter.com/) instead.
