### ISSUE TITLE
num_rows() returns 1 for empty result, instead of 0

### ISSUE THREAD

**Issue by sygram** [bcit-ci/CodeIgniter#5308]
Hi there,

strangely $query->num_rows() returns 1 for empty result. Should be 0.

Steps to reproduce. Simply run an empty result query and print num_rows() 

CI_DB_mysqli_driver
5.5.50-MariaDB
PHP 5.4.16 (cli)
Code igniter Versions 3.1.4 to 3.1.6 

Regards

**Comment by narfbg** [comment]
Can't reproduce.
