### ISSUE TITLE
Error file Cache

### ISSUE THREAD

**Issue by demortx** [bcit-ci/CodeIgniter#5312]
After the updates, the file cache stopped working.

For some strange reason, public $path = WRITEPATH.'cache/'; here comes another way

is_writable(): open_basedir restriction in effect. File(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin/) is not within the allowed path(s): 

if comment out //public $path = WRITEPATH.'cache/'; then it starts working

**Comment by narfbg** [comment]
"the updates"?

`CI_Cache_file` hasn't been changed in over a year, it has never had a `$path` property and there's no `WRITEPATH` constant in CI.
