### ISSUE TITLE
Drivers : Can a driver child access its siblings methods?

### ISSUE THREAD

**Issue by bkader** [bcit-ci/CodeIgniter#5313]
Greetings and thanks for your awesome work.
I have an issue with **CodeIgniter** drivers! Let's suppose I have a driver named **App** and inside **drivers** folder I have **App_child_one** and **App_child_two**
`App_child_one extends CI_Driver { ...} has method_one() {}`
and
`App_child_two extends CI_Driver { ...} has method_two() {}`
How can I access `App_child_two::method_two()` from `App_child_one` knowing that I have tried:
`$this->CI->app->child_two->method_two()`  but I get this error:
`Undefined property: CI::$app`
Thanks in advance.

**Comment by narfbg** [comment]
This is a bug tracker, not the place to ask questions like this.

I see that you've already also posted on our [forums](https://forum.codeigniter.com/thread-69250.html), which is the right place, but please don't cross-post in the future.

**Comment by bkader** [comment]
My sincere apologies
