### ISSUE TITLE
Fatal error: Call to a member function getShared() on null in Initializable.php on line 254 

### ISSUE THREAD

**Issue by ggchino** [bcit-ci/CodeIgniter#5314]
Help:
the next error jumps when trying to see webtools.
Fatal error: Call to a member function getShared() on null in C:\xampp\phalcon-devtools\scripts\Phalcon\Initializable.php on line 254 
using the following versions in windows:
   PHP Version: 5.6.31
   Phalcon DevTools Version: 3.2.8
   Phalcon Version: 3.2.4

**Comment by narfbg** [comment]
This is a bug tracker, we don't provide here.
And you're not even using CodeIgniter.
