### ISSUE TITLE
Unable to locate the model you have specified

### ISSUE THREAD

**Issue by anhdle14** [bcit-ci/CodeIgniter#5317]
`An uncaught Exception was encountered
Type: RuntimeException
Message: Unable to locate the model you have specified: Category_mod
Filename: /mnt/d/Projects/www/VYSA/system/core/Loader.php
Line Number: 344
Backtrace:

File: /mnt/d/Projects/www/VYSA/application/core/MY_Controller.php
Line: 4
Function: __construct

File: /mnt/d/Projects/www/VYSA/application/core/MY_Controller.php
Line: 19
Function: __construct

File: /mnt/d/Projects/www/VYSA/index.php
Line: 315
Function: require_once`

Hello guys, i am new to CI, and i don't know how to deploy it on another platform. I copy only the applications folder to another computer and setting up CodeIgniter (clean) from web but that error turned up. 

And i have tried to fix a2enmod, manually load, change autoload for database, .htaccess and changing name as guide [On my Laptop running Ubuntu 16.04]

At first i thought it was because of git LF and CRLF. So i try to use Bash On Windows. I am using Windows 10 (Version 10.0.16299 Build 16299), and i have also tried to use Bash On Windows with LAMP setup and could not start the CI project, whil MAMP in Windows with a different port could run it without problem.  Thanks in advance if anyone could came up with a solution, because i have tried to research it for a week but i could not fix it.

**Comment by gxgpet** [comment]
@anhdle14 Welcome to CodeIgniter community! :) Here, on GitHub, this section is used for bug tracking. For general questions and help for your projects, you should post/ask on the [forums](https://forum.codeigniter.com/).

**Comment by jim-parry** [comment]
Agreed - post this question on our forum, please.
This sounds like a case sensitivity problem, where your filename must be "Category_mod.php", from your message.
