### ISSUE TITLE
Gujarati font not supported in UTF-8

### ISSUE THREAD

**Issue by bhavsardhruv** [bcit-ci/CodeIgniter#5318]
hello everyone, 
I am using this library to create PDF in my project. 
But i am failed to create PDF as my desired output.
I need PDF with my actual data in Mysql.
I have Gujarati language in mysql with utf8_general_ci..

How can i solve my proble.?

**Comment by citrix123** [comment]
Do you mean you are trying to make HTML to PDF?
if yes , try mpdf .. it works fine, Hope it will work same with Gujraty fonts too.

**Comment by bhavsardhruv** [comment]
yes but if i want to use TCPDF then is there any solution.?
Because i have already implemented and the project is huge..

**Comment by citrix123** [comment]
Not sure how tcpdf works, I used mPDF yesterday and it was fine.
BTW i seen CodeIgniter with TCPDF documents: https://github.com/bcit-ci/CodeIgniter/wiki/TCPDF-Integration , go through it, if that helps :)

**Comment by bhavsardhruv** [comment]
I have already gone through with all this and also googled it before i post issue here..
It is worth it for me.. 
thanks for the reply.

**Comment by citrix123** [comment]
Then the last option is to go through the TCPDF documentation: https://tcpdf.org/examples/example_018/

or post your code (Mainly language array), so someone can help you over it.

**Comment by jim-parry** [comment]
We use github for bug tracking. Support questions should be raised on our [forum](https://forum.codeigniter.com/), thanks.
