### ISSUE TITLE
if()语句逻辑性错误

### ISSUE THREAD

**Issue by sxs89** [bcit-ci/CodeIgniter#5319]
$m							= 0;
$n							= 0;	
for($i=0;$i<200;$i++){
	if($temp_list[$i][wendu] < 0 && $m == 0){
			$m		= 1;
			$n++;
		}
		if($temp_list[$i][wendu] >= 0 && $m = 0){

		}

}
这样写if(）语句竟然可以通过编译，而且$m=0成功的把值传递了过去。求解答？

**Comment by jim-parry** [comment]
Sorry - English only. Also, if this is a support question, raise it on our forum.
