### ISSUE TITLE
not able to upload data in database but file is showing on folder

### ISSUE THREAD

**Issue by anandlinast** [bcit-ci/CodeIgniter#5322]
controller:\\
public function store_incident(){
		$config = [
			'upload_path'	=>		'./uploads',
			'allowed_types'	=>		'jpg|gif|png|jpeg|pdf',
		];
		$this->load->library('upload', $config); 
       $this->load->library('form_validation');
		if($this->form_validation->run('incident_rules') && $this->upload->do_upload()) {
 			 $insert_data = array(
         'incident_id' => $this->input->post('incident_id'),
          'description' => $this->input->post('description'),
          'date_created' => $this->input->post('date_created'),
          'created_by' => $this->input->post('created_by'),
          'user_id' => $this->session->userdata('user_id'),
		  'mode_of_receving' => $this->input->post('mode_of_receving'),
          'department' => $this->input->post('department'),
          'application' => $this->input->post('application'),
           'ticket_category' => $this->input->post('ticket_category'),
           'ticket_sub_type' => $this->input->post('ticket_sub_type'),
           'priority' => $this->input->post('priority'),
           'sla' => $this->input->post('sla'),
           'image_path' => $this->upload->data($image_path),
           'status' => $this->input->post('status'),
               'ticket_type' => $this->input->post('ticket_type')); 
			//$post = $this->input->post();
  			unset($insert_data['submit']);
			$data = $this->upload->data();
			 //echo "<pre>";
			 //print_r($data); exit;
			$image_path = base_url("uploads/" . $data['raw_name'] . $data['file_ext']);
			   //echo $image_path; exit;
			$insert_data['image_path'] = $image_path;
			$this->load->model('Admin_model');
		    if($this->Admin_model->add_incident($insert_data)){
				$this->session->set_flashdata('feedback',"incident added successfully");
				 				 $this->session->set_flashdata('feedback_class','alert-success');

			}
			else
			{
	           $this->session->set_flashdata('feedback',"failed to add data");
				                $this->session->set_flashdata('feedback_class','alert-danger');
 			}
			return redirect('admin/my_incident'); 
		} 
		else
		{
	else
		{
 		$data['dropdowns']=$this->admin_model->dropdown();
	  	$data['dropdowns_menu']=$this->admin_model->dropdown_menu();
	  $this->load->view('frame/header_view');
      $this->load->view('frame/sidebar_d_nav_view',$data);
	   $this->load->model('Admin_model');
 		 $department = $this->Admin_model->get_department_list();
		$application = $this->Admin_model->get_application_list();
		$categories=$this->Admin_model->get_ticket_categories_list();
		$ticket_type = $this->Admin_model->get_ticket_type_list();
		$ticket_sub_type = $this->Admin_model->get_ticket_sub_type_list();
		$priority_list= $this->Admin_model->get_priority_list();
		$sla_list= $this->Admin_model->get_sla_list();
		$user_list= $this->Admin_model->get_user_list();
		$upload_error = $this->upload->display_errors();

 		$this->load->view('admin/create_incident',['ticket_type'=>$ticket_type,'ticket_sub_type'=>$ticket_sub_type,'department'=>$department,'application'=>$application,'categories'=>$categories,'priority_list'=>$priority_list,'sla_list'=>$sla_list,'user_list'=>$user_list]);
  	 $this->load->view('frame/footer_view');
 		}
	}
	

view:///
 <div class="row float-left">
		 
			  <div class="col-lg-5">
         <div class="form-group">
      <label for="inputEmail" class="col-lg-4 control-label">Select Image</label>
      <div class="col-lg-8">

      <?php echo form_upload(['name'=>'userfile','class'=>'form-control']); ?>
		  
		  <div class="col-lg-10">
        <?php if(isset($upload_error)) echo $upload_error ?>
      </div>
      </div>
    </div>
         
	</div>
  	  </div>

model:
  function add_incident($insert_data)
	{              
		  $incident_id = $this->generate_incident_id();
            $insert_data = array(
         'incident_id' => md5($incident_id),
          'description' => $this->input->post('description'),
          'date_created' => $this->input->post('date_created'),
          'created_by' => $this->input->post('created_by'),
          'user_id' => $this->session->userdata('user_id'),
		  'mode_of_receving' => $this->input->post('mode_of_receving'),
          'department' => $this->input->post('department'),
          'application' => $this->input->post('application'),
           'ticket_category' => $this->input->post('ticket_category'),
           'ticket_sub_type' => $this->input->post('ticket_sub_type'),
           'priority' => $this->input->post('priority'),
           'sla' => $this->input->post('sla'),
           'status' => $this->input->post('status'),
              'ticket_type' => $this->input->post('ticket_type')); 
		  
   		 return $this->db->insert('my_incident', $insert_data);
	}

**Comment by narfbg** [comment]
This is a bug tracker; please post your questions on our [forums](https://forum.codeigniter.com/) instead.
