### ISSUE TITLE
Contributing.md codeigniter repository link redirects to https://github.com/bcit-ci/CodeIgniter>

### ISSUE THREAD

**Issue by vinodselvin** [bcit-ci/CodeIgniter#5325]
When I clicked on Codeigniter repository on Contributing.md, it redirects to https://github.com/bcit-ci/CodeIgniter>, there is some extra greater than symbol, creating issue, creating the problem, so i am creating new pull request for that.

**Comment by narfbg** [comment]
Just for future reference, you can directly create a pull request without opening a separate issue.

(referencing #5326)
