### ISSUE TITLE
Router.php - preg_replace 

### ISSUE THREAD

**Issue by mkannan22** [bcit-ci/CodeIgniter#5327]
Would anyone be able to explain why or why not the preg_replace function is potentially vulnerable inside of Router.php? Specifically on line 413.

**Comment by narfbg** [comment]
It's not.

Also, this is a bug tracker; please ask your questions on our [forums](https://forum.codeigniter.com/) instead.

**Comment by mkannan22** [comment]
Will do. Thanks for the response. I will look for additional information there.
