### ISSUE TITLE
auto_link issue with domain type email

### ISSUE THREAD

**Issue by fwsrv** [bcit-ci/CodeIgniter#5331]
I noticed a problem with auto_link the other day and so tested this on a fresh install of CI 3.1.6 to make sure its not of my own doing. The install has nothing but the following code added to welcome.php

```
<?php 
        $this->load->helper('url');  
        $string = "this is some text that includes www.email@domain.com which is causing an issue";
        echo auto_link($string);
?>
```

if a user adds text that includes an email that is in the following format and we then use auto link on this 

`this is some text that includes www.email@domain.com which is causing an issue`

the output goes something like this

`this is some text that includes //'; l[1] = 'a'; l[2] = '/'; l[3] = '<'; l[4] = '|109'; l[5] = '|111'; l[6] = '|99'; l[7] = '|46'; l[8] = '|110'; l[9] = '|105'; l[10] = '|97'; l[11] = '|109'; l[12] = '|111'; l[13] = '|100'; l[14] = '|64'; l[15] = '|108'; l[16] = '|105'; l[17] = '|97'; l[18] = '|109'; l[19] = '|101'; l[20] = '|46'; l[21] = '|119'; l[22] = '|119'; l[23] = '|119'; l[24] = '>'; l[25] = '"'; l[26] = '|109'; l[27] = '|111'; l[28] = '|99'; l[29] = '|46'; l[30] = '|110'; l[31] = '|105'; l[32] = '|97'; l[33] = '|109'; l[34] = '|111'; l[35] = '|100'; l[36] = '|64'; l[37] = '|108'; l[38] = '|105'; l[39] = '|97'; l[40] = '|109'; l[41] = '|101'; l[42] = '|46'; l[43] = '|119'; l[44] = '|119'; l[45] = '|119'; l[46] = ':'; l[47] = 'o'; l[48] = 't'; l[49] = 'l'; l[50] = 'i'; l[51] = 'a'; l[52] = 'm'; l[53] = '"'; l[54] = '='; l[55] = 'f'; l[56] = 'e'; l[57] = 'r'; l[58] = 'h'; l[59] = ' '; l[60] = 'a'; l[61] = '<'; for (var i = l.length-1; i >= 0; i=i-1) { if (l[i].substring(0, 1) === '|') document.write("&#"+unescape(l[i].substring(1))+";"); else document.write(unescape(l[i])); } //]]> ">www.email@domain.com which is causing an issue`

tested this on a local machine running latest wampserver and a live apache system

**Comment by narfbg** [comment]
That's intentional and is supposed to prevent that email from reaching spambot databases. Detected email addresses are internally passed through another helper that's already available: [safe_mailto()](https://www.codeigniter.com/user_guide/helpers/url_helper.html#safe_mailto).

**Comment by fwsrv** [comment]
sorry but that does not make any sense, the output simply fails and instead shows the code I mentioned. 

I dont see how this has anything to do with preventing emails being kept safe.

The issue is that an email formatted with www. at the start causes an error

> email@domain.com - works fine
> prefix.email@domain.com - works fine
> www.email@domain.com - causes the error

it must be confusing the email with a url

**Comment by narfbg** [comment]
Sorry, I guess I misunderstood what you're asking and TBH I didn't give a detailed look at your sample as I already know what it's supposed to do.

However:

> sorry but that does not make any sense, the output simply fails and instead shows the code I mentioned.

- What do you mean by "output simply fails"? Something either outputs or doesn't; you can't say that it fails if it does show something.
- The sample you've shown can't possibly be correct. Any return value of `safe_mailto()` would include a `<script>` tag, as well as any link produced by `auto_link()` including an `<a>` tag.

**Comment by fwsrv** [comment]
ok, i see when i view the source what you mean about the output. My point though is that some of that shows up on the user side as well as in the source. so instead of seeing a link in the browser we see the code instead.

if we use **auto_link($string, 'url')** we get a formatted url for the domain extension. Even though the user entered an email address its being treated as a url.

`<a href="http://www.email@domain.com">www.email@domain.com</a>`

if we use **auto_link($string, 'email')** we get the output as expected and the source shows as expected

```
<script type="text/javascript">
--
  | //<![CDATA[
  | var l=new Array();
  | l[0] = '>';
  | l[1] = 'a';
  | l[2] = '/';
  | l[3] = '<';
  | l[4] = '\|109';
  | l[5] = '\|111';
  | l[6] = '\|99';
  | l[7] = '\|46';
  | l[8] = '\|110';
  | l[9] = '\|105';
  | l[10] = '\|97';
  | l[11] = '\|109';
  | l[12] = '\|111';
  | l[13] = '\|100';
  | l[14] = '\|64';
  | l[15] = '\|108';
  | l[16] = '\|105';
  | l[17] = '\|97';
  | l[18] = '\|109';
  | l[19] = '\|101';
  | l[20] = '\|46';
  | l[21] = '\|119';
  | l[22] = '\|119';
  | l[23] = '\|119';
  | l[24] = '>';
  | l[25] = '"';
  | l[26] = '\|109';
  | l[27] = '\|111';
  | l[28] = '\|99';
  | l[29] = '\|46';
  | l[30] = '\|110';
  | l[31] = '\|105';
  | l[32] = '\|97';
  | l[33] = '\|109';
  | l[34] = '\|111';
  | l[35] = '\|100';
  | l[36] = '\|64';
  | l[37] = '\|108';
  | l[38] = '\|105';
  | l[39] = '\|97';
  | l[40] = '\|109';
  | l[41] = '\|101';
  | l[42] = '\|46';
  | l[43] = '\|119';
  | l[44] = '\|119';
  | l[45] = '\|119';
  | l[46] = ':';
  | l[47] = 'o';
  | l[48] = 't';
  | l[49] = 'l';
  | l[50] = 'i';
  | l[51] = 'a';
  | l[52] = 'm';
  | l[53] = '"';
  | l[54] = '=';
  | l[55] = 'f';
  | l[56] = 'e';
  | l[57] = 'r';
  | l[58] = 'h';
  | l[59] = ' ';
  | l[60] = 'a';
  | l[61] = '<';
  |  
  | for (var i = l.length-1; i >= 0; i=i-1) {
  | if (l[i].substring(0, 1) === '\|') document.write("&#"+unescape(l[i].substring(1))+";");
  | else document.write(unescape(l[i]));
  | }
  | //]]>
  | </script> 
```

if however, we use **auto_link($string, 'both')** we get the broken output shown in the browser with the source being as follows


```
<a href="http://<script type="text/javascript">
--
  | //<![CDATA[
  | var l=new Array();
  | l[0] = '>';
  | l[1] = 'a';
  | l[2] = '/';
  | l[3] = '<';
  | l[4] = '\|109';
  | l[5] = '\|111';
  | l[6] = '\|99';
  | l[7] = '\|46';
  | l[8] = '\|110';
  | l[9] = '\|105';
  | l[10] = '\|97';
  | l[11] = '\|109';
  | l[12] = '\|111';
  | l[13] = '\|100';
  | l[14] = '\|64';
  | l[15] = '\|108';
  | l[16] = '\|105';
  | l[17] = '\|97';
  | l[18] = '\|109';
  | l[19] = '\|101';
  | l[20] = '\|46';
  | l[21] = '\|119';
  | l[22] = '\|119';
  | l[23] = '\|119';
  | l[24] = '>';
  | l[25] = '"';
  | l[26] = '\|109';
  | l[27] = '\|111';
  | l[28] = '\|99';
  | l[29] = '\|46';
  | l[30] = '\|110';
  | l[31] = '\|105';
  | l[32] = '\|97';
  | l[33] = '\|109';
  | l[34] = '\|111';
  | l[35] = '\|100';
  | l[36] = '\|64';
  | l[37] = '\|108';
  | l[38] = '\|105';
  | l[39] = '\|97';
  | l[40] = '\|109';
  | l[41] = '\|101';
  | l[42] = '\|46';
  | l[43] = '\|119';
  | l[44] = '\|119';
  | l[45] = '\|119';
  | l[46] = ':';
  | l[47] = 'o';
  | l[48] = 't';
  | l[49] = 'l';
  | l[50] = 'i';
  | l[51] = 'a';
  | l[52] = 'm';
  | l[53] = '"';
  | l[54] = '=';
  | l[55] = 'f';
  | l[56] = 'e';
  | l[57] = 'r';
  | l[58] = 'h';
  | l[59] = ' ';
  | l[60] = 'a';
  | l[61] = '<';
  |  
  | for (var i = l.length-1; i >= 0; i=i-1) {
  | if (l[i].substring(0, 1) === '\|') document.write("&#"+unescape(l[i].substring(1))+";");
  | else document.write(unescape(l[i]));
  | }
  | //]]>
  | </script>"><script type="text/javascript">
  | //<![CDATA[
  | var l=new Array();
  | l[0] = '>';
  | l[1] = 'a';
  | l[2] = '/';
  | l[3] = '<';
  | l[4] = '\|109';
  | l[5] = '\|111';
  | l[6] = '\|99';
  | l[7] = '\|46';
  | l[8] = '\|110';
  | l[9] = '\|105';
  | l[10] = '\|97';
  | l[11] = '\|109';
  | l[12] = '\|111';
  | l[13] = '\|100';
  | l[14] = '\|64';
  | l[15] = '\|108';
  | l[16] = '\|105';
  | l[17] = '\|97';
  | l[18] = '\|109';
  | l[19] = '\|101';
  | l[20] = '\|46';
  | l[21] = '\|119';
  | l[22] = '\|119';
  | l[23] = '\|119';
  | l[24] = '>';
  | l[25] = '"';
  | l[26] = '\|109';
  | l[27] = '\|111';
  | l[28] = '\|99';
  | l[29] = '\|46';
  | l[30] = '\|110';
  | l[31] = '\|105';
  | l[32] = '\|97';
  | l[33] = '\|109';
  | l[34] = '\|111';
  | l[35] = '\|100';
  | l[36] = '\|64';
  | l[37] = '\|108';
  | l[38] = '\|105';
  | l[39] = '\|97';
  | l[40] = '\|109';
  | l[41] = '\|101';
  | l[42] = '\|46';
  | l[43] = '\|119';
  | l[44] = '\|119';
  | l[45] = '\|119';
  | l[46] = ':';
  | l[47] = 'o';
  | l[48] = 't';
  | l[49] = 'l';
  | l[50] = 'i';
  | l[51] = 'a';
  | l[52] = 'm';
  | l[53] = '"';
  | l[54] = '=';
  | l[55] = 'f';
  | l[56] = 'e';
  | l[57] = 'r';
  | l[58] = 'h';
  | l[59] = ' ';
  | l[60] = 'a';
  | l[61] = '<';
  |  
  | for (var i = l.length-1; i >= 0; i=i-1) {
  | if (l[i].substring(0, 1) === '\|') document.write("&#"+unescape(l[i].substring(1))+";");
  | else document.write(unescape(l[i]));
  | }
  | //]]>
  | </script></a>
```

The error only occurs when an email starts with www. and we are using the default **'both'** param in the auto_link function. eg www.email@domain.com

If the email had any other prefix such as prefix.email.com everything works as expected.

**Comment by narfbg** [comment]
That should do it.

**Comment by fwsrv** [comment]
yes, thats cracked it. good job 👍
