### ISSUE TITLE
CI_Model construct error

### ISSUE THREAD

**Issue by it-can** [bcit-ci/CodeIgniter#5332]
Since commit https://github.com/bcit-ci/CodeIgniter/commit/c9420849853a33a192c482e28c737e166d4fa698 I am getting this error now

```
Cannot call constructor
```

this is my model

```
class Test_model extends CI_Model
{
    private $_table = 'test';

    public function __construct()
    {
        parent::__construct();
    }
}
```

**Comment by benedmunds** [comment]
@narfbg looks like this is in stable but not develop.  I'm seeing issues related to this since most models that extend CI_Model call parent::__construct().

**Comment by narfbg** [comment]
@benedmunds Yes, but that's intentional: c45caeac4f45b83fbb3655f62638ebcf913981c8

**Comment by benedmunds** [comment]
Ah thanks @narfbg I didn't realize it was intentional

**Comment by TatwiraT** [comment]
for me , I used to use a common model where I put some extra helpers to be used in all inheriting models like 
custom 
where_by()
order_by()
also for encapsulation ..

how could I do that in the next release ?

**Comment by devlinbezerra** [comment]
Perhaps your CI version doesn't provide a constructor in CI_Model class. Take a look at System/core/Model.php and check if the class CI_Model has a constructor. If it doesn't then it is impossible to call a constructor, for it is doesn't even exist.

**Comment by jbrahy** [comment]
I had this error while upgrading an old project from 2 to 3 but commenting out the constructor call in the models made it work. I'm concerned about why but it's working.

**Comment by Mekongg** [comment]
![image](https://user-images.githubusercontent.com/110175196/181507226-06c2e4e6-bd5b-40e1-a4d0-f0913b6b7f7e.png)
sory i stundents plise help me how to fix it🙏

**Comment by Reconix** [comment]
> ![image](https://user-images.githubusercontent.com/110175196/181507226-06c2e4e6-bd5b-40e1-a4d0-f0913b6b7f7e.png)
> sory i stundents plise help me how to fix it🙏

Why would you post this, the thread is over five years old.
Try creating a new issue with plenty of information or head on over to the forums, the community is very friendly and helpful.
