### ISSUE TITLE
Session expiration bug?

### ISSUE THREAD

**Issue by romankubis** [bcit-ci/CodeIgniter#5335]
https://github.com/bcit-ci/CodeIgniter/blob/7e4f63cd4b792e7dc2dc4b8b0183a6072a3f9462/system/libraries/Session/Session.php#L299

Hello,
if I will set session expiration to expire after browser window close ($config['sess_expiration'] = 0;) then expiration is set to session.gc_maxlifetime because PHP function "empty" returns TRUE on 0 value.
Sorry, if I am wrong about this but I think that this row of code logs out user in my app after gc_maxlifetime  seconds (default 1440).

**Comment by narfbg** [comment]
This is not a bug.

0 is still being used as the *cookie* expiration time, which is how "expire when browser is closed" works. But sessions still need to be expired on the server side and servers don't know when browsers are closed, so yes - they will expire after `gc_maxlifetime` seconds.

**Comment by romankubis** [comment]
Thanks for explanation.
