### ISSUE TITLE
CI_Model "__constuctor" can not inherit in model.

### ISSUE THREAD

**Issue by zgetro** [bcit-ci/CodeIgniter#5336]
i updated my CI code with develop branch and found this issue on working application.
in applicartion i have code as define below 
<?php

defined('BASEPATH') OR exit('No direct script access allowed');

Class LoginModel extends CI_Model {
public function __construct() {
        parent::__construct(); //------------------------- it shows me  FATAL error on this line. 
        $this->load->database();
} 

....
}
?>

**Comment by narfbg** [comment]
The "code as define below" is not showing; you can't just copy-paste code - use the formatting tools.

Anyway, the develop branch is a **DEVELOPMENT BRANCH**. If you don't follow the changes we make, don't use it.

**Comment by zgetro** [comment]
>  the develop branch is a DEVELOPMENT BRANCH. If you don't follow the changes we make, don't use it.
agree with your point. i am just point you a bug

**Comment by narfbg** [comment]
This is intentional and there's no bug.
