### ISSUE TITLE
Awkward Sentence in Documentation

### ISSUE THREAD

**Issue by DistrictOperator** [bcit-ci/CodeIgniter#5337]
I am having trouble understanding this sentence:

> By default library connect to database provided in "default" group.

It is on this page:
[https://github.com/bcit-ci/CodeIgniter/wiki/Using-MongoDB-in-Codeigniter](https://github.com/bcit-ci/CodeIgniter/wiki/Using-MongoDB-in-Codeigniter)

Can some please explain a bit more about what this means?

**Comment by narfbg** [comment]
That's a users' wiki page, not official documentation.
And this is a bug tracker ... Please ask your questions on our [forums](https://forum.codeigniter.com/) instead.
