### ISSUE TITLE
Error 404 with unicode character in the URL like Japanese

### ISSUE THREAD

**Issue by phongtnit** [bcit-ci/CodeIgniter#5338]
Hi,

I want to allow Unicode character in the URL like Japanese.

I added in my route.php
> $route['category/(:any)'] = 'Category/view/$1'; 

When I tried access "category/大人っぽすぎる小学生が中学３年生にもなると.html", it's ok. However with the string "category/筧美和子さんのニットの衣装が素晴らしすぎる.html", it failed and return 404 error ([see this image](https://imgur.com/8lCA7s4)

I don't know why and how to fix it. Please help me, many thanks,

**Comment by narfbg** [comment]
This is a bug tracker. Please ask your questions on our [forums](https://forum.codeigniter.com/).

**Comment by phongtnit** [comment]
I guess this is a bug,

**Comment by narfbg** [comment]
It's not.
