### ISSUE TITLE
CodeIgniter v3.1.6 (Current version) not worked with PHP 7.1.7 

### ISSUE THREAD

**Issue by odykyi** [bcit-ci/CodeIgniter#5339]
CodeIgniter v3.1.6 (Current version) not worked with PHP 7.1.7 

Please add supported versions to CodeIgniter

In bcit-ci/CodeIgniter/readme.rst writed

"PHP version 5.6 or newer is recommended."

The Newer version(7.1.7) not worked!

**Comment by gxgpet** [comment]
What exactly isn't working? You have to provide us more details about the issue you encounter ...

**Comment by narfbg** [comment]
It does work.

If you believe you've found a bug, be specific - "not worked" means nothing.
