### ISSUE TITLE
Unsanitized User Input - /system/libraries/Upload.php

### ISSUE THREAD

**Issue by Alexalas** [bcit-ci/CodeIgniter#5343]
The name of the file "0[name]" is received in method CI_Upload::do_upload() in line 379 of example/system/libraries/Upload.php.

It is concatenated into path markup in function do_upload() in line 568 of example/system/libraries/Upload.php.

The user-supplied data is then used unsanitized in the sensitive operation move_uploaded_file() in method CI_Upload::do_upload() in line 568 of example/system/libraries/Upload.php.

374 | class CI_Upload{public function do_upload($field = 'userfile'){

379 | $_file = $_FILES[$field];

384 | $_file = $_FILES;

390 | $_file = NULL;

394 | $_file = $_file[$field];

568 | move_uploaded_file($this->file_temp, $this->upload_path . $this->file_name);

**Comment by narfbg** [comment]
There's a gap of ~170 LOC between those lines 394-568, which you've ignored. It's not "unsanitized".

**Comment by narfbg** [comment]
Something else I forgot to mention yesterday ...

We do have both a security@ email and a HackerOne program (both linked in the readme file). Please use those for reporting security issues.
