### ISSUE TITLE
CodeIgniter/application/config - $config['cookie_httponly']

### ISSUE THREAD

**Issue by Alexalas** [bcit-ci/CodeIgniter#5345]
The default value of $config['cookie_httponly'] is false. This enables all javascript to read the cookie value including malicious scripts. As a security measure, this should be true by default.

**Comment by narfbg** [comment]
I'll let you in on a secret: JavaScript often works with cookies too.

You've submitted 3 issues within 10 minutes and have put 0 thought in them; stop spamming us.
