### ISSUE TITLE
Pass an object/array in the language library, in the load method

### ISSUE THREAD

**Issue by joalVM** [bcit-ci/CodeIgniter#5346]
Imagine that instead of the library looking for a file in the language folder, we could assign it our own object type variable, like this:
```php
$lang = (Object)[
 "en" => (Object)[
   "hello" => "world"
  ]
];

$this->lang->load($lang, "en");
```

_sorry my english, but I used the google translator XD_

**Comment by narfbg** [comment]
Why would you need that?
