### ISSUE TITLE
Email not working in Codeigniter develop

### ISSUE THREAD

**Issue by ubeljan** [bcit-ci/CodeIgniter#5348]
Hello,

While sending a email there comes a error.
Codeigniter in complaning about a variable $atpos.

The fix seen in https://github.com/bcit-ci/CodeIgniter/issues/5300 does work.
Line 1824 in libraries/email.php

if (function_exists('idn_to_ascii') && $atpos = strpos($email, '@'))

instead of

if (function_exists('idn_to_ascii') && strpos($email, '@'))

Greetings,
Ubel Jan van Wijhe

**Comment by narfbg** [comment]
Thanks, a [merge](432a9130059873551d1cff3e40d1d8432f552b96) seems to have broken it.

**Comment by Nudasoft** [comment]
Why not doing tests before do the merge?

**Comment by gxgpet** [comment]
Some unit tests for those most used components would be useful, actually :)
