### ISSUE TITLE
Email SSL issue

### ISSUE THREAD

**Issue by salchee** [bcit-ci/CodeIgniter#5349]
Hi there. I was having a problem in last update of codeigniter which was using php7.1 
It was saying some problems for ssl certificate. I just want to tell the way i fixed it:
in email library in line 2009 just comment the fsockopen and instead type this:
$context = stream_context_create(array(
                'ssl' => array(
                    "verify_peer"      => false,
                    "verify_peer_name"=>false,
                ),
            )
        );

        $this->_smtp_connect = stream_socket_client(
            $ssl.$this->smtp_host,
            $errno,
            $errstr,
            $this->smtp_timeout,
            null, $context);

**Comment by narfbg** [comment]
This is a bug tracker, not a forum board. Please don't post things like that.
