### ISSUE TITLE
Fetches the homepage when suffixed . (period) at the end of the URL

### ISSUE THREAD

**Issue by HyndexCoder** [bcit-ci/CodeIgniter#5352]
Whenever a . (period) is suffixed at the end of any url (but before query string), then no matter what, CodeIgniter will always load the homepage.

**Comment by narfbg** [comment]
Can't reproduce. Likely caused by your routing rules; post on our [forums](https://forum.codeigniter.com/) if you need help with that.

**Comment by HyndexCoder** [comment]
somehow magically it seems that the problem has gone from my machine too.
