### ISSUE TITLE
Welcome and error pages - font sizes

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#5353]
The font sizes of the welcome and error pages are likely thought on 13px base size for normal texts. Could it be increased to 16px and other font sizes to be increased proportionally? At the moment the normal texts are hardly readable.

**Comment by narfbg** [comment]
I've always had a strong preference for smaller font sizes, but I won't take side on this as I know most people aren't like me in that regard. If there's one remark I could mention is that probably nobody cares about the welcome page. :D 

@jim-parry Up to you here.

**Comment by jim-parry** [comment]
This is in the application folder, hence clearly a developer preference. Some would like small & some large. 
Looking at the welcome_message view, the default font is already 16px, while <h1> is 22px, <code> is 12px, and the footer is 12px. Sounds like what is being asked for is there already??
The error pages, where they specify font sizes, seem to be the same, except using 13px for <code>.
I don't see that there is anything that should change.

**Comment by ivantcholakov** [comment]
Ok, I did it alone, let us not waste time on this.
