### ISSUE TITLE
[Pagination] $config['cur_page'] is not in document

### ISSUE THREAD

**Issue by yidas** [bcit-ci/CodeIgniter#5355]
In [Pagination](https://www.codeigniter.com/userguide3/libraries/pagination.html#) section, there are only  `$config['uri_segment'`] but no `$config['cur_page']`, which mention how to set CI Pagination's current page number.

I suggest to add `$config['cur_page']` to document.

**Comment by narfbg** [comment]
Fair enough, although it's not really designed for you to use `cur_page`. Why would you do that instead of using `uri_segment`?

**Comment by yidas** [comment]
I agree, `uri_segment` should be used for current page info.

The thing is that I told my member to practice Pagination of CI3. After review, I found it used `uri_segment` to fetch current page and it worked, then I guided to find current page number key for Pagination, but I could not find such key in CI document until I found `cur_page` key in StackOverflow.

Thanks.

**Comment by narfbg** [comment]
I don't understand. What did you need/use `cur_page` for? And does it still need documenting? (if it doesn't, you can close issues that you've created)

**Comment by yidas** [comment]
In the case that the current page number is not come from `uri_segment`,  but come from `$_GET` etc.

I think it's instinctive to set current page to Pagination with a number as an option.

**Comment by narfbg** [comment]
There's `page_query_string` if you want/need to use `$_GET` ("query string" is the proper name for what gets parsed into the `$_GET` variable).

I don't know how instinctive? it is to try to set `cur_page` yourself, but it wouldn't even work that way, as the library has to also generate the links, not just know which page it is on.
