### ISSUE TITLE
Did we need to restrict $where parameter in database class update?

### ISSUE THREAD

**Issue by plonknimbuzz** [bcit-ci/CodeIgniter#5356]
https://github.com/bcit-ci/CodeIgniter/blob/3ecfcaa94bbae55fec8c2c9bbf8524c49816342f/system/database/DB_query_builder.php#L1888

i miss writing 3rd parameter in update ($where). This happened to me 3 times in last 3 years on my CI usage. lucky these only happen when i starting to build new project (still on dummy db)

but how if someone miss doing this in the real apps? like this example:
```
$this->db->query('truncate table test');
$this->db->insert('test', array('name'=>'a')); //1 a
$this->db->insert('test', array('name'=>'b'));	//2 b
//$this->db->update('test', array('name'=>'c'), array('name'=>'b')); //the right writing
$this->db->update('test', array('name'=>'c')) //wrong writing; 
```
data should be : 1 a ;2 c but  because of the typo /forget the where clause (3rd parameter), so this will update all column `name` into `c` value

**Comment by narfbg** [comment]
While `update()` can be used on its own, like in your case, it is also very often (if not mostly) used in combination with separate `where()`, `limit()`, etc. calls ... So how do you suggest it be restricted?

**Comment by plonknimbuzz** [comment]
i'll check this again after office hour

**Comment by plonknimbuzz** [comment]
after several case trial modify the core. this is hard for now , because:
1. we use `$this->_merge_cache();` (4 years using CI, and i just know if `update()` work like this. i thought `update()`, `insert()`, etc is independent)
2. SQL allow update without where clause

i think this issue should closed for now, because maybe we can break someone behaviour if we restrict `$where` clause.
and we looks/wait is there any other complaint about this or not. 

thanks narf.

**Comment by narfbg** [comment]
Well, `insert()` is kind of independent, but that's only because there's no extra clauses to combine it with.

Anyway, for future reference - you too can close an issue if you've created it yourself.
