### ISSUE TITLE
User guide small error

### ISSUE THREAD

**Issue by AzaZPPL** [bcit-ci/CodeIgniter#5360]
There is a small error on https://www.codeigniter.com/userguide3/general/urls.html
The rewrite is in text

**Comment by plonknimbuzz** [comment]
yes. but it was fixed on this commit https://github.com/bcit-ci/CodeIgniter/commit/ea21f113733e914d5d0c950d5bfb5c5624368407

**Comment by jim-parry** [comment]
Already fixed, as noted above.

**Comment by narfbg** [comment]
Marking as duplicate of #5283.
