### ISSUE TITLE
Codeigniter 2.2.6 Drop Session on concurrent ajax request

### ISSUE THREAD

**Issue by nasib-shl** [bcit-ci/CodeIgniter#5364]
I have updated my codeigniter version from 2.1.4 to 2.2.6 but still I am facing the issue. 
Session Drops and user kicks out of the site in an active session.

Below is my configuration:
$config['sess_expiration'] = 14000; 
$config['sess_expire_on_close'] = TRUE;
$config['sess_encrypt_cookie'] = TRUE;
$config['sess_use_database'] = TRUE;
$config['sess_table_name'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_match_useragent'] = TRUE;
$config['sess_time_to_update'] = 300;

**Comment by andersonunsonst** [comment]
update to Codeigniter 3, ..., Codeigniter 2 no longer supported
from userguide...
"ps. Make sure your 'base_url' configuration value is not empty"

**Comment by plonknimbuzz** [comment]
yes. i use CI 2.x.x for my old project. and i confused about session expired (especially remember me feature).
even i try sess_expiration = 0 . logged user will always kicked from session. 
But this not happened in my recent project which use CI 3.x.x

so, 1 weeks ago i update my old project from CI2 into CI3 and session issue was fixed.
hope this help you

**Comment by jim-parry** [comment]
CI 2 is no longer supported. You might have better luck posting on our forum, or indeed upgrading to CI3.
