### ISSUE TITLE
404 - File or directory not found.

### ISSUE THREAD

**Issue by Edgar1012** [bcit-ci/CodeIgniter#5365]
- Hi, am new to codeignator, i uploaded my project into godaddy. While in Local server its works , when i upload to online , i got the first image, when i try to call any function, that time its show me 404 File
- 
- 
- //  routes
- <?php
- defined('BASEPATH') OR exit('No direct script access allowed');
- 
- $route['default_controller'] = 'welcome';
- $route['404_override'] = '';
- $route['translate_uri_dashes'] = TRUE;
- $route['welcome/brand'] = 'brandControler';
- $route['welcome/area'] = 'beatControler';
- $route['welcome/supplier'] = 'suppliertype';
- $route['welcome/warehouse'] = 'warehouse';
- $route['welcome/customertype'] = 'customertype';
- $route['welcome/customer'] = 'customerControler';
- $route['welcome/product'] = 'productsControler';
- $route['ProductsControler/GetdataByid/(:any)/(:any)'] = 'ProductsControler/GetdataByid';
- 
- $route['welcome/PricetypeControler'] = 'pricetypeControler';
- $route['welcome/TaxControler'] = 'taxControler';
- 
- 
- // welcome controller
- <?php
- defined('BASEPATH') OR exit('No direct script access allowed');
- 
- class Welcome extends CI_Controller {
- 
- 
- 	public function __construct(){
- 
-         parent::__construct();
-   			$this->load->helper('url');
-   	 		$this->load->model('main_model');
-             $this->load->library('session');
-             $this->load->library('form_validation');
- 
- 
- }
- 	public function index()
- 	{
- 				$this->load->view('login');
- 
- 	}
- function login_validation(){
- 	            $this->load->library('form_validation');
- 	            $this->form_validation->set_rules('username','Username','required');
- 	            $this->form_validation->set_rules('password','Password','required');
- 	            if($this->form_validation->run()){
- 	            	// true
- 
- 
- 	            	$username = $this->input->post('username');
- 	                $password = $this->input->post('password');
- 
- 	                // model function
- 	                $this->load->model('main_model');
- 
- 	                if($this->main_model->can_login($username, $password)){
- 	                	$session_date = array(
- 	                		'username'=> $username);
- 
- 	                	$this->session->set_userdata($session_date);
- 
- 	                	redirect(base_url() . 'welcome/dashboad_main');
- 	                	//redirect('/welcome/enter');
- 
- 	                }else{
- 	                	$this->session->set_flashdata('error','Invalid Username and Password');
- 	                		         //redirect(base_url() . 'welcome/login_user');
- 	                		                    redirect('Welcome');
- 
- 					}
- 	            }else{
- 	            	//false
- 
- 	            	$this->login_user();
- 	            }
- 
- 
- }
- }
- 
- //
- 
- When i try to call **login_validation** this method from my view am getting 404 errror

**Comment by jim-parry** [comment]
We use github for bug tracking. Support questions should be asked on our [forum](https://forum.codeigniter.com/index.php), thanks.
