### ISSUE TITLE
Helpers not available in error_404.php template

### ISSUE THREAD

**Issue by HyndexCoder** [bcit-ci/CodeIgniter#5368]
I am using the `base_url` function in my `error_404.php` template file. It works fine when the requested controller is found, but it fails when the controller is not found.

I have already loaded the `url_helper` through the `autoload.php` file, but still it doesn't work.

**Comment by HyndexCoder** [comment]
I have found a work around [here](https://stackoverflow.com/a/39011298/4846835). But still the devs should make sure that this work around is no longer required.

**Comment by narfbg** [comment]
This is a technical limitation and even the work-around you have won't always work.

**Comment by HyndexCoder** [comment]
What kind of technical limitation? Can you please explain.

**Comment by narfbg** [comment]
The auto-loader is triggered by the controller constructor, because libraries (and other classes like models) loaded by it are assigned to controller properties, and that's the earliest execution point possible for this.

**Comment by HyndexCoder** [comment]
But in the work around, the `url_helper` is explicitly loaded using the statement
`$CI->load->helper('url');`
Where is the need to load the auto-loader?

**Comment by narfbg** [comment]
In your issue description?

> I have already loaded the url_helper through the autoload.php file, but still it doesn't work.

**Comment by HyndexCoder** [comment]
> even the work-around you have won't always work.

Why you said this?

**Comment by HyndexCoder** [comment]
Why will the work around won't always work?

**Comment by narfbg** [comment]
Because you can call `show_404()` or trigger another modified error template from inside a hook, before `CI_Controller` is even declared.

**Comment by HyndexCoder** [comment]
So isn't that something to fix? Or shouldn't we use any helpers inside error templates?

**Comment by narfbg** [comment]
No, it's not something to fix ... that's what a technical limitation is - not everything can work everywhere, it's not magic. Don't use external resources in your error templates.
