### ISSUE TITLE
Filename cached when uploading in a loop

### ISSUE THREAD

**Issue by judemanutd** [bcit-ci/CodeIgniter#5375]
When uploading multiple files using the upload library of codeigniter, it caches the first filename and applies the same file name to every uploaded file.
Following code snippet used to upload the file:

          
           for ($i = 0; $i < $tot_row; $i++) {
            $config['upload_path'] = $filepath;
            $config['file_name'] = $id . "_" . $doc_name . "_" . time();
            $config['allowed_types'] = VALID_FILE_TYPES;

            $this->load->library('upload', $config);

            if (!$this->upload->do_upload('file_' . $i)) {

            } else {
                $data = $this->upload->data();
                $upload_doc_path = $filepath . $data['file_name'];

            }
            unset($this->upload); // unsetting because codeigniter filename bug
        }

I am unsetting the upload library as the filename would get cached in the config and there was no way to change it. Setting` $config['file_name'] = null` and then setting the actual filename didn't help either.

**Comment by narfbg** [comment]
There's no bug - second, third, N+ attempts to load the same library are ignored, because the library is already loaded. There's also a debug message logged when that happens.

Use the `initialize()` method to reuse/reconfigure.
