### ISSUE TITLE
PHPExcel: Unable to connect to the Guide

### ISSUE THREAD

**Issue by mbazouz** [bcit-ci/CodeIgniter#5377]
In the wiki page of PHPExcel, there is a link of an updated guide: http://www.ahowto.net/php/easily-integrateload-phpexcel-into-codeigniter-framework

But when clicking, I have a page indicate that Firefox can’t establish a connection to the server at www.ahowto.net.

**Comment by jim-parry** [comment]
This is a resource external to CodeIgniter - not a bug in the framework :-/
