### ISSUE TITLE
Documentation may be wrong for count_all_results

### ISSUE THREAD

**Issue by emilebourquin** [bcit-ci/CodeIgniter#5378]
The docs for count_all_results at https://www.codeigniter.com/userguide3/database/query_builder.html say:

> However, this method also resets any field values that you may have passed to select(). If you need to keep them, you can pass FALSE as the second parameter:

> echo $this->db->count_all_results('my_table', FALSE);

Referencing #5180 , narfbg says 

> there's nothing to fix here. count_all_results() is meant to be applied to full queries, and without specifying the fields to select

so I'm guessing that the documentation is wrong, rather than expecting count_all_results('my_table', FALSE); to keep the SELECT'ed fields.

I came upon this when

$this->db->select('id');
$this->db->from('offers');
$num_offers = $this->db->count_all_results();
echo $this->db->last_query();

and 

$this->db->select('id');
$num_offers = $this->db->count_all_results('offers', FALSE);
echo $this->db->last_query();

both produce

SELECT COUNT(*) AS `numrows` FROM `offers`

Having said that, it would be nice to have $this->db->count_all_results('offers', FALSE); work, as I'm guessing it would be much more memory efficient for the database to COUNT('id') rather than COUNT(\*), especially if the table has a lot of data in each row, and/or a lot of joins are used in the query. Perhaps I'm wrong about that, since saying so for sure requires more knowledge of how COUNT(\*) actually works, than I have.

**Comment by narfbg** [comment]
The documentation isn't wrong and doesn't contradict what I've said there. I don't understand what this issue is about.

**Comment by emilebourquin** [comment]
I guess I'm misunderstanding the documentation for count_all_results. When it says 

> However, this method also resets any field values that you may have passed to select(). If you need to keep them, you can pass FALSE as the second parameter:

I expect

$this->db->select('id');
$num_offers = $this->db->count_all_results('offers', FALSE);
echo $this->db->last_query();

to produce

SELECT COUNT('id') AS numrows FROM offers

it instead produces

SELECT COUNT(*) AS numrows FROM offers

Is my expectation incorrect?

**Comment by narfbg** [comment]
Your expectation is incorrect, yes.

That sentence from the documentation means that anything you may've called `select()` with will be ignored ("reset"). Passing `FALSE` still ignores them for the `count_all_results()` call, but preserves them for a later `get()` call.

**Comment by emilebourquin** [comment]
Got it, thanks for the clarification.
My hope was that I could get count_all_results to just select id, rather than *, to keep the data MySQL is COUNTing as small as possible.
I'll use a COUNT('id') MySQL call to accomplish that, rather than count_all_results.

**Comment by narfbg** [comment]
`COUNT(*)` works on rows, not columns - it doesn't even need to know how much data is in there.
