### ISSUE TITLE
Issue with default controller.

### ISSUE THREAD

**Issue by Sm7llsfishy** [bcit-ci/CodeIgniter#5383]
Hi there,

Changing my default controller gives me a 404 for some reason.

Using the standard controller "Welcome.php"

`<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Welcome extends CI_Controller {

    /**
     * Index Page for this controller.
     *
     * Maps to the following URL
     * 		http://example.com/index.php/welcome
     *	- or -
     * 		http://example.com/index.php/welcome/index
     *	- or -
     * Since this controller is set as the default controller in
     * config/routes.php, it's displayed at http://example.com/
     *
     * So any other public methods not prefixed with an underscore will
     * map to /index.php/welcome/<method_name>
     * @see https://codeigniter.com/user_guide/general/urls.html
     */
    public function index()
    {
        $data['title'] = 'test';

        $this->load->view('welcome_message', $data);

    }
}
`

Works perfectly.

When i change, in "routes.php":

`$route['default_controller'] = 'welcome';`

to

`$route['default_controller'] = 'index';`

Which should revert to using this controller

`<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Index extends CI_Controller {

    /**
     * Index Page for this controller.
     *
     * Maps to the following URL
     * 		http://example.com/index.php/welcome
     *	- or -
     * 		http://example.com/index.php/welcome/index
     *	- or -
     * Since this controller is set as the default controller in
     * config/routes.php, it's displayed at http://example.com/
     *
     * So any other public methods not prefixed with an underscore will
     * map to /index.php/welcome/<method_name>
     * @see https://codeigniter.com/user_guide/general/urls.html
     */
    public function index()
    {
        $data['title'] = 'test';

        $this->load->view('welcome_message', $data);

    }
}
`

When reloading my base url in browser i get a 404, the page you requested was not found.

Thanks in advance for the help !

**Comment by jim-parry** [comment]
Ask support questions on our forum, thanks. 
"Index" is not an appropriate controller name.
