### ISSUE TITLE
Timezone in database configuration array To [ SET time_zone='+2:00' ]

### ISSUE THREAD

**Issue by pixieaka** [bcit-ci/CodeIgniter#5387]
we can handle this in auto load model with query $this->db->query('SET time_zone=\'+2:00\'');
but when clear previous query for any reason with query $this->db->reset_query() 
the time zone will reset too.
we can make in config file or in database config array option for timezone like 
$config['time_reference'] = ''; but for database.

**Comment by narfbg** [comment]
This isn't as simple as you think it is ...

In MySQL there's a session timezone and a global timezone, so there's an ambiguity right there. I don't know if that's the case with other database platforms, but they surely also have different timezone formats, and it is important that any DB class feature is implemented across *all* drivers.

But more importantly, your queries shouldn't depend on the timezone, so the entire feature would be very questionable to begin with. And you can't just throw any idea in here ... It's fine if you can't provide a PR with the implementation (that would be desirable though), but at the very least you have to provide convincing motivation for it, and try to use properly formatted sentences (this and another issue opened by you look like you're hastily writing something in a chatroom).

Also, reset_query() doesn't in any way revert this.
