### ISSUE TITLE
404 route Error in hosting

### ISSUE THREAD

**Issue by jamboljack** [bcit-ci/CodeIgniter#5392]
Hi, i create $route['404_override']         = 'error'; in local success. 
But in hosting i get error in picture
![whatsapp image 2018-01-29 at 14 02 53](https://user-images.githubusercontent.com/6668588/35498655-c3e01826-0501-11e8-9376-9c8ad7c298c6.jpeg)
This my controller 
![whatsapp image 2018-01-29 at 14 07 13](https://user-images.githubusercontent.com/6668588/35498712-f9945978-0501-11e8-9fb2-24a4bc83b2c3.jpeg)
thanks before

**Comment by Tpojka** [comment]
Probably because of Benchmark class. Try with 
`$route['404_override'] = 'error/index';`

**Comment by narfbg** [comment]
[Error](https://secure.php.net/error) is part of PHP itself, you can't use that class name.
