### ISSUE TITLE
Possible error in session handler return value conventions

### ISSUE THREAD

**Issue by hq9000** [bcit-ci/CodeIgniter#5393]
By the following commit, the new logic of what session handler returns was introduced

https://github.com/bcit-ci/CodeIgniter/commit/af849696d43f5c3b68962af1ae5096151a6d9f1a

`	

public function __construct(&$params)
	{
		$this->_config =& $params;

		if (is_php('7'))
		{
			$this->_success = TRUE;
			$this->_failure = FALSE;
		}
		else
		{
			$this->_success = 0;
			$this->_failure = -1;
		}
	}

`

we're using PHP 5.6.31 with redis driver. After we've upgraded the CI from an older version we've started to get this kind of errors on seemingly random pageviews:

2 Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (tcp://127.0.0.1:123456?auth=xxxxx)

after some experiments, we've found that the problem disappears if we change that function like this

`	
    public function __construct(&$params)
	{
		$this->_config =& $params;

			$this->_success = TRUE;
			$this->_failure = FALSE;
	
	}
`

we believe there's a bug here to be fixed.

**Comment by narfbg** [comment]
No, the problem doesn't disappear when you do that, *only the error message disappears* - that's not the same thing.

This is not a bug. The entire point of that commit is that you get notified when such errors occur.
