### ISSUE TITLE
[Request] add ; and new line to get_compiled_insert()

### ISSUE THREAD

**Issue by plonknimbuzz** [bcit-ci/CodeIgniter#5396]
for several days i try to migrate my old db to new db.
i build them using `get_compiled_insert()`

ex: 
```php
$name = strtolower(trim($row->name)); //example process
$sql=  $this->db->set(['id'=>1, 'name'=>$name])->get_compiled_insert('table');
echo $sql; //actually i use file_put_contents FILE_APPEND
```
result:
`INSERT INTO "table" ("id", "name") VALUES ('1', 'john')`
because i want to dump all of them, so i change to:
```php
...snip..
echo $sql.';'.PHP_EOL;
```
may i pull request this code? 
maybe we can give 3rd parameter to get_compiled_insert(), get_compiled_update(), get_compiled_select(), and get_compiled_delete() 

like:
`get_compiled_insert($tblname, $resetORnot, $appendNewLineOrNot);`

**Comment by narfbg** [comment]
No, sorry.
