### ISSUE TITLE
passing form_validation() errors with redirect() to any view | and include methods for post only by using [ HTTP verbs in routes ] and Resource route

### ISSUE THREAD

**Issue by pixieaka** [bcit-ci/CodeIgniter#5401]
For example if your URL is
[ site.com/form ]
and you make route for database work for example
[ site.com/form/submit ]
if i use here

`if ($this->form_validation->run()) { echo 'added successfully' } else { $this->index(); }`
here the trick if you get validation wrong 2 times or more and after this get validation right your location now is [ site.com/form/submit ] and when you use back or forward buttons in your browser after this actually you 'll get error {{{ Confirm Form Resubmission }}} with ' ERR_CACHE_MISS '

first we can make redirect() parameter to include all data from previous route.

second we can make it very easy by use route:resource() for basic [ show / add / edit / delete / edit ( post ) delete ( post ) ] so it's fun actually

edit ( post ) route when fail or success redirect to edit route
delete ( post ) route when fail or success redirect to delete route

but with validation errors or successful massage

Notes :: its can be more secure to do $route['products']['put'] and protect the URL is more easy than check is post or not inside the method ... it just my opinion to make it easy

**Comment by narfbg** [comment]
I don't exactly understand what you're trying to say, but I know it's a can of worms.
