### ISSUE TITLE
error ci_sessions codeigniter 3 ubuntu 16.04

### ISSUE THREAD

**Issue by xaiborweb** [bcit-ci/CodeIgniter#5402]
error creates 10 session in table ci_sessions every 1 second with the same ip_address of vps ubuntu 16.04, but the same script in localhost xampp windows works perfectly just creates a session as it should be.

I attach my configuration:

application/config/config.php
$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 720000000;
$config['sess_save_path'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300000;
$config['sess_regenerate_destroy'] = FALSE;

application/config/autoload.php
`$autoload['libraries'] = array('ion_auth','session');`

table ci_sessions
CREATE TABLE `ci_sessions` (
 `id` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
 `ip_address` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
 `timestamp` int(10) unsigned NOT NULL DEFAULT '0',
 `data` blob NOT NULL,
 KEY `ci_sessions_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

please help.

**Comment by narfbg** [comment]
This is a bug tracker. Please post on our [forums](https://forum.codeigniter.com/) instead.
