### ISSUE TITLE
Failed Session Memcached Driver On Read

### ISSUE THREAD

**Issue by erwinsetiawan** [bcit-ci/CodeIgniter#5404]
I always get this warning when I use memcached driver for session.

Severity: Warning
Message: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (localhost:11211)
File Path: Unknown
Line: 0

I'm using PHP 5.6.14 and memcached ext 2.2.0

I do debug and refer to https://github.com/bcit-ci/CodeIgniter/issues/3919
and notice my apps call $this->_fail() on read function line 173

and when I call $this->_memcached->getResultCode() its return 0 or 12

here is my debug code before calling $this->_fail() on line 173

var_dump($this->_memcached);
var_dump($this->_memcached->getResultCode());
var_dump($this->_get_lock($session_id));
exit;
return $this->_fail(); --> line 173

And it returns:
object(Memcached)#83 (0) { } int(0) bool(true)
object(Memcached)#83 (0) { } int(12) bool(false)
object(Memcached)#83 (0) { } int(0) bool(true)

Sometimes unable to get lock and sometimes the memcache object isset but getResultCode 0.

Please advice, I always get this warning error after upgrade CI 2 to CI 3. Just let me know is it bug or fault with my code. Forgive me if there is just error in my code.

Thank You

**Comment by narfbg** [comment]
This doesn't make any sense ... The notice says it failed on **write**, yet you say it fails on line 173 (I assume of Session_memcached_driver.php), which is **read** - that's not possible. Especially with result codes 0 and 12 (`RES_SUCCESS` and `RES_DATA_EXISTS` respectively) - these show that there was no error.

#5382 may be related, that's the only thing I can say.
