### ISSUE TITLE
Not working properly with Certbot (Let's encrypt)

### ISSUE THREAD

**Issue by hmoazzem** [bcit-ci/CodeIgniter#5410]
CodeIgniter default template does not load properly SSL (https) version of the site when encrypted with [Let's encrypt](https://letsencrypt.org/) using [Certbot](https://certbot.eff.org/). The https site is static whereas non-SSL default site more dynamic/responsive. I am running LAMP on Debian 8 and PHP5.6; I installed Certbot following instructions found on:

[https://certbot.eff.org/#debianjessie-apache](https://certbot.eff.org/#debianjessie-apache)

What am I missing?

**Comment by narfbg** [comment]
There's no such thing as "CodeIgniter default template" ... Please explain in detail what you mean.

**Comment by hmoazzem** [comment]
Changing `base_url` variable to https://domainname solved the problem.
