### ISSUE TITLE
How to handle DECLARE and SET in MS SQL query with ODBC driver?

### ISSUE THREAD

**Issue by 90zlaya** [bcit-ci/CodeIgniter#5413]
This is more of a question than it is an issue. I tried to search for an proper answer and this is my last resort.

If we have query like this:

`$return = '';
        
        $query = "
            DECLARE @number int
            DECLARE @name varchar(10)

            SET @number = 1000
            SET @name = 'nothing'
            
            SELECT @number AS one_thousand, @name AS nothing
        ";
        $result = $this->mssql_connect->query($query);
        $sql = $result->result_array();
        foreach ($sql as $row)
        {
            $return .= $row['one_thousand'];
            $return .= ' ';
            $return .= $row['nothing'];
            $return .= '<br/>';
        }
        
        return $return;`

Following error occurs: 

> odbc_fetch_array(): No tuples available at this result index

Do I have special methods for ODBC type queries? My current fix for this problem is to split query string and insert PHP variable, which is ugly and requires a lot of work in form of redefinition of existing queries.

**Comment by narfbg** [comment]
Please ask your questions on our [forums](https://forum.codeigniter.com/). This is a bug tracker.

**Comment by 90zlaya** [comment]
Oh, silly me. Thanks for help and sorry for bothering. Cheers!
