### ISSUE TITLE
input->get_request_header returns string NULL

### ISSUE THREAD

**Issue by Firzenizer** [bcit-ci/CodeIgniter#5414]
I have been troubled by weird case of get_request_header returning string NULL when request is sent by php curl.

Here is example code, which runs on Local Vagrant machine1 (PHP 7.0):
```
try {
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, 'http://url-to-machine2.test/myController/myMethod');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10);
	curl_setopt($ch, CURLOPT_FAILONERROR, true);
	curl_setopt($ch, CURLOPT_USERAGENT, 'Machine1');

	$data = curl_exec($ch);
	if (curl_error($ch) !== "") {
		echo 'CURL error: ' . curl_error($ch) . '<br>' . PHP_EOL;
		return;
	}
	curl_close($ch);
} catch (Exception $e) {
	var_dump($e);
}
var_dump($data);
```

On machine2 I have CI running with REST_Controller (PHP 7.1) and in the controller I am simply dumping the authorization value:
```
class MyController extends REST_Controller {

	public function __construct() {
		parent::__construct();
		$token = $this->input->get_request_header('authorization', TRUE);
		var_dump($token);
        }
}
```

Case 1 called from browser URL field http://url-to-machine2.test/myController/myMethod:
var_dump($token) returns null as expected, because authorization is not set.

Case 2 called from Postman same url. Authorization url is added:
Prints the token.

Case 3 called from machine1 using php curl using code above (authorization header is not set):
var_dump prints:
string(5) "NULL
"
Somehow it returns string NULL with whitespace.

Case 4 called from machine1 using php curl using code above (authorization header is set):
Everything works fine just like in case 2.

What could possibly be the problem with case 3?

**Comment by MIqbalFadillah** [comment]
Sorry sir, I have some problem same with you 
input->get_request_header returns string NULL
how you fix it?
