### ISSUE TITLE
Can't use DELETE and WHERE IN together

### ISSUE THREAD

**Issue by kylefarris** [bcit-ci/CodeIgniter#5415]
When using QueryBuilder, one would think the following query would work:

```php
$ids = array(1,2,3);
$this->db->where_in('id', $ids)->delete('things')
```

Unfortunately, I'm getting the following error: 
`Deletes are not allowed unless they contain a "where" or "like" clause."`

Presumably the SQL output would be:

```sql
DELETE FROM [things] WHERE [id] in (1,2,3);
```
I'm fairly certain this is compliant SQL across the board but I could be wrong... Since there's no `delete_batch` method either, I could always just loop over the `$ids` array and call the delete method `n` times, but, that could be really inefficient for large sets. I guess I could compile the code manually and call `query` but that kinda defeats the purpose of QB.

Any ideas? I took a look at the code and it seems like `where_in` works a little differently than `where` in terms of where (no pun intended) it stores the values before compilation.

I'd be willing to put the work into a PR if you (@narfbg) would realistically consider pulling it in.

Thanks!

**Comment by narfbg** [comment]
Sure, go for a PR.

I can't promise a merge, but that's mostly because the QB code is quite complex and easy to break, so any PR that changes it must be very, very precise.

**Comment by michalsn** [comment]
Am I missing something here? 
```php
$this->db->where_in('id',  [2, 3])->delete('things');
echo $this->db->last_query();
```
Running the code above already gives us the result as expected:
```sql
DELETE FROM `things` WHERE `id` IN(2, 3)
```

**Comment by kylefarris** [comment]
@michalsn What version of CI are you running? I'm getting this in v3.1.6.

**Comment by kylefarris** [comment]
@michalsn I just checked the same code in both v3.1.6 and v3.1.7 and v3.1.7 definitely fixes the issue from the looks of it. So, it looks like I posted an issue that's already been resolved. 

Is there a changelog or anything that specifies the other changes made from v3.1.6 to v3.1.7? We're using CI on well over a dozen apps on our intranet and I just want to make sure nothing breaks with the upgrade. The patch-level version change would indicate that I should be good, but, just want to make sure.

**Comment by michalsn** [comment]
@kylefarris v3.1.7 but AFAIK it was "always" working.

I just searched thru some of my ancient projects and digged one that use CI 2.2.6.

So, even Active Record was handling it just fine.

**Comment by kylefarris** [comment]
@michalsn Yeah, its strange because I've never come across this issue before. Then again... I don't often do a `DELETE foo WHERE IN (...)` type query in an app. Anyways, thanks for the help. I'm going to try 3.1.7 and see if that resolves it for me. I'd already resorted to manually writing out the query and running it that way (deadlines..) so I'll have to revert that code to test it.

**Comment by kylefarris** [comment]
Also, nevermind on the changelog... found it: https://codeigniter.com/user_guide/changelog.html

**Comment by narfbg** [comment]
Since `where_in()` is handled a bit differently than regular WHEREs, I took your word for it and assumed there might be a bug ... shouldn't have.

After a quick test, 3.1.6 does too produce the correct SQL; there haven't been any related changes in 3.1.7, and I don't even remember when was the last time something related was changed. Something was deffinately wrong on your end.
