### ISSUE TITLE
Session warning on PHP 7.2, when concurrency loaded 

### ISSUE THREAD

**Issue by erwinsetiawan** [bcit-ci/CodeIgniter#5417]
It always show

Severity: Warning
Message: session_start(): Failed to read session data: user (path: ......
File Path: system/libraries/Session/Session.php
Line: 143

which is session_start();

I think it should be change to 

		$sid = session_id();
		session_write_close();
		session_id($sid);
		session_start();

to make it compatible in concurrency load session.
Is it?

**Comment by narfbg** [comment]
No word if this was something on your end?

**Comment by erwinsetiawan** [comment]
I just notice if i accidentally load cart library and then I know if cart library using ci_session. 
I have manually native session thats why it keep produce error warning failed on write, etc. 

I also found that ci_session not working on Load Balancing, in this case I'm using ELB, and my session is memcached. I change on ci config for using memcached driver for session and give correct save path. But Ci session keep reproduce ci_session cookie and it will make session doesn't persist issue on ELB. Sometimes it randomly force to log out and login again.

It would be great if codeigniter session not keep using cookie on non files driver since we have option using memcached or redis.

I my case i prefer to choose using native php session for working on AWS ELB. Hope this have solution for next CI development.
