### ISSUE TITLE
Create cache folder.

### ISSUE THREAD

**Issue by MikeSouto** [bcit-ci/CodeIgniter#5418]
Hi,
I don't know if this is a issue, but when i active web page caching with "$this->output->cache($n)" this don't create cache folder if not exists. 

Error log:
"ERROR - 2018-02-21 13:00:41 --> Unable to write cache file: /var/www/myproject/writeable/cache/"

**Comment by narfbg** [comment]
No it's not. We never auto-create things that should already exist.
