### ISSUE TITLE
Form helper: use <button> instead of <input> in form_submit, or make it possible to choose between the two

### ISSUE THREAD

**Issue by beerwin** [bcit-ci/CodeIgniter#5419]
Currently, form_submit generates a code with `<input type="submit"...`.
It would be desirable if this could generate code with `<button type="submit" ...>Button title</button>` for  styling purposes. Many of us prefer `<button>` instead of `<input>`, while we would like to use the form helper.

**Comment by narfbg** [comment]
As in [form_button()](https://github.com/bcit-ci/CodeIgniter/blob/3.1.7/system/helpers/form_helper.php#L572)?
