### ISSUE TITLE
xss_clean() should deal with "`", acute accent character.

### ISSUE THREAD

**Issue by WillyYeh** [bcit-ci/CodeIgniter#5420]
These two line are equivalent:
```javascript
eval("Vulnerable")
eval`Vulnerable`
```
or
```javascript
confirm("Vulnerable")
confirm`Vulnerable`
```
Solution
File: system/core/Security.php
Line: 540
Change 
```javascript
(alert|prompt|confirm|cmd|passthru|eval|exec|expression|system|fopen|fsockopen|file|file_get_contents|readfile|unlink)(\s*)\((.*?)\)#si',
```
to
```javascript
(alert|prompt|confirm|cmd|passthru|eval|exec|expression|system|fopen|fsockopen|file|file_get_contents|readfile|unlink)(\s*)[\(`](.*?)[\)`]#si',
```

**Comment by narfbg** [comment]
And I thought I wouldn't find another reason to hate JavaScript ...

Is this part of the language, or just one browser does it?

**Comment by kylefarris** [comment]
@narfbg This is a new feature of javascript called `template literals` (specifically what you're seeing here is what's called `tag functions`)... Its supported by all browsers with the exception IE (shocker).

**Comment by narfbg** [comment]
@kylefarris Thanks for the clarification.

I want to get #5431 too and will then release.

**Comment by narfbg** [comment]
But on another, serious note: please don't post security-sensitive stuff here.

We have a security@ email and a H1 page, both linked in the readme file.
