### ISSUE TITLE
Do not working modify_column() function appropriately for PostresSQL

### ISSUE THREAD

**Issue by AndriySvirin** [bcit-ci/CodeIgniter#5421]
Please modify file ```/vendor/codeigniter/framework/system/database/drivers/postgre/postgre_forge.php``` line 131:
From: ```if (isset($field[$i]['null']))``` => ```if ( ! empty($field[$i]['null']))```
Because it disable this function works correctly.
Thanks.

**Comment by narfbg** [comment]
Explain what do you mean by "correctly".
How does it work now and how do you expect it to work?

**Comment by AndriySvirin** [comment]
Now it out of work. Because codeigniter render empty values for all keys, so it always triggering condition ```if (isset($field[$i]['null']))```. It is unnormall to check that is always exists. But if you look inside code you can see that all keys before are checking on  ```if ( ! empty($field[$i]['null']))``` except this. Also would be good to change do for function ```modify_column()``` it expecting string but in documentation it always array.

**Comment by narfbg** [comment]
You're writing in a very incoherent way and not even attempting to answer my questions.

**Comment by AndriySvirin** [comment]
Did you saw ```/vendor/codeigniter/framework/system/database/drivers/postgre/postgre_forge.php`` line 131 ? Codeigniter 3 last edition?

**Comment by narfbg** [comment]
I did, saw nothing strange.

**Comment by AndriySvirin** [comment]
Okay, then never mind. Lets keep this code part as it is. May be my mistake.
