### ISSUE TITLE
problem with codeigniter and cloudflare sessions

### ISSUE THREAD

**Issue by xaiborweb** [bcit-ci/CodeIgniter#5422]
my config.php
```
$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 86400; //7200
$config['sess_save_path'] = 'ci_session';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = TRUE;
```
my ci_session table
```
CREATE TABLE `ci_session` (
 `id` varchar(128) NOT NULL,
 `ip_address` varchar(45) NOT NULL,
 `timestamp` int(10) unsigned NOT NULL DEFAULT '0',
 `data` blob NOT NULL,
 PRIMARY KEY (`id`),
 KEY `ci_sessions_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```
when disable cloudflare creates a session for each user and is updated normally but when active cloudflare creates multiple sessions on a page in development without traffic that makes me assume that there is a problem with cloudflarte that causes you to create many sessions for every second.

image of the records that you create in the database
https://i.gyazo.com/54a49495a5575b3c9a61937cc3e6cfb9.png

Most sessions are created with this only
`__ci_last_regenerate|i:1519607099;`

and all the sessions are created with the ip of the server please help with the error of cloudflare and the sessions that it creates.

**Comment by narfbg** [comment]
Please post on our [forums](https://forum.codeigniter.com/) instead, this is a bug tracker.
