### ISSUE TITLE
Incorrect version detection with PostgreSQL 10.2

### ISSUE THREAD

**Issue by BARNZ** [bcit-ci/CodeIgniter#5423]
**Version: CodeIgniter 3.1.7**
**PHP Version: 7.2**
**Platform: Ubuntu 16**
**Affected file: `system\database\drivers\postgre\postgre_driver.php`**
**What happens: `insert_id()` always returns `NULL`**

When using the postgre driver under linux with postgres 10.2 the `insert_id` function always returns `NULL`.

The function reads the `server` key from `pg_version` expecting some form of numeric value. However under the above case we end up with the string `10.2 (Ubuntu 10.2-1.pgdg16.04+1)` which causes the first `if` block to fail resulting in the wrong method being used to get the last insert id. On windows the version number is correctly `10.2` as expected

    if ($table === NULL && $v >= '8.1')
    {
        $sql = 'SELECT LASTVAL() AS ins_id';
    }
    
`'10.2 (Ubuntu 10.2-1.pgdg16.04+1)' > '8.1'`
`false`

**Comment by BARNZ** [comment]
An alternative to `pg_version` could be to use `SHOW server_version_num` or `SELECT current_setting('server_version_num')`

which gives a numeric version number (since Postgres 8.2) in the following format:

**Postgres 10.2**
`100002`

**Postgres 9.6.1**
`90601`

This article had some good info:
https://blog.2ndquadrant.com/finding-postgresql-version/

**Comment by narfbg** [comment]
I've accidentally skipped the `#` character while committing and the patch didn't get linked. It's here: 2f1fc71c61ee9c781949d525f27fa1d5f11b9a95
