### ISSUE TITLE
can't combine or_like , where mix

### ISSUE THREAD

**Issue by aloha1003** [bcit-ci/CodeIgniter#5424]
I call orm 
$this->db->where('source_ip', $search['source_ip'])
    			 ->or_like('member_id', $search['member_id']);
but  it will got sql like  
`WHERE `source_ip` =  'source_ip'
AND  `member_id`  LIKE '%member_id%'`

I  want sql like 
``WHERE `source_ip` =  'source_ip'
OR  `member_id`  LIKE '%member_id%'`

How can I do

**Comment by narfbg** [comment]
Can't reproduce.

Also, CI doesn't have an ORM.
