### ISSUE TITLE
required filter in form validation is not working properly

### ISSUE THREAD

**Issue by harishdurga** [bcit-ci/CodeIgniter#5426]
Form validation is throwing "field is required" error even when there is valid value in the POST for the field. In the previous versions of CI I didn't get any issue with Form validation but now When I apply "required", I am getting error.

```
$rules = array(
			array(
				'field' => 'phase', 
				'label' => "Phase", 
				'rules' => 'trim|required|max_length[60]|callback_unique_phase'
			)
		);
```

**Comment by narfbg** [comment]
Can't reproduce.
