### ISSUE TITLE
Form Validation INTL_IDNA_VARIANT_UTS46 error on cPanel based servers

### ISSUE THREAD

**Issue by ariellim** [bcit-ci/CodeIgniter#5430]
Using CodeIgniter 3.1.7

Line 1234 of /system/libraries/Form_validation.php has a code that checks for INTL_IDNA_VARIANT_UTS46

$domain = is_php('5.4')
				? idn_to_ascii($matches[2], 0, INTL_IDNA_VARIANT_UTS46)
				: idn_to_ascii($matches[2]);

INTL_IDNA_VARIANT_UTS46 is not supported on latest cPanel and the server throws PHP error

This is the error.

A PHP Error was encountered
Severity: Notice

Message: Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46'

Filename: libraries/Form_validation.php

Line Number: 1236

**Comment by narfbg** [comment]
Unlikely to have anything to do with cPanel.

But regardless, this is already fixed. See #5300 and the forum thread linked at the end of it.
