### ISSUE TITLE
CodeIgniter deployment on heroku not working

### ISSUE THREAD

**Issue by chandan315** [bcit-ci/CodeIgniter#5432]
Counting objects: 471, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (466/466), done.
Writing objects: 100% (471/471), 1.50 MiB | 264.00 KiB/s, done.
Total 471 (delta 269), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> PHP app detected
remote:
remote:  !     ERROR: Your 'composer.json' lists dependencies inside 'require',
remote:        but no 'composer.lock' was found. Please run 'composer update' to
remote:        re-generate 'composer.lock' if necessary, and commit it into your
remote:        repository. For more information, please refer to the docs at
remote:        https://devcenter.heroku.com/articles/php-support#activation
remote:
remote:  !     Push rejected, failed to compile PHP app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to blooming-lake-48769.
remote:
To https://git.heroku.com/blooming-lake-48769.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/blooming-lake-48769.git'

I am having a hard time in deploying my app
I have tried doing composer update 
git add . 
git commit -m "new codeigniter project" 
heroku create 
git push heroku master
But I get the error over and over. I cant seem to understand what is wrong

**Comment by chandan315** [comment]
Finally got it fixed.
I had to add the composer.lock file
And that did the trick
Now my app is running
Thanks

**Comment by jim-parry** [comment]
This sounds like something that would be good to explain in a post on our forum, for others who encounter the same problem!

**Comment by narfbg** [comment]
And just as important: the [forums](https://forum.codeigniter.com/) are *the* place for requesting help. This here is a bug tracker.

**Comment by Paulo2991** [comment]
Pessoal preciso de ajuda por favor
