### ISSUE TITLE
Redis session driver returning false in loop

### ISSUE THREAD

**Issue by Kwozzie** [bcit-ci/CodeIgniter#5433]
Looking at system/libraries/Session/drivers/Session_redis_driver.php, it seems that it should be `continue`ing instead of `return FALSE`.

If redis->set is unable to set/write the value (with nx argument) then it is possible that another process is saving to that same lock key at the same time, therefore, it would be valid to continue (and try again) instead of returning false.

```
		do
		{
			if (($ttl = $this->_redis->ttl($lock_key)) > 0)
			{
				sleep(1);
				continue;
			}

			$result = ($ttl === -2)
				? $this->_redis->set($lock_key, time(), array('nx', 'ex' => 300))
				: $this->_redis->setex($lock_key, 300, time());

			if ( ! $result)
			{
				log_message('error', 'Session: Error while trying to obtain lock for '.$this->_key_prefix.$session_id);
				// return FALSE;
				continue;
			}

			$this->_lock_key = $lock_key;
			break;
		}
```

**Comment by narfbg** [comment]
Is it really possible (I'm not aware of that) and can we check if that is so?

**Comment by Kwozzie** [comment]
yes, unfortunately, hence the issue :( and the log message on that line is very indicative of the problem being faced.

The architecture of the app I'm working on leads to this and this one line change resolves the problem for us (until I can get the architecture improved). 

What would be the worse case scenario for letting it retry if it can't get a lock?

**Comment by Kwozzie** [comment]
Ok, so this is looking more like an issue of not having enough resources in my local development environment. Running out of memory and cpu in vagrant box and the host doesn't have anything left to allocate from :(. 

Closing issue as I can't replicate in our development environment.
