### ISSUE TITLE
problem with set_radio function

### ISSUE THREAD

**Issue by dcr2018** [bcit-ci/CodeIgniter#5436]
Hi, this is a problem that appears in CI 3. When I fill and submit a form, and the validation fails, the form is repopulated properly with set_value, set_select and set_radio functions. But when I'm filling the form programatically set_radio fails. Let me explain myself by telling you what happens in my application.

Suppose I have an "update person's data" link in my application. When the user opens the link he receives a form with a list of people to choose from. His option is sent through POST, and then he gets a second form populated with person's data. In this form all the fields are populated properly, except the radio fields. This happens only if I'm coming from a POST request. If I change the application so the first form uses GET method, it works fine. 

I'm attaching two files showing the first and the second form.
![screen 1](https://user-images.githubusercontent.com/37335617/37347672-23363adc-26b1-11e8-908b-f821b580d7b9.png)
![screen 2](https://user-images.githubusercontent.com/37335617/37347673-235c8818-26b1-11e8-98a8-e30fd476934a.png)

**Comment by narfbg** [comment]
Sorry, but this is very unclear. And we're talking about code, so screenshots are useless ... You need to clarify with a short code example.

**Comment by dcr2018** [comment]
Ok, I made a short code example. The example is about adding and editing data about a person. There is a controller, Person, and three views. The first view is insert_form.php, where the user is able to add data into the database. The second view, list_records.php, shows a list of people and the user choose a person to edit it's data. After that, he gets the third view, update_form, where the user gets a form populated with the person's data he choose. Here the user is able to make changes to a person.

For the update form, I'm using set_value and set_radio with the DEFAULT parameter to show the form populated with data. The function set_radio is not working.
[set_radio-5436.zip](https://github.com/bcit-ci/CodeIgniter/files/1822205/set_radio-5436.zip)

**Comment by narfbg** [comment]
A short example doesn't need 3 views, lenghty explanations or be zipped ... This is a short example:

    $_SERVER['REQUEST_METHOD'] = 'POST';
    $_POST['field'] = 'value';

    // Return expected: ' checked="checked"'
    // Return actual: ''
    set_radio('field', 'value');

**Comment by davidgv88** [comment]
Your file update_form.php is incorrect.

Add form_close() and use form_radio() helper and works!

```
<?php
echo validation_errors();
echo form_open('person/event_update_person');
?>
<input type="hidden" name="personId" value="<?= $person[0]->id?>">
<div><label style="display: inline-block;width: 120px;">Name</label>
<input type="text" name="name" value="<?= set_value('name', $person[0]->name);?>"></div>
<div><br><label style="display: inline-block;width: 120px;">Size</label>
	<?php echo form_radio('size','s',$person[0]->size == 's'); ?> S&nbsp;&nbsp;
	<?php echo form_radio('size','m',$person[0]->size == 'm'); ?> M&nbsp;&nbsp;
	<?php echo form_radio('size','l',$person[0]->size == 'l'); ?> L&nbsp;&nbsp;
</div>
<br><input type="submit" value="Save">
<?php echo form_close(); ?>
```

**Comment by davidgv88** [comment]
@narfbg fixed
