### ISSUE TITLE
PHPExcel broken link

### ISSUE THREAD

**Issue by portapipe** [bcit-ci/CodeIgniter#5438]
The "updated guide" link [here](https://github.com/bcit-ci/CodeIgniter/wiki/PHPExcel) is broken.

Bye :)

**Comment by jim-parry** [comment]
That is in the wiki, which is community-maintained. Not a CodeIgniter bug.

**Comment by narfbg** [comment]
The entire point of a wiki is that you can change it yourself.

Anybody can write in there; there's no "wiki issues" section because that's like a "comments issues" section.
