### ISSUE TITLE
Sessions not saving with CI 3.1.7

### ISSUE THREAD

**Issue by rkorebrits** [bcit-ci/CodeIgniter#5439]
I'm busy upgrading from 3.0.4 to 3.1.7 and having issues with `session`. I've tested this on PHP 7.0 and PHP 7.2

I've seen a few other issues here regarding session on PHP 7.x with late versions of CI, but not any with resolution it seems.

When I run this:

        $this->session->set_userdata('test', 'test');
        print ($this->session->userdata('test'));

it prints "test" just fine. Then when I remove the `set_userdata` and reload the page, it's empty.

Either sessions aren't being stored, or they are being cleared. What could this be?

Additionally; When I delete all session files and reload the page, 6 files are loaded into the sessions folder. When I reload, another 5 get added. Surely there should only be 1 session per session..

**Comment by narfbg** [comment]
You haven't seen resolutions because none of what you've seen are bugs and this is a bug tracker. Despite our efforts, people continue to come here with any problem that they can't figure out.

Please post on our [forums](https://forum.codeigniter.com/) instead.
