### ISSUE TITLE
Bug in Codigniter Email library when using SMTP with smtp.office365.com as host

### ISSUE THREAD

**Issue by o-kamalGit** [bcit-ci/CodeIgniter#5440]
Hello,

I think there is a bug in the Codigniter Email library when using SMTP with **smtp.office365.com as host**.
When I send a simple HTML message whitout using SMTP the email I get is displaying well like below (see code and capture).

```
<?php 
$this->load->library('email');
$body = "<p><b>This is a test email.</b></p><p>This is my email me@me.com</p><p>This is a link <a href='https://xxxxxx.uslogistics.com/images/logo_big.png'>https://xxxxxx.uslogistics.com/images/logo_big.png</a><p>";
$config['mailtype'] = 'html';
$config['charset'] = 'iso-8859-1';
$config['wordwrap'] = TRUE;
$config['newline'] = "\r\n";
$this->email->clear(TRUE);
$this->email->initialize($config);
$this->email->from("no-reply@domain.com", "No Replay");
$this->email->to("myownemail@hotmail.fr");
$this->email->subject("Test");
$this->email->message($body);
$this->email->send();
```
![1](https://user-images.githubusercontent.com/5834259/37553753-0b55f0e8-29c6-11e8-9478-778e3be72354.PNG)

When I use SMTP the HTML email is displaying in a weird format (see code and capture).

```
$this->load->library('email');
$body = "<p><b>This is a test email.</b></p><p>This is my email me@me.com</p><p>This is a link <a href='https://xxxxxx.uslogistics.com/images/logo_big.png'>https://xxxxxx.uslogistics.com/images/logo_big.png</a><p>";
$config['protocol'] = 'smtp';
$config['smtp_host'] = 'smtp.office365.com';
$config['smtp_user'] = ""; //Here I put the SMTP username
$config['smtp_pass'] =""; //Here I put the SMTP password
$config['smtp_port'] = '587';
$config['smtp_crypto'] = 'tls';
$config['mailtype'] = 'html';
$config['charset'] = 'iso-8859-1';
$config['wordwrap'] = TRUE;
$config['newline'] = "\r\n";
$this->email->clear(TRUE);
$this->email->initialize($config);
$this->email->from("", "No Replay");//Here I put the SMTP username as email.
$this->email->to("myownemail@hotmail.fr");
$this->email->subject("Test");
$this->email->message($body);
$this->email->send(); 
```
![2](https://user-images.githubusercontent.com/5834259/37553759-21e2a4dc-29c6-11e8-8c07-296c66711e6e.PNG)

I'm saying it is a bug because when I use PHPMailer with the same SMTP instead of the Email CI library the emails sent look fine.

This issue happens mostly with receivers email having hotmail and other private domains at the end of the email.

According to Stackoverflow (see link below) : It Looks like a bug in CI's mailer. Those = chars indicate it's using a quoted-printable transfer encoding, but if it messes up other aspects of encoding, it can leave artifacts like that. 
[https://stackoverflow.com/questions/49302947/codeignitor-email-with-smtp-is-displaying-weird-format](url)
I'm using latest version 3.1.7

Thanks.

**Comment by narfbg** [comment]
https://github.com/bcit-ci/CodeIgniter/blob/3.1.7/system/libraries/Email.php#L1514

It's either that MS Exchange bug triggering, or a bug in PHP itself.
