### ISSUE TITLE
how can I make url_title() consider permitted_uri_chars

### ISSUE THREAD

**Issue by hamsoft-uganda** [bcit-ci/CodeIgniter#5442]
I were getting error "The URI you submitted has disallowed characters." after creating my urls then I googled and got this answer [https://stackoverflow.com/questions/3934961/filter-a-string-to-remove-disallowed-characters-to-compose-an-url-in-codeigniter](https://stackoverflow.com/questions/3934961/filter-a-string-to-remove-disallowed-characters-to-compose-an-url-in-codeigniter) but from this, I realize url_title() only replaces spaces and may be converting from upper case to lower case.
How can I make this method consider also permitted characters specified in $config['permitted_uri_chars']
Thanks so much, waiting for any help.

**Comment by hamsoft-uganda** [comment]
Sorry, I were not using it well. I just realized it after dropping in my issue, though it took me over 3 days before I wrote the issue here.

**Comment by narfbg** [comment]
This is a bug tracker; even if you couldn't figure it out yourself, you still wouldn't have gotten what you need here.

When you need help with something, post on our [forums](https://forum.codeigniter.com/) instead.
