### ISSUE TITLE
Oracle (oci) protect_identifiers behavior misses table and column identifiers in functions

### ISSUE THREAD

**Issue by lancegliser** [bcit-ci/CodeIgniter#5443]
@narfbg I ran across an issue that might be a bug. Seems related to #3757 a little. At least that's what pointed me here.

Working on going using the case-sensitive methods provided, all as going well until ran into the situation when I needed to use a function on a column during comparison. Here's the lines of interest:

```php
$this->db->from('SCHEMA.USR_LIST_MV l');
$this->db->join('SCHEMA.USR_DETAILS_MV d','d.USR_EMP_NO = l.USR_EMP_NO');
$this->db->where('lower(l.USR_EMP_ID)', $id);
```

This produces the following bits (abstracted):
```sql
FROM "SCHEMA"."MDT_USR_LIST_MV"  "l"
JOIN "SCHEMA"."USR_DETAILS_MV " "d" ON "d"."USR_EMP_NO" = "l"."USR_EMP_NO"
WHERE LOWER (l.USR_EMP_ID) = 'lance'
```

Note that we don't get the identifiers protection inside the function call. It results in "l.USR_EMP_NO invalid identifier"

**Comment by narfbg** [comment]
Yes, but unfortunately we can't deal with that.

The QB code is more than complicated in its current state, and you'd probably get a headache if you go though it. I guarantee you that even if you do find a way to fix this one issue in particular, it will break something else.

P.S. Please don't start issues by addressing me personally. I happen to be the person who deals with everything by default, but this is a community-maintained project. And I get notifications for literally everything anyway, whether I'm mentioned or not.

**Comment by lancegliser** [comment]
Thanks Narf. I suppose I could manually call for protect_identifiers before I pass it through the lower() if desired.
