### ISSUE TITLE
404 url 

### ISSUE THREAD

**Issue by maenabbasi** [bcit-ci/CodeIgniter#5444]
Hello, 
_I am trying to access the following url it gives me 404 error_ 

> (The requested URL /abb/public/main/category/ÙƒÙ…Ø§Ù„ was not found on this server.)

http://localhost/abb/public/main/category/كمال
or 
http://localhost/abb/public/main/category/%D9%83%D9%85%D8%A7%D9%84 

while accessing 
http://localhost/abb/public/main/category/فتنس
http://localhost/abb/public/main/category/%D9%81%D8%AA%D9%86%D8%B3
or 
http://localhost/abb/public/main/category/ABCDEF
works fine 

what you think of possible solution or the cause of this problem 

Thank you

**Comment by jim-parry** [comment]
Support questions should be asked on our [forum](https://forum.codeigniter.com/), thanks. We use github for bug tracking.

**Comment by maenabbasi** [comment]
I believe it is a bag

**Comment by maenabbasi** [comment]
I've tried to set $config['permitted_uri_chars'] = '' and did not work

**Comment by maenabbasi** [comment]
Ok, thank you, for record in some one faced same issue, and followed this link, I've checked the .htaccess 
it was 
RewriteRule ^(.*)$ abb/index.php?/$1 [L]
and I changed it to 
RewriteRule ^(.*)$ abb/index.php?/$1 [NC,L]

and worked

**Comment by jim-parry** [comment]
:) This isn't just a CI problem ... https://wordpress.stackexchange.com/questions/277401/arabic-characters-in-url-returns-404-error
I thought there were a few posts about it on the forum already, but didn't find them with a quick search :-/
Glad your problem is sovled!
