### ISSUE TITLE
File uploading class - "client_name" bug

### ISSUE THREAD

**Issue by untamed0** [bcit-ci/CodeIgniter#5446]
The [documentation](https://www.codeigniter.com/userguide3/libraries/file_uploading.html#CI_Upload::data) for client_name says:
> File name as supplied by the client user agent, prior to any file name preparation or incrementing

However, the do_upload() function irreversibly manipulates client_name before returning it, see below:
```php
$this->file_name = $this->_prep_filename($_file['name']);
//[...]
$this->client_name = $this->file_name;
```

A simple fix would be changing it to the below, or updating the documentation.
```php
$this->client_name = $_file['name'];
```

**Comment by narfbg** [comment]
This is done for a reason and is not a bug. The documentation is what needs fixing.
