### ISSUE TITLE
Codeigniter Background Processing Library

### ISSUE THREAD

**Issue by zgmunshi** [bcit-ci/CodeIgniter#5447]
Hello Friends,

I am glad to share here background worker library that i came up with for one of my project requirement.

It is really simple but very powerful. Kindly check if it helps anyone.
https://github.com/zgmunshi/codeigniter-backgroundworker

Regards,
Zeeshan.

**Comment by jim-parry** [comment]
Thank you for sharing, but we use github for bug tracking. 
Addins should be shared through a post on our [forum](https://forum.codeigniter.com/forum-13.html)
