### ISSUE TITLE
The button of TOC in the user guide can't work

### ISSUE THREAD

**Issue by popcorner** [bcit-ci/CodeIgniter#5452]
The button in the user guide for changing the place of the TOC disappeared.
https://www.codeigniter.com/user_guide/index.html
I found out that the function it uses is toggle() in jQuery. However, this function has been deprecated and removed in jQuery 1.9. And since the user guide is using jQuery 3.x , the button can't work anymore.

**Comment by popcorner** [comment]
I create a pull request #5453 to fix that

**Comment by narfbg** [comment]
Please don't open issues only to open PRs for them. A pull request has an issue number by itself ...

@jim-parry Leaving this one for you.
