### ISSUE TITLE
Memcached Issue in 3.16

### ISSUE THREAD

**Issue by sanknm** [bcit-ci/CodeIgniter#5458]
On Google App Engine when trying to work memcache for session. i am facing issue 
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (localhost:11211)</p>
<p>Filename: Unknown</p>
<p>Line Number: 0</p>
<p>Backtrace:</p>

My Config File : 
$config['sess_driver'] = 'memcached';
	$config['sess_cookie_name'] = 'ci_session';
	$config['sess_expiration'] = 0;
	$config['sess_save_path'] = 'tcp://localhost:11211';
	$config['sess_match_ip'] = FALSE;
	$config['sess_time_to_update'] = 0;
	$config['sess_regenerate_destroy'] = FALSE;

I have updated driver latest file according to master.

**Comment by narfbg** [comment]
- We don't have a "3.16" version; "3.1.6" is not the same thing as "3.16".
- We do have proper tags; pulling master is not the correct way to update.
- This is a bug tracker and all the info you've provided amounts only to "This configuration doesn't work for me" ... That's not a bug report; please post on our [forums](https://forum.codeigniter.com/) instead.
