### ISSUE TITLE
Query Builder LIKE BEFORE doesnt work CI 3.1.8

### ISSUE THREAD

**Issue by romainrg** [bcit-ci/CodeIgniter#5462]
There is an issue with LIKE method of query builder class when 'BEFORE' parameter is passed.

**This code generates database error :**
`$this->db->select('*')->like('id', 'zefzefezf', 'BEFORE')->get('email_v2');`

**Result :**
`SELECT * FROM `email_v2` WHERE id LIKE %'zefzefezf' ESCAPE '!'`

The 'BOTH' and 'AFTER' parameter are working properly.

**Comment by romainrg** [comment]
![image](https://user-images.githubusercontent.com/14097222/38199799-54437d9c-3692-11e8-80b1-e474c83339d6.png)

**Comment by narfbg** [comment]
Please don't post screenshots of code. It really doesn't help, and it's annoying.
