### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by urko1982** [bcit-ci/CodeIgniter#5465]
In class CI_Email, if we send and email using
`
$this->email->from(from($from[, $name = ''[, $return_path = NULL]])`

parameter $name (string) – “From” display name can't be like this 

> Google, Inc.

Must change to 

> Google Inc

**Comment by narfbg** [comment]
Please elaborate.

**Comment by elminson** [comment]
The title needs to be edited and be more specific about the issue.  @urko1982

**Comment by Taalaybek** [comment]
Dont understand this issue Please can you close
