### ISSUE TITLE
session error

### ISSUE THREAD

**Issue by simon511000** [bcit-ci/CodeIgniter#5467]
Hello, I have a file **Session.php** : 
```
<?php
class Session extends CI_Controller{
    public function __construct(){
        parent::__construct();
        $this->load->library("session");
    }
    public function accueil(){
        var_dump($this->session);
    }
}
```
but I have an error : **Unable to locate the specified class: Session.php**. Why ?

**Comment by jim-parry** [comment]
Support questions should be raised on our [forum](https://forum.codeigniter.com/index.php). We use github for bug tracking. 
CodeIgniter has a Session library, and your controller name conflicts.
