### ISSUE TITLE
$this->load->model() is very very slow

### ISSUE THREAD

**Issue by bimohxh** [bcit-ci/CodeIgniter#5477]
my env is 

CodeIgniter verison is :  `3.1.8`
PHP version is : `7.2.4`

I have a  controller, I fund the  code below is where cost time:
```php
echo "time1".time()."\n";
$this->load->model($model_path, 'route');
echo "time2".time()."\n";
```
the code is waste alomt **30**s, but not error, just slow.

is the php version not compatible with CI？how can I solve this problem

**Comment by narfbg** [comment]
This is a bug tracker.

Unless you can confirm that this is a bug and identify the cause, please post this on our [forums](https://forum.codeigniter.com/) instead.

**Comment by mehzee92** [comment]
I am having the same issue with my codeigniter app using model
