### ISSUE TITLE
system/database/DB.php Syntax check error in eclipse.

### ISSUE THREAD

**Issue by wangchuangen** [bcit-ci/CodeIgniter#5478]
在eclipse中,DB.php提示错误信息"Cannot declare type CI_DB because the name is already in use",虽然我知道这是eclipse误报,但看到错误信息心里就是不爽,
我的解决办法是将第二个"class CI_DB"写入新的文件,然后在原来的语句处引用新加入的文件,

In eclipse, db.php prompts the error message "Cannot declare type CI_DB because the name is already in use", although I know that this is eclipse misinformation, but it is not good to see the error message.
My solution is to write the second "class CI_DB" to the new file, and then to reference the newly added file in the original statement,

**Comment by tianhe1986** [comment]
As you have known it is a misinformation, why not reporting it to Eclipse ?
