### ISSUE TITLE
Input.php param $masklen undefined

### ISSUE THREAD

**Issue by skiy** [bcit-ci/CodeIgniter#5480]
In line 514.
```php
sscanf($proxy_ips[$i], '%[^/]/%d', $netaddr, $masklen);
```

![selection_007](https://user-images.githubusercontent.com/3362147/39225363-858cc306-487e-11e8-95f4-2c74d98c0b72.png)

**Comment by toonitw** [comment]
`$netaddr` is undefined also. Both are *reference variables*.
http://php.net/manual/en/function.sscanf.php

**Comment by narfbg** [comment]
The `sscanf()` call defines them.

Also, please don't post screenshots of code.
