### ISSUE TITLE
is_countable conflict with PHP 7.3

### ISSUE THREAD

**Issue by DavidTurnerDotInfo** [bcit-ci/CodeIgniter#5482]
https://wiki.php.net/rfc/is-countable

PHP 7.3 includes a function called is_countable that conflicts with the function in the CI inflection_helper.php it serves a different purpose as the former checks for whether the input can be assessed by count() and the latter whether the string input is grammatically countable for countable.

Happy to help resolve this but I'm pretty new to contributing.

**Comment by narfbg** [comment]
How would you propose to resolve it?

**Comment by DavidTurnerDotInfo** [comment]
I think the only option would be to rename it in CI.   Something like is_countable_noun()

**Comment by narfbg** [comment]
Indeed, renaming is the only option. I was qurious why you cited inexperience, as you can't do this on your own anyway - there's decisions to be taken, docs to be written and updated, etc.

I'd go with `word_is_countable()` though. Sound better?

**Comment by DavidTurnerDotInfo** [comment]
Sounds fine.  More inexperience with contributing.  Thought it quite likely that a fix was already progressing but I'd not found it.

**Comment by narfbg** [comment]
@jim-parry You ok with my suggestion here? It's always going to be a BC break, there's no easy way around it.

**Comment by jim-parry** [comment]
@narfbg I am fine with that
