### ISSUE TITLE
Form Validation callbacks do not work within models.

### ISSUE THREAD

**Issue by EoghanH** [bcit-ci/CodeIgniter#5483]
```
autoload.php : 
$autoload['libraries'] = array('form_validation', 'session');
$autoload['helper'] = array('url', 'form', 'security');
```

Code in controller;

```
$this->form_validation->set_rules('custom_id', 'custom_id', array('required', 'numeric', array($this->Services_model, 'valid_custom_id')));

if ($this->form_validation->run() === false) {
            var_dump($this->form_validation->error_array());
        }
```

Code in Services_model:
```

public function valid_custom_id($custom_id) {
        $this->form_validation->set_message('valid_custom_id', 'custom_id test.');
        return false;
    }
```

This will return back with the error;

`'custom_id' => string 'Unable to access an error message corresponding to your field name custom_id.(Anonymous function)'`

If the controller is swapped over to using `callback_valid_custom_id`, and the function is moved from the model to the controller, it works as expected. Similarly, if the callback function always returns with `true`, then no error is reported - but that defeats the purpose.

According to the documentation available at https://www.codeigniter.com/userguide3/libraries/form_validation.html#callable-use-anything-as-a-rule , the above should work as expected in all cases.

**Comment by jreklund** [comment]
You need to pass along the rule name, to be able to set a message. Like the example number 3.
```php
$this->form_validation->set_rules('custom_id', 'custom_id', array('required', 'numeric', array('valid_custom_id',array($this->Services_model, 'valid_custom_id'))));
```

**Comment by EoghanH** [comment]
Thanks @jreklund - my mistake. Closing.
