### ISSUE TITLE
Function backup() in DB_utility.php not working properly when format is zip

### ISSUE THREAD

**Issue by lambasoft** [bcit-ci/CodeIgniter#5485]
I'm currently on Codeingiter 3.1.8

When I have a function that backs-up the database before creating a migration:

    private function backup_database(){
        // Load the DB utility class
        $this->load->dbutil();

        $extension = "zip";
        $filename = date('m-d-Y-h-i-s-a', time());
        $prefs = array(
            'tables'        => array(),                     // Array of tables to backup. Empty array means all
            'ignore'        => array(),                     // List of tables to omit from the backup
            'format'        => $extension,                      // gzip, zip, txt
            'filename'      => $filename,                   // File name - NEEDED ONLY WITH ZIP FILES
            'add_drop'      => TRUE,                        // Whether to add DROP TABLE statements to backup file
            'add_insert'    => TRUE,                        // Whether to add INSERT data to backup file
            'newline'       => "\n"                         // Newline character used in backup file
        );
        $filename .= "." . $extension;

        // Backup your entire database and assign it to a variable
        $backup = $this->dbutil->backup($prefs);

        // Load the file helper and write the file to your server
        $this->load->helper('file');
        $path = FCPATH . "backups" . DIRECTORY_SEPARATOR . $filename;
        $result = write_file($path, $backup);
        show_message("Backup: {$filename} created!");
    }

To my surprise, the created backups do not have strings between varchars in INSERT:
`INSERT INTO `job_position` (`JPO_ID`, `JPO_NAME`) VALUES (1, Head of Sales);`
In my database JPO_NAME is a varchar, but in the generated sql file (which is inside a zip) none of the INSERTS have quotes between it's non-numeric values.

The above insert should be like this:
`INSERT INTO `job_position` (`JPO_ID`, `JPO_NAME`) VALUES (1, 'Head of Sales');`

If I change the format to txt instead of zip, it works properly.

**Comment by narfbg** [comment]
The only difference between 'txt' and 'zip' is that the latter is processed through the Zip library; there's zero difference in escaping between the two cases.

How sure are you that you're running 3.1.8 and not 3.1.6?

**Comment by kamfu-charlie** [comment]
I having the same problem on exporting VARCHAR or TEXT the value does not include single quote in the SQL script. But not difference between 'txt' and 'zip'.

My CI version are 3.1.6

By the way to check version use 
<?php echo CI_VERSION; ?>

**Comment by narfbg** [comment]
Closing due to lack of feedback.

@kamfu-charlie There's a reason why I asked OP if he's using 3.1.6 - that version has such a bug; it's fixed in later ones. We're at 3.1.10 now and that's what you should be using before reporting bugs.

The function is located in *system/database/DB_utility.php*, but if you can't find that on your own, honestly I wouldn't expect you to be able to contribute.

**Comment by kamfu-charlie** [comment]
@narfbg  Thanks for the advice, for sure if can always update to latest version. Due to some budgeting issue, we lack of resources to fully revamp it, therefore would seek for partial replacement solution. But we have figure another solution for using latest CI.
