### ISSUE TITLE
xss_clean

### ISSUE THREAD

**Issue by mfunollet** [bcit-ci/CodeIgniter#5492]
We have and issue when apply form validation filter xss_clean.
If the post is for example: ""We are 25% Cat", after pass the filter, the return value is: "We are 25�t".
Only happend with "% c".
Why?

**Comment by maxcreate** [comment]
I've just noticed the same issue

**Comment by mfunollet** [comment]
But only happend with the letter c '% c'. With another letter works fine

**Comment by narfbg** [comment]
Duplicate of #5125.
