### ISSUE TITLE
Error when passing an empty array as binds to function db->query

### ISSUE THREAD

**Issue by etcho** [bcit-ci/CodeIgniter#5493]
I got an error when trying to pass an empty array as binds to the function query. Debugging, I found that the problem occurs if my query have and exclamation mark that it's not a bind mark. In my case it's an url.
`SELECT CONCAT('http://example.com/index.php?op=3')`

Besides that, I pass an empty array as binds (empty because I build the bind variable dinamically and the array starts as empty). So, my code is something like this:
`$sql = "SELECT CONCAT('http://example.com/index.php?op=3')";
$this->db->query($sql, array());`

Running this, I got a loop of notices in a while that never ends. It's the while at the end of function compile_binds at DB_driver.php. For some reason, the `$c` variable is zero, and the `$c--` at the begining of the code makes the while never stops.

In this cennario I have a query with no valid bind marks and an empty array as bind. This is the error case. If I pass null as binds, it works (it's the workaround that I used to solve my problem), but the bug exists.

I think that changing the do...while to while...do will work, since the verification would happen first and `$c` wouldn't be lesser than zero.

**Comment by narfbg** [comment]
Passing NULL (or not passing anything) *is* the correct way to do this.

Passing an array, empty or not, indicates that the function should look for bind markers - that's not a bug.
