### ISSUE TITLE
Issue with Codeignter3 with network calls functions

### ISSUE THREAD

**Issue by Jamalc0m** [bcit-ci/CodeIgniter#5496]
Hello,

I haver tried both functions on CI2 and CI3 and found there is an issue with CI3.
On welcome controller I have added index2 method and execute it.
public function index()
	{
		$this->load->view('welcome_message');
	}

public function index2()
 {
	  for($j=0;$j<=10;$j++){
	  echo file_get_contents("https://google.com");
	}
}
While the index2 is executing on CI3, I wasn't able to access any other function on the controller unless it finishes the execution, When I access index() as example the browser keep waiting until the execution of index2 finishes the it load the page.

I tried same to do the same thing on CI2 and it worked without any issue.

Could you please check what could be the issue.
Thanks

**Comment by gxgpet** [comment]
It looks like you're having an issue with your own project, rather than a CodeIgniter issue. For that, please post this on the [CodeIgniter forums](https://forum.codeigniter.com/).

**Comment by jim-parry** [comment]
I see this has been raised on the forum. Closing the issue.
