### ISSUE TITLE
unable to add multiple where clause in codeigniter batch_update

### ISSUE THREAD

**Issue by singhDevloper** [bcit-ci/CodeIgniter#5497]
Hi there
m trying to update multiple records with batch_update, but it shows me error 
'A Database Error Occurred
One or more rows submitted for batch updating is missing the specified index.'

help me to fix it

Below is my code

public function batchUpdate ( $table, $data, $condition )
    {
        $this->db->where ( [ 'user_id', 'product_id' ] );
        if ( $this->db->update_batch ( $table, $data, $condition ) )
        {
            return true;
        }

    }

**Comment by jim-parry** [comment]
Support questions should be raised on our [forum](https://forum.codeigniter.com/index.php). We use github for bug tracking.
