### ISSUE TITLE
Log.php has missing directory delimiter

### ISSUE THREAD

**Issue by jlpoolen** [bcit-ci/CodeIgniter#5501]
Log.php has at 187:

`$filepath = $this->_log_path.'log-'.date('Y-m-d').'.'.$this->_file_ext;`

In Linux, an application, Stikked, using this library just hangs with no error output and nothing in the Apache logs.  What allowed me to move forward was modifying the line by inserting a forward slash:

`$filepath = $this->_log_path.'/log-'.date('Y-m-d').'.'.$this->_file_ext;`

I do not know much about PHP, but if there is a directory delimiter variable, it should be placed in where I have placed the forward slash so that the delimiting takes place as desired on any operating system.

The result of the ommission of a path delimiter in Linux under an Apache system is that a request just hangs with no error output -- really really confounding.

**Comment by Paradinight** [comment]
https://github.com/bcit-ci/CodeIgniter/blob/3.1.8/system/core/Log.php#L127

**Comment by Paradinight** [comment]
You code is wrong:

https://github.com/claudehohl/Stikked/blob/master/htdocs/application/config/config.php#L204

$config['log_path'] need a path with a trailing slash...

**Comment by jlpoolen** [comment]
I agree, the code in Stikked incorrectly specifies a file rather than a directory with a trailing delimiter character.  Closing this and requesting the owner of the Stikked Code to re-open my bug from 2016.

Good sleuthing.
