### ISSUE TITLE
Support for Oracle Bind Variables

### ISSUE THREAD

**Issue by elislenio** [bcit-ci/CodeIgniter#5505]
I leave a feature request:
Support for Oracle Bind Variables is a must on repetitive querys in order to boost database performance.

To address this issue on my company we hacked the CI driver for oracle.
It would be great if CI had native support in a future version so we woud not need to hack the DB driver with every CI upgrade.

Further reading on Oracle Bind Variables:
https://blogs.oracle.com/sql/improve-sql-query-performance-by-using-bind-variables

**Comment by wpyh** [comment]
Just a suggestion: maybe you could share your company's changes here, then the maintainers might be able to develop the feature faster? Of course, you should clear that with your legal department first.

I'm a new user myself, sorry if this comment seems inappropriate.

**Comment by narfbg** [comment]
This is not a small task, and it would also have to work with other DB drivers we have ... just FYI.
