### ISSUE TITLE
set_cookie()

### ISSUE THREAD

**Issue by emad22552** [bcit-ci/CodeIgniter#5506]
hi.i think there is a bug in codeigniter3.1.8 in system/core/input.php , set_cookie function, in line 408, where i think `$prefix.$name` should be `$name` in setcookie function.

**Comment by dafriend** [comment]
You are wrong. Look carefully at where the value of $prefix comes from and you will see it will be one of the following;

1. The value passed to set_cookie
2. The config.php item 'cookie_prefix' value
3. An empty string
