### ISSUE TITLE
missing PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT

### ISSUE THREAD

**Issue by janul** [bcit-ci/CodeIgniter#5513]
file: CodeIgniter-3.1.8/system/database/drivers/pdo/subdrivers/pdo_mysql_driver.php

PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT is not set based on value in encrypt['ssl_verify']

**Comment by narfbg** [comment]
I've searched case-insensitively for "verify" and it doesn't exist in that file. Please explain what you mean.

**Comment by Xcreen** [comment]
I guess what he meant:
He want the set the ssl_verify (based on PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT), thats missing in this block:
/system/database/drivers/pdo/subdrivers/pdo_mysql_driver.php Line ~ 163
```php
$ssl = array();
empty($this->encrypt['ssl_key'])    OR $ssl[PDO::MYSQL_ATTR_SSL_KEY]    = $this->encrypt['ssl_key'];
empty($this->encrypt['ssl_cert'])   OR $ssl[PDO::MYSQL_ATTR_SSL_CERT]   = $this->encrypt['ssl_cert'];
empty($this->encrypt['ssl_ca'])     OR $ssl[PDO::MYSQL_ATTR_SSL_CA]     = $this->encrypt['ssl_ca'];
empty($this->encrypt['ssl_capath']) OR $ssl[PDO::MYSQL_ATTR_SSL_CAPATH] = $this->encrypt['ssl_capath'];
empty($this->encrypt['ssl_cipher']) OR $ssl[PDO::MYSQL_ATTR_SSL_CIPHER] = $this->encrypt['ssl_cipher'];
```

But MYSQL_ATTR_SSL_VERIFY_SERVER_CERT seems to be missing in the documentation. Check the comment from Desislav Kamenov on http://php.net/manual/de/ref.pdo-mysql.php
