### ISSUE TITLE
codeigniter special characters of the type Ã©ðŸ”¥ ðŸ”¥

### ISSUE THREAD

**Issue by spencer237** [bcit-ci/CodeIgniter#5515]
Hi all I have an encoding problem with codeigniter. When I read my database, it shows me special characters of the type Ã©ðŸ”¥ ðŸ”¥.
Can you tell me how to avoid this?

**Comment by jim-parry** [comment]
This is a question for our [forum](https://forum.codeigniter.com/index.php), thanks.
We use github for bug tracking.
