### ISSUE TITLE
log files

### ISSUE THREAD

**Issue by malohtie** [bcit-ci/CodeIgniter#5517]
i don't know if it a bug or not but my logs files jumped from log-2018-05-29.php to log-2018-05-31.php

![image](https://user-images.githubusercontent.com/20033279/40752658-084cd5b8-6460-11e8-885d-92f0ff714817.png)

**Comment by jim-parry** [comment]
That does not sound like a bug - more likely that your server wasn't accessed during "today". If "today" isn't the 31st yet in your timezone, then it is likely that your server doesn't share the same timezone settings.

**Comment by malohtie** [comment]
it not hosted in server it running on xampp and nothing wrong with my timezone settings
anyway thanks
