### ISSUE TITLE
Transaction status FALSE but DB error NULL

### ISSUE THREAD

**Issue by csotelo8885** [bcit-ci/CodeIgniter#5518]
I'd like to catch the sqlsrv(driver) db-error from a codeigniter transac with insert_batch:

```
public function sync($data)
   {
       $this->myDB->trans_start();
           $this->myDB->insert_batch('myTable', $data);
           $db_error = $this->myDB->error();
       $this->myDB->trans_complete();

       if ($this->myDB->trans_status() === FALSE)
       {        
           if (!empty($db_error['message']))
           {
               return $db_error['message'];
           }
       }
       else
           return true;
   }
}
```

The trans_status() works fine because a generated SQL "string truncated" error. The problem is, accord with the CI3 system sqlsrv driver :

```
public function error()
   {
       $error = array('code' => '00000', 'message' => '');
       $sqlsrv_errors = sqlsrv_errors(SQLSRV_ERR_ERRORS);

       if ( ! is_array($sqlsrv_errors))
       {
           return $error;
       }
...
```
So the sqlsrv_errors(SQLSRV_ERR_ERRORS) returns NULL (Error number: 00000)

But if I set the CI config/database.php to 'db_debug' => TRUE, CI show that error:

![capture](https://user-images.githubusercontent.com/8917532/40783184-4edb8faa-64a7-11e8-87ae-5c46affeed2a.JPG)

Why??, exists another way to capture the DB-error in a batch?

Thanks in advance,

**Comment by tedncm** [comment]
You can use Sql Server Profiler of SSMS to catch the INSERT statement and debug. I think this should be an error when inserting a string with exceeded length into a NVARCHAR column.

**Comment by narfbg** [comment]
Though I'm not sure if this is the cause of it here, `insert_batch()` can execute multiple queries, while `error()` only works on the last `query()` call, so it is impossible to make it always work (and an incomplete solution is no solution ...)

If at all possible to "catch" those errors, it will happen in 3.2.0 when we switch almost all error handling to exceptions.
