### ISSUE TITLE
Error Occur when I join table and gives duplicate value

### ISSUE THREAD

**Issue by prashantrijal96** [bcit-ci/CodeIgniter#5521]
I'm writing an application on CodeIgniter 3.1.6 and when I join 4 tables with the table "order", I got more than 1 output. I have only 2 rows on my table but the output in view are 6 rows, So, how can I solve this problem.

**Comment by jim-parry** [comment]
Support questions should be raised on our [forum](https://forum.codeigniter.com/index.php). We use github for bug tracking.
