### ISSUE TITLE
url problem

### ISSUE THREAD

**Issue by AlokInsan** [bcit-ci/CodeIgniter#5522]
I got an error, when i remove index.php by .htaacess file and replace from config folder $config['index_page'] = '';  also, and i am using ion auth for login purpose . I hit localhost/CI url i got Object not found message. and when i write index.php into config folder $config['index_page'] = 'index.php'; after i hit url it works fine. the url is made like this localhost/CI/index.php/auth/login.
i want to remove index.php completely from url. my codeigniter version is CI 3.1.8

so please help me any one.

**Comment by jim-parry** [comment]
Support questions should be raised on our [forum](https://forum.codeigniter.com/index.php), thanks.
We use github for bug tracking.

**Comment by AlokInsan** [comment]
Also i am using  **hmvc** in my project.
