### ISSUE TITLE
PHP syntax error in Session_memcached_driver.php

### ISSUE THREAD

**Issue by RobinMICHELAT** [bcit-ci/CodeIgniter#5526]
https://github.com/bcit-ci/CodeIgniter/blob/b3f7aae1079e8e484437bc67f4c126f34e7903d8/system/libraries/Session/drivers/Session_memcached_driver.php#L308

Syntax error generates PHP Fatal error : Call to undefined function get() in .../system/libraries/Session/drivers/Session_memcached_driver.php on line 308

Fix : 
`$this->_memcached->get($this->_key_prefix.$id);`

**Comment by narfbg** [comment]
I could swear I ran the linter on this, so I did again:

    $ php -l system/libraries/Session/drivers/Session_memcached_driver.php 
    No syntax errors detected in system/libraries/Session/drivers/Session_memcached_driver.php

After a closer look, it probably reads it as `$this->_memcached` **minus** `get($this->_key_prefix.$id)` ... I'm speechless.

**Comment by cyoon84** [comment]
when will this fix merge to the master?

**Comment by jim-parry** [comment]
@cyoon84 This has been flagged for 3.1.10, but that does not have a specific release date.

**Comment by cyoon84** [comment]
so should I downgrade to 3.1.8 for now?

**Comment by jim-parry** [comment]
@cyoon84 You could always make the change manually in your Session_memcached_driver, which would then be over-written by the next release. Not normally a recommended practice, but it seems to fit in this case.
