### ISSUE TITLE
 can not load same DB twice

### ISSUE THREAD

**Issue by acclea** [bcit-ci/CodeIgniter#5527]
when i load one DB  in MY_Controller,
$DB2 = $this->load->database('group_two', TRUE);
another in MY_Model
$DB2 = $this->load->database('group_two', TRUE);

then i can not use $DB2 in my program.

if i load once $DB2 can be able.
why?  help ,please.
thanks very much.

**Comment by narfbg** [comment]
Because where you say "load" what it actually does is "connect", and you can't duplicate a connection.

This is a bug tracker; if you need help, please post on our [forums](https://forum.codeigniter.com/) instead.
