### ISSUE TITLE
I host project on server and before login page it shows this message.

### ISSUE THREAD

**Issue by indiandevelopers** [bcit-ci/CodeIgniter#5528]
An uncaught Exception was encountered

Type: RuntimeException

Message: Unable to locate the model you have specified: Authmodel

Filename: /home/m32jqybw1zey/public_html/system/core/Loader.php

Line Number: 348

Backtrace:

File: /home/m32jqybw1zey/public_html/application/controllers/Login.php
Line: 12
Function: model

File: /home/m32jqybw1zey/public_html/index.php
Line: 315
Function: require_once

**Comment by jim-parry** [comment]
This is a support question, and should be asked on our forum. We use github for bug tracking.
Read the error message: CI cannot find application/models/Authmopdel.php
