### ISSUE TITLE
Image_lib->resize() 'quality' is ignored if original is already correct size

### ISSUE THREAD

**Issue by aderowbotham** [bcit-ci/CodeIgniter#5534]
With the CI **Image_lib**, using the `image_lib->resize()` function with GD2, I noticed that a number of user-uploaded images were very large files, even though I had set quality to '55%'. 

On investigating I discovered that the method `image_save_gd()` (which passes `$this->quality` to `@imagejpeg()`) never gets called if the target size is exactly the same as the original size.

**Example**

User uploads an original JPEG that is already 1600 x 1200 with quality 100% (a relatively large file)
    
    $config['image_library'] = 'gd2';
    $config['source_image'] = '../uploads/MY_1600x1200_FILE.jpg';
    $config['quality'] = '55%';
    $config['width'] = '1600';
    $config['height'] = '1200';
    $config['new_image'] = 'nicely-optimised-wont-eat-my-bandwidth.jpg';
    $this->image_lib->clear();
    $this->image_lib->initialize($config);
    $this->image_lib->resize();

By putting some debugging code into **Image_lib** it is apparent that `image_save_gd()` never runs. But changing the target width or height by any amount causes it to be run as expected.

**Expected behaviour**

Because the image library accepts a `quality` parameter it is expected that the resulting file (if a JPEG) is saved with that quality regardless of input.

**Comment by narfbg** [comment]
Perhaps that's what you expected, but bear in mind that the function is called "resize" and not e.g. "transform" ... It's only natural that nothing will happen if the input doesn't need resizing.

**Comment by aderowbotham** [comment]
I can't tell if that was sarcasm or not. The [documentation](https://www.codeigniter.com/userguide3/libraries/image_lib.html) says there are four available methods: `resize()`, `crop()`, `rotate()` `watermark()`. 

Are you implying I might want to access `image_process_gd()` directly? It seemed unwise as not documented (so could be removed in future), though I see it is actually a public method.

**Comment by narfbg** [comment]
No sarcarsm and not implying anything. I just don't use the image_lib and don't remember 100% of how it functions.

**Comment by aderowbotham** [comment]
OK. I'll build a workaround into my app. How it works now feels slightly unhelpful/unintuitive to me from a _user_ perspective, although I take your point about the method being called "resize". Thanks.
