### ISSUE TITLE
Bug in Session_memcached_driver.php - mising Greater-than sign

### ISSUE THREAD

**Issue by MichalSkoula** [bcit-ci/CodeIgniter#5535]
file: CodeIgniter-3.1.9/system/libraries/Session/drivers/Session_memcached_driver.php, line 308

there is:

$this->_memcached-get($this->_key_prefix.$id);

there should be:

$this->_memcached->get($this->_key_prefix.$id);

**Comment by gxgpet** [comment]
Duplicate of #5526.
