### ISSUE TITLE
SMTP Mail not sending - Codeigniter Email Library

### ISSUE THREAD

**Issue by anburocky3** [bcit-ci/CodeIgniter#5537]
I'm having issues in sending mail through SMTP Protocol (in Some VPS/Hosting). 
(Email is sending in localhost but not working on VPS)

Described the problem detailed in CodeIgniter thread.
https://forum.codeigniter.com/thread-71045.html

**Comment by jim-parry** [comment]
You are experiencing a configuration problem, not a bug in the framework.
You have already rasied a thread on the forum, which is the proper place to get help with bugs, thanks.

**Comment by anburocky3** [comment]
Thank you. Actually the script is perfect and running on some hostings. but not running on the VPS?
I think, there may be any dependency its missing. Is there any way to check out?
