### ISSUE TITLE
Bug in dbforge->modify_column() for PostgreSQL and null columns

### ISSUE THREAD

**Issue by mikifus** [bcit-ci/CodeIgniter#5542]
Maybe related to #5421

## Steps to reproduce:
1. Create a table with a nullable column and fill it with some null values.
2. Create a migration to change the name of the nullable column and run it.

Example migration up:
```
$fields = array(
        'example_field' => array(
		'name' => 'example_field_new',
		'null' => TRUE
	),
 );
$this->dbforge->modify_column('example_table', $fields);
```
## Bug
Digging in the code I found that the condition on this line is always `FALSE`:
https://github.com/bcit-ci/CodeIgniter/blob/b1769f962d74adff766666e2b3e055191bf94b63/system/database/drivers/postgre/postgre_forge.php#L134

The reason for this is that this line sets the 'null' property to a string, breaking the previous condition:
https://github.com/bcit-ci/CodeIgniter/blob/b1769f962d74adff766666e2b3e055191bf94b63/system/database/DB_forge.php#L754

This leads to a situation in column modification will trigger a `SET NOT NULL` in all cases, and it doesn't matter if the `null` attribute is set to `TRUE`. I bet this only happens in PostgreSQL because of the syntax.

## Workaround
1. Load your database in __construct()
```
$this->db = $this->load->database('default', TRUE);
```
2. Run a raw query in up() and another in down()
```
$this->db->query('ALTER TABLE "example_table" RENAME COLUMN "example_field" TO "example_field_new"');
```

**Comment by narfbg** [comment]
Can you please verify that the fix patch is working correctly?

**Comment by mikifus** [comment]
It works only in the case ```'null' => TRUE``` is specified, which simplifies the workaround.

I think it is still not ideal, as the documentation won't warn you about having to specify null even if the field was already nullable.

In my opinion this fix is good but at some point these migrations should not trigger any change regarding nullable status if the developer doesn't make it explicit.

Thanks!

**Comment by narfbg** [comment]
Ok, please stop talking about migrations and workarounds ... We have a bug in DB Forge and it has to be fixed; it doesn't matter if you use it with migrations or not, nor are we looking for a workaround.

Now, on topic - how's it only working with `'null' => TRUE` given that there's no logic for that if you don't pass 'null': https://github.com/bcit-ci/CodeIgniter/blob/b1769f962d74adff766666e2b3e055191bf94b63/system/database/DB_forge.php#L750

**Comment by mikifus** [comment]
Agreed, let's fix this.

Deeper test lead me to this check which will resolve to TRUE in all cases as per default all keys are set in the array.
https://github.com/bcit-ci/CodeIgniter/blob/e83ae5b13504a00b3e8f543f4e232dff4c90a9aa/system/database/drivers/postgre/postgre_forge.php#L131

I changed the line to this one (after applying the previous patch) and seemed to solve the issue:
```
if (isset($field[$i]['null']) && !empty($field[$i]['null']))
```
I guess this needs to be changed on the PDO subdriver too.

Can't say for sure if it works in all cases, but worked for mine.

Glad to help.

**Comment by narfbg** [comment]
Please test with my commit.

FYI, `isset()` is part of what `! empty()` does ... that's redundant.

**Comment by mikifus** [comment]
Hi,

I confirm it is working correctly. Thanks.

**Comment by narfbg** [comment]
Great. Thanks for being so cooperative; this one would've been a pain to figure out alone.
