### ISSUE TITLE
session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct

### ISSUE THREAD

**Issue by parthrockers** [bcit-ci/CodeIgniter#5543]
I have used codeingiter 3.1.9 with google app engine flexible. To store session i am using [memcache][1], [google cloud documentation][2].

I am getting bellow error:

> Severity: Warning
> Message: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (memcached-18700.c1.us-central1-2.gce.cloud.redislabs.com:18700)
> Filename: Unknown
> Line Number: 0
> Backtrace: 

application/config/config.php

    $config['sess_driver'] = 'memcached';
    $config['sess_cookie_name'] = 'ci_session';
    $config['sess_expiration'] = 7200;
    $config['sess_save_path'] =  'memcached-18700.c1.us-central1-2.gce.cloud.redislabs.com:18700';
    $config['sess_match_ip'] = FALSE;
    $config['sess_time_to_update'] = 300;
    $config['sess_regenerate_destroy'] = FALSE;

app.yaml

    runtime: php
    env: flex

    runtime_config:
        document_root: .

    env_variables:
        # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
        # values obtained when configuring your Cloud SQL instance.
        MYSQL_USER: "MYSQL_USER"
        MYSQL_PASSWORD: "MYSQL_PASSWORD"
        MYSQL_DSN: "MYSQL_DSN"
        # If you are using the App Engine Memcache service (currently in alpha),
        # uncomment this section and comment out the other Memcache variables.
        # USE_GAE_MEMCACHE: 1
        MEMCACHE_SERVER: "memcached-18700.c1.us-central1-2.gce.cloud.redislabs.com:18700"
        # If you are using a Memcached server with SASL authentiation enabled,
        # fill in these values with your username and password.
        MEMCACHE_USERNAME: "MEMCACHE_USERNAME"
        MEMCACHE_PASSWORD: "MEMCACHE_PASSWORD"

    beta_settings:
        cloud_sql_instances: "cloud_sql_instances"

  [1]: https://redislabs.com/lp/using-memcached-cloud-multiple-languages/
  [2]: https://cloud.google.com/appengine/docs/flexible/php/using-redislabs-memcache

Any idea what going wrong?

**Comment by luizzz** [comment]
well, the address memcached-18700.c1.us-central1-2.gce.cloud.redislabs.com:18700 is correct?
make sure if port 18700 is opened on the server. test the memcache server on telnet to make sure if is working.

and please... this kind of question must be made here: https://forum.codeigniter.com/index.php

**Comment by narfbg** [comment]
Indeed, this is a bug tracker and you should ask such questions on our forums.
