### ISSUE TITLE
Cursor Object Required

### ISSUE THREAD

**Issue by Atmiya735** [bcit-ci/CodeIgniter#5547]
Hello Team,
I m facing the below error while performing the aggregate operation using this lib.
"Aggregation operation failed: ***.***.**.***:27017: The 'cursor' option is required, except for aggregate with the explain argument".
Please give me the solution for this here there i m using the latest mongo db 3.6.4. So if you have any latest lib for that also please suggest me 

Thanks

**Comment by narfbg** [comment]
This is a bug tracker for CodeIgniter ... we don't even have a MongoDB library.
