### ISSUE TITLE
Codeigniter php code view

### ISSUE THREAD

**Issue by atishamte** [bcit-ci/CodeIgniter#5549]
I am developing an application using CI 3 for a client and hosted it on the server. The client is saying, he will be able to view my PHP code using some tool which is not SSH, FileZilla like FTP.
I have not shared any credentials with them either. apache is also running and content type is also not set to text/text.
Is there anyway, the person will see the PHP code directly?

**Comment by rmcdahal** [comment]
Make Screenshots and send them

**Comment by jim-parry** [comment]
We use github for bug tracking. Support questions should be asked on our [forum](https://forum.codeigniter.com/index.php), thanks.
