### ISSUE TITLE
Database name contains a period causes a syntax error

### ISSUE THREAD

**Issue by keplerg** [bcit-ci/CodeIgniter#5553]
I know this issue has been brought up before but I wanted to suggest a solution that may work for people using nonstandard characters in database names. In the config file,

``<edited-out -- @narfbg>``

------------------

Hope this helps.

**Comment by narfbg** [comment]
If you know it's been brought up before, you should also know that this is a bug tracker and not a place to post random suggestions. And we especially dislike suggestions to edit stock framework files.

**Comment by keplerg** [comment]
my apologies
