### ISSUE TITLE
I can't understand core/common.php function remove_invisible_characters()

### ISSUE THREAD

**Issue by Zhucola** [bcit-ci/CodeIgniter#5555]
$non_displayables[] = '/%0[0-8bcef]/i';	// url encoded 00-08, 11, 12, 14, 15
$non_displayables[] = '/%1[0-9a-f]/i';	// url encoded 16-31
$non_displayables[] = '/%7f/i';	// url encoded 127
$non_displayables[] = '/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]+/S';	// 00-08, 11, 12, 14-31, 127

why preg_replace those????

If I dont use this function，What's going to happen？？？？？

thanks！

**Comment by narfbg** [comment]
This is a bug tracker. Please post your questions on our [forums](https://forum.codeiginiter.com/) instead.
