### ISSUE TITLE
Getting mcrypt extension not available error

### ISSUE THREAD

**Issue by banstola** [bcit-ci/CodeIgniter#5559]
We are using the latest version of CI and php7.2 with openssl installed and I read at the documentation that 

> he Encryption Library provides two-way data encryption. To do so in a cryptographically secure way, it utilizes PHP extensions that are unfortunately not always available on all systems. You must meet one of the following dependencies in order to use this library:

But there is this check for if mcrypt_encrypt function exists or not thus producing the error

```
	if (($this->_mcrypt_exists = function_exists('mcrypt_encrypt')) === FALSE)
		{
			show_error('The Encrypt library requires the Mcrypt extension.');
		}
```

Am I missing something ?

**Comment by jim-parry** [comment]
mcrypt has been deprecated in PHP, and is not available.
This is not a CodeIgniter bug.
I suggest using openssl instead.

**Comment by banstola** [comment]
I am sorry if I was not clear but I could not find documentation regarding openssl at CI documentation page. We do have openssl installed but we still get `The Encrypt library requires the Mcrypt extension.` error . The above code code at the constructor in Encryption class has a check if mcrypt_encrypt function exist or not which is what causes the error.

**Comment by gxgpet** [comment]
The [`Encrypt`](https://www.codeigniter.com/user_guide/libraries/encrypt.html) is not the same as [`Encryption`](https://www.codeigniter.com/user_guide/libraries/encryption.html). They are two separate libraries, the first one being deprecated.

**Comment by banstola** [comment]
Thank you! I realised my mistake now!
