### ISSUE TITLE
load_class code doesn't do what comment says.

### ISSUE THREAD

**Issue by phalox** [bcit-ci/CodeIgniter#5565]
Hi CI!

I'm currently working on an app where I want to install a library (authentication lib), but also a subclass so that I have a simple abstraction of this auth lib (in case I have to switch again). Load_class seemed to work quite well in CI2, but now it doesn't. Looking at the code, I believe there's something incorrect:

From my understanding, we should never have CI_ classes in the applications folder, but this code snippet seems to say you should. Shouldn't the code be split in 2: one for the standard name in the application folder, the other for a system, with the CI_ prefix.

I've taken the idea from flexiauth for CI2. It's a bit of a shortcut (I should make an interface class, but then I have to redefine all the standard calls (like login))

```
		// Look for the class first in the local application/libraries folder
		// then in the native system/libraries folder
		foreach (array(APPPATH, BASEPATH) as $path)
		{
			if (file_exists($path.$directory.'/'.$class.'.php'))
			{
				$name = 'CI_'.$class;

				if (class_exists($name, FALSE) === FALSE)
				{
					require_once($path.$directory.'/'.$class.'.php');
				}

				break;
			}
		}
```

Current workaround: Require_once the file...

**Comment by phalox** [comment]
sidecomment: if I split that code into two functions, I still get funny behavior: The autoloader of CI_Controller seems to be also gathering files from the app/controller folder, which seems strange.
In my case (with ion auth) that's becoming a pain:
There's an Auth controller, but also an Auth lib. It seems that the Auth controller is then doing a recursive construct on itself...

**Comment by narfbg** [comment]
Looking for `CI_`-prefixed classes under *application/* is a [documented](https://www.codeigniter.com/user_guide/general/creating_libraries.html#replacing-native-libraries-with-your-versions) feature enabling you to override stock libraries.

And I don't know why you'd even expect to have 2 classes with matching names at the same time ... Regardless of their purpose, that's a name collision.
