### ISSUE TITLE
Upload with disabled detect_mime error

### ISSUE THREAD

**Issue by SimonNegrin** [bcit-ci/CodeIgniter#5567]
Hi, I have this code in my controller, with `'detect_mime' => false`
```
$this->load->library('upload', [
    'upload_path'    => 'uploads/tmp',
    'allowed_types'  => 'sql',
    'encrypt_name'   => true,
    'detect_mime'    => false
]);
```
But in the `Upload::do_upload()` method has the below call to `Upload::is_allowed_filetype()` with no argument.

```
// Is the file type allowed to be uploaded?
if ( ! $this->is_allowed_filetype())
{
	$this->set_error('upload_invalid_filetype', 'debug');
	return FALSE;
}
```
I think there is a need to pass an argument indicating if it is necessary to check the mime type.

Regards!

**Comment by narfbg** [comment]
Disabling MIME-type checks doesn't disable filename extension checks.

**Comment by OAVHomeAdmin** [comment]
Then what would disable the Filename Extension Checks?
