### ISSUE TITLE
数据库在update的时候 当where 多个条件的时候，只返回1

### ISSUE THREAD

**Issue by youfeed** [bcit-ci/CodeIgniter#5572]
数据库在update的时候 当where 多个条件的时候，只返回1
$data = array(
			'logining' => $logining,
		);
		$array = array('hashid' => $uesrname, 'password' => $password, 'daili' => $nick);
		$this->db->where($array);
		$query = $this->db->update('user', $data);
类似与这样 会触发

**Comment by jim-parry** [comment]
?? English, please.
If this is support question, ask it on our forum (also n English)
