### ISSUE TITLE
cookie_path not set correctly

### ISSUE THREAD

**Issue by janul** [bcit-ci/CodeIgniter#5573]
Hi,
There is problem with overriding $config['cookie_path'] (tested with CI 3.1.9)
file: config.php
**$config['cookie_path'] = '/uri1';**
file: config_override.php
 **$config['cookie_path'] = '/uri2';**
file: autoload.php
**$autoload['config'] = array('config_override');**

Then the csrf cookie has correct path ('/uri2') however session cookie has still '/uri1'

**Comment by narfbg** [comment]
`$autoload['config']` is there so that you can easily use config files for your own custom stuff, not for overriding the essential ones - there's environment-specific configurations for that.
