### ISSUE TITLE
please remove the suport of mysql,mssql,sqlite in the higher version

### ISSUE THREAD

**Issue by spierman** [bcit-ci/CodeIgniter#5574]
60 | ERROR | Extension 'sqlite' is removed since PHP 5.4
  72 | ERROR | Extension 'sqlite' is removed since PHP 5.4
  89 | ERROR | Extension 'sqlite' is removed since PHP 5.4

66 | ERROR | The function is_countable() is not present in PHP version 7.2 or earlier

398 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4
 400 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

odeigniter/framework/system/libraries/Encrypt.php
-------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 14 ERRORS AFFECTING 8 LINES
-------------------------------------------------------------------------------------------------------------------------------------------------------
 208 | ERROR | The constant "MCRYPT_MODE_ECB" is deprecated since PHP 7.1 and removed since PHP 7.2
 298 | ERROR | Function mcrypt_get_iv_size() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 298 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 299 | ERROR | Function mcrypt_create_iv() is deprecated since PHP 7.1 and removed since PHP 7.2; Use random_bytes() or OpenSSL instead
 299 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 299 | ERROR | The constant "MCRYPT_DEV_URANDOM" is deprecated since PHP 7.1 and removed since PHP 7.2
 300 | ERROR | Function mcrypt_encrypt() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 300 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 315 | ERROR | Function mcrypt_get_iv_size() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 315 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 325 | ERROR | Function mcrypt_decrypt() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 325 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 433 | ERROR | The constant "MCRYPT_RIJNDAEL_256" is deprecated since PHP 7.1 and removed since PHP 7.2
 450 | ERROR | The constant "MCRYPT_MODE_CBC" is deprecated since PHP 7.1 and removed since PHP 7.2

codeigniter/framework/system/libraries/Encryption.php
---------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 50 ERRORS AND 1 WARNING AFFECTING 26 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------
 164 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
 234 | ERROR   | Function mcrypt_list_algorithms() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 234 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 260 | ERROR   | Function mcrypt_enc_get_algorithms_name() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 260 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 261 | ERROR   | Function mcrypt_enc_get_modes_name() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 261 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 264 | ERROR   | Function mcrypt_module_close() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 264 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 267 | ERROR   | Function mcrypt_module_open() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 267 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 352 | ERROR   | Function mcrypt_create_iv() is deprecated since PHP 7.1 and removed since PHP 7.2; Use random_bytes() or OpenSSL instead
 352 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 352 | ERROR   | The constant "MCRYPT_DEV_URANDOM" is deprecated since PHP 7.1 and removed since PHP 7.2
 414 | ERROR   | Function mcrypt_enc_get_iv_size() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 414 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 418 | ERROR   | Function mcrypt_generic_init() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 418 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 422 | ERROR   | Function mcrypt_module_close() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 422 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 430 | ERROR   | Function mcrypt_enc_get_modes_name() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 430 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 432 | ERROR   | Function mcrypt_enc_get_block_size() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 432 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 448 | ERROR   | Function mcrypt_enc_get_modes_name() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 448 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 449 | ERROR   | Function mcrypt_generic() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 449 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 450 | ERROR   | Function mcrypt_generic() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 450 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 452 | ERROR   | Function mcrypt_generic_deinit() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 452 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 455 | ERROR   | Function mcrypt_module_close() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 455 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 573 | ERROR   | Function mcrypt_enc_get_iv_size() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 573 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 575 | ERROR   | Function mcrypt_enc_get_modes_name() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 575 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 591 | ERROR   | Function mcrypt_generic_init() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 591 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 595 | ERROR   | Function mcrypt_module_close() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 595 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 601 | ERROR   | Function mdecrypt_generic() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 603 | ERROR   | Function mcrypt_enc_get_modes_name() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 603 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 608 | ERROR   | Function mcrypt_generic_deinit() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 608 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 611 | ERROR   | Function mcrypt_module_close() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 611 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 742 | ERROR   | Function mcrypt_module_open() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
 742 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead

oasgames/vendor/codeigniter/framework/system/libraries/Image_lib.php
--------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------
 1774 | WARNING | Function dl() is deprecated since PHP 5.3

codeigniter/framework/system/libraries/Session/Session.php
--------------------------------------------------------------------------------------------------------------------------------
FOUND 4 ERRORS AND 4 WARNINGS AFFECTING 8 LINES
--------------------------------------------------------------------------------------------------------------------------------
 343 | WARNING | INI directive 'session.hash_function' is removed since PHP 7.1
 348 | ERROR   | INI directive 'session.hash_function' is removed since PHP 7.1
 355 | ERROR   | INI directive 'session.hash_function' is removed since PHP 7.1
 360 | ERROR   | INI directive 'session.hash_function' is removed since PHP 7.1
 364 | WARNING | INI directive 'session.hash_bits_per_character' is removed since PHP 7.1
 369 | WARNING | INI directive 'session.sid_bits_per_character' is not present in PHP version 7.0 or earlier
 370 | WARNING | INI directive 'session.sid_length' is not present in PHP version 7.0 or earlier
 375 | ERROR   | INI directive 'session.sid_length' is not present in PHP version 7.0 or earlier

**Comment by narfbg** [comment]
Please don't spam OSS projects with silly results from automated scanners.
