### ISSUE TITLE
drivers/Cache_redis.php Call to a member function set() on null

### ISSUE THREAD

**Issue by Hanchengluo** [bcit-ci/CodeIgniter#5577]
CI  V3.1.9
$config['host'] = '127.0.0.1';
$config['password'] = NULL;
$config['port'] = 6379;
$config['timeout'] = 0;	
$this->load->driver('cache');
$this->cache->redis->save('foo', 'bar', 10);

Fatal error: Call to a member function set() on null in D:\Vhosts\catv\system\libraries\Cache\drivers\Cache_redis.php on line 193

A PHP Error was encountered
Severity: Error
Message: Call to a member function set() on null
Filename: drivers/Cache_redis.php

Line Number: 193

**Comment by fifthsegment** [comment]
This is most likely the php redis extension not loaded. CodeIgniter should have thrown an exception immediately when you loaded the cache driver, rather than allowing you to call the save function. I've pushed some changes that should fix that.

**Comment by narfbg** [comment]
Please follow #5562.

**Comment by ravikantgyanwave** [comment]
Getting this error:-

Type: Error

Message: Call to a member function sRemove() on null
Filename: C:\wamp64\www\services\system\libraries\Cache\drivers\Cache_redis.php
Line Number: 196

Backtrace:

File: C:\wamp64\www\services\application\controllers\Redis.php
Line: 6
Function: save

File: C:\wamp64\www\services\index.php
Line: 315
Function: require_once

Please help!

**Comment by azuajece** [comment]
i have the same problems
