### ISSUE TITLE
Table class

### ISSUE THREAD

**Issue by florent6001** [bcit-ci/CodeIgniter#5578]
Hi all,
By default the table class order by ASC the first column, how can i change it ?
I already try to make an order_by in my query but it's doesn't work.

Thank's you

**Comment by loka1** [comment]
try this
```
$this->db->order_by('title', 'DESC');
// Produces: ORDER BY `title` DESC
-------------------------------------------------------------------------
$this->db->order_by('title', 'ASC');
// Produces: ORDER BY ``title` ASC
--------------------------------------------
$this->db->order_by('title', 'RANDOM');
// Produces: ORDER BY RAND()
```

**Comment by narfbg** [comment]
Please post such questions on our [forums](https://forum.codeigniter.com/) instead. This is a bug tracker, not StackOverflow.

And it goes for both of you ... I know you just want to be helpful, @loka1, but chiming in with suggestions only encourages more people to come here for basic help and we don't want that.
