### ISSUE TITLE
Built-in functionality/feature request: Removal of "X-Powered-By"

### ISSUE THREAD

**Issue by gxgpet** [bcit-ci/CodeIgniter#5579]
Hi,

I was thinking about a new functionality for the core of framework, but I guess some discussion should be made here before actually opening a new PR.

We all know that PHP is exposing its version via `X-Powered-By` header. This is not really a big issue (as speaking of security), however, it may lead to some vulnerabilities based on this value for some attackers.

Without making a common point for the below code for its entire application, the CodeIgniter developer could simply turn on a setting/config item and the framework could do this for the developer:

```php
if (function_exists('header_remove'))
{
	header_remove('X-Powered-By');
}
else
{
	@ini_set('expose_php', 'off');
}
```

So what are the thoughts on this? :) I can make the PR myself, but as I said, a discussion should be made here before it.

**Comment by narfbg** [comment]
Even if this was desirable, the option already exists in php.ini. We're not going to duplicate functionality.

**Comment by gxgpet** [comment]
Not everyone has access to php.ini, especially on shared hosting solutions... :) But well.
