### ISSUE TITLE
当访问首页有参数时，访问页面不存在

### ISSUE THREAD

**Issue by tyong32** [bcit-ci/CodeIgniter#5582]
测试方式：配置文件uri_protocol参数修改为QUERY_STRING
访问页面：http://127.0.0.1/?ceshi=ceshi ，首页带参数，提示页面不存在

建议修正文件：\system\core\URI.php
修正函数如下：
	protected function _parse_query_string()
	{
		$uri = isset($_SERVER['QUERY_STRING']) ? $_SERVER['QUERY_STRING'] : @getenv('QUERY_STRING');
		
		if (trim($uri, '/') === '')
		{
			return '';
		}
		elseif (strncmp($uri, '/', 1) === 0)
		{
			$uri = explode('?', $uri, 2);
			! isset($uri[1]) OR parse_str($uri[1], $_GET);
			$uri = $uri[0];
		}
		else
		{
			parse_str($_SERVER['QUERY_STRING'], $_GET);
			return '';
		}
		
		return $this->_remove_relative_directory($uri);
	}

**Comment by jim-parry** [comment]
English please ...
