### ISSUE TITLE
Can't Access CI object in thread class using pthreads

### ISSUE THREAD

**Issue by chughashish47** [bcit-ci/CodeIgniter#5584]
Can't get instance of CI Object to use model in run() function of thread class.

Thread is starting ok but not able to call model  functions Please help !!!
Example code below : 

class Clinical extends CI_Controller
{
	function __construct()
	{
	    parent::__construct();
        }
       public function import()
	{
		$folder  = $_POST["folder_name"];
		$dir = directory_map('../clinicalTrial/'.$folder);
		$key     = $folder;
		$myThreadObj = new ClinicalThread($dir,$key);
		var_dump($myThreadObj->start());
		echo "Import Done";
		exit;
	}
}

class ClinicalThread extends Thread
{
	public $dir = array();
	public $key = "";
	public function __construct($dir,$key){		
		$this->dir=$dir;
		$this->key=$key;
	}
	function run()
	{
		$CI = & get_instance();
		print_r($CI);
		exit;
        }
}

**Comment by jim-parry** [comment]
Support questions should be asked on our [forum](https://forum.codeigniter.com/index.php), thanks. We use github for bug tracking.
