### ISSUE TITLE
DB_forge - Cannot use [] for reading

### ISSUE THREAD

**Issue by artlantis** [bcit-ci/CodeIgniter#5587]
Hi,

in DB_forge.php file, there is a line like below :
`isset($this->db->data_cache['table_names']) && $this->db->data_cache['table_names'][] = $table;`

Is this line right or not?

**Comment by narfbg** [comment]
What do you mean? Anybody can point to an arbitrary line of code and ask something about it, but that's not what we do here.

Are you saying there's a problem with it? If so, please explain it.

**Comment by narfbg** [comment]
This turned out to be a legitimate bug ... I don't know why you just closed the issue instead of answering my question.
