### ISSUE TITLE
Query Builder method limit() not allow 0 values 

### ISSUE THREAD

**Issue by tomylie** [bcit-ci/CodeIgniter#5588]
CI: 3.1.9
dbdriver: sqlite3

```
$this->db->where ( 'ag', $kat );
$this->db->limit($limit, $offset);
$this->db->order_by('sort', 'ASC');
$query = $this->db->get("artikel");
```

In CI Version 3.1.9

`$this->db->limit(0, 0);`

limit does not return results if the first parameter is 0. 
With values other than 0 a result is returned.  

In CI Version 3.1.8  

`$this->db->limit(0, 0);`

it worked.

**Comment by narfbg** [comment]
Quite the opposite; `limit(0)` was ignored before 3.1.9 ... See #5471. Whatever you were trying to do with that, it was pointless.

**Comment by tomylie** [comment]
My mistake. I thought 0 = false = no limit and that worked in version 3.1.8.
Two bugs that have mutually fixed each other ;-)
