### ISSUE TITLE
sql: WHERE IN (?). Use Query Bindings.

### ISSUE THREAD

**Issue by DCTmaybe1201** [bcit-ci/CodeIgniter#5589]
There are unexpected quotations after query. 
e.g.
$ids = '1,2';
$sql1 = 'SELECT * FROM `admin` WHERE `admin`.`id` IN (' . $ids . ')';
$this->db->query($sql1)->result_array();
// sql1 = SELECT * FROM `admin` WHERE `admin`.`id` IN (1,2)

$sql2 = 'SELECT * FROM `admin` WHERE `admin`.`id` IN (?)';
$this->db->query($sql2, [$ids])->result_array();
// sql2 = SELECT * FROM `admin` WHERE `admin`.`id` IN ('1,2')

Is it a behavior of query or some usage about query I don't know?

**Comment by narfbg** [comment]
`'1,2'` is a single string value ... and that's how it gets treated as.
