### ISSUE TITLE
application/config/routes.php file does not appear to contain a valid configuration array

### ISSUE THREAD

**Issue by followshihab** [bcit-ci/CodeIgniter#5593]
Today I upgraded my codeigniter project from 2.x to 3.1.9. Everything required for new update done as shown in Codeigniter Upgrade tutorial [Upgrading from 2.2.x to 3.0.x](https://www.codeigniter.com/userguide3/installation/upgrade_300.html). But when I run my project in the browser it is showing a message

> Your C:\wamp64\www\the_quarry_2.4_upgraded\application\config/routes.php file does not appear to contain a valid configuration array.

My project root folder is : `C:\wamp64\www\the_quarry_2.4_upgraded`

Contents of application/config/routes.php are:

    <?php
    defined('BASEPATH') OR exit('No direct script access allowed');

    $route['default_controller'] = 'home/index';
    $route['404_override'] = '';
    $route['translate_uri_dashes'] = FALSE;

But when I added the following lines of codes below $route array, it is working fine.

    $config['default_controller'] = 'home/index';
    $config['404_override'] = '';
    $config['translate_uri_dashes'] = FALSE;

Now it needs both $route and $config variables to work fine

**Comment by narfbg** [comment]
This is a bug tracker; please ask your questions on our [forums](https://forum.codeigniter.com/) instead.
