### ISSUE TITLE
bug: CI3 does not return correctly the results aliasing if ODBC are the database

### ISSUE THREAD

**Issue by mckaygerhard** [bcit-ci/CodeIgniter#5595]
i repeat, my database returns correctly the results, and the odbc drivers too, CI3 not!

same as #5594

**Comment by narfbg** [comment]
Next time you're getting banned.

**Comment by mckaygerhard** [comment]
i posted respectfully and i posted reading the contribution docment! thanks for nothing! ok can you baned me, its clear that you cannot hear only that you dessire! for sure ban others that dont think as you! but for sure there's a mechanish in github for this king of responses

i tested the driver and the sql and returns all correctly! only CI3 not retuns the results!
