### ISSUE TITLE
Session ID changes mid-request

### ISSUE THREAD

**Issue by aphofstede** [bcit-ci/CodeIgniter#5596]
When a request takes a while the session ID retrieved via `session_id()` can differ from the latest record in the database.
In some code upgraded from 2.x we add rows with a session ID column for easy garbage collection, but now that the session ID can change mid-session we're seeing foreign key errors since the value from `session_id()` doesn't have a record in the database yet.

Set up a new project, configure the database, create ci_sessions table and configure the sessions config to use it; add an endpoint `/welcome/wait` that takes a while and prints out the session IDs:
```
class Welcome extends CI_Controller {

	/**
	 * Index Page for this controller.
	 *
	 * Maps to the following URL
	 * 		http://example.com/index.php/welcome
	 *	- or -
	 * 		http://example.com/index.php/welcome/index
	 *	- or -
	 * Since this controller is set as the default controller in
	 * config/routes.php, it's displayed at http://example.com/
	 *
	 * So any other public methods not prefixed with an underscore will
	 * map to /index.php/welcome/<method_name>
	 * @see https://codeigniter.com/user_guide/general/urls.html
	 */
	public function index()
	{
		$this->load->view('welcome_message');
	}

	function wait() {
	    $ids = $this->db->query('select id from ci_sessions where true order by timestamp desc')->result_array();
	    sleep(60);
	    $sid = session_id();
	    var_dump(array_column($ids, 'id'));
	    var_dump($sid);
    }
}
```

Output:
```
session_test/application/controllers/Welcome.php:30:
array (size=3)
  0 => string '27ld9cu8qc83n2hvjrvi18jbisgi1rmf' (length=32)
  1 => string 'cdg9tp1tmj1ldl8nc6p4kl0fc7supip4' (length=32)
  2 => string '7p3e3p7ujf37b5dlhhvjhidkftkr4724' (length=32)
session_test/application/controllers/Welcome.php:31:string '81flh80ftco2keok46n49g2vr7brifg0' (length=32)
```

I can supply a repro project if necessary.

**Comment by narfbg** [comment]
IDs can't change *mid*-session, but ID regeneration is a thing and it does happen in the middle of a request, so I don't see anything out of order here ...

Also, in your example you first fetch the *last accessed* session, not the current one. The only way for those things to be guaranteed to be the same is if there's only ever a single user, with a single session that's never regenerated ...

**Comment by narfbg** [comment]
Nope, sessions are written once when `session_write_close()` is called and that usually happens at the end of a request.

**Comment by aphofstede** [comment]
I see PHP has control of this flow.

We are using the session ID to piggyback off of the session GC. Search results have a column linking them to the current session, the idea was to have the user have access to those rows during his session and when the sessions get cleaned so do the search results. This has worked pretty well in CI2.x the past years, but I'm starting to think this is not a reliable value to link to anymore.

Can we utilise the `sess_time_to_update` config setting to get the desired behaviour or should I start investigating a different way of tracking "while a user is logged in"? (FYI we use [Ion_auth](https://github.com/benedmunds/CodeIgniter-Ion-Auth) for authentication)

**Comment by narfbg** [comment]
Unlikely. But either way, this is a bug tracker and we don't answer such questions here. You might have a better luck on our [forums](https://forum.codeigniter.com/).

**Comment by aphofstede** [comment]
I am aware. I'd say having a session ID during a request that doesn't match any sessions in the sessions table can be an issue though. I'll direct my questions to the forum, thanks.
