### ISSUE TITLE
User specified database connection details

### ISSUE THREAD

**Issue by psuplat** [bcit-ci/CodeIgniter#5597]
Hi,

I have an application which contains an install script, which holds database table definitions and default data.

It will be up to the user to create the database first and then supply the db and login data to the application (think Drupal or any other CMS install script).

My initial form asks user for all the fields required (host, db name, port, login, pass).
What would be the best way to update the database config file with the user supplied information, or alternatively save that info to a custom file, and make cogeigniter load db config fro that file.

**Comment by jim-parry** [comment]
Please ask support questions on our [forum](https://forum.codeigniter.com/) ... we use github for bug tracking.
