### ISSUE TITLE
Problem with query

### ISSUE THREAD

**Issue by renatomcribeiro** [bcit-ci/CodeIgniter#5598]
When we make a query with subquery the sqlsrv don't return nothing.
For example: SELECT cast(VENDAS_ANO_ATUAL as money),cast(VENDAS_ANO_ANTERIOR as money), cast(cast(CASE WHEN VENDAS_ANO_ANTERIOR = 0 THEN 0 ELSE ((VENDAS_ANO_ATUAL - VENDAS_ANO_ANTERIOR) / VENDAS_ANO_ANTERIOR) * 100 END as int) as varchar) + '%' AS PERCENTAGEM, case when VENDAS_ANO_ANTERIOR< VENDAS_ANO_ATUAL then '' else case when VENDAS_ANO_ANTERIOR> VENDAS_ANO_ATUAL then '' else '' end end FROM ( SELECT SUM(CASE WHEN Ano = YEAR(GETDATE()) THEN TotalLiqMBase ELSE 0 END) AS VENDAS_ANO_ATUAL, SUM(CASE WHEN Ano = YEAR(GETDATE())-1 THEN TotalLiqMBase ELSE 0 END) AS VENDAS_ANO_ANTERIOR FROM AcumuladosVendas (NOLOCK) JOIN DocumentosVenda ON DocumentosVenda.Documento=AcumuladosVendas.TipoDoc WHERE AcumuladosVendas.VENDEDOR IN (1) AND DocumentosVenda.TipoDocumento = 4 ) AS DATA

Return that on SQL Management studio
![image](https://user-images.githubusercontent.com/389638/45501907-79abde80-b77a-11e8-8447-da057c962a74.png)

The big problem is: We received this by other software, and is impossible add alias on query.

**Comment by jim-parry** [comment]
This is a support question, and should be addressed on the forum (where you have already posted a thread). I see you are also trying to get help on the slack channel, and not getting the answer you want.
We use github for bug tracking, and this isn't one - you need access to the code so you can change it.

**Comment by renatomcribeiro** [comment]
if you see on the post and slack we say is impossible change query. We receive the same dynamically, because of that we have the problem. the only way is change the DB files on systems folder. 
But ok we solve that. We try to see a work around to don't change the system.
