### ISSUE TITLE
Wrong result for $this->db->count_all_results

### ISSUE THREAD

**Issue by followshihab** [bcit-ci/CodeIgniter#5599]
`$this->db->count_all_results('my_table', FALSE);` not taking the 'SELECT' query part as  what explained in [CI Tutorial](https://www.codeigniter.com/userguide3/database/query_builder.html#limiting-or-counting-results) as follows....

> ![ci](https://user-images.githubusercontent.com/32905143/45606773-8de72880-ba65-11e8-9a1a-acc6d4cd1dd8.png)

My CI version is 3.1.9 (Just upgraded from 2x).
My query is as follows *(Produced by $this->db->last_query())*

    SELECT DISTINCT(mch_id), machineries.* 
    FROM `machineries`, `machinery_workcentres` 
    WHERE `mch_status` = '1' 
     AND (`mwc_fk_workcentres` = '1' OR `mwc_fk_workcentres` = '4') 
     AND `mwc_status` = '1' 
     AND `mwc_fk_machineries` = `mch_id` 
    ORDER BY `mch_name` ASC 
This query results total 12 rows.
But when I tried to take the count of the same query as 

    $this->db->count_all_results('machineries, machinery_workcentres' , FALSE);
Its result is 16 and it is incurrect. It is because the query omits the `SELECT` part `DISTINCT(mch_id), machineries.*` The query returned by $this->db->last_query() as follows

    SELECT COUNT(*) AS `numrows` 
    FROM `machineries`, `machinery_workcentres` 
    WHERE `mch_status` = '1' 
     AND (`mwc_fk_workcentres` = '1' OR `mwc_fk_workcentres` = '4') 
     AND `mwc_status` = '1' 
     AND `mwc_fk_machineries` = `mch_id`

**Comment by narfbg** [comment]
That sentence in the tutorial has nothing to do with this. Explaining it would be rather lengthy, so I hope you get it from the following examples:

    $this->db->select('foo');
    $this->db->count_all_results('bar');
    $this->db->get('bar'); // all columns will be returned

    $this->db->select('foo');
    $this->db->count_all_results('bar', FALSE);
    $this->db->get('bar'); // only "foo" column will be in the result set
