### ISSUE TITLE
Call to undefined function mssql_connect(), on php 5.6

### ISSUE THREAD

**Issue by Jinqianv** [bcit-ci/CodeIgniter#5601]
Hello.
I added extension pdo_sqlsrv, sqlsrv as the extension.
But the issue is occurred from mssql_driver.php 
How to fix this problem?

**Comment by ahmadrasyidsalim** [comment]
Maybe that function was **removed** [official doc](https://secure.php.net/manual/en/function.mssql-connect.php)

Have you try using PHP 5.1? cause I found some information from [stackoverflow](https://stackoverflow.com/questions/11244470/mssql-connect-no-longer-working-as-of-php-5-3)

**Comment by narfbg** [comment]
@Jinqianv 'sqlsrv' !== 'mssql'

And this is a bug tracker. You should ask your questions on our [forums](https://forum.codeigniter.com/) instead.

@ahmadrasyidsalim Please don't ever suggest PHP 5.1 or other out of date software to anyone. We should be pushing for upgrades, not downgrades.
