### ISSUE TITLE
CodeIgniter 3.1.7 - remove from the Internet

### ISSUE THREAD

**Issue by madmis** [bcit-ci/CodeIgniter#5603]
This is an unhappy user

**Comment by jim-parry** [comment]
lways ask for help on our forum, instead of going offensively ballistic.

**Comment by narfbg** [comment]
You know what I do whenever a certain framework or tool is forced upon me? I quit the job. Every single time. I have zero regrets about it and if you hate CodeIgniter so much, I suggest you do the same.

What I don't do is go on a bugtracker to ask for someone's torturous death.

**Comment by madmis** [comment]
> You know what I do whenever a certain framework or tool is forced upon me? I quit the job. Every single time. I have zero regrets about it and if you hate CodeIgniter so much, I suggest you do the same.
> 
> What I don't do is go on a bugtracker to ask for someone's torturous death.

Thanks for suggestion.

I like my job and then next step here - is rewrite current application using another framework. But it's require a few month to doing this. So we are planning to run first version using current codebase, and that start rewriting.

Previous developer chosen CodeIgniter and when i saw this developer code, i understood why. 
Today I just gave up my nerves.
When I use the tool, I expect that it is tested and reliable. But in the case of the CodeIgniter no one knows where the next bullet will come from.

Sorry for my panic, guys.
