### ISSUE TITLE
$this->db->insert_batch( ) === false not working

### ISSUE THREAD

**Issue by ganl** [bcit-ci/CodeIgniter#5607]
insert_batch($table[, $set = NULL[, $escape = NULL[, $batch_size = 100]]])
参数:	
$table (string) -- Table name
$set (array) -- Data to insert
$escape (bool) -- Whether to escape values and identifiers
$batch_size (int) -- Count of rows to insert at once
返回:	
Number of rows inserted or FALSE on failure

返回类型:	
mixed

$this->db->insert_batch($this->table_statistics, $statistics)  === false

not working

0 === false

**Comment by jim-parry** [comment]
Reports in English, please - we don't speak Chinese or Korean.

**Comment by ganl** [comment]
I will choose laravel.

**Comment by lonnieezell** [comment]
When using the strict comparison (===) 0 != false. They only equal each other with loose comparison (==). And that's a PHP thing, not a CodeIgniter thing.

**Comment by ganl** [comment]
https://www.codeigniter.com/user_guide/database/query_builder.html?highlight=insert_batch#CI_DB_query_builder::insert_batch



Returns: | Number of rows inserted or FALSE on failure


Actually return 0 on failure
