### ISSUE TITLE
fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:140D00CF:SSL routines:SSL_write:protocol is shutdown

### ISSUE THREAD

**Issue by athiradevi** [bcit-ci/CodeIgniter#5608]
cannot send the email the error is fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:140D00CF:SSL routines:SSL_write:protocol is shutdown the code is given below

<?php
    $config['protocol'] = 'smtp';
    $config['smtp_host'] = 'ssl://mail.test.org'; //change this
    $config['smtp_port'] = '465';
    $config['smtp_user']    = 'info@test.org'; //change this
    $config['smtp_pass']    = 'testtesttest'; //change this
    $config['mailtype'] = 'html';
    $config['charset'] = 'iso-8859-1';
    $config['wordwrap'] = TRUE;
    $config['newline'] = "\r\n"; //use double quotes to comply with RFC 822 standard
?>

**Comment by athiradevi** [comment]
cannot send the email the error is fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:140D00CF:SSL routines:SSL_write:protocol is shutdown the code is given below

<?php
    $config['protocol'] = 'smtp';
    $config['smtp_host'] = 'ssl://mail.test.org'; //change this
    $config['smtp_port'] = '465';
    $config['smtp_user']    = 'info@test.org'; //change this
    $config['smtp_pass']    = 'testtesttest'; //change this
    $config['mailtype'] = 'html';
    $config['charset'] = 'iso-8859-1';
    $config['wordwrap'] = TRUE;
    $config['newline'] = "\r\n"; //use double quotes to comply with RFC 822 standard
?>

**Comment by athiradevi** [comment]
> cannot send the email the error is fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:140D00CF:SSL routines:SSL_write:protocol is shutdown the code is given below

**Comment by narfbg** [comment]
Duplicate of #3538.
