### ISSUE TITLE
can't upload coming from cordova camera plugin

### ISSUE THREAD

**Issue by ledarky** [bcit-ci/CodeIgniter#5612]
hello
codeigniter file uploading class seems not working with image coming from camera plugin
i'm developing a cordova app with codeigniter backend
i've try to upload files with classic input it's work very well
but when i try to upload images coming from camera codeigniter upload fail with 'noy authorized type file'
but when i try using native $_FILES it's work, what is the problem
please help me !

**Comment by jim-parry** [comment]
Please ask support questions on our [forum](https://forum.codeigniter.com/). We use github for bug tracking.
