### ISSUE TITLE
Numeric database names

### ISSUE THREAD

**Issue by smallislandproductions** [bcit-ci/CodeIgniter#5615]
CI database module doesn't properly escape numeric database names. For example, "SHOW TABLES FROM `1984` "becomes "SHOW TABLES FROM 1984" which fails in MySQL.

**Comment by smallislandproductions** [comment]
See an StackOverflow answer here regarding database names not existing of soley digits unless escaped. https://stackoverflow.com/a/25595372

I know it's not best practice, but in my usage, I have no control of database names - I just need to be able to connect to them.

**Comment by narfbg** [comment]
Duplicate of #3877.
