### ISSUE TITLE
Codeigniter session not working on android chrome

### ISSUE THREAD

**Issue by Elvis254** [bcit-ci/CodeIgniter#5620]
Hi, am having a problem with saving sessions on chrome android browser. The system logs a user in but it doesn't redirect to dashboard page which is accessible when a user is logged in. Am using codeigniter version 3.1.9. Any help of how I can fix the problem will be quite appreciated. Elvis.

**Comment by marvinIsSacul** [comment]
Perhaps if you provided for information & details. Perhaps even the source code...

**Comment by narfbg** [comment]
This is a bug tracker. You should seek help on our [forums](https://forum.codeigniter.com/) instead.

And be more descriptive; CI doesn't have a "dashboard" or "login" in it, so you're basically just saying "something I built doesn't work".
