### ISSUE TITLE
log_message causing deadlock

### ISSUE THREAD

**Issue by wir3code** [bcit-ci/CodeIgniter#5622]
Hi friends,

This is arguably in violation of contributing guideline number 3, but this does create a pretty big issue.

When passing an object as a second parameter to log_message, a deadlock is created, and Apache completely hangs. write_log does not appear to stringify the argument. My best guess is that the following occurs:

1) Exclusive lock on log file is obtained
2) Logging crashes
3) CI tries to log this crash into the same log file which is still locked
4) Apache cannot obtain a lock, and subsequently hangs.

Version=3.1.4.

**Comment by narfbg** [comment]
`log_message()` clearly expects a string and not objects, so this is a non-issue to me.
