### ISSUE TITLE
CSRF problem

### ISSUE THREAD

**Issue by marvinIsSacul** [bcit-ci/CodeIgniter#5625]
![csrf](https://user-images.githubusercontent.com/43840569/47271238-1f6f1c00-d577-11e8-9653-4c63b6c1b8e7.png)

Hi whenever I have CSRF enabled, i always get the above error whenever I submit my forms. And in my forms I do include the CSRF hidden input element.

What could be the issue ?
I am using CI 3.1.9

**Comment by narfbg** [comment]
This is a bug tracker. Please ask your questions on our [forums](https://forum.codeigniter.com/) instead.

Also, please don't post screenshots, especially if they don't provide any additional information. It really doesn't help and is just an annoyance.
