### ISSUE TITLE
mysqli::real_connect() expects parameter 5 to be integer, string given

### ISSUE THREAD

**Issue by ethereal-sandeep** [bcit-ci/CodeIgniter#5627]
The configuration for database use to work just fine. suddenly i am seeing this error being thrown under E_WARNING without changing any configuration in the db config file.

I am using codeigniter 3

`
mysqli::real_connect() expects parameter 5 to be integer, string given - /var/www/html/project/system/database/drivers/mysqli/mysqli_driver.php:305`

Kindly help

**Comment by ethereal-sandeep** [comment]
@narfbg  Could you help here.

**Comment by aanbar** [comment]
Just remove the quotes around the port in your database config.

**Comment by ethereal-sandeep** [comment]
@aanbar , as per the /application/config/database, its already an integer and not a string. Not sure why this error.

**Comment by ethereal-sandeep** [comment]
@aanbar , you are correct, the config file doesn't define a port so i am wondering if the port config is part of the framework definition, should i be getting this error. 

The db config is the standard one and yes i do use DNS.

$db['default'] = array(
	'dsn'	=> '',
	'hostname' => 'hostnameChangeMe',
	'username' => 'usernameChangeMe',
	'password' => 'passwordChangeMe',
	'database' => 'dbChangeMe',
	'dbdriver' => 'mysqli',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => FALSE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

**Comment by joncmc** [comment]
I am using CI 3.1.13 and PHP 8.1, the connection works fine but suddenly it shows me this error, 
```
Type: TypeError
Message: mysqli::real_connect(): Argument #5 ($port) must be of type ?int, string given
Filename: /system/database/drivers/mysqli/mysqli_driver.php 315
```

the strange thing is that it is shown in the next part
```
protected function _execute($sql)
    return $this->conn_id->query($this->_prep_query($sql));
}
```

**Comment by casper123** [comment]
@joncmc 

I was also having the same issue. I ended up hardcoding port number in `mysqli_driver.php` on` line 205`
```

$port = 3306;
		if ($this->_mysqli->real_connect($hostname, $this->username, $this->password, $this->database, $port, $socket, $client_flags))
```
