### ISSUE TITLE
File Upload copied directly from the User Guide is not working! 

### ISSUE THREAD

**Issue by OAVHomeAdmin** [bcit-ci/CodeIgniter#5628]
I copied the File Upload Example directly from the User Guide for CI 3.1.9 and it is throwing a "**The upload path does not appear to be valid.**" Error, though I am uploaded a JPG & PNG File. MIME Config is update and list every file type available basically. System Files have been updated which was said to fix the issue. Still no luck.  

Anyone have a fix for this??

Also, I'm pretty sure this is going to apply to any other file types beyond images as well, so a complete solution would be greatly appreciated.

**Controller**
`
<?php

class Upload extends Front_Controller {

        public function __construct()
        {
                parent::__construct();
                $this->load->helper(array('form', 'url'));
        }

        public function index()
        {
                $this->load->view('upload_form', array('error' => ' ' ));
        }

        public function do_upload()
        {
                $config['upload_path']          = './uploads/';
                $config['allowed_types']        = 'gif|jpg|png';
                $config['max_size']             = 100000;
                $config['max_width']            = 1024;
                $config['max_height']           = 768;

                $this->load->library('upload', $config);

                if ( ! $this->upload->do_upload('userfile'))
                {
                        $error = array('error' => $this->upload->display_errors());

                        $this->load->view('upload_form', $error);
                }
                else
                {
                        $data = array('upload_data' => $this->upload->data());

                        $this->load->view('upload_success', $data);
                }
        }
}
?>

`

**View**
`
<html>
<head>
<title>Upload Form</title>
</head>
<body>

<?php echo $error;?>

<?php echo form_open_multipart('upload/do_upload');?>

<input type="file" name="userfile" size="512" />

<br /><br />

<input type="submit" value="upload" />

</form>

</body>
</html>

`

**MIME Config**

`
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
| -------------------------------------------------------------------
| MIME TYPES
| -------------------------------------------------------------------
| This file contains an array of mime types.  It is used by the
| Upload class to help identify allowed file types.
|
*/
return array(
    'hqx'   =>	array('application/mac-binhex40', 'application/mac-binhex', 'application/x-binhex40', 'application/x-mac-binhex40'),
    'cpt'   =>	'application/mac-compactpro',
    'csv'   =>	array('text/x-comma-separated-values', 'text/comma-separated-values', 'application/octet-stream', 'application/vnd.ms-excel', 'application/x-csv', 'text/x-csv', 'text/csv', 'application/csv', 'application/excel', 'application/vnd.msexcel', 'text/plain'),
    'bin'   =>	array('application/macbinary', 'application/mac-binary', 'application/octet-stream', 'application/x-binary', 'application/x-macbinary'),
    'dms'   =>	'application/octet-stream',
    'lha'   =>	'application/octet-stream',
    'lzh'   =>	'application/octet-stream',
    'exe'   =>	array('application/octet-stream', 'application/x-msdownload'),
    'class' =>	'application/octet-stream',
    'psd'   =>	array('application/x-photoshop', 'image/vnd.adobe.photoshop'),
    'so'    =>	'application/octet-stream',
    'sea'   =>	'application/octet-stream',
    'dll'   =>	'application/octet-stream',
    'oda'   =>	'application/oda',
    'pdf'   =>	array('application/pdf', 'application/force-download', 'application/x-download', 'binary/octet-stream'),
    'ai'    =>	array('application/pdf', 'application/postscript'),
    'eps'   =>	'application/postscript',
    'ps'    =>	'application/postscript',
    'smi'   =>	'application/smil',
    'smil'  =>	'application/smil',
    'mif'   =>	'application/vnd.mif',
    'xls'   =>	array('application/vnd.ms-excel', 'application/msexcel', 'application/x-msexcel', 'application/x-ms-excel', 'application/x-excel', 'application/x-dos_ms_excel', 'application/xls', 'application/x-xls', 'application/excel', 'application/download', 'application/vnd.ms-office', 'application/msword'),
    'ppt'   =>	array('application/powerpoint', 'application/vnd.ms-powerpoint', 'application/vnd.ms-office', 'application/msword'),
    'pptx'  => 	array('application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/x-zip', 'application/zip'),
    'wbxml' =>	'application/wbxml',
    'wmlc'  =>	'application/wmlc',
    'dcr'   =>	'application/x-director',
    'dir'   =>	'application/x-director',
    'dxr'   =>	'application/x-director',
    'dvi'   =>	'application/x-dvi',
    'gtar'  =>	'application/x-gtar',
    'gz'    =>	'application/x-gzip',
    'gzip'  =>	'application/x-gzip',
    'php'   =>	array('application/x-httpd-php', 'application/php', 'application/x-php', 'text/php', 'text/x-php', 'application/x-httpd-php-source'),
    'php4'  =>	'application/x-httpd-php',
    'php3'  =>	'application/x-httpd-php',
    'phtml' =>	'application/x-httpd-php',
    'phps'  =>	'application/x-httpd-php-source',
    'js'    =>	array('application/x-javascript', 'text/plain'),
    'swf'   =>	'application/x-shockwave-flash',
    'sit'   =>	'application/x-stuffit',
    'tar'   =>	'application/x-tar',
    'tgz'   =>	array('application/x-tar', 'application/x-gzip-compressed'),
    'z'     =>	'application/x-compress',
    'xhtml' =>	'application/xhtml+xml',
    'xht'   =>	'application/xhtml+xml',
    'zip'   =>	array('application/x-zip', 'application/zip', 'application/x-zip-compressed', 'application/s-compressed', 'multipart/x-zip'),
    'rar'   =>	array('application/x-rar', 'application/rar', 'application/x-rar-compressed'),
    'mid'   =>	'audio/midi',
    'midi'  =>	'audio/midi',
    'mpga'  =>	'audio/mpeg',
    'mp2'   =>	'audio/mpeg',
    'mp3'   =>	array('audio/mpeg', 'audio/mpg', 'audio/mpeg3', 'audio/mp3'),
    'aif'   =>	array('audio/x-aiff', 'audio/aiff'),
    'aiff'  =>	array('audio/x-aiff', 'audio/aiff'),
    'aifc'  =>	'audio/x-aiff',
    'ram'   =>	'audio/x-pn-realaudio',
    'rm'    =>	'audio/x-pn-realaudio',
    'rpm'   =>	'audio/x-pn-realaudio-plugin',
    'ra'    =>	'audio/x-realaudio',
    'rv'    =>	'video/vnd.rn-realvideo',
    'wav'   =>	array('audio/x-wav', 'audio/wave', 'audio/wav'),
    'bmp'   =>	array('image/bmp', 'image/x-bmp', 'image/x-bitmap', 'image/x-xbitmap', 'image/x-win-bitmap', 'image/x-windows-bmp', 'image/ms-bmp', 'image/x-ms-bmp', 'application/bmp', 'application/x-bmp', 'application/x-win-bitmap'),
    'gif'   =>	'image/gif',
    'jpeg'  =>	array('image/jpeg', 'image/pjpeg'),
    'jpg'   =>	array('image/jpeg', 'image/pjpeg'),
    'jpe'   =>	array('image/jpeg', 'image/pjpeg'),
    'jp2'   =>	array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'j2k'   =>	array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'jpf'   =>	array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'jpg2'  =>	array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'jpx'   =>	array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'jpm'   =>	array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'mj2'   =>	array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'mjp2'  =>	array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'png'   =>	array('image/png', 'image/x-png'),
    'tiff'  =>	'image/tiff',
    'tif'   =>	'image/tiff',
    'css'   =>	array('text/css', 'text/plain'),
    'html'  =>	array('text/html', 'text/plain'),
    'htm'   =>	array('text/html', 'text/plain'),
    'shtml' =>	array('text/html', 'text/plain'),
    'txt'   =>	'text/plain',
    'text'  =>	'text/plain',
    'log'   =>	array('text/plain', 'text/x-log'),
    'rtx'   =>	'text/richtext',
    'rtf'   =>	'text/rtf',
    'xml'   =>	array('application/xml', 'text/xml', 'text/plain'),
    'xsl'   =>	array('application/xml', 'text/xsl', 'text/xml'),
    'mpeg'  =>	'video/mpeg',
    'mpg'   =>	'video/mpeg',
    'mpe'   =>	'video/mpeg',
    'qt'    =>	'video/quicktime',
    'mov'   =>	'video/quicktime',
    'avi'   =>	array('video/x-msvideo', 'video/msvideo', 'video/avi', 'application/x-troff-msvideo'),
    'movie' =>	'video/x-sgi-movie',
    'doc'   =>	array('application/msword', 'application/vnd.ms-office'),
    'docx'  =>	array('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/zip', 'application/msword', 'application/x-zip'),
    'dot'   =>	array('application/msword', 'application/vnd.ms-office'),
    'dotx'  =>	array('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/zip', 'application/msword'),
    'xlsx'  =>	array('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/zip', 'application/vnd.ms-excel', 'application/msword', 'application/x-zip'),
    'word'  =>	array('application/msword', 'application/octet-stream'),
    'xl'    =>	'application/excel',
    'eml'   =>	'message/rfc822',
    'json'  =>	array('application/json', 'text/json'),
    'pem'   =>	array('application/x-x509-user-cert', 'application/x-pem-file', 'application/octet-stream'),
    'p10'   =>	array('application/x-pkcs10', 'application/pkcs10'),
    'p12'   =>	'application/x-pkcs12',
    'p7a'   =>	'application/x-pkcs7-signature',
    'p7c'   =>	array('application/pkcs7-mime', 'application/x-pkcs7-mime'),
    'p7m'   =>	array('application/pkcs7-mime', 'application/x-pkcs7-mime'),
    'p7r'   =>	'application/x-pkcs7-certreqresp',
    'p7s'   =>	'application/pkcs7-signature',
    'crt'   =>	array('application/x-x509-ca-cert', 'application/x-x509-user-cert', 'application/pkix-cert'),
    'crl'   =>	array('application/pkix-crl', 'application/pkcs-crl'),
    'der'   =>	'application/x-x509-ca-cert',
    'kdb'   =>	'application/octet-stream',
    'pgp'   =>	'application/pgp',
    'gpg'   =>	'application/gpg-keys',
    'sst'   =>	'application/octet-stream',
    'csr'   =>	'application/octet-stream',
    'rsa'   =>	'application/x-pkcs7',
    'cer'   =>	array('application/pkix-cert', 'application/x-x509-ca-cert'),
    '3g2'   =>	'video/3gpp2',
    '3gp'   =>	array('video/3gp', 'video/3gpp'),
    'mp4'   =>	'video/mp4',
    'm4a'   =>	'audio/x-m4a',
    'f4v'   =>	array('video/mp4', 'video/x-f4v'),
    'flv'   =>	'video/x-flv',
    'webm'  =>	'video/webm',
    'aac'   =>	'audio/x-acc',
    'm4u'   =>	'application/vnd.mpegurl',
    'm3u'   =>	'text/plain',
    'xspf'  =>	'application/xspf+xml',
    'vlc'   =>	'application/videolan',
    'wmv'   =>	array('video/x-ms-wmv', 'video/x-ms-asf'),
    'au'    =>	'audio/x-au',
    'ac3'   =>	'audio/ac3',
    'flac'  =>	'audio/x-flac',
    'ogg'   =>	array('audio/ogg', 'video/ogg', 'application/ogg'),
    'kmz'   =>	array('application/vnd.google-earth.kmz', 'application/zip', 'application/x-zip'),
    'kml'   =>	array('application/vnd.google-earth.kml+xml', 'application/xml', 'text/xml'),
    'ics'   =>	'text/calendar',
    'ical'  =>	'text/calendar',
    'zsh'   =>	'text/x-scriptzsh',
    '7zip'  =>	array('application/x-compressed', 'application/x-zip-compressed', 'application/zip', 'multipart/x-zip'),
    'cdr'   =>	array('application/cdr', 'application/coreldraw', 'application/x-cdr', 'application/x-coreldraw', 'image/cdr', 'image/x-cdr', 'zz-application/zz-winassoc-cdr'),
    'wma'   =>	array('audio/x-ms-wma', 'video/x-ms-asf'),
    'jar'   =>	array('application/java-archive', 'application/x-java-application', 'application/x-jar', 'application/x-compressed'),
    'svg'   =>	array('image/svg+xml', 'application/xml', 'text/xml'),
    'vcf'   =>	'text/x-vcard',
    'srt'   =>	array('text/srt', 'text/plain'),
    'vtt'   =>	array('text/vtt', 'text/plain'),
    'ico'   =>	array('image/x-icon', 'image/x-ico', 'image/vnd.microsoft.icon')
);
`

**Comment by aanbar** [comment]
The error says you haven't created your 'uploads' folder, or you have provided the wrong path to your uploads folder.

The upload library is working fine.

**Comment by aanbar** [comment]
I don't know what bonfire is, but it doesn't matter it shouldn't affect CodeIgniter.
The message you are getting is triggered by `validate_upload_path()` method when the provided upload_path is wrong or does not exists.
There could be many reasons why it's failing Here's a few:
- Check that your uploads or 'assets/uploads' you mentioned is on the same level of your index.php since you're providing a relative location.
- If you have autoloaded the uploads library chances are your config is being ignored when you try to load it again so try passing your upload config to `->initialize()` method instead
- try calling `die(realpath($config['upload_path']))` in your upload function to make sure your upload path can be resolved.

**Comment by OAVHomeAdmin** [comment]
So here's my current configuration

**Dashboard Controller**

> 
	public function Test_Upload()
	{
		$this->load->view('Test_Upload', array('error' => ' ' ));
		Template::render();
	}
     
    public function do_upload()
	{ 
		$config['upload_path']          = '../../../../assets/uploads';
		$config['allowed_types']        = 'gif|jpg|png';
		$config['max_size']             = 100000;
		$config['max_width']            = 1024;
		$config['max_height']           = 768;
		
		$this->load->library('upload', $config);
		
		$this->upload->initialize($config);

		if ( ! $this->upload->do_upload('userfile'))
		{
				$error = array('error' => $this->upload->display_errors());

				$this->load->view('Test_Upload', $error);
		}
		else
		{
				$data = array('upload_data' => $this->upload->data());

				$this->load->view('Test_Upload_Success', $data);
		}
	}
	
	public function Test_Upload_Success() {
		$this->load->library('users/auth');
		$this->set_current_user();
		
		Template::render();
	}


**Test Upload View**

> 

`<?php echo $error;?>`

`<?php echo form_open_multipart('Dashboard/do_upload');?>`

`<input type="file" name="userfile" size="20" />`

`<br /><br />`

`<input type="submit" value="upload" />`

`</form>`


**Test Success View**

`<h3>Your file was successfully uploaded!</h3>`

`<ul>`
`<?php foreach ($upload_data as $item => $value):?>`
`<li><?php echo $item;?>: <?php echo $value;?></li>`
`<?php endforeach; ?>`
`</ul>`

`<p><?php echo anchor('upload', 'Upload Another File!'); ?></p>`


**Autoload.php**

> 

`$autoload['libraries'] = array('calendar', 'database', 'email', 'form_validation', 'pagination', 'session', 'table', 'upload', 'zip');`


**Question 1:** Does the relative path need to be relative to the Controller? If not, what does it need to be relative to? I tried it in multiple ways, even an absolute path to an online directory and `base_url('uploads/');`. Still, no resolved. 

**Question 2:** Could you possibly show me a configuration of your own that is working for you? I really need this to work. My Employees are depending upon, users of the website, as well as the same situation for Customers Websites and their users.

**Additional Note:** When I did get passed this part, I then began having issues with MIME Types, which is up-to-date as well.

**Comment by OAVHomeAdmin** [comment]
http://localhost/OAVHome/site/v7/uploads which has 777 permissions

**Comment by jim-parry** [comment]
Hmm. It looks lilke http://localhost/OAVHome/site/v7/ might be your project root, and the domain should map there, eg using virtual hosting you might have OAVHomev7.local mapped to HTDOCS/site/v7/public and http://OAVHOMEv7.local would give your homepage. Am I misinterpreting?

**Comment by OAVHomeAdmin** [comment]
That is my project root. Just to give you more information, I am developing this on Mac OS X

**Comment by jim-parry** [comment]
Regardless of the platform, the domain name (real or virtual) should map to the project root/public.
Having all of the "../" elements in your upload path doesn't sound right.
Will investigate further.

**Comment by jim-parry** [comment]
Oops - I see you are using CI3, and not CI4. My comments about the domain mapping do not apply here, sorry.
Regardless, I will dig into this.

**Comment by aanbar** [comment]
I have just tested it & it works fine as it's written in the documentation.
The path is relative to your index.php file (the file that serves everything), You can test this out by creating a method in your controller, something like this:

```
public function checkpath()
    {
        var_dump(realpath('your path goes here'));
    }
```
if you get false, you have the wrong path, keep changing it until you get a value that matches your absolute path, Your path should probably be something like `./assets/uploads/`

**Comment by OAVHomeAdmin** [comment]
Got passed that error! Thanks! But.... The issue now is the following error:

> The filetype you are attempting to upload is not allowed.

And PNG is apparently allowed in the config above

**Comment by OAVHomeAdmin** [comment]
Figured it out! 

$config['allowed_types'] = '*'; 

Was the answer!!!

**Comment by OAVHomeAdmin** [comment]
@aanbar @jim-parry 
Thank you for the assist!

**Comment by narfbg** [comment]
This is a bug tracker. When you need help with something, please ask on our [forums](https://forum.codeigniter.com/) instead.

And I'd like to remind all participants of this as well. I understand the desire to help people, but look at that repo watchers count - over 1700 people have received emails for every single of the 15+ comments in this thread. Tens of thousands of notifications emails sent out by GitHub in the process of debugging a single guy's problem ... Please be responsible and keep things organized.
