### ISSUE TITLE
join query with IF() in condition is mangled

### ISSUE THREAD

**Issue by amalon** [bcit-ci/CodeIgniter#5632]
Using the query builder to construct a join where the condition contains IF() results in a mangled and invalid query.

E.g.
`$this->db->join('entities', 'IF('.$comparison.',entityrelations.second_entity,entityrelations.first_entity) = entities.id AND entityrelations.visible AND entities.visible');`

The "IF" is dropped by the following lines in the query builder:
```
$cond .= preg_match("/(\(*)?([\[\]\w\.'-]+)".preg_quote($operator)."(.*)/i", $conditions[$i], $match)
                   ? $match[1].$this->protect_identifiers($match[2]).$operator.$this->protect_identifiers($match[3])
$match[1].$this->protect_identifiers($match[3]).$operator.$this->protect_identifiers($match[4])
                  : $conditions[$i];
```

Hacking it to change the regex to start with `"/((if)?\(*)?([\[\]\w\.'-]+)"` (and adjusting the `$match` indices) makes it work for me, though obviously that isn't a complete solution, and it only appears to protect the first identifier mentioned.

Version: 3.1.9. It worked back at circa commit 329c17081025 (yes, apparently its a decade since I updated my website!)

**Comment by narfbg** [comment]
There was basically the same issue open with `select()` somewhere, but I can't find it right now. The gist of it is this: it's a can of worms not worth opening, so we have an `$escape` parameter for (I think) every public QB method - use it.
