### ISSUE TITLE
[Possible Form validation improvement] Custom error message in language file

### ISSUE THREAD

**Issue by ko2in** [bcit-ci/CodeIgniter#5633]
In current CI form validation library, the custom error messages can set by passing the fourth argument into `set_rules` or using `set_message` method.

However, it's hard to use when we need to display error messages in multiple languages. Because, it always needs to get the error messages for different language first and then pass into `set_rules` or `set_message`.

It would be more convenient if we could pass the key of error message which stores in language file, and let form validation library to retrieve the message when display. Example:

> $this->form_validation->set_rules('field_name', 'Label', 'required', array('required' => 'foo_message'));
> $this->form_validation->set_rules('field_name', 'Label', 'required', array('required' => 'bar_message'));

This will display the error message described in language file with `$lang['form_validation_foo_message']` and `$lang['form_validation_bar_message']` array.

The method `_get_error_message` in `Form_validation.php` only supports for default messages to get from language file.

> protected function _get_error_message($rule, $field)
> {
>   // check if a custom message is defined through validation config row.
>   if (isset($this->_field_data[$field]['errors'][$rule]))
>   {
>     return $this->_field_data[$field]['errors'][$rule];
>   }
>   // check if a custom message has been set using the set_message() function
>   elseif (isset($this->_error_messages[$rule]))
>   {
>     return $this->_error_messages[$rule];
>   }
>   elseif (FALSE !== ($line = $this->CI->lang->line('form_validation_'.$rule)))
>   {
>     return $line;
>   }
>   // DEPRECATED support for non-prefixed keys, lang file again
>   elseif (FALSE !== ($line = $this->CI->lang->line($rule, FALSE)))
>   {
>     return $line;
>   }
> 
>   return $this->CI->lang->line('form_validation_error_message_not_set').'('.$rule.')';
> }

So, for my need, I have to extend the core form validation class and overwrite the `_get_error_message` method, to allow the first two conditional blocks also check the message in language file first and return as it's passed with `set_rules` or `set_message` for fallback solution.

It'll also be more easier to maintain, since we can gather all of custom error messages together with default error messages in the same language file.

Maybe, it's good idea to support by core form validation library as default?

**Comment by narfbg** [comment]
Sorry, but no.

For one, the ablity to extend the framework, which you are using, is there exactly because we can't possibly cover every single need or edge case.  
But perhaps more important for you, the ability to pass custom error messages through `set_rules()` or `set_message()` is there as a shortcut for people who *don't* need language files. You're completely misusing that when you can just match language file keys to rule names.
