### ISSUE TITLE
Which is the best way to close db connection in CodeIgniter ?

### ISSUE THREAD

**Issue by jkpandya** [bcit-ci/CodeIgniter#5635]

**Comment by karanpepi** [comment]
Codeigniter closes the db connection by itself you need not have to worry about it. But  can close it by using 

`$this->db->close() `

**Comment by jkpandya** [comment]
Thanks karanpepi for Answer .  
But I have two question 
1) connection will release or abort after using $this->db->close() ? 
2) is there other way ?

**Comment by jim-parry** [comment]
Please ask support questions on our [forum](https://forum.codeigniter.com/index.php).
We use github for bug tracking.
