### ISSUE TITLE
xss_clean can not prevent xss attacks

### ISSUE THREAD

**Issue by hyacinth1** [bcit-ci/CodeIgniter#5637]
HTML CODE
<input type="text" value="">

Sample XSS Attacks
some word" onMouseOver="alert('xss')

CodeIgniter
1.x, 2.x, 3.x All not blocked

**Comment by jim-parry** [comment]
If you suspect a security problem, please file a proper vulnerability report on https://hackerone.com/codeigniter.
It is not responsible to post vulnerabilities on github.
Note that CodeIgniter 1.x and 2.x are out-of-scope, i.e. no longer supported.
