### ISSUE TITLE
"Database Backup" Syntax to use when inserting data can add insert multiple rows in every INSERT statement？

### ISSUE THREAD

**Issue by skycyclone** [bcit-ci/CodeIgniter#5639]
When using the backup() function, passing in the "add_insert" parameter, the backup file will add the field name to each INSERT statement, like this:
```
INSERT INTO `fyhtcms_common_area` (`id`, `name`, `level`, `upid`) VALUES (1, 'Beijing', 1, 0);
INSERT INTO `fyhtcms_common_area` (`id`, `name`, `level`, `upid`) VALUES (2816, 'Miyun District', 2, 1);
INSERT INTO `fyhtcms_common_area` (`id`, `name`, `level`, `upid`) VALUES (6667, 'urban', 3, 2816);
```
When the amount of data is extremely large, unnecessary redundant data is generated; when the database backup file is imported, it also causes a great waste of resources;

Can you add an "insert_multiple_rows" option with backup(), after which the backup file becomes like this:
```
INSERT INTO `fyhtcms_common_area` (`id`, `name`, `level`, `upid`) VALUES
(1, 'Beijing', 1, 0),
(2816, 'Miyun District', 2, 1),
(6667, 'City District', 3, 2816);
```

In order to prevent the data from being too large and causing no response when inserting, it is best to insert a field every 2000 rows of data, like this:

```
INSERT INTO `fyhtcms_common_area` (`id`, `name`, `level`, `upid`) VALUES
(1, 'Beijing', 1, 0),
(2816, 'Miyun District', 2, 1),
(6667, 'City District, 3, 2816),
...[[[[about 2000 lines passed]]]]...
(49686, 'Qing Xian Farm', 4, 278);

INSERT INTO `fyhtcms_common_area` (`id`, `name`, `level`, `upid`) VALUES
(49687, 'Qingfeng Farm', 4, 278),
(49688, 'Farm', 4, 278),
(279, 'Mengcun County', 3, 264),
...[[[[output 2000 lines again]]]]...
```

final effect:
The same database, 97 tables, 43931 data records
Use default CI backup file size: 4.58mb (44125 queries) Import time: about 31 seconds
Optimized backup file size: 1.51mb (279 queries) Import time: about 2.8 seconds

**Comment by narfbg** [comment]
There's no escape from this problem as it ultimately depends on your entire database size. Once you accumulate enough data, no amount of optimizations is going to make your backup imports fast enough to perform during a single web request.

That being said, optimizations won't hurt, but there's another problem ... I don't know how you came up with that 2000 number, but MySQL measures packet sizes and not counts. Even a single row can be too large.  
Therefore, regardless of the batch size in counts, there will always be a case when it breaks something for somebody out there.
