### ISSUE TITLE
issue image uploading in codeigniter

### ISSUE THREAD

**Issue by akky9890** [bcit-ci/CodeIgniter#5642]
In codeigniter image uploading image save in database but not in Folder help me to solve this

**Comment by davidgv88** [comment]
Whats is the issue? Do you need save the image in database?

**Comment by davidgv88** [comment]
Sorry, but this is very unclear. Have you short code example?

**Comment by akky9890** [comment]
Controller
<?php
	defined('BASEPATH') OR exit('No direct script access allowed');
	error_reporting(0);
	class Event extends CI_Controller {
		public function __construct(){    
			parent::__construct();    	
			
			
		}
		public function index()
		{
			$table='Notification_send';
			$where=array('');
			$orderfield='notification_id';
			$orderfieldvalue='desc';
			$data['event_data']=$this->Select_model->select_table_data_new($table,$where,$orderfield,$orderfieldvalue);
			$this->load->view('event_gallery',$data);
		}
		 public function save_event()
		{
				
		    $this->load->model('Save_update_model');
			
			$send_data=$this->Save_update_model->save_event_data();
			
			if($send_data=='Inserttrue')
			{
				$this->session->set_flashdata('success_msg', 'Record Inserted');
			}
			if($send_data=='Inserfalse')
			{
				$this->session->set_flashdata('success_msg', 'Record Not Inserted');
			}
			
			if($send_data=='Updatetrue')
			{
				$this->session->set_flashdata('success_msg', 'Record Updated ');
			}
			
			if($send_data=='Updatefalse')
			{
				$this->session->set_flashdata('success_msg', 'Record Not Updated');
			}
			redirect('Event', 'refresh');
		}
}
?>



model

<?php
	class Save_update_model extends CI_Model 
	{
		
		public function __construct()
		{
            parent::__construct();
			date_default_timezone_set('Asia/Kolkata');
			//$this->load->helper('url');
			$this->load->helper(array('form', 'url'));
		}
		
		
		public function save_event_data()
	{ 
			$fileData = array();
			$files = $_FILES;
			$filesCount = count($_FILES['userfile']['name']);
            for($i = 0; $i < $filesCount; $i++)
			{
				
			
				$_FILES['userfile']['name']=str_replace(" ","_",$files['userfile']['name'][$i]);
				$_FILES['userfile']['name']= $files['userfile']['name'][$i];				
				$_FILES['userfile']['type']= $files['userfile']['type'][$i];
				$_FILES['userfile']['tmp_name']= $files['userfile']['tmp_name'][$i];
				$_FILES['userfile']['error']= $files['userfile']['error'][$i];
				$_FILES['userfile']['size']= $files['userfile']['size'][$i];   
                
				//print_r($files['userfile']['name']);
				
                $uploadPath = 'uploads/images/';
                $config['upload_path'] = $uploadPath;
                $config['allowed_types'] = 'jpg|jpeg|png|gif';
                
                $this->load->library('upload', $config);
                $this->upload->initialize($config);
				
               // if($this->upload->do_upload('userfile')){
                if($this->upload->do_upload('userfile')){
                   
                    $fileData[] = $this->upload->data();					
                    $uploadData[$i]['event_photo'] = $fileData[$i]['file_name'];
                    
				}
			}
			// print_r($fileData);
			// print_r($uploadData);
			
			foreach($uploadData as $val){
				if(is_array($val)){
					//$t .= $this->session->userdata('agent_id').$val['prop_photos'].',';        
					$t .= $val['event_photo'].',';        
				}
			}
			
			$strng=substr ( $t , 0 , strlen($t) -1 );
			//print_r($_FILES);
			//print_r($strng);
			//die;
			/* $hidden_path_photo=$this->input->post('hidden_path_photo');
			$response=$this->member_image_upload();
			$imgurl1="uploads/".$response[0];
			
			if($response[0]!='')
			{
				$response[0]=str_replace(" ","_",$response[0]);
				$imgurl1="uploads/".$response[0];
			}
			else
			{
				$imgurl1=$hidden_path_photo;
			}
			 */
			if($_POST['check']=='')
			{
				$insertdata = array(
				'caption' =>  $_POST['caption'],
				'event_photo' =>  $imgurl1,
				'created_by' =>$this->session->userdata('user_id'),		
				'created_time' => date("Y-m-d h:i:s"),
				
				);
				
				echo "<pre>";
				print_r($insertdata);
				echo "</pre>";
				//print_r($insertdata);
				$this->db->insert('events', $insertdata);
				echo $this->db->last_query();
				if($this->db->affected_rows() != 1)
				{
					return 'Insertfalse';
				}
				else{					
					return 'Inserttrue';
					}
			}
			else
			{
				
				$updatedata = array(
				'caption'   =>  $_POST['caption'],
				'event_photo'   =>  $imgurl1,
				'updated_by' =>$this->session->userdata('user_id'),				
				'updated_time' => date("Y-m-d h:i:s"),
				);
				//print_r($updatedata);
				$this->db->where('event_id',$_POST['check']);
				
				$this->db->update('events', $updatedata);
				if($this->db->affected_rows() != 1)
				{
					return 'Updatefalse';
				}
				else{
					return  'Updatetrue';
					
				}
			}
		}
		
		
		/* public function save_event_data()
		{ 
		$this->db->insert('events', $inputdata); 
		$insert_id = $this->db->insert_id();

	  if($filename!='' ){
	  $filename1 = explode(',',$filename);
	  foreach($filename1 as $file){
	  $file_data = array(
	  'image' => $file,
	  //'user_id' => $insert_id
	  'user_id' => $insert_id
	  );
	  $this->db->insert('photos', $file_data);
	  }
	  }
		
		} */		
		
		function member_image_upload()
        {
			//echo "inside image";
            //$this->load->library('upload');
            $files = $_FILES;
            $count = count($_FILES['user_photo']['name']);
            for($i=0; $i<$count; $i++)
            {
				$_FILES['user_photo']['name']=str_replace(" ","_",$files['user_photo']['name'][$i]);
                $_FILES['user_photo']['name']= $files['user_photo']['name'][$i];
                $_FILES['user_photo']['type']= $files['user_photo']['type'][$i];
                $_FILES['user_photo']['tmp_name']= $files['user_photo']['tmp_name'][$i];
                $_FILES['user_photo']['error']= $files['user_photo']['error'][$i];
                $_FILES['user_photo']['size']= $files['user_photo']['size'][$i];    
                $this->upload->initialize($this->set_member_upload_options());
                if($this->upload->do_upload('user_photo') == False)
                {
                    $error = array('error' => $this->upload->display_errors());
					
				}
                else
                {
					
				}
				$finamearr[]=$files['user_photo']['name'][$i];
			}
			return $finamearr;
		}
}
?>



view

<form action="<?php echo base_url();?>Event/save_event" method="POST"  enctype="multipart/form-data" >
                        <div class="form-group clearfix">
                            <label class="control-label col-sm-2" for="email">Caption:</label>
                            <div class="col-sm-10">
                                <input type="text" name="caption" class="form-control" id="cap" placeholder="Enter Image Caption" >
								 <input type="hidden" name="check" id="check" value="" />
                            </div>
                        </div>
                        <input id="file" type="file" name="userfile[]" multiple accept="image/*" />
                        <input type="hidden" name="answer" id="answer" />
                        <div id="imagePreview"></div>
                        <div class="clear10"></div>
                        <input type="submit" name="submit" class="btn btn-small pull-right" value="Submit">

                    </form>




can u help me to stoar image in database as well as in upload folder

**Comment by jim-parry** [comment]
This is a support question, and should be asked on our [forum](https://forum.codeigniter.com/index.php).
We use github for bug tracking.
When you post your question on the forum, remember to use bbcode so that the result is readable, unlike above.
