### ISSUE TITLE
Feature Request - Customize the log file name

### ISSUE THREAD

**Issue by BrandonNoad** [bcit-ci/CodeIgniter#5648]
Hi,

Is it possible to add a config setting to customize the name of the log file?

In the `write_log` method (Log.php), you can customize the log file's directory and extension, but the `'log-'.date('Y-m-d')` portion of `$filepath` cannot be changed.

 Thanks!

**Comment by BrandonNoad** [comment]
We are making some changes to our dev environment and need the log filename to be static.

**Comment by shahrushabh1996** [comment]
Search this line on system/core/log.php just replace 'log-'.date('Y-m-d').' Replace this name with your custom name.

$filepath = $this->_log_path.'log-'.date('Y-m-d').'.'.$this->_file_ext;

**Comment by narfbg** [comment]
@BrandonNoad That doesn't really answer my question. What do you mean by static?

@shahrushabh1996 Please don't suggest manual edits of the stock framework code. And especially not here - this is our official repository, not a random forum board for people who want quick hacks.

**Comment by BrandonNoad** [comment]
Instead of having a new log file each day, we want to have a single log file, which is actually a symlink that points to /dev/stderr. 

Ideally, we could log directly to stderr. But I don't think that is possible, so this is a workaround.

**Comment by narfbg** [comment]
I have to say, I don't think that's a particularly good idea.

To be honest, when I asked why you'd need the feature I expected you to say something like per-vhost logfiles. And I've slowly convinced myself that we do need such a feature, so this does go into the TODO list.

**Comment by BrandonNoad** [comment]
Thanks.

We are moving our project to Kubernetes/Docker, and this feature will help with that.

Cheers.

**Comment by Lablnet** [comment]
https://github.com/bcit-ci/CodeIgniter/pull/5679

**Comment by jonsmith1982** [comment]
@narfbg I might have a crack at this, what do you propose to do with $config['log_file_extension'] to avoid it not adding to $filepath making it FALSE? and checking against it, if its not then adding .php?

**Comment by jonsmith1982** [comment]
[patch-#5648.txt](https://github.com/bcit-ci/CodeIgniter/files/2802784/patch-.5648.txt)

@narfbg This should do the trick

**Comment by jonsmith1982** [comment]
[issue-#5648.patch.txt](https://github.com/bcit-ci/CodeIgniter/files/2802907/issue-.5648.patch.txt)

@narfbg Right, did it properly this time. Would I be able to push these changes myself or is that restricted?

**Comment by shyamjos** [comment]
We were able to redirect the CodeIgniter logs to container's STDOUT by modifying CodeIgniter logging module which is located at system/core/Log.php, here is the full tutorial just in-case if anyone looking for a solution: https://shyamjos.com/redirecting-codeigniter-logs-to-container-stdout-stderr/

**Comment by danstreeter** [comment]
> We were able to redirect the CodeIgniter logs to container's STDOUT by modifying CodeIgniter logging module which is located at system/core/Log.php, here is the full tutorial just in-case if anyone looking for a solution: https://shyamjos.com/post/redirecting-codeigniter-logs-to-container-stdout-stderr/

For those coming here late on like myself - that link has changed to https://shyamjos.com/redirecting-codeigniter-logs-to-container-stdout-stderr/

**Comment by shyamjos** [comment]
> > We were able to redirect the CodeIgniter logs to container's STDOUT by modifying CodeIgniter logging module which is located at system/core/Log.php, here is the full tutorial just in-case if anyone looking for a solution: https://shyamjos.com/post/redirecting-codeigniter-logs-to-container-stdout-stderr/
> 
> For those coming here late on like myself - that link has changed to https://shyamjos.com/redirecting-codeigniter-logs-to-container-stdout-stderr/

@danstreeter Thanks , updated my comment

**Comment by ezzosystech** [comment]
> @shahrushabh1996 Please don't suggest manual edits of the stock framework code. And especially not here - this is our official repository, not a random forum board for people who want quick hacks.

This would work! And i  think answering politely would work as well for such cases! Like editing core framework isn't a good practice or bad at long term! Please give people advices instead of being rude.
