### ISSUE TITLE
DB_query_builder.php, from function doesn't have a $escape = NULL parameter

### ISSUE THREAD

**Issue by cdsaenz** [bcit-ci/CodeIgniter#5649]
While where, join and order_by all have an extra parameter that you can set to false to avoid backticks escaping, I see from doesn't have that. Just curious, maybe it's by design.

The function declaration as of 3.1.9

`public function from($from)`

**Comment by narfbg** [comment]
This is a bug tracker ... Please don't open issues just out of curiosity.
