### ISSUE TITLE
application/libraries/UploadHandler.php

### ISSUE THREAD

**Issue by phperwang** [bcit-ci/CodeIgniter#5653]
function get_config_bytes($val) {
        $val = trim($val);
        $last = strtolower($val[strlen($val)-1]);
        $val = intval($val);  //////////////////////////////////////////////////////should add it.
        switch($last) {
            case 'g':
                $val *= 1024;
            case 'm':
                $val *= 1024;
            case 'k':
                $val *= 1024;
        }
        return $this->fix_integer_overflow($val);
    }

**Comment by narfbg** [comment]
???

**Comment by gorkemkara16** [comment]
blueimp jquery file upload error
A non well formed numeric value encountered in "........." php 348


`$val = intval($val);`
error added when adding this line.
Thank you very much @phperwang 👍
