### ISSUE TITLE
codeigniter session problem cloudflare

### ISSUE THREAD

**Issue by xaiborweb** [bcit-ci/CodeIgniter#5656]
Hi, I'm using Ion Auth social
https://github.com/ghosthouse/CodeIgniter-Ion-Auth-Social
and throughout my web check if the user has a session started or not.
```
if ($ this-> ion_auth-> logged_in ()) {
}
```
For this reason in /application/config/autoload.php charge
`$ autoload ['libraries'] = array ('ion_auth');`
in my localhost everything is perfect, but in my website protected with cloudflare, create multiple sessions just with this:
`__ci_last_regenerate | i: 1544893031;`
create more than 50 sessions per second only with this info which overloads my sql, I think it is a problem of CodeIgniter sessions with cloudflare.

So I'm wondering if you can share an option / solution, so that only one codeigniter session is created when the user logs in Ion Auth.
Thank you.

**Comment by jim-parry** [comment]
That is a support question, and should be asked on our [forum](https://forum.codeigniter.com/index.php), thanks.
There are lots of reported session problems and workarounds there.
