### ISSUE TITLE
Model Database not loaded

### ISSUE THREAD

**Issue by andreidigori** [bcit-ci/CodeIgniter#5666]
https://github.com/bcit-ci/CodeIgniter/blob/292ad891948676ecc97ab7636e99dbb5aab1b0e4/system/core/Loader.php#L278
I tried to link a database named 'mydatabase' with loaded model.
When I set third parameter to `$this->load->model('model_name', '', 'mydatabase')` database wasn't loading.

I've changed the `Loader.php` and changed line 278 to: `if ($db_conn !== FALSE && class_exists('CI_DB', FALSE))` (removed just negation operator), and now it works!
I think it's an issue, so why i've opened an issue.

Hope this will help others... )))

**Comment by narfbg** [comment]
That change only makes it so that it breaks under different circumstances. If anything should be changed, it makes more sense to just remove that check entirely.

Either way, I'm not entirely sure of the conditions under which you've encountered this problem. It may help if you provide more details.

**Comment by almatins** [comment]
per Codeigniter documentation [here](https://www.codeigniter.com/user_guide/general/models.html?highlight=load%20model#connecting-to-your-database), the third parameter is used to set either you want CI to connect to your database immediately or not. cmmiw.

or if you want to use more than 1 database connection, you can find the way [here](https://www.codeigniter.com/user_guide/database/connecting.html)

**Comment by andreidigori** [comment]
Hi there!
I ve changed my code to load database from controller.
I think this method is a little bit confusing and also its not documented enough )))
Thank you for replies!
