### ISSUE TITLE
Security issue in Code Igniter Loader.php file by using eval() method

### ISSUE THREAD

**Issue by rohitgorapid** [bcit-ci/CodeIgniter#5669]
In codeignite3 for Loader.php file, eval() is being used like this:
`echo eval('?>'.preg_replace('/;*\s*\?>/', '; ?>', str_replace('<?=', '<?php echo ', file_get_contents($_ci_path))));
`

This call to eval() contains untrusted input. If this input could be modified by an attacker, arbitrary PHP code could be executed on the server. The first argument to phpeval() contains data from the incoming HTTP request. The data from the incoming HTTP request originated from an earlier call to file_get_contents.

Can we not use Eval and use any other mencahnism???

**Comment by jim-parry** [comment]
you reported this on hacker one already.
Did you not read the security guidelines - if you suspect a secutiry issue, DON'T EXPOSE IT, like you have done here.
