### ISSUE TITLE
db query does not work well when use pdo driver and data contains special characters [PostgreSQL]

### ISSUE THREAD

**Issue by enginespot** [bcit-ci/CodeIgniter#5672]
when use PDO driver , we find that it can not insert data correctly

```
create table tb_demo
(
  name    text,
  content varchar(512)
);
```
```
        $sql = "insert into tb_demo (name,content) values('\',':3')";
        $this->db->query($sql);
```
the content field will be "$1" but not ":3"
![image](https://user-images.githubusercontent.com/1422439/50756214-67f4c680-1296-11e9-92d5-b1616d6eb477.png)

if we change driver to "Postgre" , it will work well

**Comment by enginespot** [comment]
Hi @narfbg 

    for any 3.x version , it can reproduce the bug.

    we find that it is a bug of PDO driver 

    https://bugs.php.net/bug.php?id=74220

    there are three options to solve the problem 
1. use prepared statements (i.e. use :name or ? placeholder, etc.)
2. set the PDO flag PDO::ATTR_EMULATE_PREPARES to true
3. apply pgsql C-Style escape syntax [1], i.e. VALUES(E'\\'':1)

I tried the option 2 , it should work well , but for database.php ,  there is no setting , what I can do is hook the code , so can you help to find which one is ok for CI framework

**Comment by TrendAlan** [comment]
any update?

**Comment by narfbg** [comment]
Well, we really can't do anything about this.

Let it be a lesson that PDO isn't the magic unicorn that all the propaganda out there makes it to be.
