### ISSUE TITLE
$this->db->from() puts wrong double quotes which are not tables or aliases

### ISSUE THREAD

**Issue by ko2in** [bcit-ci/CodeIgniter#5673]
`$this->db->from()` puts the double quotes incorrectly when passing the sub query statement. Example, I've the sub query as below:

> SELECT "job".*, row_to_json(sr.*) As service, row_to_json(sa.*) AS subject_area, row_to_json(sf.*) AS software, row_to_json(jt.*) AS job_type, row_to_json(js.*) AS job_status, row_to_json(vu.*) AS volume_unit, ( SELECT row_to_json(language.*) FROM language WHERE id IN ( SELECT source_language FROM job_language_pairs WHERE job_language_pairs.job_id = job.id ) ) AS source_language, ( SELECT to_json(array_agg(language.*)) FROM language WHERE id IN ( SELECT target_language FROM job_language_pairs WHERE job_language_pairs.job_id = job.id ) ) AS target_languages, row_to_json(v.*) AS poster, row_to_json(va.*) AS poster_address, row_to_json(vc.*) AS poster_contact FROM "job" LEFT JOIN "job_language_pairs" ON "job_language_pairs"."job_id" = "job"."id" LEFT JOIN (SELECT translation_service.* FROM translation_service) AS sr ON "sr"."id" = "job"."service_id" LEFT JOIN (SELECT subject_area.* FROM subject_area) AS sa ON "sa"."id" = "job"."subject_id" LEFT JOIN (SELECT software.* FROM software) AS sf ON "sf"."id" = "job"."software_id" LEFT JOIN (SELECT volume_unit.* FROM volume_unit) AS vu ON "vu"."name_singular" = "job"."volume_unit" INNER JOIN (SELECT job_type.* FROM job_type) AS jt ON "jt"."id" = "job"."job_type" INNER JOIN (SELECT job_status.* FROM job_status) AS js ON "js"."id" = "job"."job_status" LEFT JOIN (SELECT vendor.* FROM vendor) AS v ON "v"."id" = "job"."posted_by" LEFT JOIN (SELECT vendor_address.* FROM vendor_address) AS va ON "va"."vendor_id" = "job"."posted_by" LEFT JOIN (SELECT vendor_contact.* FROM vendor_contact) AS vc ON "vc"."vendor_id" = "job"."posted_by" WHERE "job_language_pairs"."source_language" = 1 GROUP BY "job"."id", "sr".*, "sa".*, "sf".*, "jt".*, "js".*, "vu".*, "v".*, "va".*, "vc".* ORDER BY "job"."title" ASC, "job"."id" DESC

And I pass this into `$this->db->from()` method as below.

```
$this->db->select('COUNT(*) AS job_count', false);
$this->db->from("(" . $sql . ") AS job_table", false);
```
`$sql` stores the sub query string as described above. When I check the query with `$this->db->get_compiled_select()`, I've the following query statement.

> SELECT COUNT(*) AS job_count FROM (SELECT "job".*, row_to_json(sr.*) As service, row_to_json(sa.*) AS subject_area, row_to_json(sf.*) AS software, row_to_json(jt.*) AS job_type, row_to_json(js.*) AS job_status, row_to_json(vu.*) AS volume_unit, ( SELECT row_to_json(language.*) FROM language WHERE id IN ( SELECT source_language FROM job_language_pairs WHERE job_language_pairs.job_id = job.id ) ) AS source_language, ( SELECT to_json(array_agg(language.*)) FROM language WHERE id IN ( SELECT target_language FROM job_language_pairs WHERE job_language_pairs.job_id = job.id ) ) AS target_languages, row_to_json(v.*) AS poster, row_to_json(va.*) AS poster_address, row_to_json(vc.*) AS poster_contact FROM "job" LEFT JOIN "job_language_pairs" ON "job_language_pairs"."job_id" = "job"."id" LEFT JOIN (SELECT translation_service.* FROM translation_service) AS sr ON "sr"."id" = "job"."service_id" LEFT JOIN (SELECT subject_area.* FROM subject_area) AS sa ON "sa"."id" = "job"."subject_id" LEFT JOIN (SELECT software.* FROM software) AS sf ON "sf"."id" = "job"."software_id" LEFT JOIN (SELECT volume_unit.* FROM volume_unit) AS vu ON "vu"."name_singular" = "job"."volume_unit" INNER JOIN (SELECT job_type.* FROM job_type) AS jt ON "jt"."id" = "job"."job_type" INNER JOIN (SELECT job_status.* FROM job_status) AS js ON "js"."id" = "job"."job_status" LEFT JOIN (SELECT vendor.* FROM vendor) AS v ON "v"."id" = "job"."posted_by" LEFT JOIN (SELECT vendor_address.* FROM vendor_address) AS va ON "va"."vendor_id" = "job"."posted_by" LEFT JOIN (SELECT vendor_contact.* FROM vendor_contact) AS vc ON "vc"."vendor_id" = "job"."posted_by" WHERE "job_language_pairs"."source_language" = 39 GROUP BY "job"."id", "sr".*, "sa".*, "sf".*, "jt".*, "js".*, "vu".*, "v".*, "va".*, "vc".* ORDER BY "job"."title" "ASC", "job"."id" DESC) AS job_table

We can see that there is double quote automatically puts to the order by flag **ASC** whereas the next order by flag **DESC** has no double quotes, at the end of the query.

This makes the query failed and returns the error when `$this->db->get()` method runs. I think there is a bug in query builder when automatically put the quotes to the table names and aliases.

`$this->db->query()` method has no problem. I've to write as below for workaround solution at the moment.
```
$sql = "SELECT COUNT(*) AS job_count FROM (" . $sql . ") AS job_table";
$this->db->query($sql);
```

Edited: I'm using PostgreSQL 9.5 with CI 3.1.9.

**Comment by narfbg** [comment]
Unfortunately, the issue searching is horrible when you look for "from", so I can't find older duplicates of this, but it has come up before. And the answer is simply that `from()` only accepts table names and the query builder isn't made to be used like you're trying to.

Especially with the example that you've provided ... When you've already written 10+ lines of SQL just for your `FROM` clause, that already beats the purpose of using a Query Builder in the first place.

Your "workaround" is what you're supposed to do.
