### ISSUE TITLE
Captcha Helper

### ISSUE THREAD

**Issue by akarupt** [bcit-ci/CodeIgniter#5674]
On new implementation of base64.

https://github.com/bcit-ci/CodeIgniter/blob/develop/system/helpers/captcha_helper.php

On Return you are using $now that not been assigned on base64 option.

**Comment by akarupt** [comment]
Change to 

$now = microtime(TRUE);
		
		if ($img_url !== '' OR $img_path !== '')
		{
			if ($img_path === '' OR $img_url === '' OR ! is_dir($img_path) OR ! is_really_writable($img_path))
			{
				return FALSE;
			}

			/**
			 * Remove old images
			 */
			
			$current_dir = @opendir($img_path);
			while ($filename = @readdir($current_dir))
			{
				if (preg_match('#^(?<ts>\d{10})\.png$#', $filename, $match) && ($match['ts'] + $expiration) < $now)
				{
					@unlink($img_path.$filename);
				}
			}

			@closedir($current_dir);

			// This variable will later be used later to determine whether we write to disk or output a data:image URI
			$img_filename = $now.'.png';
		}
		else
		{
			$img_filename = NULL;
		}

**Comment by narfbg** [comment]
Man, you're making this hard to understand ... It would've been way less confusing if you *only* said this:

> On Return you are using $now that not been assigned on base64 option.
