### ISSUE TITLE
Severity: error --> Exception: Call to a member function quote() on boolean system/database/drivers/pdo/pdo_driver.php 234

### ISSUE THREAD

**Issue by imabot2** [bcit-ci/CodeIgniter#5682]
I sometime get the following error in the CodeIgniter error log files : 

ERROR - 2019-01-21 01:12:35 --> Unable to connect to the database
ERROR - 2019-01-21 01:12:36 --> Severity: error --> Exception: Call to a member function quote() on boolean mysite/system/database/drivers/pdo/pdo_driver.php 234

It rarely happens, but happens sometimes. I guess that if the PDO driver can't connect to the database, there is no retry. So the page will display an error.

**Comment by maxcreate** [comment]
I've just found the same error in the error log:

Error: Call to a member function quote() on boolean
9 ci_system/database/drivers/pdo/pdo_driver.php(234): _escape_str
8 ci_system/database/DB_driver.php(1143): escape_str
7 ci_system/database/DB_driver.php(1108): escape
6 ci_system/database/DB_query_builder.php(683): _wh
5 ci_system/database/DB_query_builder.php(623): where
