### ISSUE TITLE
Use of undefined constant on ICONV_ENABLED and MB_ENABLED

### ISSUE THREAD

**Issue by cdevroe** [bcit-ci/CodeIgniter#5686]
Hello! I get a PHP Warning on 3.1.10 on this line:

https://github.com/bcit-ci/CodeIgniter/blob/807f43b65d6b3fc35e8fed6fce1add36971f9f51/system/core/Utf8.php#L64

I've managed to "fix" the issue for myself by defining these constants in my config. But obviously this isn't what I should be doing. I searched yesterday and today and haven't found anyone else reporting this issue.

Am I alone? Is my local PHP configuration poorly configured? Thanks in advance.

**Comment by cdevroe** [comment]
Oh, and a side note of something somewhat related that I've discovered. The Utf8 library has no documentation in the User Guide for version 2.x or 3.x. I never noticed.

**Comment by narfbg** [comment]
https://github.com/bcit-ci/CodeIgniter/blob/3.1.10/system/core/CodeIgniter.php#L230

The only way you don't have these constants declared is if you've modified our code.
