### ISSUE TITLE
failValidationError($description)

### ISSUE THREAD

**Issue by vebomedia** [bcit-ci/CodeIgniter#5688]
$description type must be  (mixed)  type.. according to description 

https://codeigniter4.github.io/CodeIgniter4/outgoing/api_responses.html#failValidationError

but function accept only string..

return $this->failValidationError($validation->getErrors());

doesn't work because of this issue.

**Comment by narfbg** [comment]
This is the CI3 repository; report this to https://github.com/codeigniter4/CodeIgniter4.

**Comment by vebomedia** [comment]
ups sorry.
