### ISSUE TITLE
Custom Error Log In CodeIgnitor

### ISSUE THREAD

**Issue by akkeSingh** [bcit-ci/CodeIgniter#5695]
I have observed an issue with codeignitor db_query and loader file in the core files. 
If we ask to load any view file which does not present in the web folder then it will not provide any log in the log file location as there is no log_message in that function and it is being handled by the function so I the user puts try catch or error logging it will not generate any log as the script ended gracefully.  

On the other side in query builder class if there is any query error again it will just log that message and display the error but let if the user wants the custom logs like with error, he want to log few session variables.The user has to change the core function for the query_builder.
I think to avoid this we should also throw the appropriate Throwable object so that the user can customise the use if he wants otherwise the core logging will work

**Comment by narfbg** [comment]
> I have observed an issue with codeignitor db_query and loader file in the core files.

It's CodeIgnit**e**r.

> If we ask to load any view file which does not present in the web folder then it will not provide any log in the log file location as there is no log_message in that function and it is being handled by the function so I the user puts try catch or error logging it will not generate any log as the script ended gracefully.

Man ... I had to read this 3 times and I still barely understand what you're trying to say. Yes, there's no log message but there's an entire error screen triggered when you try to load a non-existing view.

> On the other side in query builder class if there is any query error again it will just log that message and display the error but let if the user wants the custom logs like with error, he want to log few session variables.The user has to change the core function for the query_builder.

Again, I barely understand what you're trying to say, and again I don't see a problem.

> I think to avoid this we should also throw the appropriate Throwable object so that the user can customise the use if he wants otherwise the core logging will work

To avoid what?

**Comment by akkeSingh** [comment]
Let me give a clear scenario 
suppose we provide the table name and view page name dynamically by the session and if something among the both is wrong(either a wrong table or a view page) so just to get the error log, we have to add a log message in the view and change the log message(custom log message) in the query builder. which will change the log message for every query.

To Avoid this we should throw a Throwable(Exception) object on such errors(wrong query) so that developer can catch it in try and catch block and provide his own custom log.
With this we can add the as many different custom log even for every function(depending on the need).

Please let me know if the scenario if clear?

**Comment by narfbg** [comment]
Quite ridiculous, but clearer, yes. I have to say, custom logs are probably the weakest argument for exceptions.

But regardless, transforming all error conditions to exceptions is a plan that we're already committed to for version 3.2.0. See #4189 for example.
