### ISSUE TITLE
if mysql's sql_mode is ANSI,mysqli driver can't use

### ISSUE THREAD

**Issue by Zhucola** [bcit-ci/CodeIgniter#5696]
mysql> set global sql_mode = ANSI;

in php:
$this->database("mysqli://root:root@localhost/test?");

in file:
system/database/drivers/mysqli/mysqli_drivers，lines143 or 147

if mysql's sql_mode  is ANSI,can't use " ,only can use '

**Comment by narfbg** [comment]
Can't reproduce.
