### ISSUE TITLE
$this->database(''mysqli://root:abc@localhost/test?stricton=false'),in CI_DB_mysqli_driver class $this->stricton is not boolean

### ISSUE THREAD

**Issue by Zhucola** [bcit-ci/CodeIgniter#5697]
if I not use stricton sql_mode:
$this->database(''mysqli://root:abc@localhost/test?stricton=false')

buy,in system/database/DB.php line 138:
$val = var_export($val, TRUE);
}
$params[$key] = $val;
...
$driver = 'CI_DB_'.$params['dbdriver'].'_driver';
$DB = new $driver($params);

so,$this->stricton is 'false',is string,not boolean

so in file system/database/drivers/mysqli/mysqli_driver.php line 141
if ($this->stricton)   will  true

**Comment by narfbg** [comment]
Yes ... It's not magic.

My advice - use proper configuration files, these connection strings are only for quick and dirty tests.
