### ISSUE TITLE
set_update_batch how to plus 1

### ISSUE THREAD

**Issue by sanlingnet** [bcit-ci/CodeIgniter#5700]
$data = array(
    		array(
    			'id' => 5,
    			'name' => 'test',
    			'visit' => '`visit` + 1'
    		),
    		array(
    			'id' => 7,
    			'name' => 'wang',
    			'visit' => '`visit` + 1'
    		)
    	);

$this->Test_model->set_update_batch($data, 'visit', false);
$this->Test_model->update_batch('table', $data, 'id');

but is don't work。
when use
$update = array(
    			'id' => 7,
    			'name' => 'wang',
    		);
$this->Test_model->set('visit' , 'visit + 1', false)->update($data);

it's OK ,can you help me how to use set_update_batch and update_batch

**Comment by narfbg** [comment]
This is a bug tracker. Please ask your questions on our [forums](https://forum.codeigniter.com/) instead.
