### ISSUE TITLE
how to use pconnect in my project？

### ISSUE THREAD

**Issue by 582727501** [bcit-ci/CodeIgniter#5702]
reconnect()
Returns: TRUE on success, FALSE on failure
Return type: bool

if the reconnect() function has set return true.
when the project use pconnect,  do we need to determine whether the connection is valid and then call the reconnect function to reconnect the database?  Or we don't need to do this.  will  the framework do this automatically？

**Comment by 582727501** [comment]
pdo pconnect 如何做reconnect

**Comment by jim-parry** [comment]
Support questions should be asked on our [forum](https://forum.codeigniter.com/index.php), thanks.
