### ISSUE TITLE
Cart.php allows you to enter negative numbers of Qty

### ISSUE THREAD

**Issue by eamax** [bcit-ci/CodeIgniter#5705]
```
if ($items['qty'] == 0)
{
   unset($this->_cart_contents[$items['rowid']]);
   return TRUE;
}
```

Qty allows you to enter negative numbers, creating discounts in the shopping cart.
"<=" solves the problem.

**Comment by jim-parry** [comment]
The shopping cart was deprecated, and abandoned in Dec 2016.
https://github.com/bcit-ci/ci3-cart-library
