### ISSUE TITLE
update_batch bugs

### ISSUE THREAD

**Issue by sanlingnet** [bcit-ci/CodeIgniter#5709]
when i want use update_batch parameter visit => visit + 1,it's work

> public function update_batch($table, $set = NULL, $index = NULL, $key = NULL, $escape = NULL, $batch_size = 100)
	{
		// Combine any cached components with the current statements
		$this->_merge_cache();

		if ($index === NULL)
		{
			return ($this->db_debug) ? $this->display_error('db_must_use_index') : FALSE;
		}

		if ($set === NULL)
		{
			if (empty($this->qb_set_ub))
			{
				return ($this->db_debug) ? $this->display_error('db_must_use_set') : FALSE;
			}
		}
		else
		{
			if (empty($set))
			{
				return ($this->db_debug) ? $this->display_error('update_batch() called with no data') : FALSE;
			}

			$this->set_update_batch($set, $index, $key, $escape);
		}

		if (strlen($table) === 0)
		{
			if ( ! isset($this->qb_from[0]))
			{
				return ($this->db_debug) ? $this->display_error('db_must_set_table') : FALSE;
			}

			$table = $this->qb_from[0];
		}

		// Batch this baby
		$affected_rows = 0;
		for ($i = 0, $total = count($this->qb_set_ub); $i < $total; $i += $batch_size)
		{
			if ($this->query($this->_update_batch($this->protect_identifiers($table, TRUE, NULL, FALSE), array_slice($this->qb_set_ub, $i, $batch_size), $index)))
			{
				$affected_rows += $this->affected_rows();
			}

			$this->qb_where = array();
		}

		$this->_reset_write();
		return $affected_rows;
	}

`	public function set_update_batch($key, $index = '', $keys = null,  $escape = NULL)
	{
		$key = $this->_object_to_array_batch($key);

		if ( ! is_array($key))
		{
			// @todo error
		}

		is_bool($escape) OR $escape = $this->_protect_identifiers;

		foreach ($key as $k => $v)
		{
			$index_set = FALSE;
			$clean = array();
			foreach ($v as $k2 => $v2)
			{
				if ($k2 === $index)
				{
					$index_set = TRUE;
				}

				$clean[$k2] = array(
					'field'  => $this->protect_identifiers($k2, FALSE, ($keys == $k2 ? $escape : NULL)),
					'value'  => (($escape === FALSE && $keys == $k2) ? $v2 : $this->escape($v2))
				);
			}

			if ($index_set === FALSE)
			{
				return $this->display_error('db_batch_missing_index');
			}

			$this->qb_set_ub[] = $clean;
		}

		return $this;
	}`

**Comment by sanlingnet** [comment]
how to use : 
table : table NAME
set   : array()
$index : update key
$key   : update escape key
$escape : fasle

$this->db->update_batch('tabel', array(), 'id', 'visit', false);

**Comment by narfbg** [comment]
What? This isn't a bug description.

Please use words, you can't just throw in entire functions and expect anyone to understand what's going on.

**Comment by sanlingnet** [comment]
when i use
`        $data = array(
            array(
                'id'         => 5,
                'domainName' => 'facebook.com',
                'view'       => '`view` + 1'
            ),
            array(
                'id'        => 7,
                'domainName' => 'souicp.com',
                'view'      => '`view` + 1'
            )
        );
        $this->db->set_update_batch($data, 'view', false);
        $this->db->update_batch('icp', $data, 'id'); 
        echo $this->db->last_query();die; `
isn't work

**Comment by sanlingnet** [comment]
you can see https://forum.codeigniter.com/thread-72902.html

**Comment by narfbg** [comment]
This isn't a bug, it's a natural limitation ... Inputs that are expected to be string literals cannot be treated as arbitrary SQL; that might even be an SQL injection.
