### ISSUE TITLE
Memory leak when using db persistent connections

### ISSUE THREAD

**Issue by joanhey** [bcit-ci/CodeIgniter#5710]
We need to disable db persistent connections in the benchmark.
It's the only php framework using it that have this problem.

https://github.com/TechEmpower/FrameworkBenchmarks/pull/4514

Also fail in local using vagrant, so it's easy to test.

PD: Feel free to update the codeigniter code in the benchmark
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/PHP/codeigniter

**Comment by narfbg** [comment]
I'm sorry, but what are we supposed to do with this? You've provided zero details and we can't control how persistent connections work anyway ... It's not like we do something specai with them; we just switch `*_connect()` with `*_pconnect()` where applicable.

**Comment by joanhey** [comment]
Are you still using this fix #1265 ?

**Comment by narfbg** [comment]
Yes, that patch is still in effect. But what difference does that make? Closing a persistent connection makes no sense ... Maybe it would eliminate errors from your test results, but it wouldn't actually solve any real problem.

**Comment by joanhey** [comment]
Fixed in the last version.
