### ISSUE TITLE
Failed to decode session object 

### ISSUE THREAD

**Issue by imabot2** [bcit-ci/CodeIgniter#5713]
Not sure this is a bug, but I am sometime experiencing the following issue with CodeIgniter:

`ERROR - 2019-03-05 19:57:26 --> Severity: Warning --> session_start(): Failed to decode session object. Session has been destroyed /system/libraries/Session/Session.php 143
`

This error appears in my server log and is impossible to artificially replicate.

Here are my session configuration (in application/config/config.php)

$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

Any ideas what could be the roots of that problem and/or where to start ?

**Comment by narfbg** [comment]
We don't control the encoding/decoding process; if this is caused by a bug, it's in PHP itself and we can't do anything about it.
