### ISSUE TITLE
 touch(): Utime failed: Cannot allocate memory

### ISSUE THREAD

**Issue by taillis** [bcit-ci/CodeIgniter#5715]
I moved my application to a new server, which is php 7.2. Now I'm getting the following error

A PHP Error was encountered
Severity: Warning
Message:  touch(): Utime failed: Cannot allocate memory
Filename: drivers/Session_files_driver.php
Line Number: 250
Backtrace:

A PHP Error was encountered
Severity: Warning
Message:  session_write_close(): Failed to write session data using user defined save handler. (session.save_path: /var/www/helpdesk.veredastecnologia/application/cache/session)
Filename: Unknown
Line Number: 0
Backtrace:

Maybe someone can help me, I already made some research, but no success.

**Comment by narfbg** [comment]
`touch()` is a native PHP function outside of our control.

Given that it deals with filesystems on a low level, I can only guess it's possible that some (maybe over-aggressive security) restrictions on your server can cause this.
