### ISSUE TITLE
affected_rows() return zero on successfull update

### ISSUE THREAD

**Issue by psuplat** [bcit-ci/CodeIgniter#5718]
Latest CI, MySQL 8.0.5

Example DB table1:
```
---------------------------------
|  id  |         title          |
---------------------------------
|  1   | Some random title      |
---------------------------------
```

When I run update like this:
`$this->db->set('title','New random title')->where('id',1)->update('table1');`

it works fine and the` $this->db->affected_rows()` returns 1

but if I run update like that:
`$this->db->set('title','Some random title')->where('id',1)->update('table1');`

essentially replacing the title value with the exact same text the affected_rows() returns 0

there is no mention of such behaviour in docs, so I am not sure if I am missing something here or is this actually a bug

**Comment by michalsn** [comment]
From database driver reference for `affected_rows()`:

> Returns the number of rows changed by the last executed query.

https://codeigniter.com/user_guide/database/db_driver_reference.html?highlight=affected_rows#CI_DB_driver::affected_rows

**Comment by psuplat** [comment]
So what is the definition of _change_ here? If you run the same query directly on the database it returns that the query was successful with 1 row affected. It does not care if the values are the same before or after, update is an update.

**Comment by michalsn** [comment]
> For UPDATE statements, the affected-rows value by default is the number of rows actually changed. If you specify the CLIENT_FOUND_ROWS flag to mysql_real_connect() when connecting to mysqld, the affected-rows value is the number of rows “found”; that is, matched by the WHERE clause. 

https://dev.mysql.com/doc/refman/8.0/en/mysql-affected-rows.html

**Comment by psuplat** [comment]
Ok, now I understand. Thank you @michalsn

**Comment by michalsn** [comment]
That's great. 
In the future, please ask such questions on the forum. 
Because otherwise **narfbg** will gonna kill us both ;)
