### ISSUE TITLE
Postgres: SELECT * with no tables specified is not valid

### ISSUE THREAD

**Issue by jurisjansons** [bcit-ci/CodeIgniter#5721]
Postgres driver throws error when executing this query. 

```
    $this->db->select("sites.id, sites.name");
    $this->db->from("users");
    $this->db->join("sites", "sites.parent_id = users.parent_id");
    $this->db->join("sites_to_users", "sites_to_users.site_id = sites.id AND sites_to_users.user_id != $id");
    $this->db->where("users.id", $id);

    $query = $this->db->get();

    return $query->result();
```

Other queries with joins work. Tried everything after `SELECT` statement, without any luck. Same query printed with `$this->db->get_compiled_select()` and executed in postgres works. Query also works if all quotes are removed and query passed with `$this->db->query($query)`.  That's my workaround for now.

Error: 
*Severity: Warning*
_Message: pg_query(): Query failed: ERROR: SELECT * with no tables specified is not valid LINE 1: SELECT * ^_
*Filename: postgre/postgre_driver.php*
*Line Number: 242*

**Comment by jurisjansons** [comment]
Sorry, query didn't make any sense and works when modified, but anyway did work when executed in postgres

**Comment by RiksaParadilaPasa** [comment]
masalah yang sama, ada yang memecahkan masalah ini?

**Comment by FLAPHYSINGH** [comment]
thy this way
               $this->db->select( 'role,roleid');
		#$this->db->select('*');
               #$this->db->select( "role","roleid");
		$this->db->from('tbl_roles');
		$query = $this->db->get();
		if($query->num_rows() > 0){
			$results = $query->result_array();
		}
		return $results;
