### ISSUE TITLE
Unable to load the requested language file: language/english/_lang.php

### ISSUE THREAD

**Issue by AleSanchez1979** [bcit-ci/CodeIgniter#5726]
I was trying to implement language support in Codeigniter. 
Any controller will throw this error.

**Comment by jim-parry** [comment]
This is a support question, and should be asked on the forum.
Why are you trying to load "_lang"? That isn't one of the language files.

**Comment by jim-parry** [comment]
See https://www.codeigniter.com/user_guide/libraries/language.html
"_lang" is a suffix for a package language file, and not used on its own.

**Comment by AleSanchez1979** [comment]
> This is a support question, and should be asked on the forum.
> Why are you trying to load "_lang"? That isn't one of the language files.

I'm sorry, i will repost it in the forum.
