### ISSUE TITLE
CI_Email ignores Return-Path when sending via SMTP

### ISSUE THREAD

**Issue by fabsn182** [bcit-ci/CodeIgniter#5734]
When sending emails using an SMTP connection, the server will ignore the `Return-Path:` set in the mail header.
The reason is that a SMTP connection uses the command `MAIL FROM:<foo@bar.tld>` to set the Return Path itself

Solution:
Change `system/libraries/Email.php:1969` from
```php
if ( ! $this->_send_command('from', $this->clean_email($this->_headers['From'])))
```
to
```php
if ( ! $this->_send_command('from', $this->clean_email(!empty($this->_headers['Return-Path']) ? $this->_headers['Return-Path'] : $this->_headers['From'])))
```

This will only change the Return-Path of undeliverable mails. The "From:"-address - set in `$this->email->from()` - will still be part of the mail header and is displayed as the sender-address in the recipients mail client

**Comment by narfbg** [comment]
How would the original "From" would still be included if you replace it with the "Return-Path" value?

Also, [RFC 5321](https://tools.ietf.org/html/rfc5321) explains that generating `Return-Path` is the job of the server and we shouldn't send it at all, so I'm rather rather thinking we should change that instead ...

**Comment by fabsn182** [comment]
The SMTP Server still sets the corret `From` because it is part of
```php
$this->_header_str
```
that gets sent in `system/libraries/Email.php:2015`:

```php
$this->_send_data($this->_header_str.preg_replace('/^\./m', '..$1', $this->_finalbody));
```

Also - as far as I know - there is no other way to set the `Return-Path` because the **last** answering Server in the whole proccess is the one setting it. And what is used for this is the SMTP Command `MAIL FROM:`.

Maybe I'll find the time to set up a test-environment for you (and others) to see how sending mails using a SMTP-connection ignores the Return-Path without these changes.

If you don't think the change is necessary, maybe a hint in the documentation might be helpful.

**Comment by narfbg** [comment]
I see ... That's rather hacky though.

Anyway, I'm not questioning that `Return-Path` is getting ignored, no need to setup test environments. What I'm questioning is why should we work around that if the SMTP standard clearly states that it's not our job.

**Comment by fabsn182** [comment]
For me, this "hacky" behaviour is clearly what users (in this case: me and clients of my company) want: set an email adress where all bounces will return to, but don't show this address in the `Form:`-section in the recipients email client.

Afaik, every newsletter-service uses this logic to catch bounces but still show the senders address.

But as I said: if that's to hacky to be patched (imho it is not), maybe just update the docs and inform the developer about the fact, that the `return_path`-parameter of `$this->email->from()` will be ignored when sending via smtp.

**Comment by narfbg** [comment]
Alright, I'll give it some more thought before I decide. I'm leaning towards updating the docs as you suggested though.

**Comment by narfbg** [comment]
Ha, turns out a note about this in the docs for `from()` already does exist. And the emails docs haven't been touched in 5 years. :laughing:
