### ISSUE TITLE
Email library: passing `to`s as comma separated string

### ISSUE THREAD

**Issue by AresAndy** [bcit-ci/CodeIgniter#5736]
Hello,

I've noticed that when passing a comma-delimited string of `$this->email->to()`s, if a space between the two email is omitted, the regex fails to separate the addresses.

On the documentation page, there is written:
> can be a single e-mail, a comma-delimited list or an array.

So a space should not be necessary, right? May I propose to use `explode` instead of a regex?
Or more easily highlight that a space between the comma and the next address is necessary.

Thanks

**Comment by narfbg** [comment]
Looking at the code, I can't see why such a thing would happen and testing `CI_Email::_str_to_array()` I can't reproduce it either ...
