### ISSUE TITLE
Discrepancies with permitted URI characters

### ISSUE THREAD

**Issue by aidanthewiz** [bcit-ci/CodeIgniter#5737]
I've been using CodeIgniter for a while but every time I set up a new project I notice that there are a few discrepancies with what URI characters are allowed by default.

In the actual config field, it reads:
`$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';`

However, in the comment section above the config entry:
`| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-`
as well as in the [security documentation](https://www.codeigniter.com/userguide3/general/security.html), it does not contain `\`.

I am mostly ceratin that `\` should be a permitted uri char, however I will leave it up to the CodeIgniter team to analyze this discrepancy.

**Comment by narfbg** [comment]
There's no discrepancy, the backslash is an escaping character.
