### ISSUE TITLE
Redis driver performance issues

### ISSUE THREAD

**Issue by exussum12** [bcit-ci/CodeIgniter#5738]
CodeIgnter tries to keep a cache of all objects it knows is serialized and handle it PHP side. This causes 2 issues.

1 - On Redis this is a o(1) operation, which is very quick, but populating the array makes it o(n) so large amounts of keys in this array slowly slow the application down. 

2- This value is stored in another cache key with a TTL of 0, and slowly grows over time too due to naturally expiring keys not losing their corresponding cache array.

Under a default instance of redis issue 2 the key will grow large enough to stop redis working, but if you change the eviction policy to `allkeys-lru` to make redis behave a little more like memcache then the large cache key can be evicted leaving everything in cache effectively broken as it returns serialized strings rather then the arrays / objects expected 

Just wondering what the thoughts are on removing the the `_ci_redis_serialized`. An alternative option would be using `$this->_redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);` - I assume this wasnt used due to suspected performance issues?

Could use IGBinary but that has issues with incr and decr which would mean doing that client side, which could be breaking (splitting an atomic operation) ?

Happy to submit a PR with that I have now which is basically just adding the serliize option for all data types but having the redis library handle it rather than doing it manually

**Comment by narfbg** [comment]
I replied to the PR, but the problem seems to be that the `_ci_redis_serialized` array grows indefinitely, so why not just solve that?

**Comment by exussum12** [comment]
Because that can still disappear randomly. None of the other cache drivers do similar so I'm not sure why redis is different ?

**Comment by exussum12** [comment]
Also the performance issue still happens regardless of if it's limited. It gets slower and slower over time. Ever over a smallish number of items

**Comment by narfbg** [comment]
> None of the other cache drivers do similar so I'm not sure why redis is different ?

To be honest, I don't know. I'm not really familiar with Redis and this solution was provided by a contributor via pull request (the Redis driver didn't have serialization originally).

**Comment by exussum12** [comment]
The standard way to do the serialisation is for the driver to handle it. 

As it's already serialised in redis this change should be safe to deploy with a warm cache. There are other serialisation options available but this would mean deploying and then flushing all cache which may be problematic

**Comment by narfbg** [comment]
Should've closed this together with #5739.
