### ISSUE TITLE
Email message_id must be unique

### ISSUE THREAD

**Issue by nicojongejan** [bcit-ci/CodeIgniter#5745]
I was having problems that email that was send was mark as spam.
The cause of this was the message_id so I made a fix for this.

it would be nice to fix this in the email library.

`
class MY_Email extends CI_Email{
	/**
	 * Get the Message ID
	 *
	 * @return	string
	 */
	protected function _get_message_id()
	{
		$from = str_replace(array('>', '<'), '', $this->_headers['Return-Path']);
		/**
		* @author Nico Jongejan Hi-control
		* The message_id for an e-mail must be unique fot every e-mail.
		* there for we use ad md5 combination from time() and $from instate of an uniqid.
		* á uniqid is not always unique, that way it will be seen as spam 
		*/
		// return '<'.uniqid('').strstr($from, '@').'>';
		return '<'.md5(time().$from).strstr($from, '@').'>';
	}
}
`
For the time you can use this.

**Comment by narfbg** [comment]
Sorry for the late response.

Aside from the hard to read formatting, I can still see a potential problem with your solution - batch emails will easily be sent (if not all of them generated) in multiples per second, in which case obviously they'd have the same ID based on your `time()` solution.

Perhaps if you explain the problem in a bit more detail first, we can come up with a better solution.
