### ISSUE TITLE
Validation with get not show error message

### ISSUE THREAD

**Issue by cnakh** [bcit-ci/CodeIgniter#5746]
I created validation with REST_Controller but I can't get the error message even it return `FALSE`. Below is my validation codes.

 ```
$this->load->library('form_validation');
$rules = array(
    array(
        'field' => 'username',
        'label' => 'Username',
        'rules' => 'required',
        'errors' => array(
            'required' => "MESSAGE"
        )
    )
);
$this->form_validation->set_data($this->get());
$this->form_validation->set_rules($rules);

if ($this->form_validation->run() == FALSE) {
    var_dump($this->form_validation->error_array());
}
```
The result is empty array `array(0) { }`

**Comment by aimflaiims** [comment]
Have you tried using $this->input->get() instead of $this->get()

**Comment by narfbg** [comment]
This is a natural side-effect with "empty" GET requests - with no inputs provided, we can only assume no form was submitted. The alternative of triggering validation errors on each page request is much more inconvenient.

**Comment by cnakh** [comment]
So the validation is only form submitted?

I think validate for GET request should possible and I used `$this->form_validation->set_data` from GET request. It is empty, `$this->form_validation->run()` should `false` and return `message`.

It just my opinion, but I already decided another way to validate it.
