### ISSUE TITLE
Database error has status code 200

### ISSUE THREAD

**Issue by rmertens** [bcit-ci/CodeIgniter#5750]
We were experiencing some database problems in production.

We have this setting:
```ini_set('display_errors', 0);```

When a database error occurs we would not expect a 200 HTTP status code, but something like a 503 (we care, because our reverse proxy decides to cache pages based on status code).

**Comment by narfbg** [comment]
Our error handler defaults to a 500 status code, so at first glance I don't even see how your problem would occur. Please provide an example scenario with more details, something that we can actually test for.

**Comment by rmertens** [comment]
Sounds like this: https://bugs.php.net/bug.php?id=50921 so I guess it's not related to CodeIgniter. Closing this.
