### ISSUE TITLE
CI_Form_validation valid_url bugs

### ISSUE THREAD

**Issue by b1tc0re** [bcit-ci/CodeIgniter#5755]
If you send a number greater than 0 for verification, the method will always return true

`$this->form_validation->valid_url('1')`

**Comment by narfbg** [comment]
You should report this on bugs.php.net as well; we rely on PHP's `filter_var()` and `FILTER_VALIDATE_URL` ...

**Comment by b1tc0re** [comment]
`$this->form_validation->valid_url(true)` is true
`$this->form_validation->valid_url(1)` is true

**Comment by narfbg** [comment]
Inputs are always strings or null.
