### ISSUE TITLE
Bootstrap invalid-feedback html for form_input helper

### ISSUE THREAD

**Issue by gabrodhic** [bcit-ci/CodeIgniter#5758]
I created this function(_form_input)(notice underscore) wrap around form_input function for bootstrap ease of use since codeigniter's  helper doesn't has that extra div line for bootstrap feedback, 
This will add Bootstrap inline message error if there is any instead of all of the errors at the top of the form.

[https://getbootstrap.com/docs/4.3/components/forms/#how-it-works](url)

It will automatically append the class value if needed and if the attribute class is not present(so it doesn't overwrites it)
This function could be merge into form_input.
I'm using this function on a site and it works great.

```
if ( ! function_exists('_form_input'))
{
    function _form_input($field_data)
	{
		$html = form_input($field_data);
		$pattern = '/^(class="(.+)")$/';
		$pattern2 = '/(name="(.+)")/U';
		$valid = 'form-control ';
		$valid .= form_error($field_data['name'])?'is-invalid':'';
		
		if (preg_match($pattern, $html))
		{			
			$html = preg_replace($pattern, 'class="$2'.$valid.'"', $html);			
		}else{
			$valid = ' class="'.$valid.'" ';
			$html = preg_replace($pattern2, '$1'.$valid, $html);			
		}
		$html .= '<div class="invalid-feedback">'.form_error($field_data['name']).'</div>';		 
		return $html;
	}
}
```

**Comment by narfbg** [comment]
Appreciate the effort, but this is a bugtracker, not a place to post random things you've come up with.
