### ISSUE TITLE
[Request Feature] Stop check validation on first error

### ISSUE THREAD

**Issue by plonknimbuzz** [bcit-ci/CodeIgniter#5760]
Reason: `resource efficiency`
Library: `form_validation`
Method: `run`
Version: `3.1.10`

Example:
```
$data = [
  'password'=>'', //empty
  'username'=>'myuser', //taken
  'email' => 'myemail@mail.com', //taken
   'phone'=> '3444' //taken
];
$this->form_validation->set_data($data);
$this->form_validation->set_rules('password', 'Password', 'trim|required'); //should stop here
$this->form_validation->set_rules('username', 'Username', 'trim|required|min_length[5]|max_length[25]|is_unique[users.username]');
$this->form_validation->set_rules('email', 'Phone', 'required|valid_email|is_unique[users.email]');
$this->form_validation->set_rules('phone', 'Phone', 'required|is_unique[users.phone]');

if($!this->form_validation->run()){
 print_r($this->form_validation->error_array());
}else{
  echo 'success';
}

```

**Current:**
Check Database 3 times even password fail first.

**Expected:**
Stop when first validation fail.

Maybe we can add parameter to `run($stopOnFirstError=false)` 

If you agree, i can send pull request about this.
Thanks.

**Comment by narfbg** [comment]
A few things would break with the behavior that you want, like having a complete error array as feedback. I see the value in your suggestion though.

However, if you're going to submit a PR with it, you should implement it as a library configuration option (like `error_prefix` and `error_suffix`).
