### ISSUE TITLE
contributing.md Improvement

### ISSUE THREAD

**Issue by wangch7** [bcit-ci/CodeIgniter#5762]
Problem Description: "How-to Guide" section is not detailed enough to make sure that any contributor (old or new to GitHub) can successfully set up their environment following the nine steps listed. Some contributors can be lacking knowledge of how to run basic GitHub commands.

Solution Description: Add a link of how to perform the basic commands in GitHub. "https://guides.github.com/activities/hello-world/" is a useful one. Other than the content in this link itself, it also contains additional links to guides, on-demand training, tutorial videos, etc.

**Comment by narfbg** [comment]
Aside from the fact that we're not here how to teach people to use git, #5756 should resolve most of your concerns.
