### ISSUE TITLE
CI3 - static code analysis in general and PHPStan in particular

### ISSUE THREAD

**Issue by Tilogorn** [bcit-ci/CodeIgniter#5763]
As my CodeIgniter 3 projects grows bigger and bigger I tried to use a static analyzer on my code base.

The big players afaik are

- [PHPStan](https://github.com/phpstan/phpstan)
- [Phan](https://github.com/phan/phan)
- [Psalm](https://github.com/vimeo/psalm/)

I tried all of them and none was able to follow the CodeIgniter-typical dynamically adding of properties with  `$this->load()`. Take the following example:

```php
class Welcome extends CI_Controller {
    public function index()
    {
        $this->load->model('MyModel');
        $this->MyModel->getAllItems();
        $this->load->view('welcome_message');
    }
}
```
The analyzers complain

1. Property `load` not defined (`CI_Controller` doesn't have a method called `load()`, it gets added dynamically in its constructor)
2. Property `MyModel` not defined -> The concept of `load()` is unknown to the analyzers

I tried to dig deeper with one example so I created a [repo with a MWE](https://github.com/Tilogorn/codeigniter-vanilla-phpstan) and opened an [issue at the PHPStan project](https://github.com/phpstan/phpstan/issues/2132).

As you can read, the guys basically gave up because PHPStan is not able to match a function call over multiple files just because of `$this->load()`. Also `$this->load()` itself is not a regular function of e.g. `CI_Controller`.

So my questions are:
1. Is there any static analyzer you know of that is capable of parsing/loading CodeIgniter code correctly? 
2. Will this behaviour improve with CodeIgniter 4, where - as  far as I can see - PSR4-Autoloading is used instead of `this->load()`?

**Comment by narfbg** [comment]
Well, I read the issue the guys didn't give up ... They [explained the problem and suggested you submit a PR](https://github.com/phpstan/phpstan/issues/2132#issuecomment-494313544) (and the next comment suggests an alternative for you as a user), which would be very simple.
Would you be doing that or would you rather have us do it? Either way is fine.

As for your questions:

1. You should ask this on our [forums](https://forum.codeigniter.com/). For one, this is a bug tracker and we're not here to suggest third-party tools, but also there's a much higher chance someone on the forums has such knowledge, simply because there's a lot more people there as opposed to me and the handful of contributors here.
2. I don't know, I'm not involved in CI4 development. The head dev for it is regular on the forums, so you should find your answer to that there as well.

**Comment by Tilogorn** [comment]
Thank you for your detailed answer. Seems like I have a lot to learn.

> Would you be doing that or would you rather have us do it? Either way is fine.

I misunderstood `define the property with the correct @var type` as introducing a new class variable and heavily impacting your code base. That's why I didn't dig deeper. I would be happy if you do it and reference the commit here, I'm curious about it. Is it done just by adding some more structured comment to the constructor of the class?

> You should ask this on our forums. For one, this is a bug tracker [...]

I completely forgot about the forums. You are totally right. Please excuse any circumstances.

> Also, there's no such thing as $this->load()

Again my apologies, I was probably confused by the whole testing, researching etc. I will pay more attention next time. My intent with the parentheses was to make clear of which `load` I'm talking about. I accidentally archieved the complete opposite ;-)

**Comment by Andrewsuares** [comment]
Hello, can someone please help me out. I have CI3 with HMVC installed. I am in the root directory of CI3.

I've run this command. I want to analyse the modules.
php vendor/bin/phpstan analyse application/modules/

Lots of errors like these.
Reflection error: CI_Model not found.

Is there a different path that I need to use? If I change the command to this line, phpstan hangs.
php vendor/bin/phpstan analyse ./

**Comment by amiranagram** [comment]
Hi @Tilogorn, mind sharing your phpstan config for CI3 and/or any additional plugins you use?

**Comment by Tilogorn** [comment]
@amiranagram: Couldn't get it to work (no time to write the reflections)
