### ISSUE TITLE
CI_Email: passing a string with a german Umlaut and comma creates multiple senders

### ISSUE THREAD

**Issue by fabsn182** [bcit-ci/CodeIgniter#5764]
Assigning a string containing special characters (tested with ö, ä, ü and ß) and at least one comma in the `name`-argument of `CI_Email::from()` (or `reply_to()` results in a comma-separated list of senders which is clearly an unwanted behaviour:

```php
$this->email->from('noreply@domain.tld', 'Doe with öäü, John, also with öäü');
```
->
```
From: =?UTF-8?Q?Doe=20with=20=C3=B6=C3=A4=C3=BC@webserver-doman.tld, =20John@webserver-doman.tld,=20also=20with=20?= =?UTF-8?Q?=C3=B6=C3=A4=C3=BC?= <noreply@domain.tld>
```
`From: Doe with öäü@webserver-doman.tld, John@webserver-doman.tld, also with öäü noreply@domain.tld>`

Omitting the comma (or the Umlaute), the result is correct
```php
$this->email->from('noreply@domain.tld', 'Doe with öäü John also with öäü');
```
->
```
From: =?UTF-8?Q?Doe=20with=20=C3=B6=C3=A4=C3=BC=20John=20also=20with=20=C3=B6?= =?UTF-8?Q?=C3=A4=C3=BC?= <noreply@domain.tld>
```
`From: Doe with öäü John also with öäü <noreply@domain.tld>`

This has something to do with CI_Email's `_prep_q_encoding()`-method but I haven't had the time to dive into it since there happens some iconv-voodoo.

**Comment by sotornien** [comment]
I've got exactly the same issue, but even without special chars:

`
$config = array(
            "protocol" => "mail",
            "mailtype" => "html",
            "charset" => "UTF-8",
            "newline" => "\r\n",
            "crlf" => "\r\n"
        );

        $this->load->library("email", $config);
        $this->email->set_header('MIME-Version', '1.0; charset=utf-8');
        $this->email->set_header('Content-type', 'text/html');

        $this->email->from("shop@mysite.de", "Shop from Mysite");
        $this->email->to($recipient["email"]);
        $this->email->bcc("shop@mysite.de");
        $this->email->subject($recipient['firstName'] . ", your order by Mysite");
        $this->email->message($body);

        print_r($this->email->print_debugger(array('headers')));
`

Result:

> Ihre Nachricht wurde erfolgreich über das folgenden Protokoll verschickt: mail
>
> 
> Date: Sun, 26 May 2019 15:13:53 +0200
> **_MIME-Version: 1.0; charset=utf-8_**
> **_Content-type: text/html_**
> From: "Shop from Mysite" <shop@mysite.de>
> Return-Path: <shop@mysite.de>
> Bcc: shop@mysite.de
> Reply-To: <shop@mysite.de>
> User-Agent: CodeIgniter
> X-Sender: shop@mysite.de
> X-Mailer: CodeIgniter
> X-Priority: 3 (Normal)
> Message-ID: <5cea911172e4a@mysite.de>
> **_Mime-Version: 1.0_**
> **_Content-Type: multipart/alternative; boundary="B_ALT_5cea911172e99"_**
> =?UTF-8?Q?asdf,=20deine=20Bestellu?==?UTF-8?Q?ng=20bei=20A?= =?UTF-8?Q?RGO?=
> This is a multi-part message in MIME format.
> Your email application may not support this format.

Something strange: When using "$this->email->set_header(___);" it is appending to the header instead of overwriting it. In this case I've got 2x the header Content-type and MIME-Version

**Comment by narfbg** [comment]
@fabsn182 This appears really weird and I don't see a reason in the code why it would happen. Which CI version is this on?

@sotornien Sorry mate, what you posted is nothing like the same issue OP described.

**Comment by sotornien** [comment]
@narfbg 

Sure, the recipient get 

> Subject: =?UTF-8?Q?asdf,=20your=20Order=20fro?==?UTF-8?Q?m=20Mysite?=

but as subject, not in the "from" field as discribed from fabsn182. But its the same Issue with the Email Library. CI Version 3.1.9

**Comment by fabsn182** [comment]
@narfbg sorry, totally forgot to reply. This happens with CI 3.1.9.

**Comment by narfbg** [comment]
OK, well ... I can't reproduce this. Unfortunately that doesn't mean much because there's too many environmental variables at play, but I still can't do anything about it if I can't test it myself.

I'll leave the issue open for anyone else able and willing to tackle it.

**Comment by sotornien** [comment]
> 
> 
> OK, well ... I can't reproduce this. 

Not Every E-Mail Client show this incorrect. Outlook for Android seems to be affected. You may can reproduce it also.

@fabsn182 
Can you give us a feedback which of your E-Mail Clients is affected?

**Comment by fabsn182** [comment]
This hasn't anything to do with the email client. The email header is already messed up.

**Comment by ko2in** [comment]
I know this thread is old, but you can solve this by passing charset to your email config as UTF-8 format. Example:
```
$config['charset'] = 'utf8';
```

**Comment by fabsn182** [comment]
First: the correct value would be "UTF-8' and no, this doesn't change the behaviour as I already have this option set to UTF-8.

**Comment by ko2in** [comment]
Well, it does work. Here's my test script.
```
$this->load->library('email');

		$this->email->initialize([
			'charset' => 'utf8'
		]);

		$this->email->from('noreply@localhost.com', 'Doe with öäü, John, also with öäü');
		$this->email->to('johndoe@localhost.com');
		$this->email->subject('Test');
		$this->email->message('Test message');
		$this->email->send(false);

		echo $this->email->print_debugger(['headers']);
```

Here's from my Thunderbird mail client.
![CorrectHeader](https://user-images.githubusercontent.com/930315/87040621-ff81ff00-c216-11ea-8779-abdcced38810.png)

Without charset config.
![BrokenHeader](https://user-images.githubusercontent.com/930315/87040661-0f014800-c217-11ea-98db-6a90e9558952.png)

### Headers
With `$config['charset'] = 'utf8'`:
```
From: =?UTF8?Q?=44=6F=65=20=77=69=74=68=20=C3=B6=C3=A4=C3=BC=2C=20=4A=6F=68=6E?= =?UTF8?Q?=2C=20=61=6C=73=6F=20=77=69=74=68=20=C3=B6=C3=A4=C3=BC?= <noreply@localhost.com>
```

Without `$config['charset'] = 'utf8'`:
```
From: =?UTF-8?Q?Doe=20with=20=C3=B6=C3=A4=C3=BC,=20John,=20also=20with=20?= =?UTF-8?Q?=C3=B6=C3=A4=C3=BC?= <noreply@localhost.com>
```

**Comment by fabsn182** [comment]
Change it to 'utf-8' please and see if that changes anything, since the config value is used by htmlspecialchars and does not allow 'utf8'

**Comment by ko2in** [comment]
I know that the value should be 'UTF-8'. However, it doesn't work with 'UTF-8', but works with 'UTF8'. I've not dive into the source code where the problem relies winthin `_prep_q_encoding` function.

**Comment by fabsn182** [comment]
So what you are basically saying is: if you put something wrong into a specific spot, something at another place stops doing something wrong?
Nice, as it is no help other than proving my point that the problem is the `_prep_q_encoding` method.

**Comment by fabsn182** [comment]
In other words: a viable solution would be to change the `_prep_q_encoding' method to:
```php
protected function _prep_q_encoding($str) {
  return mb_encode_mimeheader($str, $this->charset, 'Q');
}
```

as `mb_encode_mimeheader` is a native implementation and the CI custom version is buggy.

**Comment by ko2in** [comment]
Well. I already agreed where the problem actually occurred as you mentioned. Until someone submit PR to fix this issue, there's no alternative solution to fix except as I suggested.
