### ISSUE TITLE
Codeigniter throws 502 error CloudFlare while using session

### ISSUE THREAD

**Issue by xaiborweb** [bcit-ci/CodeIgniter#5766]
Hi, I'm using the latest version of CodeIgniter
error reproduction

Login system with Ion_auth
config sessions
> $config['sess_driver'] = 'database';
> $config['sess_cookie_name'] = 'ci_session';
> $config['sess_expiration'] = 2592000; //30 dias
> $config['sess_save_path'] = 'ci_sessions';
> $config['sess_match_ip'] = FALSE;
> $config['sess_time_to_update'] = $config['sess_expiration'];
> $config['sess_regenerate_destroy'] = FALSE;
cloudflare / Crypto / flexible to access the site through https

start session on the web page and when I delete the sessions created directly from the table ci_sessions because they are created demaciadas is when the error 502 cloudflare occurs.

the only way i have found to fix it is to disable cloudflare redirect from https to http and wait a while and start loading the page

looking in google I find that apparently it is problem of the cookies are too large according to this article
https://stackoverflow.com/questions/31501972/codeigniter-throws-520-error-cloudflare-while-using-session

although I'm a rookie and I'm not sure. I appreciate any help.

if I delete my browser's cookies it also stops giving the error

**Comment by narfbg** [comment]
You should post on our [forums](https://forum.codeigniter.com/), we can't help you with this here.

P.S. The StackOverflow issue refers to a CI2 problem; CI3 session cookies only contain the session ID, which can never possible be too large.
