### ISSUE TITLE
Form helper: set_radio default value

### ISSUE THREAD

**Issue by renolooijmans** [bcit-ci/CodeIgniter#5768]
I'm not sure whether this is a bug or intentional, so if anyone could please shed some light on it.

The function "set_radio" does not work properly when used with a default value and 2 forms on the same page.

**To reproduce:**
- Create a form with radio buttons where set_radio is used (form 1)
- Create another form with a single textbox input (form 2)

When the page is opened, or when form 1 is submitted, everything works properly. A radio button is automatically set to checked based on its default value or the posted value.

When form 2 is submitted, the radio button has no checked attribute and thus is unchecked. If you reload the page (without submitting the form again) the radio button is populated again.

I suspect set_radio detects if a form has been submitted at all and if so - it checks its posted values. When form 2 has been submitted the radio values are not posted at all - so it doesn't check either of the radio buttons at all.

**Expected result:**
The provided default value, even when another form, which doesn't contain the radio buttons, has been posted.

**Used code:**
```
<input type="radio" id="profile-salutation-sir" name="profile_salutation" class="styled" value="0" {{set_radio('profile_salutation', '0', ($user->salutation == 0) ? TRUE : FALSE)}}>

<input type="radio" id="profile-salutation-madam" name="profile_salutation" class="styled" value="1" {{set_radio('profile_salutation', '1', ($user->salutation == 1) ? TRUE : FALSE)}}>
```

**Comment by narfbg** [comment]
> I suspect set_radio detects if a form has been submitted at all and if so - it checks its posted values. When form 2 has been submitted the radio values are not posted at all - so it doesn't check either of the radio buttons at all.

Right on the money. However, there's no way around that.
