### ISSUE TITLE
Is there any way to disable session logging when user agent is robot

### ISSUE THREAD

**Issue by Akshay-Hegde** [bcit-ci/CodeIgniter#5769]
This is just a query, is there any way to disable session from inserting and updating if user agent is robot,

Here is scenario, I logged in from my IP : 127.0.0.1, I also use google's mod_pagespeed, which also request for resource say  resources ( css, js, and images ), when I refresh, current page, I see session table got more records, actually it was supposed to be only 1, I also checked by disabling pagespeed, then everything is normal.

**Comment by Akshay-Hegde** [comment]
Something similar to, for robots.. 

```
// No sessions under CLI
		if (is_cli())
		{
			log_message('debug', 'Session: Initialization under CLI aborted.');
			return;
		}
```

**Comment by Akshay-Hegde** [comment]
Temporarily I fixed like this
```
$robots = array(
    'googlebot'         => 'Googlebot',
    'msnbot'            => 'MSNBot',
    'slurp'             => 'Inktomi Slurp',
    'yahoo'             => 'Yahoo',
    'askjeeves'         => 'AskJeeves',
    'fastcrawler'       => 'FastCrawler',
    'infoseek'          => 'InfoSeek Robot 1.0',
    'lycos'             => 'Lycos',
    'serf'		=> 'mod_pagespeed'
);
```
```
// No sessions under CLI
		if (is_cli() || ci()->agent->is_robot())
		{
```

**Comment by narfbg** [comment]
This is a bug tracker, please post such things on our [forums](https://forum.codeigniter.com/) instead.
