### ISSUE TITLE
DB Prefix Error

### ISSUE THREAD

**Issue by agoenks29D** [bcit-ci/CodeIgniter#5770]
please update your file *system/DB_Driver.php*

i got an error when is want to use dbprefix for table prefix name, i use **site_** for prefix name
```
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'site_TABLES site_FROM site_`CiMS_test1_1559501888`' at line 1

SHOW site_TABLES site_FROM site_`CiMS_test1_1559501888`

Filename: C:/xampp/htdocs/GanTara/CiMS-v2/system/database/DB_driver.php

Line Number: 691
```

original code : 
`$sql = preg_replace('/(\W)'.$this->swap_pre.'(\S+?)/', '\\1'.$this->dbprefix.'\\2', $sql);`

i changed to : 
`$sql = preg_replace('/(\W)'.$this->swap_pre.'(\S+?)/', '\\1\\2', $sql);`

**Comment by narfbg** [comment]
You haven't shown how you got to that SQL code to be generated.

**Comment by agoenks29D** [comment]
in config/database.php

```php
$db = array(
	'default' => array(
		'dsn'       => '',
		'hostname'  => 'localhost',
		'username'  => 'user',
		'password'  => 'pass',
		'database'  => 'mydb',
		'dbdriver'  => 'sqlite3',
		**'dbprefix'  => 'mytbprefix_',**
		'pconnect'  => FALSE,
		'db_debug'  => (ENVIRONMENT !== 'production'),
		'cache_on'  => FALSE,
		'cachedir'  => '',
		'char_set'  => 'utf8mb4',
		'dbcollat'  => 'utf8mb4_unicode_ci',
		'swap_pre'  => '',
		'encrypt'   => FALSE,
		'compress'  => FALSE,
		'stricton'  => FALSE,
		'failover'  => array(),
		'save_queries' => TRUE
	)
);
```

in controllers when i'am using this code : 
`$this->db->get('user');`

returned error

**Comment by narfbg** [comment]
A simple `$this->db->get('user')` on its own won't generate the query shown in the error message you provided ... I need to be able to replicate what you're doing.

**Comment by codenom-dev** [comment]
You can use `$this->db->dbprefix()` in  `$this->db->get()`

Example:
`$this->db->get($this->db->dbprefix('nametable'));`
