### ISSUE TITLE
MongoDB Driver for PHP

### ISSUE THREAD

**Issue by omid-student** [bcit-ci/CodeIgniter#5773]
Hi
I was downloaded MongoDB driver from php.net and place in ext folder
But still i cannot see this extension in wamp and cannot use it
Actually there are error The MongoDB PECL extension has not been installed or enabled
Please guide me

**Comment by jim-parry** [comment]
Support questions should be asked on our forum. We use github for bug tracking.
Your error message suggests that you have not installed/enabled mongodb in your PHP.
