### ISSUE TITLE
Its bug? use where_in get the warning

### ISSUE THREAD

**Issue by 2007lf** [bcit-ci/CodeIgniter#5775]
CI_VERSION = '3.1.9'
<br/>

A PHP Error was encountered

<p>Severity: Warning</p>
<p>Message:  preg_match(): Compilation failed: regular expression is too large at offset 38443</p>
<p>Filename: database/DB_query_builder.php</p>
<p>Line Number: 2418</p>

**Comment by narfbg** [comment]
I don't know what you're doing, but what the error shows is that you have an insanely large query (and at that line, it is already split at least in half). No, it's not a bug; it's a natural PCRE limitation.

**Comment by 2007lf** [comment]
Its just like $this->db->where_in('uid', $uids), yes, $uids array count is big, but I think this normal code, the table user records are many, I know its PCRE limitation, but I think CI need to check and do something to avoid warning happen.
