### ISSUE TITLE
Creating tables resetting fields and keys not mentionned anywhere

### ISSUE THREAD

**Issue by Nexey** [bcit-ci/CodeIgniter#5777]
Hi!
This is not exactly an issue as I was able to dig up the code to find my answers, but creating a table resets the arrays of keys and fields. I couldn't find it being mentionned anywhere in the user guide and I believe it would be a valuable information for future users.

I apologize if it weren't the correct place to post this. I also don't have time currently to issue a new pull request and change it myself in the user guide.

Thank you for everything you've done so far, I love CodeIgniter!

**Comment by narfbg** [comment]
You setup the array of keys/fields to be consumed by `create_table()` ... I don't really know what else you'd want to do with them, but it seems perfectly intuitive to me to expect this.
