### ISSUE TITLE
Unable to access an error message corresponding to your field name Correo.(Anonymous function)

### ISSUE THREAD

**Issue by Yonier** [bcit-ci/CodeIgniter#5780]
This is my code, its supposed to work:

		$this->form_validation->set_rules([
			[
				'field' => 'username',
				'label' => 'Usuario',
				'rules' => 'required',
				'errors' => ['required' => 'An username is required']
			],
			[
				'field' => 'password',
				'label' => 'Contrasena',
				'rules' => 'required',
				'errors' => ['required' => 'Enter a password']
			],
			[
				'field' => 'email',
				'label' => 'Correo',
				'rules' => [
					'required',
					['check_callable',
						[$this->userModel, 'testFunction[email]']
					]
				],
				'errors' => [
					'required' => 'Enter a email',
					'check_callable' => '{email} already exist!'
				]
			]
		]);

As you can see i'm using the "callbable" method...
[https://www.codeigniter.com/user_guide/libraries/form_validation.html?highlight=callback#callable-use-anything-as-a-rule](url)

_Of course, since a Callable rule by itself is not a string, it isn’t a rule name either. That is a problem when you want to set error messages for them. In order to get around that problem, you can put such rules as the second element of an array, with the first one being the rule name:_

but i don't get the error message :/ why?

help me please, thank you!

**Comment by narfbg** [comment]
You need to know what callables in PHP actually are ... `testFunction[email]` isn't a valid function; you can't use it like that.

For further questions, please post on our [forums](https://forum.codeigniter.com/) instead; this is a bug tracker.
