### ISSUE TITLE
chrome plugin Host Switch Plus URL issue

### ISSUE THREAD

**Issue by richerhuang** [bcit-ci/CodeIgniter#5782]
It is not able to open the web when I use chrome plugin Host Switch Plus.
The original URL is  http://abc.com , the log in CI is "404 Page Not Found: Abccom/index.php".
The URL abc.com is rewrite to Abccom in CI, how can I fix this issue.

**Comment by jim-parry** [comment]
Support questions should be asked on our [forum](https://forum.codeigniter.com/index.php), thanks.
We use github for bug tracking.
