### ISSUE TITLE
[Suggestion] url_helper.php's auto_link function to include rel="noopener"

### ISSUE THREAD

**Issue by yehgdotnet** [bcit-ci/CodeIgniter#5785]
Links created using url helper -> auto_link lacks security attribute, rel="noopener".  Thus, third-party links opened could pose a risk. 

Ref: [https://mathiasbynens.github.io/rel-noopener/](https://mathiasbynens.github.io/rel-noopener/)

**Comment by Paradinight** [comment]
It is.

See: https://www.codeigniter.com/user_guide/changelog.html#version-3-1-9
and
https://github.com/bcit-ci/CodeIgniter/blob/3.1.10/system/helpers/url_helper.php#L399

You should update to the latest version
