### ISSUE TITLE
How can i remove subclass_prefix?

### ISSUE THREAD

**Issue by frndmr** [bcit-ci/CodeIgniter#5786]
Hello, i want to remove subclass_prefix thing in my codeigniter project. How can i do that?

![image](https://user-images.githubusercontent.com/48316033/59979090-b9e29c00-95eb-11e9-8c01-00d47296b0fd.png)

I tried this. This doesnt work. I dont want to use subclass prefix.

**Comment by jim-parry** [comment]
Questions should be asked on our [forum](https://forum.codeigniter.com/index.php), thanks.
We use guthub for bug tracking.
