### ISSUE TITLE
Doc : Missing page "Managing your Applications"

### ISSUE THREAD

**Issue by ComputingFroggy** [bcit-ci/CodeIgniter#5787]
In the CI4 documentation, the page [Application Structure](https://codeigniter4.github.io/CodeIgniter4/concepts/structure.html) **last line** references the page "Managing your Applications" ... which does not exist !

**Comment by narfbg** [comment]
This is the CI3 repository, please open an issue at https://github.com/codeigniter4/CodeIgniter4
