### ISSUE TITLE
Bug in query_builder for PostgreSQL : neither truncate nor empty_table reset the sequence

### ISSUE THREAD

**Issue by ccaillet** [bcit-ci/CodeIgniter#5792]
**CI Version used: 3.1.10
Postgres v.10.4**

Here is the migration script to create this table :

        $this->dbforge->add_field(array(
            'id' => array(
                'type' => 'INT',
                'unsigned' => TRUE,
                'auto_increment' => TRUE
            ),
            'name' => array(
                'type' => 'VARCHAR',
                'constraint' => '100',
            ),
        ));
        $this->dbforge->add_key('id', TRUE);
        $this->dbforge->create_table('domains');

Then I add some records.

Then **empty_table** doesn't reset the _sequence_id_ which is linked with the _auto-incremented_ primary key. 

Same behaviour with **truncate**.  

PostgreSQL has a an opiton to reset this sequence_id: 
[TRUNCATE RESTART IDENTITY ](https://www.postgresql.org/docs/10/sql-truncate.html)

I did the same test on a MySQL database : _empty_table_ does the same as I mention above.
But _truncate_ on the MySQL database resets the auto_increment_value (~sequence_id of PostgreSQL). 
Is it possible to fix it ? (with an optionnal parameter i.e.)

Thanks in advance
Regards

**Comment by narfbg** [comment]
This would be non-optional for `truncate()` (and won't happen for `empty_table()`) in order to maintain portability between drivers.

Do you know if `RESTART IDENTITY` is silently ignored if the table being truncated doesn't have a sequence? If not, this could be tricky ...
