### ISSUE TITLE
views multiple-level subfolders file not working

### ISSUE THREAD

**Issue by good1515** [bcit-ci/CodeIgniter#5795]
views multiple-level subfolders file not working
application\views\admin\test\index.php

index.php form post not working

i use parse or view use form post is not working 
$this->parser->parse('admin\test\index');
$this->load->view('admin\test\index');

Because it’s an old program, it’s written in view

**Comment by narfbg** [comment]
Please explain exactly what doesn't work ...

Does the parsing fail?
Does the view not load?
Or is it just something with your form not working?

It's not at all clear from what you've written.

**Comment by good1515** [comment]
config/routes.php
$route['aaa/bbb/index'] = "main/test";

controllers/Main.php
class Main extends CI_Controller {
	public function test()
	{
		$post = $this->input->post();
		var_dump($post);
		$this->load->view('aaa/bbb/index');
	}
}

views\aaa\bbb\index.php
<form method="post">
	<input type="text" name="id">
	<input type="submit">
</form>

**Comment by good1515** [comment]
Why this issues not working but close?

**Comment by jim-parry** [comment]
You haven't explained what doesn't work & why this might be a CodeIgniter problem.

**Comment by good1515** [comment]
I am sorry, my english is poor

Multiple subfloor HTML from post not value , this is a bug. And not error message.

But subfloor is one working , subfloor is two not work.

Example on top

**Comment by jim-parry** [comment]
Your "example", in Taiwanese(?), makes no sense.
You still have not explained why this is a bug or even a problem.
What did you expect? What did you get? How to reproduce your problem?

A possibly helpful explanation: https://www.softwaretestinghelp.com/how-to-write-good-bug-report

**Comment by good1515** [comment]
**config/routes.php**
$route['aaa/bbb/index'] = "main/test";

**controllers/Main.php**
class Main extends CI_Controller {
public function test()
{
$post = $this->input->post();
var_dump($post);
$this->load->view('aaa/bbb/index');
}
}

**views\aaa\bbb\index.php**
＜form method="post">
＜input type="text" name="id">
＜input type="submit">
＜/form>

This can reproduce this problem

**Comment by narfbg** [comment]
I can't tell why, but I can tell you it's not because of anything in CodeIgniter. If I had to guess, it's probably something wrong with your rewrite rules.

You should do more extensive debugging and possibly ask somewhere else for help; preferrably somewhere where others know your mother tongue and can communicate with you easily.
