### ISSUE TITLE
The list_tables() method of the DB driver throws an error

### ISSUE THREAD

**Issue by iRedds** [bcit-ci/CodeIgniter#5796]
An error occurs if the database name consists only of numbers.
Need to escape database name.

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1234' at line 1

SHOW TABLES FROM 1234

Filename: libraries/Migration.php

Line Number: 167

**Comment by laotoutou** [comment]
This is not a CI problem

**Comment by iRedds** [comment]
SQL injections is not a CI problem. But...
Unescaped string is not a CI problem. But...
But it can be solved.
