### ISSUE TITLE
A very strange bug, combining Codeignite, php-jwt and file upload

### ISSUE THREAD

**Issue by vahidvdn** [bcit-ci/CodeIgniter#5797]
I'm using `php-jwt` in a CI project. I have a `MY_Controller` in core directory which I extend all of my other controllers by it.

I handle my jwt token in `MY_Controller` (in order to have access in all of the functions of controllers). Everything worked fine until I made an API in order to upload a file. (As you know while having a file for upload, javascript adds some `Content-Type` to the request headers automatically.)

After adding it, `php-jwt` couldn't be able to validate the same token in `MY_Controller` as mentioned at [firebase/php-jwt/#245](https://github.com/firebase/php-jwt/issues/245) . Then I tested in the controller and it worked fine.

I really don't uderstand this relates to CI or `php-jwt`. Why something like this can be happen?

**Comment by datamweb** [comment]
Hi, @vahidvdn please attach detailed information(version) about the PHP ,CI,JWT,Gchrome and ...

**Comment by gxgpet** [comment]
Please use the [forums](https://forum.codeigniter.com/) for questions and help regarding your projects. This is a bug tracker.

**Comment by vahidvdn** [comment]
Hi @datamweb. Here you are: PHP: 5.6, CI: 3.1.10, Chrome: 75 and about JWT it doesn't be mentioned in JWT.php file

@gxgpet This is mostly a bug not a question.

**Comment by gxgpet** [comment]
@vahidvdn It's a bug in your application, not in the CodeIgniter framework.

**Comment by vahidvdn** [comment]
@gxgpet How can you be this much sure? As I mentioned, this works fine in a controller, but it does not it the MY_Controller class.

**Comment by narfbg** [comment]
php-jwt is a third-party library and CodeIgniter doesn't concern itself with it, thus even if something in CI is interfering with php-jwt (which you haven't shown, just speculated), it cannot be claimed to be a CodeIgniter bug.

Also, note that when you create a `MY_Controller` extension, that's your code and part of your application, so ...
