### ISSUE TITLE
Redis session driver now returns TRUE instead of '+PONG'

### ISSUE THREAD

**Issue by darvanen** [bcit-ci/CodeIgniter#5801]
The recommended phpredis package has had this change recently:
https://github.com/phpredis/phpredis/issues/1563

This means that CI fails to close redis sessions because it is expecting a string of '+PONG' rather than the new boolean TRUE.

Line 252 of system/libraries/Session/drivers/Session_redis_driver.php

**Comment by darvanen** [comment]
PR at https://github.com/bradtraversy/ciblog/pull/15

**Comment by narfbg** [comment]
Please don't create issues just to reference them in pull requests, you can just explain the problem in the PR itself ...

**Comment by darvanen** [comment]
Noted thank you.

Got to the issue before I realised how easy a PR could be, won't happen again.

**Comment by mchobbylong** [comment]
Hi there! Since my PR is merged, I believe this issue has been solved. Please check that out for the latest solution 😉

**Comment by narfbg** [comment]
Fixed by #5816.
