### ISSUE TITLE
Insert batch get failed when the indexes of array are not the same

### ISSUE THREAD

**Issue by vahidvdn** [bcit-ci/CodeIgniter#5803]
I get some data from the front end and some columns are not mandatory. So the array is something like this:

```php
[
    0 => ['col1'=>'val1', 'col2'=>'val2'],
    1 => ['col1'=>'val3']
]
```

Then when I use `insert_batch` I get the following error:

```
Array to string conversion
```

When I add `col2` for the second index, the error is gone.

**Comment by narfbg** [comment]
Yes, this is completely natural and there's nothing to suggest that missing columns are acceptable ... the framework isn't magic.

**Comment by vahidvdn** [comment]
@narfbg So, why this is possible with simple `insert` within a loop?

**Comment by narfbg** [comment]
Because there's a difference between this:

    INSERT INTO <table> (<field1>, <field2>) VALUES (<value1>, <value2>);
    INSERT INTO <table> (<field1>, <field2>, <field3>) VALUES (<value1>, <value2>, <value3>);

... and this:

    INSERT INTO <table> (<field1>, <field2>, <field3>)
    VALUES
        (<value1>, <value2>), -- syntax error because <field3> is declared, but there's no value for it here
        (<value1>, <value2>, <value3>);
