### ISSUE TITLE
php tag doesn't working in view on CodeIgniter 3.1.10

### ISSUE THREAD

**Issue by bluishpenta** [bcit-ci/CodeIgniter#5804]
Hi, I have a difficulty to update to CodeIgniter 3.1.10 because a bug that cause PHP tag or <?php ?> in view not working. Before upgrade from 3.1.9, PHP tag works fine.

The issue is like below code;
`<body>
    <nav class="global-nav-bar navbar sticky-top navbar-expand-md navbar-light global-bg-white">
        <a class="navbar-brand" href="<?php echo base_url();?>">
            <img src="/global/images/logo.png">
        </a>`

and the web browser show nothing but I use view source, the browser show like this;
<img src="https://i.imgur.com/DC953r9.png" />

I try to seeking documentation but there is no explanation on the difference between CI 3.1.9 and CI 3.1.10

Thank you

**Comment by narfbg** [comment]
There is no such bug; it is impossible for any framework to break the PHP opening tag.

**Comment by bluishpenta** [comment]
> 
> 
> There is no such bug; it is impossible for any framework to break the PHP opening tag.

No, I can use it in CI 3.1.9. And now I can't use anymore? How?

**Comment by narfbg** [comment]
I don't know how, but it has 100% nothing to do with CI.
