### ISSUE TITLE
How to add default where condition in model

### ISSUE THREAD

**Issue by shahidgepl** [bcit-ci/CodeIgniter#5812]
class Demo_model extends CI_Model {
	
		public $table = 'test';
		
		public function __construct() 
		{
				parent::__construct();
				$this->db->where('status', 1);
		}
}
I want to add where for this model only.

In base Model i have function for all model
//-- get function
	function get($id)
	{
			$this->db->where('id',$id);
			$row = $this->db->get($this->table)->row();
			return $row;
	}

**Comment by narfbg** [comment]
This is a bug tracker; please ask your questions on our [forums](https://forum.codeigniter.com/) instead.
