### ISSUE TITLE
Some text was removed while xss filtering

### ISSUE THREAD

**Issue by khanorder** [bcit-ci/CodeIgniter#5817]
Removed text is '% 33', '% 40'. (single quote is not included)
`$text = "% 33";`
`$xss_text = $this->input->post($text, TRUE);`
`echo $xss_text;`
`// result is 3 and @`

https://stackoverflow.com/questions/56572511/some-text-was-removed-while-xss-filtering-in-codeigniter

https://stackoverflow.com/questions/5337143/codeigniter-why-use-xss-clean

**Comment by narfbg** [comment]
Duplicate of #5125.
