### ISSUE TITLE
Php-redis driver setTimeout has deprecated

### ISSUE THREAD

**Issue by al-ramadhan** [bcit-ci/CodeIgniter#5819]
> Message: Function Redis::setTimeout() is deprecated
> 
> Filename: drivers/Session_redis_driver.php
> 

After read their official repository, turns out method "setTimeout" has been replaced with "expire" on this [PR](https://github.com/phpredis/phpredis/pull/1572). Just tried to change drivers code and it works

**Comment by dhtmdgkr123** [comment]
> > Message: Function Redis::setTimeout() is deprecated
> > Filename: drivers/Session_redis_driver.php
> 
> After read their official repository, turns out method "setTimeout" has been replaced with "expire" on this [PR](https://github.com/phpredis/phpredis/pull/1572). Just tried to change drivers code and it works

I have same issue so i tried to replace "setTimeout" to "expire" but i almost have
> ini_set(): A session is active. You cannot change the session module's ini settings at this time
this error message How to fix this issue
> Ubuntu16.04, NGINX(1.10.3), REDIS(3.0.6), php 7.3.8

**Comment by dhtmdgkr123** [comment]
> > Message: Function Redis::setTimeout() is deprecated
> > Filename: drivers/Session_redis_driver.php
> 
> After read their official repository, turns out method "setTimeout" has been replaced with "expire" on this [PR](https://github.com/phpredis/phpredis/pull/1572). Just tried to change drivers code and it works

I have same issue so i tried to replace "setTimeout" to "expire" but i almost have
> ini_set(): A session is active. You cannot change the session module's ini settings at this time

this error message How to fix this issue?

> Spec : Ubuntu16.04, NGINX(1.10.3), REDIS(3.0.6), php 7.3.8

**Comment by dhtmdgkr123** [comment]
> > Message: Function Redis::setTimeout() is deprecated
> > Filename: drivers/Session_redis_driver.php
> 
> After read their official repository, turns out method "setTimeout" has been replaced with "expire" on this [PR](https://github.com/phpredis/phpredis/pull/1572). Just tried to change drivers code and it works

I have same issue so i tried to replace "setTimeout" to "expire" but i almost have
> ini_set(): A session is active. You cannot change the session module's ini settings at this time
> session_start(): Failed to read session data: user (path: /var/lib/php/sessions)
this error message.

my redis server is alive but can not load redis..
how can fix this issue...?

> Spec : Ubuntu16.04, NGINX(1.10.3), REDIS(3.0.6), php 7.3.8, php-redis

**Comment by al-ramadhan** [comment]
Maybe that's another issue even it is likely from the same redis driver. I don't know if it's related to new version of **phpdriver**, but looks like redis_driver has broken.

**Comment by al-ramadhan** [comment]
Should be solved by this [PR 5816](https://github.com/bcit-ci/CodeIgniter/pull/5816)

**Comment by dhtmdgkr123** [comment]
> Should be solved by this [PR 5816](https://github.com/bcit-ci/CodeIgniter/pull/5816)

Thank you~

**Comment by mchobbylong** [comment]
Hi there! Just for reminder, the PR was merged. You could check that out 😄
