### ISSUE TITLE
is_unique form validation not working on update.I fails the validation by comparing with same user email

### ISSUE THREAD

**Issue by MuhammadHamzaWazir** [bcit-ci/CodeIgniter#5820]
is_unique form validation not working on update.I fails the validation by comparing with same user email.is_unique is also pick the email of same id in which i updated.on update of user data , i did not change the email it will return me error of unique email on update

**Comment by MuhammadHamzaWazir** [comment]
$this->form_validation->set_rules('email', 'Email', 'required|valid_email|is_unique['.$tableName.'.email.'.$id.']');

**Comment by narfbg** [comment]
Please post on our [forums](https://forum.codeigniter.com/) instead. This is a bug tracker.
