### ISSUE TITLE
i am facing problem in otp integration if any boddy have done it already please send me sourch code please 

### ISSUE THREAD

**Issue by salmankhan786** [bcit-ci/CodeIgniter#5821]
this error i m facing
An uncaught Exception was encountered
Type: Twilio\Exceptions\RestException

Message: [HTTP 400] Unable to create record: The 'To' number +9234398887 is not a valid phone number.

Filename: C:\xampp\htdocs\ci\vendor\twilio\sdk\Twilio\Version.php

Line Number: 85

**Comment by jim-parry** [comment]
Support questions should be asked on our [forum](https://forum.codeigniter.com/index.php) or [slack channel](https://codeigniterchat.slack.com/), thanks.
We use github for bug tracking.

**Comment by narfbg** [comment]
Also, be careful with publishing data even in error messages. I don't know if that phone number was valid or not, but you shouldn't be posting stuff like that in public (I edited it out).
