### ISSUE TITLE
i am posting data into post table and images to other table images and these both are joind by forign key so when i post it show me the following errror

### ISSUE THREAD

**Issue by salmankhan786** [bcit-ci/CodeIgniter#5822]
*/
    public function upload($data = array(),$item_id){
   
  $this->db->insert('images')
          ->where('item_id',$item_id);

        $insert = $this->db->insert_batch('images',$data);

       // $this->db->insert('images')
       //    ->where('item_id',$item_id);

        return $insert?true:false;

here is my code where do i face the problem

**Comment by jim-parry** [comment]
Support questions should be asked on our [forum](https://forum.codeigniter.com/index.php) or [slack channel](https://codeigniterchat.slack.com/), thanks.
We use github for bug tracking.
