### ISSUE TITLE
mysql varchar bug

### ISSUE THREAD

**Issue by tylerzoupeng** [bcit-ci/CodeIgniter#5823]
when mysql data like that 
array (
  'aaa' => '13910551635',
  'bbb' =>
  SimpleXMLElement::__set_state(array(
     0 => '01908230227430001020',
  )),
)
the sql will be like that:
INSERT INTO xxxx (`aaa`, `bbb`) VALUES ('13910551635',  01908230227430001020)
the result will be loss the first 0 in 01908230227430001020, like that 1908230227430001020.

**Comment by bennito254** [comment]
Change your database table column to VARCHAR if you wish to preserve the preceding 0

**Comment by narfbg** [comment]
If there's a bug here, it would be in `SimpleXMLElement::__set_state()` (which btw, as far as I can tell is not a documented on php.net) and not in CodeIgniter.
