### ISSUE TITLE
Can not inserting the data

### ISSUE THREAD

**Issue by asheesharyan** [bcit-ci/CodeIgniter#5824]
I have an angular application and  doing signup via post request.Please consider the api code in Codeigniter.

header("Access-Control-Allow-Origin: *");
header("Access-Control-Request-Headers: GET,POST,OPTIONS,DELETE,PUT");
header('Access-Control-Allow-Headers: Accept,Accept-Language,Content-Language,Content-Type');

$formdata = json_decode(file_get_contents('php://input'),true);
$email=$formdata['email'];  
$save_data['email']=$email;
$save_data['password']='123456';

//print_r($save_data);     // data is printing here as well.

$this->db->insert('tbl_users',save_data);   // not working 

Errror Log: Query error: Column 'email' cannot be null - Invalid query: INSERT INTO `tbl_users` (`email`, `password`) VALUES (NULL, '123456')

Why emai is null, I am using codeigniter 3.1.10

**Comment by bennito254** [comment]
$this->db->insert('tbl_users',$save_data); // not working ...now working. You forgot '$' in your $save_data variable

**Comment by asheesharyan** [comment]
Sorry for the typo error but it is not working.

**Comment by asheesharyan** [comment]
I have checked....when i print form_data email is coming it....

**Comment by asheesharyan** [comment]
Hello Guys, Any update on this issue?..

**Comment by asheesharyan** [comment]
Here is the db_driver.php of codeigniter and the code of function 

public function query($sql, $binds = FALSE, $return_object = NULL)
	{
		if ($sql === '')
		{
			log_message('error', 'Invalid query: '.$sql);
			return ($this->db_debug) ? $this->display_error('db_invalid_query') : FALSE;
		}
		elseif ( ! is_bool($return_object))
		{
			$return_object = ! $this->is_write_type($sql);
		}

		// Verify table prefix and replace if necessary
		if ($this->dbprefix !== '' && $this->swap_pre !== '' && $this->dbprefix !== $this->swap_pre)
		{
			$sql = preg_replace('/(\W)'.$this->swap_pre.'(\S+?)/', '\\1'.$this->dbprefix.'\\2', $sql);
		}

		// Compile binds if needed
		if ($binds !== FALSE)
		{
			$sql = $this->compile_binds($sql, $binds);
		}

		// Is query caching enabled? If the query is a "read type"
		// we will load the caching class and return the previously
		// cached query if it exists
		if ($this->cache_on === TRUE && $return_object === TRUE && $this->_cache_init())
		{
			$this->load_rdriver();
			if (FALSE !== ($cache = $this->CACHE->read($sql)))
			{
				return $cache;
			}
		}

		// Save the query for debugging
		if ($this->save_queries === TRUE)
		{
			$this->queries[] = $sql;
		}

		// Start the Query Timer
		$time_start = microtime(TRUE);

		// Run the Query
		if (FALSE === ($this->result_id = $this->simple_query($sql)))
		{
			if ($this->save_queries === TRUE)
			{
				$this->query_times[] = 0;
			}

			// This will trigger a rollback if transactions are being used
			if ($this->_trans_depth !== 0)
			{
				$this->_trans_status = FALSE;
			}

			// Grab the error now, as we might run some additional queries before displaying the error
			$error = $this->error();
                 //if i put exit(); here is working fine.


Any suggestion?....

**Comment by andersonunsonst** [comment]
please post your print_r($save_data); 

you need to prove that your key really isn't empty ...

**Comment by asheesharyan** [comment]
![t](https://user-images.githubusercontent.com/7736331/63941004-4f852680-ca88-11e9-9cd8-50848e438682.png)

**Comment by asheesharyan** [comment]
@andersonunsonst  Please see the above.

**Comment by asheesharyan** [comment]
@andersonunsonst , Please see the above.

**Comment by andersonunsonst** [comment]
there is no email key
$formdata['email'] is null
the error is in your code and not in codeigniter, please close this issue

**Comment by asheesharyan** [comment]
> there is no email key
> $formdata['email'] is null
> the error is in your code and not in codeigniter, please close this issue

It is second code..
ERROR - 2019-08-29 14:22:23 --> Query error: Column 'name' cannot be null - Invalid query: INSERT INTO `tbl_bank` (`name`, `bank_name`, `iban`, `user_id`, `status`, `date_added`, `date_modified`) VALUES (NULL, NULL, NULL, NULL, 1, '2019-08-29 14:22:23', '2019-08-29 14:22:23')

Last 3rd are hard coded..

 public function  add_bankaccount()
    {

            header("Access-Control-Allow-Origin: *");
            header("Access-Control-Request-Headers: GET,POST,OPTIONS,DELETE,PUT");
            header('Access-Control-Allow-Headers: Accept,Accept-Language,Content-Language,Content-Type');
            $response= [];
            $status=0; 
            $error_mess='Some error occured.';
            $success_mess=''; 

            $formdata = json_decode(file_get_contents('php://input'),true);

            $name=$formdata['name']; 
            $bank_name=$formdata['bank_name'];
            $iban=$formdata['iban'];
            $user_id=$formdata['user_id'];
            $is_account_exist=get_table_data('id', 'tbl_bank', ['user_id'=>$user_id,'iban'=>$iban]); 
            
            if(!empty($is_account_exist))
            {
                $status=2; 
                $error_mess='Account already exist.';

            }
            else
            {

                 $save_data= []; 

                 $save_data['name']= $name; 
                 $save_data['bank_name']= $bank_name; 
                 $save_data['iban']= $iban; 
                 $save_data['user_id']= $user_id;

                 $save_data['user_id']= $user_id;  
                 $save_data['status']= 1; 
                 $save_data['date_added']= date('Y-m-d H:i:s'); 
                 $save_data['date_modified']= date('Y-m-d H:i:s'); 

                 pr($save_data);  exit ; 

                // $this->db->insert('tbl_bank',$save_data ); 

               
                  


                  $status=1; 
                  $error_mess='';
                  $success_mess='Account added successfully.'; 


            }





            

            //pr($formdata); exit; 


            $response['status']=$status; 
            $response['error_mess']=$error_mess; 
            $response['success_mess']=$success_mess; 

            $this->output
            ->set_content_type('application/json')
            ->set_output(json_encode($response));
    
    }

**Comment by asheesharyan** [comment]
> > there is no email key
> > $formdata['email'] is null
> > the error is in your code and not in codeigniter, please close this issue
> 
> It is second code..
> ERROR - 2019-08-29 14:22:23 --> Query error: Column 'name' cannot be null - Invalid query: INSERT INTO `tbl_bank` (`name`, `bank_name`, `iban`, `user_id`, `status`, `date_added`, `date_modified`) VALUES (NULL, NULL, NULL, NULL, 1, '2019-08-29 14:22:23', '2019-08-29 14:22:23')
> 
> Last 3rd are hard coded..
> 
> public function add_bankaccount()
> {
> 
> ```
>         header("Access-Control-Allow-Origin: *");
>         header("Access-Control-Request-Headers: GET,POST,OPTIONS,DELETE,PUT");
>         header('Access-Control-Allow-Headers: Accept,Accept-Language,Content-Language,Content-Type');
>         $response= [];
>         $status=0; 
>         $error_mess='Some error occured.';
>         $success_mess=''; 
> 
>         $formdata = json_decode(file_get_contents('php://input'),true);
> 
>         $name=$formdata['name']; 
>         $bank_name=$formdata['bank_name'];
>         $iban=$formdata['iban'];
>         $user_id=$formdata['user_id'];
>         $is_account_exist=get_table_data('id', 'tbl_bank', ['user_id'=>$user_id,'iban'=>$iban]); 
>         
>         if(!empty($is_account_exist))
>         {
>             $status=2; 
>             $error_mess='Account already exist.';
> 
>         }
>         else
>         {
> 
>              $save_data= []; 
> 
>              $save_data['name']= $name; 
>              $save_data['bank_name']= $bank_name; 
>              $save_data['iban']= $iban; 
>              $save_data['user_id']= $user_id;
> 
>              $save_data['user_id']= $user_id;  
>              $save_data['status']= 1; 
>              $save_data['date_added']= date('Y-m-d H:i:s'); 
>              $save_data['date_modified']= date('Y-m-d H:i:s'); 
> 
>              pr($save_data);  exit ; 
> 
>             // $this->db->insert('tbl_bank',$save_data ); 
> 
>            
>               
> 
> 
>               $status=1; 
>               $error_mess='';
>               $success_mess='Account added successfully.'; 
> 
> 
>         }
> 
> 
> 
> 
> 
>         
> 
>         //pr($formdata); exit; 
> 
> 
>         $response['status']=$status; 
>         $response['error_mess']=$error_mess; 
>         $response['success_mess']=$success_mess; 
> 
>         $this->output
>         ->set_content_type('application/json')
>         ->set_output(json_encode($response));
> 
> }
> ```
the values are coming from the post, ci  treating them as null...

**Comment by narfbg** [comment]
This is a bug tracker. Please post your questions on our [forums](https://forum.codeigniter.com/) instead.
