### ISSUE TITLE
Query builder limit() function generates LIMIT 0 with 'false' in parameter

### ISSUE THREAD

**Issue by punjabik** [bcit-ci/CodeIgniter#5827]
Hello,

commit b070d923fee349b36c16010da3ff3c0222dddec3 breaks my application.

When i call
`$this->db->limit(FALSE, 10);`

then FALSE become 0 because of this code
`is_null($value) OR $this->qb_limit = (int) $value;`

And this new commit pass that 0 as a wanted 0.
LIMIT 0 is generated and I get no result from that query.

**Comment by narfbg** [comment]
You're not supposed to pass `FALSE` there, that makes no sense.

**Comment by punjabik** [comment]
I used that for years to simplify code. One function for limit, offset or both based on parameters. It saves me a few lines of code.
Now because of this new commit it's not possible. I think it's a shame.

**Comment by narfbg** [comment]
Well, that's what happens when you rely on undocumented side-effects.
