### ISSUE TITLE
Form validation with array doesn't work

### ISSUE THREAD

**Issue by vahidvdn** [bcit-ci/CodeIgniter#5829]
Here is my `$_POST['options']` output:

```
0 => [
   "name":"Vahid"
],
  ...

```

And this is my config for the input in `form_validation.php`:

```
'addOptions' => [
    [
        'field' => 'options',
        'rules' => [
            function ($value) {
                // this gives me null
                echo $value;
            }
        ]
    ],
]
```

When I use `'field' => 'options'` the value is null, and when I use `'field' => 'options[0]'` it gives me the values, but I don't want to indicate the index, beside I just want to this is a valid array (not checking the values). Also this doesn't work: `'field' => 'options[]'` (It doesn't echo anything)

Any idea?

**Comment by narfbg** [comment]
> when I use `'field' => 'options[0]'` it gives me the values, but I don't want to indicate the index

Then it's obviously working, but you want it to work in a different way ... well, can't have it both ways. If you need help, please post on our [forums](https://forum.codeigniter.com/); it's not a bug, so there's nothing to be done about it here.

**Comment by vahidvdn** [comment]
@narfbg The bug is here that `'field' => 'options'` gives me null which I can't check whether it's a valid array or not.

**Comment by narfbg** [comment]
It gives you null because an array wasn't expected and was subsequently invalidated. That's not a bug.

**Comment by vahidvdn** [comment]
It seems the only option is encoding `$_POST['options']` to string and decoding it in the `rules` callback function.
