### ISSUE TITLE
There is an property for CI, but no place to init it or set it.

### ISSUE THREAD

**Issue by xlzheng111** [bcit-ci/CodeIgniter#5830]
Hi, 
I find we use CI->$property in both function _ci_load_library() and _ci_load_stock_library(), but there is no place to set the property or init the property. 

             // Safety: Was the class already loaded by a previous call?
                if (class_exists($class, FALSE))
                {
                        $property = $object_name;
                        if (empty($property))
                        {
                                $property = strtolower($class);
                                isset($this->_ci_varmap[$property]) && $property = $this->_ci_varmap[$property];
                        }

                        $CI =& get_instance();
                        **if (isset($CI->$property))**
                        {
                                log_message('debug', $class.' class already loaded. Second attempt ignored.');
                                return;
                        }

                        return $this->_ci_init_library($class, '', $params, $object_name);
                }

So even this lib had already been loaded, for the CI->$property will always been empty, which will cause we repeat load the lib,

**Comment by narfbg** [comment]
https://github.com/bcit-ci/CodeIgniter/blob/3.1.10/system/core/Loader.php#L1283
