### ISSUE TITLE
getHistory issue

### ISSUE THREAD

**Issue by eincandela** [bcit-ci/CodeIgniter#5838]
Hello,

i'm using codeigniter 4 rc1 + postgres 10

When you apply migrations onto tests group

`php spark migrate -g tests`

the getHistory() method searches the previous applied migrations into the default datatabase, not the "tests" one, though doesn't apply them if they are present in the main database.

the correct database is only selected when creating the migration instance in migrate() method

```
// Forcing migration to selected database group
$instance = new $class(\Config\Database::forge($this->group));
```

i hope i'm not using the framework wrong and reporting a false bug :/ but i tried many things without success.

**Comment by jim-parry** [comment]
This should be raised in the [CodeIgniter 4 repository](https://github.com/codeigniter4/CodeIgniter4).
This repository is for CodeIgniter 3.
