### ISSUE TITLE
Redis cache driver sRemove() is deprecated

### ISSUE THREAD

**Issue by laszlol** [bcit-ci/CodeIgniter#5840]
Hello there,
I'm using Redis server v5.0.5 on my server and I have phpredis 5.1.0-dev.
I found this in the log
`Severity: 8192 --> Function Redis::sRemove() is deprecated /system/libraries/Cache/drivers/Cache_redis.php 196`
`sRemove` should be changed to `sRem` as they have a note about this here https://github.com/phpredis/phpredis#srem-sremove

**Comment by robertmain** [comment]
Chipping in here to say I'm saying this too. I'm also seeing page loading times go through the roof since I enabled redis, and `Message: Function Redis::setTimeout() is deprecated`. I suspect they may well all be related...
