### ISSUE TITLE
Exclude user_guide if CodeIgniter is installed via Composer.

### ISSUE THREAD

**Issue by indrakaw** [bcit-ci/CodeIgniter#5843]
This is probably similar to #3831.

If possible, I'd to exclude `user_guide` directory to keep the file size when using composer down. It's quite big, compared to core directories:

**Installed with `--prefer-dist`**
```
$ du -h --max-depth=1 | sort -h
280K    ./application
2.4M    ./system
11M     ./user_guide
13M     .
```

**Installed with `--prefer-source`**
```
$ du -h --max-depth=1 | sort -h
280K    ./application
2.4M    ./system
11M     ./user_guide
55M     ./.git
67M     .
```

I'm in favor of ignoring it, The idea is that when using the library as is on a prod server, you don't end up with files that can be used for full path disclosure.
https://www.owasp.org/index.php/Full_Path_Disclosure

Addendum:
My thoughts were that when you are using this (or any other package), I would typically look through the code and the documentation online instead of reading through a docs folder in the vendor directory.

**Comment by narfbg** [comment]
Well, how do you propose to do that? The `user_guide` dir is included in the tag ...

**Comment by indrakaw** [comment]
I'm not familiar with composer packages. Normally, it can be excluded by add this line:
```
user_guide export-ignore
```
Into `.gitattributes` file.

**Comment by djunehor** [comment]
I agree with @indrakaw, installation via composer should be fast and light-weight, which means non-required files should be excluded. As suggested, the folder should be included in `gitignore` and an update pushed so that subsequent composer installations don't down user_guider folder.

**Comment by indrakaw** [comment]
Apparently all `3.X` tags are updated with the current `.gitattributes`. I was trying to test by installing older version before one from issue I mentioned then compare it with the current one.

This might take while, I'm installing the package via composer as commit as version pointer.

**Comment by gphg** [comment]
Hi. Is it possible to get `user_guide_src` excluded too?
