### ISSUE TITLE
[config] "sess_cookie_name" ignored when using redis driver

### ISSUE THREAD

**Issue by derMatze82** [bcit-ci/CodeIgniter#5844]
when I use redis as the session driver, the "sess_cookie_name" value is ignored. The key in Redis server is always starting with "ci_session:...", regardless of the sess_cookie_name value.

**Comment by narfbg** [comment]
`ci_session:` is an intentionally hard-coded key prefix to avoid accidental collisions with other data that may be stored in Redis. It's not meant to be the cookie name.
