### ISSUE TITLE
CI 3.1.11 PHP cross-version compatibility Errors when using PHP_CodeSniffer

### ISSUE THREAD

**Issue by fledSnapx** [bcit-ci/CodeIgniter#5845]
Hi.
I'm currently upgrading an application that was still working on PHP 5.6 to the last CI version 3.1.11 in order to be installed on a server using PHP 7.3.9. Since the code was not executing (syntax error, unexpected end of file) on a helper file, I decided to run an analysis on my code for compatibility with higher versions of PHP using PHP_CodeSniffer (https://github.com/PHPCompatibility/PHPCompatibility).

I want to bring to your attention the result of the code audit, in the hope that it will help.

[CI-CodeSniffer-Audit-Results.txt](https://github.com/bcit-ci/CodeIgniter/files/3655283/CI-CodeSniffer-Audit-Results.txt)

**Comment by narfbg** [comment]
Sorry, but that file is 1200+ lines long and after just about 400 lines it starts listing warnings about your composer dependencies ... You cannot expect us to be able to thoroughly review it.

A quick glance of the CI-related errors that I see is all things that we handle conditionally and are not in fact any issues. If you can point to that syntax error you mentioned or anything more specific, I'd be happy to look into it, but as it is I can't do anything with this issue.
