### ISSUE TITLE
Codeigniter 3.1.11 Migration does not work anymore.

### ISSUE THREAD

**Issue by BartMommens** [bcit-ci/CodeIgniter#5850]
Hi,

My project is using Migration library to create and update table structures.
Until version 3.1.10 everything worked fine. i use cli to execute the migration:

`php index.php migrate_controller up`

This works in version 3.1.9, 3.1.10 but not not 3.1.11:

CLI returns following error:

Database error: A Database Error Occurred

	Error Number: 42000/1102
	Incorrect database name ''
	SHOW TABLES FROM ``
	Filename: libraries/Migration.php
	Line Number: 167

At first glance the libraries look identical... yet it does not work in 3.1.11 when i replace the system folder with the 3.1.10 / 3.1.9 it's up and running again ...

I've been searching for where it's going wrong for over 3 hours now but can't seem to locate the issue ...

**Comment by BartMommens** [comment]
It seems it has something to do with me using PDO drivers:
For people having this issue take a look at : https://forum.codeigniter.com/thread-74507-post-368110.html#pid368110

**Comment by narfbg** [comment]
So ... from what I understand, you left out a configuration field that the DB library depends on empty. Can't do anything about that.

**Comment by BartMommens** [comment]
> So ... from what I understand, you left out a configuration field that the DB library depends on empty. Can't do anything about that.

Since the PDO driver uses DSN field instead of the database field: 
`'dsn'    => 'mysql:host=localhost;port=3306;dbname=myproject',`
I left the database field empty, it used to work perfectly over the last few years up until v3.1.10, i've seen many other projects on github using only the 'DSN' field and leaving the database blank.

So the update to 3.1.11 the pdo_driver.php reads the line from the database field,
which it didn't do before causing an error. if you fill in the database field to correspond with the dbname in the dns line it works. But when you change database and forgot to change one of them it's also going to cause an error. I did change my drivers from PDO to MySQLi and removed the 'DSN' Field. As you pointed out it's not really an issue. But i hope people with a similar error find their way tho this thread for a quick solution.
