### ISSUE TITLE
Cannot login on forum

### ISSUE THREAD

**Issue by Pantoflarz** [bcit-ci/CodeIgniter#5853]
I understand that the git repo is not the place for this, but theres no where else to go when I cant login to the forum.

When I press sign in, the login popup appears in the bottom left of the browser but I can't actually use it - http://ftp.pantoflarz.flamespeak.pl/DgSCfkeNUD.mp4

Any way to overcome this, or am I doing something wrong?

Thanks

**Comment by Elardzhi** [comment]
Use Chrome, it works there.
But it is really a bug.

**Comment by narfbg** [comment]
This is indeed not the place and I thought that there's a support email linked somewhere on the forums, but alas, I cannot find that myself.

@jim-parry Can you look into it?

**Comment by jim-parry** [comment]
@Pantoflarz As the other poster said, you can use Chrome, or you can maximize the screen, login, then restore it. This is a legacy hiccup from the summer forum transition that hasn't been resolved.
