### ISSUE TITLE
flashdata not clearing on remote server, but works on local xampp server

### ISSUE THREAD

**Issue by sutherlandnele** [bcit-ci/CodeIgniter#5854]
I am running the following:

CI version 3.1.11 using database driver for session storage on PHP version 7.2

I am using flashdata as shown by controller class function below:

	public function create() {

        if($this->input->post('input_val'))
		{
			$input_data = $this->input->post('input_val');

			if($this->session->image != 'DEL'){
				//get the product image name from the previous session request
				$input_data['image'] = $this->session->image;
			}

			$this->session->unset_userdata('image');

			//populate audit fields
			$input_data['created_by']  = 'iccc'; //TODO: need to get this value from currently logged in username
			$input_data['created_date'] = mdate('%Y-%m-%d %H:%i:%s');

            $is_inserted = $this->product_model->create($input_data);
            
            if($is_inserted) 
                $this->session->set_flashdata('success','Record created successfully.');
            else		
                $this->session->set_flashdata('error','Could not create new record!');
        }
        else
		{
			$this->session->set_flashdata('error','No request!');
		}

		redirect(base_url('Product/add_new'));
    }

After this controller function executes the message "Record created successfully" keeps popping up regardless of which page/view I'm on within the application. This is because the flash data is still present when I check for it before displaying the appropriate message on the browser using the code here in the footer section of my view file:         

        <script type="text/javascript">
            <?php if($this->session->flashdata('success')){ ?>

                PageAlert.success("Success","<?php echo $this->session->flashdata('success'); ?>");

            <?php }else if($this->session->flashdata('error')){  ?>

                PageAlert.error("An error occured","<?php echo $this->session->flashdata('error'); ?>");

            <?php }else if($this->session->flashdata('warning')){  ?>

                PageAlert.warning("Warning","<?php echo $this->session->flashdata('warning'); ?>");

            <?php }else if($this->session->flashdata('info')){  ?>

                PageAlert.info("Information","<?php echo $this->session->flashdata('info'); ?>");

            <?php } ?>
        </script>

This happens only after I moved the application to a remote server. It runs without any issues on my local XAMPP server. Is this a bug or does anybody have a solution for this.

**Comment by andichaerul** [comment]
Using Xdebug or var_dump, for trace your problem.

**Comment by sutherlandnele** [comment]
Issue was related to new line spacing before the <php> tag in my controller file.
