### ISSUE TITLE
Session conflict with Session_files_driver driver

### ISSUE THREAD

**Issue by TimotheeBoutinDAMAaas** [bcit-ci/CodeIgniter#5857]
While sending multiple call to a server with the same session ID, using the CI_Session_files_driver
we encouter some problem when reading the session file.

-------------------------------------

The filesize (line 212) reads the size of the session file which has been put in the cache at line 174 (in the fopen), but the file may have changed of content (and so of length).

See _note_ in the filesize docs : https://www.php.net/manual/en/function.filesize.php

When it occurs (multiple call at the same time, some writing things in session) the session data will be unconsistent, invalid, and so destroyed.

-------------------------------------

We patched it by the folowing way :

- Comment of the read method
- Change it to a simple fread

```

//		for ($read = 0, $length = filesize($this->_file_path.$session_id); $read < $length; $read += self::strlen($buffer))
//		{
//			if (($buffer = fread($this->_file_handle, $length - $read)) === FALSE)
//			{
//				break;
//			}
//
//			$session_data .= $buffer;
//		}
		while (($buffer = fread($this->_file_handle, 10000))) $session_data .= $buffer;


```

**Comment by narfbg** [comment]
I'm afraid your patch has the potential to do just the same in an ever subtler way, as it is possible for `fread()` to return data that would be treated as "falsy" by PHP and thus interrupting the loop (that's why we use a `for()` with calculated size).

Clearing the cache should fix it; see linked commit.
