### ISSUE TITLE
Problem with macOs 10.15 & SQL Driver

### ISSUE THREAD

**Issue by bhupalasuresh** [bcit-ci/CodeIgniter#5858]
Hi, I have upgraded my macBook Pro to Catalina(10.15), from there onwards sql drivers not working properly.

I am using

CodeIgnitor 3.1.1 framework
PHP 7.3.10
Fatal error: sqlsrv_fetch_array: Unknown exception caught. in /Users/bhupalasuresh/Sites/sqlconnect/system/database/drivers/sqlsrv/sqlsrv_result.php on line 175

**Comment by narfbg** [comment]
This is not a CodeIgniter issue; a cursory Google search for "Fatal error: sqlsrv_fetch_array: Unknown exception caught" will point you to plenty of other people having the same issue, clearly not related to any framework.
