### ISSUE TITLE
Zip library: memory optimization

### ISSUE THREAD

**Issue by humpfhumpf** [bcit-ci/CodeIgniter#5864]
Hi,

I tried to create a ZIP with 277MB of files. The allocated memory on PHP was exhausted because the Zip library seems to allocate 277MB twice (my php.ini sets the memory_limit to 512M).

The cause is get_zip() function, line 409:
```php
	return $this->zipdata
			.$this->directory."\x50\x4b\x05\x06\x00\x00\x00\x00"
			.pack('v', $this->entries) // total # of entries "on this disk"
			.pack('v', $this->entries) // total # of entries overall
			.pack('V', self::strlen($this->directory)) // size of central dir
			.pack('V', self::strlen($this->zipdata)) // offset to start of central dir
			."\x00\x00"; // .zip file comment length
```
Memory is allocated two times: one time for $this->zipdata itself, and a second time for the concatenation.
To workaround quickly this issue, I wrote a MY_Zip class, and overload this function with:
```php
	$this->zipdata .=
			$this->directory."\x50\x4b\x05\x06\x00\x00\x00\x00"
			.pack('v', $this->entries) // total # of entries "on this disk"
			.pack('v', $this->entries) // total # of entries overall
			.pack('V', self::strlen($this->directory)) // size of central dir
			.pack('V', self::strlen($this->zipdata)) // offset to start of central dir
			."\x00\x00"; // .zip file comment length
	return $this->zipdata;
```
I hope this will help you to improve this library.
Regards

**Comment by narfbg** [comment]
Well, with how often and somewhat radically the PHP engine has been changing in recent years, there's no guarantee that this would be an effective long term solution, but I guess it makes sense.

Care to submit it as a pull request instead?

**Comment by humpfhumpf** [comment]
I can try to submit a pull request

**Comment by narfbg** [comment]
Well, are you gonna? :)

**Comment by aitorres** [comment]
I can submit the Pull Request, if it is still needed!

**Comment by vlakoff** [comment]
In the first code, maybe the whole zipdata is copied again at *each* concatenation.

An improvement could be to build beforehand the footer, then concatenate only once to the zipdata:

```
$footer = $this->directory."\x50\x4b\x05\x06\x00\x00\x00\x00"
    .pack('v', $this->entries)
    .etc()
    ."\x00\x00";
return $this->zipdata . $footer;
```

That's probably the optimization that your code actually does.

So we have 2 copies for a short time : zipdata, zipdata+footer. But I guess the current code makes much more copies.

**Comment by narfbg** [comment]
Cool, I'm fine with either solution. Whoever steps up with it wins ... just don't wait on me to say "yes, I do want you to submit a pull request" for another 2 months. :D

**Comment by humpfhumpf** [comment]
Sorry for the very late reply.
When a concatenation of two string occurs, PHP does a memory allocation (ie. malloc() in C).
So, you will have 2 memory blocks: $this->zipdata and $this->zipdata . $footer.
If zipdata is big, the PHP memory will be exhausted immediatly.

If you use the .= operator, PHP does a memory reallocation (zend_string_extend() => realloc() in C) [if internal refcount of $this->zipdata is 1, which is the case here in the zip lib].
So, you will only have one block for $this->zipdata.

**Comment by vlakoff** [comment]
I thought about "left to right" processing, only guessed and haven't tested if my assertions about memory usage were exact.

However I just noticed there is a (big) issue with your proposal: you're overwriting `$this->zipdata`. So this property no longer contains the raw zip data, but the data + the footer. Suppose you call `get_zip()` twice: the second time it will give completely broken result!

**Comment by vlakoff** [comment]
By the way, if my assertions about memory usage were confirmed to be exact, the protected method `_add_data()` could be similarly optimized.

**Comment by narfbg** [comment]
Indeed, that would be a problem.

Closing this with #5893 already merged, but feel free to submit PRs with further optimizations.

**Comment by humpfhumpf** [comment]
> However I just noticed there is a (big) issue with your proposal: you're overwriting `$this->zipdata`. So this property no longer contains the raw zip data, but the data + the footer. Suppose you call the `get_zip()` method twice: the second time it will give completely broken result!

You are right. By chance, get_zip() is normally called one time, before rendering the binary zipped data to HTTP output stream.
