### ISSUE TITLE
email->send fails if "from name" is set

### ISSUE THREAD

**Issue by ahmed-mahdi-pt** [bcit-ci/CodeIgniter#5867]
I'm using Codeigniter 3.1.9
This is a sample of my test:

    $this->email->from($fromemail, $fromname)
                ->to($toemail)
                ->subject($subject)
                ->message($message);
    $this->email->attach($filepath);
    $isSent = $this->email->send();
    var_dump($isSent);

If I set $fromname, it doesn't send email ($isSent becomes false), if I remove it or keep it empty string the email is sent successfully.

Also, if using `$this->email->attach($filepath);` doesn't send email, but using `$this->email->attach($filepath, '', 'samplefilename');` it works.

**Comment by narfbg** [comment]
Unfortunately, all I can say is do what works for you.

Email is a complicated thing ... What one mail server accepts, another may reject; isSent status may also be misreported (i.e. set to false while mail was actually sent); a lot of things can go wrong.
