### ISSUE TITLE
get error when i try to customize error page on CI 3.1.11

### ISSUE THREAD

**Issue by rockmantic2018** [bcit-ci/CodeIgniter#5872]
1. when I set my error page on ```routes 404 override```, its not work. its always goes to default errors page CI ```(views/errors/html/error_404.php)```
2. when I change CI error page with mine, its work. BUT, when i try to put assets from my css, its turn "```Message: Call to undefined function base_url()```". then,
3. When I set ```$ci = new CI_Controller(); $ci =& get_instance(); $ci->load->helper('url');``` on that error page, then its will turn another error. which is "```Unable to locate the specified class: Session.php```" , when i had session on that URI

what could I do for it? is that my wrong there? helppppp

**Comment by rockmantic2018** [comment]
Its suck, sorry

**Comment by narfbg** [comment]
This is a bug tracker. Please post your help requests on our [forums](https://forum.codeigniter.com/).
