### ISSUE TITLE
Command-line "php spark serve"

### ISSUE THREAD

**Issue by RedskyThirty** [bcit-ci/CodeIgniter#5873]
I get an error when I try the command "php spark serve".
Error in French: _'C:\Program' n’est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes._
Error in English: _'C:\Program' is not recognized as an internal or external command, operable program or batch file._
I've fixed that by wrapping $php with quotes.
File "/system/Commands/Server/Serve.php", Line 142 :
`passthru('"' . $php . '" -S ' . $host . ':' . $port . ' -t ' . $docroot . ' ' . $rewrite);`

**Comment by narfbg** [comment]
Sorry, this is the CI3 repo.
