### ISSUE TITLE
Need in ISO-8601 support

### ISSUE THREAD

**Issue by paulvonlecter** [bcit-ci/CodeIgniter#5878]
https://github.com/bcit-ci/CodeIgniter/blob/0db8b60492cc98ef3c85b986fc11e9dac6d7ca6c/system/libraries/Calendar.php#L380
Need in day numeracy and day order like from ISO-8601: starting from Monday for some countries.
Also, it may need to start counting from 1 (instead of 0).
Some working example from one of my projects attached below.
[calendar_helper.php](https://github.com/bcit-ci/CodeIgniter/files/3965282/calendar_helper.txt)

**Comment by narfbg** [comment]
Sorry, but at this point `CI_Calendar` is only kept for BC purposes and not actively maintained. I've been wanting to split it from the main package for a long time, actually.
You're welcome to submit a pull request with any changes that you may want in it, but we're not spending any development time on it by ourselves.
