### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by slps970093** [bcit-ci/CodeIgniter#5879]
Array and string offset access syntax with curly braces is deprecated

`        $this->output->enable_profiler(TRUE); `

PHP Version 7.4

![圖片](https://user-images.githubusercontent.com/8385770/71050311-d6692680-217f-11ea-848f-38fc00a82dae.png)

**Comment by GLedoussal** [comment]
Can reproduce with PHP 7.4. I don't understand why this is happening, they deprecated string offset access and this is just a dynamic property name. Is this a PHP bug ?

As a workaround you can replace that line with `$this->{'_compile_' . $section} = TRUE;` and change other lines using curly braces (138 and 557)

**Comment by TalonTR** [comment]
I was pretty confused for some time by this, too - took my a while to figure it out. This notation actually creates a public array property `$this->_compile_` which is used as an associative array - keys from `$_available_sections`, `true` or `false` values. 
The correct notation would simply be `$this->_compile_[$section]`. The deprecated curly braces are used three times throughout the file.

**Comment by TalonTR** [comment]
I created a PR: https://github.com/bcit-ci/CodeIgniter/pull/5888

**Comment by TalonTR** [comment]
@narfbg wrote in https://github.com/bcit-ci/CodeIgniter/pull/5888
> Sorry, but your patch does the opposite of what it should be doing ... see 4fc777a for the correct fix.

Your fix is ok, but i´m pretty sure that you are mistaken on that. I totally understand how you arrived at this misconception, thats one of the reasons PHP deprecated this notation. The previous code `$this->_compile_{$section}` implicitly creates an array `$this->_compile` and then sets values by using $section as key.  Your fixed code now created multiple properties with different names, each concatenations of `_compile_` and `$section`. 

Nevertheless thanks for fixing this issue by removing the deprecated notation 👍

**Comment by narfbg** [comment]
I'm not mistaken.

For one, we'd never name an array `_compile_`; then there's the matching `_compile_*()` method names and last but not least, [it's practicly documented](https://github.com/bcit-ci/CodeIgniter/blob/4fc777a92942eee78f72cfc86453942bc21da020/system/libraries/Profiler.php#L121).
As a side note, if I was wrong, then while the code would technically still work, simply making a notice go away is not a fix if the code doesn't do what it was intended to. :)

Props for being vigilant though.

**Comment by TalonTR** [comment]
> For one, we'd never name an array _compile_

it happens implicitly by using this syntax: $this->_propertyName_{_$index_} = _value_

> then there's the matching _compile_*() method names

Yep, exactly, this confused me, too. PHP would allow for identical named properties & methods in parallel. 

> it's practically documented

Yep - the documentation was wrong. Only after YOUR fix it behaves like implied in the the comment in line 121.

Try for yourself or have a look at this shortened example:
http://sandbox.onlinephpfunctions.com/code/b34fc81ce7733d9b7459ec78ad9f8cceb66b1b5f

**Comment by narfbg** [comment]
Um ... The only thing I'm confused about is how you have not yet understood what I meant.

Yes, `$this->propertyName{$index}` would implicitly create an array - I am 100% aware of that - and yes, that is how the code worked until 748b2280c63e994f4153bdafb683606df8213bc3.

The documenting comment in question was only wrong in terms of not reflecting the (at the time) current code - in that sense you are correct - but what you're missing is that the comment in question documents how the code was *intended* to work. Meaning that it was the code itself that was wrong, and it only happened to work due to a lucky coincidence and nothing else.
It was always meant to create individual boolean properties and not an array.

**Comment by leo-rojas** [comment]
@narfbg hey, I know this is a few months old but do you know when the fix for this will be added to a release?  Seeing in 3.1.11 the issue is still there.

**Comment by pbarney** [comment]
@leo-rojas until 3.1.12 is released, just copy the [code](https://github.com/bcit-ci/CodeIgniter/blob/4fc777a92942eee78f72cfc86453942bc21da020/system/libraries/Profiler.php) to `application/helpers/MY_Profiler.php`. That way you can start using it now without touching the core. Just remember to remove it when 3.1.12 is released.

**Comment by xanabobana** [comment]
> > For one, we'd never name an array _compile_
> 
> it happens implicitly by using this syntax: $this->_propertyName_{_$index_} = _value_
> 
> > then there's the matching _compile_*() method names
> 
> Yep, exactly, this confused me, too. PHP would allow for identical named properties & methods in parallel.
> 
> > it's practically documented
> 
> Yep - the documentation was wrong. Only after YOUR fix it behaves like implied in the the comment in line 121.
> 
> Try for yourself or have a look at this shortened example: http://sandbox.onlinephpfunctions.com/code/b34fc81ce7733d9b7459ec78ad9f8cceb66b1b5f

Your code in the sandbox is throwing the error 
![image](https://github.com/bcit-ci/CodeIgniter/assets/7066019/77187f5d-8da2-41d5-885b-843a8738b9f3)

**Comment by xanabobana** [comment]
I'm running into this error with this line: system/libraries/Profiler.php 108
Severity: Compile Error --> Array and string offset access syntax with curly braces is no longer supported

				$this->{'_compile_'.$section} = TRUE;

This looks like what was supposed to be the working code according to this thread...what happened?

**Comment by pbarney** [comment]
> Your code in the sandbox is throwing the error

You'll notice that it's failing on the line that is commented with "// old". You have to remove that line for it to work in the sandbox.

As far as your other problem, are you _certain_ that that's the line that is creating the problem?

**Comment by xanabobana** [comment]
It gave a different error when I took out old.  

![image](https://github.com/bcit-ci/CodeIgniter/assets/7066019/548cc2c7-6829-4ea5-bb10-d952799e8808)

I was able to get my code working using:  

`$this->_compile_[$section] = TRUE`
