### ISSUE TITLE
Multidimensional Array input names not working in codeigniter 3 version but it's working in codeigniter 4 ,Core php and laravel .

### ISSUE THREAD

**Issue by gurindersarai** [bcit-ci/CodeIgniter#5880]
For example this is my form fields :>

>     <input type="text" name="day['mon']">
>     <input type="text" name="day['tue']">
>     <input type="text" name="day['wed']">
>     <input type="text" name="day['thu']">

When i post it to controller it Returns Below output if i Print it using $_POST or $this->input->post()

> Array
> (
>     [day] => Array
>         (
>             [0] => 
>         )
> 
> )

Let me know if i am doing something wrong

**Comment by euginepj** [comment]
Do you try the following: 
```
<input type="text" name="day[mon]" /> 
<input type="text" name="day[tue]" />
<input type="text" name="day[wed]" />
<input type="text" name="day[thu]" />
```

**Comment by gurindersarai** [comment]
@euginepj  I was wrong at Single Quotes . It's Working Thanks .
