### ISSUE TITLE
Form_validation library: could not get error_string() when PUT method and validation_data = array()

### ISSUE THREAD

**Issue by freeaircn** [bcit-ci/CodeIgniter#5894]
1) use PUT method, not POST
2) code:
$data = array();
$this->form_validation->reset_validation();
    $this->form_validation->set_data($data);
        if ($this->form_validation->run($rules) === false) {
            return $this->form_validation->error_string();
        } else {
            return true;
        }

problem:
could not get error_string()

**Comment by freeaircn** [comment]
version: 3.11

**Comment by narfbg** [comment]
1. If request method is relevant at all, that's only to the extent that you should know the library is built for standard HTML web forms, which is obviously not the case with a PUT request.
2. Please define what you mean by "could not get error_string()".
3. There's no 3.11 version.

**Comment by freeaircn** [comment]
Thanks for your reply. I got your point. Resolved.
Sorry, the ci version is 3.1.11.
In my case, the restful api mode is introduced. Validation for data by PUT method will be needed.
I will modify form validation based original libary only in my case.
