### ISSUE TITLE
Can't load my library if name is capitalized

### ISSUE THREAD

**Issue by tristanOry** [bcit-ci/CodeIgniter#5897]
In CI 3.1.11, when I try to load the library `Json_html`, in the file `application/libraries/Json_html.php`,  with `$this->load->library('Json_html');` (or via autoload). I have the notice ` Undefined property: Users::$Json_html` when I try to use a method in my lib, and  an error 'cause I call a method on null. If I load my lib with non capitalized name, it works.  All other loaders I try (Controllers and Models) doesn't care about capitalization and the doc about libraries say this loader too.

**Comment by narfbg** [comment]
It's really hard to understand what you're trying to say, but ... Your library will load just fine; there's no issue with *loading* it.
You're simply trying to access it the wrong way; it will always be assigned to `$this->json_html`, which is case-sensitive, because PHP variables are case-sensitive.

**Comment by tristanOry** [comment]
I understand what you say, but I have a few problems with your explanation :

- When I load a model (resp. a controller) with `$this->load->model('Name');`, I access to it with `$this->Name->SomeMethod();`.
- When I load a model (resp. a controller) with `$this->load->model('name');`, I access to it with `$this->name->SomeMethod();`.

Now when I try to load my library with `$this->load->library('lib');` and access to it with `$this->lib->SomeMethod();` all works fine.
But with `$this->load->library('Lib');` and access to it with `$this->Lib->SomeMethod();` nothing works. 

And for the ugly english I use, I'm sorry. It's the better I can use.

**Comment by narfbg** [comment]
Well, sorry but I can only suggest that you stop doing capitalization and to it all in lowercase.
