### ISSUE TITLE
Enhance $router with $router->controllerPath()

### ISSUE THREAD

**Issue by x1250** [bcit-ci/CodeIgniter#5900]
Hello:

Please implement a way to know the complete path of a given controller.
For example:
`
$router = \Config\Services::router();

var_dump([
 $router->controllerName(),
 __$router->controllerPath()__ // To implement
]);

/*
Would give:
[
 "\App\Modules\My_Module\Controllers\My_Controller",
 __"/my/path/to/codeigniter/app/Modules/My_Module/Controllers/My_Controller.php"__
]
*/
`

**Comment by narfbg** [comment]
Wrong place, this is the CI3 repo.
