### ISSUE TITLE
Please saw these review

### ISSUE THREAD

**Issue by zee85** [bcit-ci/CodeIgniter#5904]
No one can register on your forums.

https://forum.codeigniter.com/member.php

I think we could teach an Orangutan to produce a higher quality product.

I'm so happy that CI is run by such an incompetent group of individuals. It just brings a smile to my face.

**Comment by tylerwood** [comment]
sorry your girlfriend dumped you

**Comment by zee85** [comment]
taylor,

Actually I dumbed her way before she could have ever dumbed me.

**Comment by lonnieezell** [comment]
@zee85 What issues did you have creating an account? I just created a new account and it worked just fine for me. I didn't go through email verification, though, so if you're hitting a snag there, it'd be great to know so we can try and get it fixed.

**Comment by zee85** [comment]
Are you part of the current CI team?

**Comment by narfbg** [comment]
FYI, I've blocked zee85.

3 issues and multiple comments - his entire activity here, bar the last comment in this thread - have all been openly hostile, personal attacks against me. I wish there was at least a visible reason for that, but ... well, I guess some people are just like that.
