### ISSUE TITLE
narfbg fake profile

### ISSUE THREAD

**Issue by zee85** [bcit-ci/CodeIgniter#5905]
This dude doesn't even exist.

https://bg.linkedin.com/in/andreiandreev

He/she stole his profile from here.

https://bg.linkedin.com/in/andrey-andreev-943397a

**Comment by lonnieezell** [comment]
Github is for tracking bugs. Closing.

**Comment by zee85** [comment]
Github should also be used for producing quality software but since you
broke that rule I didn't think you would care about the others.
