### ISSUE TITLE
When using the failover function, setting with DSN is required (PostgreSQL)

### ISSUE THREAD

**Issue by lf-uraku-yuki** [bcit-ci/CodeIgniter#5906]
CI_DB_postgre_driver assembles the DSN string only when the constructor is executed.
Therefore, if you do not use the DSN string, you cannot connect to the failover destination properly.

I personally think that it is not always necessary to modify the code and it is good to add to the document.

**Comment by narfbg** [comment]
This is a bug though, I don't think just documenting it is appropriate.

**Comment by ivantcholakov** [comment]
Just a remainder, there is a typo here, I hope it won't be missed.
