### ISSUE TITLE
ftp class file upload: gives error but the file is uploaded

### ISSUE THREAD

**Issue by mgjuhler** [bcit-ci/CodeIgniter#5908]
codeignites behave strangely.
i am trying to upload a one file but get error message "Unable to upload the specified file. Please check your path." which seems strange since the file was uploaded. I have tried with and without passive but I get the same result. 
I have tried to change the mode but it does not change that I get the error message.

CI_VERSION: 3.1.10
PHP 7.0.33-0

Config:
```
$config['hostname'] = 'ip';
$config['username'] = 'user';
$config['password'] = 'password';
$config['debug'] = TRUE;
$config['passive'] = FALSE;

$this->ftp->connect($config);
$this->ftp->upload($fileFrom, $fileTo);
$this->ftp->close();
```

**Comment by narfbg** [comment]
We simply use the return value of `ftp_put()` to determine whether an error has occured or not. If you see that error message, it means `ftp_put()` has returned false.

I can only suggest that you provide a specific `upload()` mode (via the third parameter), but outside of that there's nothing we can do.
