### ISSUE TITLE
Install System folder in Vendor folder

### ISSUE THREAD

**Issue by cambur** [bcit-ci/CodeIgniter#5909]
I was wondering is there a way to install CodeIgniter using composer, but ignore the system folder.
I just installed this package and was happy about being able to install Codeigniter with composer, but then I noticed that the source code still outside the vendor folder.
Wonder if it is possible to install codeigniter inside the vendor file.

**Comment by narfbg** [comment]
I'm not even aware of a way to make Composer install source code outside of vendor/ and we're certainly not doing that, so ... Whatever is happening it's outside of our control.

**Comment by cambur** [comment]
> I'm not even aware of a way to make Composer install source code outside of vendor/ and we're certainly not doing that, so ... Whatever is happening it's outside of our control.

When you install codeigniter using composer, is the **/system/core** folder inside the **/vendor** folder? Maybe I did something wrong.
