### ISSUE TITLE
Bug in xss_clean() creating a hex characters in a different charset 

### ISSUE THREAD

**Issue by sjblack11** [bcit-ci/CodeIgniter#5910]
A customer entered _'... 30% about...'_ in a textbox field on one of our submission forms. We use xss_clean() on all our input data to filter out any possible XSS injections. 

An error occurred when attempting to insert the resulting text into the database (mySQL).

We tracked the offending piece of code to: 

```
	protected function _urldecodespaces($matches)
	{
		$input    = $matches[0];
		$nospaces = preg_replace('#\s+#', '', $input);
		return ($nospaces === $input)
			? $input
			: rawurldecode($nospaces);
	}
```

The issue we found was that there was a rule in the xss_clean() that searched for character injections that converted into HTML strings like: _'% 3 c script % 3 ealert(document.domain)% 3 c /script % 3 e'_.

In this case, the _'% 3 c'_ would ordinarily be stripped as it would be interpreted as a _‘<’_ character.

However, the algorithm detected _'30% about'_ as having a _'%ab'_ and thus encoded it into a character which then became incompatible with the character set we are using in the database and creating an error when inserting into the database.

We have now fixed this with the patch:

`$nospaces = preg_replace('#\s+#', '%20', $input);`

This converts whitespaces between the '%' and subsequent hex characters to an encoded space so that _'30% about'_ becomes _'30%%20about'_. This seems to solve the problem for us.

I am not an XSS expert, so if someone could provide some feedback on this, that would be much appreciated.

**Comment by narfbg** [comment]
Duplicate of #5125. I know that's not particularly helpful, but it is what it is.

What I can suggest is that you apply `xss_clean()` only during output, not before saving data to your database.

**Comment by sjblack11** [comment]
Thanks for that.

After reading the discussions I think what I did will work OK.

Appreciate the response,
Simon

**Comment by marcusnunes** [comment]
Thank you so much for this!
