### ISSUE TITLE
Accept configuration for auto transformation database model snake_case to camelCase

### ISSUE THREAD

**Issue by vallemar** [bcit-ci/CodeIgniter#5923]
Hi,

I think that accepting camelCase variables in class would be fine.
In my class I have camelcase variables that do not resemble the database, this is mysql and the columns of the database are snake_case. My problem is that when I try to launch the queries it gives an error because the column does not exist:

- My Class

![image](https://user-images.githubusercontent.com/15719383/75934187-2781e000-5e7c-11ea-8152-f80690e9b8c2.png)

- DataBase

![image](https://user-images.githubusercontent.com/15719383/75934233-3799bf80-5e7c-11ea-8eef-c4c4127e9021.png)

I have solved the problem by creating a function that transforms from camelCase to snake_case and applying it in \ system \ database \ DB_query_builder.php  (core)

`	
function snake($array = ''){
		foreach ($array as $clave => $valor) {
			$objReturn[strtolower(preg_replace('/(?<!^)[A-Z]/', '_$0', $clave))] = $valor;
		}
		return $objReturn;
	}
`

Applying it to the core...
![image](https://user-images.githubusercontent.com/15719383/75934973-3e293680-5e7e-11ea-8470-7f8a9e45de45.png)

I think the change is very small and people like me who come from the frontend or java will be very happy with life.

Thank you!

**Comment by narfbg** [comment]
It's not an ORM, we don't do mapping.
