### ISSUE TITLE
Codeigniter styling guide now returns 404

### ISSUE THREAD

**Issue by GarrettYork** [bcit-ci/CodeIgniter#5932]
This link did work a few days ago, but now only returns a 404.

https://codeigniter.com/user_guide/general/styleguide.html

**Comment by ojensen5115** [comment]
_All_ CodeIgniter 3 documentation seems to be broken, including the download and epub links

- https://codeigniter.com/user_guide/index.html
- https://codeigniter.com/data/CodeIgniter-3.1.11-userguide.zip
- https://codeigniter.com/data/CodeIgniter%20User%20Guide%203.1.11.epub

**Comment by datamweb** [comment]
> _All_ CodeIgniter 3 documentation seems to be broken, including the download and epub links
> 
> * https://codeigniter.com/user_guide/index.html
> * https://codeigniter.com/data/CodeIgniter-3.1.11-userguide.zip
> * https://codeigniter.com/data/CodeIgniter%20User%20Guide%203.1.11.epub

Now it's Ok.
