### ISSUE TITLE
All documentation is unaccessible

### ISSUE THREAD

**Issue by BarbzYHOOL** [bcit-ci/CodeIgniter#5933]
https://codeigniter.com/userguide2/database/active_record.html
https://codeigniter.com/user_guide/database/query_builder.html

404 - File Not Found

Can't find a route for 'user_guide/database/query_builder.html'.

**Comment by datamweb** [comment]
how ok.

> https://codeigniter.com/userguide2/database/active_record.html
> https://codeigniter.com/user_guide/database/query_builder.html
> 
> 404 - File Not Found
> 
> Can't find a route for 'user_guide/database/query_builder.html'.

now OK.

**Comment by BarbzYHOOL** [comment]
true, thank you
