### ISSUE TITLE
xss_clean() bypass inside script context 

### ISSUE THREAD

**Issue by ahussam** [bcit-ci/CodeIgniter#5935]
I submitted a bypass for `xss_clean()` on HackerOne and I didn't get any update for 3 months. 
I will write an XSS challenge that gonna denote this technique. So, please patch it asap. 

Please check it out here: https://hackerone.com/reports/764510

**Comment by narfbg** [comment]
Replied there.

For the public: the supposed vulnerability is code printed directly into a `<script>` tag; `xss_clean()` is not made for this and there's nothing to patch.

**Comment by ahussam** [comment]
@narfbg I replied to you there please check it out.
