### ISSUE TITLE
Session_database_driver reading in query WHERE condition

### ISSUE THREAD

**Issue by mrjemson** [bcit-ci/CodeIgniter#5937]
Seems to be a possible regression for issue #4373 in 3.1.10/3.1.11
I have attempted to migrate to database session this evening and am intermittently receiving below error on XHR calls.

> <body>
> 	<div id="container">
> 		<h1>A Database Error Occurred</h1>
> 		<p>Error Number: 1054</p><p>Unknown column 'name' in 'where clause'</p><p>UPDATE `ci_sessions` SET `timestamp` = 1585573353, `data` = '[Omitted Session Data]'
> WHERE (`name` LIKE '%%' OR `number` LIKE '%%') AND `type` IN (21,22,23,24,25) AND `corp` = '90'
> AND `id` = 'cgf2sr8akmucvetcs5sn4kupvhpni28u'</p><p>Filename: libraries/Session/drivers/Session_database_driver.php</p><p>Line Number: 261</p>	</div>
> </body>

Was running 3.1.10, but tested the same on 3.1.11 also.

The additional WHERE argument is used in the XHR query immediately before the one that returns the above error.

**Comment by narfbg** [comment]
The session library doesn't generate these WHERE conditions and #4373 has nothing to do with sessions ... Whatever the issue is, it's your own doing.

**Comment by mrjemson** [comment]
Sorry it was regression of #4374, I made a typo.
If you read my OP again, you will see that I mentioned the WHERE argument comes from the query immediately before the session query, and it is clearly the Session_database_driver throwing this error by using the additional WHERE arguments from the previous query.

**Comment by narfbg** [comment]
#4374 is a 3.0.3 issue fixed in 3.0.4 ... If there was a regression there it would've been noticed in the 4 years since that patch, but even double checking it now - a regression is impossible.

**Comment by mrjemson** [comment]
So the issue turned out to be query caching on previous queries affecting the session query.

While we could ensure to flush the cache after every function that calls it, adding into the Session_database_driver would act as a safeguard.

To ensure this, I added $this->_db->flush_cache(); to Session_database_driver.php under $this->_db->reset_query();

**Comment by narfbg** [comment]
I see ... that's a problem number 546841231844651651 caused by that query caching feature. I'll get rid of it the first chance I have, you shouldn't rely on it.
