### ISSUE TITLE
insert_id() Error with INSERT IGNORE

### ISSUE THREAD

**Issue by Andrewsuares** [bcit-ci/CodeIgniter#5942]
Hello,

I have 2 unique columns in a MySQL database. After an INSERT I need the insert_id. The query below does not return the insert_id. If I use codeigniter's insert query builder, INSERT IGNORE is not supported. Is there a solution for this? Thank You.

CI_VERSION = '3.1.11';
Database config
'dbdriver' => 'pdo',

This does not return the insert_id
$sql = "
INSERT IGNORE INTO
	`user`
(
name,
age
)
	VALUES
(
?,
?
)
";

$query =  $this->db->query(
$sql, array(
(int)$data['name'],
(int)$data['age']
));

if($this->db->insert_id() > 0) {
	return $this->db->insert_id();
}

// This does not support INSERT IGNORE
$this->db->insert('user', $data);
return $this->db->insert_id();

**Comment by michalsn** [comment]
`$this->db->affected_rows()` is here for the rescue.

Also, please use our forum for the support questions.

**Comment by Andrewsuares** [comment]
Thanks for your help!
