### ISSUE TITLE
Manual Instalation

### ISSUE THREAD

**Issue by cecilioruiz** [bcit-ci/CodeIgniter#5944]
Hi.
I have done the manual installation, unzipped the folder at www/ci4. Assigned "chmod -R 755 ci4 /".

I use docker image "php: 7.4.4-apache" with volume to local folder.

When I run: http: // localhost: 8080 / ci4 / public
  seen in browser:

> Whoops!
> 
> We seem to have hit a snag. Please try again later...

I have also downloaded a udemy course and it is the same.

 What I can do?

(I use Linux Mint)

**Comment by amehta11** [comment]
i'd say you should use codeigniter latest image instead of php:7.4.4-apache.
For example 
`image: aspendigital/codeigniter:latest`

**Comment by narfbg** [comment]
This is the CI3 repository, you seem to be looking for https://github.com/codeigniter4/CodeIgniter4. But also, we use GitHub for bug tracking, you should ask for help on our [forums](https://forum.codeigniter.com/) instead.
