### ISSUE TITLE
CI Version Upgradation from 2.1.4 to 3.1.11- HMVC Structure

### ISSUE THREAD

**Issue by tatva-170** [bcit-ci/CodeIgniter#5948]
Hello,
In one of our Codeigniter Project we are facing issues while upgrading it's version from 2.1.4 to 3.1.11.
We have followed Codeigniter Official site to upgrade the version but as we have HMVC Structure that method is not working properly.

We have followed the method mentioned in these sites - https://codeigniter.com/userguide3/installation/upgrade_300.html 
and https://www.chuongduong.net/ci3/installation/upgrade_300.html.

But by following both the sites and solving the errors after that we reached to the 404 error at last.

Can anyone please help us here? Anyone who has any idea about upgradation in HMVC structure.

Let me know if you need any information.

Thanks.

**Comment by narfbg** [comment]
This is a bug tracker, and the HMVC extension you use is a third-party package anyway ... Post on our [forums](https://forum.codeigniter.com/) instead.
