### ISSUE TITLE
Incorrect 'protect_identifiers' when using multiple tables with alias in a query builder

### ISSUE THREAD

**Issue by tenzap** [bcit-ci/CodeIgniter#5952]
In this part of the code
https://github.com/bcit-ci/CodeIgniter/blob/3.1-stable/system/database/DB_driver.php#L1853

CodeIgniter manages the case when one uses table names having aliases with 'AS'.
In the code of an app I use, there is such a call :
`$this->db->update($update_folder.' as '.$update_folder_alias.', '.$update_user_folder.' as '.$update_user_folder_alias);`

Something like this
`"table1" as "b", "table2" as "b"`
gets transformed to 
`""table1" as "b", "table2"" as "b"`

This leads to SQL errors (at least with postgresql)

**Comment by narfbg** [comment]
`update()` accepts a table name, not arbitrary SQL ... if the latter happens to work, that's completely accidental.
