### ISSUE TITLE
form_helper set_select() has undefined variable $input

### ISSUE THREAD

**Issue by anovokreschenov** [bcit-ci/CodeIgniter#5956]
set_select() function has undefined variable $input at line 734, so this function does not work without using form_validation
https://github.com/bcit-ci/CodeIgniter/blob/1428072599798395b04a545cfe483707cd2aaaca/system/helpers/form_helper.php#L734
Current:
```php
$value = (string) $value;
if (is_array($input))
```
Should be:
```php
$value = (string) $value;
$input = $CI->input->post($field, FALSE);
if (is_array($input))
```

**Comment by narfbg** [comment]
It's not undefined. Not obvious, but it is assigned inside the `elseif` here:

https://github.com/bcit-ci/CodeIgniter/blob/1428072599798395b04a545cfe483707cd2aaaca/system/helpers/form_helper.php#L728

**Comment by anovokreschenov** [comment]
Oh, sorry man, my fault ...
