### ISSUE TITLE
memcached session error

### ISSUE THREAD

**Issue by starman1108** [bcit-ci/CodeIgniter#5957]
Codeigniter version: 3.1.19
PHP version: 7.1
In my config.php
$config['sess_driver'] = 'memcached';
$config['sess_save_path'] = 'localhost:11211';

In this case, the error occured as following:

An uncaught Exception was encountered
Type: Error
Message: Call to undefined function get()
Filename: /var/www/angtalk/system/libraries/Session/drivers/Session_memcached_driver.php
Line Number: 308

In Session_memcached_drive.php 308 line, It was working well after I changed it
//$this->_memcached-get($this->_key_prefix.$id);

Is this bug?

**Comment by narfbg** [comment]
There has never been a CI 3.1.19 ... if you're referring to 3.1.9, then upgrade to the latest before asking about possible bugs, that's why we make releases.
