### ISSUE TITLE
CI_DEBUG incorrect type and fails strict validation

### ISSUE THREAD

**Issue by John-Betong** [bcit-ci/CodeIgniter#5959]
Adding the following script to index.php and to every single ./system PHP file makes the script compatible with the PHP Strict 7.?? standard:

&lt;?php DECLARE(STRICT_TYPES=1); ?&gt;

The following three files fail PHP strict validation because they "type juggle" to change the numeric to a bool:

Files: 
  ./app/Config/Boot/development.php
  ./app/Config/Boot/production.php
  ./app/Config/Boot/testing.php

// FAIL 
// defined('CI_DEBUG') || define('CI_DEBUG', 1);

// PASS:
defined('CI_DEBUG') || define('CI_DEBUG', TRUE);

These three small changes make it possible to render the Welcome page using PHP Strict Mode.

**Comment by narfbg** [comment]
This is the CI3 repo, you're in the wrong place.
