### ISSUE TITLE
Missing code formatting for migration block

### ISSUE THREAD

**Issue by arnisjuraga** [bcit-ci/CodeIgniter#5960]
Missing code formatting for 

```php spark migrate:create [filename]```

block at https://codeigniter4.github.io/userguide/dbmgmt/migration.html#create-a-migration

**Comment by otengkwame** [comment]
Hello @arnisjuraga  please open this issue at https://github.com/codeigniter4/CodeIgniter4. This is for codeigniter3.x

**Comment by arnisjuraga** [comment]
Ok, done: https://github.com/codeigniter4/CodeIgniter4/issues/3243
