### ISSUE TITLE
Links within CI3 source to user guide need a update.

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#5962]
Links such these lead to CI4 manual or to nowhere. An Example:
```php
 * @link		https://codeigniter.com/user_guide/libraries/email.html
```

A correction like this is likely pointing to the right page. (user_guide ---> userguide3).
```php
 * @link		https://codeigniter.com/userguide3/libraries/email.html
```

A mass-change within source is needed.

**Comment by sapics** [comment]
@ivantcholakov 
It looks an important issue to me, so, I make a PR to fix urls #5970.
If you find any problems in #5970, I am glad to let me know.
