### ISSUE TITLE
Allow static calls in Form Validation

### ISSUE THREAD

**Issue by akinuri** [bcit-ci/CodeIgniter#5963]
I wanted to call a static method to validate a field, but this doesn't work. For example

This
```php
$this->form_validation->set_rules(
    'phone', 'Telefon',
    array(
        'trim',
        array(
            "valid_phone",
            array(Turkish::class, "validatePhone")
        )
    ),
    array("valid_phone" => "Geçersiz")
);
```
throws an error:

> An uncaught Exception was encountered
> Type: Error
> 
> Message: Call to a member function validatePhone() on string
> 
> Filename: C:\xampp\htdocs\\...\libraries\Form_validation.php
> 
> Line Number: 730
> 
> Backtrace:
> 
> File: C:\xampp\htdocs\\...
> Line: 107
> Function: run
> 
> File: C:\xampp\htdocs\\...\index.php
> Line: 327
> Function: require_once

So I decided to examine `Form_validation.php`. This is what's in the line 730:

```php
$result = is_array($rule)
    ? $rule[0]->{$rule[1]}($postdata)
    : $rule($postdata);
```
It expects `$rule[0]` to be an object. In the [guide](https://codeigniter.com/userguide3/libraries/form_validation.html#callable-use-anything-as-a-rule), it uses an object (`$this->users_model`). Is this restriction intentional?

To make it work, I've used `call_user_func($rule, $postdata)` instead of `$rule[0]->{$rule[1]}($postdata)`.

Why is `$rule[0]->{$rule[1]}($postdata)` used instead of `call_user_func($rule, $postdata)`? Isn't `call_user_func()` more flexible? Will using `call_user_func()` cause problems that I'm, currently, not aware of?

**Comment by otengkwame** [comment]
@akinuri when you read the error message: "Message: Call to a member function validatePhone() on string" I think your class should have a function called that. And when you use "Turkish::class" I don't think you have read the documentation on Form_validation. You are rather complicating your code.

**Comment by narfbg** [comment]
Have you tried simply using `Turkish::validatePhone` in the same way that you use `trim`?

**Comment by codingpawan** [comment]
Turskish::class evaluated to be string, you need to pass instance of class.
