### ISSUE TITLE
setting csrf_protection from controller dont work

### ISSUE THREAD

**Issue by Enigma-20** [bcit-ci/CodeIgniter#5965]
When I try to set csrf_protection to true ($this->config->set_item('csrf_protection', TRUE);) from the controller the token is not generated even if the value is really setted to true and in the form the hidden imput is set <input type="hidden" name="ci_csrf_token" value=""> but with the native name value and not withe the one i setted (  $this->config->set_item('csrf_cookie_name', 'cookie_direct')  ) like if the  security library must be reloaded . 
Is there any solution?

**Comment by narfbg** [comment]
Naturally, this setting is already being used before a controller is instantiated. You can't change everything on the fly.
