### ISSUE TITLE
Code is not running

### ISSUE THREAD

**Issue by jophof** [bcit-ci/CodeIgniter#5966]
Hi,

Thanks for the good tool. One problem my minimized js code is not running :-(
I have these combined files.
If you wish II can give you the orginals as well. The errors can be seen on screenshot of the console.
![2020-06-15 08_33_37-FURST](https://user-images.githubusercontent.com/1681316/84625175-08670580-aee3-11ea-8ff6-4fec49147c49.png)

I hope you can find out what is wrong. I update the library cssmin also attached a message over the constructor solved.
![2020-06-15 08_37_10-c__xampp_htdocs_b4u_loc_v36_dev_application_libraries_cssmin php - Notepad++](https://user-images.githubusercontent.com/1681316/84625410-7b707c00-aee3-11ea-95d5-d8724676a9b2.png)

Thanks for helping

John
[cache.zip](https://github.com/bcit-ci/CodeIgniter/files/4778386/cache.zip)

**Comment by sapics** [comment]
Hi @jophof

I guess that your issue is "how to", not a bug report of CodeIgniter3.
If so, I think that you will get better answer by writing issue in stackoverflow or [community forum](https://forum.codeigniter.com/).

**Comment by narfbg** [comment]
We only accept bug reports related to CI3 here. We have no relation to this cssmin library.
