### ISSUE TITLE
getValidationRules not working if we use validationRules as string

### ISSUE THREAD

**Issue by jahmedk** [bcit-ci/CodeIgniter#5967]
Hi,
there is a problem i faced in model getValidationRules not working if we use validationRules as string in model.

![image](https://user-images.githubusercontent.com/22505794/84805123-36e8fb80-b01d-11ea-989e-76a34b67ca83.png)

i think it should update as you'd in validate method $rules is updating in validate method if it's assign as string in model

**Comment by ytetsuro** [comment]
This is the repository for CodeIgniter3.
In CodeIgniter3, the `getValidationRules` method does not exist.
Could it be that CodeIgniter4?

https://github.com/codeigniter4/CodeIgniter4

**Comment by narfbg** [comment]
Indeed, this is a CI4 issue.
