### ISSUE TITLE
Form validation is not working with PUT request directly

### ISSUE THREAD

**Issue by vahidvdn** [bcit-ci/CodeIgniter#5968]
I use config file for setting rules for my validations. This works with `POST` request:

```
$this->form_validation->run('changePassword');
```

But when the request method is `PUT`, it doesn't work and I have to set the following before validation:
```
$this->form_validation->set_data($this->req);
```

Is there any way in order to properly handle the validation in the same way for all request methods?

**Comment by aidanthewiz** [comment]
Currently, the default validation data is the $_POST array. Using the set_data method is the correct way to handle this.

Relevant User Guide Section:
https://codeigniter.com/userguide3/libraries/form_validation.html?highlight=form%20validation#validating-an-array-other-than-post
