### ISSUE TITLE
set_flashdata do not work. when your logged in or used session

### ISSUE THREAD

**Issue by rahulcs754** [bcit-ci/CodeIgniter#5977]
I am working on codeigniter 3  project. I have set some message with set flashdata . whenever I logged in  and filled some form then my set flashdata did not show.  its happen many time.

Sorry for Bad  English.

**Comment by vithultnair** [comment]
Hey Rahul,
Flashdata is working perfectly fine in CI3, something might be wrong with your code. This is how you set a flashdata in CI3

`$this->session->set_flashdata('item','value');`

If this didn't help, share the code so that we can help you with this.

**Comment by narfbg** [comment]
You can seek help on our [forums](https://forum.codeigniter.com/). This is a bug tracker.
