### ISSUE TITLE
Codeigniter ORMs functionality equivalents

### ISSUE THREAD

**Issue by vahidvdn** [bcit-ci/CodeIgniter#5979]
There are some functionalities in ORMs which is very good, but I couldn't find any equivalents in CodeIgniter. Let me tell the problem. When I want to write a join query (e.g. users join comments) the output is something like this:

```
[
	user_id:1,
	payment_id:1
],
[
	user_id:1,
	payment_id:2
],
[
	user_id:2,
	payment_id:3
],
[
	user_id:2,
	payment_id:4
],
```
The thing I want to achieve is something like this:

```
[
	user_id: 1,
	payments: [
		[
			payment_id:1
		],
		[
			payment_id:2
		],
	]
],
[
	user_id: 2,
	payments: [
		[
			payment_id:3
		],
		[
			payment_id:4
		],
	]
],
```

The same thing that I've done in `sequalize` ORM:

```JS
return Users.findAll({
    include: [{
        model: Payments,
        as: "payments"
    }]
})

```

Any idea how to achieve this?

**Comment by narfbg** [comment]
This is a bug tracker, not a place to seek "how to" help. Please ask such questions on our [forums](https://forum.codeigniter.com/) instead.

You have been warned of this multiple times before, please take a note.
