### ISSUE TITLE
ci_sessionkekkhpu5t7rs09peensd2t9tsur5vs5l file lost

### ISSUE THREAD

**Issue by wildanlsfs** [bcit-ci/CodeIgniter#5986]
i've been working on some website, then something happen 

here is the report 
`Severity: Warning

Message: fopen(D:\xampp\tmp\ci_sessionkekkhpu5t7rs09peensd2t9tsur5vs5l): failed to open stream: No such file or directory

Filename: drivers/Session_files_driver.php

Line Number: 174`

then all of my CI project has the same error...

**Comment by gxgpet** [comment]
Please post your questions on the [forums](https://forum.codeigniter.com/). GitHub is used for bug tracking.
