### ISSUE TITLE
Deprecation warning: composer.json

### ISSUE THREAD

**Issue by Bliksempie** [bcit-ci/CodeIgniter#5987]
In the "require-dev" section of the composer.json file, "mikey179/vfsStream" should become "mikey/vfsstream" (no capital) as Composer 2.0 will result in an error. Currently, using Composer 1.9.1, it only results in a deprecation warning.

```
Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.
```
Reproduce by running "composer update" to see the message on an unmodified version of the composer.json file packaged with the repo.

**Comment by narfbg** [comment]
Next release won't have the issue.
