### ISSUE TITLE
Composer: phpunit/php-token-stream and mock-objects

### ISSUE THREAD

**Issue by Bliksempie** [bcit-ci/CodeIgniter#5988]
Running "composer update" results in the following warning:

```
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
```

Of course, I understand that CI3 requires PHP 5.6 or later, and that the last version of phpunit that supported PHP 5 was phpunit 5, so not sure if this should or could be fixed.  If not, please close the ticket. You can do so silently, or very ceremoniously if you wish, if that is the case.

**Comment by gxgpet** [comment]
Well, it doesn't seem that is something we can do for it right now. I guess it will go away by the time, when a potential upgrade will happen.
