### ISSUE TITLE
log_threshold=1 does not work on Production

### ISSUE THREAD

**Issue by Andrewsuares** [bcit-ci/CodeIgniter#5990]
Hello,

I'm on the newest version of CI 3. On production, I see that log_threshold does not create log files with errors. If I change to development, the log files are created. I do not want to output the errors. I just need them logged to a file. Is it possible to enable logging errors on production? Thanks.

This is my setting.
$config['log_threshold'] = 1;

**Comment by gxgpet** [comment]
Github is used for bug tracking. You will find more help for your question on the [forums](https://forum.codeigniter.com/).
