### ISSUE TITLE
feature: custom MY_DB_Result driver

### ISSUE THREAD

**Issue by blinkinglight** [bcit-ci/CodeIgniter#5992]
https://github.com/bcit-ci/CodeIgniter/blob/18718545e0faa98d62df3f65d045d84494ec29ca/system/database/DB_driver.php#L687

**Comment by gxgpet** [comment]
The result classes are part of each driver's own implementation. Why would you want to do this?

**Comment by blinkinglight** [comment]
to aditional functionality like 2 dimensional arrays: array[table][field] for mysql https://github.com/9glt/php-codeigniter-skel/blob/master/application/core/MY_DB_mysqli_result.php
