### ISSUE TITLE
how redirect page

### ISSUE THREAD

**Issue by khushmohammad** [bcit-ci/CodeIgniter#5996]
``public function checksession(){
			$userId = session()->has('name');			
			if (!$userId) { 
				return redirect()->to(base_url()); 
	}
			
			
	}
	public function index()
	{		
			$this->checksession();
			echo view('Header');
			echo view('Dashboard/Home');
			echo view('Dashboard/footer');
		
	}

**Comment by anovsiradj** [comment]
```php
$this->load->helper('url');
redirect('somewhere');
```

u should read the docs.

**Comment by bedrijfsportaal** [comment]
I think the question is for CI4, this is CI3, by looking at the code difference,

**Comment by gxgpet** [comment]
Please ask for help on the [forums](https://forum.codeigniter.com/).
The issues here are for bug tracking.
