### ISSUE TITLE
Randomly losing session after redirect

### ISSUE THREAD

**Issue by AryaRDI** [bcit-ci/CodeIgniter#5997]
Hey guys

I read many threads about this issue and I guess it is solved in the current version 3.1.11. But I'm facing a strange issue which is I'm losing randomly the session after redirect.

Working on a project that has been integrated  with `"cartalyst/sentinel": "2.0.18"` and when I come back to the page after redirect this function which made for checking the Auth failed:

```
public function checkAuth($auth = true){
		if(!($this->user = $this->sentinel->check()) AND $auth){
			$this->session->set_userdata('requested_url', current_url());
			redirect('users/login');
		}else{
			return($this->user);
		}
	}
```

Any idea if this issue is related to Codeigniter or Sentinel? I also noticed this config file at the root of the project is doing a `session_start` I removed it and the user can not log in at all. I thought the autoloader automatically loads the `session_start()`
![image](https://user-images.githubusercontent.com/22077311/95688171-63e29f00-0c08-11eb-8c28-7ee1e4441cca.png)
I also realized that the session is not being saved in the local storage, it can be the issue for instance?

Running on Nginx, PHP 7.3

any help is appreciated!

**Comment by AryaRDI** [comment]
These changes here made it work BUT I'm doubting the issue maybe is something else that I will investigate. https://stackoverflow.com/a/42717708/6473770. I commented out these lines only

```php
		// Security is king
		ini_set('session.use_trans_sid', 0);
		ini_set('session.use_strict_mode', 1);
		ini_set('session.use_cookies', 1);
		ini_set('session.use_only_cookies', 1);

		$this->_configure_sid_length();
```

**Comment by AryaRDI** [comment]
> Hey guys
> 
> I read many threads about this issue and I guess it is solved in the current version 3.1.11. But I'm facing a strange issue which is I'm losing randomly the session after redirect.
> 
> Working on a project that has been integrated with `"cartalyst/sentinel": "2.0.18"` and when I come back to the page after redirect this function which made for checking the Auth failed:
> 
> ```
> public function checkAuth($auth = true){
> 		if(!($this->user = $this->sentinel->check()) AND $auth){
> 			$this->session->set_userdata('requested_url', current_url());
> 			redirect('users/login');
> 		}else{
> 			return($this->user);
> 		}
> 	}
> ```
> 
> Any idea if this issue is related to Codeigniter or Sentinel? I also noticed this config file at the root of the project is doing a `session_start` I removed it and the user can not log in at all. I thought the autoloader automatically loads the `session_start()`
> ![image](https://user-images.githubusercontent.com/22077311/95688171-63e29f00-0c08-11eb-8c28-7ee1e4441cca.png)
> I also realized that the session is not being saved in the local storage, it can be the issue for instance?
> 
> Running on Nginx, PHP 7.3
> 
> any help is appreciated!

In case someone faces the issue. If this issue is only happening in Chrome it's because of the security update from version 80 Google Chrome. CI team needs to update their `Session.php` code and add another option for SameSite update in Google Chrome

**Comment by bigeomaha** [comment]
@AryaRDI There is a seemingly quick fix for this, override the function, I only did this in development because I have HTTPS on other environments.

`
class MY_Security extends CI_Security {

	/**
	 * CSRF Set Cookie
	 *
	 * @codeCoverageIgnore
	 * @return	CI_Security
	 */
	public function csrf_set_cookie()
	{
		$expire = time() + $this->_csrf_expire;
		// $secure_cookie = (bool) config_item('cookie_secure');
	// BUGFIX
	//	ADDED this code to fix a known issue when not using https, in production this is forced
		if (ENVIRONMENT == 'development')
		{
			$secure_cookie = FALSE;
		}
		else
		{
			$secure_cookie = (bool) config_item('cookie_secure');
		}
	// END BUGFIX

		if ($secure_cookie && !is_https()) {
			return FALSE;
		}

		setcookie(
			$this->_csrf_cookie_name,
			$this->_csrf_hash,
			$expire,
			config_item('cookie_path'),
			config_item('cookie_domain'),
			$secure_cookie,
			config_item('cookie_httponly')
		);
		log_message('info', 'CSRF cookie sent');

		return $this;
	}

}
`

**Comment by OskarsOzols** [comment]
This is duplicate of #5791. CI needs functionality to set SameSite attribute from configuration.

**Comment by SolinSM** [comment]
I think that I faced similar problem when working on codeigniter 3, that each time redirect the session change which make me confused case I lost user and the auth failed.
so I do this in the session file driver I created called (Session_app_driver.php) it in the session library in below path:    **application->libraries->Session->drivers->Session_app_driver.php**

`<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class CI_Session_mobile_driver extends CI_Session_driver implements SessionHandlerInterface {

// protected variables ...

// constructor ...
public function __construct(&$params) {
        $CI = & get_instance();
        if ( $is_mobile ){            
            if ( !$public_service ){         // mean if it service need to be user auth
                 // get session from DB that you saved when user logged in
                $this->_session_id = $row['session_id'];
            }
         }
}



}
`

**Comment by SolinSM** [comment]
I think that your problem seem to be similar to what I faced when working on Backend in codeigniter 3, that each time redirect the session change which make me confused case I lost user and the auth failed.
so I do this in the session file driver I created called (Session_app_driver.php) it in the session library in below path: application->libraries->Session->drivers->Session_app_driver.php

```
<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class CI_Session_mobile_driver extends CI_Session_driver implements SessionHandlerInterface {

    // protected variables ...

    // constructor ...
    public function __construct(&$params) {
         $CI = & get_instance();
          if ( $is_mobile ){
               if ( !$public_service ){ // mean if it service need to be user auth
                      // check user authenticate & get session from result returned from DB
                      // Note that returned session, you saved it when user logged in
                      $this->_session_id = $row['session_id'];
                }
          }
    }
    
    public function read($session_id) {
          $session_id = ($this->_session_id == '') ? $session_id : $this->_session_id;
          ....
    }

    public function write($session_id, $session_data) {      
        $session_id = ($this->_session_id == '') ? $session_id : $this->_session_id;
         ....
         // insert data auth to DB (containing session_id , token , user_id .... etc)
         ....
    }

    public function destroy($session_id) {    
        $session_id = ($this->_session_id == '') ? $session_id : $this->_session_id;
         ....
    }    
}
```

**Comment by markomaza** [comment]
Mac users would understand you...
[](https://macsecurity.net/view/214-remove-virus-from-macbook-pro)
"The fundamental element of this plot is all about websites resolved for very brief intervals before the victim hits the benign site. These interim addresses compose a complex traffic redistribution and monetization scheme with dubious advertising networks kicking in as well. A common example is an in-between page whose URL contains a.akamaihd.net string, which is often prepended with “lkysearchds” character sequence. Other spinoffs of the Yahoo redirect hoax include shifty services like Safe Finder, Chill Tab, SearchMine, Search Pulse, Any Search Manager, and SearchLee. Their role is to tweak the victim’s browser settings and reroute the traffic further."
