### ISSUE TITLE
why style attribute is in  evil attribute 

### ISSUE THREAD

**Issue by CSShekhar** [bcit-ci/CodeIgniter#5998]
Hello 
AS you see the following  screen shot attribute style is in evil side  so can you please explain me why because it cause issue in our side 
![image](https://user-images.githubusercontent.com/57479896/96459997-62385d00-1240-11eb-9be6-7e76c97ff1d7.png)
![image](https://user-images.githubusercontent.com/57479896/96460448-d541d380-1240-11eb-9131-3c05b9ea8a3f.png)

**Comment by uuf6429** [comment]
I can't reply on behalf of the CI devs, however there are plenty of answers on the 'net for your question, for example this one: https://stackoverflow.com/a/41925838/314056
