### ISSUE TITLE
Query helper on $this->db->row() doesn't allow 0 to be returned

### ISSUE THREAD

**Issue by bedrijfsportaal** [bcit-ci/CodeIgniter#6000]
Hello,

Yesterday i've had the issue that $this->db->row() wasn't returning any 0 values, all above 0 had no issues returning as result. The result stated it hasn't any rows affected, did a direct query check against my table and that seems to be working just fine.

**Query**
`SELECT ToggleSidebar FROM UsersPreference WHERE UserId = 1 LIMIT 1`

As told direct query request had no issue returning 0 as a value on this column, have found a quick work around that seems to work. Returning it in a result_array() with the first index and column name can see the 0 value on that result.

I think when return a single row with $this->db->row() it is stripping 0 as a NULL value so the query is telling me no rows found.

Please let me know if you require more information on this.

**Comment by narfbg** [comment]
What CI version is this on?
