### ISSUE TITLE
order_by() use NULLS LAST, NULLS FIRST with sorting

### ISSUE THREAD

**Issue by mlukac89** [bcit-ci/CodeIgniter#6001]
I recently had issue with ordering columns in database where i had null in columns.

Problem was that i wasn't able to add NULLS LAST or NULL FIRST with sorting, so problem was solved by changing `order_by()` function in "system/database/DB_query_builder.php"

```
public function order_by($orderby, $direction = '', $escape = NULL) {
    ................
    // replaced
    // $direction = in_array($direction, array('ASC', 'DESC'), TRUE) ? ' '.$direction : '';
   
    // replaced with
    $direction = in_array($direction, array('ASC', 'DESC', 'ASC NULLS FIST', 'ASC NULLS LAST', 'DESC NULLS FIRST', 'DESC NULLS LAST'), TRUE) ? ' '.$direction : '';
    ................
}
```
So now it can be used like 
`$this->db->order_by('column', 'desc nulls first');`
`$this->db->order_by('column', 'desc nulls last');`
`$this->db->order_by('column', 'asc nulls first');`
`$this->db->order_by('column', 'asc nulls last');`

Can this be fixed in original files ?

**Comment by orionstar** [comment]
NULLS FIRST & NULLS LAST are only Postgre and Oracle thing if I remember correctly... The query builder have to be cross db compatible. So I don't think it's a good idea... What db engine do you use?

**Comment by mlukac89** [comment]
> NULLS FIRST & NULLS LAST are only Postgre and Oracle thing if I remember correctly... The query builder have to be cross db compatible. So I don't think it's a good idea... What db engine do you use?

I am using Postgresql
