### ISSUE TITLE
add new function in class CI_Input

### ISSUE THREAD

**Issue by amin007** [bcit-ci/CodeIgniter#6008]
in class CI_Input we have 

```
	/**
	 * Fetch an item from the POST array
	 *
	 * @param	mixed	$index		Index for item to be fetched from $_POST
	 * @param	bool	$xss_clean	Whether to apply XSS filtering
	 * @return	mixed
	 */
	public function post($index = NULL, $xss_clean = NULL)
	{
		return $this->_fetch_from_array($_POST, $index, $xss_clean);
	}

```

but what if so many array in $_POST to handle.

if i add new method like 

```
	// --------------------------------------------------------------------

	/**
	 * Fetch an item from the POST array - Amin Godek Sebab MIT
	 *
	 * @param	mixed	$keyPost	if $_POST so many array
	 * @param	mixed	$index	Index for item to be fetched from $_POST
	 * @param	bool	$xss_clean	Whether to apply XSS filtering
	 * @return	mixed
	 */
	public function postMulti($keyPost = null, $index = NULL, $xss_clean = NULL)
	{
		return $this->_fetch_from_array($keyPost, $index, $xss_clean);
	}

```
can i do that?

**Comment by narfbg** [comment]
What do you mean by "if $_POST so many array"?

**Comment by amin007** [comment]
@narfbg 

in my form i use input like this

<input type="text" name="mytable1[name]">
<input type="text" name="mytable2[name]">

and my $_POST like this
$_POST['myTable']['name']
$_POST['myTable2']['name']

**Comment by narfbg** [comment]
If I understand your problem correctly, you could use this: `$this->input->post('mytable[name]')`
Or you know ... just stop using arrays in forms, it's not a good practice.

If not, it's really hard to understand what you mean and the core classes are extendable anyway ...
