### ISSUE TITLE
travis-ci.org will be closed by Dec 31st, 2020

### ISSUE THREAD

**Issue by sapics** [bcit-ci/CodeIgniter#6010]
https://docs.travis-ci.com/user/migrate/open-source-repository-migration#q-when-will-the-migration-from-travis-ciorg-to-travis-cicom-be-completed

travis-ci.org will be closed by Dec 31st, 2020. It would be better to migrate to travis-ci.com before closed.

**Comment by totoprayogo1916** [comment]
The big question is: Where's the developers?

**Comment by gxgpet** [comment]
Well, I think someone with access to the travis-ci.org CI account should perform the migration?

**Comment by sapics** [comment]
I think that it is better to move from travis-ci to github actions, so I close the issue.
