### ISSUE TITLE
error in php 7.4

### ISSUE THREAD

**Issue by nunnu1** [bcit-ci/CodeIgniter#6017]
An uncaught Exception was encountered

Type: Error

Message: Call to undefined method CI_Form_validation::substr()

Filename: /system/libraries/Form_validation.php

Line Number: 1242

Backtrace:

File: /application/controllers/Welcome.php
Line: 84
Function: run

File: /index.php
Line: 315
Function: require_once
@narfbg

**Comment by gxgpet** [comment]
There is no `substr` method in the `CI_Form_validation` class. 
If you have any issues with your own application, please ask for help on the [forums](https://forum.codeigniter.com/).
