### ISSUE TITLE
how to create pagination codeigniter 4

### ISSUE THREAD

**Issue by Rothy99** [bcit-ci/CodeIgniter#6018]

**Comment by Rothy99** [comment]
How to create pagination in codeigniter 4

**Comment by gxgpet** [comment]
Hello! This is the CodeIgniter 3 repository. For bugs and issues related to CodeIgniter 4, please use [this repo](https://github.com/codeigniter4/CodeIgniter4). If you need any help regarding your own application, please see [the forums](https://forum.codeigniter.com/).
