### ISSUE TITLE
There are some strange issue of redirect  session issue 

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [bcit-ci/CodeIgniter#6020]
Hello 

i have faced issue sometime when is add data and then sometime stuck all everything 
so here  i am using set ```session->flashdata``` then redirect url 
but some time side stuck or loading not response 

i think is something session issue 

Following Code 
User controller code 
```
class Users extends CI_Controller 
{
	public function __construct()
	{
		parent:: __construct();
	}


	public function Add()
	{

        $this->view_data = [];

		if($this->input->post() ){
            
            $config=[
                array(
                    'field' => 'user_name',
                    'label' => 'user name',
                    'rules' => 'required'
                ),
            ];


            $this->form_validation->set_rules($config);
            if ($this->form_validation->run()){

                $this->session->set_flashdata('success','Successfully added');
                redirect(base_url('Users/Add'));
            }else{
                $this->view_data['error'] = validation_errors();
            }

		}

        $this->load->view("user",$this->view_data);
	}

}
```

view file code 
```
<?php 
    
    $success = $this->session->flashdata('success');
    if( $success != "" ){
        echo  $success;
    }

?>
```

**Comment by gxgpet** [comment]
Hello! For questions and help related to your own app code, please use [the forums](https://forum.codeigniter.com/). We use GitHub to track bugs and issues related to the framework itself.

Also, based on the latest changes, you may have a look at #6013.

**Comment by narfbg** [comment]
@gxgpet If you believe this is the same issue as #6013, please tag it with the "Duplicate" label.
