### ISSUE TITLE
ini_get('mbstring.func_overload') is deprecated as of PHP 7.2.0 and removed as of PHP 8.0.0

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/CodeIgniter#6021]
Within several files the following routine statement exists:

```php
isset(self::$func_overload) OR self::$func_overload = (extension_loaded('mbstring') && ini_get('mbstring.func_overload'));
```

For avoiding notices or errors this statement should be modified in several places, I've found this example:

```php
isset(self::$func_overload) OR self::$func_overload = (defined('MB_OVERLOAD_STRING') && ((int) @ini_get('mbstring.func_overload') & MB_OVERLOAD_STRING));
```

I don't see a way the @-operator to be removed.

**Comment by gxgpet** [comment]
I'm not sure if this change is really required. The way I see it: 

* the multibyte function overloading feature is removed. This means that a call to the `strlen()` will no longer be a proxy call to `mb_strlen()` anymore in all possible situations.
* the INI config `mbstring.func_overload` no longer exists, and thus, `ini_get()` returns with `FALSE`.

I see that you are speaking about some notices and errors. Can you please provide some examples of those? I'm not sure if they are related to the multibyte function overloading.

(for reference: I used the `CI_Session_files_driver` as example)

**Comment by ivantcholakov** [comment]
@gxgpet I personally haven't seen such a warning. I use PHP8 and ini_get('mbstring.func_overload') silently return FALSE. But I am not sure what would happen on PHP 7.2, PHP 7.3 and PHP 7.4.

Here is the place I noticed this topic, there are other simolar fixes on other place too:

https://github.com/voku/portable-utf8/issues/70

https://github.com/voku/portable-utf8/commit/dd1b81a1aac190784ed65534e30ace7996d24632

**Comment by gxgpet** [comment]
Ah, I see. So we could encounter a deprecation notice. Well, according to the environments' default error reporting, a `production` one should never report this error. However, a `development` env will report it, and I personally don't see this as an issue, but rather how should such env behave. 

Anyway, if you still consider this, you could submit a PR for adding the `@` operator to that `ini_get()` call.
