### ISSUE TITLE
mp4 application/octet-stream

### ISSUE THREAD

**Issue by Andrewsuares** [bcit-ci/CodeIgniter#6023]
Hello,

Currently do_upload detects mp4 files as an application/octet-stream and the upload fails. I need to add this MIME for mp4 uploads to work correctly. Is this safe? or would it open up a security hole? Thanks.

'mp4' => array('video/mp4', 'application/octet-stream'),

**Comment by gxgpet** [comment]
Hello! While not directly a duplicate, this issue could give you some insights: https://github.com/bcit-ci/CodeIgniter/pull/2510#issuecomment-20405281. 

As for any security concerns: you should _always_ validate the user input. MIME type detection is just being used for detecting a file type, and even so, it's not bullet-proof.
