### ISSUE TITLE
Bug: potential redis session error

### ISSUE THREAD

**Issue by kenjis** [bcit-ci/CodeIgniter#6030]
**Describe the bug**
Multiple Ajax communications at the same time sometimes result in session errors.
In rare cases, a key is created by another process between the time the `$ttl` is retrieved and the time the key is set.

Reported: (Japanese) <https://groups.google.com/g/codeigniter_jp/c/h65Q7KZtDN4/m/Ef_Vl8DmAAAJ>.

**Affected module(s)**
CI_Session_redis_driver
https://github.com/bcit-ci/CodeIgniter/blob/0648ae2acb3fae84f2cc49e15edb345ccef6cad5/system/libraries/Session/drivers/Session_redis_driver.php#L420-L443

**Expected behavior**
Use [setnx](https://redis.io/commands/setnx) to acquire the lock.
If it fails, retry after some time.

Improved code from the original report:
```php
protected function _get_lock($session_id)
{
   //log_message('error', 'lock' . getmypid() . date(' i:s'));
   // PHP 7 reuses the SessionHandler object on regeneration,
   // so we need to check here if the lock key is for the
   // correct session ID.
   if ($this->_lock_key === $this->_key_prefix.$session_id.':lock')
   {
      return $this->_redis->setTimeout($this->_lock_key, 300);
   }

   // 300 attempts(about 30 second) to obtain a lock, in case another request already has it
   $lock_key = $this->_key_prefix.$session_id.':lock';
   $attempt = 0;
   do
   {
      // Use setnx to perform exclusions with other processes using the lock key. Loop if the lock key cannot be set.
      $result = $this->_redis->set($lock_key, time(), array('nx', 'ex' => 300));
      if ( ! $result)
      {
         usleep(100000);
         continue;
      }
      $result = $this->_redis->setex($lock_key, 300, time());
 
      $this->_lock_key = $lock_key;
      break;
   }
   while (++$attempt < 300);
   if ($attempt === 300)
   {
      log_message('error', 'Session: Unable to obtain lock for '.$this->_key_prefix.$session_id.' after 300 attempts, aborting.');
      return FALSE;
   }

   $this->_lock = TRUE;
   return TRUE;
}
```

**Comment by narfbg** [comment]
I can't read Japanese, so I can't understand what the issue really is.
Also, it's hard to compare code like that ... can you submit a PR?

**Comment by kenjis** [comment]
The issue is a race condition.

- In rare cases, a key is created by another process between the time the $ttl is retrieved and the time the key is set.
- It makes error.

I submitted a PR #6031. I modified the Improved code to change the existing CI3 code as little as possible.
But I'm not a redis user. I'm not sure the PR is correct.

**Comment by narfbg** [comment]
As I just said in #6031, there's no way to really fix this, it's only possible to hide the error.
