### ISSUE TITLE
Add backup logic for pdo_utility.php

### ISSUE THREAD

**Issue by generalludd** [bcit-ci/CodeIgniter#6032]
Currently there's a stub for the protected function _backup($params = array()) in pdo_utility.php. Very little needs to be altered from the mysqli_utility.php method for it to work with PDO.

**Comment by narfbg** [comment]
PDO isn't just another way to connect to MySQL. If you want to implement the MySQL backup functionality, you'd have to do it in the pdo_mysql subdriver - feel free to submit a PR for that, but it's not as simple as just copy-pasting code from one driver to another.
