### ISSUE TITLE
The file you download from the official page is wrong

### ISSUE THREAD

**Issue by Temepest74** [bcit-ci/CodeIgniter#6034]
If you download the CodeIgniter 3 from here: https://codeigniter.com/download you can clearly see in the composer.json file vfsStream instead of the vfsstream (capitalization of the Stream word).

If you download the code from GitHub, this mistake is solved. It looks like the files are not synced properly, this issue was solved here: https://github.com/TYPO3/Fluid/issues/432

**Comment by narfbg** [comment]
It's not wrong and there's nothing out of sync. We just haven't had a release with the updated composer.json yet and you're downloading a development version from GitHub.
