### ISSUE TITLE
insert_batch 中的for遇到Duplicate entry会中断

### ISSUE THREAD

**Issue by lifetin** [bcit-ci/CodeIgniter#6037]
for ($i = 0, $total = count($this->qb_set); $i < $total; $i += $batch_size)
换成
foreach($this->qb_set as $k=>$v){

这样就不会中断

**Comment by gxgpet** [comment]
Hello!

Please use only English when opening issues here, so everyone can understand. 
If you need help with your own project, please use the [forums](https://forum.codeigniter.com/) instead.
