### ISSUE TITLE
DB cache_on errors older CI

### ISSUE THREAD

**Issue by RoyvanEmpel** [bcit-ci/CodeIgniter#6039]
Hello!

We have got a system running on `Pryo2.2` with `CI 3.0-dev` for a few years now and wanted to turn on the DB `cache_on` option in `database.php`. Now when trying that it spits out an error from `codeigniter.php`, looking on the internet and also this github the only solution is to update/reinstall CI but since our system has become so big and has patches in it to get it working right on PHP 7.2 this isn't a option for us (we tried it but that would take days).

```
Fatal error: Uncaught Error: Class 'CI_Controller' not found in /var/www/project/system/codeigniter/core/CodeIgniter.php:229 
Stack trace: #0 /var/www/project/system/codeigniter/database/DB_cache.php(43): get_instance() 
    #1 /var/www/project/system/codeigniter/database/DB_driver.php(1355): CI_DB_Cache->__construct(Object(CI_DB_mysqli_driver)) 
    #2 /var/www/project/system/codeigniter/database/DB_driver.php(345): CI_DB_driver->_cache_init() 
    #3 /var/www/project/system/codeigniter/database/DB_driver.php(829): CI_DB_driver->query('SHOW TABLES FRO...') 
    #4 /var/www/project/system/codeigniter/database/DB_driver.php(871): CI_DB_driver->list_tables() 
    #5 /var/www/project/system/cms/libraries/MX/Router.php(78): CI_DB_driver->table_exists('core_domains') 
    #6 /var/www/project/system/cms/libraries/MX/Router.php(51): MX_Router->locate(Array) 
    #7 /var/www/project/system/codeigniter/core/Router.php(226): MX_Router->_validate_request(Array) 
    #8 /var/www/project/system/codeigniter/core/Router.php(382): CI_Router->_set_r in /var/www/project/system/codeigniter/core/CodeIgniter.php on line 229
```

Error in CodeIgniter.php:
```
require BASEPATH.'core/Controller.php';
/**
 * Reference to the CI_Controller method.
 *
 * Returns current CI instance object
 *
 * @return object
 */
function &get_instance()
{
    return CI_Controller::get_instance();
}
```

Coming from DB_cache.php
```
/**
 * Database Cache Class
 *
 * @category	Database
 * @author		EllisLab Dev Team
 * @link		http://codeigniter.com/user_guide/database/
 */
class CI_DB_Cache {
    public $CI;
    public $db;	// allows passing of db object so that multiple database connections and returned db objects can be supported
    public function __construct(&$db)
    {
        // Assign the main CI object to $this->CI and load the file helper since we use it a lot
	$this->CI =& get_instance();
	$this->db =& $db;
	$this->CI->load->helper('file');
    }
```

Now am I hoping that anyone here is willing to help me figure out what is causing the problem since we have been working on it for more then a day now. It looks like it's erroring from the first ran query `"SHOW TABLES FROM DB"` this is only happening when I turn on the cache_on setting. I don't know if Pyro is the problem or because Pyro used CI version 3.0-dev and the caching wasn't working at the time, can't really find any solution on google.

If I need to add more info then I will be happy to do so.

Greetings Roy

**Comment by narfbg** [comment]
Sorry, the answer here will always be to get the latest official CI version. You might have better luck asking for help on our [forums](https://forum.codeigniter.com/), but honestly I wouldn't count on it.

**Comment by dtsw** [comment]
are you sure it's the SHOW TABLES SQL? because it says "Class 'CI_Controller' not found" - so i rather think it does not find the class.

**Comment by RoyvanEmpel** [comment]
> are you sure it's the SHOW TABLES SQL? because it says "Class 'CI_Controller' not found" - so i rather think it does not find the class.

The file is requered 8 lined above it so it is loaded. Even when the required is put in the function it self it says that it isn't loaded. It runs the SHOW TABLES query and FROM there it at sometime will need the this->ci and then it dies.

**Comment by dtsw** [comment]
but your db user is allowed to issue that failing SQL statement? May be the error message is just misleading as i read here https://eftakhairul.com/weird-error-fatal-error-class-ci_controller-not-found-in-codeigniter-framework/ it was a similar error message but a completely different problem. I dont know if debugging it will help you?

**Comment by RoyvanEmpel** [comment]
> but your db user is allowed to issue that failing SQL statement? May be the error message is just misleading as i read here https://eftakhairul.com/weird-error-fatal-error-class-ci_controller-not-found-in-codeigniter-framework/ it was a similar error message but a completely different problem. I dont know if debugging it will help you?

If I turn the cache_on setting off everything works at it is suppost to. Also running the SHOW TABLES query.

**Comment by narfbg** [comment]
I know people want to help, but this is not the place.
