### ISSUE TITLE
FR: Move non public content inside 'private' folder

### ISSUE THREAD

**Issue by narcisgarcia** [bcit-ci/CodeIgniter#6040]
As "index.php" and other files are in `public` subfolder, my feature request is for moving rest of files to `private` subfolder at same root-level as `public` one.

This way, separation of components will be more clear and clean on hosting management.

**Comment by narfbg** [comment]
This is the CodeIgniter 3 repository, you're looking for https://github.com/codeigniter4/CodeIgniter4.
