### ISSUE TITLE
I'm using PHP version 7.4 can anyone help me to change the composer.json? because when I print my pdf it keeps failing

### ISSUE THREAD

**Issue by SahabatTugas** [bcit-ci/CodeIgniter#6046]
I'm using PHP version 7.4 can anyone help me to change the composer.json? because when I print my pdf it keeps failing

**Comment by feryardiant** [comment]
Throw that question to the community, dude. Since that's not CI issue.

**Comment by gxgpet** [comment]
Hi there! If you have any questions or need help with your own project, please check the [forums](https://forum.codeigniter.com/). We use GitHub for tracking issues and bugs related to the framework itself.
