### ISSUE TITLE
form_validation Preprocessing of html code in form validation does not take effect

### ISSUE THREAD

**Issue by badguyp** [bcit-ci/CodeIgniter#6048]
1.Type in the input box
![image](https://user-images.githubusercontent.com/57091435/121506709-8b4b6f00-ca16-11eb-8f40-62678c1b6106.png)
2.Receive data in the background and verify the data format and data preprocessing
![image](https://user-images.githubusercontent.com/57091435/121506965-ce0d4700-ca16-11eb-8f5e-6a415f687198.png)
3.Determine whether the verification rule is passed, and print the preprocessed data after passing
![image](https://user-images.githubusercontent.com/57091435/121507056-e1201700-ca16-11eb-8512-606c10808bc2.png)
4.Data preprocessing did not take effect
![image](https://user-images.githubusercontent.com/57091435/121506660-7ff84380-ca16-11eb-9b27-21deb7850901.png)
5.My CI version is 3.1.11
![image](https://user-images.githubusercontent.com/57091435/121507446-36f4bf00-ca17-11eb-966b-b81a036ced67.png)
My English is not very good, I hope I have described my problem clearly, I look forward to your reply, thank you

**Comment by narfbg** [comment]
Please provide actual code instead of selective images of code.
