### ISSUE TITLE
system/core/output.php  get_header() function is problem with php8 

### ISSUE THREAD

**Issue by usback** [bcit-ci/CodeIgniter#6050]
public function get_header($header)
	{
		// Combine headers already sent with our batched headers
		$headers = @array_merge(
			// We only need [x][0] from our multi-dimensional array
			@array_map('array_shift', $this->headers),
			headers_list()
		);

		if (empty($headers) or empty($header)) {
			return NULL;
		}

		// Count backwards, in order to get the last matching header
		for ($c = count($headers) - 1; $c > -1; $c--) {
			if (strncasecmp($header, $headers[$c], $l = self::strlen($header)) === 0) {
				return trim(self::substr($headers[$c], $l + 1));
			}
		}

		return NULL;
	}

**Comment by narfbg** [comment]
Care to explain what this is about?

**Comment by usback** [comment]
php8.0 version has problem with @array_map('array_shift', $this->headers), 
so need to change or array_merge need to change.

**Comment by narfbg** [comment]
Well, good thing #6074 resolved this, because I still would've had no clue what you're saying.

**Comment by usback** [comment]
thank you
