### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [bcit-ci/CodeIgniter#6051]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by narfbg** [comment]
We may add a security.md in the future, but as of right now, we have a security@ mail and a hackerone page linked in our quite short readme. I don't at all think it is hard to find those contact routes.

**Comment by JamieSlome** [comment]
@narfbg - deeply apologize for the delayed response here!

Sure, we can send those over to you via e-mail! 👍 

Otherwise, feel free to view the reports directly here:

https://www.huntr.dev/bounties/95ed8835-9f90-4ad6-9ff7-184e8645413f/
https://www.huntr.dev/bounties/2168f96d-678a-4d43-9951-2d6f415611e5/
https://www.huntr.dev/bounties/106c6ab8-4eb8-4538-85c3-e868515eeea5/

**Comment by narfbg** [comment]
I can't those because I'm not registered on that site. Even if I did register, I assume I'd need to request permissions.
Frankly, this whole thing here looks like just an marketing campaign for your product ...

**Comment by JamieSlome** [comment]
@narfbg - just sent an e-mail to your security contact - cheers!

**Comment by michaellrowley** [comment]
Any update on this? Also, @JamieSlome could the maintainer be provided with a no-login link to https://huntr.dev/bounties/af65e7d1-5367-4ec4-90b9-71360160c5d3/, too?

**Comment by JamieSlome** [comment]
@michaellrowley - I sent a magic URL in February, but happy to re-send if needed?

**Comment by michaellrowley** [comment]
Oh I hadn't noticed that you sent one in February, nevermind!

**Comment by narfbg** [comment]
Sorry for the delay on this. I hadn't received the email in question due to an issue on our end and just now had someone forward it to me.

I've addressed the reported issues, they're all invalid.
