### ISSUE TITLE
Email Validation Rule allows Invalid Email

### ISSUE THREAD

**Issue by itsmemanoj** [bcit-ci/CodeIgniter#6052]
Please check the link, i have posted it in stackoverflow. Please help if anyone knows about it.

https://stackoverflow.com/questions/68418835/validate-email-in-codeigniter-3?noredirect=1#comment120921355_68418835

**Comment by narfbg** [comment]
Please check a link yourself: https://datatracker.ietf.org/doc/html/rfc5322
