### ISSUE TITLE
Deprecated When updating to php 7.4 on ci 3.1.11

### ISSUE THREAD

**Issue by qamarhafeez** [bcit-ci/CodeIgniter#6059]
Deprecated: Array and string offset access syntax with curly braces is deprecated in /xyz/system/libraries/Profiler.php on line 108

Deprecated: Array and string offset access syntax with curly braces is deprecated in /xyz/public_html/system/libraries/Profiler.php on line 138

Deprecated: Array and string offset access syntax with curly braces is deprecated in /xyz/public_html/system/libraries/Profiler.php on line 557

**Comment by otengkwame** [comment]
Please check the version again, everything seems to be working

**Comment by karthik-code** [comment]
This error occurs when we have enabled profiler. Using version CI 3.1.11, PHP 7.4.3

**Comment by narfbg** [comment]
Duplicate of #5879.
