### ISSUE TITLE
Cookie sess_expire_on_close has no effect if session_lifetime is set. THESE ARE TWO SEPARATE THINGS 

### ISSUE THREAD

**Issue by otheus** [bcit-ci/CodeIgniter#6060]
In https://github.com/bcit-ci/CodeIgniter/blob/0648ae2acb3fae84f2cc49e15edb345ccef6cad5/system/libraries/Session/Session.php#L252 the code is wrong. It should simply be:

                        $params['cookie_lifetime'] = config_item('sess_expire_on_close') ? 0 : (int) $expiration;

session-expiration time and cookie-lifetime are two different things. It's reasonable to set session-expiration to 0 so that the *session* does not expire, while setting the cookie_lifetime independently. Or, have a limit to the session-expiration, while ensuring all cookies are deleted when the window is closed. The original code confounds these two by giving precedence to the session-lifetime. 

CodeIgniter4 appears to have the same problem, but there does not appear to be a 'sess_expire_on_close' option.

**Comment by narfbg** [comment]
`sess_expire_on_close` is a legacy setting that existed in CI2 and that piece of code is just an old fallback for people who migrated up from that and have broken config files. You shouldn't have it in CI3 and there's nothing wrong here.
