### ISSUE TITLE
Allow csrf cookies to end with the browser-close

### ISSUE THREAD

**Issue by otheus** [bcit-ci/CodeIgniter#6061]
https://github.com/bcit-ci/CodeIgniter/blob/0648ae2acb3fae84f2cc49e15edb345ccef6cad5/system/core/Security.php#L268

should instead be:

                $expire = empty($this->_csrf_expire) ? 0 : time() + $this->_csrf_expire;

This allows the admin/application to set the value to 0 so that cookies are not retained by the browser at all. The incredibly small risk of this cookie being leaked and then hijacked is mitigated by browser restarts.

**Comment by narfbg** [comment]
The "incredibly small risk" is your own assessment and I personally haven't restarted my browser in over a month, so that mitigation isn't applicable to everybody.
