### ISSUE TITLE
Can't access OS environment variables

### ISSUE THREAD

**Issue by pentago** [bcit-ci/CodeIgniter#6065]
I'm (_DevOps, not a PHP dev_) trying to help team deploy the application and providing configuration (API endpoints, database server IP/user/pass) via OS environment variables but whatever we try, we can't read OS environment variables.

I know for a fact that Laravel can read OS environment and CI3 potentially can too.

Any suggestion or this is some sort of bug?

Our stack is:
Nginx + PHP-FPM

**Comment by narfbg** [comment]
If your PHP can, so can CodeIgniter. Even if it's possible, we don't put any such limitations and no bug can cause this.
You might want to ask for help on our [forums](https://forum.codeigniter.com/) or StackOverflow; we only deal with bug reports here.
