### ISSUE TITLE
Composer 2.0 error: mikey179/vfsStream is invalid

### ISSUE THREAD

**Issue by philsturgeon** [bcit-ci/CodeIgniter#6072]
Hey folks. Long time since I've posted here, but I've just found an issue using CodeIgniter 3 with Composer 2.

```
composer create-project CodeIgniter/framework ci3-php8
Creating a "CodeIgniter/framework" project at "./ci3-php8"
Installing codeigniter/framework (3.1.11)
  - Downloading codeigniter/framework (3.1.11)
  - Installing codeigniter/framework (3.1.11): Extracting archive
Created project in /Users/phil/src/cloudbeds/ci3-php8


  [RuntimeException]
  require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please us
  e mikey179/vfsstream instead.
```

I switched my composer.json to this and it worked fine: 

```
"require-dev": {
		"mikey179/vfsstream": "1.1.*",
```

Looks like this was changed a long time ago in develop, so perhaps somebody could tag up a release real quick?

@narfbg you still here? :D

**Comment by narfbg** [comment]
Yes, I am not nearly as involved nowadays, but I'm still around. Good to see from you Phil. :)

develop is actually supposed to become 3.2, but of course we should tag the next 3.1.x sometime soon ... It's been awhile and more than enough changes have been accumulated.

**Comment by philsturgeon** [comment]
Thank you! I think a quick 3.1.12 or 3.2 would be useful even if it’s not full PHP 8 compatibility it’s solving a lot of problems.

**Comment by yurii-github** [comment]
hello guys

I've been assigned to a project on CodeIgniter3 and I wanted to ask you if you need and would accept my help by upgrading CodeIgniter3 so it can run on PHP 7.4 - 8.1 ?

At the moment I see 3 options for my self:
- private repository of the framework with my patches
- make PRs to get new official release
- use some patching tweaks after composer install

regards

**Comment by gxgpet** [comment]
Hi @yurii-github,

Thank you for using CI 3! The framework is already working with PHP 7.*, [has a PR for adding PHP 8.0 support](https://github.com/bcit-ci/CodeIgniter/pull/6066), and I'm planning to submit a PHP 8.1 compatibility PR, as well, soon.

But yes, you can submit any patches and/or fixes, too. In the end, that's why this is an open-source project. :D

**Comment by philsturgeon** [comment]
@gxgpet can we start merging some of these PRs that add PHP 8 compatability? I combined various PRs to make a mega one, but there's a random error I don't know how to fix. Would you take a look? #6074

**Comment by yurii-github** [comment]
> Hi @yurii-github,
> 
> Thank you for using CI 3! The framework is already working with PHP 7.*, [has a PR for adding PHP 8.0 support](https://github.com/bcit-ci/CodeIgniter/pull/6066), and I'm planning to submit a PHP 8.1 compatibility PR, as well, soon.
> 
> But yes, you can submit any patches and/or fixes, too. In the end, that's why this is an open-source project. :D

nice, thank you! Then my plan is next.
I have started to investigate codebase and I see there are some unreleased changes under version '3.1.2'. Thankfully to simplicity of the framework I will take ownership of it in my project by copying 'system' folder into project repository and do my fixes there, meanwhile monitoring your changes. 

 in the end of project's migration journey I will produce several PRs back to framework's repository.. it looks like a win-win situation.
 
 have a nice day!
