### ISSUE TITLE
How to exit normally in my controller

### ISSUE THREAD

**Issue by yongplus** [bcit-ci/CodeIgniter#6075]
I wrote a global function below called `outputJSON` in my project to print JSON and exit.

```
/**
 * 格式化Json输出并终止程序
 */
function outputJson($status, $msg='', $data=''){
    //header("content-type:application/json");
    \Config\Services::response()->setBody(json_encode(['code'=>$status, 'msg'=>$msg, 'data'=>$data]))->send();
    die();
}
```
I found a problem when I call PHP native functions "exit/quit" to terminate my program，The rest codes of CI4 framework after running the controller weren't be executed, Such as the After Filter mechanism, Send Response, and Release some instances.

I think calling the exit/quit function to terminate directly my program that is really more convenient than returning recursively in some cases. 

Is there any way or more friendly function offered by CI4 Framework to replace exit/quit?
Thanks in advance.

**Comment by narfbg** [comment]
This is the CI3 repository and we only deal with bug reports here anyway. You should ask on the [forums](https://forum.codeigniter.com/) instead.

**Comment by sunlane880** [comment]
[The Thread](https://forum.codeigniter.com/thread-80620.html)

**Comment by yongplus** [comment]
[The Thread](https://forum.codeigniter.com/thread-80620.html)
