### ISSUE TITLE
Argument Types for Validation Rules

### ISSUE THREAD

**Issue by donpwinston** [bcit-ci/CodeIgniter#6079]
I created the following rule:

`public function not_blocked(int $mebn_seq): bool
  {
    return !(new MebnDb())->isBlocked($mebn_seq);
  }`

It errored because $mebn_seq is declared as an int. I had to declare it as  'string' and cast my argument using (int):
`return !(new MebnDb())->isBlocked((int)$mebn_seq);`

I don't believe I should have to do this.

**Comment by gxgpet** [comment]
Hello!

We are using GitHub for tracking bugs and issues related to CI 3 itself. Please use our [forums](https://forum.codeigniter.com/) if you need help with your project.
