### ISSUE TITLE
Migration Library for php >=8.0 is not working properly

### ISSUE THREAD

**Issue by KNobHack** [bcit-ci/CodeIgniter#6080]
Migration library not detect up or down method when running Migration::version() function with PHP >=8.0.
I shows error like this
```
ERROR: An Error Was Encountered
        The migration class "Migration_[migration name]" is missing an "up" method.
```
when i'm indeed have up method in my migration.

I tried using php 7.4 and no error encountered.

The problem was in condition for checking method exist with is_callable() (Migration.php line 291)
```
elseif ( ! is_callable(array($class, $method)))
 {
    $this->_error_string = sprintf($this->lang->line('migration_missing_'.$method.'_method'), $class);
    return FALSE;
}
```

PHP 8 handle is_callable() slightly different mentioned [here](https://www.php.net/manual/en/function.is-callable.php#126199)

**Comment by kenjis** [comment]
See 0925b5099919300a239909588351a6482c5e792d

**Comment by KNobHack** [comment]
> See [0925b50](https://github.com/bcit-ci/CodeIgniter/commit/0925b5099919300a239909588351a6482c5e792d)

Thank you. Sorry i did not notice that
