### ISSUE TITLE
CI will not run validation on an empty array if method is not POST

### ISSUE THREAD

**Issue by jamieburchell** [bcit-ci/CodeIgniter#6087]
Because of [this condition](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Form_validation.php#L164) it's not possible to run the validation rules on an empty array unless the request method is a POST.

Consider:

```
$rules = [
	[
		'field' => 'i_am_required',
		'label' => 'Some label',
		'rules' => 'trim|required|integer'
	]
];

$this->load->library('form_validation');
$this->form_validation->set_data([]);

if (! $this->form_validation->run($rules)) {
	// If HTTP POST, we land here, with error messages
	// If HTTP GET, we land here, no error messages
}
```

I don't think the request method should come in to play here.

**Comment by narfbg** [comment]
Well, you may not think that way, but it is so intentionally.

**Comment by jamieburchell** [comment]
Useful comment

**Comment by jamieburchell** [comment]
The entire purpose of the `set_data`  method is to validate something other than POST, so I don't see how the request method is relevant when using it.

This behaviour is not consistent, it's unexpected and I don't believe it's documented, so I would have appreciated some elaboration on why this is intentional and not a bug.

**Comment by narfbg** [comment]
It's an empty array, there's no data in it, there's nothing to validate - this is obvious.

And furthermore, don't expect that someone would give you an elaborate explanation when all you've said is "I disagree with this". I don't even know what you want to be explained. Why would you want to attempt to validate something that doesn't exist?

**Comment by jamieburchell** [comment]
I believe the original post explains this and demonstrates the inconsistent behaviour.

If I pass an empty array to `set_data` it should behave the same as when `$_POST` is empty, but it does not.

Don't forget that while the data might be empty, required validation rules should still be checked, like they are for `$_POST`.

If you need a concrete use case, I wanted to validate that certain URL parameters are present and meet certain validation rules. I passed the equivalent of `$_GET` to `set_data`, and found the validation library behaves differently (i.e. the rules are not checked) unless the request method is POST.
