### ISSUE TITLE
on CI3_develop see  Session_driver  and php8.1

### ISSUE THREAD

**Issue by DEV-byoos** [bcit-ci/CodeIgniter#6097]
Hi,
I specify that I have just installed codeIgniter3_develop and php8.1 on an application coded in ci3.1.10.

I have a small error message on the script
system/libraries/Session/Session_driver.php
Severity: 8192

Message: setcookie(): Passing null to parameter #2 ($value) of type string is deprecated

Filename: Session/Session_driver.php

line 156 replace #2 of null to '' type string
		return setcookie(
			$this->_config['cookie_name'],
			'',// correctif
			array(
				'expires' => 1,
				'path' => $this->_config['cookie_path'],
				'domain' => $this->_config['cookie_domain'],
				'secure' => $this->_config['cookie_secure'],
				'httponly' => TRUE,
				'samesite' => $this->_config['cookie_samesite']
			)

I hope this will help!!!
best regard
Gabriel

Translated with www.DeepL.com/Translator (free version)

**Comment by jamieburchell** [comment]
See https://github.com/bcit-ci/CodeIgniter/pull/6096
