### ISSUE TITLE
docs, partial changes on function desc

### ISSUE THREAD

**Issue by sukrosono** [bcit-ci/CodeIgniter#6099]
i like to make a PR which add more details on the PHP doc, ie:

```
/**
	 * JOIN
	 *
	 * Generates the JOIN portion of the query
	 *
	 * @param	string
	 * @param	string	the join condition
	 * @param	string	the type of join (NATURAL|LEFT|RIGHT|FULL|INNER|OUTER)
	 * @param	string	whether not to try to escape identifiers
	 * @return	CI_DB_query_builder
	 */
```

is that more readable? if so, I just make PR for a single func desc, please let me know if it was just not worth doing.

**Comment by narfbg** [comment]
Some might find it more informative, I don't. But I have to reject this for a different reason entirely - it sets a verbose standard that also invites all possible combinations (e.g. `LEFT OUTER`) to be listed as well and that's just ... no.
