### ISSUE TITLE
CodeIgniter3 User Guide Docs Broken

### ISSUE THREAD

**Issue by JonnoFTW** [bcit-ci/CodeIgniter#6108]
Trying to access userguide3 documentation results in many 404 errors.

For example, going to this page: https://www.codeigniter.com/userguide3/ results in no styles or scripts loading. 

Clicking the links on the page leads to more 404 errors.

The same occurs when accessing pages that are linked from google: https://codeigniter.com/userguide3/installation/index.html

**Comment by narfbg** [comment]
Yes, something went wrong with the release ... working on it.

**Comment by lonnieezell** [comment]
This has been fixed.
