### ISSUE TITLE
3.1.13 user guide missing from packagist & release tarballs/zip

### ISSUE THREAD

**Issue by tenzap** [bcit-ci/CodeIgniter#6110]
There is no more user_guide dir in the release tarball, neither in the package fetched from packagist with composer ?

Is it in a new package?

**Comment by narfbg** [comment]
This is the unfortunate result of #5859. In [my comment there](https://github.com/bcit-ci/CodeIgniter/pull/5859#issuecomment-548738856) I'd concluded that this would be fine, but evidently I didn't test the downloads here, just the tag itself.

I'm afraid that reverting this at this point isn't worth it - much fewer people would rely on the in-archive docs compared to those who'd get needless extra traffic with their composer downloads. You can still directly pull the tag if you need though, it should appear there.

**Comment by tenzap** [comment]
Ok thanks. I was actually wondering if it would reappear in future. Apparently not. No problem.
