### ISSUE TITLE
CI 3.1.13 with PHP 8.1 - Errors in helpers using str_replace if empty string passed in

### ISSUE THREAD

**Issue by alixbergeret** [bcit-ci/CodeIgniter#6111]
This is regarding CodeIgniter 3.1.13, running on PHP 8.1

In PHP 8.1, functions such as str_replace() and trim() can no longer accept an empty string (which I find a bit strange). I have attached the error, I was trying to call the quotes_to_entities() helper with an empty string.

<img width="359" alt="error" src="https://user-images.githubusercontent.com/1101864/156810499-8a4b9049-5b02-40af-8d75-0419a247f03a.png">

A simple fix would be to deal with this case in the code, for example:
```
	function quotes_to_entities($str)
	{
		if($str == '')
			return $str;
		else
			return str_replace(array("\'","\"","'",'"'), array("&#39;","&quot;","&#39;","&quot;"), $str);
	}
```

It needs doing across the board obviously.

**Comment by madwings** [comment]
You can call them with an empty string without a problem. You cannot call them with anything else. In your case, you call `quotes_to_entities(null)`. Just call it with a string `quotes_to_entities((string) $str)`.

**Comment by gxgpet** [comment]
> You can call them with an empty string without a problem

That's very true. And according to the [helper's docs](https://codeigniter.com/userguide3/helpers/string_helper.html#quotes_to_entities), you shouldn't pass anything else than a string to that parameter.
