### ISSUE TITLE
I'm getting the Session_database_driver  command out of sync error

### ISSUE THREAD

**Issue by ibrcan** [bcit-ci/CodeIgniter#6115]
What can I do 
> Commands out of sync; you can't run this command now
UPDATE `ci_sessions` SET `timestamp` = 1647410318 WHERE `id` = 'rtfs61als636j9paq0rafup5mlb5bhg9'

**Comment by wysiwyg-data** [comment]
Hi ibrcan,
Just joined the discussion today and saw your post.
Have you solved the issue?
