### ISSUE TITLE
PHP 8.1 warning in core/URI.php

### ISSUE THREAD

**Issue by pyerro** [bcit-ci/CodeIgniter#6120]
CI 3.1.13 is working with PHP 8.0.3 like a charm. With PHP 8.1.4 I get this error:

Message: ltrim(): Passing null to parameter #1 ($string) of type string is deprecated
Filename: core/URI.php
Line Number: 641

Original:
`return ltrim(load_class('Router', 'core')->directory, '/').implode('/', $this->rsegments); `

Possible fix:
`return ltrim((string) load_class('Router', 'core')->directory, '/').implode('/', $this->rsegments); `

**Comment by RedDragonWebDesign** [comment]
Possibly related #6117

**Comment by gxgpet** [comment]
Yes, a duplicate of #6117.
