### ISSUE TITLE
Fix for OCI8 TO_DATE for CI3

### ISSUE THREAD

**Issue by joshuadave143** [bcit-ci/CodeIgniter#6135]
Good day to all

I just want to share my quick fix for inserting data with TO_DATE.

When you insert data like this code below 
<pre>
$data = array(
        'title' => 'My title',
        'name' => 'My Name',
        'date' =>"TO_DATE('08-JUN-22', 'DD/MON/RR')"
);

$this->db->insert('mytable', $data);
// Produces: INSERT INTO mytable (title, name, date) VALUES ('My title', 'My name', 'TO_DATE("08-JUN-22", "DD/MON/RR")')
</pre>
they add single quote in TO_DATE("08-JUN-22", "DD/MON/RR") and it will cause oracle error.

so what I did is that I modified DB_query_builder.php in line 1320
I add below code inside foreach ($key as $k => $v)
<pre>
        if(strtolower($this->dbdriver) == 'oci8'){
		if( strstr(strtolower($v), 'to_date' )){
			$escape_v = $v;

		}else{
			$escape_v =  $this->escape($v);
		}
	}
	else{
		$escape_v =  $this->escape($v);
	}
</pre>
and change this code 

 <pre>$this->qb_set[$this->protect_identifiers($k, FALSE, $escape)] = ($escape)? $this->escape($v) : $v;</pre>

 to 
  <pre>$this->qb_set[$this->protect_identifiers($k, FALSE, $escape)] = ($escape) ?$escape_v : $v;</pre>

with this modification I fix my problem of OCI8

sorry for my bad English and grammar

**Comment by gxgpet** [comment]
Sorry, but this is not the proper way to handle such situations.

Besides your code handling only the `TO_DATE` Oracle function, it also brings driver-specific code in the `CI_DB_query_builder` class.

The `insert` method cannot possibly deal with all combinations of queries. For such cases, there's the generic `->query()` method.
