### ISSUE TITLE
Error when install dependencies on Codeigniter 3 via composer

### ISSUE THREAD

**Issue by radenrap** [bcit-ci/CodeIgniter#6137]
Good day to all.

I've tried to install some dependencies via composer on my new codeigniter 3.1.13 project.
I think all list package on my composer.json has been installed, but i found error at the last messege.
I using MAMP as local web server, anyone can help my problem, please.
Thank you.
<img width="646" alt="Screen Shot 2022-06-14 at 3 24 25 AM" src="https://user-images.githubusercontent.com/24818437/173439085-89426717-d0c8-4738-b23a-6722e5ebad40.png">
<img width="567" alt="Screen Shot 2022-06-14 at 3 23 31 AM" src="https://user-images.githubusercontent.com/24818437/173439111-e1f46036-37b3-4821-9965-bf169425617a.png">

**Comment by gxgpet** [comment]
It seems that you are copying and pasting the `composer.json` file from the CodeIgniter's base code, and then modifying it.

I'm not sure what you are trying to do, but simply running `composer require codeigniter/framework` on an empty directory should work without any issue. Script commands do not run when using `codeigniter/framework` as a dependency.

**Comment by radenrap** [comment]
I've tried to install new codeigniter's base code from packagist.org and I found error too.

<img width="565" alt="Screen Shot 2022-06-14 at 2 33 39 PM" src="https://user-images.githubusercontent.com/24818437/173520641-d7142d96-9a6c-4374-b419-4a499e78a455.png">

**Comment by gxgpet** [comment]
You are either not using `composer require`, just as I mentioned before, or you are using a composer.json file that is populated with data already. Scripts are not being run when [the package is a dependency](https://getcomposer.org/doc/articles/scripts.md).

In any case, we are using GitHub Issues to track bugs and problems related to the CodeIgniter framework itself. If you have any problems with your own project, you may use our forums or even GitHub Discussions.

Last (but not least), kindly please do not post screenshots of _text outputs_.
