### ISSUE TITLE
syntax error, unexpected '_592_000' (T_STRING), expecting ',' or ')' in

### ISSUE THREAD

**Issue by CorruptKubCzh** [bcit-ci/CodeIgniter#6138]

**Comment by CorruptKubCzh** [comment]
在 centos 7 中出现了 yntax error, unexpected '_592_000' (T_STRING), expecting ',' or ')' in /var/www/html/ 这个错误

**Comment by darkterminal** [comment]
can you give the complete error?

**Comment by CorruptKubCzh** [comment]
我只在我的error_log 看到了这个错误
[php7:error] [pid 15453] [client 87.200.19.209:53654] PHP Parse error:  syntax error, unexpected '_592_000' (T_STRING), expecting ',' or ')' in /var/www/html/telegram-bot/app/Config/Constants.php on line 41

，浏览器上是 下图这样的
![image](https://user-images.githubusercontent.com/22706798/174424521-37157e14-0224-41a9-b1ea-c4491a05f6d1.png)

**Comment by darkterminal** [comment]
Which version CodeIgniter you used? I think you in wrong thread, in CodeIgniter3 using `application` folder and CodeIgniter4 using `app`. Or try visit this link for more info [Codeigniter blank page and error 500 in apache log?](https://stackoverflow.com/questions/15588813/codeigniter-blank-page-and-error-500-in-apache-log)

**Comment by kenjis** [comment]
It seems you are using CI4 and your PHP version is too old.
Use PHP 7.4 or later.
