### ISSUE TITLE
Redis Driver Error

### ISSUE THREAD

**Issue by motoroller1983** [bcit-ci/CodeIgniter#6141]
A PHP Error was encountered

Severity: 8192

Message: Redis::connect(): Passing null to parameter #3 ($timeout) of type float is deprecated

Filename: drivers/Session_redis_driver.php

Line Number: 181

**Comment by digitalinaja** [comment]
this bug is still exist, because the error message is : Redis::connect(): Passing null to parameter #3 ($timeout) of **type float** is deprecated

**Comment by digitalinaja** [comment]
[3efe7f0](https://github.com/bcit-ci/CodeIgniter/commit/3efe7f0d070ad530208ea4f732708c1e660df0a7) only solve NULL depracated, not float
