### ISSUE TITLE
Version 3.1.13 is the last version of CI3?..

### ISSUE THREAD

**Issue by gyveryeoh** [bcit-ci/CodeIgniter#6145]
Just want to know if codeigniter3.1.13 is still usefull until now?.. im using vps with 7.4 version.
I am still maintaning almost 5-8 systems with C.I3 version. im afraid if one day my clients encountered an errors or glitches while using the system with C.I 3 version.

**Comment by gxgpet** [comment]
Hi!

Yes, we are still maintaining CI 3.

If you encounter any issues, just let us know.
