### ISSUE TITLE
如果入参里面包含 单引号   这里会导致 单引号的 *2   举个栗子  正常入参是   abc'123  经过 _escape_str 处理之后就会变成 abc''123  最终入库也就变成了  abc''123

### ISSUE THREAD

**Issue by Jizekun** [bcit-ci/CodeIgniter#6162]
https://github.com/bcit-ci/CodeIgniter/blob/9b8f2b7a8405acd1b8ad5956ada3d84472b1e8ae/system/database/DB_driver.php#L1135

**Comment by gxgpet** [comment]
Hello!

Please use English when reporting issues here.
Also, any bug reports should include a snippet of code (or at least some reproduction steps), so we can actually verify the issue.
