### ISSUE TITLE
404 by clicking "User Guide"

### ISSUE THREAD

**Issue by danilort** [bcit-ci/CodeIgniter#6169]
Hello,
nothing serious.

On the page: https://github.com/bcit-ci/CodeIgniter
paragraph: Resources
the URL of "User Guide", is wrong (error 404)

**Comment by carlosdoub** [comment]
I would add that, it would be great if there were a release of the downloadable user guide.

Like there is on CI4: 
https://github.com/codeigniter4/userguide/releases

Thanks!

**Comment by gxgpet** [comment]
We will think about your suggestion as well, @carlosdoub.

Thanks!
