### ISSUE TITLE
Release new version with fixes for php 8.1 & 8.2

### ISSUE THREAD

**Issue by tenzap** [bcit-ci/CodeIgniter#6170]
I'm trying to get codeigniter 3.1 enter Debian as an official package.

Next stable version of Debian is likely for S1/2023 and freeze will likely begin Jan/2023.
It is supposed to ship with PHP 8.2 which should be released by then end of nov/2022. (Currently Debian testing runs php 8.1)

Could a new version of CI3 be released soon with fixes so that it can run on PHP-8.1 & PHP-8.2?

**Comment by tenzap** [comment]
@gxgpet

**Comment by tenzap** [comment]
@narfbg

**Comment by gxgpet** [comment]
Hi!

I will try to set things to get going in this weekend.

**Comment by MichalSkoula** [comment]
Support for PHP 7.4 ended today. Will there be a version supporting PHP 8?

https://endoflife.date/php

**Comment by gxgpet** [comment]
Hi! 

We already support PHP versions up to 8.1. This is actually how the pipelines are running.

I understand that there were some bug reports lately opened, so I will look at them these days. And then we shall release a version containing the bug fixes, but also add the support for PHP 8.2.

Sorry for this delay, and thanks again!

**Comment by MichalSkoula** [comment]
I really appreciate all the work. But do you know roughly when the new stable version will be released?
