### ISSUE TITLE
$this->uri->ruri_string() generates error message in PHP 8.1

### ISSUE THREAD

**Issue by Kenqr** [bcit-ci/CodeIgniter#6175]
The following code
```php
public function ruri() {
    echo $this->uri->ruri_string();
}
```

generates this error message in php 8.1:
```
A PHP Error was encountered
Severity: 8192

Message: ltrim(): Passing null to parameter #1 ($string) of type string is deprecated

Filename: core/URI.php

Line Number: 641

Backtrace:

File: C:\project\path\application\controllers\Test.php
Line: 91
Function: ruri_string

File: C:\project\path\index.php
Line: 320
Function: require_once
```

This also affects other functions that use ruri_string, like `$this->form_validation->run()`

**Comment by bgougent** [comment]
Global question - will CI3 be tested against php 8.1 and updated?

File : sys/core/URI.php :: 639
Changed the function with this code

$value = load_class('Router', 'core')->directory;
return empty($value) ? '' : ltrim(load_class('Router', 'core')->directory, '/').implode('/', $this->rsegments);

**Comment by Tampa** [comment]
I would hope it would be getting some love with 8.1 potentially making a few things a bit simpler to achieve. CI4 has failed to grow on me, I still prefer 3.

**Comment by Gary1712** [comment]
in Xmlrpc.php

Change to somthing like this

$the_parser = (string) empty((array) $the_parser)?'' :$the_parser;

**Comment by marcelod** [comment]
I resolved with this

return ltrim(load_class('Router', 'core')->directory ?? '', '/').implode('/', $this->rsegments);
