### ISSUE TITLE
SSL Database Error: MYSQLi was configured for an SSL connection, but got an unencrypted connection instead!

### ISSUE THREAD

**Issue by drkNsubuga** [bcit-ci/CodeIgniter#6212]
# Introduction
I encountered a persistent error when connecting to a [Planetscale](planetscale.com) database which requires the SSL_CA to be provided as part of the connection string.  
## The error
> MYSQLi was configured for an SSL connection, but got an unencrypted connection instead!
Filename: system/database/drivers/mysqli/mysqli_driver.php
Line Number: 223

This error also occurs when the **pdo driver** is used with a correct mysql dsn string
> PDO_MYSQL was configured for an SSL connection, but got an unencrypted connection instead!
Filename: system/database/drivers/pdo/subdrivers/pdo_mysql_driver.php
Line Number: 191

## Environment
- PHP 8.2.3
- Codeigniter 3.1.13

## What I resolved
The error disappeared after changing this snippet
```php
// Prior to version 5.7.3, MySQL silently downgrades to an unencrypted connection if SSL setup fails
:
:
version_compare($this->_mysqli->client_info, '5.7.3', '<=')
```
to 
```php
version_compare($this->_mysqli->server_info, '5.7.3', '<=')
```
This change was suggested in the [codigniter forum](https://forum.codeigniter.com/post-329024.html) but wasn't responded to. 
## Question
1. Is the fix valid and safe?
2. Could the issue be at the database provider's end?

****Note:** This is the first time I encountered this error for a db configured with SSL.

**Comment by zulfirman** [comment]
I'm also encountering this issue, it works fine using the planetscale sample code without any framework to connect the database.

**Comment by drkNsubuga** [comment]
Did you resolve it?.
