### ISSUE TITLE
CodeIgniter Forums - Cannot Register

### ISSUE THREAD

**Issue by andrew-lim** [bcit-ci/CodeIgniter#6224]
Try going to the following URL, click on Agree. The "Submit Registration!" button on the next page does not do anything.
https://forum.codeigniter.com/member.php?action=register

Also there is a captcha error on the bottom right of the page that says "This site key is not enabled for the invisible captcha."

**Comment by lonnieezell** [comment]
Sorry about that. Should be all fixed up now. Thanks for reporting it!
