### ISSUE TITLE
CodeIgniter + Session usage with Redis is slow

### ISSUE THREAD

**Issue by El-Tommy** [bcit-ci/CodeIgniter#6233]
I'm migrating my application with CodeIgniter 3 to use Redis as a session manager, but as the app makes many requests in AJAX I noticed that they tend to take longer, 11 requests that in all took 300ms (sessionHandler=files) now take 11s (sessionHandler=redis).

I made some code changes to get all sessions at the beginning of each controller, put the values in a model and after that I run `session_write_close(`).

The request time even improved, lowering the time to an average of 3 - 5s, but far from ideal.

Reading the CodeIgniter documentation I saw this:

>  CodeIgniter’s Session library does NOT use the actual ‘redis’ session.save_handler.

With that I decided to disable the autoload of the native CodeIgniter session and directly use the `session_start()` at the beginning of the Controllers before getting the session values and feeding my Model.

To my surprise, the application load the data again in less than 300ms. And even not using `session_write_close() anymore`, it still continued at the same speed.

What could be happening with CodeIgniter that makes it take longer to connect and read the session in Redis?

Both CI and PHP are configured with Redis as the session manager.

Version:
CodeIgniter 3.1.13
PHP 7.4
Redis 7

**Comment by bunglegrind** [comment]
maybe this is related:

https://github.com/bcit-ci/CodeIgniter/issues/6157

**Comment by El-Tommy** [comment]
From what I understand the CI does its own session lock treatment, correct?

Can I then use PHP's default session_start() instead of using the CI or will that cause a problem?

I only set sessions at login time, otherwise I don't change them.

**Comment by bunglegrind** [comment]
Correct, the problem is the fixed long interval (1 second). Default interval for the PHPRedis driver is 20 ms...
You have two alternatives:
1. Extend (or edit...) the CI Session redis driver in order to customize the lock polling timeout to a more reasonable smaller value (in case, follow what I wrote in #6157 and substitute sleep with usleep)
2. dealing with sessions outside the framework. That is, use $_SESSION, the phpredis settings in php.ini etc..

**Comment by El-Tommy** [comment]
The "problem" was resolved by not using CodeIgniter sessions.
I had to remove it from autoload and use the standard PHP `session_start()`.
