### ISSUE TITLE
Drop support for PHP < 8.1

### ISSUE THREAD

**Issue by tbreuss** [bcit-ci/CodeIgniter#6241]
Sorry, but is this a joke?

https://github.com/bcit-ci/CodeIgniter/blob/develop/composer.json#L14

Who needs support for PHP 5.4?

Soon, PHP 8.0 will be EOL and 8.3 will be available. What is the roadmap in terms of support for old/new PHP versions?

**Comment by jamieburchell** [comment]
I believe when CI3 was released nearly a decade ago PHP 5.4 was still a thing and it's always been the case that CI tried to cater for a wide range of versions and to not introduce breaking changes. That said, new development on CI3 looks to have almost completely stopped - it's on life support and as far as I'm concerned shouldn't even be considered for new projects. Use something else like CI4 or Laravel.

**Comment by visserrobin** [comment]
The main reason I am still using CI3 is that one of my (huge) projects is running on a (local intranet) server with PHP 5.6.40. There are other projects running on that server which rely on 5.6.40, so it is not my decision to update PHP to a newer version. 

Any new projects I develop in CI4.

**Comment by tbreuss** [comment]
BTW I filed the issue because I wasn't aware that this is not the CI main repo. So, sorry for that. 

Therefore it could be a good idea to place a comment somewhere in the Readme that this is CI3 and not 4. And maybe one could remove the link to CI4. This would make the situation much clearer.

**Comment by gxgpet** [comment]
> This would make the situation much clearer.

I don't even know what to say... did you open the issue by just checking the composer.json file? Unless you never used any of CodeIgniter's versions, the difference between the repos can be easily found by checking at least one (and maybe even any of) PHP source file, in my opinion.

**Comment by tbreuss** [comment]
> > This would make the situation much clearer.
> 
> I don't even know what to say... did you open the issue by just checking the composer.json file? Unless you never used any of CodeIgniter's versions, the difference between the repos can be easily found by checking at least one (and maybe even any of) PHP source file, in my opinion.

There is not a single word about version 3 in your README and a prominent link to https://codeigniter.com/userguide3/ would definitely make things clearer.

And by the way, I wanted to use CI for a new project, but starting like this? No way.

And sorry again, PHP version 5.4 is end of life since 2015. Ridiculous.

PS: You should add a topic "php5".

**Comment by kenjis** [comment]
@tbreuss CI3 is the legacy version.
See the latest version. https://github.com/codeigniter4/CodeIgniter4

**Comment by gxgpet** [comment]
It's okay people, you are not the first ones throwing darts at the "legacy" version of the CI. And probably you won't be even the last ones.

> There is not a single word about version 3 in your README and a prominent link to https://codeigniter.com/userguide3/ would definitely make things clearer.

So have you checked out the "Installation" section of Readme.md? It's just the little effort I was asking about...

> And sorry again, PHP version 5.4 is end of life since 2015. Ridiculous.

I don't see how this impacting the usage of the framework. You are just saying _something_ is EOL. You are free to use any level of the PHP features in your own CI3 project and nothing would be wrong about that.

> PS: You should add a topic "php5".

Oh, another dart.

**Comment by tbreuss** [comment]
I'm not willing to inspect the Readme's source code to find information about a version of the product.

Is it ~~so difficult~~ such a bad idea to add a sentence at the top of the page that says, this is version 3 and the legacy version of CI?

People are coming from Google etc. and are maybe newbies to CI.

> @tbreuss CI3 is the legacy version. See the latest version. https://github.com/codeigniter4/CodeIgniter4

And maybe adding a link to the current repo?

**Comment by kenjis** [comment]
@tbreuss Thank you for your suggestion!
I sent a PR #6266

**Comment by tbreuss** [comment]
> @tbreuss Thank you for your suggestion! I sent a PR #6266

Thanks and sorry for the noise
