### ISSUE TITLE
Upcoming deprecations in PHP 8.3

### ISSUE THREAD

**Issue by tenzap** [bcit-ci/CodeIgniter#6244]
There will be new deprecations in PHP 8.3

https://wiki.php.net/rfc/deprecations_php_8_3

Apparently CI3 is impacted at least for the `mt_rand`/`rand` changes.

**Comment by jamieburchell** [comment]
I think only the constant `MT_RAND_PHP` is proposed to be deprecated. Deprecation of `rand()` functions was voted against 16 - 13.

**Comment by gxgpet** [comment]
Yes, indeed.

I will have a look over PHP's upgrading docs and come up with any pull requests, if needed, for the new version.
