### ISSUE TITLE
Codeigniter 3.1.4 and PHP 8.1

### ISSUE THREAD

**Issue by yab86** [bcit-ci/CodeIgniter#6245]
I am getting several error messages while running my script. By far, I am not an expert but I am not able to fix it. It seems like an issue due to PHP 8.1 for me.

Severity:    8192
Message:     str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated
Filename:    /myproject/system/core/Output.php
Line Number: 447

Backtrace:
	File: /myproject/index.php
	Line: 294
	Function: require_once

PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /myproject/system/libraries/Profiler.php on line 108

Fatal error: Array and string offset access syntax with curly braces is no longer supported in /myproject/system/libraries/Profiler.php on line 108

A PHP Error was encountered

Severity:    Compile Error
Message:     Array and string offset access syntax with curly braces is no longer supported
Filename:    /myproject/system/libraries/Profiler.php
Line Number: 108

**Comment by bunglegrind** [comment]
https://github.com/bcit-ci/CodeIgniter/issues/5879

use CI latest version (3.1.13 at the moment)

**Comment by rikrdolavin** [comment]
Maybe it would be a good idea to migrate to CI4 since you are using PHP 8.1

**Comment by mariolucasdev** [comment]
the version 3.1.13 is compatible with php 8.1. I have 2 projects working very well with these especifications.

**Comment by gxgpet** [comment]
Sorry, but I can't locate any of the mentioned lines/function calls by using the code from the develop branch... If you will point them by using a GitHub link to the actual lines, I will have a look at them.
