### ISSUE TITLE
is_unique validation not working

### ISSUE THREAD

**Issue by nikoskip** [bcit-ci/CodeIgniter#724]
Hi,

I recently update my CodeIgniter from 2.0.2 to 2.1 because I need to use is_unique validation (from Form_validation.php), but is not working for me. The code:

Controller:
$this->form_validation->set_rules('email', 'E-mail', 'required|valid_email|is_unique[persona.email]');

View error msg:

A PHP Error was encountered

Severity: Notice

Message: Undefined property: Usuarios::$db

Filename: libraries/Form_validation.php

Line Number: 954

Fatal error: Call to a member function limit() on a non-object in C:\xampp\htdocs\st\system\libraries\Form_validation.php on line 954

-----------

The problem is with the DB object. It seems that it not properly implemented on CI instance.

PHP Version: 5.3.0
Plataform: Windows

**Comment by jony1234** [comment]
I had same problem, with in method is_unique, I solved in MY_Form_validaiton, only copy original method and row return isset($this->CI->db) ? ... changed to $this->CI->db (library database is autouploaded), it works

**Comment by dominservice** [comment]
Hello,I have a Codeigniter 3.0.6. I have a similar problem, but for me there is an error when loading languages in form_validation.

`Fatal error: Call to a member function load() on a non-object in /home/dominservizo/ftp/DSO_CRM_CARGO/system/libraries/Form_validation.php on line 450

Warning: include(application/views/errors/html/error_php.php): failed to open stream: No such file or directory in /home/dominservizo/ftp/DSO_CRM_CARGO/system/core/Exceptions.php on line 269

Warning: include(): Failed opening 'application/views/errors/html/error_php.php' for inclusion (include_path='.:/usr/share/pear/') in /home/dominservizo/ftp/DSO_CRM_CARGO/system/core/Exceptions.php on line 269

Warning: include(application/views/errors/html/error_php.php): failed to open stream: No such file or directory in /home/dominservizo/ftp/DSO_CRM_CARGO/system/core/Exceptions.php on line 269

Warning: include(): Failed opening 'application/views/errors/html/error_php.php' for inclusion (include_path='.:/usr/share/pear/') in /home/dominservizo/ftp/DSO_CRM_CARGO/system/core/Exceptions.php on line 269

Warning: include(application/views/errors/html/error_php.php): failed to open stream: No such file or directory in /home/dominservizo/ftp/DSO_CRM_CARGO/system/core/Exceptions.php on line 269

Warning: include(): Failed opening 'application/views/errors/html/error_php.php' for inclusion (include_path='.:/usr/share/pear/') in /home/dominservizo/ftp/DSO_CRM_CARGO/system/core/Exceptions.php on line 269`

In the library, I have such a rule:
`$this->CI->form_validation->set_rules('DSOfirstname', 'Imię', 'required');
		$this->CI->form_validation->set_rules('DSOlastname', 'Nazwisko', 'required|min_length[2]|max_length[50]');
        $this->CI->form_validation->set_rules('DSOemail', 'E-mail', 'required|max_length[70]|valid_email|is_unique[dso_user_email.email]');
		$this->CI->form_validation->set_rules('DSOuser', 'Nazwa użytkownika', 'required|min_length[6]|max_length[50]|is_unique[dso_user.username]');
		$this->CI->form_validation->set_rules('DSOpass', 'Hasło', 'required|min_length[6]|max_length[50]');
		$this->CI->form_validation->set_rules('DSOrpass', 'Powtórz hasło', 'required|max_length[50]|matches[DSOpass]');
		$this->CI->form_validation->set_rules('DSOcompany', 'Nazwa firmy', 'required|max_length[50]');
		$this->CI->form_validation->set_rules('DSOnip', 'NIP firmy', 'required|numeric|is_unique[dso_company.tax_identification_nr]');//min_length[10]|max_length[11]|
		$this->CI->form_validation->set_rules('DSOregon', 'REGON', 'numeric|is_unique[dso_company.regon]');
		$this->CI->form_validation->set_rules('DSOaddress', 'Adres Firmy', 'required|min_length[6]|max_length[150]');
		$this->CI->form_validation->set_rules('DSOcity', 'Poczta', 'required|min_length[3]|max_length[50]');
		$this->CI->form_validation->set_rules('DSOcountry', 'Państwo', 'required|min_length[3]|max_length[80]');
		$this->CI->form_validation->set_rules('DSOterms_and_conditions', 'Regulamin', 'required');`

Seeking solutions for a few days and I can not deal with it
What could be causing this?

**Comment by jim-parry** [comment]
@dominservice This is a thread from 2011, originally referring to CI2. Why are you posting here???
Post your question on our forum instead - github is for bug tracking in the current version of CodeIgniter.
