### ISSUE TITLE
CI's session handling not working in WebKit browsers and IE

### ISSUE THREAD

**Issue by jamesgifford** [bcit-ci/CodeIgniter#744]
Data stored using CodeIgniter's session library is not persisted between requests in browsers other than Firefox.

To recreate this problem install a fresh copy of CI 2.1.0, add an encryption key to application/config/config.php, then add the following three lines to the constructor of application/controllers/welcome.php:

<pre>
$this->load->library('session');
$session_id = $this->session->userdata('session_id');
echo "My Session ID is $session_id";
</pre>

Viewing this page in a browser should display the current session id and this id should remain the same if the page is reloaded. However, in Safari, Chrome, and IE reloading the page causes the session id to change. Something in the way CodeIgniter stores session data is triggering the session id to change which means any data stored in the session cannot be persisted from one request to the next.

Please note that no changes were made to the default CI installation other than those mentioned above. This means that the database schema which was changed in CI 2.0.3 is not the cause of this issue. Furthermore, if logging is enabled then the following entry is made to the log file after instantiating the database driver class

<pre>
DEBUG - 2011-12-06 00:35:01 --> A session cookie was not found.
</pre>

Since the default session setup does work in Firefox (version 8 at least) then the cause of this problem is probably related to the user agent value.

**Comment by itskawsar** [comment]
I also faced the same problem. My Session was destroying on redirect after successful login. I have tried all of suggestions in this issue.
I have tested in with following environment:
**PHP Version:** 5.6.3
**System:** Windows NT build 9200 (Windows 8.1 Business Edition) i586
**Architecture:** x86
**Apache Version:** Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3
**MySQL version:** mysqlnd 5.0.11-dev - 20120503
**Browser:** *Chrome 40.0.2214.93 m* and *IE 11.0.9600.16663*

After lot of test i found the session is not started. When i use `session_start()`, i got all values inside session. So i added following code to `index.php`:

	if (version_compare(PHP_VERSION, '5.4.0', '<')) {
	    if(session_id() == '') session_start();
	} else  {
	   if (session_status() == PHP_SESSION_NONE) session_start();
	}

and it's working :)

**Comment by alamops** [comment]
@itskawsar 
Well, I didn't think it and I will try it.
Thank you!

**Comment by blissville** [comment]
> I also faced the same problem. My Session was destroying on redirect after successful login. I have tried all of suggestions in this issue.
> I have tested in with following environment:
> **PHP Version:** 5.6.3
> **System:** Windows NT build 9200 (Windows 8.1 Business Edition) i586
> **Architecture:** x86
> **Apache Version:** Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3
> **MySQL version:** mysqlnd 5.0.11-dev - 20120503
> **Browser:** _Chrome 40.0.2214.93 m_ and _IE 11.0.9600.16663_
> 
> After lot of test i found the session is not started. When i use `session_start()`, i got all values inside session. So i added following code to `index.php`:
> 
> ```
> if (version_compare(PHP_VERSION, '5.4.0', '<')) {
>     if(session_id() == '') session_start();
> } else  {
>    if (session_status() == PHP_SESSION_NONE) session_start();
> }
> ```
> and it's working :)

which of the index file please?
