### ISSUE TITLE
Character issue on Cart Class

### ISSUE THREAD

**Issue by bitbucket-import** [bcit-ci/CodeIgniter#78]
Hello,

I was itching my head when I was trying out the cart class. Because some products was added nicely, but some wouldn't at all. Without any error.

After some head scratching I found out that this line is the problem for us that lives in scandinavia, and possibly many other countries.

``` php
var $product_name_rules = '\.\:\-_ a-z0-9'; // alpha-numeric, dashes, underscores, colons or periods
```

located in system/libraries/Cart.php

The reason is we use ÆØÅ in our product names and therefor it will fail. 

So I suggest to add a config item that we can add local characters on and the CI_Cart can fetch those from there. Instead of "hacking the core". That's one option.

This is the working code for me.

``` php
var $product_name_rules = '\.\:\-_ a-zæøåÆØÅ0-9'; // alpha-numeric, dashes, underscores, colons or periods

```

Best regards
Anthoni Giskegjerde ( @antonigiske )

**Comment by ibadgore** [comment]
How about 
/*
		if ( ! preg_match("/^[".$this->product_name_rules."]+$/i", $items['name']))
		{
			log_message('error', 'An invalid name was submitted as the product name: '.$items['name'].' The name can only contain alpha-numeric characters, dashes, underscores, colons, and spaces');
			return FALSE;
		}
*/
