### ISSUE TITLE
PostgreSQL driver is incomplete

### ISSUE THREAD

**Issue by vespakoen** [bcit-ci/CodeIgniter#808]
I discovered that DBForge functions like `add_column`, `drop_column` didn't work with the postgres driver. (there's probably a good chance that others don't work too, but I did't have the time to look into this)
It looks like it is missing the _process_fields function that MySQL has for example.

If I find time I will look into this myself.

**Comment by mjmedmen** [comment]
I'm still seeing this error for modifying or adding columns using postgres 9.4
