### ISSUE TITLE
dbforge add_field shouldn't accept constraints for INT with sqlsrv

### ISSUE THREAD

**Issue by colonelchlorine** [bcit-ci/CodeIgniter#861]
Using sqlsrv (SQL Server 2008 database), when I tried the Migration library it fails to create the "migrations" table because of line 74:

``` php
$this->dbforge->add_field(array(
    'version' => array('type' => 'INT', 'constraint' => 3),
));
```

which generates the SQL equivalent

``` sql
CREATE TABLE IF NOT EXISTS migrations (
    version INT(3) NOT NULL
) 
```

SQL gives error: **Cannot specify a column width on data type int**

Removing the second parameter and leaving "'type' => 'INT'" works. Not sure if this is a problem with CodeIgniter's sqlsrv driver, or the dbforge library.

Additionally refer to github [issue #862](https://github.com/EllisLab/CodeIgniter/issues/862) because SQL also gives an error _Incorrect syntax near the keyword 'IF'._ Changing line 78 to the below line fixes this error.

``` php
$this->dbforge->create_table('migrations', false);
```

**Comment by jayjfletcher** [comment]
I believe this issue has been re-introduced. As all db_forge drivers are currently using the same _create_table function from the extended CI_DB_forge class.
