### ISSUE TITLE
get_dir_file_info() the return array's key needs to be unique

### ISSUE THREAD

**Issue by bitbucket-import** [bcit-ci/CodeIgniter#92]
The get_dir_file_info() function in the file helper has a bug in the return array being generated.

$file is being used as the return arrays key. But this in not unique enough in that If I have 2 similarly named files in different folders, the first files data is overwritten by the secong eg.

**I have the following files:**

assets\bingopizza_dbn\language\english\sitetext_lang.php

assets\bingopizza_dbn\language\spanish\sitetext_lang.php

**The english files data is missing.**

**If I call the function as per below:**

get_dir_file_info('assets\bingopizza_dbn\language\', $top_level_only = FALSE)

**The result returned is:**

Array
(
    [sitetext_lang.php] => Array
    (
        [name] => sitetext_lang.php
        [server_path] => ...assets\bingopizza_dbn\language\spanish\sitetext_lang.php
            [size] => 31
            [date] => 1285930111
            [relative_path] => ...assets\bingopizza_dbn\language\spanish\
    )
)

**Comment by gadelat** [comment]
My opinion is that this helper should not use filenames as keys. Accessing filename from array is easy enough even without this "feature". It should be changed to use numeric keys as is proposed by @Indigo74 . Yes, it will be BC-break. I still think this should be done.
